-- Source: reference/Final Fantasy Sound Sources (Detailed) - Final Fantasy VII.csv
-- Pilot batch for the FF Detailed family. Column-mapping rules and rationale
-- live in docs/ff-detailed-batch-plan.md (this is the first seed to populate
-- usages.sample_label and usages.sample_ref).
--
-- Two sections in the CSV:
--   Section 1 - Main Game Music (Sample 0 .. Sample 92)   → category 'main'
--   Demo Samples (Sample 0 .. Sample 12, described rows)  → category 'unused'
-- Blank-description Demo Samples rows (CSV rows 119-180) are dropped.
--
-- 50 of 93 Section 1 samples have known sources; 43 are UNKNOWN. All UNKNOWNs
-- keep category 'main' and surface via raw_source per the batch plan.
-- E-MU vs E-MU Classic Series spelling drift from the CSV is preserved
-- verbatim; consolidation deferred to a future data-quality pass.

INSERT OR IGNORE INTO manufacturers (name) VALUES
  ('Northstar'),
  ('AMG & Hit Music'),
  ('Kurzweil'),
  ('InVision Interactive'),
  ('Alesis'),
  ('Best Service'),
  ('E-MU Systems'),
  ('AKAI'),
  ('Fairlight'),
  ('ILIO'),
  ('Digidesign'),
  ('Ensoniq InVision'),
  ('Zero-G'),
  ('Spectrasonics'),
  ('E-MU Classic Series');

INSERT OR IGNORE INTO products (manufacturer_id, name, type) VALUES
  ((SELECT id FROM manufacturers WHERE name = 'Northstar'            COLLATE NOCASE), 'The Wizard',                                                        'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'AMG & Hit Music'      COLLATE NOCASE), 'JJ Jeczalik''s Art of Sampling',                                    'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Kurzweil'             COLLATE NOCASE), 'K1200',                                                             'Synth'),
  ((SELECT id FROM manufacturers WHERE name = 'InVision Interactive' COLLATE NOCASE), 'Lightware Vol. 1 - Instruments & Percussions',                      'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Alesis'               COLLATE NOCASE), 'D4',                                                                'Hardware'),
  ((SELECT id FROM manufacturers WHERE name = 'Best Service'         COLLATE NOCASE), 'Gigapack',                                                          'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'E-MU Systems'         COLLATE NOCASE), 'Classic Series Vol. 1',                                             'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'E-MU Systems'         COLLATE NOCASE), 'Classic Series Vol. 3',                                             'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'InVision Interactive' COLLATE NOCASE), 'Lightware Vol. 6 - Ethnic, Guitar, Synth & Percussion',             'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'AKAI'                 COLLATE NOCASE), 'CD-ROM Sound Library Vol. 2',                                       'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Best Service'         COLLATE NOCASE), 'Classical Choir',                                                   'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Fairlight'            COLLATE NOCASE), 'CMI III',                                                           'Hardware'),
  ((SELECT id FROM manufacturers WHERE name = 'ILIO'                 COLLATE NOCASE), 'Synclavier Brass and Winds',                                        'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'E-MU Systems'         COLLATE NOCASE), 'Classic Series Vol. 14',                                            'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'ILIO'                 COLLATE NOCASE), 'Synclaiver Strings',                                                'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Digidesign'           COLLATE NOCASE), 'SampleCell II CD-ROM Library #2',                                   'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'InVision Interactive' COLLATE NOCASE), 'Lightware Vol. 4 - Symphonic II',                                   'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Ensoniq InVision'     COLLATE NOCASE), 'CDR-9 Ethnic',                                                      'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Zero-G'               COLLATE NOCASE), 'Ethnic',                                                            'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Spectrasonics'        COLLATE NOCASE), 'Hans Zimmer Guitars Vol. 1',                                        'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'E-MU Classic Series'  COLLATE NOCASE), 'Vol. 8',                                                            'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'E-MU Classic Series'  COLLATE NOCASE), 'Vol. 5',                                                            'Sample Library');

INSERT INTO games (title, platform, released, composers, composers_normalized, notes) VALUES
  ('Final Fantasy VII',
   'PlayStation, PC, iOS, Android, PlayStation 4, Switch, Xbox One',
   '1997-01-31',
   'Nobuo Uematsu',
   'nobuo uematsu',
   'Source: Final Fantasy Sound Sources (Detailed) - Final Fantasy VII.csv. CSV header notes "This section is a work-in-progress." 60 of 93 Section 1 samples flagged unknown; all 13 named Demo Samples are unknown. Demo build samples with blank descriptions (CSV rows 119-180) dropped during ingestion.');

INSERT INTO usages
  (game_id, product_id, sample_label, sample_ref, path_bank, preset, notes, raw_source, category, source_family, position)
VALUES
  -- =========================================================================
  -- Section 1 - Main Game Music
  -- =========================================================================
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'), NULL, 'Wave 1 (Sine)', 'Sample 0', NULL, NULL, NULL, 'UNKNOWN', 'main', 'ff_detailed', 1),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'), NULL, 'Wave 2', 'Sample 1', NULL, NULL, NULL, 'UNKNOWN', 'main', 'ff_detailed', 2),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'), NULL, 'Wave 3', 'Sample 2', NULL, NULL, NULL, 'UNKNOWN', 'main', 'ff_detailed', 3),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'), NULL, 'Wave 4', 'Sample 3', NULL, NULL, NULL, 'UNKNOWN', 'main', 'ff_detailed', 4),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Northstar' COLLATE NOCASE AND p.name = 'The Wizard' COLLATE NOCASE),
   'Creepy Atmosphere', 'Sample 4', 'FLOURESCENCE', 'A#3 FLOUR00', 'Check note', NULL, 'main', 'ff_detailed', 5),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'), NULL, 'Noise', 'Sample 5', NULL, NULL, NULL, 'UNKNOWN', 'main', 'ff_detailed', 6),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'), NULL, 'Suspended Cymbal', 'Sample 6', NULL, NULL, NULL, 'UNKNOWN', 'main', 'ff_detailed', 7),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'), NULL, 'Machine Gun?', 'Sample 7', NULL, NULL, NULL, 'UNKNOWN', 'main', 'ff_detailed', 8),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'), NULL, 'Wave 5', 'Sample 8', NULL, NULL, NULL, 'UNKNOWN', 'main', 'ff_detailed', 9),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'), NULL, 'Weird Bell Synth', 'Sample 9', NULL, NULL, NULL, 'UNKNOWN', 'main', 'ff_detailed', 10),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'), NULL, 'Train SFX', 'Sample 10', NULL, NULL, NULL, 'UNKNOWN', 'main', 'ff_detailed', 11),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'), NULL, 'Wave 6', 'Sample 11', NULL, NULL, NULL, 'UNKNOWN', 'main', 'ff_detailed', 12),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'), NULL, 'Wave 7', 'Sample 12', NULL, NULL, NULL, 'UNKNOWN', 'main', 'ff_detailed', 13),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'), NULL, 'Wave 8', 'Sample 13', NULL, NULL, NULL, 'UNKNOWN', 'main', 'ff_detailed', 14),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'), NULL, 'Screechy Synth 1', 'Sample 14', NULL, NULL, NULL, 'UNKNOWN, SAME SOURCE AS SAMPLES 15, 23, 24, 25', 'main', 'ff_detailed', 15),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'), NULL, 'Screechy Synth 2', 'Sample 15', NULL, NULL, NULL, 'UNKNOWN, SAME SOURCE AS SAMPLES 14, 23, 24, 25', 'main', 'ff_detailed', 16),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG & Hit Music' COLLATE NOCASE AND p.name = 'JJ Jeczalik''s Art of Sampling' COLLATE NOCASE),
   'Tambourine', 'Sample 16', 'Track 27 -> Sample 1', 'Ambient Tambourine Hit', 'Used for the "clang" in the Those Who Fight', NULL, 'main', 'ff_detailed', 17),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'), NULL, 'Bass Drum', 'Sample 17', NULL, NULL, NULL, 'UNKNOWN', 'main', 'ff_detailed', 18),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Kurzweil' COLLATE NOCASE AND p.name = 'K1200' COLLATE NOCASE),
   'Electric Piano', 'Sample 18', '100 Bank', '3 Chorused E Piano [G#5]', '<85% Velocity', NULL, 'main', 'ff_detailed', 19),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'), NULL, 'Wave 9 (Square)', 'Sample 19', NULL, NULL, NULL, 'UNKNOWN', 'main', 'ff_detailed', 20),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'), NULL, 'Wave 10 (Saw)', 'Sample 20', NULL, NULL, NULL, 'UNKNOWN', 'main', 'ff_detailed', 21),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'), NULL, 'Wave 11 (Triangle)', 'Sample 21', NULL, NULL, NULL, 'UNKNOWN', 'main', 'ff_detailed', 22),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'), NULL, 'Wave 12', 'Sample 22', NULL, NULL, NULL, 'UNKNOWN', 'main', 'ff_detailed', 23),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'), NULL, 'Screechy Synth 3', 'Sample 23', NULL, NULL, NULL, 'UNKNOWN, SAME SOURCE AS SAMPLES 14, 15, 24, 25', 'main', 'ff_detailed', 24),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'), NULL, 'Screechy Synth 4', 'Sample 24', NULL, NULL, NULL, 'UNKNOWN, SAME SOURCE AS SAMPLES 14, 15, 23, 25', 'main', 'ff_detailed', 25),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'), NULL, 'Screechy Synth 5', 'Sample 25', NULL, NULL, NULL, 'UNKNOWN, SAME SOURCE AS SAMPLES 14, 15, 23, 24', 'main', 'ff_detailed', 26),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'InVision Interactive' COLLATE NOCASE AND p.name = 'Lightware Vol. 1 - Instruments & Percussions' COLLATE NOCASE),
   'Orchestral Cymbal', 'Sample 26', 'Partition B -> ORCH.PERC. 2', 'ORCH.CYMBALS', NULL, NULL, 'main', 'ff_detailed', 27),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'InVision Interactive' COLLATE NOCASE AND p.name = 'Lightware Vol. 1 - Instruments & Percussions' COLLATE NOCASE),
   'Nylon Guitar', 'Sample 27', 'Partition A - AC 6-STRING', 'AC.GUITAR 1 [B2]', NULL, NULL, 'main', 'ff_detailed', 28),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'), NULL, 'Synth Bass', 'Sample 28', NULL, NULL, 'Likely Roland', 'UNKNOWN', 'main', 'ff_detailed', 29),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Alesis' COLLATE NOCASE AND p.name = 'D4' COLLATE NOCASE),
   'Noisy Kick', 'Sample 29', 'EFX', '09 Door Slam', NULL, NULL, 'main', 'ff_detailed', 30),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Alesis' COLLATE NOCASE AND p.name = 'D4' COLLATE NOCASE),
   'Industrial Perc', 'Sample 30', 'EFX', '19 Trq Wrench', 'Pitched up 150 cents', NULL, 'main', 'ff_detailed', 31),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Gigapack' COLLATE NOCASE),
   'Oboe', 'Sample 31', 'CD 2 -> BRA:Brass&Woods1 -> BRA:Oboe', 'BRA:Oboe', NULL, NULL, 'main', 'ff_detailed', 32),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'E-MU Systems' COLLATE NOCASE AND p.name = 'Classic Series Vol. 1' COLLATE NOCASE),
   'Bassoon', 'Sample 32', 'OrchestralComp#1', 'Bassoon', 'Check Note', NULL, 'main', 'ff_detailed', 33),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'E-MU Systems' COLLATE NOCASE AND p.name = 'Classic Series Vol. 1' COLLATE NOCASE),
   'Trombone', 'Sample 33', 'Solo Trombone 4M', 'Hard Trombone', 'Also in Emulator III Factory Sounds Vol. 1', NULL, 'main', 'ff_detailed', 34),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'E-MU Systems' COLLATE NOCASE AND p.name = 'Classic Series Vol. 3' COLLATE NOCASE),
   'French Horn', 'Sample 34', 'Solo Fr Horns 8M', 'ff St Fr Horn', NULL, NULL, 'main', 'ff_detailed', 35),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'E-MU Systems' COLLATE NOCASE AND p.name = 'Classic Series Vol. 3' COLLATE NOCASE),
   'Tuba', 'Sample 35', 'Solo Tuba&Bones', 'St Tuba', 'Check Note', NULL, 'main', 'ff_detailed', 36),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'InVision Interactive' COLLATE NOCASE AND p.name = 'Lightware Vol. 1 - Instruments & Percussions' COLLATE NOCASE),
   'Snare Drum 1', 'Sample 36', 'Partition B -> SNARES ONE', 'SNARES MAP 1 [A1 note]', 'Pitched up 300 cents', NULL, 'main', 'ff_detailed', 37),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'InVision Interactive' COLLATE NOCASE AND p.name = 'Lightware Vol. 6 - Ethnic, Guitar, Synth & Percussion' COLLATE NOCASE),
   'Closed HiHat', 'Sample 37', 'Partition B -> VOLUME 005', 'T1 DRUMS', NULL, NULL, 'main', 'ff_detailed', 38),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'InVision Interactive' COLLATE NOCASE AND p.name = 'Lightware Vol. 6 - Ethnic, Guitar, Synth & Percussion' COLLATE NOCASE),
   'Open HiHat', 'Sample 38', 'Partition B -> VOLUME 005', 'T1 DRUMS', NULL, NULL, 'main', 'ff_detailed', 39),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'), NULL, 'Orchestral Hit', 'Sample 39', NULL, NULL, NULL, 'UNKNOWN', 'main', 'ff_detailed', 40),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AKAI' COLLATE NOCASE AND p.name = 'CD-ROM Sound Library Vol. 2' COLLATE NOCASE),
   'Low Grand Piano', 'Sample 40', 'Partition A -> STEREO G.PF1', 'STW GRAND PF', 'May be something else. This sample is in a lot of things.', NULL, 'main', 'ff_detailed', 41),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Alesis' COLLATE NOCASE AND p.name = 'D4' COLLATE NOCASE),
   'Clicky Perc', 'Sample 41', 'EFX', '23 Thrash Lid', NULL, NULL, 'main', 'ff_detailed', 42),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Kurzweil' COLLATE NOCASE AND p.name = 'K1200' COLLATE NOCASE),
   'Strings', 'Sample 42', '000 Bank', '73 Fast Strings [F5]', '100% Velocity', NULL, 'main', 'ff_detailed', 43),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'), NULL, 'Horn + Strings', 'Sample 43', NULL, NULL, NULL, 'UNKNOWN', 'main', 'ff_detailed', 44),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Classical Choir' COLLATE NOCASE),
   'Choir Ahs', 'Sample 44', 'Partition C -> AHH SL 16 MB', 'Ahh 3R', 'Likely Classical Choir Extended instead', NULL, 'main', 'ff_detailed', 45),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'InVision Interactive' COLLATE NOCASE AND p.name = 'Lightware Vol. 1 - Instruments & Percussions' COLLATE NOCASE),
   'Timpani', 'Sample 45', 'Parition B -> ORCH.PERC. 2', 'ORCH.PERC.#2 [C3 note]', NULL, NULL, 'main', 'ff_detailed', 46),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'E-MU Systems' COLLATE NOCASE AND p.name = 'Classic Series Vol. 1' COLLATE NOCASE),
   'Flute', 'Sample 46', 'OrchestralComp#1', 'Flute', 'Also in Emulator III Factory Sounds Vol. 1', NULL, 'main', 'ff_detailed', 47),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Gigapack' COLLATE NOCASE),
   'Harp', 'Sample 47', 'CD 2 -> STR:Orchestral -> STR:Harp', 'STR:Harp', NULL, NULL, 'main', 'ff_detailed', 48),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Fairlight' COLLATE NOCASE AND p.name = 'CMI III' COLLATE NOCASE),
   'Clarinet', 'Sample 48', 'Reeds', 'Clarinet12', 'Likely sampled from a CD that sampled the CMI', NULL, 'main', 'ff_detailed', 49),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'ILIO' COLLATE NOCASE AND p.name = 'Synclavier Brass and Winds' COLLATE NOCASE),
   'Trumpet', 'Sample 49', 'Partition A -> 010 1.7MB', 'TPT SOLO FF', NULL, NULL, 'main', 'ff_detailed', 50),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'E-MU Systems' COLLATE NOCASE AND p.name = 'Classic Series Vol. 14' COLLATE NOCASE),
   'Tubular Bells', 'Sample 50', '4M General Midi', 'Tubular Bells', 'Likely Proteus/2 instead. Same sample, more likely source.', NULL, 'main', 'ff_detailed', 51),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'ILIO' COLLATE NOCASE AND p.name = 'Synclaiver Strings' COLLATE NOCASE),
   'Pizzicato Strings', 'Sample 51', 'Partition F -> 087 3.8MB', 'VLN SEC PZ 1', NULL, NULL, 'main', 'ff_detailed', 52),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Digidesign' COLLATE NOCASE AND p.name = 'SampleCell II CD-ROM Library #2' COLLATE NOCASE),
   'High Grand Piano', 'Sample 52', 'Big Pianos', 'Yamaha C5 Stereo 1', 'Correct sample, may be from something else', NULL, 'main', 'ff_detailed', 53),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Alesis' COLLATE NOCASE AND p.name = 'D4' COLLATE NOCASE),
   'Toms', 'Sample 53', 'TOMS', '01 Hi Power', NULL, NULL, 'main', 'ff_detailed', 54),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'), NULL, 'Snare Roll', 'Sample 54', NULL, NULL, 'Might be Lightware 1 ORCH.PERC.#2?', 'UNKNOWN', 'main', 'ff_detailed', 55),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'), NULL, 'FM Bass', 'Sample 55', NULL, NULL, NULL, 'UNKNOWN', 'main', 'ff_detailed', 56),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Fairlight' COLLATE NOCASE AND p.name = 'CMI III' COLLATE NOCASE),
   'Upright Bass', 'Sample 56', 'Bass', 'BassAcc11', 'Likely sampled from a CD that sampled the CMI', NULL, 'main', 'ff_detailed', 57),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Fairlight' COLLATE NOCASE AND p.name = 'CMI III' COLLATE NOCASE),
   'Banjo', 'Sample 57', 'Plucked Instruments', 'Banjo11', 'Likely sampled from a CD that sampled the CMI', NULL, 'main', 'ff_detailed', 58),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'InVision Interactive' COLLATE NOCASE AND p.name = 'Lightware Vol. 1 - Instruments & Percussions' COLLATE NOCASE),
   'Fiddle', 'Sample 58', 'Partion B -> FIDDLE ONE', 'FIDDLE ONE', NULL, NULL, 'main', 'ff_detailed', 59),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Ensoniq InVision' COLLATE NOCASE AND p.name = 'CDR-9 Ethnic' COLLATE NOCASE),
   'Mandolin', 'Sample 59', 'STRINGED -> ETHNIC+MISC', 'MANDOLIN', NULL, NULL, 'main', 'ff_detailed', 60),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'InVision Interactive' COLLATE NOCASE AND p.name = 'Lightware Vol. 1 - Instruments & Percussions' COLLATE NOCASE),
   'Synth Pad 1', 'Sample 60', 'Partion B -> WAVESYNTH', 'WRM.SYNSTRINGS', 'I think these are something different. Also probably just strings.', NULL, 'main', 'ff_detailed', 61),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'InVision Interactive' COLLATE NOCASE AND p.name = 'Lightware Vol. 1 - Instruments & Percussions' COLLATE NOCASE),
   'Synth Pad 2', 'Sample 61', 'Partion B -> WAVESYNTH', 'WRM.SYNSTRINGS', 'I think these are something different. Also probably just strings.', NULL, 'main', 'ff_detailed', 62),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'InVision Interactive' COLLATE NOCASE AND p.name = 'Lightware Vol. 1 - Instruments & Percussions' COLLATE NOCASE),
   'Synth Pad 3', 'Sample 62', 'Partion B -> WAVESYNTH', 'WRM.SYNSTRINGS', 'I think these are something different. Also probably just strings.', NULL, 'main', 'ff_detailed', 63),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'InVision Interactive' COLLATE NOCASE AND p.name = 'Lightware Vol. 1 - Instruments & Percussions' COLLATE NOCASE),
   'Synth Pad 4', 'Sample 63', 'Partion B -> WAVESYNTH', 'WRM.SYNSTRINGS', 'I think these are something different. Also probably just strings.', NULL, 'main', 'ff_detailed', 64),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Alesis' COLLATE NOCASE AND p.name = 'D4' COLLATE NOCASE),
   'Kick Drum', 'Sample 64', 'KICKS', '11 Foot', 'Pitched up 200 cents', NULL, 'main', 'ff_detailed', 65),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Alesis' COLLATE NOCASE AND p.name = 'D4' COLLATE NOCASE),
   'Crash Cymbal', 'Sample 65', 'CYMBALS', '44 Medium', NULL, NULL, 'main', 'ff_detailed', 66),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Alesis' COLLATE NOCASE AND p.name = 'D4' COLLATE NOCASE),
   'Snare Drum 2', 'Sample 66', 'SNARES', '70 Bad Punch', 'Pitched down 100 cents', NULL, 'main', 'ff_detailed', 67),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'), NULL, 'Synth Pad 5', 'Sample 67', NULL, NULL, NULL, 'UNKNOWN', 'main', 'ff_detailed', 68),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'InVision Interactive' COLLATE NOCASE AND p.name = 'Lightware Vol. 4 - Symphonic II' COLLATE NOCASE),
   'Classical Guitar', 'Sample 68', 'Classical Guitar', 'Classical Gtr', NULL, NULL, 'main', 'ff_detailed', 69),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'), NULL, 'Taikos 1', 'Sample 69', NULL, NULL, NULL, 'UNKNOWN', 'main', 'ff_detailed', 70),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'), NULL, 'Taikos 2', 'Sample 70', NULL, NULL, NULL, 'UNKNOWN', 'main', 'ff_detailed', 71),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'), NULL, 'Guitar Fret', 'Sample 71', NULL, NULL, NULL, 'UNKNOWN', 'main', 'ff_detailed', 72),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'), NULL, 'Ride Cymbal', 'Sample 72', NULL, NULL, NULL, 'UNKNOWN', 'main', 'ff_detailed', 73),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'), NULL, 'Chorus Electric Guitar', 'Sample 73', NULL, NULL, NULL, 'UNKNOWN', 'main', 'ff_detailed', 74),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'), NULL, 'Drawbar Organ', 'Sample 74', NULL, NULL, NULL, 'UNKNOWN', 'main', 'ff_detailed', 75),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'), NULL, 'Snare Drum 3', 'Sample 75', NULL, NULL, 'sounds E-MU', 'UNKNOWN', 'main', 'ff_detailed', 76),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Ethnic' COLLATE NOCASE),
   'Guitar Mutes', 'Sample 76', 'FILL IN', 'Track 78', 'originally sampled from "Perfidia" by The Ventures', NULL, 'main', 'ff_detailed', 77),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'), NULL, 'Chocobo SFX', 'Sample 77', NULL, NULL, NULL, 'UNKNOWN', 'main', 'ff_detailed', 78),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'), NULL, 'Electric Bass', 'Sample 78', NULL, NULL, 'Could be Proteus 1 -> Buzzy Frets', 'UNKNOWN', 'main', 'ff_detailed', 79),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'), NULL, 'Side Stick', 'Sample 79', NULL, NULL, NULL, 'UNKNOWN', 'main', 'ff_detailed', 80),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'), NULL, 'Lo Conga', 'Sample 80', NULL, NULL, NULL, 'UNKNOWN', 'main', 'ff_detailed', 81),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'), NULL, 'Hi Conga', 'Sample 81', NULL, NULL, NULL, 'UNKNOWN', 'main', 'ff_detailed', 82),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'), NULL, 'Shaker', 'Sample 82', NULL, NULL, NULL, 'UNKNOWN', 'main', 'ff_detailed', 83),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Kurzweil' COLLATE NOCASE AND p.name = 'K1200' COLLATE NOCASE),
   'Strings 2', 'Sample 83', '000 Bank', '73 Fast Strings [C5]', '100% Velocity (Likely another note)', NULL, 'main', 'ff_detailed', 84),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Kurzweil' COLLATE NOCASE AND p.name = 'K1200' COLLATE NOCASE),
   'Strings 2 (soft)', 'Sample 84', '000 Bank', '73 Fast Strings [C5]', '50% Velocity  (Likely another note)', NULL, 'main', 'ff_detailed', 85),
  -- Sample 85: source has no " - " split; raw_source captures the unsplittable value.
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'), NULL, 'Yahoo SFX', 'Sample 85', 'CARTOON, YELL', ' ''YAHOO'', COWBOY', NULL, 'Warner Bros. Sound Effects Library', 'main', 'ff_detailed', 86),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Hans Zimmer Guitars Vol. 1' COLLATE NOCASE),
   'Distortion Guitar', 'Sample 86', 'Partition A -> PRS LEAD', 'PRS LEAD B [A2]', NULL, NULL, 'main', 'ff_detailed', 87),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'E-MU Classic Series' COLLATE NOCASE AND p.name = 'Vol. 8' COLLATE NOCASE),
   'Percussive Organ', 'Sample 87', 'Tone Wheel Organ', 'Rock Percussion', NULL, NULL, 'main', 'ff_detailed', 88),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG & Hit Music' COLLATE NOCASE AND p.name = 'JJ Jeczalik''s Art of Sampling' COLLATE NOCASE),
   'Snap', 'Sample 88', 'Track 29 -> Sample 28', 'FILL IN', 'Used for the "clang" in the Those Who Fight', NULL, 'main', 'ff_detailed', 89),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Alesis' COLLATE NOCASE AND p.name = 'D4' COLLATE NOCASE),
   'Pop', 'Sample 89', 'EFX', '07 Lip Pop', 'Pitched up 800 cents', NULL, 'main', 'ff_detailed', 90),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Alesis' COLLATE NOCASE AND p.name = 'D4' COLLATE NOCASE),
   'Wood Block', 'Sample 90', 'PERC', '38 Hi Wood', NULL, NULL, 'main', 'ff_detailed', 91),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'E-MU Classic Series' COLLATE NOCASE AND p.name = 'Vol. 5' COLLATE NOCASE),
   'Dulcimer', 'Sample 91', 'Hmrd Dulcimer', 'Short Dulcimer', NULL, NULL, 'main', 'ff_detailed', 92),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'), NULL, 'Vocal Grunt', 'Sample 92', NULL, NULL, NULL, 'UNKNOWN', 'main', 'ff_detailed', 93),
  -- =========================================================================
  -- Demo Samples (prototype build; only rows with a description are kept).
  -- Per CSV note column, most are "Same as final"; preserved in notes.
  -- =========================================================================
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'), NULL, 'Wave 4', 'Sample 0', NULL, NULL, 'Same as final', 'UNKNOWN', 'unused', 'ff_detailed', 94),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'), NULL, 'Creepy Atmosphere', 'Sample 1', NULL, NULL, 'Same as final', 'UNKNOWN', 'unused', 'ff_detailed', 95),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'), NULL, 'Noise', 'Sample 2', NULL, NULL, 'Same as final', 'UNKNOWN', 'unused', 'ff_detailed', 96),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'), NULL, 'Suspended Cymbal', 'Sample 3', NULL, NULL, 'Same as final', 'UNKNOWN', 'unused', 'ff_detailed', 97),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'), NULL, 'Machine Gun?', 'Sample 4', NULL, NULL, 'Same as final', 'UNKNOWN', 'unused', 'ff_detailed', 98),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'), NULL, 'Wave 5', 'Sample 5', NULL, NULL, 'Same as final', 'UNKNOWN', 'unused', 'ff_detailed', 99),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'), NULL, 'Chord Clang', 'Sample 6', NULL, NULL, NULL, 'UNKNOWN', 'unused', 'ff_detailed', 100),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'), NULL, 'Train SFX', 'Sample 7', NULL, NULL, 'Same as final', 'UNKNOWN', 'unused', 'ff_detailed', 101),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'), NULL, 'Wave 6', 'Sample 8', NULL, NULL, 'Same as final', 'UNKNOWN', 'unused', 'ff_detailed', 102),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'), NULL, 'Wave 7', 'Sample 9', NULL, NULL, 'Same as final', 'UNKNOWN', 'unused', 'ff_detailed', 103),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'), NULL, 'Wave 1 (Sine)', 'Sample 10', NULL, NULL, 'Same as final', 'UNKNOWN', 'unused', 'ff_detailed', 104),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'), NULL, 'Wave 1 (Sine)', 'Sample 11', NULL, NULL, 'Same as final', 'UNKNOWN', 'unused', 'ff_detailed', 105),
  ((SELECT id FROM games WHERE title = 'Final Fantasy VII'), NULL, 'Wave 1 (Sine)', 'Sample 12', NULL, NULL, 'Same as final', 'UNKNOWN', 'unused', 'ff_detailed', 106);
