-- Source: reference/Final Fantasy Sound Sources (Detailed) - Ivalice Alliance.csv
-- Section 1: Final Fantasy Tactics (CSV rows 15-135).
-- 99 sequenced soundbank samples (75 unsourced) + 10 streamed-track rows (6 sourced).
-- Sequenced samples: category 'main', position 1-99.
-- Streamed tracks: category 'main', position 100-109, examples = track name.
-- Empty Source values (vs explicit UNKNOWN) leave raw_source NULL per batch plan.
-- Whitespace in product names is normalized (collapse internal multi-spaces);
-- "Roland - SR-JV80-02  Orchestral" (double space) → single space.
-- "Roland SR-JV80-02 Orchestral" (no separator on streamed Sample, line 120) goes
-- to raw_source verbatim per the source-split rule.

INSERT OR IGNORE INTO manufacturers (name) VALUES
  ('Roland');

INSERT OR IGNORE INTO products (manufacturer_id, name, type) VALUES
  ((SELECT id FROM manufacturers WHERE name = 'Roland' COLLATE NOCASE), 'SR-JV80-02 Orchestral', 'Hardware'),
  ((SELECT id FROM manufacturers WHERE name = 'Roland' COLLATE NOCASE), 'JV-1080',               'Synth'),
  ((SELECT id FROM manufacturers WHERE name = 'Roland' COLLATE NOCASE), 'SR-JV80-05 World',      'Hardware');

INSERT INTO games (title, platform, released, composers, composers_normalized, notes) VALUES
  ('Final Fantasy Tactics',
   'PlayStation, PSP, iOS, Android',
   '1997-06-20',
   'Hitoshi Sakimoto, Masaharu Iwata',
   'hitoshi sakimoto, masaharu iwata',
   'Source: Final Fantasy Sound Sources (Detailed) - Ivalice Alliance.csv (Section 1). CSV is flagged work-in-progress; 75 of 99 sequenced soundbank samples have no source set yet (empty Source column, not explicit UNKNOWN). Streamed Tracks section is mostly stubs — only 6 of 10 rows have a sourced product. Track headers ("Opening", "Prolouge Movie" sic) dropped during ingestion.');

INSERT INTO usages
  (game_id, product_id, sample_label, sample_ref, path_bank, preset, notes, raw_source, examples, category, source_family, position)
VALUES
  -- =========================================================================
  -- Section 1 - Sequenced Soundbank (Sample 0..Sample 98)
  -- =========================================================================
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Wave 1', 'Sample 0', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 1),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Wave 2', 'Sample 1', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 2),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Wave 3', 'Sample 2', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 3),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Wave 4', 'Sample 3', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 4),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Wave 5', 'Sample 4', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 5),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Wave 6', 'Sample 5', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 6),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Wave 7', 'Sample 6', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 7),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Wave 8', 'Sample 7', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 8),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-02 Orchestral' COLLATE NOCASE),
   'Tubular Bell', 'Sample 8', 'XP-X', '088 TubulaBells1', NULL, NULL, NULL, 'main', 'ff_detailed', 9),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Wave 9', 'Sample 9', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 10),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Noise SFX???', 'Sample 10', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 11),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Noise SFX???', 'Sample 11', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 12),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Noise SFX???', 'Sample 12', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 13),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Snare Drum', 'Sample 13', NULL, NULL, 'Maybe Advance Orchestra or Proteus/2?', NULL, NULL, 'main', 'ff_detailed', 14),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Tonal Clang', 'Sample 14', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 15),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Crash Hit', 'Sample 15', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 16),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-02 Orchestral' COLLATE NOCASE),
   'Orchestral Cymbal 1', 'Sample 16', 'Waveforms', '134 Cymbal Hit', NULL, NULL, NULL, 'main', 'ff_detailed', 17),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Wind Chime', 'Sample 17', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 18),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-02 Orchestral' COLLATE NOCASE),
   'Glockenspiel', 'Sample 18', 'XP-X', '211 Glocken 1', NULL, NULL, NULL, 'main', 'ff_detailed', 19),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-02 Orchestral' COLLATE NOCASE),
   'Harp', 'Sample 19', 'XP-X', '058 Harp 1', NULL, NULL, NULL, 'main', 'ff_detailed', 20),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-02 Orchestral' COLLATE NOCASE),
   'Harp', 'Sample 20', 'XP-X', '058 Harp 1', NULL, NULL, NULL, 'main', 'ff_detailed', 21),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-02 Orchestral' COLLATE NOCASE),
   'Harp', 'Sample 21', 'XP-X', '058 Harp 1', NULL, NULL, NULL, 'main', 'ff_detailed', 22),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-02 Orchestral' COLLATE NOCASE),
   'Harp', 'Sample 22', 'XP-X', '058 Harp 1', NULL, NULL, NULL, 'main', 'ff_detailed', 23),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-02 Orchestral' COLLATE NOCASE),
   'Harp', 'Sample 23', 'XP-X', '058 Harp 1', NULL, NULL, NULL, 'main', 'ff_detailed', 24),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-02 Orchestral' COLLATE NOCASE),
   'Oboe', 'Sample 24', 'XP-X', '094 Oboe 3', NULL, NULL, NULL, 'main', 'ff_detailed', 25),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-02 Orchestral' COLLATE NOCASE),
   'Oboe', 'Sample 25', 'XP-X', '094 Oboe 3', NULL, NULL, NULL, 'main', 'ff_detailed', 26),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JV-1080' COLLATE NOCASE),
   'Pizzicato Strings', 'Sample 26', 'PR-C', '047 Bass Pizz', NULL, NULL, NULL, 'main', 'ff_detailed', 27),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-02 Orchestral' COLLATE NOCASE),
   'Sleigh Bells', 'Sample 27', 'Waveforms', '144 Sleigh Bell', NULL, NULL, NULL, 'main', 'ff_detailed', 28),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Flute 1', 'Sample 28', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 29),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Flute 1', 'Sample 29', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 30),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Flute 1', 'Sample 30', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 31),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Crash Hit', 'Sample 31', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 32),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-02 Orchestral' COLLATE NOCASE),
   'Hard String Ensemble', 'Sample 32', 'XP-X', '043 Vivace Strs', NULL, NULL, NULL, 'main', 'ff_detailed', 33),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-02 Orchestral' COLLATE NOCASE),
   'Hard String Ensemble', 'Sample 33', 'XP-X', '043 Vivace Strs', NULL, NULL, NULL, 'main', 'ff_detailed', 34),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-02 Orchestral' COLLATE NOCASE),
   'Hard String Ensemble', 'Sample 34', 'XP-X', '043 Vivace Strs', NULL, NULL, NULL, 'main', 'ff_detailed', 35),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-02 Orchestral' COLLATE NOCASE),
   'Hard String Ensemble', 'Sample 35', 'XP-X', '043 Vivace Strs', NULL, NULL, NULL, 'main', 'ff_detailed', 36),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-02 Orchestral' COLLATE NOCASE),
   'Hard String Ensemble', 'Sample 36', 'XP-X', '043 Vivace Strs', NULL, NULL, NULL, 'main', 'ff_detailed', 37),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-02 Orchestral' COLLATE NOCASE),
   'Hard String Ensemble', 'Sample 37', 'XP-X', '043 Vivace Strs', NULL, NULL, NULL, 'main', 'ff_detailed', 38),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Clarinet', 'Sample 38', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 39),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Clarinet', 'Sample 39', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 40),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Clarinet', 'Sample 40', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 41),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Clarinet', 'Sample 41', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 42),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Trombone', 'Sample 42', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 43),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Trombone', 'Sample 43', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 44),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Trombone', 'Sample 44', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 45),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-02 Orchestral' COLLATE NOCASE),
   'Orchestral Cymbal 2', 'Sample 45', 'Waveforms', '132 Crash Cymbal', NULL, NULL, NULL, 'main', 'ff_detailed', 46),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Flute 2', 'Sample 46', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 47),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-02 Orchestral' COLLATE NOCASE),
   'Brass Section', 'Sample 47', 'XP-X', '160 McArthur Brs', NULL, NULL, NULL, 'main', 'ff_detailed', 48),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-02 Orchestral' COLLATE NOCASE),
   'Brass Section', 'Sample 48', 'XP-X', '160 McArthur Brs', NULL, NULL, NULL, 'main', 'ff_detailed', 49),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-02 Orchestral' COLLATE NOCASE),
   'Brass Section', 'Sample 49', 'XP-X', '160 McArthur Brs', NULL, NULL, NULL, 'main', 'ff_detailed', 50),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-02 Orchestral' COLLATE NOCASE),
   'Brass Section', 'Sample 50', 'XP-X', '160 McArthur Brs', NULL, NULL, NULL, 'main', 'ff_detailed', 51),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-02 Orchestral' COLLATE NOCASE),
   'Timpani', 'Sample 51', 'Waveforms', '121 Timpani f', 'Check JV-1080', NULL, NULL, 'main', 'ff_detailed', 52),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-02 Orchestral' COLLATE NOCASE),
   'Timpani', 'Sample 52', 'Waveforms', '121 Timpani f', 'Check JV-1080', NULL, NULL, 'main', 'ff_detailed', 53),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Celesta', 'Sample 53', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 54),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Trumpet', 'Sample 54', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 55),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Trumpet', 'Sample 55', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 56),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Trumpet', 'Sample 56', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 57),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Trumpet', 'Sample 57', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 58),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Trumpet', 'Sample 58', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 59),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Bassoon', 'Sample 59', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 60),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Bassoon', 'Sample 60', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 61),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Bassoon', 'Sample 61', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 62),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Bassoon', 'Sample 62', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 63),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Bassoon', 'Sample 63', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 64),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Soft String Ensemble', 'Sample 64', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 65),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Soft String Ensemble', 'Sample 65', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 66),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Soft String Ensemble', 'Sample 66', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 67),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Soft String Ensemble', 'Sample 67', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 68),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Soft String Ensemble', 'Sample 68', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 69),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Noise SFX???', 'Sample 69', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 70),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Horn Ensemble', 'Sample 70', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 71),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Horn Ensemble', 'Sample 71', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 72),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Horn Ensemble', 'Sample 72', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 73),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Horn Ensemble', 'Sample 73', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 74),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Horn Ensemble', 'Sample 74', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 75),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Noise SFX???', 'Sample 75', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 76),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Loud Knock', 'Sample 76', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 77),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Noise SFX???', 'Sample 77', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 78),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Metallic Knock', 'Sample 78', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 79),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Babbling Vox', 'Sample 79', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 80),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Metallic Key', 'Sample 80', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 81),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Wave', 'Sample 81', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 82),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Wave', 'Sample 82', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 83),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Choir Aahs', 'Sample 83', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 84),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Synth Pad', 'Sample 84', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 85),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Noise SFX???', 'Sample 85', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 86),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Noise SFX???', 'Sample 86', NULL, NULL, 'Might be a Guiro', NULL, NULL, 'main', 'ff_detailed', 87),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Noise SFX???', 'Sample 87', NULL, NULL, 'Sounds metallic', NULL, NULL, 'main', 'ff_detailed', 88),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Sine Wave', 'Sample 88', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 89),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Synth Pad', 'Sample 89', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 90),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Synth Pad', 'Sample 90', NULL, NULL, 'Also heard on the Proteus 2000 as "Pad:Classic "', NULL, NULL, 'main', 'ff_detailed', 91),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Wave', 'Sample 91', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 92),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Noise SFX???', 'Sample 92', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 93),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Slow Strings', 'Sample 93', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 94),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Slow Strings', 'Sample 94', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 95),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Solo Trumpet', 'Sample 95', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 96),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Solo Trumpet', 'Sample 96', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 97),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Solo Trumpet', 'Sample 97', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 98),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Solo Trumpet', 'Sample 98', NULL, NULL, NULL, NULL, NULL, 'main', 'ff_detailed', 99),
  -- =========================================================================
  -- Streamed Tracks (track headers dropped; examples = parent track name)
  -- =========================================================================
  -- Opening
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Piano', NULL, NULL, NULL, NULL, NULL, 'Opening', 'main', 'ff_detailed', 100),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JV-1080' COLLATE NOCASE),
   'String Ensemble', NULL, 'PR-D (GM)', '049 Strings', NULL, NULL, 'Opening', 'main', 'ff_detailed', 101),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Wind Chime', NULL, 'XP-X', 'Wind Chimes1', NULL, 'Roland SR-JV80-02 Orchestral', 'Opening', 'main', 'ff_detailed', 102),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Oboe', NULL, NULL, NULL, NULL, NULL, 'Opening', 'main', 'ff_detailed', 103),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Bassoon', NULL, NULL, NULL, NULL, NULL, 'Opening', 'main', 'ff_detailed', 104),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'), NULL, 'Cymbal', NULL, NULL, NULL, NULL, NULL, 'Opening', 'main', 'ff_detailed', 105),
  -- Prolouge Movie (typo "Prolouge" preserved per Rule 2)
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-05 World' COLLATE NOCASE),
   'Bagpipes', NULL, 'XP-X', '174 Bagpipes', NULL, NULL, 'Prolouge Movie', 'main', 'ff_detailed', 106),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-02 Orchestral' COLLATE NOCASE),
   'Oboe', NULL, 'XP-X', '094 Oboe 3', NULL, NULL, 'Prolouge Movie', 'main', 'ff_detailed', 107),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-02 Orchestral' COLLATE NOCASE),
   'Brass Section', NULL, 'XP-X', '160 McArthur Brs', NULL, NULL, 'Prolouge Movie', 'main', 'ff_detailed', 108),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-02 Orchestral' COLLATE NOCASE),
   'Wind Chime', NULL, 'XP-X', '245 Wind Chimes1', NULL, NULL, 'Prolouge Movie', 'main', 'ff_detailed', 109);
