-- Source: reference/Final Fantasy Sound Sources (Detailed) - Ivalice Alliance.csv
-- Section 4: Final Fantasy XII: Revenant Wings (CSV rows 262-343).
-- Two tracks documented (SEQ_08 Giza Plains, SEQ_28BossBattle "Flash of Steel"),
-- 78 sample rows total. Uses SWAV N indexing (DS .SDAT wave archive style per the
-- editor's guide). Heavy "CHECK" usage on percussion and brass.
-- "Roland -  SR-JV80-02 Orchestral" (double space) is normalized to single-space
-- product name to match Section 1 / FFT.

INSERT OR IGNORE INTO manufacturers (name) VALUES
  ('ProjectSAM'),
  ('DS Soundware');

INSERT OR IGNORE INTO products (manufacturer_id, name, type) VALUES
  ((SELECT id FROM manufacturers WHERE name = 'Roland'       COLLATE NOCASE), 'XV-5080',                          'Hardware'),
  ((SELECT id FROM manufacturers WHERE name = 'ProjectSAM'   COLLATE NOCASE), 'SAM Horns',                        'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'DS Soundware' COLLATE NOCASE), 'Ultimate Orchestral Percussion',   'Sample Library');

INSERT INTO games (title, platform, released, composers, composers_normalized, notes) VALUES
  ('Final Fantasy XII: Revenant Wings',
   'Nintendo DS',
   '2007-04-26',
   'Hitoshi Sakimoto, Nobuo Uematsu, Hayato Matsuo, Kenichiro Fukui',
   'hitoshi sakimoto, nobuo uematsu, hayato matsuo, kenichiro fukui',
   'Source: Final Fantasy Sound Sources (Detailed) - Ivalice Alliance.csv (Section 4). Two of N tracks documented (SEQ_08 Giza Plains - Preperation Phase, SEQ_28BossBattle "Flash of Steel"). Many CHECK markers on percussion and brass rows.');

INSERT INTO usages
  (game_id, product_id, sample_label, sample_ref, path_bank, preset, notes, raw_source, examples, category, source_family, position)
VALUES
  -- =========================================================================
  -- SEQ_08 (Giza Plains - Preperation Phase)
  -- =========================================================================
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'XV-5080' COLLATE NOCASE),
   'Oboe', 'SWAV 0', 'PR-B', '104 Oboe Express', NULL, NULL, 'SEQ_08 (Giza Plains - Preperation Phase)', 'main', 'ff_detailed', 1),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'XV-5080' COLLATE NOCASE),
   'Oboe', 'SWAV 1', 'PR-B', '104 Oboe Express', NULL, NULL, 'SEQ_08 (Giza Plains - Preperation Phase)', 'main', 'ff_detailed', 2),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-02 Orchestral' COLLATE NOCASE),
   'Celesta', 'SWAV 2', 'XP-X', '201 Celesta 3', NULL, NULL, 'SEQ_08 (Giza Plains - Preperation Phase)', 'main', 'ff_detailed', 3),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-02 Orchestral' COLLATE NOCASE),
   'Celesta', 'SWAV 3', 'XP-X', '201 Celesta 3', NULL, NULL, 'SEQ_08 (Giza Plains - Preperation Phase)', 'main', 'ff_detailed', 4),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-02 Orchestral' COLLATE NOCASE),
   'Celesta', 'SWAV 4', 'XP-X', '201 Celesta 3', NULL, NULL, 'SEQ_08 (Giza Plains - Preperation Phase)', 'main', 'ff_detailed', 5),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'XV-5080' COLLATE NOCASE),
   'Clarinet', 'SWAV 5', NULL, NULL, NULL, NULL, 'SEQ_08 (Giza Plains - Preperation Phase)', 'main', 'ff_detailed', 6),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'XV-5080' COLLATE NOCASE),
   'Clarinet', 'SWAV 6', NULL, NULL, NULL, NULL, 'SEQ_08 (Giza Plains - Preperation Phase)', 'main', 'ff_detailed', 7),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'), NULL, 'Flute', 'SWAV 7', NULL, NULL, NULL, 'CHECK', 'SEQ_08 (Giza Plains - Preperation Phase)', 'main', 'ff_detailed', 8),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'), NULL, 'Flute', 'SWAV 8', NULL, NULL, NULL, 'CHECK', 'SEQ_08 (Giza Plains - Preperation Phase)', 'main', 'ff_detailed', 9),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'), NULL, 'Flute', 'SWAV 9', NULL, NULL, NULL, 'CHECK', 'SEQ_08 (Giza Plains - Preperation Phase)', 'main', 'ff_detailed', 10),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-02 Orchestral' COLLATE NOCASE),
   'Harp', 'SWAV 10', 'XP-X', '058 Harp 1', NULL, NULL, 'SEQ_08 (Giza Plains - Preperation Phase)', 'main', 'ff_detailed', 11),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-02 Orchestral' COLLATE NOCASE),
   'Harp', 'SWAV 11', 'XP-X', '058 Harp 1', NULL, NULL, 'SEQ_08 (Giza Plains - Preperation Phase)', 'main', 'ff_detailed', 12),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-02 Orchestral' COLLATE NOCASE),
   'Harp', 'SWAV 12', 'XP-X', '058 Harp 1', NULL, NULL, 'SEQ_08 (Giza Plains - Preperation Phase)', 'main', 'ff_detailed', 13),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-02 Orchestral' COLLATE NOCASE),
   'Harp', 'SWAV 13', 'XP-X', '058 Harp 1', NULL, NULL, 'SEQ_08 (Giza Plains - Preperation Phase)', 'main', 'ff_detailed', 14),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'ProjectSAM' COLLATE NOCASE AND p.name = 'SAM Horns' COLLATE NOCASE),
   'French Horn', 'SWAV 14', 'SAM Horns 1. Main (far)', 'SAM H KEY - Basic A (f)', 'Layered between stacc and legato', NULL, 'SEQ_08 (Giza Plains - Preperation Phase)', 'main', 'ff_detailed', 15),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'ProjectSAM' COLLATE NOCASE AND p.name = 'SAM Horns' COLLATE NOCASE),
   'French Horn', 'SWAV 15', 'SAM Horns 1. Main (far)', 'SAM H KEY - Basic A (f)', 'Layered between stacc and legato', NULL, 'SEQ_08 (Giza Plains - Preperation Phase)', 'main', 'ff_detailed', 16),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'ProjectSAM' COLLATE NOCASE AND p.name = 'SAM Horns' COLLATE NOCASE),
   'French Horn', 'SWAV 16', 'SAM Horns 1. Main (far)', 'SAM H KEY - Basic A (f)', 'Layered between stacc and legato', NULL, 'SEQ_08 (Giza Plains - Preperation Phase)', 'main', 'ff_detailed', 17),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'ProjectSAM' COLLATE NOCASE AND p.name = 'SAM Horns' COLLATE NOCASE),
   'French Horn', 'SWAV 17', 'SAM Horns 1. Main (far)', 'SAM H KEY - Basic A (f)', 'Layered between stacc and legato', NULL, 'SEQ_08 (Giza Plains - Preperation Phase)', 'main', 'ff_detailed', 18),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'ProjectSAM' COLLATE NOCASE AND p.name = 'SAM Horns' COLLATE NOCASE),
   'French Horn', 'SWAV 18', 'SAM Horns 1. Main (far)', 'SAM H KEY - Basic A (f)', 'Layered between stacc and legato', NULL, 'SEQ_08 (Giza Plains - Preperation Phase)', 'main', 'ff_detailed', 19),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'XV-5080' COLLATE NOCASE),
   'Oboe', 'SWAV 19', 'PR-B', '104 Oboe Express', NULL, NULL, 'SEQ_08 (Giza Plains - Preperation Phase)', 'main', 'ff_detailed', 20),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'XV-5080' COLLATE NOCASE),
   'Oboe', 'SWAV 20', 'PR-B', '104 Oboe Express', NULL, NULL, 'SEQ_08 (Giza Plains - Preperation Phase)', 'main', 'ff_detailed', 21),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'XV-5080' COLLATE NOCASE),
   'Oboe', 'SWAV 21', 'PR-B', '104 Oboe Express', NULL, NULL, 'SEQ_08 (Giza Plains - Preperation Phase)', 'main', 'ff_detailed', 22),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'DS Soundware' COLLATE NOCASE AND p.name = 'Ultimate Orchestral Percussion' COLLATE NOCASE),
   'Orchestral Cymbal', 'SWAV 22', 'Orchestral Cymbals', 'Orchestral Cymbals', NULL, NULL, 'SEQ_08 (Giza Plains - Preperation Phase)', 'main', 'ff_detailed', 23),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'DS Soundware' COLLATE NOCASE AND p.name = 'Ultimate Orchestral Percussion' COLLATE NOCASE),
   'Orchestral Cymbal Crash', 'SWAV 23', 'Orchestral Cymbals', 'Orchestral Cymbals', NULL, NULL, 'SEQ_08 (Giza Plains - Preperation Phase)', 'main', 'ff_detailed', 24),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'), NULL, 'Tambourine', 'SWAV 24', NULL, NULL, NULL, 'CHECK', 'SEQ_08 (Giza Plains - Preperation Phase)', 'main', 'ff_detailed', 25),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'), NULL, 'Triangle', 'SWAV 25', NULL, NULL, NULL, 'CHECK', 'SEQ_08 (Giza Plains - Preperation Phase)', 'main', 'ff_detailed', 26),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JV-1080' COLLATE NOCASE),
   'Pizz Strings', 'SWAV 26', '046 PizzicatoStr', NULL, NULL, NULL, 'SEQ_08 (Giza Plains - Preperation Phase)', 'main', 'ff_detailed', 27),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JV-1080' COLLATE NOCASE),
   'Pizz Strings', 'SWAV 27', '046 PizzicatoStr', NULL, NULL, NULL, 'SEQ_08 (Giza Plains - Preperation Phase)', 'main', 'ff_detailed', 28),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JV-1080' COLLATE NOCASE),
   'Pizz Strings', 'SWAV 28', '046 PizzicatoStr', NULL, NULL, NULL, 'SEQ_08 (Giza Plains - Preperation Phase)', 'main', 'ff_detailed', 29),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'), NULL, 'Snare', 'SWAV 29', NULL, NULL, NULL, 'CHECK', 'SEQ_08 (Giza Plains - Preperation Phase)', 'main', 'ff_detailed', 30),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'), NULL, 'Timpani', 'SWAV 30', NULL, NULL, NULL, 'CHECK', 'SEQ_08 (Giza Plains - Preperation Phase)', 'main', 'ff_detailed', 31),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'), NULL, 'Trumpet', 'SWAV 31', NULL, NULL, NULL, 'CHECK', 'SEQ_08 (Giza Plains - Preperation Phase)', 'main', 'ff_detailed', 32),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'), NULL, 'Trumpet', 'SWAV 32', NULL, NULL, NULL, 'CHECK', 'SEQ_08 (Giza Plains - Preperation Phase)', 'main', 'ff_detailed', 33),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'), NULL, 'Trumpet', 'SWAV 33', NULL, NULL, NULL, 'CHECK', 'SEQ_08 (Giza Plains - Preperation Phase)', 'main', 'ff_detailed', 34),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'), NULL, 'Trumpet', 'SWAV 34', NULL, NULL, NULL, 'CHECK', 'SEQ_08 (Giza Plains - Preperation Phase)', 'main', 'ff_detailed', 35),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'XV-5080' COLLATE NOCASE),
   'String Ensemble', 'SWAV 35', 'PR-C', '035 St.Strings', NULL, NULL, 'SEQ_08 (Giza Plains - Preperation Phase)', 'main', 'ff_detailed', 36),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'XV-5080' COLLATE NOCASE),
   'String Ensemble', 'SWAV 36', 'PR-C', '035 St.Strings', NULL, NULL, 'SEQ_08 (Giza Plains - Preperation Phase)', 'main', 'ff_detailed', 37),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'XV-5080' COLLATE NOCASE),
   'String Ensemble', 'SWAV 37', 'PR-C', '035 St.Strings', NULL, NULL, 'SEQ_08 (Giza Plains - Preperation Phase)', 'main', 'ff_detailed', 38),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'XV-5080' COLLATE NOCASE),
   'String Ensemble', 'SWAV 38', 'PR-C', '035 St.Strings', NULL, NULL, 'SEQ_08 (Giza Plains - Preperation Phase)', 'main', 'ff_detailed', 39),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'XV-5080' COLLATE NOCASE),
   'String Ensemble', 'SWAV 39', 'PR-C', '035 St.Strings', NULL, NULL, 'SEQ_08 (Giza Plains - Preperation Phase)', 'main', 'ff_detailed', 40),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'XV-5080' COLLATE NOCASE),
   'String Ensemble', 'SWAV 40', 'PR-C', '035 St.Strings', NULL, NULL, 'SEQ_08 (Giza Plains - Preperation Phase)', 'main', 'ff_detailed', 41),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'XV-5080' COLLATE NOCASE),
   'String Ensemble', 'SWAV 41', 'PR-C', '035 St.Strings', NULL, NULL, 'SEQ_08 (Giza Plains - Preperation Phase)', 'main', 'ff_detailed', 42),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'XV-5080' COLLATE NOCASE),
   'String Ensemble', 'SWAV 42', 'PR-C', '035 St.Strings', NULL, NULL, 'SEQ_08 (Giza Plains - Preperation Phase)', 'main', 'ff_detailed', 43),
  -- =========================================================================
  -- SEQ_28BossBattle (Flash of Steel)
  -- =========================================================================
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'DS Soundware' COLLATE NOCASE AND p.name = 'Ultimate Orchestral Percussion' COLLATE NOCASE),
   'Orchestral Cymbal', 'SWAV 0', 'Orchestral Cymbals', 'Orchestral Cymbals', NULL, NULL, 'SEQ_28BossBattle (Flash of Steel)', 'main', 'ff_detailed', 44),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'DS Soundware' COLLATE NOCASE AND p.name = 'Ultimate Orchestral Percussion' COLLATE NOCASE),
   'Orchestral Cymbal Crash', 'SWAV 1', 'Orchestral Cymbals', 'Orchestral Cymbals', NULL, NULL, 'SEQ_28BossBattle (Flash of Steel)', 'main', 'ff_detailed', 45),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'), NULL, 'Timpani', 'SWAV 2', NULL, NULL, NULL, 'CHECK', 'SEQ_28BossBattle (Flash of Steel)', 'main', 'ff_detailed', 46),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'), NULL, 'Timpani', 'SWAV 3', NULL, NULL, NULL, 'CHECK', 'SEQ_28BossBattle (Flash of Steel)', 'main', 'ff_detailed', 47),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'), NULL, 'Trumpet', 'SWAV 4', NULL, NULL, 'Sounds like SR-JV80-02', 'CHECK', 'SEQ_28BossBattle (Flash of Steel)', 'main', 'ff_detailed', 48),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'), NULL, 'Trumpet', 'SWAV 5', NULL, NULL, 'Sounds like SR-JV80-02', 'CHECK', 'SEQ_28BossBattle (Flash of Steel)', 'main', 'ff_detailed', 49),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'), NULL, 'Trumpet', 'SWAV 6', NULL, NULL, 'Sounds like SR-JV80-02', 'CHECK', 'SEQ_28BossBattle (Flash of Steel)', 'main', 'ff_detailed', 50),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'), NULL, 'Trumpet', 'SWAV 7', NULL, NULL, 'Sounds like SR-JV80-02', 'CHECK', 'SEQ_28BossBattle (Flash of Steel)', 'main', 'ff_detailed', 51),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'), NULL, 'Tuba(?)', 'SWAV 8', NULL, NULL, 'Sounds like SR-JV80-02', 'CHECK', 'SEQ_28BossBattle (Flash of Steel)', 'main', 'ff_detailed', 52),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'), NULL, 'Tuba(?)', 'SWAV 9', NULL, NULL, NULL, 'CHECK', 'SEQ_28BossBattle (Flash of Steel)', 'main', 'ff_detailed', 53),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'), NULL, 'Tuba(?)', 'SWAV 10', NULL, NULL, NULL, 'CHECK', 'SEQ_28BossBattle (Flash of Steel)', 'main', 'ff_detailed', 54),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'), NULL, 'French Horn', 'SWAV 11', NULL, NULL, NULL, 'CHECK', 'SEQ_28BossBattle (Flash of Steel)', 'main', 'ff_detailed', 55),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'), NULL, 'French Horn', 'SWAV 12', NULL, NULL, NULL, 'CHECK', 'SEQ_28BossBattle (Flash of Steel)', 'main', 'ff_detailed', 56),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'), NULL, 'French Horn', 'SWAV 13', NULL, NULL, NULL, 'CHECK', 'SEQ_28BossBattle (Flash of Steel)', 'main', 'ff_detailed', 57),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'), NULL, 'French Horn', 'SWAV 14', NULL, NULL, NULL, 'CHECK', 'SEQ_28BossBattle (Flash of Steel)', 'main', 'ff_detailed', 58),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'), NULL, 'French Horn', 'SWAV 15', NULL, NULL, NULL, 'CHECK', 'SEQ_28BossBattle (Flash of Steel)', 'main', 'ff_detailed', 59),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'), NULL, 'Trombone', 'SWAV 16', NULL, NULL, NULL, 'CHECK', 'SEQ_28BossBattle (Flash of Steel)', 'main', 'ff_detailed', 60),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'), NULL, 'Trombone', 'SWAV 17', NULL, NULL, NULL, 'CHECK', 'SEQ_28BossBattle (Flash of Steel)', 'main', 'ff_detailed', 61),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'), NULL, 'Trombone', 'SWAV 18', NULL, NULL, NULL, 'CHECK', 'SEQ_28BossBattle (Flash of Steel)', 'main', 'ff_detailed', 62),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'), NULL, 'Trombone', 'SWAV 19', NULL, NULL, NULL, 'CHECK', 'SEQ_28BossBattle (Flash of Steel)', 'main', 'ff_detailed', 63),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'), NULL, 'Trombone', 'SWAV 20', NULL, NULL, NULL, 'CHECK', 'SEQ_28BossBattle (Flash of Steel)', 'main', 'ff_detailed', 64),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-05 World' COLLATE NOCASE),
   'Gong', 'SWAV 21', 'XP-X', '077 Gong Menu', NULL, NULL, 'SEQ_28BossBattle (Flash of Steel)', 'main', 'ff_detailed', 65),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'), NULL, 'Percussion Hit', 'SWAV 22', NULL, NULL, NULL, 'CHECK', 'SEQ_28BossBattle (Flash of Steel)', 'main', 'ff_detailed', 66),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'), NULL, 'Percussion Hit', 'SWAV 23', NULL, NULL, NULL, 'CHECK', 'SEQ_28BossBattle (Flash of Steel)', 'main', 'ff_detailed', 67),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'), NULL, 'Xylophone', 'SWAV 24', NULL, NULL, NULL, 'CHECK', 'SEQ_28BossBattle (Flash of Steel)', 'main', 'ff_detailed', 68),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'), NULL, 'Xylophone', 'SWAV 25', NULL, NULL, NULL, 'CHECK', 'SEQ_28BossBattle (Flash of Steel)', 'main', 'ff_detailed', 69),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'), NULL, 'Xylophone', 'SWAV 26', NULL, NULL, NULL, 'CHECK', 'SEQ_28BossBattle (Flash of Steel)', 'main', 'ff_detailed', 70),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'XV-5080' COLLATE NOCASE),
   'String Ensemble', 'SWAV 27', 'PR-C', '035 St.Strings', NULL, NULL, 'SEQ_28BossBattle (Flash of Steel)', 'main', 'ff_detailed', 71),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'XV-5080' COLLATE NOCASE),
   'String Ensemble', 'SWAV 28', 'PR-C', '035 St.Strings', NULL, NULL, 'SEQ_28BossBattle (Flash of Steel)', 'main', 'ff_detailed', 72),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'XV-5080' COLLATE NOCASE),
   'String Ensemble', 'SWAV 29', 'PR-C', '035 St.Strings', NULL, NULL, 'SEQ_28BossBattle (Flash of Steel)', 'main', 'ff_detailed', 73),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'XV-5080' COLLATE NOCASE),
   'String Ensemble', 'SWAV 30', 'PR-C', '035 St.Strings', NULL, NULL, 'SEQ_28BossBattle (Flash of Steel)', 'main', 'ff_detailed', 74),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'XV-5080' COLLATE NOCASE),
   'String Ensemble', 'SWAV 31', 'PR-C', '035 St.Strings', NULL, NULL, 'SEQ_28BossBattle (Flash of Steel)', 'main', 'ff_detailed', 75),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'XV-5080' COLLATE NOCASE),
   'String Ensemble', 'SWAV 32', 'PR-C', '035 St.Strings', NULL, NULL, 'SEQ_28BossBattle (Flash of Steel)', 'main', 'ff_detailed', 76),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'XV-5080' COLLATE NOCASE),
   'String Ensemble', 'SWAV 33', 'PR-C', '035 St.Strings', NULL, NULL, 'SEQ_28BossBattle (Flash of Steel)', 'main', 'ff_detailed', 77),
  ((SELECT id FROM games WHERE title = 'Final Fantasy XII: Revenant Wings'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'XV-5080' COLLATE NOCASE),
   'String Ensemble', 'SWAV 34', 'PR-C', '035 St.Strings', NULL, NULL, 'SEQ_28BossBattle (Flash of Steel)', 'main', 'ff_detailed', 78);
