-- Source: reference/Final Fantasy Sound Sources (Detailed) - Ivalice Alliance.csv
-- Section 5: Final Fantasy Tactics A2: Grimoire of the Rift (CSV rows 349-514).
-- Most thoroughly sourced game in the Ivalice file. 151 sample rows across 8 tracks
-- (4, 5, 8, 22, 27, 33, 35, 38). Track 35 is flagged "(Unused)" so its rows are
-- category 'unused'. "(OST Version only)" sub-headers switch following rows to
-- category 'bonus'.
-- Sonic Implants ships both "Symphonic Strings Collection" (plural) and "Symphonic
-- String Collection" (singular) in this CSV — preserved verbatim as distinct
-- products per the FF Detailed contributor-drift convention; cleanup deferred.
-- EastWest trailing-space source variants ("EastWest - Symphonic Orchestra ") are
-- normalized via internal-whitespace rule in the batch plan.

INSERT OR IGNORE INTO manufacturers (name) VALUES
  ('Sonic Implants');

INSERT OR IGNORE INTO products (manufacturer_id, name, type) VALUES
  ((SELECT id FROM manufacturers WHERE name = 'Sonic Implants' COLLATE NOCASE), 'Symphonic Strings Collection',  'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Sonic Implants' COLLATE NOCASE), 'Symphonic String Collection',   'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'ProjectSAM'     COLLATE NOCASE), 'SAM Trombone',                  'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'EastWest'       COLLATE NOCASE), 'Voices of the Apocalypse',      'Sample Library');

INSERT INTO games (title, platform, released, composers, composers_normalized, notes) VALUES
  ('Final Fantasy Tactics A2: Grimoire of the Rift',
   'Nintendo DS',
   '2007-10-25',
   'Hitoshi Sakimoto, Mitsuhiro Kaneda, Kazuko Umino, Yoshimi Kudo',
   'hitoshi sakimoto, mitsuhiro kaneda, kazuko umino, yoshimi kudo',
   'Source: Final Fantasy Sound Sources (Detailed) - Ivalice Alliance.csv (Section 5). Most actively documented Ivalice game in the CSV: 151 rows across 8 tracks. Tracks 5/27/33/35/38 are FFXII or FFTA arrangement references per their CSV titles. Track 35 ("To The Peak (Unused)") rows are category unused. (OST Version only) sub-headers route following rows to bonus.');

INSERT INTO usages
  (game_id, product_id, sample_label, sample_ref, path_bank, preset, notes, raw_source, examples, category, source_family, position)
VALUES
  -- =========================================================================
  -- Track 4: Unfold The Map
  -- =========================================================================
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-05 World' COLLATE NOCASE),
   'Bagpipes', 'SWAV 0', 'XP-X', '173 Velobagpipes', NULL, NULL, '4. Unfold The Map', 'main', 'ff_detailed', 1),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-05 World' COLLATE NOCASE),
   'Bagpipes', 'SWAV 1', 'XP-X', '173 Velobagpipes', NULL, NULL, '4. Unfold The Map', 'main', 'ff_detailed', 2),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-05 World' COLLATE NOCASE),
   'Bagpipes', 'SWAV 2', 'XP-X', '173 Velobagpipes', NULL, NULL, '4. Unfold The Map', 'main', 'ff_detailed', 3),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-05 World' COLLATE NOCASE),
   'Bagpipes', 'SWAV 3', 'XP-X', '173 Velobagpipes', NULL, NULL, '4. Unfold The Map', 'main', 'ff_detailed', 4),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-05 World' COLLATE NOCASE),
   'Bagpipes', 'SWAV 4', 'XP-X', '173 Velobagpipes', NULL, NULL, '4. Unfold The Map', 'main', 'ff_detailed', 5),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-05 World' COLLATE NOCASE),
   'Tambourine/Finger Cymbal', 'SWAV 5', 'XP-X', '082 AsiaCym', NULL, NULL, '4. Unfold The Map', 'main', 'ff_detailed', 6),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'), NULL, 'Conga', 'SWAV 6', NULL, NULL, NULL, 'UNKNOWN', '4. Unfold The Map', 'main', 'ff_detailed', 7),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-05 World' COLLATE NOCASE),
   'Finger Cymbal', 'SWAV 7', 'XP-X', '082 AsiaCym', NULL, NULL, '4. Unfold The Map', 'main', 'ff_detailed', 8),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-05 World' COLLATE NOCASE),
   'Mizmar', 'SWAV 8', 'XP-X', '125 Mizmar Solo', NULL, NULL, '4. Unfold The Map', 'main', 'ff_detailed', 9),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-05 World' COLLATE NOCASE),
   'Mizmar', 'SWAV 9', 'XP-X', '125 Mizmar Solo', NULL, NULL, '4. Unfold The Map', 'main', 'ff_detailed', 10),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-05 World' COLLATE NOCASE),
   'Mizmar', 'SWAV 10', 'XP-X', '125 Mizmar Solo', NULL, NULL, '4. Unfold The Map', 'main', 'ff_detailed', 11),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sonic Implants' COLLATE NOCASE AND p.name = 'Symphonic Strings Collection' COLLATE NOCASE),
   'Pizzicato Strings', 'SWAV 11', '07 Ensemble II -> Ensemble Pizzicato', 'Ensemble Pizzicato MW>Snap', NULL, NULL, '4. Unfold The Map', 'main', 'ff_detailed', 12),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sonic Implants' COLLATE NOCASE AND p.name = 'Symphonic Strings Collection' COLLATE NOCASE),
   'Pizzicato Strings', 'SWAV 12', '07 Ensemble II -> Ensemble Pizzicato', 'Ensemble Pizzicato MW>Snap', NULL, NULL, '4. Unfold The Map', 'main', 'ff_detailed', 13),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sonic Implants' COLLATE NOCASE AND p.name = 'Symphonic Strings Collection' COLLATE NOCASE),
   'Pizzicato Strings', 'SWAV 13', '07 Ensemble II -> Ensemble Pizzicato', 'Ensemble Pizzicato MW>Snap', NULL, NULL, '4. Unfold The Map', 'main', 'ff_detailed', 14),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sonic Implants' COLLATE NOCASE AND p.name = 'Symphonic Strings Collection' COLLATE NOCASE),
   'Pizzicato Strings', 'SWAV 14', '07 Ensemble II -> Ensemble Pizzicato', 'Ensemble Pizzicato MW>Snap', NULL, NULL, '4. Unfold The Map', 'main', 'ff_detailed', 15),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sonic Implants' COLLATE NOCASE AND p.name = 'Symphonic Strings Collection' COLLATE NOCASE),
   'Pizzicato Strings', 'SWAV 15', '07 Ensemble II -> Ensemble Pizzicato', 'Ensemble Pizzicato MW>Snap', NULL, NULL, '4. Unfold The Map', 'main', 'ff_detailed', 16),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sonic Implants' COLLATE NOCASE AND p.name = 'Symphonic Strings Collection' COLLATE NOCASE),
   'Pizzicato Strings', 'SWAV 16', '07 Ensemble II -> Ensemble Pizzicato', 'Ensemble Pizzicato MW>Snap', NULL, NULL, '4. Unfold The Map', 'main', 'ff_detailed', 17),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sonic Implants' COLLATE NOCASE AND p.name = 'Symphonic Strings Collection' COLLATE NOCASE),
   'Pizzicato Strings', 'SWAV 17', '07 Ensemble II -> Ensemble Pizzicato', 'Ensemble Pizzicato MW>Snap', NULL, NULL, '4. Unfold The Map', 'main', 'ff_detailed', 18),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sonic Implants' COLLATE NOCASE AND p.name = 'Symphonic Strings Collection' COLLATE NOCASE),
   'Pizzicato Strings', 'SWAV 18', '07 Ensemble II -> Ensemble Pizzicato', 'Ensemble Pizzicato MW>Snap', NULL, NULL, '4. Unfold The Map', 'main', 'ff_detailed', 19),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sonic Implants' COLLATE NOCASE AND p.name = 'Symphonic Strings Collection' COLLATE NOCASE),
   'Pizzicato Strings', 'SWAV 19', '07 Ensemble II -> Ensemble Pizzicato', 'Ensemble Pizzicato MW>Snap', NULL, NULL, '4. Unfold The Map', 'main', 'ff_detailed', 20),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sonic Implants' COLLATE NOCASE AND p.name = 'Symphonic String Collection' COLLATE NOCASE),
   'Sustain Strings', 'SWAV 20', '07 Ensemble I -> Ensemble Legato', 'Ensemble Legato', NULL, NULL, '4. Unfold The Map', 'main', 'ff_detailed', 21),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sonic Implants' COLLATE NOCASE AND p.name = 'Symphonic Strings Collection' COLLATE NOCASE),
   'Staccato Strings', 'SWAV 21', '07 - Ensemble II -> Ensemble Staccato ', 'Ensemble Staccato', NULL, NULL, '4. Unfold The Map', 'main', 'ff_detailed', 22),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sonic Implants' COLLATE NOCASE AND p.name = 'Symphonic String Collection' COLLATE NOCASE),
   'Sustain Strings', 'SWAV 22', '07 Ensemble I -> Ensemble Legato', 'Ensemble Legato', NULL, NULL, '4. Unfold The Map', 'main', 'ff_detailed', 23),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sonic Implants' COLLATE NOCASE AND p.name = 'Symphonic String Collection' COLLATE NOCASE),
   'Sustain Strings', 'SWAV 23', '07 Ensemble I -> Ensemble Legato', 'Ensemble Legato', NULL, NULL, '4. Unfold The Map', 'main', 'ff_detailed', 24),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sonic Implants' COLLATE NOCASE AND p.name = 'Symphonic String Collection' COLLATE NOCASE),
   'Sustain Strings', 'SWAV 24', '07 Ensemble I -> Ensemble Legato', 'Ensemble Legato', NULL, NULL, '4. Unfold The Map', 'main', 'ff_detailed', 25),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sonic Implants' COLLATE NOCASE AND p.name = 'Symphonic String Collection' COLLATE NOCASE),
   'Sustain Strings', 'SWAV 25', '07 Ensemble I -> Ensemble Legato', 'Ensemble Legato', NULL, NULL, '4. Unfold The Map', 'main', 'ff_detailed', 26),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sonic Implants' COLLATE NOCASE AND p.name = 'Symphonic String Collection' COLLATE NOCASE),
   'Sustain Strings', 'SWAV 26', '07 Ensemble I -> Ensemble Legato', 'Ensemble Legato', NULL, NULL, '4. Unfold The Map', 'main', 'ff_detailed', 27),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sonic Implants' COLLATE NOCASE AND p.name = 'Symphonic String Collection' COLLATE NOCASE),
   'Sustain Strings', 'SWAV 27', '07 Ensemble I -> Ensemble Legato', 'Ensemble Legato', NULL, NULL, '4. Unfold The Map', 'main', 'ff_detailed', 28),
  -- Track 4 (OST Version only)
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'), NULL, 'Gong', '---', NULL, NULL, 'Definately Roland', 'UNKNOWN', '4. Unfold The Map (OST Version only)', 'bonus', 'ff_detailed', 29),
  -- =========================================================================
  -- Track 5: Companions that Surpassed Their Races from FFT-A "Companions that Surpassed Their Races"
  -- =========================================================================
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'DS Soundware' COLLATE NOCASE AND p.name = 'Ultimate Orchestral Percussion' COLLATE NOCASE),
   'Cymbals', '---', 'Orchestral Cymbal', 'Orchestral Cymbal', NULL, NULL, '5. Companions that Surpassed Their Races from FFT-A "Companions that Surpassed Their Races"', 'main', 'ff_detailed', 30),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'DS Soundware' COLLATE NOCASE AND p.name = 'Ultimate Orchestral Percussion' COLLATE NOCASE),
   'Snare', '---', 'Orchestral Snare', 'Orchestral Snare', NULL, NULL, '5. Companions that Surpassed Their Races from FFT-A "Companions that Surpassed Their Races"', 'main', 'ff_detailed', 31),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'DS Soundware' COLLATE NOCASE AND p.name = 'Ultimate Orchestral Percussion' COLLATE NOCASE),
   'Triangle', '---', 'Orchestral Triangles', 'Orchestral Triangles', NULL, NULL, '5. Companions that Surpassed Their Races from FFT-A "Companions that Surpassed Their Races"', 'main', 'ff_detailed', 32),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'French Horn Ensemble', '---', 'Brass -> 6 French Horns -> 5 Keysw', '6FH KS Master', NULL, NULL, '5. Companions that Surpassed Their Races from FFT-A "Companions that Surpassed Their Races"', 'main', 'ff_detailed', 33),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'Flute', '---', 'Woodwinds -> 3 Oboes -> 5 Keysw', '3OB KS Master', NULL, NULL, '5. Companions that Surpassed Their Races from FFT-A "Companions that Surpassed Their Races"', 'main', 'ff_detailed', 34),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'Oboe Ensemble', '---', 'Woodwinds -> Solo Flute -> 5 Keysw', 'SFL KS Master', NULL, NULL, '5. Companions that Surpassed Their Races from FFT-A "Companions that Surpassed Their Races"', 'main', 'ff_detailed', 35),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'Glockenspiel', '---', 'Perc -> Metals', 'Glock', NULL, NULL, '5. Companions that Surpassed Their Races from FFT-A "Companions that Surpassed Their Races"', 'main', 'ff_detailed', 36),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Miroslav Vitous' COLLATE NOCASE AND p.name = 'Woodwind and Brass Ensembles 2.0' COLLATE NOCASE),
   'Trumpet', '---', 'Tps', 'Tps Port 1', NULL, NULL, '5. Companions that Surpassed Their Races from FFT-A "Companions that Surpassed Their Races"', 'main', 'ff_detailed', 37),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Miroslav Vitous' COLLATE NOCASE AND p.name = 'Woodwind and Brass Ensembles 2.0' COLLATE NOCASE),
   'Trumpet', '---', 'Tps', 'Tps Stacc 1', NULL, NULL, '5. Companions that Surpassed Their Races from FFT-A "Companions that Surpassed Their Races"', 'main', 'ff_detailed', 38),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Miroslav Vitous' COLLATE NOCASE AND p.name = 'Woodwind and Brass Ensembles 2.0' COLLATE NOCASE),
   'Trumpet', '---', 'Tps', 'Tps X', NULL, NULL, '5. Companions that Surpassed Their Races from FFT-A "Companions that Surpassed Their Races"', 'main', 'ff_detailed', 39),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'ProjectSAM' COLLATE NOCASE AND p.name = 'SAM Horns' COLLATE NOCASE),
   'French Horn Ensemble', '---', 'Sam H Key - Basic A (f)', 'Sam H Key - Basic A (f)', NULL, NULL, '5. Companions that Surpassed Their Races from FFT-A "Companions that Surpassed Their Races"', 'main', 'ff_detailed', 40),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'ProjectSAM' COLLATE NOCASE AND p.name = 'SAM Trombone' COLLATE NOCASE),
   'Trombone Ensemble', '---', 'Sam T Key - Basic A (f)', 'Sam T Key - Basic A (f)', NULL, NULL, '5. Companions that Surpassed Their Races from FFT-A "Companions that Surpassed Their Races"', 'main', 'ff_detailed', 41),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sonic Implants' COLLATE NOCASE AND p.name = 'Symphonic Strings Collection' COLLATE NOCASE),
   'Pizzicato Strings', '---', '07 Ensemble II -> Ensemble Pizzicato', 'Ensemble Pizzicato MW>Snap', NULL, NULL, '5. Companions that Surpassed Their Races from FFT-A "Companions that Surpassed Their Races"', 'main', 'ff_detailed', 42),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sonic Implants' COLLATE NOCASE AND p.name = 'Symphonic String Collection' COLLATE NOCASE),
   'Sustain Strings', '---', '07 Ensemble I -> Ensemble Legato', 'Ensemble Legato', NULL, NULL, '5. Companions that Surpassed Their Races from FFT-A "Companions that Surpassed Their Races"', 'main', 'ff_detailed', 43),
  -- =========================================================================
  -- Track 8: Knowledge of the Adventurer
  -- =========================================================================
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'DS Soundware' COLLATE NOCASE AND p.name = 'Ultimate Orchestral Percussion' COLLATE NOCASE),
   'Cymbals', '---', 'Orchestral Cymbal', 'Orchestral Cymbal', NULL, NULL, '8. Knowledge of the Adventurer', 'main', 'ff_detailed', 44),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'DS Soundware' COLLATE NOCASE AND p.name = 'Ultimate Orchestral Percussion' COLLATE NOCASE),
   'Tambourine', '---', 'Orchestral Tambourines', 'Orchestral Tambourines', NULL, NULL, '8. Knowledge of the Adventurer', 'main', 'ff_detailed', 45),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'DS Soundware' COLLATE NOCASE AND p.name = 'Ultimate Orchestral Percussion' COLLATE NOCASE),
   'Timpani', '---', 'Med Hard Timpani', 'Med Hard Timpani', NULL, NULL, '8. Knowledge of the Adventurer', 'main', 'ff_detailed', 46),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'DS Soundware' COLLATE NOCASE AND p.name = 'Ultimate Orchestral Percussion' COLLATE NOCASE),
   'Triangle', '---', 'Orchestral Triangles', 'Orchestral Triangles', NULL, NULL, '8. Knowledge of the Adventurer', 'main', 'ff_detailed', 47),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'DS Soundware' COLLATE NOCASE AND p.name = 'Ultimate Orchestral Percussion' COLLATE NOCASE),
   'Wind Chime', '---', NULL, NULL, NULL, NULL, '8. Knowledge of the Adventurer', 'main', 'ff_detailed', 48),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'Tuba', '---', 'Brass -> Solo Tuba -> 5 Keysw', 'STU KS Master', NULL, NULL, '8. Knowledge of the Adventurer', 'main', 'ff_detailed', 49),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'Oboe Ensemble', '---', 'Woodwinds -> 3 Oboes -> 5 Keysw', '3OB KS Master', NULL, NULL, '8. Knowledge of the Adventurer', 'main', 'ff_detailed', 50),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'Flute', '---', 'Woodwinds -> Solo Flute -> 5 Keysw', 'SFL KS Master', NULL, NULL, '8. Knowledge of the Adventurer', 'main', 'ff_detailed', 51),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'Glockenspiel', '---', 'Perc -> Metals', 'Glock', NULL, NULL, '8. Knowledge of the Adventurer', 'main', 'ff_detailed', 52),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Miroslav Vitous' COLLATE NOCASE AND p.name = 'Woodwind and Brass Ensembles 2.0' COLLATE NOCASE),
   'Trumpet', '---', 'Tps', 'Tps Port 1', NULL, NULL, '8. Knowledge of the Adventurer', 'main', 'ff_detailed', 53),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Miroslav Vitous' COLLATE NOCASE AND p.name = 'Woodwind and Brass Ensembles 2.0' COLLATE NOCASE),
   'Trumpet', '---', 'Tps', 'Tps Stacc 1', NULL, NULL, '8. Knowledge of the Adventurer', 'main', 'ff_detailed', 54),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Miroslav Vitous' COLLATE NOCASE AND p.name = 'Woodwind and Brass Ensembles 2.0' COLLATE NOCASE),
   'Trumpet', '---', 'Tps', 'Tps X', NULL, NULL, '8. Knowledge of the Adventurer', 'main', 'ff_detailed', 55),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'ProjectSAM' COLLATE NOCASE AND p.name = 'SAM Horns' COLLATE NOCASE),
   'French Horn Ensemble', '---', 'Sam H Key - Basic A (f)', 'Sam H Key - Basic A (f)', NULL, NULL, '8. Knowledge of the Adventurer', 'main', 'ff_detailed', 56),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'ProjectSAM' COLLATE NOCASE AND p.name = 'SAM Trombone' COLLATE NOCASE),
   'Trombone Ensemble', '---', 'Sam T Key - Basic A (f)', 'Sam T Key - Basic A (f)', NULL, NULL, '8. Knowledge of the Adventurer', 'main', 'ff_detailed', 57),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sonic Implants' COLLATE NOCASE AND p.name = 'Symphonic Strings Collection' COLLATE NOCASE),
   'Col Legno Strings', '---', '07 Ensemble II -> Ensemble Col Legno', 'Col Legno', NULL, NULL, '8. Knowledge of the Adventurer', 'main', 'ff_detailed', 58),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sonic Implants' COLLATE NOCASE AND p.name = 'Symphonic Strings Collection' COLLATE NOCASE),
   'Pizzicato Strings', '---', '07 Ensemble II -> Ensemble Pizzicato', 'Ensemble Pizzicato MW>Snap', NULL, NULL, '8. Knowledge of the Adventurer', 'main', 'ff_detailed', 59),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sonic Implants' COLLATE NOCASE AND p.name = 'Symphonic Strings Collection' COLLATE NOCASE),
   'Staccato Strings', '---', '07 - Ensemble II -> Ensemble Staccato ', 'Ensemble Staccato', NULL, NULL, '8. Knowledge of the Adventurer', 'main', 'ff_detailed', 60),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sonic Implants' COLLATE NOCASE AND p.name = 'Symphonic String Collection' COLLATE NOCASE),
   'Sustain Strings', '---', '07 Ensemble I -> Ensemble Legato', 'Ensemble Legato', NULL, NULL, '8. Knowledge of the Adventurer', 'main', 'ff_detailed', 61),
  -- =========================================================================
  -- Track 22: Determination
  -- =========================================================================
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'DS Soundware' COLLATE NOCASE AND p.name = 'Ultimate Orchestral Percussion' COLLATE NOCASE),
   'Cymbal', '---', 'Orchestral Cymbal', 'Orchestral Cymbal', NULL, NULL, '22. Determination', 'main', 'ff_detailed', 62),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'DS Soundware' COLLATE NOCASE AND p.name = 'Ultimate Orchestral Percussion' COLLATE NOCASE),
   'Timpani', '---', 'Med Hard Timpani', 'Med Hard Timpani', NULL, NULL, '22. Determination', 'main', 'ff_detailed', 63),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'French Horn Ensemble', '---', 'Brass -> 6 French Horns -> 5 Keysw', '6FH KS Master', NULL, NULL, '22. Determination', 'main', 'ff_detailed', 64),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'Xylophone', '---', 'Perc -> Wood', 'Xylophone', NULL, NULL, '22. Determination', 'main', 'ff_detailed', 65),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sonic Implants' COLLATE NOCASE AND p.name = 'Symphonic String Collection' COLLATE NOCASE),
   'Spiccato String', '---', '07 - Ensemble II -> Ensemble Spiccato', 'Ensemble Spiccato', NULL, NULL, '22. Determination', 'main', 'ff_detailed', 66),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sonic Implants' COLLATE NOCASE AND p.name = 'Symphonic String Collection' COLLATE NOCASE),
   'Sustain String', '---', '07 Ensemble I -> Ensemble Legato', 'Ensemble Legato', NULL, NULL, '22. Determination', 'main', 'ff_detailed', 67),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sonic Implants' COLLATE NOCASE AND p.name = 'Symphonic String Collection' COLLATE NOCASE),
   'Col Legno Strings', '---', '07 - Ensemble II -> Ensemble Col Legno', 'Col Legno', NULL, NULL, '22. Determination', 'main', 'ff_detailed', 68),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'ProjectSAM' COLLATE NOCASE AND p.name = 'SAM Trombone' COLLATE NOCASE),
   'Trombone Ensemble', '---', 'Sam T Key - Basic A (f)', 'Sam T Key - Basic A (f)', NULL, NULL, '22. Determination', 'main', 'ff_detailed', 69),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Miroslav Vitous' COLLATE NOCASE AND p.name = 'Woodwind and Brass Ensembles 2.0' COLLATE NOCASE),
   'Trumpet', '---', 'Tps', 'Tps Port 1', NULL, NULL, '22. Determination', 'main', 'ff_detailed', 70),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Miroslav Vitous' COLLATE NOCASE AND p.name = 'Woodwind and Brass Ensembles 2.0' COLLATE NOCASE),
   'Trumpet', '---', 'Tps', 'Tps Stacc 1', NULL, NULL, '22. Determination', 'main', 'ff_detailed', 71),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Miroslav Vitous' COLLATE NOCASE AND p.name = 'Woodwind and Brass Ensembles 2.0' COLLATE NOCASE),
   'Trumpet', '---', 'Tps', 'Tps X', NULL, NULL, '22. Determination', 'main', 'ff_detailed', 72),
  -- =========================================================================
  -- Track 27: A Beating Heart from FFXII "The Mosphoran Highwaste"
  -- =========================================================================
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'DS Soundware' COLLATE NOCASE AND p.name = 'Ultimate Orchestral Percussion' COLLATE NOCASE),
   'Cymbal', '---', 'Orchestral Cymbal', 'Orchestral Cymbal', NULL, NULL, '27. A Beating Heart from FFXII "The Mosphoran Highwaste"', 'main', 'ff_detailed', 73),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'), NULL, 'Snare ', '---', NULL, NULL, NULL, 'UNKNOWN', '27. A Beating Heart from FFXII "The Mosphoran Highwaste"', 'main', 'ff_detailed', 74),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'DS Soundware' COLLATE NOCASE AND p.name = 'Ultimate Orchestral Percussion' COLLATE NOCASE),
   'Timpani', '---', 'Med Hard Timpani', 'Med Hard Timpani', NULL, NULL, '27. A Beating Heart from FFXII "The Mosphoran Highwaste"', 'main', 'ff_detailed', 75),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'), NULL, 'Bass Drum(?)', '---', NULL, NULL, NULL, 'UNKNOWN', '27. A Beating Heart from FFXII "The Mosphoran Highwaste"', 'main', 'ff_detailed', 76),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'French Horn Ensemble', '---', 'Brass -> 6 French Horns -> 5 Keysw', '6FH KS Master', NULL, NULL, '27. A Beating Heart from FFXII "The Mosphoran Highwaste"', 'main', 'ff_detailed', 77),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'Tubular Bells', '---', 'Perc -> Metals', 'Orch chimes', NULL, NULL, '27. A Beating Heart from FFXII "The Mosphoran Highwaste"', 'main', 'ff_detailed', 78),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'), NULL, 'Flute', '---', NULL, NULL, 'Sounds like Roland', 'UNKNOWN', '27. A Beating Heart from FFXII "The Mosphoran Highwaste"', 'main', 'ff_detailed', 79),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'ProjectSAM' COLLATE NOCASE AND p.name = 'SAM Horns' COLLATE NOCASE),
   'French Horn Ensemble Layer', '---', 'Sam H Key - Basic A (f)', 'Sam H Key - Basic A (f)', NULL, NULL, '27. A Beating Heart from FFXII "The Mosphoran Highwaste"', 'main', 'ff_detailed', 80),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'ProjectSAM' COLLATE NOCASE AND p.name = 'SAM Trombone' COLLATE NOCASE),
   'Trombone Ensemble', '---', 'Sam T Key - Basic A (f)', 'Sam T Key - Basic A (f)', NULL, NULL, '27. A Beating Heart from FFXII "The Mosphoran Highwaste"', 'main', 'ff_detailed', 81),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'), NULL, 'Trumpet Ensemble', '---', NULL, NULL, NULL, 'CHECK', '27. A Beating Heart from FFXII "The Mosphoran Highwaste"', 'main', 'ff_detailed', 82),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sonic Implants' COLLATE NOCASE AND p.name = 'Symphonic String Collection' COLLATE NOCASE),
   'Staccato Strings', '---', '07 - Ensemble II -> Ensemble Spiccato', 'Ensemble Spiccato', NULL, NULL, '27. A Beating Heart from FFXII "The Mosphoran Highwaste"', 'main', 'ff_detailed', 83),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sonic Implants' COLLATE NOCASE AND p.name = 'Symphonic String Collection' COLLATE NOCASE),
   'Sustain Strings', '---', '07 Ensemble I -> Ensemble Legato', 'Ensemble Legato', NULL, NULL, '27. A Beating Heart from FFXII "The Mosphoran Highwaste"', 'main', 'ff_detailed', 84),
  -- =========================================================================
  -- Track 33: Crossing Over the Hill from FFXII "Ozmone Plains"
  -- =========================================================================
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'Cymbal', '---', 'Perc -> CymGong', 'All Cymbals', NULL, NULL, '33. Crossing Over the Hill from FFXII "Ozmone Plains"', 'main', 'ff_detailed', 85),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'DS Soundware' COLLATE NOCASE AND p.name = 'Ultimate Orchestral Percussion' COLLATE NOCASE),
   'Tambourine', '---', NULL, NULL, NULL, NULL, '33. Crossing Over the Hill from FFXII "Ozmone Plains"', 'main', 'ff_detailed', 86),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'DS Soundware' COLLATE NOCASE AND p.name = 'Ultimate Orchestral Percussion' COLLATE NOCASE),
   'Timpani', '---', 'Med Hard Timpani', 'Med Hard Timpani', NULL, NULL, '33. Crossing Over the Hill from FFXII "Ozmone Plains"', 'main', 'ff_detailed', 87),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'DS Soundware' COLLATE NOCASE AND p.name = 'Ultimate Orchestral Percussion' COLLATE NOCASE),
   'Triangle', '---', 'Orchestral Triangles', 'Orchestral Triangles', NULL, NULL, '33. Crossing Over the Hill from FFXII "Ozmone Plains"', 'main', 'ff_detailed', 88),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'Flute', '---', 'Woodwinds -> Solo Flute -> 5 Keysw', 'SFL KS Master', NULL, NULL, '33. Crossing Over the Hill from FFXII "Ozmone Plains"', 'main', 'ff_detailed', 89),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'Oboe Ensemble', '---', 'Woodwinds -> 3 Oboes -> 5 Keysw', '3OB KS Master', NULL, NULL, '33. Crossing Over the Hill from FFXII "Ozmone Plains"', 'main', 'ff_detailed', 90),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'Clarinet Ensemble', '---', 'Woodwinds -> 3 Clarinets -> 5 Keysw', '3CL KS Master', NULL, NULL, '33. Crossing Over the Hill from FFXII "Ozmone Plains"', 'main', 'ff_detailed', 91),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'Bassoon', '---', 'Woodwinds -> Bassoon -> 5 Keysw', 'BSN KS Master', NULL, NULL, '33. Crossing Over the Hill from FFXII "Ozmone Plains"', 'main', 'ff_detailed', 92),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'Glockenspiel', '---', 'Perc -> Metals', 'Glock', NULL, NULL, '33. Crossing Over the Hill from FFXII "Ozmone Plains"', 'main', 'ff_detailed', 93),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'Vibraphone', '---', 'Perc -> Metals', 'Vibes', NULL, NULL, '33. Crossing Over the Hill from FFXII "Ozmone Plains"', 'main', 'ff_detailed', 94),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'Wood Blocks', '---', 'Perc -> Wood', 'Various Percussion', NULL, NULL, '33. Crossing Over the Hill from FFXII "Ozmone Plains"', 'main', 'ff_detailed', 95),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'Xylophone', '---', 'Perc -> Wood', 'Xylophone', NULL, NULL, '33. Crossing Over the Hill from FFXII "Ozmone Plains"', 'main', 'ff_detailed', 96),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Voices of the Apocalypse' COLLATE NOCASE),
   '"Ooh-Aah" Choir', '---', 'Women''s Choir V.2', 'WC ah-oh MOD', NULL, NULL, '33. Crossing Over the Hill from FFXII "Ozmone Plains"', 'main', 'ff_detailed', 97),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'Harp', '---', 'Strings -> Harp -> 1 Long', 'Harp Pluck', NULL, NULL, '33. Crossing Over the Hill from FFXII "Ozmone Plains"', 'main', 'ff_detailed', 98),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'), NULL, 'Trumpet', '---', NULL, NULL, NULL, 'CHECK', '33. Crossing Over the Hill from FFXII "Ozmone Plains"', 'main', 'ff_detailed', 99),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'), NULL, 'Trumpet', '---', NULL, NULL, NULL, 'CHECK', '33. Crossing Over the Hill from FFXII "Ozmone Plains"', 'main', 'ff_detailed', 100),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'ProjectSAM' COLLATE NOCASE AND p.name = 'SAM Horns' COLLATE NOCASE),
   'French Horn Ensemble', '---', 'Sam H Key - Basic A (f)', 'Sam H Key - Basic A (f)', NULL, NULL, '33. Crossing Over the Hill from FFXII "Ozmone Plains"', 'main', 'ff_detailed', 101),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sonic Implants' COLLATE NOCASE AND p.name = 'Symphonic Strings Collection' COLLATE NOCASE),
   'Pizzicato Strings', '---', '07 Ensemble II -> Ensemble Pizzicato', 'Ensemble Pizzicato MW>Snap', NULL, NULL, '33. Crossing Over the Hill from FFXII "Ozmone Plains"', 'main', 'ff_detailed', 102),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sonic Implants' COLLATE NOCASE AND p.name = 'Symphonic String Collection' COLLATE NOCASE),
   'Sustain Strings', '---', '06 Ensemble I -> Ensemble Legato', 'Ensemble Legato', NULL, NULL, '33. Crossing Over the Hill from FFXII "Ozmone Plains"', 'main', 'ff_detailed', 103),
  -- =========================================================================
  -- Track 35: To The Peak from FFXII "To The Peak" (Unused) — category 'unused'
  -- =========================================================================
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'DS Soundware' COLLATE NOCASE AND p.name = 'Ultimate Orchestral Percussion' COLLATE NOCASE),
   'Cymbal', '---', 'Orchestral Cymbals', 'Orchestral Cymbals', NULL, NULL, '35. To The Peak from FFXII "To The Peak" (Unused)', 'unused', 'ff_detailed', 104),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'Tambourine', '---', 'Perc -> Wood', 'Various Percussion', NULL, NULL, '35. To The Peak from FFXII "To The Peak" (Unused)', 'unused', 'ff_detailed', 105),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'DS Soundware' COLLATE NOCASE AND p.name = 'Ultimate Orchestral Percussion' COLLATE NOCASE),
   'Timpani', '---', 'Med Hard Timpani', 'Med Hard Timpani', NULL, NULL, '35. To The Peak from FFXII "To The Peak" (Unused)', 'unused', 'ff_detailed', 106),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'Flute', '---', 'Woodwinds -> Solo Flute -> 5 Keysw', 'SFL KS Master', NULL, NULL, '35. To The Peak from FFXII "To The Peak" (Unused)', 'unused', 'ff_detailed', 107),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'Oboe Ensemble', '---', 'Woodwinds -> 3 Oboes -> 5 Keysw', '3OB KS Master', NULL, NULL, '35. To The Peak from FFXII "To The Peak" (Unused)', 'unused', 'ff_detailed', 108),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'Bassoon', '---', 'Woodwinds -> Bassoon -> 5 Keysw', 'BSN KS Master', NULL, NULL, '35. To The Peak from FFXII "To The Peak" (Unused)', 'unused', 'ff_detailed', 109),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'Trumpet Ensemble', '---', 'Brass -> 4 Trumpets -> 5 Keysw', '4TP KS Master', NULL, NULL, '35. To The Peak from FFXII "To The Peak" (Unused)', 'unused', 'ff_detailed', 110),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'French Horn Ensemble', '---', 'Brass -> 6 French Horns -> 5 Keysw', '6FH KS Master', NULL, NULL, '35. To The Peak from FFXII "To The Peak" (Unused)', 'unused', 'ff_detailed', 111),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'), NULL, 'Gong', '---', NULL, NULL, NULL, 'CHECK', '35. To The Peak from FFXII "To The Peak" (Unused)', 'unused', 'ff_detailed', 112),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'Timpani', NULL, 'Perc -> Drums', 'Timp Hits LR', NULL, NULL, '35. To The Peak from FFXII "To The Peak" (Unused)', 'unused', 'ff_detailed', 113),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'Tubular Bell', '---', 'Perc -> Metals', 'Orch chimes', NULL, NULL, '35. To The Peak from FFXII "To The Peak" (Unused)', 'unused', 'ff_detailed', 114),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'Harp', '---', 'Strings -> Harp -> 1 Long', 'Harp Pluck', NULL, NULL, '35. To The Peak from FFXII "To The Peak" (Unused)', 'unused', 'ff_detailed', 115),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'Violin Ensemble', '---', NULL, NULL, NULL, NULL, '35. To The Peak from FFXII "To The Peak" (Unused)', 'unused', 'ff_detailed', 116),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'Cello Ensemble', '---', NULL, NULL, NULL, NULL, '35. To The Peak from FFXII "To The Peak" (Unused)', 'unused', 'ff_detailed', 117),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'ProjectSAM' COLLATE NOCASE AND p.name = 'SAM Trombone' COLLATE NOCASE),
   'Trombone Ensemble', '---', 'Sam T Key - Basic A (f)', 'Sam T Key - Basic A (f)', NULL, NULL, '35. To The Peak from FFXII "To The Peak" (Unused)', 'unused', 'ff_detailed', 118),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sonic Implants' COLLATE NOCASE AND p.name = 'Symphonic String Collection' COLLATE NOCASE),
   'Pizzicato Strings', '---', '07 Ensemble II -> Ensemble Pizzicato', 'Ensemble Pizzicato MW>Snap', NULL, NULL, '35. To The Peak from FFXII "To The Peak" (Unused)', 'unused', 'ff_detailed', 119),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sonic Implants' COLLATE NOCASE AND p.name = 'Symphonic String Collection' COLLATE NOCASE),
   'Slow String Ensemble', '---', '06 Ensemble I -> Ensemble Espressivo', 'Ensemble Espressivo 3-Layer NR', NULL, NULL, '35. To The Peak from FFXII "To The Peak" (Unused)', 'unused', 'ff_detailed', 120),
  -- =========================================================================
  -- Track 38: Sky Pirates from the East from FFXII "Penelo's Theme"
  -- =========================================================================
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'Bassoon(?)', 'SWAV 0', 'Woodwinds -> Bassoon -> 5 Keysw', 'BSN KS Master', 'Definately present on the OST release, unsure about in-game', NULL, '38. Sky Pirates from the East from FFXII "Penelo''s Theme"', 'main', 'ff_detailed', 121),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'Castanets', 'SWAV 1', 'Perc -> Wood', 'Various Percussion', NULL, NULL, '38. Sky Pirates from the East from FFXII "Penelo''s Theme"', 'main', 'ff_detailed', 122),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'Castanets', 'SWAV 2', 'Perc -> Wood', 'Various Percussion', NULL, NULL, '38. Sky Pirates from the East from FFXII "Penelo''s Theme"', 'main', 'ff_detailed', 123),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'Castanets', 'SWAV 3', 'Perc -> Wood', 'Various Percussion', NULL, NULL, '38. Sky Pirates from the East from FFXII "Penelo''s Theme"', 'main', 'ff_detailed', 124),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'Clarinet', 'SWAV 4', 'Woodwinds -> Solo Clarinet', 'CHECK', NULL, NULL, '38. Sky Pirates from the East from FFXII "Penelo''s Theme"', 'main', 'ff_detailed', 125),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'Clarinet', 'SWAV 5', 'Woodwinds -> Solo Clarinet', 'CHECK', NULL, NULL, '38. Sky Pirates from the East from FFXII "Penelo''s Theme"', 'main', 'ff_detailed', 126),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'Clarinet', 'SWAV 6', 'Woodwinds -> Solo Clarinet', 'CHECK', NULL, NULL, '38. Sky Pirates from the East from FFXII "Penelo''s Theme"', 'main', 'ff_detailed', 127),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'Flute', 'SWAV 7', 'Woodwinds -> Solo Flute ', 'CHECK', NULL, NULL, '38. Sky Pirates from the East from FFXII "Penelo''s Theme"', 'main', 'ff_detailed', 128),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'Flute', 'SWAV 8', 'Woodwinds -> Solo Flute ', 'CHECK', NULL, NULL, '38. Sky Pirates from the East from FFXII "Penelo''s Theme"', 'main', 'ff_detailed', 129),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'Clarinet', 'SWAV 9', 'Woodwinds -> Solo Clarinet', 'CHECK', NULL, NULL, '38. Sky Pirates from the East from FFXII "Penelo''s Theme"', 'main', 'ff_detailed', 130),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'Clarinet', 'SWAV 10', 'Woodwinds -> Solo Clarinet', 'CHECK', NULL, NULL, '38. Sky Pirates from the East from FFXII "Penelo''s Theme"', 'main', 'ff_detailed', 131),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'Oboe', 'SWAV 11', 'Woodwinds -> Solo Oboe -> 5 Keysw', 'SOB KS Master', 'Definately present on the OST release, unsure about in-game', NULL, '38. Sky Pirates from the East from FFXII "Penelo''s Theme"', 'main', 'ff_detailed', 132),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'Oboe', 'SWAV 12', 'Woodwinds -> Solo Oboe -> 5 Keysw', 'SOB KS Master', 'Definately present on the OST release, unsure about in-game', NULL, '38. Sky Pirates from the East from FFXII "Penelo''s Theme"', 'main', 'ff_detailed', 133),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'Oboe', 'SWAV 13', 'Woodwinds -> Solo Oboe -> 5 Keysw', 'SOB KS Master', 'Definately present on the OST release, unsure about in-game', NULL, '38. Sky Pirates from the East from FFXII "Penelo''s Theme"', 'main', 'ff_detailed', 134),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sonic Implants' COLLATE NOCASE AND p.name = 'Symphonic String Collection' COLLATE NOCASE),
   'Pizzicato Strings', 'SWAV 14', '07 Ensemble II -> Ensemble Pizzicato', 'Ensemble Pizzicato MW>Snap', NULL, NULL, '38. Sky Pirates from the East from FFXII "Penelo''s Theme"', 'main', 'ff_detailed', 135),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sonic Implants' COLLATE NOCASE AND p.name = 'Symphonic String Collection' COLLATE NOCASE),
   'Pizzicato Strings', 'SWAV 15', '07 Ensemble II -> Ensemble Pizzicato', 'Ensemble Pizzicato MW>Snap', NULL, NULL, '38. Sky Pirates from the East from FFXII "Penelo''s Theme"', 'main', 'ff_detailed', 136),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sonic Implants' COLLATE NOCASE AND p.name = 'Symphonic String Collection' COLLATE NOCASE),
   'Pizzicato Strings', 'SWAV 16', '07 Ensemble II -> Ensemble Pizzicato', 'Ensemble Pizzicato MW>Snap', NULL, NULL, '38. Sky Pirates from the East from FFXII "Penelo''s Theme"', 'main', 'ff_detailed', 137),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sonic Implants' COLLATE NOCASE AND p.name = 'Symphonic String Collection' COLLATE NOCASE),
   'Pizzicato Strings', 'SWAV 17', '07 Ensemble II -> Ensemble Pizzicato', 'Ensemble Pizzicato MW>Snap', NULL, NULL, '38. Sky Pirates from the East from FFXII "Penelo''s Theme"', 'main', 'ff_detailed', 138),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sonic Implants' COLLATE NOCASE AND p.name = 'Symphonic String Collection' COLLATE NOCASE),
   'Pizzicato Strings', 'SWAV 18', '07 Ensemble II -> Ensemble Pizzicato', 'Ensemble Pizzicato MW>Snap', NULL, NULL, '38. Sky Pirates from the East from FFXII "Penelo''s Theme"', 'main', 'ff_detailed', 139),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sonic Implants' COLLATE NOCASE AND p.name = 'Symphonic String Collection' COLLATE NOCASE),
   'Pizzicato Strings', 'SWAV 19', '07 Ensemble II -> Ensemble Pizzicato', 'Ensemble Pizzicato MW>Snap', NULL, NULL, '38. Sky Pirates from the East from FFXII "Penelo''s Theme"', 'main', 'ff_detailed', 140),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sonic Implants' COLLATE NOCASE AND p.name = 'Symphonic String Collection' COLLATE NOCASE),
   'Sustain Strings', 'SWAV 20', '06 Ensemble I -> Ensemble Legato', 'Ensemble Legato', NULL, NULL, '38. Sky Pirates from the East from FFXII "Penelo''s Theme"', 'main', 'ff_detailed', 141),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sonic Implants' COLLATE NOCASE AND p.name = 'Symphonic String Collection' COLLATE NOCASE),
   'Sustain Strings', 'SWAV 21', '06 Ensemble I -> Ensemble Legato', 'Ensemble Legato', NULL, NULL, '38. Sky Pirates from the East from FFXII "Penelo''s Theme"', 'main', 'ff_detailed', 142),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sonic Implants' COLLATE NOCASE AND p.name = 'Symphonic String Collection' COLLATE NOCASE),
   'Sustain Strings', 'SWAV 22', '06 Ensemble I -> Ensemble Legato', 'Ensemble Legato', NULL, NULL, '38. Sky Pirates from the East from FFXII "Penelo''s Theme"', 'main', 'ff_detailed', 143),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sonic Implants' COLLATE NOCASE AND p.name = 'Symphonic String Collection' COLLATE NOCASE),
   'Sustain Strings', 'SWAV 23', '06 Ensemble I -> Ensemble Legato', 'Ensemble Legato', NULL, NULL, '38. Sky Pirates from the East from FFXII "Penelo''s Theme"', 'main', 'ff_detailed', 144),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sonic Implants' COLLATE NOCASE AND p.name = 'Symphonic String Collection' COLLATE NOCASE),
   'Sustain Strings', 'SWAV 24', '06 Ensemble I -> Ensemble Legato', 'Ensemble Legato', NULL, NULL, '38. Sky Pirates from the East from FFXII "Penelo''s Theme"', 'main', 'ff_detailed', 145),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sonic Implants' COLLATE NOCASE AND p.name = 'Symphonic String Collection' COLLATE NOCASE),
   'Sustain Strings', 'SWAV 25', '06 Ensemble I -> Ensemble Legato', 'Ensemble Legato', NULL, NULL, '38. Sky Pirates from the East from FFXII "Penelo''s Theme"', 'main', 'ff_detailed', 146),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sonic Implants' COLLATE NOCASE AND p.name = 'Symphonic String Collection' COLLATE NOCASE),
   'Sustain Strings', 'SWAV 26', '06 Ensemble I -> Ensemble Legato', 'Ensemble Legato', NULL, NULL, '38. Sky Pirates from the East from FFXII "Penelo''s Theme"', 'main', 'ff_detailed', 147),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'DS Soundware' COLLATE NOCASE AND p.name = 'Ultimate Orchestral Percussion' COLLATE NOCASE),
   'Triangle', 'SWAV 27', 'Med Hard Timpani', 'Med Hard Timpani', NULL, NULL, '38. Sky Pirates from the East from FFXII "Penelo''s Theme"', 'main', 'ff_detailed', 148),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'DS Soundware' COLLATE NOCASE AND p.name = 'Ultimate Orchestral Percussion' COLLATE NOCASE),
   'Triangle', 'SWAV 28', 'Med Hard Timpani', 'Med Hard Timpani', NULL, NULL, '38. Sky Pirates from the East from FFXII "Penelo''s Theme"', 'main', 'ff_detailed', 149),
  -- Track 38 (OST Version only)
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'), NULL, 'Strings', '---', NULL, NULL, NULL, NULL, '38. Sky Pirates from the East from FFXII "Penelo''s Theme" (OST Version only)', 'bonus', 'ff_detailed', 150),
  ((SELECT id FROM games WHERE title = 'Final Fantasy Tactics A2: Grimoire of the Rift'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'French Horn Ensemble', '---', 'Brass -> 6 French Horns -> 5 Keysw', '6FH KS Master', NULL, NULL, '38. Sky Pirates from the East from FFXII "Penelo''s Theme" (OST Version only)', 'bonus', 'ff_detailed', 151);
