-- Source: reference/Final Fantasy Sound Sources (Detailed) - Final Fantasy X.csv
-- Section 1 part 3 of 3+: tracks 41-50 (CSV rows 1115-1396). 263 rows.
-- Position numbering continues from part 2 (1020 onwards). Game record
-- reused via SELECT.
-- T46 "Hymn - Ixion" is an empty placeholder — dropped.
-- T48 Rikku''s Theme has source "EastWest - Quantum Leap Guitar and Bass"
-- (with "and") — contributor drift vs the existing "Quantum Leap Guitar
-- & Bass" (with "&"). Preserved verbatim as a separate product.
-- Tracks 41-44, 47, 49, 50 are entirely UNKNOWN. Tracks 45 and 48 have
-- partial source data. Lots of CSV rows here are stubs awaiting research.

INSERT OR IGNORE INTO products (manufacturer_id, name, type) VALUES
  ((SELECT id FROM manufacturers WHERE name = 'EastWest' COLLATE NOCASE), 'Quantum Leap Guitar and Bass', 'Sample Library');

INSERT INTO usages
  (game_id, product_id, sample_label, sample_ref, path_bank, preset, notes, raw_source, examples, category, source_family, position)
VALUES
  -- T41: The Travel Agency (Arranged by Masashi Hamauzu) — 35 rows, all UNKNOWN
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 0', NULL, NULL, NULL, 'UNKNOWN', '41. The Travel Agency', 'main', 'ff_detailed', 1020),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 1', NULL, NULL, NULL, 'UNKNOWN', '41. The Travel Agency', 'main', 'ff_detailed', 1021),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 2', NULL, NULL, NULL, 'UNKNOWN', '41. The Travel Agency', 'main', 'ff_detailed', 1022),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 3', NULL, NULL, NULL, 'UNKNOWN', '41. The Travel Agency', 'main', 'ff_detailed', 1023),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 4', NULL, NULL, NULL, 'UNKNOWN', '41. The Travel Agency', 'main', 'ff_detailed', 1024),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 5', NULL, NULL, NULL, 'UNKNOWN', '41. The Travel Agency', 'main', 'ff_detailed', 1025),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Acoustic Piano', 'Sample 6', NULL, NULL, NULL, 'UNKNOWN', '41. The Travel Agency', 'main', 'ff_detailed', 1026),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Acoustic Piano', 'Sample 7', NULL, NULL, NULL, 'UNKNOWN', '41. The Travel Agency', 'main', 'ff_detailed', 1027),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Acoustic Piano', 'Sample 8', NULL, NULL, NULL, 'UNKNOWN', '41. The Travel Agency', 'main', 'ff_detailed', 1028),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Acoustic Piano', 'Sample 9', NULL, NULL, NULL, 'UNKNOWN', '41. The Travel Agency', 'main', 'ff_detailed', 1029),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Acoustic Piano', 'Sample 10', NULL, NULL, NULL, 'UNKNOWN', '41. The Travel Agency', 'main', 'ff_detailed', 1030),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Acoustic Piano', 'Sample 11', NULL, NULL, NULL, 'UNKNOWN', '41. The Travel Agency', 'main', 'ff_detailed', 1031),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Acoustic Piano', 'Sample 12', NULL, NULL, NULL, 'UNKNOWN', '41. The Travel Agency', 'main', 'ff_detailed', 1032),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Acoustic Piano', 'Sample 13', NULL, NULL, NULL, 'UNKNOWN', '41. The Travel Agency', 'main', 'ff_detailed', 1033),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Acoustic Piano', 'Sample 14', NULL, NULL, NULL, 'UNKNOWN', '41. The Travel Agency', 'main', 'ff_detailed', 1034),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Acoustic Piano', 'Sample 15', NULL, NULL, NULL, 'UNKNOWN', '41. The Travel Agency', 'main', 'ff_detailed', 1035),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Acoustic Piano', 'Sample 16', NULL, NULL, NULL, 'UNKNOWN', '41. The Travel Agency', 'main', 'ff_detailed', 1036),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Acoustic Piano', 'Sample 17', NULL, NULL, NULL, 'UNKNOWN', '41. The Travel Agency', 'main', 'ff_detailed', 1037),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Acoustic Piano', 'Sample 18', NULL, NULL, NULL, 'UNKNOWN', '41. The Travel Agency', 'main', 'ff_detailed', 1038),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Acoustic Piano', 'Sample 19', NULL, NULL, NULL, 'UNKNOWN', '41. The Travel Agency', 'main', 'ff_detailed', 1039),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Percussion Loop', 'Sample 20', NULL, NULL, NULL, 'UNKNOWN', '41. The Travel Agency', 'main', 'ff_detailed', 1040),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Triangle(?)', 'Sample 21', NULL, NULL, NULL, 'UNKNOWN', '41. The Travel Agency', 'main', 'ff_detailed', 1041),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Conga(?)', 'Sample 22', NULL, NULL, NULL, 'UNKNOWN', '41. The Travel Agency', 'main', 'ff_detailed', 1042),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Conga(?)', 'Sample 23', NULL, NULL, NULL, 'UNKNOWN', '41. The Travel Agency', 'main', 'ff_detailed', 1043),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Clap', 'Sample 24', NULL, NULL, NULL, 'UNKNOWN', '41. The Travel Agency', 'main', 'ff_detailed', 1044),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Clap', 'Sample 25', NULL, NULL, NULL, 'UNKNOWN', '41. The Travel Agency', 'main', 'ff_detailed', 1045),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Hand Cymbal', 'Sample 26', NULL, NULL, NULL, 'UNKNOWN', '41. The Travel Agency', 'main', 'ff_detailed', 1046),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Hand Cymbal', 'Sample 27', NULL, NULL, NULL, 'UNKNOWN', '41. The Travel Agency', 'main', 'ff_detailed', 1047),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Col Legno', 'Sample 28', NULL, NULL, NULL, 'UNKNOWN', '41. The Travel Agency', 'main', 'ff_detailed', 1048),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Col Legno', 'Sample 29', NULL, NULL, NULL, 'UNKNOWN', '41. The Travel Agency', 'main', 'ff_detailed', 1049),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Fretless Bass', 'Sample 30', NULL, NULL, NULL, 'UNKNOWN', '41. The Travel Agency', 'main', 'ff_detailed', 1050),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Fretless Bass', 'Sample 31', NULL, NULL, NULL, 'UNKNOWN', '41. The Travel Agency', 'main', 'ff_detailed', 1051),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Fretless Bass', 'Sample 32', NULL, NULL, NULL, 'UNKNOWN', '41. The Travel Agency', 'main', 'ff_detailed', 1052),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Gamelan', 'Sample 33', NULL, NULL, NULL, 'UNKNOWN', '41. The Travel Agency', 'main', 'ff_detailed', 1053),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Gamelan', 'Sample 34', NULL, NULL, NULL, 'UNKNOWN', '41. The Travel Agency', 'main', 'ff_detailed', 1054),
  -- T42: They May Pass — 8 rows, all UNKNOWN
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 0', NULL, NULL, NULL, 'UNKNOWN', '42. They May Pass', 'main', 'ff_detailed', 1055),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 1', NULL, NULL, NULL, 'UNKNOWN', '42. They May Pass', 'main', 'ff_detailed', 1056),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 2', NULL, NULL, NULL, 'UNKNOWN', '42. They May Pass', 'main', 'ff_detailed', 1057),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 3', NULL, NULL, NULL, 'UNKNOWN', '42. They May Pass', 'main', 'ff_detailed', 1058),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 4', NULL, NULL, NULL, 'UNKNOWN', '42. They May Pass', 'main', 'ff_detailed', 1059),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 5', NULL, NULL, NULL, 'UNKNOWN', '42. They May Pass', 'main', 'ff_detailed', 1060),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 6', NULL, NULL, NULL, 'UNKNOWN', '42. They May Pass', 'main', 'ff_detailed', 1061),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 7', NULL, NULL, NULL, 'UNKNOWN', '42. They May Pass', 'main', 'ff_detailed', 1062),
  -- T43: Seymour''s Theme (Arranged by Masashi Hamauzu) — 31 rows, all UNKNOWN
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Tubular Bells', 'Sample 0', NULL, NULL, NULL, 'UNKNOWN', '43. Seymour''s Theme', 'main', 'ff_detailed', 1063),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Tubular Bells', 'Sample 1', NULL, NULL, NULL, 'UNKNOWN', '43. Seymour''s Theme', 'main', 'ff_detailed', 1064),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Choir', 'Sample 2', NULL, NULL, NULL, 'UNKNOWN', '43. Seymour''s Theme', 'main', 'ff_detailed', 1065),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Choir', 'Sample 3', NULL, NULL, NULL, 'UNKNOWN', '43. Seymour''s Theme', 'main', 'ff_detailed', 1066),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Udu Pot', 'Sample 4', NULL, NULL, NULL, 'UNKNOWN', '43. Seymour''s Theme', 'main', 'ff_detailed', 1067),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Udu Pot', 'Sample 5', NULL, NULL, NULL, 'UNKNOWN', '43. Seymour''s Theme', 'main', 'ff_detailed', 1068),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Drum', 'Sample 6', NULL, NULL, NULL, 'UNKNOWN', '43. Seymour''s Theme', 'main', 'ff_detailed', 1069),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Finger Cymbal', 'Sample 7', NULL, NULL, NULL, 'UNKNOWN', '43. Seymour''s Theme', 'main', 'ff_detailed', 1070),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Harp', 'Sample 8', NULL, NULL, NULL, 'UNKNOWN', '43. Seymour''s Theme', 'main', 'ff_detailed', 1071),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Harp', 'Sample 9', NULL, NULL, NULL, 'UNKNOWN', '43. Seymour''s Theme', 'main', 'ff_detailed', 1072),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Harp', 'Sample 10', NULL, NULL, NULL, 'UNKNOWN', '43. Seymour''s Theme', 'main', 'ff_detailed', 1073),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Harp', 'Sample 11', NULL, NULL, NULL, 'UNKNOWN', '43. Seymour''s Theme', 'main', 'ff_detailed', 1074),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Harp', 'Sample 12', NULL, NULL, NULL, 'UNKNOWN', '43. Seymour''s Theme', 'main', 'ff_detailed', 1075),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'French Horn', 'Sample 13', NULL, NULL, NULL, 'UNKNOWN', '43. Seymour''s Theme', 'main', 'ff_detailed', 1076),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'French Horn', 'Sample 14', NULL, NULL, NULL, 'UNKNOWN', '43. Seymour''s Theme', 'main', 'ff_detailed', 1077),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Saw Wave', 'Sample 15', NULL, NULL, NULL, 'UNKNOWN', '43. Seymour''s Theme', 'main', 'ff_detailed', 1078),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 16', NULL, NULL, NULL, 'UNKNOWN', '43. Seymour''s Theme', 'main', 'ff_detailed', 1079),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 17', NULL, NULL, NULL, 'UNKNOWN', '43. Seymour''s Theme', 'main', 'ff_detailed', 1080),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 18', NULL, NULL, NULL, 'UNKNOWN', '43. Seymour''s Theme', 'main', 'ff_detailed', 1081),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 19', NULL, NULL, NULL, 'UNKNOWN', '43. Seymour''s Theme', 'main', 'ff_detailed', 1082),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 20', NULL, NULL, NULL, 'UNKNOWN', '43. Seymour''s Theme', 'main', 'ff_detailed', 1083),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 21', NULL, NULL, NULL, 'UNKNOWN', '43. Seymour''s Theme', 'main', 'ff_detailed', 1084),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Synth Pad', 'Sample 22', NULL, NULL, NULL, 'UNKNOWN', '43. Seymour''s Theme', 'main', 'ff_detailed', 1085),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Synth Pad', 'Sample 23', NULL, NULL, NULL, 'UNKNOWN', '43. Seymour''s Theme', 'main', 'ff_detailed', 1086),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Synth Pad', 'Sample 24', NULL, NULL, NULL, 'UNKNOWN', '43. Seymour''s Theme', 'main', 'ff_detailed', 1087),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Synth Pad', 'Sample 25', NULL, NULL, NULL, 'UNKNOWN', '43. Seymour''s Theme', 'main', 'ff_detailed', 1088),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Synth Pad', 'Sample 26', NULL, NULL, NULL, 'UNKNOWN', '43. Seymour''s Theme', 'main', 'ff_detailed', 1089),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Timpani', 'Sample 27', NULL, NULL, NULL, 'UNKNOWN', '43. Seymour''s Theme', 'main', 'ff_detailed', 1090),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Nylon Guitar', 'Sample 28', NULL, NULL, NULL, 'UNKNOWN', '43. Seymour''s Theme', 'main', 'ff_detailed', 1091),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Nylon Guitar', 'Sample 29', NULL, NULL, NULL, 'UNKNOWN', '43. Seymour''s Theme', 'main', 'ff_detailed', 1092),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Nylon Guitar', 'Sample 30', NULL, NULL, NULL, 'UNKNOWN', '43. Seymour''s Theme', 'main', 'ff_detailed', 1093),
  -- T44: Twilight (Arranged by Junya Nakano) — 22 rows, all UNKNOWN String Ensemble
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 0', NULL, NULL, NULL, 'UNKNOWN', '44. Twilight', 'main', 'ff_detailed', 1094),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 1', NULL, NULL, NULL, 'UNKNOWN', '44. Twilight', 'main', 'ff_detailed', 1095),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 2', NULL, NULL, NULL, 'UNKNOWN', '44. Twilight', 'main', 'ff_detailed', 1096),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 3', NULL, NULL, NULL, 'UNKNOWN', '44. Twilight', 'main', 'ff_detailed', 1097),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 4', NULL, NULL, NULL, 'UNKNOWN', '44. Twilight', 'main', 'ff_detailed', 1098),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 5', NULL, NULL, NULL, 'UNKNOWN', '44. Twilight', 'main', 'ff_detailed', 1099),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 6', NULL, NULL, NULL, 'UNKNOWN', '44. Twilight', 'main', 'ff_detailed', 1100),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 7', NULL, NULL, NULL, 'UNKNOWN', '44. Twilight', 'main', 'ff_detailed', 1101),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 8', NULL, NULL, NULL, 'UNKNOWN', '44. Twilight', 'main', 'ff_detailed', 1102),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 9', NULL, NULL, NULL, 'UNKNOWN', '44. Twilight', 'main', 'ff_detailed', 1103),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 10', NULL, NULL, NULL, 'UNKNOWN', '44. Twilight', 'main', 'ff_detailed', 1104),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 11', NULL, NULL, NULL, 'UNKNOWN', '44. Twilight', 'main', 'ff_detailed', 1105),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 12', NULL, NULL, NULL, 'UNKNOWN', '44. Twilight', 'main', 'ff_detailed', 1106),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 13', NULL, NULL, NULL, 'UNKNOWN', '44. Twilight', 'main', 'ff_detailed', 1107),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 14', NULL, NULL, NULL, 'UNKNOWN', '44. Twilight', 'main', 'ff_detailed', 1108),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 15', NULL, NULL, NULL, 'UNKNOWN', '44. Twilight', 'main', 'ff_detailed', 1109),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 16', NULL, NULL, NULL, 'UNKNOWN', '44. Twilight', 'main', 'ff_detailed', 1110),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 17', NULL, NULL, NULL, 'UNKNOWN', '44. Twilight', 'main', 'ff_detailed', 1111),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 18', NULL, NULL, NULL, 'UNKNOWN', '44. Twilight', 'main', 'ff_detailed', 1112),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 19', NULL, NULL, NULL, 'UNKNOWN', '44. Twilight', 'main', 'ff_detailed', 1113),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 20', NULL, NULL, NULL, 'UNKNOWN', '44. Twilight', 'main', 'ff_detailed', 1114),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 21', NULL, NULL, NULL, 'UNKNOWN', '44. Twilight', 'main', 'ff_detailed', 1115),
  -- T45: Djose Temple (Arranged by Nobuo Uematsu) — 43 rows. 6 Tremolo Strings sourced from Best Service Advanced Orchestra; rest UNKNOWN.
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Advanced Orchestra' COLLATE NOCASE), 'Tremolo Strings', 'Sample 0', 'CD 1 -> Partition B -> 02 VI TR PP', 'VI TR PP', NULL, NULL, '45. Djose Temple', 'main', 'ff_detailed', 1116),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Advanced Orchestra' COLLATE NOCASE), 'Tremolo Strings', 'Sample 1', 'CD 1 -> Partition B -> 02 VI TR PP', 'VI TR PP', NULL, NULL, '45. Djose Temple', 'main', 'ff_detailed', 1117),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Advanced Orchestra' COLLATE NOCASE), 'Tremolo Strings', 'Sample 2', 'CD 1 -> Partition B -> 02 VI TR PP', 'VI TR PP', NULL, NULL, '45. Djose Temple', 'main', 'ff_detailed', 1118),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Advanced Orchestra' COLLATE NOCASE), 'Tremolo Strings', 'Sample 3', 'CD 1 -> Partition B -> 02 VI TR PP', 'VI TR PP', NULL, NULL, '45. Djose Temple', 'main', 'ff_detailed', 1119),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Advanced Orchestra' COLLATE NOCASE), 'Tremolo Strings', 'Sample 4', 'CD 1 -> Partition B -> 02 VI TR PP', 'VI TR PP', NULL, NULL, '45. Djose Temple', 'main', 'ff_detailed', 1120),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Advanced Orchestra' COLLATE NOCASE), 'Tremolo Strings', 'Sample 5', 'CD 1 -> Partition B -> 02 VI TR PP', 'VI TR PP', NULL, NULL, '45. Djose Temple', 'main', 'ff_detailed', 1121),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Pizzicato String', 'Sample 6', NULL, NULL, NULL, 'UNKNOWN', '45. Djose Temple', 'main', 'ff_detailed', 1122),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Pizzicato String', 'Sample 7', NULL, NULL, NULL, 'UNKNOWN', '45. Djose Temple', 'main', 'ff_detailed', 1123),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Pizzicato String', 'Sample 8', NULL, NULL, NULL, 'UNKNOWN', '45. Djose Temple', 'main', 'ff_detailed', 1124),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Pizzicato String', 'Sample 9', NULL, NULL, NULL, 'UNKNOWN', '45. Djose Temple', 'main', 'ff_detailed', 1125),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Pizzicato String', 'Sample 10', NULL, NULL, NULL, 'UNKNOWN', '45. Djose Temple', 'main', 'ff_detailed', 1126),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Pizzicato String', 'Sample 11', NULL, NULL, NULL, 'UNKNOWN', '45. Djose Temple', 'main', 'ff_detailed', 1127),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Pizzicato String', 'Sample 12', NULL, NULL, NULL, 'UNKNOWN', '45. Djose Temple', 'main', 'ff_detailed', 1128),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Pizzicato String', 'Sample 13', NULL, NULL, NULL, 'UNKNOWN', '45. Djose Temple', 'main', 'ff_detailed', 1129),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Pizzicato String', 'Sample 14', NULL, NULL, NULL, 'UNKNOWN', '45. Djose Temple', 'main', 'ff_detailed', 1130),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Flute Staccato', 'Sample 15', NULL, NULL, NULL, 'UNKNOWN', '45. Djose Temple', 'main', 'ff_detailed', 1131),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Flute Staccato', 'Sample 16', NULL, NULL, NULL, 'UNKNOWN', '45. Djose Temple', 'main', 'ff_detailed', 1132),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Flute Staccato', 'Sample 17', NULL, NULL, NULL, 'UNKNOWN', '45. Djose Temple', 'main', 'ff_detailed', 1133),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Flute Staccato', 'Sample 18', NULL, NULL, NULL, 'UNKNOWN', '45. Djose Temple', 'main', 'ff_detailed', 1134),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Flute Staccato', 'Sample 19', NULL, NULL, NULL, 'UNKNOWN', '45. Djose Temple', 'main', 'ff_detailed', 1135),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Flute Staccato', 'Sample 20', NULL, NULL, NULL, 'UNKNOWN', '45. Djose Temple', 'main', 'ff_detailed', 1136),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Guiro', 'Sample 21', NULL, NULL, NULL, 'UNKNOWN', '45. Djose Temple', 'main', 'ff_detailed', 1137),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Guiro', 'Sample 22', NULL, NULL, NULL, 'UNKNOWN', '45. Djose Temple', 'main', 'ff_detailed', 1138),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Timpani', 'Sample 23', NULL, NULL, NULL, 'UNKNOWN', '45. Djose Temple', 'main', 'ff_detailed', 1139),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Timpani', 'Sample 24', NULL, NULL, NULL, 'UNKNOWN', '45. Djose Temple', 'main', 'ff_detailed', 1140),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Pizzicato String', 'Sample 25', NULL, NULL, NULL, 'UNKNOWN', '45. Djose Temple', 'main', 'ff_detailed', 1141),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Pizzicato String', 'Sample 26', NULL, NULL, NULL, 'UNKNOWN', '45. Djose Temple', 'main', 'ff_detailed', 1142),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Pizzicato String', 'Sample 27', NULL, NULL, NULL, 'UNKNOWN', '45. Djose Temple', 'main', 'ff_detailed', 1143),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Pizzicato String', 'Sample 28', NULL, NULL, NULL, 'UNKNOWN', '45. Djose Temple', 'main', 'ff_detailed', 1144),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Pizzicato String', 'Sample 29', NULL, NULL, NULL, 'UNKNOWN', '45. Djose Temple', 'main', 'ff_detailed', 1145),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Pizzicato String', 'Sample 30', NULL, NULL, NULL, 'UNKNOWN', '45. Djose Temple', 'main', 'ff_detailed', 1146),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Pizzicato String', 'Sample 31', NULL, NULL, NULL, 'UNKNOWN', '45. Djose Temple', 'main', 'ff_detailed', 1147),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Marimba', 'Sample 32', NULL, NULL, NULL, 'UNKNOWN', '45. Djose Temple', 'main', 'ff_detailed', 1148),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Marimba', 'Sample 33', NULL, NULL, NULL, 'UNKNOWN', '45. Djose Temple', 'main', 'ff_detailed', 1149),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Marimba', 'Sample 34', NULL, NULL, NULL, 'UNKNOWN', '45. Djose Temple', 'main', 'ff_detailed', 1150),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Marimba', 'Sample 35', NULL, NULL, NULL, 'UNKNOWN', '45. Djose Temple', 'main', 'ff_detailed', 1151),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Marimba', 'Sample 36', NULL, NULL, NULL, 'UNKNOWN', '45. Djose Temple', 'main', 'ff_detailed', 1152),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Snare', 'Sample 37', NULL, NULL, NULL, 'UNKNOWN', '45. Djose Temple', 'main', 'ff_detailed', 1153),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Snare', 'Sample 38', NULL, NULL, NULL, 'UNKNOWN', '45. Djose Temple', 'main', 'ff_detailed', 1154),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Snare', 'Sample 39', NULL, NULL, NULL, 'UNKNOWN', '45. Djose Temple', 'main', 'ff_detailed', 1155),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Snare', 'Sample 40', NULL, NULL, NULL, 'UNKNOWN', '45. Djose Temple', 'main', 'ff_detailed', 1156),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Woodblock', 'Sample 41', NULL, NULL, NULL, 'UNKNOWN', '45. Djose Temple', 'main', 'ff_detailed', 1157),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Woodblock', 'Sample 42', NULL, NULL, NULL, 'UNKNOWN', '45. Djose Temple', 'main', 'ff_detailed', 1158),
  -- T46: Hymn - Ixion — empty placeholder dropped
  -- T47: Ridess The Shoopuf? (Arranged by Nobuo Uematsu) — 21 rows
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Marimba', 'Sample 0', NULL, NULL, NULL, 'UNKNOWN', '47. Ridess The Shoopuf?', 'main', 'ff_detailed', 1159),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Marimba', 'Sample 1', NULL, NULL, NULL, 'UNKNOWN', '47. Ridess The Shoopuf?', 'main', 'ff_detailed', 1160),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Marimba', 'Sample 2', NULL, NULL, NULL, 'UNKNOWN', '47. Ridess The Shoopuf?', 'main', 'ff_detailed', 1161),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Marimba', 'Sample 3', NULL, NULL, NULL, 'UNKNOWN', '47. Ridess The Shoopuf?', 'main', 'ff_detailed', 1162),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Marimba', 'Sample 4', NULL, NULL, NULL, 'UNKNOWN', '47. Ridess The Shoopuf?', 'main', 'ff_detailed', 1163),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Marimba', 'Sample 5', NULL, NULL, NULL, 'UNKNOWN', '47. Ridess The Shoopuf?', 'main', 'ff_detailed', 1164),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Marimba', 'Sample 6', NULL, NULL, NULL, 'UNKNOWN', '47. Ridess The Shoopuf?', 'main', 'ff_detailed', 1165),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Synth Pad', 'Sample 7', NULL, NULL, NULL, 'UNKNOWN', '47. Ridess The Shoopuf?', 'main', 'ff_detailed', 1166),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Synth Pad', 'Sample 8', NULL, NULL, NULL, 'UNKNOWN', '47. Ridess The Shoopuf?', 'main', 'ff_detailed', 1167),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Pizzicato String', 'Sample 9', NULL, NULL, NULL, 'UNKNOWN', '47. Ridess The Shoopuf?', 'main', 'ff_detailed', 1168),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Pizzicato String', 'Sample 10', NULL, NULL, NULL, 'UNKNOWN', '47. Ridess The Shoopuf?', 'main', 'ff_detailed', 1169),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Pizzicato String', 'Sample 11', NULL, NULL, NULL, 'UNKNOWN', '47. Ridess The Shoopuf?', 'main', 'ff_detailed', 1170),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Pizzicato String', 'Sample 12', NULL, NULL, NULL, 'UNKNOWN', '47. Ridess The Shoopuf?', 'main', 'ff_detailed', 1171),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Pizzicato String', 'Sample 13', NULL, NULL, NULL, 'UNKNOWN', '47. Ridess The Shoopuf?', 'main', 'ff_detailed', 1172),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Pizzicato String', 'Sample 14', NULL, NULL, NULL, 'UNKNOWN', '47. Ridess The Shoopuf?', 'main', 'ff_detailed', 1173),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Pizzicato String', 'Sample 15', NULL, NULL, NULL, 'UNKNOWN', '47. Ridess The Shoopuf?', 'main', 'ff_detailed', 1174),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Kick', 'Sample 16', NULL, NULL, NULL, 'UNKNOWN', '47. Ridess The Shoopuf?', 'main', 'ff_detailed', 1175),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Kick', 'Sample 17', NULL, NULL, NULL, 'UNKNOWN', '47. Ridess The Shoopuf?', 'main', 'ff_detailed', 1176),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Hi Hat', 'Sample 18', NULL, NULL, NULL, 'UNKNOWN', '47. Ridess The Shoopuf?', 'main', 'ff_detailed', 1177),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Hi Hat', 'Sample 19', NULL, NULL, NULL, 'UNKNOWN', '47. Ridess The Shoopuf?', 'main', 'ff_detailed', 1178),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Tambourine', 'Sample 20', NULL, NULL, NULL, 'UNKNOWN', '47. Ridess The Shoopuf?', 'main', 'ff_detailed', 1179),
  -- T48: Rikku''s Theme (Arranged by Nobuo Uematsu) — 28 rows. 6 with EastWest "Guitar and Bass" variant.
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Harmonica', 'Sample 0', NULL, NULL, NULL, 'UNKNOWN', '48. Rikku''s Theme', 'main', 'ff_detailed', 1180),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Harmonica', 'Sample 1', NULL, NULL, NULL, 'UNKNOWN', '48. Rikku''s Theme', 'main', 'ff_detailed', 1181),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Shaker', 'Sample 2', NULL, NULL, NULL, 'UNKNOWN', '48. Rikku''s Theme', 'main', 'ff_detailed', 1182),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Shaker', 'Sample 3', NULL, NULL, NULL, 'UNKNOWN', '48. Rikku''s Theme', 'main', 'ff_detailed', 1183),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Triangle', 'Sample 4', NULL, NULL, NULL, 'UNKNOWN', '48. Rikku''s Theme', 'main', 'ff_detailed', 1184),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Triangle', 'Sample 5', NULL, NULL, NULL, 'UNKNOWN', '48. Rikku''s Theme', 'main', 'ff_detailed', 1185),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Vibraphone', 'Sample 6', NULL, NULL, NULL, 'UNKNOWN', '48. Rikku''s Theme', 'main', 'ff_detailed', 1186),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Vibraphone', 'Sample 7', NULL, NULL, NULL, 'UNKNOWN', '48. Rikku''s Theme', 'main', 'ff_detailed', 1187),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Fingered Bass', 'Sample 8', NULL, NULL, NULL, 'UNKNOWN', '48. Rikku''s Theme', 'main', 'ff_detailed', 1188),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Fingered Bass', 'Sample 9', NULL, NULL, NULL, 'UNKNOWN', '48. Rikku''s Theme', 'main', 'ff_detailed', 1189),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Fingered Bass', 'Sample 10', NULL, NULL, NULL, 'UNKNOWN', '48. Rikku''s Theme', 'main', 'ff_detailed', 1190),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Quantum Leap Guitar and Bass' COLLATE NOCASE), 'Nylon Guitar', 'Sample 11', 'Partition C -> VOLUME 002', 'CLSCFGRVB  1', NULL, NULL, '48. Rikku''s Theme', 'main', 'ff_detailed', 1191),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Quantum Leap Guitar and Bass' COLLATE NOCASE), 'Nylon Guitar', 'Sample 12', 'Partition C -> VOLUME 002', 'CLSCFGRVB  1', NULL, NULL, '48. Rikku''s Theme', 'main', 'ff_detailed', 1192),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Quantum Leap Guitar and Bass' COLLATE NOCASE), 'Nylon Guitar', 'Sample 13', 'Partition C -> VOLUME 002', 'CLSCFGRVB  1', NULL, NULL, '48. Rikku''s Theme', 'main', 'ff_detailed', 1193),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Quantum Leap Guitar and Bass' COLLATE NOCASE), 'Nylon Guitar', 'Sample 14', 'Partition C -> VOLUME 002', 'CLSCFGRVB  1', NULL, NULL, '48. Rikku''s Theme', 'main', 'ff_detailed', 1194),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Quantum Leap Guitar and Bass' COLLATE NOCASE), 'Nylon Guitar', 'Sample 15', 'Partition C -> VOLUME 002', 'CLSCFGRVB  1', NULL, NULL, '48. Rikku''s Theme', 'main', 'ff_detailed', 1195),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Quantum Leap Guitar and Bass' COLLATE NOCASE), 'Nylon Guitar', 'Sample 16', 'Partition C -> VOLUME 002', 'CLSCFGRVB  1', NULL, NULL, '48. Rikku''s Theme', 'main', 'ff_detailed', 1196),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Flute', 'Sample 17', NULL, NULL, NULL, 'UNKNOWN', '48. Rikku''s Theme', 'main', 'ff_detailed', 1197),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Flute', 'Sample 18', NULL, NULL, NULL, 'UNKNOWN', '48. Rikku''s Theme', 'main', 'ff_detailed', 1198),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 19', NULL, NULL, NULL, 'UNKNOWN', '48. Rikku''s Theme', 'main', 'ff_detailed', 1199),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 20', NULL, NULL, NULL, 'UNKNOWN', '48. Rikku''s Theme', 'main', 'ff_detailed', 1200),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 21', NULL, NULL, NULL, 'UNKNOWN', '48. Rikku''s Theme', 'main', 'ff_detailed', 1201),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 22', NULL, NULL, NULL, 'UNKNOWN', '48. Rikku''s Theme', 'main', 'ff_detailed', 1202),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 23', NULL, NULL, NULL, 'UNKNOWN', '48. Rikku''s Theme', 'main', 'ff_detailed', 1203),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 24', NULL, NULL, NULL, 'UNKNOWN', '48. Rikku''s Theme', 'main', 'ff_detailed', 1204),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 25', NULL, NULL, NULL, 'UNKNOWN', '48. Rikku''s Theme', 'main', 'ff_detailed', 1205),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 26', NULL, NULL, NULL, 'UNKNOWN', '48. Rikku''s Theme', 'main', 'ff_detailed', 1206),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 27', NULL, NULL, NULL, 'UNKNOWN', '48. Rikku''s Theme', 'main', 'ff_detailed', 1207),
  -- T49: Guadosalam (Arranged by Junya Nakano) — 27 rows, all UNKNOWN
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Triangle', 'Sample 0', NULL, NULL, NULL, 'UNKNOWN', '49. Guadosalam', 'main', 'ff_detailed', 1208),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Choir', 'Sample 1', NULL, NULL, NULL, 'UNKNOWN', '49. Guadosalam', 'main', 'ff_detailed', 1209),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Choir', 'Sample 2', NULL, NULL, NULL, 'UNKNOWN', '49. Guadosalam', 'main', 'ff_detailed', 1210),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Choir', 'Sample 3', NULL, NULL, NULL, 'UNKNOWN', '49. Guadosalam', 'main', 'ff_detailed', 1211),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Flute', 'Sample 4', NULL, NULL, NULL, 'UNKNOWN', '49. Guadosalam', 'main', 'ff_detailed', 1212),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Flute', 'Sample 5', NULL, NULL, NULL, 'UNKNOWN', '49. Guadosalam', 'main', 'ff_detailed', 1213),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Flute', 'Sample 6', NULL, NULL, NULL, 'UNKNOWN', '49. Guadosalam', 'main', 'ff_detailed', 1214),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Flute', 'Sample 7', NULL, NULL, NULL, 'UNKNOWN', '49. Guadosalam', 'main', 'ff_detailed', 1215),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Bass Drum', 'Sample 8', NULL, NULL, NULL, 'UNKNOWN', '49. Guadosalam', 'main', 'ff_detailed', 1216),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Sansa(?)', 'Sample 9', NULL, NULL, NULL, 'UNKNOWN', '49. Guadosalam', 'main', 'ff_detailed', 1217),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Sansa(?)', 'Sample 10', NULL, NULL, NULL, 'UNKNOWN', '49. Guadosalam', 'main', 'ff_detailed', 1218),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Sansa(?)', 'Sample 11', NULL, NULL, NULL, 'UNKNOWN', '49. Guadosalam', 'main', 'ff_detailed', 1219),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Sansa(?)', 'Sample 12', NULL, NULL, NULL, 'UNKNOWN', '49. Guadosalam', 'main', 'ff_detailed', 1220),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Sansa(?)', 'Sample 13', NULL, NULL, NULL, 'UNKNOWN', '49. Guadosalam', 'main', 'ff_detailed', 1221),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Sansa(?)', 'Sample 14', NULL, NULL, NULL, 'UNKNOWN', '49. Guadosalam', 'main', 'ff_detailed', 1222),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Pizzicato String', 'Sample 15', NULL, NULL, NULL, 'UNKNOWN', '49. Guadosalam', 'main', 'ff_detailed', 1223),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Pizzicato String', 'Sample 16', NULL, NULL, NULL, 'UNKNOWN', '49. Guadosalam', 'main', 'ff_detailed', 1224),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Pizzicato String', 'Sample 17', NULL, NULL, NULL, 'UNKNOWN', '49. Guadosalam', 'main', 'ff_detailed', 1225),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Pizzicato String', 'Sample 18', NULL, NULL, NULL, 'UNKNOWN', '49. Guadosalam', 'main', 'ff_detailed', 1226),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Synth String', 'Sample 19', NULL, NULL, NULL, 'UNKNOWN', '49. Guadosalam', 'main', 'ff_detailed', 1227),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Synth String', 'Sample 20', NULL, NULL, NULL, 'UNKNOWN', '49. Guadosalam', 'main', 'ff_detailed', 1228),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Synth String', 'Sample 21', NULL, NULL, NULL, 'UNKNOWN', '49. Guadosalam', 'main', 'ff_detailed', 1229),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Synth String', 'Sample 22', NULL, NULL, NULL, 'UNKNOWN', '49. Guadosalam', 'main', 'ff_detailed', 1230),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Dulcimer', 'Sample 23', NULL, NULL, NULL, 'UNKNOWN', '49. Guadosalam', 'main', 'ff_detailed', 1231),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Dulcimer', 'Sample 24', NULL, NULL, NULL, 'UNKNOWN', '49. Guadosalam', 'main', 'ff_detailed', 1232),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Dulcimer', 'Sample 25', NULL, NULL, NULL, 'UNKNOWN', '49. Guadosalam', 'main', 'ff_detailed', 1233),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Dulcimer', 'Sample 26', NULL, NULL, NULL, 'UNKNOWN', '49. Guadosalam', 'main', 'ff_detailed', 1234),
  -- T50: Thunder Plains — 48 rows, all UNKNOWN (no arranger listed in CSV)
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Fretless Bass', 'Sample 0', NULL, NULL, NULL, 'UNKNOWN', '50. Thunder Plains', 'main', 'ff_detailed', 1235),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Fretless Bass', 'Sample 1', NULL, NULL, NULL, 'UNKNOWN', '50. Thunder Plains', 'main', 'ff_detailed', 1236),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Fretless Bass', 'Sample 2', NULL, NULL, NULL, 'UNKNOWN', '50. Thunder Plains', 'main', 'ff_detailed', 1237),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Fretless Bass', 'Sample 3', NULL, NULL, NULL, 'UNKNOWN', '50. Thunder Plains', 'main', 'ff_detailed', 1238),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Fretless Bass', 'Sample 4', NULL, NULL, NULL, 'UNKNOWN', '50. Thunder Plains', 'main', 'ff_detailed', 1239),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Fretless Bass', 'Sample 5', NULL, NULL, NULL, 'UNKNOWN', '50. Thunder Plains', 'main', 'ff_detailed', 1240),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Fretless Bass', 'Sample 6', NULL, NULL, NULL, 'UNKNOWN', '50. Thunder Plains', 'main', 'ff_detailed', 1241),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Fretless Bass', 'Sample 7', NULL, NULL, NULL, 'UNKNOWN', '50. Thunder Plains', 'main', 'ff_detailed', 1242),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Flute', 'Sample 8', NULL, NULL, NULL, 'UNKNOWN', '50. Thunder Plains', 'main', 'ff_detailed', 1243),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Flute', 'Sample 9', NULL, NULL, NULL, 'UNKNOWN', '50. Thunder Plains', 'main', 'ff_detailed', 1244),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Flute', 'Sample 10', NULL, NULL, NULL, 'UNKNOWN', '50. Thunder Plains', 'main', 'ff_detailed', 1245),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Flute', 'Sample 11', NULL, NULL, NULL, 'UNKNOWN', '50. Thunder Plains', 'main', 'ff_detailed', 1246),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Clock Ticks', 'Sample 12', NULL, NULL, 'A similar tick is heard in FFVIII''s Galbadian Garden', 'UNKNOWN', '50. Thunder Plains', 'main', 'ff_detailed', 1247),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Clock Ticks', 'Sample 13', NULL, NULL, 'A similar tick is heard in FFVIII''s Galbadian Garden', 'UNKNOWN', '50. Thunder Plains', 'main', 'ff_detailed', 1248),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Clock Ticks', 'Sample 14', NULL, NULL, NULL, 'UNKNOWN', '50. Thunder Plains', 'main', 'ff_detailed', 1249),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Clock Ticks', 'Sample 15', NULL, NULL, NULL, 'UNKNOWN', '50. Thunder Plains', 'main', 'ff_detailed', 1250),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Clock Ticks', 'Sample 16', NULL, NULL, NULL, 'UNKNOWN', '50. Thunder Plains', 'main', 'ff_detailed', 1251),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Clock Ticks', 'Sample 17', NULL, NULL, NULL, 'UNKNOWN', '50. Thunder Plains', 'main', 'ff_detailed', 1252),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Clock Ticks', 'Sample 18', NULL, NULL, NULL, 'UNKNOWN', '50. Thunder Plains', 'main', 'ff_detailed', 1253),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Kalimba Pad', 'Sample 19', NULL, NULL, NULL, 'UNKNOWN', '50. Thunder Plains', 'main', 'ff_detailed', 1254),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Kalimba Pad', 'Sample 20', NULL, NULL, NULL, 'UNKNOWN', '50. Thunder Plains', 'main', 'ff_detailed', 1255),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Kalimba Pad', 'Sample 21', NULL, NULL, NULL, 'UNKNOWN', '50. Thunder Plains', 'main', 'ff_detailed', 1256),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Kalimba Pad', 'Sample 22', NULL, NULL, NULL, 'UNKNOWN', '50. Thunder Plains', 'main', 'ff_detailed', 1257),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Kalimba Pad', 'Sample 23', NULL, NULL, NULL, 'UNKNOWN', '50. Thunder Plains', 'main', 'ff_detailed', 1258),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Kalimba Pad', 'Sample 24', NULL, NULL, NULL, 'UNKNOWN', '50. Thunder Plains', 'main', 'ff_detailed', 1259),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Kalimba Pad', 'Sample 25', NULL, NULL, NULL, 'UNKNOWN', '50. Thunder Plains', 'main', 'ff_detailed', 1260),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Kalimba Pad', 'Sample 26', NULL, NULL, NULL, 'UNKNOWN', '50. Thunder Plains', 'main', 'ff_detailed', 1261),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 27', NULL, NULL, NULL, 'UNKNOWN', '50. Thunder Plains', 'main', 'ff_detailed', 1262),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 28', NULL, NULL, NULL, 'UNKNOWN', '50. Thunder Plains', 'main', 'ff_detailed', 1263),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 29', NULL, NULL, NULL, 'UNKNOWN', '50. Thunder Plains', 'main', 'ff_detailed', 1264),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 30', NULL, NULL, NULL, 'UNKNOWN', '50. Thunder Plains', 'main', 'ff_detailed', 1265),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 31', NULL, NULL, NULL, 'UNKNOWN', '50. Thunder Plains', 'main', 'ff_detailed', 1266),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 32', NULL, NULL, NULL, 'UNKNOWN', '50. Thunder Plains', 'main', 'ff_detailed', 1267),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 33', NULL, NULL, NULL, 'UNKNOWN', '50. Thunder Plains', 'main', 'ff_detailed', 1268),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 34', NULL, NULL, NULL, 'UNKNOWN', '50. Thunder Plains', 'main', 'ff_detailed', 1269),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 35', NULL, NULL, NULL, 'UNKNOWN', '50. Thunder Plains', 'main', 'ff_detailed', 1270),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 36', NULL, NULL, NULL, 'UNKNOWN', '50. Thunder Plains', 'main', 'ff_detailed', 1271),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 37', NULL, NULL, NULL, 'UNKNOWN', '50. Thunder Plains', 'main', 'ff_detailed', 1272),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 38', NULL, NULL, NULL, 'UNKNOWN', '50. Thunder Plains', 'main', 'ff_detailed', 1273),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 39', NULL, NULL, NULL, 'UNKNOWN', '50. Thunder Plains', 'main', 'ff_detailed', 1274),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 40', NULL, NULL, NULL, 'UNKNOWN', '50. Thunder Plains', 'main', 'ff_detailed', 1275),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 41', NULL, NULL, NULL, 'UNKNOWN', '50. Thunder Plains', 'main', 'ff_detailed', 1276),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 42', NULL, NULL, NULL, 'UNKNOWN', '50. Thunder Plains', 'main', 'ff_detailed', 1277),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 43', NULL, NULL, NULL, 'UNKNOWN', '50. Thunder Plains', 'main', 'ff_detailed', 1278),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 44', NULL, NULL, NULL, 'UNKNOWN', '50. Thunder Plains', 'main', 'ff_detailed', 1279),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 45', NULL, NULL, NULL, 'UNKNOWN', '50. Thunder Plains', 'main', 'ff_detailed', 1280),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 46', NULL, NULL, NULL, 'UNKNOWN', '50. Thunder Plains', 'main', 'ff_detailed', 1281),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 47', NULL, NULL, NULL, 'UNKNOWN', '50. Thunder Plains', 'main', 'ff_detailed', 1282);
