-- Source: reference/Final Fantasy Sound Sources (Detailed) - Final Fantasy X.csv
-- Section 1 part 4 of 4+: tracks 51-60 (CSV rows 1397-1643). 227 rows.
-- Position numbering continues from part 3 (1283 onwards).
-- T56 Hymn - Shiva is an empty placeholder — dropped.
-- T60 The Truth Revealed has a "(Variation only)" sub-section labeled
-- separately; samples there inherit the same track title but use "Variation"
-- in examples to disambiguate.
-- New product: EastWest / Percussive Adventures (T59 Sample 4).

INSERT OR IGNORE INTO products (manufacturer_id, name, type) VALUES
  ((SELECT id FROM manufacturers WHERE name = 'EastWest' COLLATE NOCASE), 'Percussive Adventures', 'Sample Library');

INSERT INTO usages
  (game_id, product_id, sample_label, sample_ref, path_bank, preset, notes, raw_source, examples, category, source_family, position)
VALUES
  -- T51: Jecht''s Theme (Arranged by Nobuo Uematsu) — 20 rows, all Live Recording (Tsuyoshi Sekito)
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Acoustic Guitar', 'Sample 0', NULL, NULL, NULL, 'Live Recording (Tsuyoshi Sekito)', '51. Jecht''s Theme', 'main', 'ff_detailed', 1283),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Acoustic Guitar', 'Sample 1', NULL, NULL, NULL, 'Live Recording (Tsuyoshi Sekito)', '51. Jecht''s Theme', 'main', 'ff_detailed', 1284),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Acoustic Guitar', 'Sample 2', NULL, NULL, NULL, 'Live Recording (Tsuyoshi Sekito)', '51. Jecht''s Theme', 'main', 'ff_detailed', 1285),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Acoustic Guitar', 'Sample 3', NULL, NULL, NULL, 'Live Recording (Tsuyoshi Sekito)', '51. Jecht''s Theme', 'main', 'ff_detailed', 1286),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Acoustic Guitar', 'Sample 4', NULL, NULL, NULL, 'Live Recording (Tsuyoshi Sekito)', '51. Jecht''s Theme', 'main', 'ff_detailed', 1287),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Acoustic Guitar', 'Sample 5', NULL, NULL, NULL, 'Live Recording (Tsuyoshi Sekito)', '51. Jecht''s Theme', 'main', 'ff_detailed', 1288),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Acoustic Guitar', 'Sample 6', NULL, NULL, NULL, 'Live Recording (Tsuyoshi Sekito)', '51. Jecht''s Theme', 'main', 'ff_detailed', 1289),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Acoustic Guitar', 'Sample 7', NULL, NULL, NULL, 'Live Recording (Tsuyoshi Sekito)', '51. Jecht''s Theme', 'main', 'ff_detailed', 1290),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Acoustic Guitar', 'Sample 8', NULL, NULL, NULL, 'Live Recording (Tsuyoshi Sekito)', '51. Jecht''s Theme', 'main', 'ff_detailed', 1291),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Acoustic Guitar Harmonics', 'Sample 9', NULL, NULL, NULL, 'Live Recording (Tsuyoshi Sekito)', '51. Jecht''s Theme', 'main', 'ff_detailed', 1292),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Acoustic Guitar Harmonics', 'Sample 10', NULL, NULL, NULL, 'Live Recording (Tsuyoshi Sekito)', '51. Jecht''s Theme', 'main', 'ff_detailed', 1293),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Acoustic Guitar Interval', 'Sample 11', NULL, NULL, NULL, 'Live Recording (Tsuyoshi Sekito)', '51. Jecht''s Theme', 'main', 'ff_detailed', 1294),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Acoustic Guitar Interval', 'Sample 12', NULL, NULL, NULL, 'Live Recording (Tsuyoshi Sekito)', '51. Jecht''s Theme', 'main', 'ff_detailed', 1295),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Acoustic Guitar Interval', 'Sample 13', NULL, NULL, NULL, 'Live Recording (Tsuyoshi Sekito)', '51. Jecht''s Theme', 'main', 'ff_detailed', 1296),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Acoustic Guitar Interval', 'Sample 14', NULL, NULL, NULL, 'Live Recording (Tsuyoshi Sekito)', '51. Jecht''s Theme', 'main', 'ff_detailed', 1297),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Acoustic Guitar Interval', 'Sample 15', NULL, NULL, NULL, 'Live Recording (Tsuyoshi Sekito)', '51. Jecht''s Theme', 'main', 'ff_detailed', 1298),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Acoustic Guitar Interval', 'Sample 16', NULL, NULL, NULL, 'Live Recording (Tsuyoshi Sekito)', '51. Jecht''s Theme', 'main', 'ff_detailed', 1299),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Acoustic Guitar Interval', 'Sample 17', NULL, NULL, NULL, 'Live Recording (Tsuyoshi Sekito)', '51. Jecht''s Theme', 'main', 'ff_detailed', 1300),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Acoustic Guitar Interval', 'Sample 18', NULL, NULL, NULL, 'Live Recording (Tsuyoshi Sekito)', '51. Jecht''s Theme', 'main', 'ff_detailed', 1301),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Acoustic Guitar Interval', 'Sample 19', NULL, NULL, NULL, 'Live Recording (Tsuyoshi Sekito)', '51. Jecht''s Theme', 'main', 'ff_detailed', 1302),
  -- T52: Macalania Woods (Arranged by Masashi Hamauzu) — 32 rows, all UNKNOWN
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Marcato String', 'Sample 0', NULL, NULL, NULL, 'UNKNOWN', '52. Macalania Woods', 'main', 'ff_detailed', 1303),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Marcato String', 'Sample 1', NULL, NULL, NULL, 'UNKNOWN', '52. Macalania Woods', 'main', 'ff_detailed', 1304),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Marcato String', 'Sample 2', NULL, NULL, NULL, 'UNKNOWN', '52. Macalania Woods', 'main', 'ff_detailed', 1305),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Marcato String', 'Sample 3', NULL, NULL, NULL, 'UNKNOWN', '52. Macalania Woods', 'main', 'ff_detailed', 1306),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Marcato String', 'Sample 4', NULL, NULL, NULL, 'UNKNOWN', '52. Macalania Woods', 'main', 'ff_detailed', 1307),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Marcato String', 'Sample 5', NULL, NULL, NULL, 'UNKNOWN', '52. Macalania Woods', 'main', 'ff_detailed', 1308),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 6', NULL, NULL, NULL, 'UNKNOWN', '52. Macalania Woods', 'main', 'ff_detailed', 1309),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'French Horn', 'Sample 7', NULL, NULL, NULL, 'UNKNOWN', '52. Macalania Woods', 'main', 'ff_detailed', 1310),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'French Horn', 'Sample 8', NULL, NULL, NULL, 'UNKNOWN', '52. Macalania Woods', 'main', 'ff_detailed', 1311),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 9', NULL, NULL, NULL, 'UNKNOWN', '52. Macalania Woods', 'main', 'ff_detailed', 1312),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 10', NULL, NULL, NULL, 'UNKNOWN', '52. Macalania Woods', 'main', 'ff_detailed', 1313),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 11', NULL, NULL, NULL, 'UNKNOWN', '52. Macalania Woods', 'main', 'ff_detailed', 1314),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 12', NULL, NULL, NULL, 'UNKNOWN', '52. Macalania Woods', 'main', 'ff_detailed', 1315),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 13', NULL, NULL, NULL, 'UNKNOWN', '52. Macalania Woods', 'main', 'ff_detailed', 1316),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 14', NULL, NULL, NULL, 'UNKNOWN', '52. Macalania Woods', 'main', 'ff_detailed', 1317),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 15', NULL, NULL, NULL, 'UNKNOWN', '52. Macalania Woods', 'main', 'ff_detailed', 1318),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 16', NULL, NULL, NULL, 'UNKNOWN', '52. Macalania Woods', 'main', 'ff_detailed', 1319),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 17', NULL, NULL, NULL, 'UNKNOWN', '52. Macalania Woods', 'main', 'ff_detailed', 1320),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 18', NULL, NULL, NULL, 'UNKNOWN', '52. Macalania Woods', 'main', 'ff_detailed', 1321),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 19', NULL, NULL, NULL, 'UNKNOWN', '52. Macalania Woods', 'main', 'ff_detailed', 1322),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 20', NULL, NULL, NULL, 'UNKNOWN', '52. Macalania Woods', 'main', 'ff_detailed', 1323),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 21', NULL, NULL, NULL, 'UNKNOWN', '52. Macalania Woods', 'main', 'ff_detailed', 1324),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 22', NULL, NULL, NULL, 'UNKNOWN', '52. Macalania Woods', 'main', 'ff_detailed', 1325),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 23', NULL, NULL, NULL, 'UNKNOWN', '52. Macalania Woods', 'main', 'ff_detailed', 1326),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Electric Piano', 'Sample 24', NULL, NULL, NULL, 'UNKNOWN', '52. Macalania Woods', 'main', 'ff_detailed', 1327),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Electric Piano', 'Sample 25', NULL, NULL, NULL, 'UNKNOWN', '52. Macalania Woods', 'main', 'ff_detailed', 1328),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Electric Piano', 'Sample 26', NULL, NULL, NULL, 'UNKNOWN', '52. Macalania Woods', 'main', 'ff_detailed', 1329),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Trill Strings', 'Sample 27', NULL, NULL, NULL, 'UNKNOWN', '52. Macalania Woods', 'main', 'ff_detailed', 1330),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Tremolo Strings', 'Sample 28', NULL, NULL, NULL, 'UNKNOWN', '52. Macalania Woods', 'main', 'ff_detailed', 1331),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Slow String Ensemble', 'Sample 29', NULL, NULL, NULL, 'UNKNOWN', '52. Macalania Woods', 'main', 'ff_detailed', 1332),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Slow String Ensemble', 'Sample 30', NULL, NULL, NULL, 'UNKNOWN', '52. Macalania Woods', 'main', 'ff_detailed', 1333),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Slow String Ensemble', 'Sample 31', NULL, NULL, NULL, 'UNKNOWN', '52. Macalania Woods', 'main', 'ff_detailed', 1334),
  -- T53: The Void (Arranged by Junya Nakano) — 12 rows
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Anvil', 'Sample 0', NULL, NULL, NULL, 'UNKNOWN', '53. The Void', 'main', 'ff_detailed', 1335),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Anvil', 'Sample 1', NULL, NULL, NULL, 'UNKNOWN', '53. The Void', 'main', 'ff_detailed', 1336),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Anvil', 'Sample 2', NULL, NULL, NULL, 'UNKNOWN', '53. The Void', 'main', 'ff_detailed', 1337),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Anvil', 'Sample 3', NULL, NULL, NULL, 'UNKNOWN', '53. The Void', 'main', 'ff_detailed', 1338),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88Pro' COLLATE NOCASE), 'Finger Cymbal', 'Sample 4', 'SC-88Pro Map -> Drum Set', '053 ASIA', NULL, NULL, '53. The Void', 'main', 'ff_detailed', 1339),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88Pro' COLLATE NOCASE), 'Finger Cymbal', 'Sample 5', 'SC-88Pro Map -> Drum Set', '053 ASIA', NULL, NULL, '53. The Void', 'main', 'ff_detailed', 1340),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Udu Pot', 'Sample 6', NULL, NULL, NULL, 'UNKNOWN', '53. The Void', 'main', 'ff_detailed', 1341),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Udu Pot', 'Sample 7', NULL, NULL, NULL, 'UNKNOWN', '53. The Void', 'main', 'ff_detailed', 1342),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Conga(?)', 'Sample 8', NULL, NULL, NULL, 'UNKNOWN', '53. The Void', 'main', 'ff_detailed', 1343),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Wind SFX', 'Sample 9', NULL, NULL, NULL, 'UNKNOWN', '53. The Void', 'main', 'ff_detailed', 1344),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Wind SFX', 'Sample 10', NULL, NULL, NULL, 'UNKNOWN', '53. The Void', 'main', 'ff_detailed', 1345),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Wind SFX', 'Sample 11', NULL, NULL, NULL, 'UNKNOWN', '53. The Void', 'main', 'ff_detailed', 1346),
  -- T54: The Temple Players (Arranged by Junya Nakano) — 7 rows
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 0', NULL, NULL, NULL, 'UNKNOWN', '54. The Temple Players', 'main', 'ff_detailed', 1347),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 1', NULL, NULL, NULL, 'UNKNOWN', '54. The Temple Players', 'main', 'ff_detailed', 1348),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Udu Pot', 'Sample 2', NULL, NULL, NULL, 'UNKNOWN', '54. The Temple Players', 'main', 'ff_detailed', 1349),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Tambourine', 'Sample 3', NULL, NULL, NULL, 'UNKNOWN', '54. The Temple Players', 'main', 'ff_detailed', 1350),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Tambourine', 'Sample 4', NULL, NULL, NULL, 'UNKNOWN', '54. The Temple Players', 'main', 'ff_detailed', 1351),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Conga(?)', 'Sample 5', NULL, NULL, NULL, 'UNKNOWN', '54. The Temple Players', 'main', 'ff_detailed', 1352),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Conga(?)', 'Sample 6', NULL, NULL, NULL, 'UNKNOWN', '54. The Temple Players', 'main', 'ff_detailed', 1353),
  -- T55: Seymour''s Ambitions (Arranged by Nobuo Uematsu) — 30 rows, all UNKNOWN
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Slap Bass', 'Sample 0', NULL, NULL, NULL, 'UNKNOWN', '55. Seymour''s Ambitions', 'main', 'ff_detailed', 1354),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Slap Bass', 'Sample 1', NULL, NULL, NULL, 'UNKNOWN', '55. Seymour''s Ambitions', 'main', 'ff_detailed', 1355),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Choir', 'Sample 2', NULL, NULL, NULL, 'UNKNOWN', '55. Seymour''s Ambitions', 'main', 'ff_detailed', 1356),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Electric Guitar', 'Sample 3', NULL, NULL, NULL, 'UNKNOWN', '55. Seymour''s Ambitions', 'main', 'ff_detailed', 1357),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Electric Guitar', 'Sample 4', NULL, NULL, NULL, 'UNKNOWN', '55. Seymour''s Ambitions', 'main', 'ff_detailed', 1358),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Electric Guitar', 'Sample 5', NULL, NULL, NULL, 'UNKNOWN', '55. Seymour''s Ambitions', 'main', 'ff_detailed', 1359),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Electric Guitar', 'Sample 6', NULL, NULL, NULL, 'UNKNOWN', '55. Seymour''s Ambitions', 'main', 'ff_detailed', 1360),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Tom', 'Sample 7', NULL, NULL, NULL, 'UNKNOWN', '55. Seymour''s Ambitions', 'main', 'ff_detailed', 1361),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Snare', 'Sample 8', NULL, NULL, NULL, 'UNKNOWN', '55. Seymour''s Ambitions', 'main', 'ff_detailed', 1362),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Hi Hat', 'Sample 9', NULL, NULL, NULL, 'UNKNOWN', '55. Seymour''s Ambitions', 'main', 'ff_detailed', 1363),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Hi Hat', 'Sample 10', NULL, NULL, NULL, 'UNKNOWN', '55. Seymour''s Ambitions', 'main', 'ff_detailed', 1364),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Synth Pad', 'Sample 11', NULL, NULL, NULL, 'UNKNOWN', '55. Seymour''s Ambitions', 'main', 'ff_detailed', 1365),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Synth Pad', 'Sample 12', NULL, NULL, NULL, 'UNKNOWN', '55. Seymour''s Ambitions', 'main', 'ff_detailed', 1366),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Synth Pad', 'Sample 13', NULL, NULL, NULL, 'UNKNOWN', '55. Seymour''s Ambitions', 'main', 'ff_detailed', 1367),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 14', NULL, NULL, NULL, 'UNKNOWN', '55. Seymour''s Ambitions', 'main', 'ff_detailed', 1368),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 15', NULL, NULL, NULL, 'UNKNOWN', '55. Seymour''s Ambitions', 'main', 'ff_detailed', 1369),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 16', NULL, NULL, NULL, 'UNKNOWN', '55. Seymour''s Ambitions', 'main', 'ff_detailed', 1370),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 17', NULL, NULL, NULL, 'UNKNOWN', '55. Seymour''s Ambitions', 'main', 'ff_detailed', 1371),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 18', NULL, NULL, NULL, 'UNKNOWN', '55. Seymour''s Ambitions', 'main', 'ff_detailed', 1372),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 19', NULL, NULL, NULL, 'UNKNOWN', '55. Seymour''s Ambitions', 'main', 'ff_detailed', 1373),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 20', NULL, NULL, NULL, 'UNKNOWN', '55. Seymour''s Ambitions', 'main', 'ff_detailed', 1374),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 21', NULL, NULL, NULL, 'UNKNOWN', '55. Seymour''s Ambitions', 'main', 'ff_detailed', 1375),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 22', NULL, NULL, NULL, 'UNKNOWN', '55. Seymour''s Ambitions', 'main', 'ff_detailed', 1376),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Synth Bass', 'Sample 23', NULL, NULL, NULL, 'UNKNOWN', '55. Seymour''s Ambitions', 'main', 'ff_detailed', 1377),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Synth Bass', 'Sample 24', NULL, NULL, NULL, 'UNKNOWN', '55. Seymour''s Ambitions', 'main', 'ff_detailed', 1378),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Reverse Cymbal', 'Sample 25', NULL, NULL, NULL, 'UNKNOWN', '55. Seymour''s Ambitions', 'main', 'ff_detailed', 1379),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Santur(?)', 'Sample 26', NULL, NULL, NULL, 'UNKNOWN', '55. Seymour''s Ambitions', 'main', 'ff_detailed', 1380),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 27', NULL, NULL, NULL, 'UNKNOWN', '55. Seymour''s Ambitions', 'main', 'ff_detailed', 1381),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 28', NULL, NULL, NULL, 'UNKNOWN', '55. Seymour''s Ambitions', 'main', 'ff_detailed', 1382),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 29', NULL, NULL, NULL, 'UNKNOWN', '55. Seymour''s Ambitions', 'main', 'ff_detailed', 1383),
  -- T56: Hymn - Shiva — empty placeholder dropped
  -- T57: Pursuit (Arranged by Junya Nakano) — 19 rows, all UNKNOWN
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Dulcimer', 'Sample 0', NULL, NULL, NULL, 'UNKNOWN', '57. Pursuit', 'main', 'ff_detailed', 1384),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Dulcimer', 'Sample 1', NULL, NULL, NULL, 'UNKNOWN', '57. Pursuit', 'main', 'ff_detailed', 1385),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Synth Snare', 'Sample 2', NULL, NULL, NULL, 'UNKNOWN', '57. Pursuit', 'main', 'ff_detailed', 1386),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Synth Snare', 'Sample 3', NULL, NULL, NULL, 'UNKNOWN', '57. Pursuit', 'main', 'ff_detailed', 1387),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Synth Snare', 'Sample 4', NULL, NULL, NULL, 'UNKNOWN', '57. Pursuit', 'main', 'ff_detailed', 1388),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Synth Hi Hat', 'Sample 5', NULL, NULL, NULL, 'UNKNOWN', '57. Pursuit', 'main', 'ff_detailed', 1389),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Tambourine', 'Sample 6', NULL, NULL, NULL, 'UNKNOWN', '57. Pursuit', 'main', 'ff_detailed', 1390),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Synth Cymbal Crash', 'Sample 7', NULL, NULL, NULL, 'UNKNOWN', '57. Pursuit', 'main', 'ff_detailed', 1391),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Tambourine', 'Sample 8', NULL, NULL, NULL, 'UNKNOWN', '57. Pursuit', 'main', 'ff_detailed', 1392),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Metallic Hit', 'Sample 9', NULL, NULL, NULL, 'UNKNOWN', '57. Pursuit', 'main', 'ff_detailed', 1393),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Metallic Hit', 'Sample 10', NULL, NULL, NULL, 'UNKNOWN', '57. Pursuit', 'main', 'ff_detailed', 1394),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Metallic Hit', 'Sample 11', NULL, NULL, NULL, 'UNKNOWN', '57. Pursuit', 'main', 'ff_detailed', 1395),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Metallic Hit', 'Sample 12', NULL, NULL, NULL, 'UNKNOWN', '57. Pursuit', 'main', 'ff_detailed', 1396),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Timpani', 'Sample 13', NULL, NULL, NULL, 'UNKNOWN', '57. Pursuit', 'main', 'ff_detailed', 1397),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Timpani', 'Sample 14', NULL, NULL, NULL, 'UNKNOWN', '57. Pursuit', 'main', 'ff_detailed', 1398),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 15', NULL, NULL, NULL, 'UNKNOWN', '57. Pursuit', 'main', 'ff_detailed', 1399),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 16', NULL, NULL, NULL, 'UNKNOWN', '57. Pursuit', 'main', 'ff_detailed', 1400),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 17', NULL, NULL, NULL, 'UNKNOWN', '57. Pursuit', 'main', 'ff_detailed', 1401),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Low String Ensemble', 'Sample 18', NULL, NULL, NULL, 'UNKNOWN', '57. Pursuit', 'main', 'ff_detailed', 1402),
  -- T58: The Burning Sands (Arranged by Masashi Hamauzu) — 33 rows, all UNKNOWN
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Synth Voice', 'Sample 0', NULL, NULL, NULL, 'UNKNOWN', '58. The Burning Sands', 'main', 'ff_detailed', 1403),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Gamelan', 'Sample 1', NULL, NULL, NULL, 'UNKNOWN', '58. The Burning Sands', 'main', 'ff_detailed', 1404),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Gamelan', 'Sample 2', NULL, NULL, NULL, 'UNKNOWN', '58. The Burning Sands', 'main', 'ff_detailed', 1405),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Gamelan', 'Sample 3', NULL, NULL, NULL, 'UNKNOWN', '58. The Burning Sands', 'main', 'ff_detailed', 1406),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Synth Pad', 'Sample 4', NULL, NULL, NULL, 'UNKNOWN', '58. The Burning Sands', 'main', 'ff_detailed', 1407),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Synth Pad', 'Sample 5', NULL, NULL, NULL, 'UNKNOWN', '58. The Burning Sands', 'main', 'ff_detailed', 1408),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Synth Pad', 'Sample 6', NULL, NULL, NULL, 'UNKNOWN', '58. The Burning Sands', 'main', 'ff_detailed', 1409),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Djembe', 'Sample 7', NULL, NULL, NULL, 'UNKNOWN', '58. The Burning Sands', 'main', 'ff_detailed', 1410),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Djembe', 'Sample 8', NULL, NULL, NULL, 'UNKNOWN', '58. The Burning Sands', 'main', 'ff_detailed', 1411),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Djembe', 'Sample 9', NULL, NULL, NULL, 'UNKNOWN', '58. The Burning Sands', 'main', 'ff_detailed', 1412),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Djembe', 'Sample 10', NULL, NULL, NULL, 'UNKNOWN', '58. The Burning Sands', 'main', 'ff_detailed', 1413),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Djembe(?)', 'Sample 11', NULL, NULL, NULL, 'UNKNOWN', '58. The Burning Sands', 'main', 'ff_detailed', 1414),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Mellotron Strings', 'Sample 12', NULL, NULL, NULL, 'UNKNOWN', '58. The Burning Sands', 'main', 'ff_detailed', 1415),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Mandolin', 'Sample 13', NULL, NULL, NULL, 'UNKNOWN', '58. The Burning Sands', 'main', 'ff_detailed', 1416),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Mandolin', 'Sample 14', NULL, NULL, NULL, 'UNKNOWN', '58. The Burning Sands', 'main', 'ff_detailed', 1417),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Mandolin', 'Sample 15', NULL, NULL, NULL, 'UNKNOWN', '58. The Burning Sands', 'main', 'ff_detailed', 1418),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Mandolin', 'Sample 16', NULL, NULL, NULL, 'UNKNOWN', '58. The Burning Sands', 'main', 'ff_detailed', 1419),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Mandolin', 'Sample 17', NULL, NULL, NULL, 'UNKNOWN', '58. The Burning Sands', 'main', 'ff_detailed', 1420),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Mandolin', 'Sample 18', NULL, NULL, NULL, 'UNKNOWN', '58. The Burning Sands', 'main', 'ff_detailed', 1421),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Mandolin', 'Sample 19', NULL, NULL, NULL, 'UNKNOWN', '58. The Burning Sands', 'main', 'ff_detailed', 1422),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Mandolin', 'Sample 20', NULL, NULL, NULL, 'UNKNOWN', '58. The Burning Sands', 'main', 'ff_detailed', 1423),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Synth Pad', 'Sample 21', NULL, NULL, NULL, 'UNKNOWN', '58. The Burning Sands', 'main', 'ff_detailed', 1424),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Analog Chime', 'Sample 22', NULL, NULL, NULL, 'UNKNOWN', '58. The Burning Sands', 'main', 'ff_detailed', 1425),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Analog Chime', 'Sample 23', NULL, NULL, NULL, 'UNKNOWN', '58. The Burning Sands', 'main', 'ff_detailed', 1426),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Picked Bass', 'Sample 24', NULL, NULL, NULL, 'UNKNOWN', '58. The Burning Sands', 'main', 'ff_detailed', 1427),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Picked Bass', 'Sample 25', NULL, NULL, NULL, 'UNKNOWN', '58. The Burning Sands', 'main', 'ff_detailed', 1428),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 26', NULL, NULL, NULL, 'UNKNOWN', '58. The Burning Sands', 'main', 'ff_detailed', 1429),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 27', NULL, NULL, NULL, 'UNKNOWN', '58. The Burning Sands', 'main', 'ff_detailed', 1430),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 28', NULL, NULL, NULL, 'UNKNOWN', '58. The Burning Sands', 'main', 'ff_detailed', 1431),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 29', NULL, NULL, NULL, 'UNKNOWN', '58. The Burning Sands', 'main', 'ff_detailed', 1432),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 30', NULL, NULL, NULL, 'UNKNOWN', '58. The Burning Sands', 'main', 'ff_detailed', 1433),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 31', NULL, NULL, NULL, 'UNKNOWN', '58. The Burning Sands', 'main', 'ff_detailed', 1434),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Reverse Synth Pad', 'Sample 32', NULL, NULL, NULL, 'UNKNOWN', '58. The Burning Sands', 'main', 'ff_detailed', 1435),
  -- T59: Peril — 36 rows. Heavy Best Service Advanced Orchestra + 1 EastWest Percussive Adventures.
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Advanced Orchestra' COLLATE NOCASE), 'Cello Trill', 'Sample 0', 'CD 4 -> Partition G -> 31 BA FX 04', 'BA FX 04', NULL, NULL, '59. Peril', 'main', 'ff_detailed', 1436),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Advanced Orchestra' COLLATE NOCASE), 'Flute SFX', 'Sample 1', 'CD 4 -> Partition G -> 23 FL FX 09', 'FL FX 09A', NULL, NULL, '59. Peril', 'main', 'ff_detailed', 1437),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Tabla', 'Sample 2', NULL, NULL, NULL, 'UNKNOWN', '59. Peril', 'main', 'ff_detailed', 1438),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Tabla', 'Sample 3', NULL, NULL, NULL, 'UNKNOWN', '59. Peril', 'main', 'ff_detailed', 1439),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Percussive Adventures' COLLATE NOCASE), 'Hit SFX', 'Sample 4', 'Disc 1 -> Independence Day ', '04-DA-130', 'DAHAC6 -LR (E3)', NULL, '59. Peril', 'main', 'ff_detailed', 1440),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Advanced Orchestra' COLLATE NOCASE), 'String Suspense SFX', 'Sample 5', 'CD 4 -> Partition G -> 29 ST FX 01-4', 'ST FX 01', NULL, NULL, '59. Peril', 'main', 'ff_detailed', 1441),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String(?) SFX', 'Sample 6', NULL, NULL, NULL, 'UNKNOWN', '59. Peril', 'main', 'ff_detailed', 1442),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Advanced Orchestra' COLLATE NOCASE), 'Trombone Stacc', 'Sample 7', 'CD 4 -> Partition D -> 03 TB STAC 1', 'TB STACATO 1', NULL, NULL, '59. Peril', 'main', 'ff_detailed', 1443),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Advanced Orchestra' COLLATE NOCASE), 'Trombone Stacc', 'Sample 8', 'CD 4 -> Partition D -> 03 TB STAC 1', 'TB STACATO 1', NULL, NULL, '59. Peril', 'main', 'ff_detailed', 1444),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Advanced Orchestra' COLLATE NOCASE), 'Trombone Stacc', 'Sample 9', 'CD 4 -> Partition D -> 03 TB STAC 1', 'TB STACATO 1', NULL, NULL, '59. Peril', 'main', 'ff_detailed', 1445),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Advanced Orchestra' COLLATE NOCASE), 'Trombone Stacc', 'Sample 10', 'CD 4 -> Partition D -> 03 TB STAC 1', 'TB STACATO 1 ', NULL, NULL, '59. Peril', 'main', 'ff_detailed', 1446),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Advanced Orchestra' COLLATE NOCASE), 'Trombone Stacc', 'Sample 11', 'CD 4 -> Partition D -> 03 TB STAC 1', 'TB STACATO 1 ', NULL, NULL, '59. Peril', 'main', 'ff_detailed', 1447),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Advanced Orchestra' COLLATE NOCASE), 'Trombone Stacc', 'Sample 12', 'CD 4 -> Partition D -> 03 TB STAC 1', 'TB STACATO 1', NULL, NULL, '59. Peril', 'main', 'ff_detailed', 1448),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Advanced Orchestra' COLLATE NOCASE), 'Trombone Stacc', 'Sample 13', 'CD 4 -> Partition D -> 03 TB STAC 1', 'TB STACATO 1', NULL, NULL, '59. Peril', 'main', 'ff_detailed', 1449),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Advanced Orchestra' COLLATE NOCASE), 'Trombone Stacc', 'Sample 14', 'CD 4 -> Partition D -> 03 TB STAC 1', 'TB STACATO 1 ', NULL, NULL, '59. Peril', 'main', 'ff_detailed', 1450),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Advanced Orchestra' COLLATE NOCASE), 'Trombone Stacc', 'Sample 15', 'CD 4 -> Partition D -> 03 TB STAC 1', 'TB STACATO 1', NULL, NULL, '59. Peril', 'main', 'ff_detailed', 1451),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Advanced Orchestra' COLLATE NOCASE), 'Trombone Stacc', 'Sample 16', 'CD 4 -> Partition D -> 03 TB STAC 1', 'TB STACATO 1', NULL, NULL, '59. Peril', 'main', 'ff_detailed', 1452),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Advanced Orchestra' COLLATE NOCASE), 'Trombone Glissando', 'Sample 17', NULL, NULL, NULL, NULL, '59. Peril', 'main', 'ff_detailed', 1453),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Advanced Orchestra' COLLATE NOCASE), 'Trombone Glissando', 'Sample 18', NULL, NULL, NULL, NULL, '59. Peril', 'main', 'ff_detailed', 1454),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Advanced Orchestra' COLLATE NOCASE), 'Trombone Glissando', 'Sample 19', NULL, NULL, NULL, NULL, '59. Peril', 'main', 'ff_detailed', 1455),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Advanced Orchestra' COLLATE NOCASE), 'Trombone Glissando', 'Sample 20', NULL, NULL, NULL, NULL, '59. Peril', 'main', 'ff_detailed', 1456),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Advanced Orchestra' COLLATE NOCASE), 'Trombone Glissando', 'Sample 21', NULL, NULL, NULL, NULL, '59. Peril', 'main', 'ff_detailed', 1457),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Advanced Orchestra' COLLATE NOCASE), 'String Stacc', 'Sample 22', 'CD 4 -> Partition G -> 18 VA FX 01', 'VA FX 01E', NULL, NULL, '59. Peril', 'main', 'ff_detailed', 1458),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 23', NULL, NULL, NULL, 'UNKNOWN', '59. Peril', 'main', 'ff_detailed', 1459),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 24', NULL, NULL, NULL, 'UNKNOWN', '59. Peril', 'main', 'ff_detailed', 1460),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 25', NULL, NULL, NULL, 'UNKNOWN', '59. Peril', 'main', 'ff_detailed', 1461),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 26', NULL, NULL, NULL, 'UNKNOWN', '59. Peril', 'main', 'ff_detailed', 1462),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Hit SFX', 'Sample 27', NULL, NULL, NULL, 'UNKNOWN', '59. Peril', 'main', 'ff_detailed', 1463),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 28', NULL, NULL, NULL, 'UNKNOWN', '59. Peril', 'main', 'ff_detailed', 1464),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 29', NULL, NULL, NULL, 'UNKNOWN', '59. Peril', 'main', 'ff_detailed', 1465),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 30', NULL, NULL, NULL, 'UNKNOWN', '59. Peril', 'main', 'ff_detailed', 1466),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 31', NULL, NULL, NULL, 'UNKNOWN', '59. Peril', 'main', 'ff_detailed', 1467),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 32', NULL, NULL, NULL, 'UNKNOWN', '59. Peril', 'main', 'ff_detailed', 1468),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 33', NULL, NULL, NULL, 'UNKNOWN', '59. Peril', 'main', 'ff_detailed', 1469),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Advanced Orchestra' COLLATE NOCASE), 'Cymbal', 'Sample 34', 'CD 5 -> Partition A -> 01 CSY HITS', 'CSY MDFF', NULL, NULL, '59. Peril', 'main', 'ff_detailed', 1470),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Advanced Orchestra' COLLATE NOCASE), 'Cymbal', 'Sample 35', 'CD 5 -> Partition A -> 01 CSY HITS', 'CSY MDFF', NULL, NULL, '59. Peril', 'main', 'ff_detailed', 1471),
  -- T60: The Truth Revealed (Arranged by Nobuo Uematsu) — 38 rows (22 main + 16 variation), all UNKNOWN
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Triangle', 'Sample 0', NULL, NULL, NULL, 'UNKNOWN', '60. The Truth Revealed', 'main', 'ff_detailed', 1472),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Triangle', 'Sample 1', NULL, NULL, NULL, 'UNKNOWN', '60. The Truth Revealed', 'main', 'ff_detailed', 1473),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 2', NULL, NULL, NULL, 'UNKNOWN', '60. The Truth Revealed', 'main', 'ff_detailed', 1474),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 3', NULL, NULL, NULL, 'UNKNOWN', '60. The Truth Revealed', 'main', 'ff_detailed', 1475),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 4', NULL, NULL, NULL, 'UNKNOWN', '60. The Truth Revealed', 'main', 'ff_detailed', 1476),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 5', NULL, NULL, NULL, 'UNKNOWN', '60. The Truth Revealed', 'main', 'ff_detailed', 1477),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 6', NULL, NULL, NULL, 'UNKNOWN', '60. The Truth Revealed', 'main', 'ff_detailed', 1478),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 7', NULL, NULL, NULL, 'UNKNOWN', '60. The Truth Revealed', 'main', 'ff_detailed', 1479),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 8', NULL, NULL, NULL, 'UNKNOWN', '60. The Truth Revealed', 'main', 'ff_detailed', 1480),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 9', NULL, NULL, NULL, 'UNKNOWN', '60. The Truth Revealed', 'main', 'ff_detailed', 1481),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 10', NULL, NULL, NULL, 'UNKNOWN', '60. The Truth Revealed', 'main', 'ff_detailed', 1482),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 11', NULL, NULL, NULL, 'UNKNOWN', '60. The Truth Revealed', 'main', 'ff_detailed', 1483),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 12', NULL, NULL, NULL, 'UNKNOWN', '60. The Truth Revealed', 'main', 'ff_detailed', 1484),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 13', NULL, NULL, NULL, 'UNKNOWN', '60. The Truth Revealed', 'main', 'ff_detailed', 1485),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 14', NULL, NULL, NULL, 'UNKNOWN', '60. The Truth Revealed', 'main', 'ff_detailed', 1486),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 15', NULL, NULL, NULL, 'UNKNOWN', '60. The Truth Revealed', 'main', 'ff_detailed', 1487),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 16', NULL, NULL, NULL, 'UNKNOWN', '60. The Truth Revealed', 'main', 'ff_detailed', 1488),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 17', NULL, NULL, NULL, 'UNKNOWN', '60. The Truth Revealed', 'main', 'ff_detailed', 1489),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 18', NULL, NULL, NULL, 'UNKNOWN', '60. The Truth Revealed', 'main', 'ff_detailed', 1490),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 19', NULL, NULL, NULL, 'UNKNOWN', '60. The Truth Revealed', 'main', 'ff_detailed', 1491),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 20', NULL, NULL, NULL, 'UNKNOWN', '60. The Truth Revealed', 'main', 'ff_detailed', 1492),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 21', NULL, NULL, NULL, 'UNKNOWN', '60. The Truth Revealed', 'main', 'ff_detailed', 1493),
  -- T60 (Variation only) — 16 rows
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 0', NULL, NULL, NULL, 'UNKNOWN', '60. The Truth Revealed (Variation only)', 'main', 'ff_detailed', 1494),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 1', NULL, NULL, NULL, 'UNKNOWN', '60. The Truth Revealed (Variation only)', 'main', 'ff_detailed', 1495),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 2', NULL, NULL, NULL, 'UNKNOWN', '60. The Truth Revealed (Variation only)', 'main', 'ff_detailed', 1496),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Triangle', 'Sample 3', NULL, NULL, NULL, 'UNKNOWN', '60. The Truth Revealed (Variation only)', 'main', 'ff_detailed', 1497),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Triangle', 'Sample 4', NULL, NULL, NULL, 'UNKNOWN', '60. The Truth Revealed (Variation only)', 'main', 'ff_detailed', 1498),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 5', NULL, NULL, NULL, 'UNKNOWN', '60. The Truth Revealed (Variation only)', 'main', 'ff_detailed', 1499),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 6', NULL, NULL, NULL, 'UNKNOWN', '60. The Truth Revealed (Variation only)', 'main', 'ff_detailed', 1500),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 7', NULL, NULL, NULL, 'UNKNOWN', '60. The Truth Revealed (Variation only)', 'main', 'ff_detailed', 1501),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 8', NULL, NULL, NULL, 'UNKNOWN', '60. The Truth Revealed (Variation only)', 'main', 'ff_detailed', 1502),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 9', NULL, NULL, NULL, 'UNKNOWN', '60. The Truth Revealed (Variation only)', 'main', 'ff_detailed', 1503),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 10', NULL, NULL, NULL, 'UNKNOWN', '60. The Truth Revealed (Variation only)', 'main', 'ff_detailed', 1504),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 11', NULL, NULL, NULL, 'UNKNOWN', '60. The Truth Revealed (Variation only)', 'main', 'ff_detailed', 1505),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 12', NULL, NULL, NULL, 'UNKNOWN', '60. The Truth Revealed (Variation only)', 'main', 'ff_detailed', 1506),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 13', NULL, NULL, NULL, 'UNKNOWN', '60. The Truth Revealed (Variation only)', 'main', 'ff_detailed', 1507),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 14', NULL, NULL, NULL, 'UNKNOWN', '60. The Truth Revealed (Variation only)', 'main', 'ff_detailed', 1508),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 15', NULL, NULL, NULL, 'UNKNOWN', '60. The Truth Revealed (Variation only)', 'main', 'ff_detailed', 1509);
