-- Source: reference/Final Fantasy Sound Sources (Detailed) - Final Fantasy X.csv
-- Section 1 part 6 of N: tracks 71-82 (CSV rows 1922-2230). 285 rows.
-- Position numbering continues from part 5 (1767 onwards).
-- T74 Hymn - Yojimbo, T76 Hymn - Ronso, T79 Hymn - Yunalesca all dropped
-- as empty placeholders. T71 has duplicate "Sample 0" rows in the CSV
-- (lines 1924-1925) — preserved verbatim.
-- New products: Sampleheads / Dave Samuels - Marimba & Vibes;
-- Miroslav Vitous / Solo Instruments II 2.0; Sonic Foundry/Sounds Good /
-- Methods of Mayhem - Industrial Toolkit.

INSERT OR IGNORE INTO manufacturers (name) VALUES
  ('Sonic Foundry/Sounds Good');

INSERT OR IGNORE INTO products (manufacturer_id, name, type) VALUES
  ((SELECT id FROM manufacturers WHERE name = 'Sampleheads'                COLLATE NOCASE), 'Dave Samuels - Marimba & Vibes',            'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Miroslav Vitous'            COLLATE NOCASE), 'Solo Instruments II 2.0',                   'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Sonic Foundry/Sounds Good'  COLLATE NOCASE), 'Methods of Mayhem - Industrial Toolkit',    'Sample Library');

INSERT INTO usages
  (game_id, product_id, sample_label, sample_ref, path_bank, preset, notes, raw_source, examples, category, source_family, position)
VALUES
  -- T71: Yuna''s Decision — 28 rows, all UNKNOWN. CSV has Sample 0 duplicated.
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Analog Chime', 'Sample 0', NULL, NULL, NULL, 'UNKNOWN', '71. Yuna''s Decision', 'main', 'ff_detailed', 1767),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Analog Chime', 'Sample 0', NULL, NULL, NULL, 'UNKNOWN', '71. Yuna''s Decision', 'main', 'ff_detailed', 1768),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Analog Chime', 'Sample 1', NULL, NULL, NULL, 'UNKNOWN', '71. Yuna''s Decision', 'main', 'ff_detailed', 1769),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Analog Chime', 'Sample 2', NULL, NULL, NULL, 'UNKNOWN', '71. Yuna''s Decision', 'main', 'ff_detailed', 1770),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Analog Chime', 'Sample 3', NULL, NULL, NULL, 'UNKNOWN', '71. Yuna''s Decision', 'main', 'ff_detailed', 1771),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Fantasia Pad', 'Sample 4', NULL, NULL, NULL, 'UNKNOWN', '71. Yuna''s Decision', 'main', 'ff_detailed', 1772),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Fantasia Pad', 'Sample 5', NULL, NULL, NULL, 'UNKNOWN', '71. Yuna''s Decision', 'main', 'ff_detailed', 1773),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Fantasia Pad', 'Sample 6', NULL, NULL, NULL, 'UNKNOWN', '71. Yuna''s Decision', 'main', 'ff_detailed', 1774),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Fantasia Pad', 'Sample 7', NULL, NULL, NULL, 'UNKNOWN', '71. Yuna''s Decision', 'main', 'ff_detailed', 1775),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Fantasia Pad', 'Sample 8', NULL, NULL, NULL, 'UNKNOWN', '71. Yuna''s Decision', 'main', 'ff_detailed', 1776),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Fantasia Pad', 'Sample 9', NULL, NULL, NULL, 'UNKNOWN', '71. Yuna''s Decision', 'main', 'ff_detailed', 1777),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Synth Pad', 'Sample 10', NULL, NULL, NULL, 'UNKNOWN', '71. Yuna''s Decision', 'main', 'ff_detailed', 1778),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Synth Pad', 'Sample 11', NULL, NULL, NULL, 'UNKNOWN', '71. Yuna''s Decision', 'main', 'ff_detailed', 1779),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Synth Pad', 'Sample 12', NULL, NULL, NULL, 'UNKNOWN', '71. Yuna''s Decision', 'main', 'ff_detailed', 1780),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Synth Pad', 'Sample 13', NULL, NULL, NULL, 'UNKNOWN', '71. Yuna''s Decision', 'main', 'ff_detailed', 1781),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Synth Pad', 'Sample 14', NULL, NULL, NULL, 'UNKNOWN', '71. Yuna''s Decision', 'main', 'ff_detailed', 1782),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Synth Pad', 'Sample 15', NULL, NULL, NULL, 'UNKNOWN', '71. Yuna''s Decision', 'main', 'ff_detailed', 1783),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Synth Pad', 'Sample 16', NULL, NULL, NULL, 'UNKNOWN', '71. Yuna''s Decision', 'main', 'ff_detailed', 1784),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Synth Pad', 'Sample 17', NULL, NULL, NULL, 'UNKNOWN', '71. Yuna''s Decision', 'main', 'ff_detailed', 1785),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Synth Pad', 'Sample 18', NULL, NULL, NULL, 'UNKNOWN', '71. Yuna''s Decision', 'main', 'ff_detailed', 1786),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Synth Pad', 'Sample 19', NULL, NULL, NULL, 'UNKNOWN', '71. Yuna''s Decision', 'main', 'ff_detailed', 1787),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Flute', 'Sample 20', NULL, NULL, NULL, 'UNKNOWN', '71. Yuna''s Decision', 'main', 'ff_detailed', 1788),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Flute', 'Sample 21', NULL, NULL, NULL, 'UNKNOWN', '71. Yuna''s Decision', 'main', 'ff_detailed', 1789),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Flute', 'Sample 22', NULL, NULL, NULL, 'UNKNOWN', '71. Yuna''s Decision', 'main', 'ff_detailed', 1790),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Oboe', 'Sample 23', NULL, NULL, NULL, 'UNKNOWN', '71. Yuna''s Decision', 'main', 'ff_detailed', 1791),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Clarinet', 'Sample 24', NULL, NULL, NULL, 'UNKNOWN', '71. Yuna''s Decision', 'main', 'ff_detailed', 1792),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'English Horn', 'Sample 25', NULL, NULL, NULL, 'UNKNOWN', '71. Yuna''s Decision', 'main', 'ff_detailed', 1793),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'English Horn', 'Sample 26', NULL, NULL, NULL, 'UNKNOWN', '71. Yuna''s Decision', 'main', 'ff_detailed', 1794),
  -- T72: Lulu''s Theme — 29 rows. 3 sourced (Kurzweil).
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'English Horn', 'Sample 0', NULL, NULL, NULL, NULL, '72. Lulu''s Theme', 'main', 'ff_detailed', 1795),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'English Horn', 'Sample 1', NULL, NULL, NULL, NULL, '72. Lulu''s Theme', 'main', 'ff_detailed', 1796),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'English Horn', 'Sample 2', NULL, NULL, NULL, NULL, '72. Lulu''s Theme', 'main', 'ff_detailed', 1797),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'English Horn', 'Sample 3', NULL, NULL, NULL, NULL, '72. Lulu''s Theme', 'main', 'ff_detailed', 1798),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Mellotron Flute', 'Sample 4', NULL, NULL, NULL, NULL, '72. Lulu''s Theme', 'main', 'ff_detailed', 1799),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Mellotron Flute', 'Sample 5', NULL, NULL, NULL, NULL, '72. Lulu''s Theme', 'main', 'ff_detailed', 1800),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Mellotron Flute', 'Sample 6', NULL, NULL, NULL, NULL, '72. Lulu''s Theme', 'main', 'ff_detailed', 1801),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Mellotron Flute', 'Sample 7', NULL, NULL, NULL, NULL, '72. Lulu''s Theme', 'main', 'ff_detailed', 1802),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Mellotron Strings', 'Sample 8', NULL, NULL, NULL, NULL, '72. Lulu''s Theme', 'main', 'ff_detailed', 1803),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Mellotron Strings', 'Sample 9', NULL, NULL, NULL, NULL, '72. Lulu''s Theme', 'main', 'ff_detailed', 1804),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Mellotron Strings', 'Sample 10', NULL, NULL, NULL, NULL, '72. Lulu''s Theme', 'main', 'ff_detailed', 1805),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Mellotron Strings', 'Sample 11', NULL, NULL, NULL, NULL, '72. Lulu''s Theme', 'main', 'ff_detailed', 1806),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Harp', 'Sample 12', NULL, NULL, NULL, NULL, '72. Lulu''s Theme', 'main', 'ff_detailed', 1807),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Harp', 'Sample 13', NULL, NULL, NULL, NULL, '72. Lulu''s Theme', 'main', 'ff_detailed', 1808),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Harp', 'Sample 14', NULL, NULL, NULL, NULL, '72. Lulu''s Theme', 'main', 'ff_detailed', 1809),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Kurzweil' COLLATE NOCASE AND p.name = 'Orchestral ROM' COLLATE NOCASE), 'Pizzicato Strings', 'Sample 15', 'Programs -> Section Strings', '957 Pizzicato String', NULL, NULL, '72. Lulu''s Theme', 'main', 'ff_detailed', 1810),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Kurzweil' COLLATE NOCASE AND p.name = 'Orchestral ROM' COLLATE NOCASE), 'Pizzicato Strings', 'Sample 16', 'Programs -> Section Strings', '957 Pizzicato String', NULL, NULL, '72. Lulu''s Theme', 'main', 'ff_detailed', 1811),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Kurzweil' COLLATE NOCASE AND p.name = 'Orchestral ROM' COLLATE NOCASE), 'Pizzicato Strings', 'Sample 17', 'Programs -> Section Strings', '957 Pizzicato String', NULL, NULL, '72. Lulu''s Theme', 'main', 'ff_detailed', 1812),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 18', NULL, NULL, NULL, NULL, '72. Lulu''s Theme', 'main', 'ff_detailed', 1813),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 19', NULL, NULL, NULL, NULL, '72. Lulu''s Theme', 'main', 'ff_detailed', 1814),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 20', NULL, NULL, NULL, NULL, '72. Lulu''s Theme', 'main', 'ff_detailed', 1815),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 21', NULL, NULL, NULL, NULL, '72. Lulu''s Theme', 'main', 'ff_detailed', 1816),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Choir', 'Sample 22', NULL, NULL, NULL, NULL, '72. Lulu''s Theme', 'main', 'ff_detailed', 1817),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Choir', 'Sample 23', NULL, NULL, NULL, NULL, '72. Lulu''s Theme', 'main', 'ff_detailed', 1818),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Choir', 'Sample 24', NULL, NULL, NULL, NULL, '72. Lulu''s Theme', 'main', 'ff_detailed', 1819),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Choir', 'Sample 25', NULL, NULL, NULL, NULL, '72. Lulu''s Theme', 'main', 'ff_detailed', 1820),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Choir', 'Sample 26', NULL, NULL, NULL, NULL, '72. Lulu''s Theme', 'main', 'ff_detailed', 1821),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Picked Bass', 'Sample 27', NULL, NULL, NULL, NULL, '72. Lulu''s Theme', 'main', 'ff_detailed', 1822),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Picked Bass', 'Sample 28', NULL, NULL, NULL, NULL, '72. Lulu''s Theme', 'main', 'ff_detailed', 1823),
  -- T73: Bravely Forward — 28 rows, all empty source
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Finger Bass', 'Sample 0', NULL, NULL, NULL, NULL, '73. Bravely Forward', 'main', 'ff_detailed', 1824),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'French Horn', 'Sample 1', NULL, NULL, NULL, NULL, '73. Bravely Forward', 'main', 'ff_detailed', 1825),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'French Horn', 'Sample 2', NULL, NULL, NULL, NULL, '73. Bravely Forward', 'main', 'ff_detailed', 1826),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'French Horn', 'Sample 3', NULL, NULL, NULL, NULL, '73. Bravely Forward', 'main', 'ff_detailed', 1827),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Organ', 'Sample 4', NULL, NULL, NULL, NULL, '73. Bravely Forward', 'main', 'ff_detailed', 1828),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Organ', 'Sample 5', NULL, NULL, NULL, NULL, '73. Bravely Forward', 'main', 'ff_detailed', 1829),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Organ', 'Sample 6', NULL, NULL, NULL, NULL, '73. Bravely Forward', 'main', 'ff_detailed', 1830),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Organ', 'Sample 7', NULL, NULL, NULL, NULL, '73. Bravely Forward', 'main', 'ff_detailed', 1831),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Kick', 'Sample 8', NULL, NULL, NULL, NULL, '73. Bravely Forward', 'main', 'ff_detailed', 1832),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Kick', 'Sample 9', NULL, NULL, NULL, NULL, '73. Bravely Forward', 'main', 'ff_detailed', 1833),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Snare', 'Sample 10', NULL, NULL, NULL, NULL, '73. Bravely Forward', 'main', 'ff_detailed', 1834),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Hi Hat', 'Sample 11', NULL, NULL, NULL, NULL, '73. Bravely Forward', 'main', 'ff_detailed', 1835),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Snare', 'Sample 12', NULL, NULL, NULL, NULL, '73. Bravely Forward', 'main', 'ff_detailed', 1836),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Hi Hat', 'Sample 13', NULL, NULL, NULL, NULL, '73. Bravely Forward', 'main', 'ff_detailed', 1837),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Snare', 'Sample 14', NULL, NULL, NULL, NULL, '73. Bravely Forward', 'main', 'ff_detailed', 1838),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Cymbal Crash', 'Sample 15', NULL, NULL, NULL, NULL, '73. Bravely Forward', 'main', 'ff_detailed', 1839),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Cymbal Crash', 'Sample 16', NULL, NULL, NULL, NULL, '73. Bravely Forward', 'main', 'ff_detailed', 1840),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Gun Shot', 'Sample 17', NULL, NULL, NULL, NULL, '73. Bravely Forward', 'main', 'ff_detailed', 1841),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 18', NULL, NULL, NULL, NULL, '73. Bravely Forward', 'main', 'ff_detailed', 1842),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 19', NULL, NULL, NULL, NULL, '73. Bravely Forward', 'main', 'ff_detailed', 1843),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 20', NULL, NULL, NULL, NULL, '73. Bravely Forward', 'main', 'ff_detailed', 1844),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 21', NULL, NULL, NULL, NULL, '73. Bravely Forward', 'main', 'ff_detailed', 1845),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 22', NULL, NULL, NULL, NULL, '73. Bravely Forward', 'main', 'ff_detailed', 1846),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 23', NULL, NULL, NULL, NULL, '73. Bravely Forward', 'main', 'ff_detailed', 1847),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 24', NULL, NULL, NULL, NULL, '73. Bravely Forward', 'main', 'ff_detailed', 1848),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Trumpet', 'Sample 25', NULL, NULL, NULL, NULL, '73. Bravely Forward', 'main', 'ff_detailed', 1849),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Whistle', 'Sample 26', NULL, NULL, NULL, NULL, '73. Bravely Forward', 'main', 'ff_detailed', 1850),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Whistle', 'Sample 27', NULL, NULL, NULL, NULL, '73. Bravely Forward', 'main', 'ff_detailed', 1851),
  -- T74: Hymn - Yojimbo — empty placeholder dropped
  -- T75: Servants of the Mountain (Arranged by Masashi Hamauzu) — 38 rows
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 0', NULL, NULL, NULL, 'UNKNOWN', '75. Servants of the Mountain', 'main', 'ff_detailed', 1852),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 1', NULL, NULL, NULL, 'UNKNOWN', '75. Servants of the Mountain', 'main', 'ff_detailed', 1853),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 2', NULL, NULL, NULL, 'UNKNOWN', '75. Servants of the Mountain', 'main', 'ff_detailed', 1854),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 3', NULL, NULL, NULL, 'UNKNOWN', '75. Servants of the Mountain', 'main', 'ff_detailed', 1855),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Staccato Strings', 'Sample 4', NULL, NULL, NULL, 'UNKNOWN', '75. Servants of the Mountain', 'main', 'ff_detailed', 1856),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Djembe', 'Sample 5', NULL, NULL, NULL, 'UNKNOWN', '75. Servants of the Mountain', 'main', 'ff_detailed', 1857),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Djembe Rim', 'Sample 6', NULL, NULL, NULL, 'UNKNOWN', '75. Servants of the Mountain', 'main', 'ff_detailed', 1858),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Whip', 'Sample 7', NULL, NULL, NULL, 'UNKNOWN', '75. Servants of the Mountain', 'main', 'ff_detailed', 1859),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Tom', 'Sample 8', NULL, NULL, NULL, 'UNKNOWN', '75. Servants of the Mountain', 'main', 'ff_detailed', 1860),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Tom', 'Sample 9', NULL, NULL, NULL, 'UNKNOWN', '75. Servants of the Mountain', 'main', 'ff_detailed', 1861),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Tom', 'Sample 10', NULL, NULL, NULL, 'UNKNOWN', '75. Servants of the Mountain', 'main', 'ff_detailed', 1862),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Tom', 'Sample 11', NULL, NULL, NULL, 'UNKNOWN', '75. Servants of the Mountain', 'main', 'ff_detailed', 1863),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Tom', 'Sample 12', NULL, NULL, NULL, 'UNKNOWN', '75. Servants of the Mountain', 'main', 'ff_detailed', 1864),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Staccato Strings', 'Sample 13', NULL, NULL, NULL, 'UNKNOWN', '75. Servants of the Mountain', 'main', 'ff_detailed', 1865),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Staccato Strings', 'Sample 14', NULL, NULL, NULL, 'UNKNOWN', '75. Servants of the Mountain', 'main', 'ff_detailed', 1866),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Staccato Strings', 'Sample 15', NULL, NULL, NULL, 'UNKNOWN', '75. Servants of the Mountain', 'main', 'ff_detailed', 1867),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Staccato Strings', 'Sample 16', NULL, NULL, NULL, 'UNKNOWN', '75. Servants of the Mountain', 'main', 'ff_detailed', 1868),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Bagpipes', 'Sample 17', NULL, NULL, NULL, 'UNKNOWN', '75. Servants of the Mountain', 'main', 'ff_detailed', 1869),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Bagpipes', 'Sample 18', NULL, NULL, NULL, 'UNKNOWN', '75. Servants of the Mountain', 'main', 'ff_detailed', 1870),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sampleheads' COLLATE NOCASE AND p.name = 'Dave Samuels - Marimba & Vibes' COLLATE NOCASE), 'Marimba', 'Sample 19', 'Partition B -> MRMBA HARD F', 'MRMBAHRD F A', NULL, NULL, '75. Servants of the Mountain', 'main', 'ff_detailed', 1871),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sampleheads' COLLATE NOCASE AND p.name = 'Dave Samuels - Marimba & Vibes' COLLATE NOCASE), 'Marimba', 'Sample 20', 'Partition B -> MRMBA HARD F', 'MRMBAHRD F A', NULL, NULL, '75. Servants of the Mountain', 'main', 'ff_detailed', 1872),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sampleheads' COLLATE NOCASE AND p.name = 'Dave Samuels - Marimba & Vibes' COLLATE NOCASE), 'Marimba', 'Sample 21', 'Partition B -> MRMBA HARD F', 'MRMBAHRD F A', NULL, NULL, '75. Servants of the Mountain', 'main', 'ff_detailed', 1873),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 22', NULL, NULL, NULL, 'UNKNOWN', '75. Servants of the Mountain', 'main', 'ff_detailed', 1874),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 23', NULL, NULL, NULL, 'UNKNOWN', '75. Servants of the Mountain', 'main', 'ff_detailed', 1875),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 24', NULL, NULL, NULL, 'UNKNOWN', '75. Servants of the Mountain', 'main', 'ff_detailed', 1876),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Miroslav Vitous' COLLATE NOCASE AND p.name = 'Solo Instruments II 2.0' COLLATE NOCASE), 'Solo Violin', 'Sample 25', 'Solo Inst. II -> 015 Violin', 'Violin', NULL, NULL, '75. Servants of the Mountain', 'main', 'ff_detailed', 1877),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Miroslav Vitous' COLLATE NOCASE AND p.name = 'Solo Instruments II 2.0' COLLATE NOCASE), 'Solo Violin', 'Sample 26', 'Solo Inst. II -> 015 Violin', 'Violin', NULL, NULL, '75. Servants of the Mountain', 'main', 'ff_detailed', 1878),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Miroslav Vitous' COLLATE NOCASE AND p.name = 'Solo Instruments II 2.0' COLLATE NOCASE), 'Solo Violin', 'Sample 27', 'Solo Inst. II -> 015 Violin', 'Violin', NULL, NULL, '75. Servants of the Mountain', 'main', 'ff_detailed', 1879),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Miroslav Vitous' COLLATE NOCASE AND p.name = 'Solo Instruments II 2.0' COLLATE NOCASE), 'Solo Violin', 'Sample 28', 'Solo Inst. II -> 015 Violin', 'Violin', NULL, NULL, '75. Servants of the Mountain', 'main', 'ff_detailed', 1880),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Miroslav Vitous' COLLATE NOCASE AND p.name = 'Solo Instruments II 2.0' COLLATE NOCASE), 'Solo Violin', 'Sample 29', 'Solo Inst. II -> 015 Violin', 'Violin', NULL, NULL, '75. Servants of the Mountain', 'main', 'ff_detailed', 1881),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Miroslav Vitous' COLLATE NOCASE AND p.name = 'Solo Instruments II 2.0' COLLATE NOCASE), 'Solo Violin', 'Sample 30', 'Solo Inst. II -> 015 Violin', 'Violin', NULL, NULL, '75. Servants of the Mountain', 'main', 'ff_detailed', 1882),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Miroslav Vitous' COLLATE NOCASE AND p.name = 'Solo Instruments II 2.0' COLLATE NOCASE), 'Solo Violin', 'Sample 31', 'Solo Inst. II -> 015 Violin', 'Violin', NULL, NULL, '75. Servants of the Mountain', 'main', 'ff_detailed', 1883),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Miroslav Vitous' COLLATE NOCASE AND p.name = 'Solo Instruments II 2.0' COLLATE NOCASE), 'Solo Violin', 'Sample 32', 'Solo Inst. II -> 015 Violin', 'Violin', NULL, NULL, '75. Servants of the Mountain', 'main', 'ff_detailed', 1884),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Slow String Ensemble', 'Sample 33', NULL, NULL, NULL, 'UNKNOWN', '75. Servants of the Mountain', 'main', 'ff_detailed', 1885),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Slow String Ensemble', 'Sample 34', NULL, NULL, NULL, 'UNKNOWN', '75. Servants of the Mountain', 'main', 'ff_detailed', 1886),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Slow String Ensemble', 'Sample 35', NULL, NULL, NULL, 'UNKNOWN', '75. Servants of the Mountain', 'main', 'ff_detailed', 1887),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Slow String Ensemble', 'Sample 36', NULL, NULL, NULL, 'UNKNOWN', '75. Servants of the Mountain', 'main', 'ff_detailed', 1888),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Slow String Ensemble', 'Sample 37', NULL, NULL, NULL, 'UNKNOWN', '75. Servants of the Mountain', 'main', 'ff_detailed', 1889),
  -- T76: Hymn - Ronso — empty placeholder dropped
  -- T77: Wandering (Arranged by Masashi Hamauzu) — 29 rows, mostly empty source, 2 Miroslav Vitous
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Clarinet Crescendo', 'Sample 0', NULL, NULL, NULL, NULL, '77. Wandering', 'main', 'ff_detailed', 1890),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Clarinet Crescendo', 'Sample 1', NULL, NULL, NULL, NULL, '77. Wandering', 'main', 'ff_detailed', 1891),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Clarinet Crescendo', 'Sample 2', NULL, NULL, NULL, NULL, '77. Wandering', 'main', 'ff_detailed', 1892),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Clarinet Grace', 'Sample 3', NULL, NULL, NULL, NULL, '77. Wandering', 'main', 'ff_detailed', 1893),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Clarinet Grace', 'Sample 4', NULL, NULL, NULL, NULL, '77. Wandering', 'main', 'ff_detailed', 1894),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Clarinet Grace', 'Sample 5', NULL, NULL, NULL, NULL, '77. Wandering', 'main', 'ff_detailed', 1895),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Clarinet', 'Sample 6', NULL, NULL, NULL, NULL, '77. Wandering', 'main', 'ff_detailed', 1896),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Clarinet', 'Sample 7', NULL, NULL, NULL, NULL, '77. Wandering', 'main', 'ff_detailed', 1897),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Clarinet', 'Sample 8', NULL, NULL, NULL, NULL, '77. Wandering', 'main', 'ff_detailed', 1898),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Clarinet', 'Sample 9', NULL, NULL, NULL, NULL, '77. Wandering', 'main', 'ff_detailed', 1899),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Clarinet', 'Sample 10', NULL, NULL, NULL, NULL, '77. Wandering', 'main', 'ff_detailed', 1900),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Clarinet', 'Sample 11', NULL, NULL, NULL, NULL, '77. Wandering', 'main', 'ff_detailed', 1901),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Clarinet', 'Sample 12', NULL, NULL, NULL, NULL, '77. Wandering', 'main', 'ff_detailed', 1902),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Clarinet', 'Sample 13', NULL, NULL, NULL, NULL, '77. Wandering', 'main', 'ff_detailed', 1903),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Clarinet Staccato', 'Sample 14', NULL, NULL, NULL, NULL, '77. Wandering', 'main', 'ff_detailed', 1904),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Clarinet Staccato', 'Sample 15', NULL, NULL, NULL, NULL, '77. Wandering', 'main', 'ff_detailed', 1905),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Clarinet Staccato', 'Sample 16', NULL, NULL, NULL, NULL, '77. Wandering', 'main', 'ff_detailed', 1906),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Clarinet Staccato', 'Sample 17', NULL, NULL, NULL, NULL, '77. Wandering', 'main', 'ff_detailed', 1907),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Guiro(?)', 'Sample 18', NULL, NULL, NULL, NULL, '77. Wandering', 'main', 'ff_detailed', 1908),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Miroslav Vitous' COLLATE NOCASE AND p.name = 'Solo Instruments II 2.0' COLLATE NOCASE), 'Flute', 'Sample 19', NULL, NULL, NULL, NULL, '77. Wandering', 'main', 'ff_detailed', 1909),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Miroslav Vitous' COLLATE NOCASE AND p.name = 'Solo Instruments II 2.0' COLLATE NOCASE), 'Flute', 'Sample 20', NULL, NULL, NULL, NULL, '77. Wandering', 'main', 'ff_detailed', 1910),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Synth Pad', 'Sample 21', NULL, NULL, NULL, NULL, '77. Wandering', 'main', 'ff_detailed', 1911),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Synth Pad', 'Sample 22', NULL, NULL, NULL, NULL, '77. Wandering', 'main', 'ff_detailed', 1912),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Synth Pad', 'Sample 23', NULL, NULL, NULL, NULL, '77. Wandering', 'main', 'ff_detailed', 1913),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Synth Pad', 'Sample 24', NULL, NULL, NULL, NULL, '77. Wandering', 'main', 'ff_detailed', 1914),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Synth Pad', 'Sample 25', NULL, NULL, NULL, NULL, '77. Wandering', 'main', 'ff_detailed', 1915),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Synth Pad', 'Sample 26', NULL, NULL, NULL, NULL, '77. Wandering', 'main', 'ff_detailed', 1916),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Distortion FX', 'Sample 27', NULL, NULL, NULL, NULL, '77. Wandering', 'main', 'ff_detailed', 1917),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Distortion FX', 'Sample 28', NULL, NULL, NULL, NULL, '77. Wandering', 'main', 'ff_detailed', 1918),
  -- T78: A Fleeting Dream (Arranged by Masashi Hamauzu) — 29 rows
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Miroslav Vitous' COLLATE NOCASE AND p.name = 'Solo Instruments II 2.0' COLLATE NOCASE), 'Oboe', 'Sample 0', 'Solo Inst. II -> 005 Oboe', 'Oboe 1x', NULL, NULL, '78. A Fleeting Dream', 'main', 'ff_detailed', 1919),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Miroslav Vitous' COLLATE NOCASE AND p.name = 'Solo Instruments II 2.0' COLLATE NOCASE), 'Oboe', 'Sample 1', 'Solo Inst. II -> 005 Oboe', 'Oboe 1x', NULL, NULL, '78. A Fleeting Dream', 'main', 'ff_detailed', 1920),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Miroslav Vitous' COLLATE NOCASE AND p.name = 'Solo Instruments II 2.0' COLLATE NOCASE), 'Oboe', 'Sample 2', 'Solo Inst. II -> 005 Oboe', 'Oboe 1x', NULL, NULL, '78. A Fleeting Dream', 'main', 'ff_detailed', 1921),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Miroslav Vitous' COLLATE NOCASE AND p.name = 'Solo Instruments II 2.0' COLLATE NOCASE), 'Oboe', 'Sample 3', 'Solo Inst. II -> 005 Oboe', 'Oboe 1x', NULL, NULL, '78. A Fleeting Dream', 'main', 'ff_detailed', 1922),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Miroslav Vitous' COLLATE NOCASE AND p.name = 'Solo Instruments II 2.0' COLLATE NOCASE), 'Flute', 'Sample 4', 'Solo Inst. II -> 002 Flute', 'Flute', NULL, NULL, '78. A Fleeting Dream', 'main', 'ff_detailed', 1923),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Miroslav Vitous' COLLATE NOCASE AND p.name = 'Solo Instruments II 2.0' COLLATE NOCASE), 'Flute', 'Sample 5', 'CHECK', 'CHECK', NULL, NULL, '78. A Fleeting Dream', 'main', 'ff_detailed', 1924),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Miroslav Vitous' COLLATE NOCASE AND p.name = 'Solo Instruments II 2.0' COLLATE NOCASE), 'Flute', 'Sample 6', 'Solo Inst. II -> 002 Flute', 'Flute', NULL, NULL, '78. A Fleeting Dream', 'main', 'ff_detailed', 1925),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 7', NULL, NULL, NULL, NULL, '78. A Fleeting Dream', 'main', 'ff_detailed', 1926),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 8', NULL, NULL, NULL, NULL, '78. A Fleeting Dream', 'main', 'ff_detailed', 1927),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 9', NULL, NULL, NULL, NULL, '78. A Fleeting Dream', 'main', 'ff_detailed', 1928),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 10', NULL, NULL, NULL, NULL, '78. A Fleeting Dream', 'main', 'ff_detailed', 1929),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 11', NULL, NULL, NULL, NULL, '78. A Fleeting Dream', 'main', 'ff_detailed', 1930),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 12', NULL, NULL, NULL, NULL, '78. A Fleeting Dream', 'main', 'ff_detailed', 1931),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 13', NULL, NULL, NULL, NULL, '78. A Fleeting Dream', 'main', 'ff_detailed', 1932),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 14', NULL, NULL, NULL, NULL, '78. A Fleeting Dream', 'main', 'ff_detailed', 1933),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 15', NULL, NULL, NULL, NULL, '78. A Fleeting Dream', 'main', 'ff_detailed', 1934),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Percussion Hit', 'Sample 16', NULL, NULL, NULL, NULL, '78. A Fleeting Dream', 'main', 'ff_detailed', 1935),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Percussion Hit', 'Sample 17', NULL, NULL, NULL, NULL, '78. A Fleeting Dream', 'main', 'ff_detailed', 1936),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Distorted Reality 2' COLLATE NOCASE), 'Synth Hit', 'Sample 18', 'CD 2 -> Partition D -> 01 LO-TEK 1', 'LO-TEK-BITS1 [G1]', NULL, NULL, '78. A Fleeting Dream', 'main', 'ff_detailed', 1937),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JV-1080' COLLATE NOCASE), 'Piano', 'Sample 19', 'PR-A', '005 Piano Thang', NULL, NULL, '78. A Fleeting Dream', 'main', 'ff_detailed', 1938),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JV-1080' COLLATE NOCASE), 'Piano', 'Sample 20', 'PR-A', '005 Piano Thang', NULL, NULL, '78. A Fleeting Dream', 'main', 'ff_detailed', 1939),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JV-1080' COLLATE NOCASE), 'Piano', 'Sample 21', 'PR-A', '005 Piano Thang', NULL, NULL, '78. A Fleeting Dream', 'main', 'ff_detailed', 1940),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JV-1080' COLLATE NOCASE), 'Piano', 'Sample 22', 'PR-A', '005 Piano Thang', NULL, NULL, '78. A Fleeting Dream', 'main', 'ff_detailed', 1941),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JV-1080' COLLATE NOCASE), 'Piano', 'Sample 23', 'PR-A', '005 Piano Thang', NULL, NULL, '78. A Fleeting Dream', 'main', 'ff_detailed', 1942),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Cymbal Crash', 'Sample 24', NULL, NULL, NULL, NULL, '78. A Fleeting Dream', 'main', 'ff_detailed', 1943),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Timpani', 'Sample 25', NULL, NULL, NULL, NULL, '78. A Fleeting Dream', 'main', 'ff_detailed', 1944),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Timpani', 'Sample 26', NULL, NULL, NULL, NULL, '78. A Fleeting Dream', 'main', 'ff_detailed', 1945),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-02 Orchestral' COLLATE NOCASE), 'French Horn', 'Sample 27', 'XP-X', '131 F.Hrn Sect4', NULL, NULL, '78. A Fleeting Dream', 'main', 'ff_detailed', 1946),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-02 Orchestral' COLLATE NOCASE), 'French Horn', 'Sample 28', 'XP-X', '131 F.Hrn Sect4', NULL, NULL, '78. A Fleeting Dream', 'main', 'ff_detailed', 1947),
  -- T79: Hymn - Yunalesca — empty placeholder dropped
  -- T80: Challenge (Arranged by Masashi Hamauzu) — 32 rows
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Hans Zimmer Guitars Vol. 1' COLLATE NOCASE), 'Distorted Guitar', 'Sample 0', NULL, NULL, NULL, NULL, '80. Challenge', 'main', 'ff_detailed', 1948),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Hans Zimmer Guitars Vol. 1' COLLATE NOCASE), 'Guitar Harmonics', 'Sample 1', NULL, NULL, NULL, NULL, '80. Challenge', 'main', 'ff_detailed', 1949),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Drum Loop', 'Sample 2', NULL, NULL, NULL, 'UNKNOWN', '80. Challenge', 'main', 'ff_detailed', 1950),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sonic Foundry/Sounds Good' COLLATE NOCASE AND p.name = 'Methods of Mayhem - Industrial Toolkit' COLLATE NOCASE), 'Guitar Loop', 'Sample 3', 'Nasty', 'Riff 11 32-01', NULL, NULL, '80. Challenge', 'main', 'ff_detailed', 1951),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Synth String', 'Sample 4', NULL, NULL, NULL, 'UNKNOWN', '80. Challenge', 'main', 'ff_detailed', 1952),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Synth String', 'Sample 5', NULL, NULL, NULL, 'UNKNOWN', '80. Challenge', 'main', 'ff_detailed', 1953),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Synth Pad', 'Sample 6', NULL, NULL, NULL, 'UNKNOWN', '80. Challenge', 'main', 'ff_detailed', 1954),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Cymbal Crash', 'Sample 7', NULL, NULL, NULL, 'UNKNOWN', '80. Challenge', 'main', 'ff_detailed', 1955),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Kick', 'Sample 8', NULL, NULL, NULL, 'UNKNOWN', '80. Challenge', 'main', 'ff_detailed', 1956),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Kick', 'Sample 9', NULL, NULL, NULL, 'UNKNOWN', '80. Challenge', 'main', 'ff_detailed', 1957),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Synth Bass', 'Sample 10', NULL, NULL, NULL, 'UNKNOWN', '80. Challenge', 'main', 'ff_detailed', 1958),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Synth Bass', 'Sample 11', NULL, NULL, NULL, 'UNKNOWN', '80. Challenge', 'main', 'ff_detailed', 1959),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Synth Bass', 'Sample 12', NULL, NULL, NULL, 'UNKNOWN', '80. Challenge', 'main', 'ff_detailed', 1960),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Synth Bass', 'Sample 13', NULL, NULL, NULL, 'UNKNOWN', '80. Challenge', 'main', 'ff_detailed', 1961),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sampleheads' COLLATE NOCASE AND p.name = 'Peter Erskine - Living Drums' COLLATE NOCASE), 'Snare', 'Sample 14', 'CHECK', 'CHECK', NULL, NULL, '80. Challenge', 'main', 'ff_detailed', 1962),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sampleheads' COLLATE NOCASE AND p.name = 'Peter Erskine - Living Drums' COLLATE NOCASE), 'Snare', 'Sample 15', 'CHECK', 'CHECK', NULL, NULL, '80. Challenge', 'main', 'ff_detailed', 1963),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sampleheads' COLLATE NOCASE AND p.name = 'Peter Erskine - Living Drums' COLLATE NOCASE), 'Snare', 'Sample 16', 'CHECK', 'CHECK', NULL, NULL, '80. Challenge', 'main', 'ff_detailed', 1964),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sampleheads' COLLATE NOCASE AND p.name = 'Peter Erskine - Living Drums' COLLATE NOCASE), 'Snare', 'Sample 17', 'CHECK', 'CHECK', NULL, NULL, '80. Challenge', 'main', 'ff_detailed', 1965),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sampleheads' COLLATE NOCASE AND p.name = 'Peter Erskine - Living Drums' COLLATE NOCASE), 'Snare', 'Sample 18', 'CHECK', 'CHECK', NULL, NULL, '80. Challenge', 'main', 'ff_detailed', 1966),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sampleheads' COLLATE NOCASE AND p.name = 'Peter Erskine - Living Drums' COLLATE NOCASE), 'Snare', 'Sample 19', 'CHECK', 'CHECK', NULL, NULL, '80. Challenge', 'main', 'ff_detailed', 1967),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Picked Bass', 'Sample 20', NULL, NULL, NULL, 'UNKNOWN', '80. Challenge', 'main', 'ff_detailed', 1968),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Picked Bass', 'Sample 21', NULL, NULL, NULL, 'UNKNOWN', '80. Challenge', 'main', 'ff_detailed', 1969),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Hi Hat', 'Sample 22', NULL, NULL, NULL, 'UNKNOWN', '80. Challenge', 'main', 'ff_detailed', 1970),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Hi Hat', 'Sample 23', NULL, NULL, NULL, 'UNKNOWN', '80. Challenge', 'main', 'ff_detailed', 1971),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Hi Hat', 'Sample 24', NULL, NULL, NULL, 'UNKNOWN', '80. Challenge', 'main', 'ff_detailed', 1972),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Hi Hat', 'Sample 25', NULL, NULL, NULL, 'UNKNOWN', '80. Challenge', 'main', 'ff_detailed', 1973),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Synth String', 'Sample 26', NULL, NULL, NULL, 'UNKNOWN', '80. Challenge', 'main', 'ff_detailed', 1974),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 27', NULL, NULL, NULL, 'UNKNOWN', '80. Challenge', 'main', 'ff_detailed', 1975),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 28', NULL, NULL, NULL, 'UNKNOWN', '80. Challenge', 'main', 'ff_detailed', 1976),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 29', NULL, NULL, NULL, 'UNKNOWN', '80. Challenge', 'main', 'ff_detailed', 1977),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 30', NULL, NULL, NULL, 'UNKNOWN', '80. Challenge', 'main', 'ff_detailed', 1978),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 31', NULL, NULL, NULL, 'UNKNOWN', '80. Challenge', 'main', 'ff_detailed', 1979),
  -- T81: Beyond The Darkness — 44 rows, all empty source
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 0', NULL, NULL, NULL, NULL, '81. Beyond The Darkness', 'main', 'ff_detailed', 1980),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 1', NULL, NULL, NULL, NULL, '81. Beyond The Darkness', 'main', 'ff_detailed', 1981),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 2', NULL, NULL, NULL, NULL, '81. Beyond The Darkness', 'main', 'ff_detailed', 1982),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 3', NULL, NULL, NULL, NULL, '81. Beyond The Darkness', 'main', 'ff_detailed', 1983),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 4', NULL, NULL, NULL, NULL, '81. Beyond The Darkness', 'main', 'ff_detailed', 1984),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 5', NULL, NULL, NULL, NULL, '81. Beyond The Darkness', 'main', 'ff_detailed', 1985),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 6', NULL, NULL, NULL, NULL, '81. Beyond The Darkness', 'main', 'ff_detailed', 1986),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 7', NULL, NULL, NULL, NULL, '81. Beyond The Darkness', 'main', 'ff_detailed', 1987),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 8', NULL, NULL, NULL, NULL, '81. Beyond The Darkness', 'main', 'ff_detailed', 1988),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 9', NULL, NULL, NULL, NULL, '81. Beyond The Darkness', 'main', 'ff_detailed', 1989),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 10', NULL, NULL, NULL, NULL, '81. Beyond The Darkness', 'main', 'ff_detailed', 1990),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Piano', 'Sample 11', NULL, NULL, NULL, NULL, '81. Beyond The Darkness', 'main', 'ff_detailed', 1991),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Spiccato Strings', 'Sample 12', NULL, NULL, NULL, NULL, '81. Beyond The Darkness', 'main', 'ff_detailed', 1992),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Spiccato Strings', 'Sample 13', NULL, NULL, NULL, NULL, '81. Beyond The Darkness', 'main', 'ff_detailed', 1993),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Spiccato Strings', 'Sample 14', NULL, NULL, NULL, NULL, '81. Beyond The Darkness', 'main', 'ff_detailed', 1994),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Spiccato Strings', 'Sample 15', NULL, NULL, NULL, NULL, '81. Beyond The Darkness', 'main', 'ff_detailed', 1995),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Spiccato Strings', 'Sample 16', NULL, NULL, NULL, NULL, '81. Beyond The Darkness', 'main', 'ff_detailed', 1996),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Spiccato Strings', 'Sample 17', NULL, NULL, NULL, NULL, '81. Beyond The Darkness', 'main', 'ff_detailed', 1997),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Spiccato Strings', 'Sample 18', NULL, NULL, NULL, NULL, '81. Beyond The Darkness', 'main', 'ff_detailed', 1998),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Spiccato Strings', 'Sample 19', NULL, NULL, NULL, NULL, '81. Beyond The Darkness', 'main', 'ff_detailed', 1999),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Spiccato Strings', 'Sample 20', NULL, NULL, NULL, NULL, '81. Beyond The Darkness', 'main', 'ff_detailed', 2000),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Ride Cymbal', 'Sample 21', NULL, NULL, NULL, NULL, '81. Beyond The Darkness', 'main', 'ff_detailed', 2001),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Ride Cymbal', 'Sample 22', NULL, NULL, NULL, NULL, '81. Beyond The Darkness', 'main', 'ff_detailed', 2002),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Snare', 'Sample 23', NULL, NULL, NULL, NULL, '81. Beyond The Darkness', 'main', 'ff_detailed', 2003),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Snare', 'Sample 24', NULL, NULL, NULL, NULL, '81. Beyond The Darkness', 'main', 'ff_detailed', 2004),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Snare', 'Sample 25', NULL, NULL, NULL, NULL, '81. Beyond The Darkness', 'main', 'ff_detailed', 2005),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Snare', 'Sample 26', NULL, NULL, NULL, NULL, '81. Beyond The Darkness', 'main', 'ff_detailed', 2006),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Snare Roll', 'Sample 27', NULL, NULL, NULL, NULL, '81. Beyond The Darkness', 'main', 'ff_detailed', 2007),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Snare Roll', 'Sample 28', NULL, NULL, NULL, NULL, '81. Beyond The Darkness', 'main', 'ff_detailed', 2008),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Spiccato Strings', 'Sample 29', NULL, NULL, NULL, NULL, '81. Beyond The Darkness', 'main', 'ff_detailed', 2009),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Spiccato Strings', 'Sample 30', NULL, NULL, NULL, NULL, '81. Beyond The Darkness', 'main', 'ff_detailed', 2010),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Spiccato Strings', 'Sample 31', NULL, NULL, NULL, NULL, '81. Beyond The Darkness', 'main', 'ff_detailed', 2011),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'French Horn', 'Sample 32', NULL, NULL, NULL, NULL, '81. Beyond The Darkness', 'main', 'ff_detailed', 2012),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'French Horn', 'Sample 33', NULL, NULL, NULL, NULL, '81. Beyond The Darkness', 'main', 'ff_detailed', 2013),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'French Horn', 'Sample 34', NULL, NULL, NULL, NULL, '81. Beyond The Darkness', 'main', 'ff_detailed', 2014),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Synth Pad', 'Sample 35', NULL, NULL, NULL, NULL, '81. Beyond The Darkness', 'main', 'ff_detailed', 2015),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Synth Pad', 'Sample 36', NULL, NULL, NULL, NULL, '81. Beyond The Darkness', 'main', 'ff_detailed', 2016),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Synth Pad', 'Sample 37', NULL, NULL, NULL, NULL, '81. Beyond The Darkness', 'main', 'ff_detailed', 2017),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Synth Pad', 'Sample 38', NULL, NULL, NULL, NULL, '81. Beyond The Darkness', 'main', 'ff_detailed', 2018),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 39', NULL, NULL, NULL, NULL, '81. Beyond The Darkness', 'main', 'ff_detailed', 2019),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 40', NULL, NULL, NULL, NULL, '81. Beyond The Darkness', 'main', 'ff_detailed', 2020),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 41', NULL, NULL, NULL, NULL, '81. Beyond The Darkness', 'main', 'ff_detailed', 2021),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 42', NULL, NULL, NULL, NULL, '81. Beyond The Darkness', 'main', 'ff_detailed', 2022),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 43', NULL, NULL, NULL, NULL, '81. Beyond The Darkness', 'main', 'ff_detailed', 2023),
  -- T82: Gloom (Arranged by Junya Nakano) — 28 rows
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Gamelan', 'Sample 0', NULL, NULL, NULL, NULL, '82. Gloom', 'main', 'ff_detailed', 2024),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Gamelan', 'Sample 1', NULL, NULL, NULL, NULL, '82. Gloom', 'main', 'ff_detailed', 2025),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Gamelan', 'Sample 2', NULL, NULL, NULL, NULL, '82. Gloom', 'main', 'ff_detailed', 2026),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Gamelan', 'Sample 3', NULL, NULL, NULL, NULL, '82. Gloom', 'main', 'ff_detailed', 2027),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Gamelan', 'Sample 4', NULL, NULL, NULL, NULL, '82. Gloom', 'main', 'ff_detailed', 2028),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Gamelan', 'Sample 5', NULL, NULL, NULL, NULL, '82. Gloom', 'main', 'ff_detailed', 2029),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Gamelan', 'Sample 6', NULL, NULL, NULL, NULL, '82. Gloom', 'main', 'ff_detailed', 2030),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Gamelan', 'Sample 7', NULL, NULL, NULL, NULL, '82. Gloom', 'main', 'ff_detailed', 2031),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Gamelan', 'Sample 8', NULL, NULL, NULL, NULL, '82. Gloom', 'main', 'ff_detailed', 2032),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Surdo', 'Sample 9', NULL, NULL, NULL, NULL, '82. Gloom', 'main', 'ff_detailed', 2033),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Surdo', 'Sample 10', NULL, NULL, NULL, NULL, '82. Gloom', 'main', 'ff_detailed', 2034),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Surdo', 'Sample 11', NULL, NULL, NULL, NULL, '82. Gloom', 'main', 'ff_detailed', 2035),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88Pro' COLLATE NOCASE), 'Finger Cymbal', 'Sample 12', 'SC-88Pro Map -> Drum Set', '053 ASIA', NULL, NULL, '82. Gloom', 'main', 'ff_detailed', 2036),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88Pro' COLLATE NOCASE), 'Finger Cymbal', 'Sample 13', 'SC-88Pro Map -> Drum Set', '053 ASIA', NULL, NULL, '82. Gloom', 'main', 'ff_detailed', 2037),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Udu Pot', 'Sample 14', NULL, NULL, NULL, NULL, '82. Gloom', 'main', 'ff_detailed', 2038),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Udu Pot', 'Sample 15', NULL, NULL, NULL, NULL, '82. Gloom', 'main', 'ff_detailed', 2039),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Udu Pot', 'Sample 16', NULL, NULL, NULL, NULL, '82. Gloom', 'main', 'ff_detailed', 2040),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Udu Pot', 'Sample 17', NULL, NULL, NULL, NULL, '82. Gloom', 'main', 'ff_detailed', 2041),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Conga', 'Sample 18', NULL, NULL, NULL, NULL, '82. Gloom', 'main', 'ff_detailed', 2042),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Conga', 'Sample 19', NULL, NULL, NULL, NULL, '82. Gloom', 'main', 'ff_detailed', 2043),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Tambourine', 'Sample 20', NULL, NULL, NULL, NULL, '82. Gloom', 'main', 'ff_detailed', 2044),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Tambourine', 'Sample 21', NULL, NULL, NULL, NULL, '82. Gloom', 'main', 'ff_detailed', 2045),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Synth Bass', 'Sample 22', NULL, NULL, NULL, NULL, '82. Gloom', 'main', 'ff_detailed', 2046),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'Synth Bass', 'Sample 23', NULL, NULL, NULL, NULL, '82. Gloom', 'main', 'ff_detailed', 2047),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 24', NULL, NULL, NULL, NULL, '82. Gloom', 'main', 'ff_detailed', 2048),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 25', NULL, NULL, NULL, NULL, '82. Gloom', 'main', 'ff_detailed', 2049),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 26', NULL, NULL, NULL, NULL, '82. Gloom', 'main', 'ff_detailed', 2050),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X'), NULL, 'String Ensemble', 'Sample 27', NULL, NULL, NULL, NULL, '82. Gloom', 'main', 'ff_detailed', 2051);
