-- FF Detailed: Final Fantasy X-2
--
-- Source: reference/Final Fantasy Sound Sources (Detailed) - Final Fantasy X-2.csv
--
-- Survey of the 244-line CSV:
--   Section 1 - Final Fantasy X-2 (lines 4-205): 60 tracks, but the contributor
--     left most as ",Sample 0,,,,," placeholder stubs. Only 5 tracks have any
--     real data: T2 Real Emotion, T3 YuRiPa Fight! No.1, T7 We're the Gullwings!,
--     T50 1000 Words, T59 1000 Words (Orchestra Version).
--   Section 2 - INTERNATIONAL+LAST MISSION (lines 208-223): only track headers,
--     no rows beneath. Skipped — same handling as the empty FFX OST tracks.
--   Section 3 - Unused Tracks (lines 226-234): bgm090 has 5 oboe rows from
--     Best Service / Advanced Orchestra. Ingested as category='unused'.
--
-- Total: 90 usage rows. Positions 1-90 fresh for this new game.
--
-- New manufacturers: e-LAB, Korg.
-- New products: Roland / SR-JV80-12 Hip Hop Collection, Roland / SR-JV80-02
-- Orchestral, Korg / Triton, e-LAB / XTc Files of Techno, Best Service /
-- ProSamples (CHECK) (parenthetical "CHECK" suffix preserved verbatim per Rule 2 —
-- it signals contributor uncertainty about exact library variant).

INSERT INTO games (title, platform, released, composers, composers_normalized, notes) VALUES
  ('Final Fantasy X-2',
   'PlayStation 2, PlayStation 3, PlayStation 4, PlayStation Vita, Nintendo Switch, Xbox One, PC',
   '2003-03-13',
   'Noriko Matsueda, Takahito Eguchi',
   'noriko matsueda, takahito eguchi',
   'Source: Final Fantasy Sound Sources (Detailed) - Final Fantasy X-2.csv. Research credited to NEWER VGM Sound Sources sheet, Mudstep. Most Section 1 tracks were left as contributor stubs (just a ",Sample 0," placeholder row); only 5 tracks (T2, T3, T7, T50, T59) had identified sources or live-recording credits. Section 2 (International+Last Mission, lines 208-223) had only headers with no rows. Section 3 (Unused, bgm090) contributed 5 oboe rows under category=unused.');

INSERT OR IGNORE INTO manufacturers (name) VALUES
  ('e-LAB'),
  ('Korg');

INSERT OR IGNORE INTO products (manufacturer_id, name, type) VALUES
  ((SELECT id FROM manufacturers WHERE name = 'Roland'       COLLATE NOCASE), 'SR-JV80-12 Hip Hop Collection', 'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Roland'       COLLATE NOCASE), 'SR-JV80-02 Orchestral',         'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Korg'         COLLATE NOCASE), 'Triton',                        'Synth'),
  ((SELECT id FROM manufacturers WHERE name = 'e-LAB'        COLLATE NOCASE), 'XTc Files of Techno',           'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Best Service' COLLATE NOCASE), 'ProSamples (CHECK)',            'Sample Library');

INSERT INTO usages
  (game_id, product_id, sample_label, sample_ref, path_bank, preset, notes, raw_source, examples, category, source_family, position)
VALUES
  -- T2: Real Emotion (lines 9-10) — 2 vocal live recordings.
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, 'Vocals (JP)', '---', NULL, NULL, 'Also sings it in English on her single "Come With Me"', 'Live Recording (Koda Kumi)',   '2. Real Emotion', 'main', 'ff_detailed', 1),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, 'Vocals (EN)', '---', NULL, NULL, NULL,                                                    'Live Recording (Jade Valerie)', '2. Real Emotion', 'main', 'ff_detailed', 2),

  -- T3: YuRiPa, Fight! No. 1 (lines 13-51) — 39 rows. Mix of identified
  -- e-LAB, Zero-G, Roland, Korg samples with many unidentified entries.
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, 'Kick',           'Sample 0',  NULL, NULL, NULL, NULL, '3. YuRiPa, Fight! No. 1', 'main', 'ff_detailed', 3),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, 'Kick',           'Sample 1',  NULL, NULL, NULL, NULL, '3. YuRiPa, Fight! No. 1', 'main', 'ff_detailed', 4),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, 'Snare',          'Sample 2',  NULL, NULL, NULL, NULL, '3. YuRiPa, Fight! No. 1', 'main', 'ff_detailed', 5),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, 'Hi Hat',         'Sample 3',  NULL, NULL, NULL, NULL, '3. YuRiPa, Fight! No. 1', 'main', 'ff_detailed', 6),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, 'Closed Hi Hat',  'Sample 4',  NULL, NULL, NULL, NULL, '3. YuRiPa, Fight! No. 1', 'main', 'ff_detailed', 7),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'e-LAB' COLLATE NOCASE AND p.name = 'XTc Files of Techno' COLLATE NOCASE),
   'Synth Riser',    'Sample 5',  'FB10_construction_kit_138bpm', 'FB1001_demo', NULL, NULL, '3. YuRiPa, Fight! No. 1', 'main', 'ff_detailed', 8),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'e-LAB' COLLATE NOCASE AND p.name = 'XTc Files of Techno' COLLATE NOCASE),
   'Synth Riser',    'Sample 6',  'FB10_construction_kit_138bpm', 'FB1001_demo', NULL, NULL, '3. YuRiPa, Fight! No. 1', 'main', 'ff_detailed', 9),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, 'Synth Bass',     'Sample 7',  NULL, NULL, NULL, NULL, '3. YuRiPa, Fight! No. 1', 'main', 'ff_detailed', 10),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, 'Synth Bass',     'Sample 8',  NULL, NULL, NULL, NULL, '3. YuRiPa, Fight! No. 1', 'main', 'ff_detailed', 11),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, 'Synth Bass',     'Sample 9',  NULL, NULL, NULL, NULL, '3. YuRiPa, Fight! No. 1', 'main', 'ff_detailed', 12),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, 'Guitar Wahs',    'Sample 10', NULL, NULL, NULL, NULL, '3. YuRiPa, Fight! No. 1', 'main', 'ff_detailed', 13),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, 'Guitar Wahs',    'Sample 11', NULL, NULL, NULL, NULL, '3. YuRiPa, Fight! No. 1', 'main', 'ff_detailed', 14),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, 'Guitar Wahs',    'Sample 12', NULL, NULL, NULL, NULL, '3. YuRiPa, Fight! No. 1', 'main', 'ff_detailed', 15),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, 'Synth Lead',     'Sample 13', NULL, NULL, NULL, NULL, '3. YuRiPa, Fight! No. 1', 'main', 'ff_detailed', 16),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, 'Synth Lead',     'Sample 14', NULL, NULL, NULL, NULL, '3. YuRiPa, Fight! No. 1', 'main', 'ff_detailed', 17),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, 'Synth Lead',     'Sample 15', NULL, NULL, NULL, NULL, '3. YuRiPa, Fight! No. 1', 'main', 'ff_detailed', 18),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, 'Synth Lead',     'Sample 16', NULL, NULL, NULL, NULL, '3. YuRiPa, Fight! No. 1', 'main', 'ff_detailed', 19),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, 'Synth Bass',     'Sample 17', NULL, NULL, NULL, NULL, '3. YuRiPa, Fight! No. 1', 'main', 'ff_detailed', 20),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, 'Synth Bass',     'Sample 18', NULL, NULL, NULL, NULL, '3. YuRiPa, Fight! No. 1', 'main', 'ff_detailed', 21),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, 'Synth Bass',     'Sample 19', NULL, NULL, NULL, NULL, '3. YuRiPa, Fight! No. 1', 'main', 'ff_detailed', 22),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, 'Synth Bass Fall','Sample 20', NULL, NULL, NULL, NULL, '3. YuRiPa, Fight! No. 1', 'main', 'ff_detailed', 23),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Phantom Horns' COLLATE NOCASE),
   'Brass Shorts Phrase', 'Sample 21', 'RIFFS -> JB_SOUL_RIFFS', 'JB RF32 132', NULL, NULL, '3. YuRiPa, Fight! No. 1', 'main', 'ff_detailed', 24),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Phantom Horns' COLLATE NOCASE),
   'Brass Shorts Phrase', 'Sample 22', 'RIFFS -> JB_SOUL_RIFFS', 'JB RF32 132', NULL, NULL, '3. YuRiPa, Fight! No. 1', 'main', 'ff_detailed', 25),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Phantom Horns' COLLATE NOCASE),
   'Brass Phrase',        'Sample 23', 'JBR3-110BPM',           'J24D110B',     NULL, NULL, '3. YuRiPa, Fight! No. 1', 'main', 'ff_detailed', 26),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Phantom Horns' COLLATE NOCASE),
   'Brass Phrase',        'Sample 24', 'JBR3-110BPM',           'J24D110B',     NULL, NULL, '3. YuRiPa, Fight! No. 1', 'main', 'ff_detailed', 27),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, 'Reverse Cymbal',     'Sample 25', NULL, NULL, NULL, NULL, '3. YuRiPa, Fight! No. 1', 'main', 'ff_detailed', 28),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, 'Synth Riser',        'Sample 26', NULL, NULL, NULL, NULL, '3. YuRiPa, Fight! No. 1', 'main', 'ff_detailed', 29),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, 'Synth Bass Phrase',  'Sample 27', NULL, NULL, NULL, NULL, '3. YuRiPa, Fight! No. 1', 'main', 'ff_detailed', 30),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'e-LAB' COLLATE NOCASE AND p.name = 'XTc Files of Techno' COLLATE NOCASE),
   'Metallic Pad',        'Sample 28', 'FB02_construction_kit_135bpm', 'F0203_swoosh', NULL, NULL, '3. YuRiPa, Fight! No. 1', 'main', 'ff_detailed', 31),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, 'Percussion Hit',     'Sample 29', NULL, NULL, NULL, NULL, '3. YuRiPa, Fight! No. 1', 'main', 'ff_detailed', 32),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-12 Hip Hop Collection' COLLATE NOCASE),
   'Orchestral Hit',      'Sample 30', 'XP-X', '176 Lo-Fi Hits', NULL, NULL, '3. YuRiPa, Fight! No. 1', 'main', 'ff_detailed', 33),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Korg' COLLATE NOCASE AND p.name = 'Triton' COLLATE NOCASE),
   'Cymbal Crash',        'Sample 31', 'CHECK', 'CHECK', NULL, NULL, '3. YuRiPa, Fight! No. 1', 'main', 'ff_detailed', 34),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, 'Synth Bass',         'Sample 32', NULL, NULL, NULL, NULL, '3. YuRiPa, Fight! No. 1', 'main', 'ff_detailed', 35),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, 'Synth FX',           'Sample 33', NULL, NULL, NULL, NULL, '3. YuRiPa, Fight! No. 1', 'main', 'ff_detailed', 36),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, 'Wah Guitar',         'Sample 34', NULL, NULL, NULL, NULL, '3. YuRiPa, Fight! No. 1', 'main', 'ff_detailed', 37),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, 'Wah Guitar',         'Sample 35', NULL, NULL, NULL, NULL, '3. YuRiPa, Fight! No. 1', 'main', 'ff_detailed', 38),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, 'Synth Phrase',       'Sample 36', NULL, NULL, NULL, NULL, '3. YuRiPa, Fight! No. 1', 'main', 'ff_detailed', 39),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, 'Synth Phrase',       'Sample 37', NULL, NULL, NULL, NULL, '3. YuRiPa, Fight! No. 1', 'main', 'ff_detailed', 40),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, 'Synth Pad',          'Sample 38', NULL, NULL, NULL, NULL, '3. YuRiPa, Fight! No. 1', 'main', 'ff_detailed', 41),

  -- T7: We're the Gullwings! (lines 59-97) — 39 rows. Best Service ProSamples
  -- (CHECK) parens preserved verbatim. Notes on Jazz Guitar samples flag
  -- similarity to "Electric GTR. (Jazz)" in EastWest Goliath.
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, 'Kick',                  'Sample 0',  NULL, NULL, NULL, NULL, '7. We''re the Gullwings!', 'main', 'ff_detailed', 42),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, 'Fretless Bass',         'Sample 1',  NULL, NULL, NULL, NULL, '7. We''re the Gullwings!', 'main', 'ff_detailed', 43),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, 'Fretless Bass',         'Sample 2',  NULL, NULL, NULL, NULL, '7. We''re the Gullwings!', 'main', 'ff_detailed', 44),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, 'Fretless Bass',         'Sample 3',  NULL, NULL, NULL, NULL, '7. We''re the Gullwings!', 'main', 'ff_detailed', 45),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, 'Fretless Bass',         'Sample 4',  NULL, NULL, NULL, NULL, '7. We''re the Gullwings!', 'main', 'ff_detailed', 46),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, 'Hit(?)',                'Sample 5',  NULL, NULL, NULL, NULL, '7. We''re the Gullwings!', 'main', 'ff_detailed', 47),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, 'Clavinet',              'Sample 6',  NULL, NULL, NULL, NULL, '7. We''re the Gullwings!', 'main', 'ff_detailed', 48),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, 'Clavinet',              'Sample 7',  NULL, NULL, NULL, NULL, '7. We''re the Gullwings!', 'main', 'ff_detailed', 49),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, 'Clavinet',              'Sample 8',  NULL, NULL, NULL, NULL, '7. We''re the Gullwings!', 'main', 'ff_detailed', 50),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'ProSamples (CHECK)' COLLATE NOCASE),
   'Jazz Guitar',           'Sample 9',  NULL, NULL, 'Sounds similar to what is known as "Electric GTR. (Jazz)" in EastWest Goliath. Their pitch bends match too.', NULL, '7. We''re the Gullwings!', 'main', 'ff_detailed', 51),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'ProSamples (CHECK)' COLLATE NOCASE),
   'Jazz Guitar',           'Sample 10', NULL, NULL, 'Sounds similar to what is known as "Electric GTR. (Jazz)" in EastWest Goliath. Their pitch bends match too.', NULL, '7. We''re the Gullwings!', 'main', 'ff_detailed', 52),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'ProSamples (CHECK)' COLLATE NOCASE),
   'Jazz Guitar',           'Sample 11', NULL, NULL, 'Sounds similar to what is known as "Electric GTR. (Jazz)" in EastWest Goliath. Their pitch bends match too.', NULL, '7. We''re the Gullwings!', 'main', 'ff_detailed', 53),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'ProSamples (CHECK)' COLLATE NOCASE),
   'Jazz Guitar',           'Sample 12', NULL, NULL, 'Sounds similar to what is known as "Electric GTR. (Jazz)" in EastWest Goliath. Their pitch bends match too.', NULL, '7. We''re the Gullwings!', 'main', 'ff_detailed', 54),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, 'Cymbal Crash',          'Sample 13', NULL, NULL, NULL, NULL, '7. We''re the Gullwings!', 'main', 'ff_detailed', 55),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, 'Reverse Cymbal',        'Sample 14', NULL, NULL, NULL, NULL, '7. We''re the Gullwings!', 'main', 'ff_detailed', 56),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, 'Djembe Loop',           'Sample 15', NULL, NULL, NULL, NULL, '7. We''re the Gullwings!', 'main', 'ff_detailed', 57),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, 'Drum Loop',             'Sample 16', NULL, NULL, NULL, NULL, '7. We''re the Gullwings!', 'main', 'ff_detailed', 58),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, 'Drum Loop',             'Sample 17', NULL, NULL, NULL, NULL, '7. We''re the Gullwings!', 'main', 'ff_detailed', 59),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Phantom Horns' COLLATE NOCASE),
   'Brass Phrase',          'Sample 18', 'CHECK', 'CHECK', NULL, NULL, '7. We''re the Gullwings!', 'main', 'ff_detailed', 60),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Phantom Horns' COLLATE NOCASE),
   'Brass Phrase',          'Sample 19', 'CHECK', 'CHECK', NULL, NULL, '7. We''re the Gullwings!', 'main', 'ff_detailed', 61),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Phantom Horns' COLLATE NOCASE),
   'Brass Gliss. Phrase',   'Sample 20', 'RIFFS -> JB_SOUL_RIFFS', 'JB RF18 120', NULL, NULL, '7. We''re the Gullwings!', 'main', 'ff_detailed', 62),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-02 Orchestral' COLLATE NOCASE),
   'Vibraphone',            'Sample 21', 'XP-X', '207 Vibes', NULL, NULL, '7. We''re the Gullwings!', 'main', 'ff_detailed', 63),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-02 Orchestral' COLLATE NOCASE),
   'Vibraphone',            'Sample 22', 'XP-X', '207 Vibes', NULL, NULL, '7. We''re the Gullwings!', 'main', 'ff_detailed', 64),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-02 Orchestral' COLLATE NOCASE),
   'Vibraphone',            'Sample 23', 'XP-X', '207 Vibes', NULL, NULL, '7. We''re the Gullwings!', 'main', 'ff_detailed', 65),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-02 Orchestral' COLLATE NOCASE),
   'Vibraphone',            'Sample 24', 'XP-X', '207 Vibes', NULL, NULL, '7. We''re the Gullwings!', 'main', 'ff_detailed', 66),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, 'Synth Riser',                 'Sample 25', NULL, NULL, NULL, NULL, '7. We''re the Gullwings!', 'main', 'ff_detailed', 67),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, 'Flute',                       'Sample 26', NULL, NULL, NULL, NULL, '7. We''re the Gullwings!', 'main', 'ff_detailed', 68),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, 'Flute',                       'Sample 27', NULL, NULL, NULL, NULL, '7. We''re the Gullwings!', 'main', 'ff_detailed', 69),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, 'Flute',                       'Sample 28', NULL, NULL, NULL, NULL, '7. We''re the Gullwings!', 'main', 'ff_detailed', 70),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, 'Flute',                       'Sample 29', NULL, NULL, NULL, NULL, '7. We''re the Gullwings!', 'main', 'ff_detailed', 71),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, 'Flute',                       'Sample 30', NULL, NULL, NULL, NULL, '7. We''re the Gullwings!', 'main', 'ff_detailed', 72),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, 'Industrial Percussion Loop',  'Sample 31', NULL, NULL, NULL, NULL, '7. We''re the Gullwings!', 'main', 'ff_detailed', 73),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, 'Electric Guitar "Wah"',       'Sample 32', NULL, NULL, NULL, NULL, '7. We''re the Gullwings!', 'main', 'ff_detailed', 74),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Total House' COLLATE NOCASE),
   'Guitar Phrase',         'Sample 33', 'Samples -> Groove Loops -> Guitar Loops 135-BPM', 'Double Chic-C', NULL, NULL, '7. We''re the Gullwings!', 'main', 'ff_detailed', 75),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Total House' COLLATE NOCASE),
   'Guitar Phrase',         'Sample 34', 'Samples -> Groove Loops -> Guitar Loops 135-BPM', 'Double Chic-C', NULL, NULL, '7. We''re the Gullwings!', 'main', 'ff_detailed', 76),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, '"Wah" Guitar Phrase',         'Sample 35', NULL, NULL, NULL, NULL, '7. We''re the Gullwings!', 'main', 'ff_detailed', 77),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, 'Guitar Clicks(?)',            'Sample 36', NULL, NULL, NULL, NULL, '7. We''re the Gullwings!', 'main', 'ff_detailed', 78),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, '"Wah" Guitar Phrase',         'Sample 37', NULL, NULL, NULL, NULL, '7. We''re the Gullwings!', 'main', 'ff_detailed', 79),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, 'Noise(?)',                    'Sample 38', NULL, NULL, NULL, NULL, '7. We''re the Gullwings!', 'main', 'ff_detailed', 80),

  -- T50: 1000 Words (lines 183-185) — 3 rows. Vocals JP + EN live recordings,
  -- plus a Wind Chime from Roland SR-JV80-02 Orchestral.
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, 'Vocals (JP)', '---', NULL, NULL, 'Also sings it in English on her single "Come With Me"', 'Live Recording (Koda Kumi)',   '50. 1000 Words', 'main', 'ff_detailed', 81),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, 'Vocals (EN)', '---', NULL, NULL, NULL,                                                    'Live Recording (Jade Valerie)', '50. 1000 Words', 'main', 'ff_detailed', 82),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-02 Orchestral' COLLATE NOCASE),
   'Wind Chime', '---', 'XP-X', '245 Wind Chimes1', NULL, NULL, '50. 1000 Words', 'main', 'ff_detailed', 83),

  -- T59: 1000 Words (Orchestra Version) (lines 203-204) — 2 vocal live recordings.
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, 'Vocals (JP)', '---', NULL, NULL, NULL, 'Live Recording (Koda Kumi)',   '59. 1000 Words (Orchestra Version)', 'main', 'ff_detailed', 84),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   NULL, 'Vocals (EN)', '---', NULL, NULL, NULL, 'Live Recording (Jade Valerie)', '59. 1000 Words (Orchestra Version)', 'main', 'ff_detailed', 85),

  -- Section 3 Unused: bgm090 (lines 229-233) — 5 oboe samples from Best Service
  -- Advanced Orchestra. Track name preserved verbatim including the parenthetical.
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Advanced Orchestra' COLLATE NOCASE),
   'Oboe', 'Sample 0', 'CD 3 -> Partition D -> 01 OBS LG F', 'OBS LONG F', NULL, NULL, 'bgm090 (Incomplete, presumably placeholder melody)', 'unused', 'ff_detailed', 86),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Advanced Orchestra' COLLATE NOCASE),
   'Oboe', 'Sample 1', 'CD 3 -> Partition D -> 01 OBS LG F', 'OBS LONG F', NULL, NULL, 'bgm090 (Incomplete, presumably placeholder melody)', 'unused', 'ff_detailed', 87),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Advanced Orchestra' COLLATE NOCASE),
   'Oboe', 'Sample 2', 'CD 3 -> Partition D -> 01 OBS LG F', 'OBS LONG F', NULL, NULL, 'bgm090 (Incomplete, presumably placeholder melody)', 'unused', 'ff_detailed', 88),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Advanced Orchestra' COLLATE NOCASE),
   'Oboe', 'Sample 3', 'CD 3 -> Partition D -> 01 OBS LG F', 'OBS LONG F', NULL, NULL, 'bgm090 (Incomplete, presumably placeholder melody)', 'unused', 'ff_detailed', 89),
  ((SELECT id FROM games WHERE title = 'Final Fantasy X-2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Advanced Orchestra' COLLATE NOCASE),
   'Oboe', 'Sample 4', 'CD 3 -> Partition D -> 01 OBS LG F', 'OBS LONG F', NULL, NULL, 'bgm090 (Incomplete, presumably placeholder melody)', 'unused', 'ff_detailed', 90);
