-- NEWER VGM SEGA/Atlus — Section 1 (Megami Tensei)
--
-- Source: reference/NEWER VGM Sound Sources - SEGAAtlus.csv lines 26-316.
-- 21 game/album records, ~256 usage rows.
--
-- Conventions:
--   - Per-game positions start at 1, monotonic across both 'main' and
--     'stuff_to_find' categories so the UI render order matches CSV order.
--   - "?,?" CSV rows (contributor flagged unknown source) → product_id NULL,
--     raw_source NULL. Description preserved in notes; examples populated.
--   - "Manufacturer,?" CSV rows (manufacturer known, product unknown) →
--     product_id NULL, raw_source = 'Manufacturer - ?'.
--   - "Sample: Shoji Meguro, Shin Megami Tensei III" cross-game reference (T214)
--     → product_id NULL, raw_source = 'Sample: Shoji Meguro - Shin Megami Tensei III'.
--   - Three Atlus arrange/companion albums (Soul Hackers Arrange, SMT IV Sound &
--     Art, 25th Memorial Arrange) are ingested as game records per CSV treatment.
--   - Composers field left NULL unless the CSV row supplies a "(Music by:" note
--     (none in Section 1) — explicit composer research would overstep Rule 2.
--   - Platform inferred from "(SFC)"/"(Sony Playstation 1)" suffix when present,
--     otherwise from well-known release platform for that title.

INSERT OR IGNORE INTO manufacturers (name) VALUES
  ('AKAI'),
  ('AMG'),
  ('Apple'),
  ('AudioNerdz'),
  ('Audiobro'),
  ('Big Fish Audio'),
  ('E-MU Systems'),
  ('Heavyocity'),
  ('Modartt'),
  ('Sound Ideas'),
  ('Spectrasonics'),
  ('Steinberg'),
  ('UltimateSoundBank'),
  ('Vir2'),
  ('XLN Audio');

INSERT OR IGNORE INTO products (manufacturer_id, name, type) VALUES
  ((SELECT id FROM manufacturers WHERE name = 'KORG'               COLLATE NOCASE), 'M1',                                          'Synth'),
  ((SELECT id FROM manufacturers WHERE name = 'KORG'               COLLATE NOCASE), 'M1 Legacy Collection',                        'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'KORG'               COLLATE NOCASE), 'TRINITY pro',                                 'Synth'),
  ((SELECT id FROM manufacturers WHERE name = 'KORG'               COLLATE NOCASE), 'TRITON-Rack',                                 'Synth'),
  ((SELECT id FROM manufacturers WHERE name = 'Roland'             COLLATE NOCASE), 'SN-U110-07 Electric Guitar',                  'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Roland'             COLLATE NOCASE), 'SOUND Canvas SC-55',                          'Synth'),
  ((SELECT id FROM manufacturers WHERE name = 'Roland'             COLLATE NOCASE), 'SOUND Canvas SC-88',                          'Synth'),
  ((SELECT id FROM manufacturers WHERE name = 'Roland'             COLLATE NOCASE), 'SOUND Canvas SC-88 Pro',                      'Synth'),
  ((SELECT id FROM manufacturers WHERE name = 'Roland'             COLLATE NOCASE), 'JD-990',                                      'Synth'),
  ((SELECT id FROM manufacturers WHERE name = 'Roland'             COLLATE NOCASE), 'R-70',                                        'Hardware'),
  ((SELECT id FROM manufacturers WHERE name = 'Best Service'       COLLATE NOCASE), 'Classical Choir',                             'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'E-MU Systems'       COLLATE NOCASE), 'Ultra Proteus',                               'Synth'),
  ((SELECT id FROM manufacturers WHERE name = 'Apple'              COLLATE NOCASE), 'Text to Speech',                              'Effect'),
  ((SELECT id FROM manufacturers WHERE name = 'Apple'              COLLATE NOCASE), 'Logic Pro',                                   'DAW'),
  ((SELECT id FROM manufacturers WHERE name = 'Apple'              COLLATE NOCASE), 'EXS24',                                       'Instrument'),
  ((SELECT id FROM manufacturers WHERE name = 'Apple'              COLLATE NOCASE), 'Loops',                                       'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Apple'              COLLATE NOCASE), 'ES2',                                         'Synth'),
  ((SELECT id FROM manufacturers WHERE name = 'AKAI'               COLLATE NOCASE), 'S3000',                                       'Hardware'),
  ((SELECT id FROM manufacturers WHERE name = 'AKAI'               COLLATE NOCASE), 'S3000 (Volume 3)',                            'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Zero-G'             COLLATE NOCASE), 'Nostalgia',                                   'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Zero-G'             COLLATE NOCASE), 'Hardcore',                                    'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Zero-G'             COLLATE NOCASE), 'Chemical Beats',                              'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Zero-G'             COLLATE NOCASE), 'Total Funk',                                  'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'AudioNerdz'         COLLATE NOCASE), 'Delay Lama',                                  'Instrument'),
  ((SELECT id FROM manufacturers WHERE name = 'UltimateSoundBank'  COLLATE NOCASE), 'PlugSound Vol. 2 Fretted Instruments',        'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Heavyocity'         COLLATE NOCASE), 'Damage',                                      'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Native Instruments' COLLATE NOCASE), 'Absynth',                                     'Synth'),
  ((SELECT id FROM manufacturers WHERE name = 'Native Instruments' COLLATE NOCASE), 'FM7',                                         'Synth'),
  ((SELECT id FROM manufacturers WHERE name = 'Native Instruments' COLLATE NOCASE), 'FM8',                                         'Synth'),
  ((SELECT id FROM manufacturers WHERE name = 'Native Instruments' COLLATE NOCASE), 'Massive',                                     'Synth'),
  ((SELECT id FROM manufacturers WHERE name = 'Native Instruments' COLLATE NOCASE), 'New York Concert Grand',                      'Instrument'),
  ((SELECT id FROM manufacturers WHERE name = 'Native Instruments' COLLATE NOCASE), 'Spotlight Collection: India',                 'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Spectrasonics'      COLLATE NOCASE), 'Stylus RMX',                                  'Instrument'),
  ((SELECT id FROM manufacturers WHERE name = 'Spectrasonics'      COLLATE NOCASE), 'Trilian',                                     'Instrument'),
  ((SELECT id FROM manufacturers WHERE name = 'Spectrasonics'      COLLATE NOCASE), 'Atmosphere',                                  'Instrument'),
  ((SELECT id FROM manufacturers WHERE name = 'Spectrasonics'      COLLATE NOCASE), 'Omnisphere',                                  'Instrument'),
  ((SELECT id FROM manufacturers WHERE name = 'Spectrasonics'      COLLATE NOCASE), 'Liquid Grooves S.A.G.E. Xpander',             'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Spectrasonics'      COLLATE NOCASE), 'Metamorphosis S.A.G.E. Xpander',              'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Modartt'            COLLATE NOCASE), 'PianoTeq 6',                                  'Instrument'),
  ((SELECT id FROM manufacturers WHERE name = 'AMG'                COLLATE NOCASE), 'Kick-Ass Brass!',                             'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Big Fish Audio'     COLLATE NOCASE), 'Electric Ghetto',                             'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Big Fish Audio'     COLLATE NOCASE), 'Megaton Trance Bomb',                         'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Vir2'               COLLATE NOCASE), 'Electri6ity',                                 'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Steinberg'          COLLATE NOCASE), 'HALion Sonic SE',                             'Instrument'),
  ((SELECT id FROM manufacturers WHERE name = 'Steinberg'          COLLATE NOCASE), 'Halion Sonic',                                'Instrument'),
  ((SELECT id FROM manufacturers WHERE name = 'XLN Audio'          COLLATE NOCASE), 'Addictive Drums',                             'Instrument'),
  ((SELECT id FROM manufacturers WHERE name = 'Audiobro'           COLLATE NOCASE), 'LA Scoring Strings',                          'Sample Library');

INSERT INTO games (title, platform, released, composers, composers_normalized, notes) VALUES
  ('Shin Megami Tensei (SFC)',                                       'Super Famicom',                   '1992-10-30', NULL, NULL, 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 1 Megami Tensei). Original Super Famicom release; separate PS1 port listed independently in the CSV.'),
  ('Shin Megami Tensei If... (SFC)',                                 'Super Famicom',                   '1994-10-28', NULL, NULL, 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 1 Megami Tensei). Super Famicom side-story to SMT II.'),
  ('Megami Tensei Gaiden: Last Bible III',                           'Super Famicom',                   '1995-03-04', NULL, NULL, 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 1 Megami Tensei). Third entry in the Last Bible gaiden series; ~25 contributor-flagged stuff_to_find rows below the identified main usages.'),
  ('Devil Summoner: Soul Hackers',                                   'Sega Saturn',                     '1997-11-13', NULL, NULL, 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 1 Megami Tensei). Saturn original; later rereleased on Nintendo 3DS (2012).'),
  ('Shin Megami Tensei (Sony Playstation 1)',                        'PlayStation',                     '2001-05-31', NULL, NULL, 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 1 Megami Tensei). PS1 port of the 1992 Super Famicom original. Game title preserved verbatim from CSV.'),
  ('Shin Megami Tensei II (Sony Playstation 1)',                     'PlayStation',                     '2002-03-20', NULL, NULL, 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 1 Megami Tensei). PS1 port of the 1994 SFC original.'),
  ('Shin Megami Tensei III: Nocturne',                               'PlayStation 2',                   '2003-02-20', NULL, NULL, 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 1 Megami Tensei). Base PS2 release ("Main Game" sub-section in the CSV); see also separate Nocturne Maniax rerelease entry.'),
  ('Nocturne Maniax',                                                'PlayStation 2',                   '2004-01-29', NULL, NULL, 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 1 Megami Tensei). Expanded JP rerelease of SMT III: Nocturne with the Dante crossover scenario; title preserved verbatim (Western releases use the "Maniax" label too).'),
  ('Shin Megami Tensei: Digital Devil Saga 2',                       'PlayStation 2',                   '2005-01-27', NULL, NULL, 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 1 Megami Tensei). Only 1 source row in the CSV for this title.'),
  ('Shin Megami Tensei IMAGINE',                                     'PC',                              '2007-04-04', NULL, NULL, 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 1 Megami Tensei). Windows MMO; service discontinued 2016.'),
  ('Devil Summoner 2: Raidou Kuzunoha vs. King Abaddon',             'PlayStation 2',                   '2008-10-23', NULL, NULL, 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 1 Megami Tensei).'),
  ('Devil Survivor',                                                 'Nintendo DS',                     '2009-01-15', NULL, NULL, 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 1 Megami Tensei). DS original.'),
  ('Devil Survivor 2',                                               'Nintendo DS',                     '2011-07-28', NULL, NULL, 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 1 Megami Tensei). DS original.'),
  ('Devil Summoner: Soul Hackers Arrange (Soundtrack Album)',        NULL,                              '2012-08-30', NULL, NULL, 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 1 Megami Tensei). Companion soundtrack album, not a game; ingested as a game record per CSV treatment.'),
  ('Shin Megami Tensei IV',                                          'Nintendo 3DS',                    '2013-05-23', NULL, NULL, 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 1 Megami Tensei). Notable: T214 cross-game sample reference ("Sample: Shoji Meguro - Shin Megami Tensei III - Normal Battle") preserved in raw_source.'),
  ('Shin Megami Tensei IV: Sound & Art Collection',                  NULL,                              '2013-05-23', NULL, NULL, 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 1 Megami Tensei). Companion music + art collection released alongside SMT IV; not a game.'),
  ('Shin Megami Tensei IV: Apocalypse',                              'Nintendo 3DS',                    '2016-02-10', NULL, NULL, 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 1 Megami Tensei). Standalone followup to SMT IV.'),
  ('Shin Megami Tensei 25th Anniversary Memorial Arrange',           NULL,                              '2017-10-26', NULL, NULL, 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 1 Megami Tensei). Arrangement album celebrating the franchise''s 25th anniversary; not a game.'),
  ('Dx2 Shin Megami Tensei: Liberation',                             'iOS, Android',                    '2018-01-22', NULL, NULL, 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 1 Megami Tensei). Free-to-play mobile spinoff.'),
  ('Shin Megami Tensei V',                                           'Nintendo Switch',                 '2021-11-11', NULL, NULL, 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 1 Megami Tensei). Switch exclusive at launch; later superseded by Vengeance rerelease.'),
  ('Shin Megami Tensei V Vengeance',                                 'Nintendo Switch, PlayStation 4, PlayStation 5, Xbox One, Xbox Series X|S, PC', '2024-06-14', NULL, NULL, 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 1 Megami Tensei). Expanded multi-platform rerelease of SMT V with the new Canon of Vengeance story branch.');

INSERT INTO usages
  (game_id, product_id, path_bank, preset, notes, raw_source, examples, category, source_family, position)
VALUES
  -- G1: Shin Megami Tensei (SFC) — 11 main + 6 stuff_to_find = 17 rows
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei (SFC)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'M1' COLLATE NOCASE),
   'PROG', '01 Piano 16''', NULL, NULL, 'Title', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei (SFC)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'M1' COLLATE NOCASE),
   'PROG', '08 PanFlute', NULL, NULL, 'Mansion of the Four Heavenly Kings, Ruins, Epilogue, Ending, Pascal', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei (SFC)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'M1' COLLATE NOCASE),
   'PROG', '09 Drums #1', NULL, NULL, '-Used throughout the soundtrack-', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei (SFC)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'M1' COLLATE NOCASE),
   'PROG', '15 Vibes', NULL, NULL, 'Dream, Neutral, Terminal, Ending', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei (SFC)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'M1' COLLATE NOCASE),
   'PROG', '22 SoloSax', NULL, NULL, 'Shop', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei (SFC)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'M1' COLLATE NOCASE),
   'PROG', '23 Choir', NULL, NULL, '-Used throughout the soundtrack-', 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei (SFC)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'M1' COLLATE NOCASE),
   'PROG', '33 Bottles', NULL, NULL, 'Home, Kichijoji, Shopping Arcade, Game Over, Epilogue', 'main', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei (SFC)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'M1' COLLATE NOCASE),
   'PROG', '47 PipeOrgan', NULL, NULL, 'Mansion of Heresy, Fusion', 'main', 'newer_vgm', 8),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei (SFC)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'M1' COLLATE NOCASE),
   'PROG', '53 VoiceWave', NULL, NULL, 'Shop', 'main', 'newer_vgm', 9),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei (SFC)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SN-U110-07 Electric Guitar' COLLATE NOCASE),
   NULL, '07-050 DSG F', NULL, NULL, 'Dream, Battle, Level Up, Ruins, Ending', 'main', 'newer_vgm', 10),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei (SFC)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SN-U110-07 Electric Guitar' COLLATE NOCASE),
   NULL, '07-055 DSG -5TH 2', NULL, NULL, 'Embassy, Terminal, Battle, Boss Battle, Cathedral', 'main', 'newer_vgm', 11),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei (SFC)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'M1' COLLATE NOCASE),
   'PROG', '76 AnalogBass', NULL, NULL, '-Used throughout the soundtrack-', 'stuff_to_find', 'newer_vgm', 12),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei (SFC)'),
   NULL, NULL, NULL, 'Piano? Maybe guitar?', NULL, 'Home, Pascal, Embassy, Ruins', 'stuff_to_find', 'newer_vgm', 13),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei (SFC)'),
   NULL, NULL, NULL, 'Saw wave-like sample', NULL, 'Enemy Appearance, Boss, Cathedral', 'stuff_to_find', 'newer_vgm', 14),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei (SFC)'),
   NULL, NULL, NULL, 'Piano-like bass', NULL, 'Kichijoji', 'stuff_to_find', 'newer_vgm', 15),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei (SFC)'),
   NULL, NULL, NULL, 'Instrument used as muted guitar and then lead', NULL, 'Ginza', 'stuff_to_find', 'newer_vgm', 16),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei (SFC)'),
   NULL, NULL, NULL, 'Lead sound', NULL, 'Ginza', 'stuff_to_find', 'newer_vgm', 17),

  -- G2: Shin Megami Tensei If... (SFC) — 14 main rows
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei If... (SFC)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'M1' COLLATE NOCASE),
   'PROG', '08 PanFlute', NULL, NULL, 'President''s Office, Makai Town', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei If... (SFC)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'M1' COLLATE NOCASE),
   'PROG', '15 Vibes', NULL, NULL, 'Title, Epilogue', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei If... (SFC)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'M1' COLLATE NOCASE),
   'PROG', '22 SoloSax', NULL, NULL, 'Classroom', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei If... (SFC)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'M1' COLLATE NOCASE),
   'PROG', '23 Choir', NULL, NULL, '-Used throughout the soundtrack-', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei If... (SFC)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'M1' COLLATE NOCASE),
   'PROG', '33 Bottles', NULL, NULL, 'Ending', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei If... (SFC)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'M1' COLLATE NOCASE),
   'PROG', '47 PipeOrgan', NULL, NULL, 'Fusion, Battle', 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei If... (SFC)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'M1' COLLATE NOCASE),
   'PROG', '53 VoiceWave', NULL, NULL, 'Classroom', 'main', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei If... (SFC)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SN-U110-07 Electric Guitar' COLLATE NOCASE),
   NULL, '07-055 DSG -5TH 2', NULL, NULL, '-Used throughout the soundtrack-', 'main', 'newer_vgm', 8),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei If... (SFC)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-55' COLLATE NOCASE),
   'Capital', '031 DistortionGt.', NULL, NULL, 'Staff Roll', 'main', 'newer_vgm', 9),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei If... (SFC)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-55' COLLATE NOCASE),
   'Capital', '034 Fingered Bs.', NULL, NULL, 'Important Meeting, Battle, Houshoku Kai, Disco, Shitto Kai', 'main', 'newer_vgm', 10),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei If... (SFC)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-55' COLLATE NOCASE),
   'Capital', '049 Strings', NULL, NULL, 'Danger, Devil Appears, Dimensional Portal, Disco, Shitto Kai, Heroine', 'main', 'newer_vgm', 11),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei If... (SFC)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-55' COLLATE NOCASE),
   'Capital', '055 SynVox', NULL, NULL, 'Title, Data Load Screen, Important Meeting, Between the Seals, etc.', 'main', 'newer_vgm', 12),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei If... (SFC)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-55' COLLATE NOCASE),
   'Capital', '057 Trumpet', NULL, NULL, 'Epilogue', 'main', 'newer_vgm', 13),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei If... (SFC)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-55' COLLATE NOCASE),
   'Drum Set', '001 STANDARD', NULL, NULL, '-Used throughout the soundtrack-', 'main', 'newer_vgm', 14),

  -- G3: Megami Tensei Gaiden: Last Bible III — 7 main + 33 stuff_to_find = 40 rows
  ((SELECT id FROM games WHERE title = 'Megami Tensei Gaiden: Last Bible III'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Classical Choir' COLLATE NOCASE),
   'Track 63 - effects -> TS 0:24', 'whistle', 'unis. (C)', NULL, 'Brantika, Sodom', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Megami Tensei Gaiden: Last Bible III'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'E-MU Systems' COLLATE NOCASE AND p.name = 'Ultra Proteus' COLLATE NOCASE),
   'Instruments', '139 VbHarmonica', NULL, NULL, 'Memories, Field I, Val Ship, Devil City Usher', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Megami Tensei Gaiden: Last Bible III'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'E-MU Systems' COLLATE NOCASE AND p.name = 'Ultra Proteus' COLLATE NOCASE),
   'Bank 0', '100 Banjo', NULL, NULL, 'Name Entry, Quarrel', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Megami Tensei Gaiden: Last Bible III'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'E-MU Systems' COLLATE NOCASE AND p.name = 'Ultra Proteus' COLLATE NOCASE),
   'Bank 1', '091 English Horn', 'Multiple notes sampled', NULL, 'Bullton Tower, Red Owl, Megalopolis, North Lake, Underworld Town', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Megami Tensei Gaiden: Last Bible III'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'E-MU Systems' COLLATE NOCASE AND p.name = 'Ultra Proteus' COLLATE NOCASE),
   'Bank 1', '113 Accordion', 'Attack was cut off', NULL, 'Hometown, Hill', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'Megami Tensei Gaiden: Last Bible III'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'E-MU Systems' COLLATE NOCASE AND p.name = 'Ultra Proteus' COLLATE NOCASE),
   'Bank 1', '125 Bagpipe', NULL, NULL, 'Boss Battle 1, Dragon''s Fang, Sky Wing, Field Theme 2, Battle 3', 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'Megami Tensei Gaiden: Last Bible III'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'M1' COLLATE NOCASE),
   'PROG', '23 Choir', NULL, NULL, 'Opening Title, Memories, Light, Before Battle, Dragon Fang, Sadness, Mochowa, Song of Mina, Battle IV, Battle V, Ending A, Ending B', 'main', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'Megami Tensei Gaiden: Last Bible III'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'E-MU Systems' COLLATE NOCASE AND p.name = 'Ultra Proteus' COLLATE NOCASE),
   NULL, 'Piano', 'To do: find exact patch - Multiple notes sampled', NULL, 'Harry''s Theme, Danger, Sadness, Field Theme 2', 'stuff_to_find', 'newer_vgm', 8),
  ((SELECT id FROM games WHERE title = 'Megami Tensei Gaiden: Last Bible III'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'E-MU Systems' COLLATE NOCASE AND p.name = 'Ultra Proteus' COLLATE NOCASE),
   NULL, 'Vibraphone', 'To do: find exact patch', NULL, 'Dance, Shark Ship', 'stuff_to_find', 'newer_vgm', 9),
  ((SELECT id FROM games WHERE title = 'Megami Tensei Gaiden: Last Bible III'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'E-MU Systems' COLLATE NOCASE AND p.name = 'Ultra Proteus' COLLATE NOCASE),
   NULL, 'Percussive Organ', 'To do: find exact patch', NULL, 'Dinner, Megalopolis', 'stuff_to_find', 'newer_vgm', 10),
  ((SELECT id FROM games WHERE title = 'Megami Tensei Gaiden: Last Bible III'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'E-MU Systems' COLLATE NOCASE AND p.name = 'Ultra Proteus' COLLATE NOCASE),
   NULL, 'Pizz Basses', 'To do: find exact patch', NULL, 'Load Game, Dinner, Pumpkin Pom, Lake II, Devil City Usher', 'stuff_to_find', 'newer_vgm', 11),
  ((SELECT id FROM games WHERE title = 'Megami Tensei Gaiden: Last Bible III'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'E-MU Systems' COLLATE NOCASE AND p.name = 'Ultra Proteus' COLLATE NOCASE),
   NULL, 'French Horn', 'To do: find exact patch', NULL, 'Flight of Birds, Shark Ship', 'stuff_to_find', 'newer_vgm', 12),
  ((SELECT id FROM games WHERE title = 'Megami Tensei Gaiden: Last Bible III'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'E-MU Systems' COLLATE NOCASE AND p.name = 'Ultra Proteus' COLLATE NOCASE),
   NULL, 'Harmon Mute', 'To do: find exact patch', NULL, 'Flight of Birds, Dance, Megalopolis', 'stuff_to_find', 'newer_vgm', 13),
  ((SELECT id FROM games WHERE title = 'Megami Tensei Gaiden: Last Bible III'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'E-MU Systems' COLLATE NOCASE AND p.name = 'Ultra Proteus' COLLATE NOCASE),
   NULL, 'Sax', 'To do: find exact patch - Multiple notes sampled', NULL, 'Yonatan''s Theme, Hill, Val Ship, Red Owl', 'stuff_to_find', 'newer_vgm', 14),
  ((SELECT id FROM games WHERE title = 'Megami Tensei Gaiden: Last Bible III'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'R-70' COLLATE NOCASE),
   NULL, 'Drums', 'Brush Snare, Low Tom, Ride Cymbal', NULL, 'Hometown, Hill, Underworld Town', 'stuff_to_find', 'newer_vgm', 15),
  ((SELECT id FROM games WHERE title = 'Megami Tensei Gaiden: Last Bible III'),
   NULL, NULL, 'Synth Marimba', NULL, NULL, 'Dragon''s Fang, Felest Tower', 'stuff_to_find', 'newer_vgm', 16),
  ((SELECT id FROM games WHERE title = 'Megami Tensei Gaiden: Last Bible III'),
   NULL, NULL, 'Leslie Organ', NULL, NULL, 'Hometown, Dinner, Pumpkin Pom, Quarrel', 'stuff_to_find', 'newer_vgm', 17),
  ((SELECT id FROM games WHERE title = 'Megami Tensei Gaiden: Last Bible III'),
   NULL, NULL, 'Six String Guitar', NULL, NULL, 'Name Entry', 'stuff_to_find', 'newer_vgm', 18),
  ((SELECT id FROM games WHERE title = 'Megami Tensei Gaiden: Last Bible III'),
   NULL, NULL, 'Steel Guitar', NULL, NULL, 'Load Game, Hometown', 'stuff_to_find', 'newer_vgm', 19),
  ((SELECT id FROM games WHERE title = 'Megami Tensei Gaiden: Last Bible III'),
   NULL, NULL, 'Steel Guitar Pad', NULL, NULL, 'Field Theme 1', 'stuff_to_find', 'newer_vgm', 20),
  ((SELECT id FROM games WHERE title = 'Megami Tensei Gaiden: Last Bible III'),
   NULL, NULL, 'Muted Guitar', NULL, NULL, 'Dragon''s Fang, Garfy Service', 'stuff_to_find', 'newer_vgm', 21),
  ((SELECT id FROM games WHERE title = 'Megami Tensei Gaiden: Last Bible III'),
   NULL, NULL, 'Strat Guitar', NULL, NULL, 'Val Ship, Sky Wing', 'stuff_to_find', 'newer_vgm', 22),
  ((SELECT id FROM games WHERE title = 'Megami Tensei Gaiden: Last Bible III'),
   NULL, NULL, 'Funk Guitar Chord', NULL, NULL, 'Yontan''s Theme, Garfy Service', 'stuff_to_find', 'newer_vgm', 23),
  ((SELECT id FROM games WHERE title = 'Megami Tensei Gaiden: Last Bible III'),
   NULL, NULL, 'Distorted Guitar', NULL, NULL, 'Boss Battle 1, Felest Tower', 'stuff_to_find', 'newer_vgm', 24),
  ((SELECT id FROM games WHERE title = 'Megami Tensei Gaiden: Last Bible III'),
   NULL, NULL, 'Rock Guitar Chord & Chug', NULL, NULL, 'Battle 3, Battle with Arec', 'stuff_to_find', 'newer_vgm', 25),
  ((SELECT id FROM games WHERE title = 'Megami Tensei Gaiden: Last Bible III'),
   NULL, NULL, 'Fingered Bass', NULL, NULL, '-Used throughout the soundtrack-', 'stuff_to_find', 'newer_vgm', 26),
  ((SELECT id FROM games WHERE title = 'Megami Tensei Gaiden: Last Bible III'),
   NULL, NULL, 'Synth Bass', NULL, NULL, 'Bullton Tower, Underworld Forest, Arec''s Revenge, Battle with Arec, Last Battle', 'stuff_to_find', 'newer_vgm', 27),
  ((SELECT id FROM games WHERE title = 'Megami Tensei Gaiden: Last Bible III'),
   NULL, NULL, 'Distorted Square Bass', NULL, NULL, 'Flight of the Birds, Boss Battle 2', 'stuff_to_find', 'newer_vgm', 28),
  ((SELECT id FROM games WHERE title = 'Megami Tensei Gaiden: Last Bible III'),
   NULL, NULL, 'Harp', NULL, NULL, 'Mochoa', 'stuff_to_find', 'newer_vgm', 29),
  ((SELECT id FROM games WHERE title = 'Megami Tensei Gaiden: Last Bible III'),
   NULL, NULL, 'Octave Strings Section', NULL, NULL, 'Felest Tower', 'stuff_to_find', 'newer_vgm', 30),
  ((SELECT id FROM games WHERE title = 'Megami Tensei Gaiden: Last Bible III'),
   NULL, NULL, 'Trumpet', NULL, NULL, 'Field Theme 2', 'stuff_to_find', 'newer_vgm', 31),
  ((SELECT id FROM games WHERE title = 'Megami Tensei Gaiden: Last Bible III'),
   NULL, NULL, 'Attack Flute', NULL, NULL, 'To Underworld, Harry''s Theme', 'stuff_to_find', 'newer_vgm', 32),
  ((SELECT id FROM games WHERE title = 'Megami Tensei Gaiden: Last Bible III'),
   NULL, NULL, 'Piccolo', NULL, NULL, 'Village', 'stuff_to_find', 'newer_vgm', 33),
  ((SELECT id FROM games WHERE title = 'Megami Tensei Gaiden: Last Bible III'),
   NULL, NULL, 'Whistle', NULL, NULL, 'Brantika, Sodom', 'stuff_to_find', 'newer_vgm', 34),
  ((SELECT id FROM games WHERE title = 'Megami Tensei Gaiden: Last Bible III'),
   NULL, NULL, 'Synth Calliope', NULL, NULL, 'Field Theme 2', 'stuff_to_find', 'newer_vgm', 35),
  ((SELECT id FROM games WHERE title = 'Megami Tensei Gaiden: Last Bible III'),
   NULL, NULL, 'Music Box Bell', NULL, NULL, 'Brantika, Bad News, Underworld Forest', 'stuff_to_find', 'newer_vgm', 36),
  ((SELECT id FROM games WHERE title = 'Megami Tensei Gaiden: Last Bible III'),
   NULL, NULL, 'Jaw Harp Synths', NULL, NULL, 'Shark Ship, Battle with Arec', 'stuff_to_find', 'newer_vgm', 37),
  ((SELECT id FROM games WHERE title = 'Megami Tensei Gaiden: Last Bible III'),
   NULL, NULL, 'Synth Chord', NULL, NULL, 'Battle with Arec', 'stuff_to_find', 'newer_vgm', 38),
  ((SELECT id FROM games WHERE title = 'Megami Tensei Gaiden: Last Bible III'),
   NULL, NULL, 'Hip Hop Percussion', 'Kick, Snare', NULL, 'Flight of the Birds, Val Ship, Red Owl, Shark Ship, Garfy Service, Felest Tower', 'stuff_to_find', 'newer_vgm', 39),
  ((SELECT id FROM games WHERE title = 'Megami Tensei Gaiden: Last Bible III'),
   NULL, NULL, 'Analog Percussion', '909 Kick, 909 Snare, 808 Snare, 909 Hat, Clave, Tom', NULL, 'Bullton Tower, Sodom, Underworld Forest, Battle with Arec', 'stuff_to_find', 'newer_vgm', 40),

  -- G4: Devil Summoner: Soul Hackers — 3 rows
  ((SELECT id FROM games WHERE title = 'Devil Summoner: Soul Hackers'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'Text to Speech' COLLATE NOCASE),
   'System Voice -> Novelty', 'Albert', NULL, NULL, 'Opening Music', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Devil Summoner: Soul Hackers'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, NULL, 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Devil Summoner: Soul Hackers'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Nostalgia' COLLATE NOCASE),
   '15 Atmosferics', 'Snowfall', NULL, NULL, 'Epilogue 2, Staff Roll', 'main', 'newer_vgm', 3),

  -- G5: Shin Megami Tensei (PS1) — 3 rows
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei (Sony Playstation 1)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88 Pro' COLLATE NOCASE),
   'Native Map', '085 008 P5 Sync Lead', NULL, NULL, 'Battle! (Normal), Encounter! (Ginza)', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei (Sony Playstation 1)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88 Pro' COLLATE NOCASE),
   'Native Map -> Drum set', '017 POWER', NULL, NULL, 'Battle (Normal), Level Up, Ginza', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei (Sony Playstation 1)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'M1' COLLATE NOCASE),
   'PROG', '23 Choir', NULL, NULL, 'Law, Chaos', 'main', 'newer_vgm', 3),

  -- G6: Shin Megami Tensei II (PS1) — 2 rows
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei II (Sony Playstation 1)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88 Pro' COLLATE NOCASE),
   'Native Map -> Drum set', '017 POWER', NULL, NULL, 'Valhalla, Battle (Normal), Level Up', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei II (Sony Playstation 1)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'M1' COLLATE NOCASE),
   'PROG', '23 Choir', NULL, NULL, 'Neutral, Underground World, Chaos', 'main', 'newer_vgm', 2),

  -- G7: SMT III: Nocturne — 31 main + 9 stuff_to_find = 40 rows
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei III: Nocturne'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AKAI' COLLATE NOCASE AND p.name = 'S3000' COLLATE NOCASE),
   'Partition A -> AMBIENCE KICK ', 'N B.D.A 1', NULL, NULL, 'Forced Battle ', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei III: Nocturne'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AKAI' COLLATE NOCASE AND p.name = 'S3000' COLLATE NOCASE),
   'Partition B -> 13INCH HH', '13INCH AZ HH', NULL, NULL, 'Normal Battle -Town-', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei III: Nocturne'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AKAI' COLLATE NOCASE AND p.name = 'S3000' COLLATE NOCASE),
   'Partition B ->  PICCOLO SN', 'P-SN LP2', NULL, NULL, 'Forced Battle ', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei III: Nocturne'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AKAI' COLLATE NOCASE AND p.name = 'S3000' COLLATE NOCASE),
   'Partition C -> 14.K-ZIL H ', 'K-ZIL HH05', NULL, NULL, 'Forced Battle ', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei III: Nocturne'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AKAI' COLLATE NOCASE AND p.name = 'S3000' COLLATE NOCASE),
   'Partition C -> 14.K-ZIL H ', 'K-ZIL HH 1', NULL, NULL, 'Forced Battle ', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei III: Nocturne'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AKAI' COLLATE NOCASE AND p.name = 'S3000' COLLATE NOCASE),
   'Partition C -> 14.K-ZIL H ', 'K-ZIL HH 2', NULL, NULL, 'Forced Battle ', 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei III: Nocturne'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AKAI' COLLATE NOCASE AND p.name = 'S3000 (Volume 3)' COLLATE NOCASE),
   'Partition A -> LA KICK', 'LA KICK 1', NULL, NULL, 'Ginza', 'main', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei III: Nocturne'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AKAI' COLLATE NOCASE AND p.name = 'S3000 (Volume 3)' COLLATE NOCASE),
   'Partition A -> LA KICK', 'LA KICK 2', NULL, NULL, 'Ginza', 'main', 'newer_vgm', 8),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei III: Nocturne'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AKAI' COLLATE NOCASE AND p.name = 'S3000 (Volume 3)' COLLATE NOCASE),
   'Partition A -> LA KICK', 'LA KICK 3', NULL, NULL, 'Ginza', 'main', 'newer_vgm', 9),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei III: Nocturne'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AKAI' COLLATE NOCASE AND p.name = 'S3000 (Volume 3)' COLLATE NOCASE),
   'Partition B -> BRASS SNARE', 'BRASS 6-5A', NULL, NULL, 'Ginza', 'main', 'newer_vgm', 10),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei III: Nocturne'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AKAI' COLLATE NOCASE AND p.name = 'S3000 (Volume 3)' COLLATE NOCASE),
   'Partition B -> BRASS SNARE', 'BRASS 6-5B', NULL, NULL, 'Ginza', 'main', 'newer_vgm', 11),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei III: Nocturne'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AKAI' COLLATE NOCASE AND p.name = 'S3000 (Volume 3)' COLLATE NOCASE),
   'Partition B -> BRASS SNARE', 'BRASS 6-5D', NULL, NULL, 'Ginza', 'main', 'newer_vgm', 12),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei III: Nocturne'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AKAI' COLLATE NOCASE AND p.name = 'S3000 (Volume 3)' COLLATE NOCASE),
   'Partition D -> 14.K-ZIL HH', 'K-ZIL HH 1', NULL, NULL, 'Ginza', 'main', 'newer_vgm', 13),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei III: Nocturne'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AKAI' COLLATE NOCASE AND p.name = 'S3000 (Volume 3)' COLLATE NOCASE),
   'Partition D -> 14.K-ZIL HH', 'K-ZIL HH 2', NULL, NULL, 'Ginza', 'main', 'newer_vgm', 14),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei III: Nocturne'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AKAI' COLLATE NOCASE AND p.name = 'S3000 (Volume 3)' COLLATE NOCASE),
   'Partition D -> 14.K-ZIL HH', 'K-ZIL HH 3', NULL, NULL, 'Ginza', 'main', 'newer_vgm', 15),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei III: Nocturne'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AKAI' COLLATE NOCASE AND p.name = 'S3000 (Volume 3)' COLLATE NOCASE),
   'Partition D -> 14.K-ZIL HH', 'K-ZIL HH05', NULL, NULL, 'Ginza', 'main', 'newer_vgm', 16),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei III: Nocturne'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'Logic Pro' COLLATE NOCASE),
   'Legacy -> GarageBand -> Pianos and Keyboards', 'Smokey Clav', NULL, NULL, '48TEST.ADB', 'main', 'newer_vgm', 17),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei III: Nocturne'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'Text to Speech' COLLATE NOCASE),
   'System Voice -> Novelty', 'Albert', 'The vocals are amped', NULL, 'Forced Battle, Normal Battle, Boss Battle', 'main', 'newer_vgm', 18),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei III: Nocturne'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AudioNerdz' COLLATE NOCASE AND p.name = 'Delay Lama' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, 'Playing the Fool', 'main', 'newer_vgm', 19),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei III: Nocturne'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Classical Choir' COLLATE NOCASE),
   'Track 64 - effects -> TS 0:12', 'crossfade', 'clstr.-unis. (C3)', NULL, 'Metatron Defeated', 'main', 'newer_vgm', 20),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei III: Nocturne'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'TRINITY pro' COLLATE NOCASE),
   'Programs -> Bank B', 'B072 Orch/Ethnic Kits', NULL, NULL, 'Playing the Fool', 'main', 'newer_vgm', 21),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei III: Nocturne'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'TRITON-Rack' COLLATE NOCASE),
   'Programs -> Bank A', 'INT-A 062 Crimson 5ths', NULL, NULL, 'Ikebukuro Tunnel', 'main', 'newer_vgm', 22),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei III: Nocturne'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'TRITON-Rack' COLLATE NOCASE),
   'Programs -> Bank B', 'INT-B 042 CyborgFactoryHit', NULL, NULL, 'Kabukicho Prison', 'main', 'newer_vgm', 23),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei III: Nocturne'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Native Instruments' COLLATE NOCASE AND p.name = 'Absynth' COLLATE NOCASE),
   'Absynth Legacy', '5th Harmonic', NULL, NULL, 'Last Boss Battle - Before Transformation', 'main', 'newer_vgm', 24),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei III: Nocturne'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Native Instruments' COLLATE NOCASE AND p.name = 'Absynth' COLLATE NOCASE),
   'Absynth Legacy', 'KyptoniteDigger', NULL, NULL, 'Assembly of Nihilo', 'main', 'newer_vgm', 25),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei III: Nocturne'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Native Instruments' COLLATE NOCASE AND p.name = 'Absynth' COLLATE NOCASE),
   'Absynth Legacy', 'Spanker', NULL, NULL, 'Assembly of Nihilo', 'main', 'newer_vgm', 26),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei III: Nocturne'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88 Pro' COLLATE NOCASE),
   'Native Map -> Drum set', '017 POWER', NULL, NULL, 'Various', 'main', 'newer_vgm', 27),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei III: Nocturne'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88 Pro' COLLATE NOCASE),
   NULL, 'P5 Sync Lead', NULL, NULL, 'Normal Battle ~Amala Network~', 'main', 'newer_vgm', 28),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei III: Nocturne'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JD-990' COLLATE NOCASE),
   'PR-A', 'A-15 Deep Breath Pad', NULL, NULL, 'Boss Appearance', 'main', 'newer_vgm', 29),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei III: Nocturne'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-06 Dance' COLLATE NOCASE),
   'XP-X', '186 Vocamatic', NULL, NULL, 'Cathedral of Shadows ~Cursed~', 'main', 'newer_vgm', 30),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei III: Nocturne'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-06 Dance' COLLATE NOCASE),
   NULL, 'New Jack 136', NULL, NULL, 'Cathedral of Shadows -Cursed-', 'main', 'newer_vgm', 31),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei III: Nocturne'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'ES2' COLLATE NOCASE),
   'Lead Synths Bank A', 'Fuzzy Synth Guitar', NULL, NULL, 'Last Boss Battle - After Transformation', 'stuff_to_find', 'newer_vgm', 32),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei III: Nocturne'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Native Instruments' COLLATE NOCASE AND p.name = 'FM7' COLLATE NOCASE),
   NULL, NULL, 'might be used', NULL, 'Large Map - Real Universe, Normal Battle', 'stuff_to_find', 'newer_vgm', 33),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei III: Nocturne'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'TRINITY pro' COLLATE NOCASE),
   NULL, NULL, 'Brass', NULL, 'Playing the Fool', 'stuff_to_find', 'newer_vgm', 34),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei III: Nocturne'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JD-990' COLLATE NOCASE),
   NULL, NULL, 'Metal hit', NULL, 'Recovery Spring', 'stuff_to_find', 'newer_vgm', 35),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei III: Nocturne'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JD-990' COLLATE NOCASE),
   NULL, NULL, '64voicepiano (Layered with pad)', NULL, 'Heretic Mansion, Normal Battle - Stuck in Amalah', 'stuff_to_find', 'newer_vgm', 36),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei III: Nocturne'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JD-990' COLLATE NOCASE),
   NULL, NULL, 'Shakuhachi', NULL, 'Heretic Mansion', 'stuff_to_find', 'newer_vgm', 37),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei III: Nocturne'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JD-990' COLLATE NOCASE),
   NULL, NULL, 'Pick bass', NULL, 'Normal Battle - Stuck in Amalah, Heretic Mansion - Curse', 'stuff_to_find', 'newer_vgm', 38),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei III: Nocturne'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JD-990' COLLATE NOCASE),
   NULL, NULL, 'JV-1080 "Power Trip"', NULL, 'Normal Battle - Stuck in Amalah', 'stuff_to_find', 'newer_vgm', 39),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei III: Nocturne'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JD-990' COLLATE NOCASE),
   NULL, NULL, 'Vibraphone', NULL, 'Junk Shop', 'stuff_to_find', 'newer_vgm', 40),

  -- G8: Nocturne Maniax — 8 main + 2 stuff_to_find = 10 rows
  ((SELECT id FROM games WHERE title = 'Nocturne Maniax'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Big Fish Audio' COLLATE NOCASE AND p.name = 'Electric Ghetto' COLLATE NOCASE),
   'Disc 1 -> 03 132 E', 'guitar03', NULL, NULL, 'Dante Battle', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Nocturne Maniax'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Big Fish Audio' COLLATE NOCASE AND p.name = 'Electric Ghetto' COLLATE NOCASE),
   'Disc 1 -> 03 132 E', 'kick01', NULL, NULL, 'Dante Battle', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Nocturne Maniax'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Big Fish Audio' COLLATE NOCASE AND p.name = 'Megaton Trance Bomb' COLLATE NOCASE),
   'CD 1 -> Track 17 -> TS 1:09', 'drums', NULL, NULL, 'Dante Battle', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Nocturne Maniax'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Big Fish Audio' COLLATE NOCASE AND p.name = 'Megaton Trance Bomb' COLLATE NOCASE),
   'CD 1 -> Track 17 -> TS 1:18', 'drums', NULL, NULL, 'Dante Battle', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Nocturne Maniax'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Big Fish Audio' COLLATE NOCASE AND p.name = 'Megaton Trance Bomb' COLLATE NOCASE),
   'CD 1 -> Track 22 -> Sample 10', 'arpeggios 140 bpm', NULL, NULL, 'Dante Battle', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'Nocturne Maniax'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Hardcore' COLLATE NOCASE),
   'DJ Brisk -> 303', 'Bouncer', NULL, NULL, 'Dante Battle', 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'Nocturne Maniax'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Hardcore' COLLATE NOCASE),
   'DJ Brisk -> 303', 'TB or Not TB', NULL, NULL, 'Dante Battle', 'main', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'Nocturne Maniax'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Hardcore' COLLATE NOCASE),
   'DJ Brisk -> Arpeggios', 'Tinitus', NULL, NULL, 'Dante Battle', 'main', 'newer_vgm', 8),
  ((SELECT id FROM games WHERE title = 'Nocturne Maniax'),
   NULL, NULL, NULL, 'Pick bass', 'Roland - ? (JV or JD series)', 'Talk', 'stuff_to_find', 'newer_vgm', 9),
  ((SELECT id FROM games WHERE title = 'Nocturne Maniax'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Chemical Beats' COLLATE NOCASE),
   NULL, NULL, 'Drum loop', NULL, 'Talk', 'stuff_to_find', 'newer_vgm', 10),

  -- G9: SMT Digital Devil Saga 2 — 1 row
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei: Digital Devil Saga 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'UltimateSoundBank' COLLATE NOCASE AND p.name = 'PlugSound Vol. 2 Fretted Instruments' COLLATE NOCASE),
   '04-Electric Bass -> 04-Fend. Jazz Bass', '?', 'Fend. Slap patch', NULL, 'Epic Battle', 'main', 'newer_vgm', 1),

  -- G10: SMT IMAGINE — 16 main + 3 stuff_to_find = 19 rows
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IMAGINE'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'Logic Pro' COLLATE NOCASE),
   NULL, 'French Horn Section Legato', NULL, NULL, '7th Anniversary, Easy Boss', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IMAGINE'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'Logic Pro' COLLATE NOCASE),
   NULL, 'Trumpet Section Legato', NULL, NULL, NULL, 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IMAGINE'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Ra' COLLATE NOCASE),
   'Far East -> Plucked -> Koto', 'Koto KS C0-F#0', NULL, NULL, 'New Year 2014', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IMAGINE'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   NULL, '4TB Forte Piano', NULL, NULL, NULL, 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IMAGINE'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   NULL, 'C Orch Chimes', NULL, NULL, 'Act XX Lucifer, Celu Tower Boss, Colosseum Boss, Fiend Battle', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IMAGINE'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   NULL, 'C 12 Cymbal', NULL, NULL, 'Battle! (Final [Nocturne])', 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IMAGINE'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Heavyocity' COLLATE NOCASE AND p.name = 'Damage' COLLATE NOCASE),
   NULL, 'LPS Organic', NULL, NULL, 'Battle! (Universe Seth)', 'main', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IMAGINE'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Heavyocity' COLLATE NOCASE AND p.name = 'Damage' COLLATE NOCASE),
   NULL, 'LPS Epic Tech Full', NULL, NULL, '7th Anniversary, Hard Boss 2, Universe Area', 'main', 'newer_vgm', 8),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IMAGINE'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Heavyocity' COLLATE NOCASE AND p.name = 'Damage' COLLATE NOCASE),
   NULL, 'LPS Mangled Pop Full', NULL, NULL, '7th Anniversary, Dungeon', 'main', 'newer_vgm', 9),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IMAGINE'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Native Instruments' COLLATE NOCASE AND p.name = 'Absynth' COLLATE NOCASE),
   NULL, 'Mekon Temple', NULL, NULL, 'New Char Selection', 'main', 'newer_vgm', 10),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IMAGINE'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Steinberg' COLLATE NOCASE AND p.name = 'HALion Sonic SE' COLLATE NOCASE),
   'GM Set', '[GM 003] Electric Grand Piano', NULL, NULL, 'Devil Wedding', 'main', 'newer_vgm', 11),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IMAGINE'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'XLN Audio' COLLATE NOCASE AND p.name = 'Addictive Drums' COLLATE NOCASE),
   'Kit', NULL, NULL, NULL, 'Abaddon Battle, Act 20-2 Seth Battle, Celu Tower Boss', 'main', 'newer_vgm', 12),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IMAGINE'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Total Funk' COLLATE NOCASE),
   NULL, 'Fluster (Echo D2)', NULL, NULL, 'Act 19-4: Distortion Floor', 'main', 'newer_vgm', 13),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IMAGINE'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Total Funk' COLLATE NOCASE),
   NULL, 'Flute FX 7 (Echo C2)', NULL, NULL, 'Act 19-4: Distortion Floor', 'main', 'newer_vgm', 14),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IMAGINE'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Total Funk' COLLATE NOCASE),
   NULL, 'Flute FX 7 (Echo D2)', NULL, NULL, 'Act 19-4: Distortion Floor', 'main', 'newer_vgm', 15),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IMAGINE'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Total Funk' COLLATE NOCASE),
   NULL, 'Flute FX 7 (Echo G2)', NULL, NULL, 'Act 19-4: Distortion Floor', 'main', 'newer_vgm', 16),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IMAGINE'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Native Instruments' COLLATE NOCASE AND p.name = 'Kontakt Factory Library' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, NULL, 'stuff_to_find', 'newer_vgm', 17),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IMAGINE'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Hardcore' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, NULL, 'stuff_to_find', 'newer_vgm', 18),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IMAGINE'),
   NULL, NULL, NULL, NULL, 'Zero-G - ?', 'Colosseum, Pentalpha Battle', 'stuff_to_find', 'newer_vgm', 19),

  -- G11: Devil Summoner 2: Raidou — 1 main + 1 stuff = 2 rows
  ((SELECT id FROM games WHERE title = 'Devil Summoner 2: Raidou Kuzunoha vs. King Abaddon'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG' COLLATE NOCASE AND p.name = 'Kick-Ass Brass!' COLLATE NOCASE),
   'KAB Trumpet', NULL, NULL, NULL, 'Theme of Raidou Kuzunoha 2008, The Summoner of Tsukigata, Treat Me Well From Now On, Adventure, Decisive Battle', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Devil Summoner 2: Raidou Kuzunoha vs. King Abaddon'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG' COLLATE NOCASE AND p.name = 'Kick-Ass Brass!' COLLATE NOCASE),
   NULL, NULL, 'more patches are used', NULL, NULL, 'stuff_to_find', 'newer_vgm', 2),

  -- G12: Devil Survivor — 5 rows
  ((SELECT id FROM games WHERE title = 'Devil Survivor'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'Loops' COLLATE NOCASE),
   'Jam Pack for Garageband', 'Effected Drum Kit 10', NULL, NULL, 'Pinch Battle', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Devil Survivor'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'Classic Stylus', '67-Crenshaw', NULL, NULL, 'Normal - jingle', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Devil Survivor'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves', '72-Liquid Frame Puddles', NULL, NULL, 'Anxiety - jingle', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Devil Survivor'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves', '80-Space Ranger S+H', NULL, NULL, 'Anxiety - jingle', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Devil Survivor'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves', '143-Mind Bender Half Metal', NULL, NULL, 'Achievement - jingle', 'main', 'newer_vgm', 5),

  -- G13: Devil Survivor 2 — 7 rows
  ((SELECT id FROM games WHERE title = 'Devil Survivor 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   NULL, NULL, 'cymbal', NULL, 'In The Devistated Town', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Devil Survivor 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'Classic Stylus', NULL, 'Congas', NULL, 'Exploration', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Devil Survivor 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves', '68-Tower Zero Hi Hats', NULL, NULL, 'World of Illusions', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Devil Survivor 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves', '70-Datalife', NULL, NULL, 'Crumbling Routine', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Devil Survivor 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves', '79-Red Clouds', NULL, NULL, 'Providence', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'Devil Survivor 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves', '125-Evil Echo', 'custom loop', NULL, 'Devil Fusion.exe', 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'Devil Survivor 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'XLN Audio' COLLATE NOCASE AND p.name = 'Addictive Drums' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, 'Rotating World', 'main', 'newer_vgm', 7),

  -- G14: Soul Hackers Arrange (Album) — 1 row
  ((SELECT id FROM games WHERE title = 'Devil Summoner: Soul Hackers Arrange (Soundtrack Album)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves -> 68-Small Blocks', '68-Small Blocks Bending Bass', NULL, NULL, 'Hotel Gomaden', 'main', 'newer_vgm', 1),

  -- G15: SMT IV — 26 main + 9 stuff_to_find = 35 rows.
  -- Row 1 below: cross-game sample reference (Shoji Meguro from SMT III).
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IV'),
   NULL, NULL, 'Normal Battle', NULL, 'Sample: Shoji Meguro - Shin Megami Tensei III', 'CLUBMILTON', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IV'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'EXS24' COLLATE NOCASE),
   'Synthesizers -> Sequence Elements', 'Abstracta', NULL, NULL, 'Battle B1 - (Midboss Battle Theme)', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IV'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'EXS24' COLLATE NOCASE),
   'Synthesizers -> Synth Waveforms -> Digital Waveforms', 'Voxpad INIT', 'lead', NULL, 'Black Market, Battle A1 - (Naruku Battle Theme)', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IV'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'Loops' COLLATE NOCASE),
   'Jam Pack Voices', 'Darcy Background 05', NULL, NULL, 'Members Only Club', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IV'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'Loops' COLLATE NOCASE),
   'Jam Pack Voices', 'Darcy Melody 04', NULL, NULL, 'Members Only Club', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IV'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'Loops' COLLATE NOCASE),
   'Jam Pack Voices', 'Darcy Melody 33', NULL, NULL, 'Members Only Club', 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IV'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'Loops' COLLATE NOCASE),
   'Jam Pack Voices', 'Tia Lyric 11', NULL, NULL, 'Ashura-Kai Authorized Shop', 'main', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IV'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'Loops' COLLATE NOCASE),
   'Jam Pack Voices', 'Jessi Melody 06', NULL, NULL, 'The Hunter Association', 'main', 'newer_vgm', 8),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IV'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Goliath' COLLATE NOCASE),
   'Keyboard Mallet Instr', 'Church Organ', NULL, NULL, 'Law Theme, Battle B6 - (Merkahbah II)', 'main', 'newer_vgm', 9),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IV'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'Strings -> Solo Violin -> 1 Long', 'SVL Sus Vib Hard', NULL, NULL, 'Battle C5 - (Archangel Battle)', 'main', 'newer_vgm', 10),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IV'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Ra' COLLATE NOCASE),
   'Europe -> Wind -> Highlnd Pipes', 'Highland Pipes VS', NULL, NULL, 'Aquila Statue Plaza ', 'main', 'newer_vgm', 11),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IV'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'M1 Legacy Collection' COLLATE NOCASE),
   'PROG', 'M01 23 Choir', NULL, NULL, 'Battle C1 - (VR Battle)', 'main', 'newer_vgm', 12),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IV'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Native Instruments' COLLATE NOCASE AND p.name = 'FM8' COLLATE NOCASE),
   'FM8 Factory -> Mallet Instruments', 'Anatomie', NULL, NULL, 'Excavation Worker''s Quarters', 'main', 'newer_vgm', 13),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IV'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Native Instruments' COLLATE NOCASE AND p.name = 'Massive' COLLATE NOCASE),
   'Massive Factory', '1991', NULL, NULL, 'Aboveground Urban Area C', 'main', 'newer_vgm', 14),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IV'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Native Instruments' COLLATE NOCASE AND p.name = 'Massive' COLLATE NOCASE),
   'Massive Factory', 'Classic 3VCO Kit', NULL, NULL, 'Main Theme', 'main', 'newer_vgm', 15),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IV'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Native Instruments' COLLATE NOCASE AND p.name = 'Massive' COLLATE NOCASE),
   'Massive Threat', 'Asp Viper', NULL, NULL, 'Infernal Ichigaya', 'main', 'newer_vgm', 16),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IV'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Native Instruments' COLLATE NOCASE AND p.name = 'Massive' COLLATE NOCASE),
   'Massive Exp. 2 ', 'Amsterdamned', NULL, NULL, 'The Eastern Kingdom of Mikado', 'main', 'newer_vgm', 17),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IV'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Native Instruments' COLLATE NOCASE AND p.name = 'Massive' COLLATE NOCASE),
   'Massive Exp. 2', 'Beltramerized', NULL, NULL, 'The Hunter Association', 'main', 'newer_vgm', 18),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IV'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Native Instruments' COLLATE NOCASE AND p.name = 'Massive' COLLATE NOCASE),
   'Urban Arsenal 2', 'Square Pipe', NULL, NULL, 'Battle C4 - (Fiend Battle Theme)', 'main', 'newer_vgm', 19),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IV'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Native Instruments' COLLATE NOCASE AND p.name = 'Massive' COLLATE NOCASE),
   'Urban Arsenal 2 -> Synth Lead', 'Sweetlick', 'likely a different preset', NULL, 'The Hunter Association', 'main', 'newer_vgm', 20),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IV'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Native Instruments' COLLATE NOCASE AND p.name = 'Massive' COLLATE NOCASE),
   NULL, 'Tickle', 'could be FM8 - Fading Frog instead', NULL, 'The Hunter Association', 'main', 'newer_vgm', 21),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IV'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'Classic Stylus -> Triangle', '126-Triangle', NULL, NULL, 'Members Only Club', 'main', 'newer_vgm', 22),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IV'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves -> 70-Eden', '70-Eden Vinyl Cowbell', NULL, NULL, 'Ashura-Kai Authorized Shop', 'main', 'newer_vgm', 23),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IV'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves -> 103-Earthquake', '103-Earthquake Dist Drum', NULL, NULL, 'Pluto Castle', 'main', 'newer_vgm', 24),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IV'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Trilian' COLLATE NOCASE),
   'Bass - Electric Picked', 'Rock P-Bass - Full Range', NULL, NULL, 'Black Market', 'main', 'newer_vgm', 25),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IV'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Vir2' COLLATE NOCASE AND p.name = 'Electri6ity' COLLATE NOCASE),
   NULL, 'Rickenbacker Amped', 'sounds like it, need to confirm', NULL, 'Battle A2 - (Tokyo Battle Theme)', 'main', 'newer_vgm', 26),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IV'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'EXS24' COLLATE NOCASE),
   'Synthesizers', NULL, '?? (wave pad)', NULL, 'Battle B1 - (Midboss Battle Theme), The Hunter Association', 'stuff_to_find', 'newer_vgm', 27),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IV'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, 'Battle B6 - (Merkahbah II)', 'stuff_to_find', 'newer_vgm', 28),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IV'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Ra' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, 'Tennozu Shelter', 'stuff_to_find', 'newer_vgm', 29),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IV'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Heavyocity' COLLATE NOCASE AND p.name = 'Damage' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, 'Battle C4 - (Fiend Battle Theme)', 'stuff_to_find', 'newer_vgm', 30),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IV'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Native Instruments' COLLATE NOCASE AND p.name = 'FM8' COLLATE NOCASE),
   NULL, NULL, 'pad', NULL, 'Battle C2 - (Challenge Quest Boss Battle)', 'stuff_to_find', 'newer_vgm', 31),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IV'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'M1 Legacy Collection' COLLATE NOCASE),
   NULL, NULL, 'could be something else', NULL, 'Homesickness', 'stuff_to_find', 'newer_vgm', 32),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IV'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'M1 Legacy Collection' COLLATE NOCASE),
   NULL, NULL, 'could be something else', NULL, 'Roppongi Area', 'stuff_to_find', 'newer_vgm', 33),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IV'),
   NULL, NULL, NULL, 'static', 'Sound Ideas - ?', 'Traffic - (Arcade Town)', 'stuff_to_find', 'newer_vgm', 34),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IV'),
   NULL, NULL, NULL, NULL, 'Zero-G - ?', NULL, 'stuff_to_find', 'newer_vgm', 35),

  -- G16: SMT IV Sound & Art Collection — 1 row
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IV: Sound & Art Collection'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'Classic Stylus', '79-Shifted Jazz', 'modified / pitched down', NULL, 'Prelude III', 'main', 'newer_vgm', 1),

  -- G17: SMT IV: Apocalypse — 9 main + 8 stuff_to_find = 17 rows
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IV: Apocalypse'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'EXS24' COLLATE NOCASE),
   'Synthesizers -> Synth Pads', 'Voxpad', NULL, NULL, 'Time of Selection', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IV: Apocalypse'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'EXS24' COLLATE NOCASE),
   'Orchestral -> Choir', 'Church Choir', NULL, NULL, 'Battle - f7 (To Be All Things)', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IV: Apocalypse'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'Loops' COLLATE NOCASE),
   'Jam Pack Voices', 'Jessi Melody 06', NULL, NULL, 'Evildoer Hunter Chamber of Commerce', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IV: Apocalypse'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   NULL, 'Orch chimes', NULL, NULL, 'Coalescence 1212', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IV: Apocalypse'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Ra' COLLATE NOCASE),
   'Americas -> Wind -> Pan Flute', 'Pan Flute KS C0-D#0', NULL, NULL, 'TD15_kgsk (Castle of the Four Gods)', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IV: Apocalypse'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'M1 Legacy Collection' COLLATE NOCASE),
   'COMBI', 'M03 44 Gen/Fue', 'Syn ZIMBA (M03 07) TS:0:00; SquarePipe (M03 75) TS:0:07', NULL, 'Kinshicho Underground District', 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IV: Apocalypse'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'M1 Legacy Collection' COLLATE NOCASE),
   'PROG', 'M01 23 Choir', NULL, NULL, 'Battle - f4 (Polytheistic God Union)', 'main', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IV: Apocalypse'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Trilian' COLLATE NOCASE),
   NULL, 'Sweepy Prophet Rez DDL', 'could be something else', NULL, 'East Madness', 'main', 'newer_vgm', 8),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IV: Apocalypse'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Trilian' COLLATE NOCASE),
   'Bass - Electric Fingered', 'Clean Fender - Full Range All', NULL, NULL, 'Kenshicho Underground', 'main', 'newer_vgm', 9),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IV: Apocalypse'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   NULL, NULL, 'cymbals', NULL, 'Coalescence 1212', 'stuff_to_find', 'newer_vgm', 10),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IV: Apocalypse'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Heavyocity' COLLATE NOCASE AND p.name = 'Damage' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, 'Battle - f5 (Break Away from the Old Kimono)', 'stuff_to_find', 'newer_vgm', 11),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IV: Apocalypse'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Heavyocity' COLLATE NOCASE AND p.name = 'Damage' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, 'Battle - f8 (To Become God''s Enemy)', 'stuff_to_find', 'newer_vgm', 12),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IV: Apocalypse'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Heavyocity' COLLATE NOCASE AND p.name = 'Damage' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, 'Main Theme', 'stuff_to_find', 'newer_vgm', 13),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IV: Apocalypse'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Heavyocity' COLLATE NOCASE AND p.name = 'Damage' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, 'Coalescence 1212', 'stuff_to_find', 'newer_vgm', 14),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IV: Apocalypse'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'M1 Legacy Collection' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, 'Large Map, The World After', 'stuff_to_find', 'newer_vgm', 15),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IV: Apocalypse'),
   NULL, NULL, NULL, NULL, 'KORG - ?', 'Interactions', 'stuff_to_find', 'newer_vgm', 16),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei IV: Apocalypse'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, 'East Madness', 'stuff_to_find', 'newer_vgm', 17),

  -- G18: SMT 25th Anniversary Memorial Arrange — 11 main + 4 stuff_to_find = 15 rows
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei 25th Anniversary Memorial Arrange'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'Logic Pro' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, 'World Map: Real World (Shin Megami Tensei III: Nocturne)', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei 25th Anniversary Memorial Arrange'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'Loops' COLLATE NOCASE),
   'Jam Pack 1', 'Effected Drum Kit 18', 'processed', NULL, 'Kinshicho Underground (Shin Megami Tensei IV: Apocalypse)', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei 25th Anniversary Memorial Arrange'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Audiobro' COLLATE NOCASE AND p.name = 'LA Scoring Strings' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, 'Passage to Subterranean World', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei 25th Anniversary Memorial Arrange'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, 'The Fear of God', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei 25th Anniversary Memorial Arrange'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Native Instruments' COLLATE NOCASE AND p.name = 'New York Concert Grand' COLLATE NOCASE),
   NULL, NULL, 'available in Kontakt Factory Library and Akoustik Piano', NULL, 'Confession / Secret (Piano Version), Regret, Sweet, "Run, Run, Run!", Trick, Ark, Rivers in the Desert, Swear to My Bones', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei 25th Anniversary Memorial Arrange'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Liquid Grooves S.A.G.E. Xpander' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, 'Cathedral (Shin Megami Tensei)', 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei 25th Anniversary Memorial Arrange'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Metamorphosis S.A.G.E. Xpander' COLLATE NOCASE),
   '050-059', '055-Mohave a', 'custom loop', NULL, 'Camp Ichigaya', 'main', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei 25th Anniversary Memorial Arrange'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Omnisphere' COLLATE NOCASE),
   'Distortion', 'Laredo', NULL, NULL, 'Cathedral (Shin Megami Tensei)', 'main', 'newer_vgm', 8),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei 25th Anniversary Memorial Arrange'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Omnisphere' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, 'Camp Ichigaya', 'main', 'newer_vgm', 9),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei 25th Anniversary Memorial Arrange'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Trilian' COLLATE NOCASE),
   'Bass - Electric Fingered', 'Clean Fender - Full Range All', NULL, NULL, 'Tokyo, 3D Underground World, Ending (Shin Megami Tensei)', 'main', 'newer_vgm', 10),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei 25th Anniversary Memorial Arrange'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'XLN Audio' COLLATE NOCASE AND p.name = 'Addictive Drums' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, 'The Fear of God', 'main', 'newer_vgm', 11),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei 25th Anniversary Memorial Arrange'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Heavyocity' COLLATE NOCASE AND p.name = 'Damage' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, 'Cathedral (Shin Megami Tensei)', 'stuff_to_find', 'newer_vgm', 12),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei 25th Anniversary Memorial Arrange'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Heavyocity' COLLATE NOCASE AND p.name = 'Damage' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, 'Ginza', 'stuff_to_find', 'newer_vgm', 13),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei 25th Anniversary Memorial Arrange'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Trilian' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, 'Cathedral (Shin Megami Tensei)', 'stuff_to_find', 'newer_vgm', 14),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei 25th Anniversary Memorial Arrange'),
   NULL, NULL, NULL, 'pretty obvious drumloop', NULL, '3D Underground World', 'stuff_to_find', 'newer_vgm', 15),

  -- G19: Dx2 SMT Liberation — 2 rows
  ((SELECT id FROM games WHERE title = 'Dx2 Shin Megami Tensei: Liberation'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Atmosphere' COLLATE NOCASE),
   'Bells and Vibes', 'Classic Super Bells', NULL, NULL, 'bgm_drama_unquiet', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Dx2 Shin Megami Tensei: Liberation'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Omnisphere' COLLATE NOCASE),
   'Synth Mono', 'Amped Electric Supersaw', NULL, NULL, 'Home', 'main', 'newer_vgm', 2),

  -- G20: SMT V — 6 rows
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei V'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'Text to Speech' COLLATE NOCASE),
   'System Voice -> Novelty', 'Albert', 'the vocals are amped', NULL, 'Demi Fiend Battle', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei V'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Modartt' COLLATE NOCASE AND p.name = 'PianoTeq 6' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, 'World of Shadows', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei V'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Omnisphere' COLLATE NOCASE),
   'Bells and Vibes', 'Church Bells', NULL, NULL, 'Fairy Forest, North Shinagawa', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei V'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Omnisphere' COLLATE NOCASE),
   'Human Voices', 'Classical Tenor Ah - p', NULL, NULL, 'Cadaver''s Hollow', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei V'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves', '68-Tower Zero Hi Hats', NULL, NULL, 'Battle - Power', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei V'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Trilian' COLLATE NOCASE),
   'Bass - Electric Fingered', 'Clean Fender - Full Range All', NULL, NULL, 'Jouin High School, Tokyo -Daybreak-', 'main', 'newer_vgm', 6),

  -- G21: SMT V Vengeance — 8 main + 8 stuff_to_find = 16 rows
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei V Vengeance'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'M1 Legacy Collection' COLLATE NOCASE),
   'PROG', 'M01 08 Pan Flute', NULL, NULL, 'SMTV festival dance', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei V Vengeance'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Modartt' COLLATE NOCASE AND p.name = 'PianoTeq 6' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, '~Used throughout the soundtrack~', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei V Vengeance'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Atmosphere' COLLATE NOCASE),
   'Bells and Vibes', 'Attack Shimmer', NULL, NULL, 'Battle -deadlock-', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei V Vengeance'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Omnisphere' COLLATE NOCASE),
   'Electronic Mayhem', 'Terrabyte', NULL, NULL, 'Battle -primordial goddess-', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei V Vengeance'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Omnisphere' COLLATE NOCASE),
   'Keyboards', 'Just The Simple Dreamy Piano Again', NULL, NULL, 'Guide to the end, Ichiro and Yuzuru, Tao and the young man', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei V Vengeance'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'Classic Stylus -> Triangles', NULL, NULL, NULL, 'Ace Detective Pixie', 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei V Vengeance'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves -> 109-War of the Thips', '109-War of the Thips', NULL, NULL, 'Battle -deadlock-', 'main', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei V Vengeance'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Trilian' COLLATE NOCASE),
   'Synth Mono', 'Sweepy Prophet Rez DDL', NULL, NULL, 'Battle -Beelzebub-', 'main', 'newer_vgm', 8),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei V Vengeance'),
   NULL, NULL, NULL, '303 bass', 'Apple - ?', 'Battle -alkalic acid rush-', 'stuff_to_find', 'newer_vgm', 9),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei V Vengeance'),
   NULL, NULL, NULL, 'choir ', 'KORG / Roland - ?', 'Battle -no hypocrisy-', 'stuff_to_find', 'newer_vgm', 10),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei V Vengeance'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Native Instruments' COLLATE NOCASE AND p.name = 'Spotlight Collection: India' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, 'Battle -the adversary-', 'stuff_to_find', 'newer_vgm', 11),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei V Vengeance'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Steinberg' COLLATE NOCASE AND p.name = 'Halion Sonic' COLLATE NOCASE),
   NULL, NULL, 'piano (?) sounds like it kinda', NULL, 'Battle -no hypocrisy-', 'stuff_to_find', 'newer_vgm', 12),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei V Vengeance'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Omnisphere' COLLATE NOCASE),
   NULL, NULL, 'pluck', NULL, 'Battle -deadlock-', 'stuff_to_find', 'newer_vgm', 13),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei V Vengeance'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Omnisphere' COLLATE NOCASE),
   NULL, NULL, 'bells and synth saw', NULL, 'Battle -primordial goddess-', 'stuff_to_find', 'newer_vgm', 14),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei V Vengeance'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Omnisphere' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, 'Ichiro and Yuzuru', 'stuff_to_find', 'newer_vgm', 15),
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei V Vengeance'),
   NULL, NULL, NULL, 'Amen Break', NULL, 'Battle -primordial goddess-', 'stuff_to_find', 'newer_vgm', 16);
