-- NEWER VGM SEGA/Atlus — Section 2 (Puyo Puyo)
--
-- Source: reference/NEWER VGM Sound Sources - SEGAAtlus.csv lines 317-460.
-- 10 game records, ~124 usage rows.
--
-- Puyo Puyo Sun is split into three game records (Arcade / Saturn / N64) since
-- the CSV identifies distinct release dates AND distinct composer credits per
-- platform — the Compile-era Saturn music and the Sega-developed N64 remake
-- share almost no sample library overlap.
--
-- Verbatim oddities preserved (Rule 2):
--   - "Super Puyo Puyo Tsuu " trailing space in title.
--   - "Puyo Puyo Sun " trailing space in section header (but used without
--     the space in the platform-specific game records).
--   - "Puyo Puyo!! Tetris" — CSV release-date cell has missing close paren
--     "(Released: February 6, 2014" and missing close paren on the composer
--     "(Music By: Hideki Abe". Game record uses the dates without preserving
--     the typos.
--   - Roland "D-50 / U-20" (T365) — contributor unsure which of two Rolands
--     was used; preserved as a single product name with the slash.
--
-- Conventions: per-game positions restart at 1; "?,?" rows → product_id NULL
-- and raw_source NULL with description in notes (same as Section 1).

INSERT OR IGNORE INTO products (manufacturer_id, name, type) VALUES
  ((SELECT id FROM manufacturers WHERE name = 'Yamaha'        COLLATE NOCASE), 'DX100',                          'Synth'),
  ((SELECT id FROM manufacturers WHERE name = 'Yamaha'        COLLATE NOCASE), 'MU80',                           'Synth'),
  ((SELECT id FROM manufacturers WHERE name = 'Roland'        COLLATE NOCASE), 'TR-909',                         'Hardware'),
  ((SELECT id FROM manufacturers WHERE name = 'Roland'        COLLATE NOCASE), 'D-50 / U-20',                    'Synth'),
  ((SELECT id FROM manufacturers WHERE name = 'Roland'        COLLATE NOCASE), 'JV-1080',                        'Synth'),
  ((SELECT id FROM manufacturers WHERE name = 'Roland'        COLLATE NOCASE), 'Fantom-XR',                      'Synth'),
  ((SELECT id FROM manufacturers WHERE name = 'Spectrasonics' COLLATE NOCASE), 'Retro Funk S.A.G.E. Xpander',    'Sample Library');

INSERT INTO games (title, platform, released, composers, composers_normalized, notes) VALUES
  ('Super Puyo Puyo',                          'Super Famicom',                                              '1993-12-10', 'Masanobu Tsukamoto, Einosuke Nagao',                                                  'masanobu tsukamoto, einosuke nagao',                                                  'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 2 Puyo Puyo).'),
  ('Super Nazo Puyo: Rulue no Roux',           'Super Famicom',                                              '1995-05-26', 'Tomonori Minami, Einosuke Nagao, Tsuyoshi Matsushima, Nobuaki Yamasaki, Koji Onari', 'tomonori minami, einosuke nagao, tsuyoshi matsushima, nobuaki yamasaki, koji onari', 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 2 Puyo Puyo). Compile-era spinoff title.'),
  ('Puyo Puyo Tsuu (SEGA Saturn)',             'Sega Saturn',                                                '1995-10-27', 'Katsumi Tanaka, Tomonori Minami, Einosuke Nagao, Tsuyoshi Matsushima, Nobuaki Yamasaki', 'katsumi tanaka, tomonori minami, einosuke nagao, tsuyoshi matsushima, nobuaki yamasaki', 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 2 Puyo Puyo). Title preserved verbatim including platform suffix in title.'),
  ('Super Puyo Puyo Tsuu ',                    'Super Famicom',                                              NULL,         'Tomonori Minami, Einosuke Nagao, Tsuyoshi Matsushima',                                'tomonori minami, einosuke nagao, tsuyoshi matsushima',                                'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 2 Puyo Puyo). CSV release-date cell reads "(Released: ???)" — date unknown. Title preserves trailing space verbatim from CSV.'),
  ('Puyo Puyo Sun (Original - Arcade)',        'Arcade',                                                     '1996-12-01', NULL,                                                                                  NULL,                                                                                  'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 2 Puyo Puyo). CSV release cell "(Released: December, 1996)" specifies month only; day=01 used for sort key. Only 1 source row in CSV (Roland SC-88 with no details).'),
  ('Puyo Puyo Sun (Saturn)',                   'Sega Saturn',                                                '1997-02-14', 'Tsuyoshi Matsushima, Koji Onari, Satoshi Shimazaki, Einosuke Nagao, Kazuaki Nagai',  'tsuyoshi matsushima, koji onari, satoshi shimazaki, einosuke nagao, kazuaki nagai',  'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 2 Puyo Puyo). Compile-era Saturn port.'),
  ('Puyo Puyo Sun (N64)',                      'Nintendo 64',                                                '1997-10-01', 'Koji Onari, Satoshi Shimazaki, Kō Hayashi, Daisuke Nagata, Osamu Ishikawa',          'koji onari, satoshi shimazaki, kō hayashi, daisuke nagata, osamu ishikawa',          'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 2 Puyo Puyo). N64-specific remake by Sega; different composer team and sample library from the Arcade/Saturn versions. CSV release cell "(Released: October, 1997)" specifies month only; day=01 used for sort key.'),
  ('Puyo Puyo!! 15th Anniversary',             'Nintendo DS, PlayStation Portable, Wii',                     '2006-12-14', 'Hideki Abe',                                                                          'hideki abe',                                                                          'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 2 Puyo Puyo). No identified main usages in CSV — only stuff_to_find rows listing JV-1080, XV-5080, Fantom-XR candidates.'),
  ('Puyo Puyo!! 20th Anniversary',             'Nintendo DS, Nintendo 3DS, PlayStation Portable, Wii, PlayStation 3', '2011-07-14', 'Hideki Abe, Naofumi Hataya',                                                          'hideki abe, naofumi hataya',                                                          'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 2 Puyo Puyo).'),
  ('Puyo Puyo!! Tetris',                       'PlayStation 3, PlayStation 4, PlayStation Vita, Nintendo 3DS, Wii U, Xbox One, Nintendo Switch, PC', '2014-02-06', 'Hideki Abe',                                                                          'hideki abe',                                                                          'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 2 Puyo Puyo). CSV had two unbalanced parens in the release-date and composer cells (close parens missing); content captured here as intended by the contributor.');

INSERT INTO usages
  (game_id, product_id, path_bank, preset, notes, raw_source, examples, category, source_family, position)
VALUES
  -- G1: Super Puyo Puyo — 5 main + 4 stuff = 9 rows
  ((SELECT id FROM games WHERE title = 'Super Puyo Puyo'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'M1' COLLATE NOCASE),
   'PROG', '18 Flute', NULL, NULL, 'Memories of PuyoPuyo, Sunset of PuyoPuyo', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Super Puyo Puyo'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'M1' COLLATE NOCASE),
   'PROG', '27 Strings', NULL, NULL, 'Baroque of PuyoPuyo', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Super Puyo Puyo'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-55' COLLATE NOCASE),
   'Capital', '022 Accordion Fr', 'Staccato with reverb', NULL, 'Theme of PuyoPuyo', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Super Puyo Puyo'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-55' COLLATE NOCASE),
   'Capital', '115 Steel Drums', NULL, NULL, 'Toy of PuyoPuyo, Sticker of PuyoPuyo', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Super Puyo Puyo'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-55' COLLATE NOCASE),
   'Capital -> Drum Set', '001 STANDARD', 'Cowbell', NULL, 'Warning of PuyoPuyo, Ondo of PuyoPuyo', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'Super Puyo Puyo'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-55' COLLATE NOCASE),
   'Capital', '063 Synth Brass 1', NULL, NULL, 'Theme of PuyoPuyo', 'stuff_to_find', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'Super Puyo Puyo'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Yamaha' COLLATE NOCASE AND p.name = 'DX100' COLLATE NOCASE),
   'Internal -> BANK B', '06 Horns', 'To properly check', NULL, 'Sticker of PuyoPuyo', 'stuff_to_find', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'Super Puyo Puyo'),
   NULL, NULL, 'Electric Guitar', NULL, NULL, 'Final of Puyo Puyo', 'stuff_to_find', 'newer_vgm', 8),
  ((SELECT id FROM games WHERE title = 'Super Puyo Puyo'),
   NULL, NULL, 'Drums', 'Kick, Snare, Tom, Hats', NULL, '-Used throughout the soundtrack-', 'stuff_to_find', 'newer_vgm', 9),

  -- G2: Super Nazo Puyo: Rulue no Roux — 10 main + 7 stuff = 17 rows
  ((SELECT id FROM games WHERE title = 'Super Nazo Puyo: Rulue no Roux'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-55 Map', '047 000 Harp', NULL, NULL, 'Arle Area 2, Arle Area 4, Game Over', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Super Nazo Puyo: Rulue no Roux'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '001 000 Piano', NULL, NULL, 'Rulue Opening & Puzzle Editor, Arle Puzzle 1 & Practice Mode, Rulue Area 4', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Super Nazo Puyo: Rulue no Roux'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '005 016 FM+SA EP', NULL, NULL, 'Unused Track', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Super Nazo Puyo: Rulue no Roux'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '012 000 Vibraphone', NULL, NULL, '-Used throughout the soundtrack-', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Super Nazo Puyo: Rulue no Roux'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '013 000 Marimba', NULL, NULL, 'Title, Interlude ~ Arle and Rulue, Rulue Area 4', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'Super Nazo Puyo: Rulue no Roux'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '035 000 Picked Bass', NULL, NULL, '-Used throughout the soundtrack-', 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'Super Nazo Puyo: Rulue no Roux'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '049 000 Strings', NULL, NULL, '-Used throughout the soundtrack-', 'main', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'Super Nazo Puyo: Rulue no Roux'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '069 000 Oboe', NULL, NULL, 'Arle Area 4', 'main', 'newer_vgm', 8),
  ((SELECT id FROM games WHERE title = 'Super Nazo Puyo: Rulue no Roux'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '076 000 Pan Flute', NULL, NULL, 'Mode Select, Arle Area 1, Arle Area 2, Rulue Puzzle 2, Area 5 ~ Arle vs. Rulue, Unused Track', 'main', 'newer_vgm', 9),
  ((SELECT id FROM games WHERE title = 'Super Nazo Puyo: Rulue no Roux'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'TR-909' COLLATE NOCASE),
   'Internal', 'Snare Drum', 'From Kirby''s Avalanche', NULL, '-Used throughout the soundtrack-', 'main', 'newer_vgm', 10),
  ((SELECT id FROM games WHERE title = 'Super Nazo Puyo: Rulue no Roux'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Yamaha' COLLATE NOCASE AND p.name = 'MU80' COLLATE NOCASE),
   'XG Voice -> Bank 0', '017 DrawOrgn', 'To properly check; likely wrong', NULL, 'Rulue Area 3, Rulue Puzzle 2', 'stuff_to_find', 'newer_vgm', 11),
  ((SELECT id FROM games WHERE title = 'Super Nazo Puyo: Rulue no Roux'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Yamaha' COLLATE NOCASE AND p.name = 'MU80' COLLATE NOCASE),
   'XG Voice -> Bank 0', '064 SynBras2', 'To properly check; likely wrong', NULL, '-Used throughout the soundtrack-', 'stuff_to_find', 'newer_vgm', 12),
  ((SELECT id FROM games WHERE title = 'Super Nazo Puyo: Rulue no Roux'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Yamaha' COLLATE NOCASE AND p.name = 'MU80' COLLATE NOCASE),
   'XG Voice -> Bank 0', '068 Bari.Sax', 'To properly check; likely wrong', NULL, 'Mode Select, Rulue Opening & Puzzle Editor, Arle Area 1, Rulue Puzzle 3, Rulue Puzzle 4', 'stuff_to_find', 'newer_vgm', 13),
  ((SELECT id FROM games WHERE title = 'Super Nazo Puyo: Rulue no Roux'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Yamaha' COLLATE NOCASE AND p.name = 'MU80' COLLATE NOCASE),
   'XG Voice -> Bank 0', '088 Bass&Ld', 'To properly check; likely wrong', NULL, 'Rulue Opening & Puzzle Editor, Rulue Area 2, Rulue Puzzle 2', 'stuff_to_find', 'newer_vgm', 14),
  ((SELECT id FROM games WHERE title = 'Super Nazo Puyo: Rulue no Roux'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Yamaha' COLLATE NOCASE AND p.name = 'MU80' COLLATE NOCASE),
   'XG Voice -> Bank 127', '1 Standard Kit', 'To properly check; likely wrong', NULL, '-Used throughout the soundtrack-', 'stuff_to_find', 'newer_vgm', 15),
  ((SELECT id FROM games WHERE title = 'Super Nazo Puyo: Rulue no Roux'),
   NULL, NULL, 'FM EP', NULL, NULL, 'Mode Select, Rulue Opening & Puzzle Editor, Rulue Puzzle 3', 'stuff_to_find', 'newer_vgm', 16),
  ((SELECT id FROM games WHERE title = 'Super Nazo Puyo: Rulue no Roux'),
   NULL, NULL, 'Synth Stab Chord', NULL, NULL, 'Rulue Puzzle 4', 'stuff_to_find', 'newer_vgm', 17),

  -- G3: Puyo Puyo Tsuu (SEGA Saturn) — 14 main + 1 stuff = 15 rows
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Tsuu (SEGA Saturn)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-55' COLLATE NOCASE),
   'Capital', '083 Syn. Calliope', NULL, NULL, 'Floor 1', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Tsuu (SEGA Saturn)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Yamaha' COLLATE NOCASE AND p.name = 'MU80' COLLATE NOCASE),
   'XG Voice -> Bank 0', '001 GrandPno', NULL, NULL, '-Used throughout the soundtrack-', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Tsuu (SEGA Saturn)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Yamaha' COLLATE NOCASE AND p.name = 'MU80' COLLATE NOCASE),
   'XG Voice -> Bank 0', '004 HnkyTonk', NULL, NULL, 'Rally Mode Theme A', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Tsuu (SEGA Saturn)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Yamaha' COLLATE NOCASE AND p.name = 'MU80' COLLATE NOCASE),
   'XG Voice -> Bank 0', '013 Marimba', NULL, NULL, 'Floor 2 and 3', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Tsuu (SEGA Saturn)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Yamaha' COLLATE NOCASE AND p.name = 'MU80' COLLATE NOCASE),
   'XG Voice -> Bank 0', '017 DrawOrgn', NULL, NULL, 'Floor 1', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Tsuu (SEGA Saturn)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Yamaha' COLLATE NOCASE AND p.name = 'MU80' COLLATE NOCASE),
   'XG Voice -> Bank 0', '022 Accordion', NULL, NULL, 'Practice Mode', 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Tsuu (SEGA Saturn)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Yamaha' COLLATE NOCASE AND p.name = 'MU80' COLLATE NOCASE),
   'XG Voice -> Bank 0', '028 Clean Guitar', NULL, NULL, 'Floor 1', 'main', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Tsuu (SEGA Saturn)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Yamaha' COLLATE NOCASE AND p.name = 'MU80' COLLATE NOCASE),
   'XG Voice -> Bank 0', '054 VoiceOoh', NULL, NULL, 'Floor 1, Last Floor', 'main', 'newer_vgm', 8),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Tsuu (SEGA Saturn)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Yamaha' COLLATE NOCASE AND p.name = 'MU80' COLLATE NOCASE),
   'XG Voice -> Bank 0', '062 BrasSect', NULL, NULL, 'Floor 2 and 3', 'main', 'newer_vgm', 9),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Tsuu (SEGA Saturn)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Yamaha' COLLATE NOCASE AND p.name = 'MU80' COLLATE NOCASE),
   'XG Voice -> Bank 0', '105 Sitar', NULL, NULL, 'Floor 1', 'main', 'newer_vgm', 10),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Tsuu (SEGA Saturn)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Yamaha' COLLATE NOCASE AND p.name = 'MU80' COLLATE NOCASE),
   'XG Voice -> Bank 0', '106 Banjo', NULL, NULL, 'Floor 1', 'main', 'newer_vgm', 11),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Tsuu (SEGA Saturn)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Yamaha' COLLATE NOCASE AND p.name = 'MU80' COLLATE NOCASE),
   'XG Voice -> Bank 0', '109 Kalimba ', NULL, NULL, 'Selection Screen, Cutscene Theme, Floor 1', 'main', 'newer_vgm', 12),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Tsuu (SEGA Saturn)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Yamaha' COLLATE NOCASE AND p.name = 'MU80' COLLATE NOCASE),
   'XG Voice -> Bank 0', '115 SteelDrm', NULL, NULL, 'Floor 2 and 3', 'main', 'newer_vgm', 13),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Tsuu (SEGA Saturn)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Yamaha' COLLATE NOCASE AND p.name = 'MU80' COLLATE NOCASE),
   'XG Voice -> Bank 127', '1 Standard Kit', NULL, NULL, 'Floor 2 and 3', 'main', 'newer_vgm', 14),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Tsuu (SEGA Saturn)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'D-50 / U-20' COLLATE NOCASE),
   NULL, 'Living Calliope', NULL, NULL, 'Title Theme', 'stuff_to_find', 'newer_vgm', 15),

  -- G4: Super Puyo Puyo Tsuu (trailing space verbatim) — 8 main + 1 stuff = 9 rows
  ((SELECT id FROM games WHERE title = 'Super Puyo Puyo Tsuu '),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-55 Map', '013 000 Marimba', NULL, NULL, 'Title, Mode Select, Demo 1, 1st Floor, The Top Floor, Ending 2', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Super Puyo Puyo Tsuu '),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-55 Map', '015 000 Tubular-bell', NULL, NULL, 'Ending 1', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Super Puyo Puyo Tsuu '),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '012 000 Vibraphone', 'From Rulue no Roux', NULL, '-Used throughout the soundtrack-', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Super Puyo Puyo Tsuu '),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '035 000 Picked Bass', 'From Rulue no Roux', NULL, '-Used throughout the soundtrack-', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Super Puyo Puyo Tsuu '),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '049 001 Strings 2', 'Octaved', NULL, '4th and 5th Floor, Game Over, Ending 1', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'Super Puyo Puyo Tsuu '),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '062 000 Brass 1', NULL, NULL, '-Used throughout the soundtrack-', 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'Super Puyo Puyo Tsuu '),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map -> Drum Set', '001 STANDARD 1', 'Kick, tambourine', NULL, '-Used throughout the soundtrack-', 'main', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'Super Puyo Puyo Tsuu '),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map -> Drum Set', '033 JAZZ', 'Snare', NULL, '-Used throughout the soundtrack-', 'main', 'newer_vgm', 8),
  ((SELECT id FROM games WHERE title = 'Super Puyo Puyo Tsuu '),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Yamaha' COLLATE NOCASE AND p.name = 'MU80' COLLATE NOCASE),
   'XG Voice -> Bank 0', '088 Bass&Ld', 'To properly check; likely wrong', NULL, '-Used throughout the soundtrack-', 'stuff_to_find', 'newer_vgm', 9),

  -- G5: Puyo Puyo Sun (Original - Arcade) — 1 row
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (Original - Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, NULL, 'main', 'newer_vgm', 1),

  -- G6: Puyo Puyo Sun (Saturn) — 8 main rows
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (Saturn)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '005 025 Hard Rhodes', NULL, NULL, 'Rival Mode', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (Saturn)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '019 000 Organ 3', NULL, NULL, 'Rival Mode', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (Saturn)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '036 000 Fretless Bs.', NULL, NULL, 'Rival Mode', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (Saturn)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '049 001 Strings 2', NULL, NULL, 'Rival Mode', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (Saturn)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '062 000 Brass 1', NULL, NULL, 'Rival Mode', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (Saturn)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '074 000 Flute', NULL, NULL, 'Rival Mode', 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (Saturn)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map -> Drum Set', '050 ETHNIC', NULL, NULL, 'Rival Mode', 'main', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (Saturn)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map -> Drum Set', '051 KICK&SNARE', NULL, NULL, '-Used throughout the soundtrack-', 'main', 'newer_vgm', 8),

  -- G7: Puyo Puyo Sun (N64) — 57 rows, all Roland SOUND Canvas SC-88
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (N64)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '001 000 Piano 1', NULL, NULL, '-Used throughout the soundtrack-', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (N64)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '003 000 Piano 3', NULL, NULL, NULL, 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (N64)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '005 025 Hard Rhodes', NULL, NULL, 'Map, Rival Mode', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (N64)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '006 016 St.FM EP', NULL, NULL, 'Title, Normal Mode, Carbuncle, Name Entry 1, Play Result', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (N64)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '008 000 Clav.', NULL, NULL, 'Carbuncle', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (N64)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '011 000 Music Box', NULL, NULL, NULL, 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (N64)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '012 000 Vibraphone', NULL, NULL, 'Comic Dialogue ~ Rulue, Ending 1', 'main', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (N64)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '013 000 Marimba', NULL, NULL, 'Rule Explanation, Mode Select, Normal Mode, Ranking', 'main', 'newer_vgm', 8),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (N64)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '014 000 Xylophone', NULL, NULL, NULL, 'main', 'newer_vgm', 9),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (N64)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '017 016 60''s Organ 1', NULL, NULL, 'Hard Mode, Pinch', 'main', 'newer_vgm', 10),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (N64)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '018 000 Organ 2', NULL, NULL, 'Title, Hard Mode, Carbuncle', 'main', 'newer_vgm', 11),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (N64)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '019 000 Organ 3', NULL, NULL, 'Normal Mode, Rival Mode, Name Entry 1', 'main', 'newer_vgm', 12),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (N64)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '019 024 Rotary Org.F', NULL, NULL, 'Comic Dialogue ~ Rulue, Last Boss', 'main', 'newer_vgm', 13),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (N64)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '026 000 Steel-str.Gt', NULL, NULL, 'Name Entry 2', 'main', 'newer_vgm', 14),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (N64)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '028 000 Clean Gt.', NULL, NULL, 'Last Boss', 'main', 'newer_vgm', 15),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (N64)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '029 000 Muted Gt.', NULL, NULL, 'Comic Dialogue ~ Girl, Comic Dialogue ~ Weirdos, Comic Dialogue ~ Weirdos, Last Boss', 'main', 'newer_vgm', 16),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (N64)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '029 008 Funk Pop', NULL, NULL, 'Name Entry 2', 'main', 'newer_vgm', 17),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (N64)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '031 000 DistortionGt', NULL, NULL, 'Last Boss', 'main', 'newer_vgm', 18),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (N64)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '033 000 Acoustic Bs.', NULL, NULL, 'Comic Dialogue ~ Rulue, Pinch, Ending 1', 'main', 'newer_vgm', 19),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (N64)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '035 000 Picked Bass', NULL, NULL, 'Last Boss, Combat', 'main', 'newer_vgm', 20),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (N64)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '036 000 Fretless Bs.', NULL, NULL, 'Title, Rival Mode, Victory, Name Entry 2, Play Result', 'main', 'newer_vgm', 21),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (N64)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '037 000 Slap Bass 1', NULL, NULL, NULL, 'main', 'newer_vgm', 22),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (N64)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '039 000 Synth Bass 1', NULL, NULL, 'Rule Explanation', 'main', 'newer_vgm', 23),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (N64)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '039 009 TB303 Bass', NULL, NULL, NULL, 'main', 'newer_vgm', 24),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (N64)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '040 003 Seq Bass', NULL, NULL, 'Map', 'main', 'newer_vgm', 25),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (N64)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '040 008 Beef FM Bass', NULL, NULL, 'Normal Mode, Name Entry 1', 'main', 'newer_vgm', 26),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (N64)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '047 000 Harp', NULL, NULL, 'Ending 1', 'main', 'newer_vgm', 27),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (N64)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '049 000 Strings', NULL, NULL, 'Title, Last Boss, Combat, Victory, Name Entry 1, Game Over, Play Result, Ending 1, Ending 2', 'main', 'newer_vgm', 28),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (N64)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '053 000 Choir Aahs', NULL, NULL, 'Normal Mode', 'main', 'newer_vgm', 29),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (N64)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '057 000 Trumpet', NULL, NULL, 'Victory', 'main', 'newer_vgm', 30),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (N64)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '057 024 Bright Tp.', NULL, NULL, NULL, 'main', 'newer_vgm', 31),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (N64)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '058 000 Trombone', NULL, NULL, 'Comic Dialogue ~ Weirdos', 'main', 'newer_vgm', 32),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (N64)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '061 000 French Horns', NULL, NULL, 'Victory', 'main', 'newer_vgm', 33),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (N64)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '062 000 Brass 1', NULL, NULL, '-Used throughout the soundtrack-', 'main', 'newer_vgm', 34),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (N64)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '062 016 Brass Fall', NULL, NULL, 'Comic Dialogue ~ Weirdos, Easy Mode, Hard Mode', 'main', 'newer_vgm', 35),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (N64)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '063 000 Synth Brass1', NULL, NULL, 'Pinch', 'main', 'newer_vgm', 36),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (N64)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '066 000 Alto Sax', NULL, NULL, 'Comic Dialogue ~ Weirdos, Hard Mode', 'main', 'newer_vgm', 37),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (N64)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '067 000 Tenor Sax', NULL, NULL, 'Normal Mode', 'main', 'newer_vgm', 38),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (N64)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '074 000 Flute', NULL, NULL, 'Comic Dialogue ~ Rulue, Rival Mode, Victory, Ending 1', 'main', 'newer_vgm', 39),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (N64)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '076 000 Pan Flute', NULL, NULL, 'Title, Normal Mode, Play Result', 'main', 'newer_vgm', 40),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (N64)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '080 000 Ocarina', NULL, NULL, NULL, 'main', 'newer_vgm', 41),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (N64)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '081 002 Hollow Mini ', NULL, NULL, NULL, 'main', 'newer_vgm', 42),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (N64)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '081 008 Sine Wave', NULL, NULL, 'Comic Dialogue ~ Rival', 'main', 'newer_vgm', 43),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (N64)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '084 000 Chiffer Lead', NULL, NULL, 'Title, Mode Select, Normal Mode, Ending 2', 'main', 'newer_vgm', 44),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (N64)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '091 000 Polysynth', NULL, NULL, 'Map, Practice, Normal Mode, Carbuncle, Name Entry 1, Name Entry 2, Ranking, Ending 2', 'main', 'newer_vgm', 45),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (N64)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '098 001 Ancestral', NULL, NULL, 'Rule Explanation, Whole Map', 'main', 'newer_vgm', 46),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (N64)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '099 001 Syn Mallet', NULL, NULL, 'Title, Carbuncle', 'main', 'newer_vgm', 47),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (N64)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '113 016 RAMA Cymbal', NULL, NULL, NULL, 'main', 'newer_vgm', 48),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (N64)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '115 000 Steel Drums', NULL, NULL, 'Rule Explanation, Practice, Comic Dialogue ~ Weirdos, Easy Mode, Hard Mode', 'main', 'newer_vgm', 49),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (N64)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '116 000 Woodblock', NULL, NULL, NULL, 'main', 'newer_vgm', 50),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (N64)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map', '119 000 Synth Drum', NULL, NULL, 'Carbuncle', 'main', 'newer_vgm', 51),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (N64)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map -> Drum Set', '001 STANDARD ', NULL, NULL, '-Used throughout the soundtrack-', 'main', 'newer_vgm', 52),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (N64)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map -> Drum Set', '025 TR808/909', NULL, NULL, NULL, 'main', 'newer_vgm', 53),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (N64)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map -> Drum Set', '033 JAZZ', NULL, NULL, NULL, 'main', 'newer_vgm', 54),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (N64)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map -> Drum Set', '049 ORCHESTRA', NULL, NULL, 'Victory, Game Over', 'main', 'newer_vgm', 55),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (N64)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map -> Drum Set', '050 ETHNIC', NULL, NULL, NULL, 'main', 'newer_vgm', 56),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo Sun (N64)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88' COLLATE NOCASE),
   'SC-88 Map -> Drum Set', '051 KICK&SNARE', NULL, NULL, '-Used throughout the soundtrack-', 'main', 'newer_vgm', 57),

  -- G8: Puyo Puyo!! 15th Anniversary — 3 stuff_to_find rows (no main usages identified)
  ((SELECT id FROM games WHERE title = 'Puyo Puyo!! 15th Anniversary'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JV-1080' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, NULL, 'stuff_to_find', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo!! 15th Anniversary'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'XV-5080' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, NULL, 'stuff_to_find', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo!! 15th Anniversary'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'Fantom-XR' COLLATE NOCASE),
   NULL, NULL, 'May be used (See Picture)', NULL, NULL, 'stuff_to_find', 'newer_vgm', 3),

  -- G9: Puyo Puyo!! 20th Anniversary — 1 main + 2 stuff = 3 rows
  ((SELECT id FROM games WHERE title = 'Puyo Puyo!! 20th Anniversary'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Retro Funk S.A.G.E. Xpander' COLLATE NOCASE),
   '130-Mr Dynamite', '130-Mr Dynamite Fill d', NULL, NULL, 'The Puyo Puyo Song - Chiptune Mix', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo!! 20th Anniversary'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JV-1080' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, NULL, 'stuff_to_find', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo!! 20th Anniversary'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'XV-5080' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, NULL, 'stuff_to_find', 'newer_vgm', 3),

  -- G10: Puyo Puyo!! Tetris — 2 rows
  ((SELECT id FROM games WHERE title = 'Puyo Puyo!! Tetris'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'EXS24' COLLATE NOCASE),
   '02 Bass -> 02 Electric Bass', 'Slapped Electric Bass', NULL, NULL, 'Chaos Mix Difficulty', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Puyo Puyo!! Tetris'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'EXS24' COLLATE NOCASE),
   '09 Orchestral -> 09 Strings', 'String Ensemble', NULL, NULL, 'Dialogue: Something''s Wrong', 'main', 'newer_vgm', 2);
