-- NEWER VGM SEGA/Atlus — Section 3 (Daytona USA)
--
-- Source: reference/NEWER VGM Sound Sources - SEGAAtlus.csv lines 461-581.
-- 5 game records, ~105 usage rows.
--
-- Each game header is followed by a meta line "These findings are mostly
-- copied from the Daytona USA Sample Spreadsheet" — that's a provenance
-- note, not a usage row; skipped.
--
-- Cross-references / live recordings preserved verbatim per Rule 2:
--   - "Live Recording: <person> (<instrument>)" pattern — col2 in the CSV
--     describes the recorded subject (Vocals / Guitar / Sax). Stored as
--     raw_source = 'Live Recording: <person> (<instrument>)' with
--     product_id NULL.
--   - "Sample: Johnny Pate / Shaft in Africa (Addis)" (Daytona 2001 T535)
--     → raw_source preserves cross-album sample reference.
--   - "Sample: Daytona USA 2 / Crew Chief Lines" (T520) — self-reference
--     where the game samples its own in-game voice clips.
--   - "Live Recording: ???" rows (T572-573) → unknown performer preserved
--     as the literal "???".
--
-- Combined-uncertainty manufacturer/product names preserved verbatim:
--   - "AMG & Hit Music" (Norman Cook - Skip to my Loops co-publisher).
--   - "Sounds Good & Steinberg" (Hip Hop Beats & Treats co-publisher).
--   - "KORG Trinity / TR-Rack" (contributor unsure which).
--   - "Roland SC-88Pro (?)" parenthetical question mark preserved
--     (distinct from existing 'Roland / SC-88Pro' and
--     'Roland / SOUND Canvas SC-88 Pro').
--   - "E-MU Systems / Hip Hop/Phatt Collection" (forward slash in product
--     name preserved).
--   - "Ensoniq, ?" and "E-MU Systems, ?" rows → product_id NULL,
--     raw_source = '<Manufacturer> - ?'.
--
-- Conventions: per-game positions restart at 1; ?,? rows → both NULL.

INSERT OR IGNORE INTO manufacturers (name) VALUES
  ('Ensoniq'),
  ('Optical Media International'),
  ('Polestar Magnetics'),
  ('AMG & Hit Music'),
  ('Sounds Good & Steinberg');

INSERT OR IGNORE INTO products (manufacturer_id, name, type) VALUES
  ((SELECT id FROM manufacturers WHERE name = 'AKAI'                        COLLATE NOCASE), 'CD-ROM Library Vol. 1',                    'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'AKAI'                        COLLATE NOCASE), 'CD-ROM Library Vol. 2',                    'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Best Service'                COLLATE NOCASE), 'Gigapack',                                 'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'EastWest'                    COLLATE NOCASE), 'Dance/Industrial',                         'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Ensoniq'                     COLLATE NOCASE), 'VFX',                                      'Synth'),
  ((SELECT id FROM manufacturers WHERE name = 'Optical Media International' COLLATE NOCASE), 'Universe of Sounds Vol. 1',                'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Optical Media International' COLLATE NOCASE), 'Universe of Sounds Vol. 3',                'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Polestar Magnetics'          COLLATE NOCASE), 'The X-Static Goldmine',                    'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Roland'                      COLLATE NOCASE), 'R-8',                                      'Hardware'),
  ((SELECT id FROM manufacturers WHERE name = 'Roland'                      COLLATE NOCASE), 'U-110',                                    'Synth'),
  ((SELECT id FROM manufacturers WHERE name = 'Zero-G'                      COLLATE NOCASE), 'Datafile 2',                               'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'KORG'                        COLLATE NOCASE), '01/W',                                     'Synth'),
  ((SELECT id FROM manufacturers WHERE name = 'KORG'                        COLLATE NOCASE), 'Trinity / TR-Rack',                        'Synth'),
  ((SELECT id FROM manufacturers WHERE name = 'Roland'                      COLLATE NOCASE), 'JV-2080',                                  'Synth'),
  ((SELECT id FROM manufacturers WHERE name = 'Roland'                      COLLATE NOCASE), 'SR-JV80-10',                               'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Roland'                      COLLATE NOCASE), 'SC-88Pro (?)',                             'Synth'),
  ((SELECT id FROM manufacturers WHERE name = 'AMG & Hit Music'             COLLATE NOCASE), 'Norman Cook - Skip to my Loops',           'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'EastWest'                    COLLATE NOCASE), 'Steve Stevens Guitar',                     'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Roland'                      COLLATE NOCASE), 'SOUND Canvas SC-8850',                     'Synth'),
  ((SELECT id FROM manufacturers WHERE name = 'Sounds Good & Steinberg'     COLLATE NOCASE), 'Hip Hop Beats & Treats',                   'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Zero-G'                      COLLATE NOCASE), 'Jungle Warfare',                           'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'E-MU Systems'                COLLATE NOCASE), 'Hip Hop/Phatt Collection',                 'Sample Library');

INSERT INTO games (title, platform, released, composers, composers_normalized, notes) VALUES
  ('Daytona USA (Arcade)',                       'Arcade',                                          '1994-03-01', 'Takenobu Mitsuyoshi, David R. Leytze',                                                'takenobu mitsuyoshi, david r. leytze',                                                'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 3 Daytona USA). CSV release cell "(Released: March, 1994)" specifies month only; day=01 used for sort key. Findings credited to the Daytona USA Sample Spreadsheet.'),
  ('Daytona USA (Saturn)',                       'Sega Saturn',                                     '1995-04-01', 'Takenobu Mitsuyoshi, David R. Leytze',                                                'takenobu mitsuyoshi, david r. leytze',                                                'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 3 Daytona USA). Saturn port. Findings credited to the Daytona USA Sample Spreadsheet.'),
  ('Daytona USA: Championship Circuit Edition',  'Sega Saturn',                                     '1996-05-17', 'Takenobu Mitsuyoshi, Jun Senoue, Tomonori Sawada, Kenichi Tokoi, Richard Jacques',    'takenobu mitsuyoshi, jun senoue, tomonori sawada, kenichi tokoi, richard jacques',    'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 3 Daytona USA). Findings credited to the Daytona USA Sample Spreadsheet.'),
  ('Daytona USA 2 (Arcade)',                     'Arcade',                                          '1998-05-01', 'Fumio Ito, Takenobu Mitsuyoshi',                                                      'fumio ito, takenobu mitsuyoshi',                                                      'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 3 Daytona USA). CSV release cell "(Released: May, 1998)" specifies month only; day=01 used for sort key. Findings credited to the Daytona USA Sample Spreadsheet.'),
  ('Daytona USA 2001 (Dreamcast)',               'Dreamcast',                                       '2000-12-21', 'Takenobu Mitsuyoshi, Keiichi Sugiyama, Hirofumi Murasaki, Junko Shiratsu',            'takenobu mitsuyoshi, keiichi sugiyama, hirofumi murasaki, junko shiratsu',            'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 3 Daytona USA). Final entry in the Daytona arcade lineage; heavy use of the Norman Cook "Skip to my Loops" sample CD. Findings credited to the Daytona USA Sample Spreadsheet.');

INSERT INTO usages
  (game_id, product_id, path_bank, preset, notes, raw_source, examples, category, source_family, position)
VALUES
  -- G1: Daytona USA (Arcade) — 30 main + 7 stuff = 36 rows (skipping meta line 464)
  ((SELECT id FROM games WHERE title = 'Daytona USA (Arcade)'),
   NULL, NULL, NULL, NULL, 'Live Recording: Takenobu Mitsuyoshi (Vocals)', '-Used throughout the soundtrack-', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Daytona USA (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AKAI' COLLATE NOCASE AND p.name = 'CD-ROM Library Vol. 1' COLLATE NOCASE),
   'SL3057 JOHNS G', 'DIRT GTR SW', '2 E2 GTR, 11 E2 4TH', NULL, 'Let''s Go Away, Start Your Engines', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Daytona USA (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AKAI' COLLATE NOCASE AND p.name = 'CD-ROM Library Vol. 2' COLLATE NOCASE),
   '1017 G.PF #3', 'RADICAL PF', NULL, NULL, 'Let''s Go Away, David Goes to Victory Lane', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Daytona USA (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Gigapack' COLLATE NOCASE),
   'CD 2 -> PIA:PIANOS Mixe! -> PIA:Pianos-Mixe!', 'PIA:PCM Piano', 'PIA:Old Smpl 6', NULL, 'The King of Speed, Rolling Start', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Daytona USA (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Gigapack' COLLATE NOCASE),
   'CD 2 -> ORG:B-3 ORGANS -> ORG:B-3 Organs', 'ORG:B3-Organ 3', 'ORG:OF11', NULL, 'Let''s Go Away, Sky High, Pounding Pavement, "G,A,M,E,O,V,E,R,", S.K.H. (Sky High)', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'Daytona USA (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Dance/Industrial' COLLATE NOCASE),
   'Partition C -> VOLUME 006', 'HITS + EFX 2', 'FX 32, FX 34, FX 35, FX 36', NULL, 'The King of Speed, Rolling Start', 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'Daytona USA (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Dance/Industrial' COLLATE NOCASE),
   'Partition C -> VOLUME 006', 'HITS + EFX 2', 'FX 35, FX 37', NULL, 'Sky High', 'main', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'Daytona USA (Arcade)'),
   NULL, NULL, 'BRASS BLAZE', NULL, 'Ensoniq - ?', 'The King of Speed, Sky High, Rolling Start', 'main', 'newer_vgm', 8),
  ((SELECT id FROM games WHERE title = 'Daytona USA (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Optical Media International' COLLATE NOCASE AND p.name = 'Universe of Sounds Vol. 1' COLLATE NOCASE),
   'COMBO -> 123 Library Combo', 'Big Synth', 'also in E-MU EMAX library Vol. 2', NULL, NULL, 'main', 'newer_vgm', 9),
  ((SELECT id FROM games WHERE title = 'Daytona USA (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Optical Media International' COLLATE NOCASE AND p.name = 'Universe of Sounds Vol. 3' COLLATE NOCASE),
   'Electr.Lead', NULL, NULL, NULL, 'David Goes To Victory Lane', 'main', 'newer_vgm', 10),
  ((SELECT id FROM games WHERE title = 'Daytona USA (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Polestar Magnetics' COLLATE NOCASE AND p.name = 'The X-Static Goldmine' COLLATE NOCASE),
   'CD 1 -> Track 37 - TR 909 BD -> TS 0:00', 'Bass Drum 1', NULL, NULL, 'The King of Speed', 'main', 'newer_vgm', 11),
  ((SELECT id FROM games WHERE title = 'Daytona USA (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Polestar Magnetics' COLLATE NOCASE AND p.name = 'The X-Static Goldmine' COLLATE NOCASE),
   'CD 1 -> Track 38 - TR 909 SD 1 -> TS 0:00', 'Snare Drum 1', NULL, NULL, 'The King of Speed', 'main', 'newer_vgm', 12),
  ((SELECT id FROM games WHERE title = 'Daytona USA (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JD-990' COLLATE NOCASE),
   'Internal', 'I-18 Fantasia 990', NULL, NULL, 'Dreaming of Daytona USA, Bitchin''', 'main', 'newer_vgm', 13),
  ((SELECT id FROM games WHERE title = 'Daytona USA (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JD-990' COLLATE NOCASE),
   'Internal', 'I-25 Throaty Clav', NULL, NULL, 'L.G.A (Let''s Go Away)', 'main', 'newer_vgm', 14),
  ((SELECT id FROM games WHERE title = 'Daytona USA (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JD-990' COLLATE NOCASE),
   'Internal', 'I-33 MIDI Stack', NULL, NULL, NULL, 'main', 'newer_vgm', 15),
  ((SELECT id FROM games WHERE title = 'Daytona USA (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JD-990' COLLATE NOCASE),
   'PR-A', 'A-22 Ac Piano Hybrid', NULL, NULL, 'Sky High', 'main', 'newer_vgm', 16),
  ((SELECT id FROM games WHERE title = 'Daytona USA (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JD-990' COLLATE NOCASE),
   'PR-A', 'A-64 Slap Bass', NULL, NULL, 'Awaiting Other Challengers, Sky High', 'main', 'newer_vgm', 17),
  ((SELECT id FROM games WHERE title = 'Daytona USA (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'R-8' COLLATE NOCASE),
   'Internal', '53 MUTE HIGH CONGA', NULL, NULL, 'The King of Speed, Pounding Pavement, Sky High', 'main', 'newer_vgm', 18),
  ((SELECT id FROM games WHERE title = 'Daytona USA (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'R-8' COLLATE NOCASE),
   'Internal', '54 SLAP HIGH CONGA', NULL, NULL, 'The King of Speed, Pounding Pavement, Sky High', 'main', 'newer_vgm', 19),
  ((SELECT id FROM games WHERE title = 'Daytona USA (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'R-8' COLLATE NOCASE),
   'Internal', '55 OPEN LOW CONGA', NULL, NULL, 'The King of Speed, Pounding Pavement, Sky High', 'main', 'newer_vgm', 20),
  ((SELECT id FROM games WHERE title = 'Daytona USA (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'R-8' COLLATE NOCASE),
   'Internal', '56 SLIDE LOW CONGA', NULL, NULL, 'The King of Speed, Pounding Pavement, Sky High', 'main', 'newer_vgm', 21),
  ((SELECT id FROM games WHERE title = 'Daytona USA (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'R-8' COLLATE NOCASE),
   'Internal', '57 AGOGO 1', NULL, NULL, 'The King of Speed, Pounding Pavement', 'main', 'newer_vgm', 22),
  ((SELECT id FROM games WHERE title = 'Daytona USA (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'R-8' COLLATE NOCASE),
   'Internal', '57 AGOGO 2', NULL, NULL, 'The King of Speed, Pounding Pavement', 'main', 'newer_vgm', 23),
  ((SELECT id FROM games WHERE title = 'Daytona USA (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'U-110' COLLATE NOCASE),
   'Patches', 'P-14: Marimba', NULL, NULL, 'A.B (After Burner)', 'main', 'newer_vgm', 24),
  ((SELECT id FROM games WHERE title = 'Daytona USA (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'U-110' COLLATE NOCASE),
   'Patches', 'P-18: Mute Sw EG', '100% Velocity', NULL, 'The King of Speed', 'main', 'newer_vgm', 25),
  ((SELECT id FROM games WHERE title = 'Daytona USA (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'U-110' COLLATE NOCASE),
   'Patches', 'P-31: Strings', NULL, NULL, 'The King of Speed, Let''s Go Away, Sky High', 'main', 'newer_vgm', 26),
  ((SELECT id FROM games WHERE title = 'Daytona USA (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'U-110' COLLATE NOCASE),
   'Tones', 'T-47: PICKED 1', NULL, NULL, 'Let''s Go Away, Bitchin'', Sweat, Dreaming of Daytona USA', 'main', 'newer_vgm', 27),
  ((SELECT id FROM games WHERE title = 'Daytona USA (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 2' COLLATE NOCASE),
   'Track 03 - Breakbeat Live -> TS 0:25', '1 Bar', NULL, NULL, 'Start Your Engines, K.O.S. (King of Speed)', 'main', 'newer_vgm', 28),
  ((SELECT id FROM games WHERE title = 'Daytona USA (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 2' COLLATE NOCASE),
   'Track 07 - Breakbeat Live -> TS 0:32', '1 Bar', NULL, NULL, 'The King of Speed', 'main', 'newer_vgm', 29),
  ((SELECT id FROM games WHERE title = 'Daytona USA (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 2' COLLATE NOCASE),
   'Track 09 - Breakbeat Progd. -> TS 0:00', '1 Bar', NULL, NULL, 'G,A,M,E,O,V,E,R', 'main', 'newer_vgm', 30),
  ((SELECT id FROM games WHERE title = 'Daytona USA (Arcade)'),
   NULL, '?', 'Snare 1', NULL, NULL, 'Let''s Go Away', 'stuff_to_find', 'newer_vgm', 31),
  ((SELECT id FROM games WHERE title = 'Daytona USA (Arcade)'),
   NULL, '?', 'Snare 2', NULL, NULL, 'Sky High', 'stuff_to_find', 'newer_vgm', 32),
  ((SELECT id FROM games WHERE title = 'Daytona USA (Arcade)'),
   NULL, '?', 'Sync Lead', NULL, NULL, 'King of Speed', 'stuff_to_find', 'newer_vgm', 33),
  ((SELECT id FROM games WHERE title = 'Daytona USA (Arcade)'),
   NULL, '?', 'Acoustic Guitar', NULL, NULL, 'Let''s Go Away', 'stuff_to_find', 'newer_vgm', 34),
  ((SELECT id FROM games WHERE title = 'Daytona USA (Arcade)'),
   NULL, '?', 'Funk Guitar Chords', NULL, NULL, 'Sky High', 'stuff_to_find', 'newer_vgm', 35),
  ((SELECT id FROM games WHERE title = 'Daytona USA (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Ensoniq' COLLATE NOCASE AND p.name = 'VFX' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, NULL, 'stuff_to_find', 'newer_vgm', 36),
  ((SELECT id FROM games WHERE title = 'Daytona USA (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = '01/W' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, 'Let''s Go Away, Sky High', 'stuff_to_find', 'newer_vgm', 37),

  -- G2: Daytona USA (Saturn) — 6 rows (skipping meta line 504)
  ((SELECT id FROM games WHERE title = 'Daytona USA (Saturn)'),
   NULL, NULL, NULL, NULL, 'Live Recording: Takenobu Mitsuyoshi (Vocals)', '-Used throughout the soundtrack-', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Daytona USA (Saturn)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Dance/Industrial' COLLATE NOCASE),
   'Partition C -> VOLUME 006', 'HITS + EFX 2', 'FX 32, FX 34, FX 36', NULL, 'The King of Speed, Rolling Start', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Daytona USA (Saturn)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Dance/Industrial' COLLATE NOCASE),
   'Partition C -> VOLUME 006', 'HITS + EFX 2', 'FX 35, FX 37', NULL, 'Sky High, Could You Fly?', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Daytona USA (Saturn)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 2' COLLATE NOCASE),
   'Track 03 - Breakbeat Live -> TS 0:25', '1 Bar', NULL, NULL, 'Start Your Engines, K.O.S. (King of Speed)', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Daytona USA (Saturn)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 2' COLLATE NOCASE),
   'Track 07 - Breakbeat Live -> TS 0:32', '1 Bar', NULL, NULL, 'The King of Speed', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'Daytona USA (Saturn)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 2' COLLATE NOCASE),
   'Track 09 - Breakbeat Progd. -> TS 0:00', '1 Bar', NULL, NULL, 'G,A,M,E,O,V,E,R', 'main', 'newer_vgm', 6),

  -- G3: Daytona USA: Championship Circuit Edition — 3 rows
  ((SELECT id FROM games WHERE title = 'Daytona USA: Championship Circuit Edition'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JV-1080' COLLATE NOCASE),
   'PR-A', '001 64VoicePiano', 'Tone 3 Enabled', NULL, 'The Kings of Speed (Part 1), The Kings of Speed (Part 2)', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Daytona USA: Championship Circuit Edition'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JV-1080' COLLATE NOCASE),
   'PR-B', '009 Pick Bass', NULL, NULL, 'Funk Fair (Part 1), Funk Fair (Part 2)', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Daytona USA: Championship Circuit Edition'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JV-1080' COLLATE NOCASE),
   'PR-B', '091 Little Devil', NULL, NULL, 'Funk Fair (Part 1), Funk Fair (Part 2)', 'main', 'newer_vgm', 3),

  -- G4: Daytona USA 2 (Arcade) — 12 main + 1 stuff = 13 rows
  ((SELECT id FROM games WHERE title = 'Daytona USA 2 (Arcade)'),
   NULL, NULL, NULL, NULL, 'Live Recording: Dennis St. James (Vocals)', 'BATTLE ON THE EDGE, SLINGSHOT, I CAN DO IT, SKYSCRAPER SEQUENCE', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Daytona USA 2 (Arcade)'),
   NULL, NULL, NULL, 'See Note', 'Live Recording: Takenobu Mitsuyoshi (Vocals)', 'BATTLE ON THE EDGE, SLINGSHOT, I CAN DO IT, SKYSCRAPER SEQUENCE', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Daytona USA 2 (Arcade)'),
   NULL, NULL, NULL, NULL, 'Sample: Daytona USA 2 - Crew Chief Lines', 'PALM ROCK VALLEY (NO USE)', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Daytona USA 2 (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Ensoniq' COLLATE NOCASE AND p.name = 'VFX' COLLATE NOCASE),
   NULL, NULL, 'Lead Saxophone', NULL, 'PALM ROCK VALLEY (NO USE)', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Daytona USA 2 (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'Trinity / TR-Rack' COLLATE NOCASE),
   'Programs -> Bank A', 'A068 Power Chord Plus', NULL, NULL, 'HOW TO 2 (NO USE)', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'Daytona USA 2 (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SC-88Pro (?)' COLLATE NOCASE),
   'Native Mapping', 'Brass', NULL, NULL, 'HOW TO 2 (NO USE)', 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'Daytona USA 2 (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SC-88Pro' COLLATE NOCASE),
   'Native Mapping', '000 017 POWER', NULL, NULL, 'NAME ENTRY', 'main', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'Daytona USA 2 (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SC-88Pro' COLLATE NOCASE),
   'Native Mapping', '000 032 Gt. Harmonics', NULL, NULL, 'Skyscraper Sequence', 'main', 'newer_vgm', 8),
  ((SELECT id FROM games WHERE title = 'Daytona USA 2 (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JV-1080' COLLATE NOCASE),
   'PR-A', '001 64VoicePiano', NULL, NULL, 'PALM ROCK VALLEY (NO USE)', 'main', 'newer_vgm', 9),
  ((SELECT id FROM games WHERE title = 'Daytona USA 2 (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JV-1080' COLLATE NOCASE),
   'Rhythm Set -> PR-A', '001 PopDrumSet 1', NULL, NULL, 'HOW TO 2 (NO USE)', 'main', 'newer_vgm', 10),
  ((SELECT id FROM games WHERE title = 'Daytona USA 2 (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-10' COLLATE NOCASE),
   'Patch -> XP-X', '137 Rock On KIT', NULL, NULL, 'ADVANCED ENDING', 'main', 'newer_vgm', 11),
  ((SELECT id FROM games WHERE title = 'Daytona USA 2 (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-10' COLLATE NOCASE),
   'Patch -> XP-X', '116 SlapHappy 90', NULL, NULL, 'RESULT', 'main', 'newer_vgm', 12),
  ((SELECT id FROM games WHERE title = 'Daytona USA 2 (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JV-2080' COLLATE NOCASE),
   'PR-E', '082 Pulsatronic', NULL, NULL, 'SKYSCRAPER SEQUENCE', 'stuff_to_find', 'newer_vgm', 13),

  -- G5: Daytona USA 2001 (Dreamcast) — 37 main + 10 stuff = 47 rows
  ((SELECT id FROM games WHERE title = 'Daytona USA 2001 (Dreamcast)'),
   NULL, NULL, NULL, 'From Daytona USA (Saturn)', 'Live Recording: Takenobu Mitsuyoshi (Vocals)', '-Used throughout the soundtrack-', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Daytona USA 2001 (Dreamcast)'),
   NULL, NULL, 'Timestamp 0:06', 'Conga loop', 'Sample: Johnny Pate - Shaft in Africa (Addis)', 'DON''T LOOK BACK-Mirror', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Daytona USA 2001 (Dreamcast)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG & Hit Music' COLLATE NOCASE AND p.name = 'Norman Cook - Skip to my Loops' COLLATE NOCASE),
   'Track 11 - 105 BPM -> TS 0:20', 'No Sweat', NULL, NULL, 'Game Over', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Daytona USA 2001 (Dreamcast)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG & Hit Music' COLLATE NOCASE AND p.name = 'Norman Cook - Skip to my Loops' COLLATE NOCASE),
   'Track 22 - 121 BPM -> TS 0:36', 'Bassline Again', NULL, NULL, 'Greatfall in the Sky-Race', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Daytona USA 2001 (Dreamcast)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG & Hit Music' COLLATE NOCASE AND p.name = 'Norman Cook - Skip to my Loops' COLLATE NOCASE),
   'Track 24 - 124-125 BPM -> TS 1:01', 'Disco Syndrums - 125 BPM', NULL, NULL, 'Greatfall in the Sky-Race', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'Daytona USA 2001 (Dreamcast)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG & Hit Music' COLLATE NOCASE AND p.name = 'Norman Cook - Skip to my Loops' COLLATE NOCASE),
   'Track 24 - Toy Drums -> TS 0:51', 'Toy Drums 8 - 120 BPM', NULL, NULL, 'DON''T LOOK BACK-Mirror', 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'Daytona USA 2001 (Dreamcast)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG & Hit Music' COLLATE NOCASE AND p.name = 'Norman Cook - Skip to my Loops' COLLATE NOCASE),
   'Track 45 - DX Tuners -> TS 0:03', '7 DX Tuners - All twice', NULL, NULL, 'The King of Speed-Race, The King of Speed-Mirror, The King of Speed-CLEAR, The King of Speed-Ending', 'main', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'Daytona USA 2001 (Dreamcast)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG & Hit Music' COLLATE NOCASE AND p.name = 'Norman Cook - Skip to my Loops' COLLATE NOCASE),
   'Track 51 - Alphabet Soup -> TS Various', 'A-Z', 'Spells out "GAME OVER"', NULL, 'Game Over', 'main', 'newer_vgm', 8),
  ((SELECT id FROM games WHERE title = 'Daytona USA 2001 (Dreamcast)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG & Hit Music' COLLATE NOCASE AND p.name = 'Norman Cook - Skip to my Loops' COLLATE NOCASE),
   'Track 51 - Alphabet Soup -> TS Various', 'A-Z', 'Spells out "KING OF SPEED"', NULL, 'The King of Speed-Race', 'main', 'newer_vgm', 9),
  ((SELECT id FROM games WHERE title = 'Daytona USA 2001 (Dreamcast)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG & Hit Music' COLLATE NOCASE AND p.name = 'Norman Cook - Skip to my Loops' COLLATE NOCASE),
   'Track 60 - Short Ad Libs -> TS 0:04', 'Come On', NULL, NULL, 'The King of Speed-Race', 'main', 'newer_vgm', 10),
  ((SELECT id FROM games WHERE title = 'Daytona USA 2001 (Dreamcast)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG & Hit Music' COLLATE NOCASE AND p.name = 'Norman Cook - Skip to my Loops' COLLATE NOCASE),
   'Track 63 - And More -> TS 0:10', 'Go', 'See Note for Mirror', NULL, 'The King of Speed-Race, The King of Speed-Mirror, The King of Speed-CLEAR, The King of Speed-Ending', 'main', 'newer_vgm', 11),
  ((SELECT id FROM games WHERE title = 'Daytona USA 2001 (Dreamcast)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG & Hit Music' COLLATE NOCASE AND p.name = 'Norman Cook - Skip to my Loops' COLLATE NOCASE),
   'Track 64 - Vocals -> TS 0:00', 'Wooh', NULL, NULL, 'The King of Speed-Race', 'main', 'newer_vgm', 12),
  ((SELECT id FROM games WHERE title = 'Daytona USA 2001 (Dreamcast)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG & Hit Music' COLLATE NOCASE AND p.name = 'Norman Cook - Skip to my Loops' COLLATE NOCASE),
   'Track 64 - Vocals -> TS 0:19', 'Come On', NULL, NULL, 'The King of Speed-Race', 'main', 'newer_vgm', 13),
  ((SELECT id FROM games WHERE title = 'Daytona USA 2001 (Dreamcast)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG & Hit Music' COLLATE NOCASE AND p.name = 'Norman Cook - Skip to my Loops' COLLATE NOCASE),
   'Track 68 - Vox -> TS 0:14', 'Clap your hands', NULL, NULL, 'The King of Speed-Race', 'main', 'newer_vgm', 14),
  ((SELECT id FROM games WHERE title = 'Daytona USA 2001 (Dreamcast)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG & Hit Music' COLLATE NOCASE AND p.name = 'Norman Cook - Skip to my Loops' COLLATE NOCASE),
   'Track 72 - Vocals -> TS 0:22', 'Clap your hands', NULL, NULL, 'The King of Speed-Race', 'main', 'newer_vgm', 15),
  ((SELECT id FROM games WHERE title = 'Daytona USA 2001 (Dreamcast)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Steve Stevens Guitar' COLLATE NOCASE),
   'Track 12 - DIVE BOMBS -> TS 0:00', 'D', NULL, NULL, 'SPEED FRIEND-Race, SPEED FRIEND-Mirror', 'main', 'newer_vgm', 16),
  ((SELECT id FROM games WHERE title = 'Daytona USA 2001 (Dreamcast)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Steve Stevens Guitar' COLLATE NOCASE),
   'Track 13 - DIVE BOMBS -> TS 0:31', 'F', NULL, NULL, 'SPEED FRIEND-Race, SPEED FRIEND-Mirror', 'main', 'newer_vgm', 17),
  ((SELECT id FROM games WHERE title = 'Daytona USA 2001 (Dreamcast)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Steve Stevens Guitar' COLLATE NOCASE),
   'Track 14 - DIVE BOMBS -> TS 0:00', 'F', NULL, NULL, 'SPEED FRIEND-Race, SPEED FRIEND-Mirror', 'main', 'newer_vgm', 18),
  ((SELECT id FROM games WHERE title = 'Daytona USA 2001 (Dreamcast)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Steve Stevens Guitar' COLLATE NOCASE),
   'Track 14 - DIVE BOMBS -> TS 0:21', 'F', NULL, NULL, 'SPEED FRIEND-Race, SPEED FRIEND-Mirror', 'main', 'newer_vgm', 19),
  ((SELECT id FROM games WHERE title = 'Daytona USA 2001 (Dreamcast)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Steve Stevens Guitar' COLLATE NOCASE),
   'Track 14 - DIVE BOMBS -> TS 0:56', '-', NULL, NULL, 'SPEED FRIEND-Race, SPEED FRIEND-Mirror', 'main', 'newer_vgm', 20),
  ((SELECT id FROM games WHERE title = 'Daytona USA 2001 (Dreamcast)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Steve Stevens Guitar' COLLATE NOCASE),
   'Partition B ', 'CHUNG', NULL, NULL, 'SPEED FRIEND-Race, SPEED FRIEND-Mirror', 'main', 'newer_vgm', 21),
  ((SELECT id FROM games WHERE title = 'Daytona USA 2001 (Dreamcast)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JV-2080' COLLATE NOCASE),
   'PR-A', '001 64voicePiano', NULL, NULL, 'Select', 'main', 'newer_vgm', 22),
  ((SELECT id FROM games WHERE title = 'Daytona USA 2001 (Dreamcast)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JV-2080' COLLATE NOCASE),
   'PR-B', '071 Impact', NULL, NULL, 'Advertise', 'main', 'newer_vgm', 23),
  ((SELECT id FROM games WHERE title = 'Daytona USA 2001 (Dreamcast)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-8850' COLLATE NOCASE),
   'Native Mapping', '001 029 Muted Dis.Gt', 'Panned L64', NULL, 'Greatfall in the Sky-Mirror', 'main', 'newer_vgm', 24),
  ((SELECT id FROM games WHERE title = 'Daytona USA 2001 (Dreamcast)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-8850' COLLATE NOCASE),
   'Native Mapping', '006 121 Pick Scrape', NULL, NULL, 'Greatfall in the Sky-Mirror', 'main', 'newer_vgm', 25),
  ((SELECT id FROM games WHERE title = 'Daytona USA 2001 (Dreamcast)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Distorted Reality 2' COLLATE NOCASE),
   'CD 1 -> Partition A -> 01 50-69 BPM', 'INDIGENOUS', 'Pitched down 500 cents', NULL, 'Holiday in the Park-Race, Holiday in the Park-Mirror', 'main', 'newer_vgm', 26),
  ((SELECT id FROM games WHERE title = 'Daytona USA 2001 (Dreamcast)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Distorted Reality 2' COLLATE NOCASE),
   'CD 1 -> Partition A -> 02 70-79 BPM', 'SQUELCHY', 'Pitched up 200 cents', NULL, 'Holiday in the Park-Race, Holiday in the Park-Mirror', 'main', 'newer_vgm', 27),
  ((SELECT id FROM games WHERE title = 'Daytona USA 2001 (Dreamcast)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Distorted Reality 2' COLLATE NOCASE),
   'CD 1 -> Partition B -> 03 130-139 BPM', 'SWEEPSTEPZ', 'Altered Panning', NULL, 'DON''T LOOK BACK-Race, DON''T LOOK BACK-Mirror, DON''T LOOK BACK-CLEAR', 'main', 'newer_vgm', 28),
  ((SELECT id FROM games WHERE title = 'Daytona USA 2001 (Dreamcast)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sounds Good & Steinberg' COLLATE NOCASE AND p.name = 'Hip Hop Beats & Treats' COLLATE NOCASE),
   'CD 1 -> 80_SCRATCH', '080GOVER', NULL, NULL, 'Game Over', 'main', 'newer_vgm', 29),
  ((SELECT id FROM games WHERE title = 'Daytona USA 2001 (Dreamcast)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sounds Good & Steinberg' COLLATE NOCASE AND p.name = 'Hip Hop Beats & Treats' COLLATE NOCASE),
   'CD 1 -> 80_SCRATCH', '080YO', NULL, NULL, 'Greatfall in the Sky-Race, Greatfall in the Sky-GOAL', 'main', 'newer_vgm', 30),
  ((SELECT id FROM games WHERE title = 'Daytona USA 2001 (Dreamcast)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sounds Good & Steinberg' COLLATE NOCASE AND p.name = 'Hip Hop Beats & Treats' COLLATE NOCASE),
   'CD 2 -> 90_SCRATCH', '090HIT2', NULL, NULL, 'Game Over', 'main', 'newer_vgm', 31),
  ((SELECT id FROM games WHERE title = 'Daytona USA 2001 (Dreamcast)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Jungle Warfare' COLLATE NOCASE),
   'VOL 1 -> Drum Rolls', 'Drum Roll', NULL, NULL, 'Sky High-CLEAR, Sky High-Ending', 'main', 'newer_vgm', 32),
  ((SELECT id FROM games WHERE title = 'Daytona USA 2001 (Dreamcast)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Jungle Warfare' COLLATE NOCASE),
   'VOL 1 -> Straight Loops', 'Deamon 162', NULL, NULL, 'Sky High-CLEAR, Sky High-Ending', 'main', 'newer_vgm', 33),
  ((SELECT id FROM games WHERE title = 'Daytona USA 2001 (Dreamcast)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Jungle Warfare' COLLATE NOCASE),
   'VOL 1 -> Straight Loops', 'Explore 162', NULL, NULL, 'Sky High-CLEAR, Sky High-Ending', 'main', 'newer_vgm', 34),
  ((SELECT id FROM games WHERE title = 'Daytona USA 2001 (Dreamcast)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Jungle Warfare' COLLATE NOCASE),
   'VOL 1 -> Straight Loops', 'Hingz 162', NULL, NULL, 'Sky High-CLEAR, Sky High-Ending', 'main', 'newer_vgm', 35),
  ((SELECT id FROM games WHERE title = 'Daytona USA 2001 (Dreamcast)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Jungle Warfare' COLLATE NOCASE),
   'VOL 1 -> Instruments -> Special FX', 'Guitar', NULL, NULL, 'Sky High-RACE', 'main', 'newer_vgm', 36),
  ((SELECT id FROM games WHERE title = 'Daytona USA 2001 (Dreamcast)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Jungle Warfare' COLLATE NOCASE),
   'VOL 1 -> Instruments -> Special FX', 'Owl', NULL, NULL, 'Sky High-CLEAR, Sky High-Ending', 'main', 'newer_vgm', 37),
  ((SELECT id FROM games WHERE title = 'Daytona USA 2001 (Dreamcast)'),
   NULL, '-', '-', 'Guitarist for the Leads in many songs.', 'Live Recording: ??? (Electric Guitar)', 'See Note', 'stuff_to_find', 'newer_vgm', 38),
  ((SELECT id FROM games WHERE title = 'Daytona USA 2001 (Dreamcast)'),
   NULL, NULL, NULL, 'Saxophone Solo', 'Live Recording: ??? (Saxophone)', 'Sky High-Race, Sky High-Mirror', 'stuff_to_find', 'newer_vgm', 39),
  ((SELECT id FROM games WHERE title = 'Daytona USA 2001 (Dreamcast)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'E-MU Systems' COLLATE NOCASE AND p.name = 'Hip Hop/Phatt Collection' COLLATE NOCASE),
   '?', '?', 'See Note', NULL, 'Greatfall in the Sky-Race, Greatfall in the Sky-CLEAR', 'stuff_to_find', 'newer_vgm', 40),
  ((SELECT id FROM games WHERE title = 'Daytona USA 2001 (Dreamcast)'),
   NULL, '?', '?', 'Wind Chimes at the very end of the song.', 'E-MU Systems - ?', 'Sky High-Race', 'stuff_to_find', 'newer_vgm', 41),
  ((SELECT id FROM games WHERE title = 'Daytona USA 2001 (Dreamcast)'),
   NULL, '?', '?', 'Kick, Possibly.', '? (Synth)', 'Sky High-Race, Sky High-Mirror', 'stuff_to_find', 'newer_vgm', 42),
  ((SELECT id FROM games WHERE title = 'Daytona USA 2001 (Dreamcast)'),
   NULL, '?', '?', 'Kit', '? (Synth)', 'SELECT, OPTIONS', 'stuff_to_find', 'newer_vgm', 43),
  ((SELECT id FROM games WHERE title = 'Daytona USA 2001 (Dreamcast)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = '01/W' COLLATE NOCASE),
   '?', '?', 'Alan''s Run Guitar, Has not been checked.', NULL, 'Championship Demo', 'stuff_to_find', 'newer_vgm', 44),
  ((SELECT id FROM games WHERE title = 'Daytona USA 2001 (Dreamcast)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = '01/W' COLLATE NOCASE),
   '?', '?', 'Crash Cymbal, Has not been checked.', NULL, 'OPTIONS', 'stuff_to_find', 'newer_vgm', 45),
  ((SELECT id FROM games WHERE title = 'Daytona USA 2001 (Dreamcast)'),
   NULL, '?', '?', 'Drum kit', 'Roland - ?', 'Let''s Go Away-Arcade Ending2', 'stuff_to_find', 'newer_vgm', 46),
  ((SELECT id FROM games WHERE title = 'Daytona USA 2001 (Dreamcast)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-8850' COLLATE NOCASE),
   '?', '?', 'Drum Kit', NULL, 'Sky High-Race, Sky High-Mirror', 'stuff_to_find', 'newer_vgm', 47);
