-- NEWER VGM SEGA/Atlus — Sections 4-6 bundled (Virtua / SEGA Rally / NiGHTS)
--
-- Source: reference/NEWER VGM Sound Sources - SEGAAtlus.csv lines 583-723.
-- 11 game records, ~111 usage rows total. Three short franchise sections
-- bundled into one batch.
--
-- Splits made: Virtua Tennis 3 → two game records (PSP / PC), matching the
-- CSV's platform sub-headers under one game block (same handling as Puyo
-- Puyo Sun in Section 2).
--
-- Cross-album/cross-media samples preserved verbatim in raw_source:
--   - "Sample: Miles Davis - High Speed Chase" (SEGA Rally 2)
--   - "Sample: The Crystal Method - "Wild, Sweet And Cool"" (SEGA Rally 2006)
--   - "Sample: Teresa Berganza - Una voce poco fa" (NiGHTS, the Rossini aria)
--   - "Sample: 20th Century Fox - Home Alone" (NiGHTS — movie sample!)
--
-- "Roland - ? (Probably JV-1080 or XV-5080)" contributor-uncertainty rows
-- (Virtua Tennis 2, Virtua Tennis 3, SEGA Rally 2) preserved as raw_source
-- rather than as a contrived "?" product, to avoid spamming the product
-- table with placeholder rows.
--
-- Title preservation: "NiGHTS Into Dreams…" uses the U+2026 ellipsis from
-- the CSV (not three dots).

INSERT OR IGNORE INTO manufacturers (name) VALUES
  ('Crypton'),
  ('Ueberschall');

INSERT OR IGNORE INTO products (manufacturer_id, name, type) VALUES
  ((SELECT id FROM manufacturers WHERE name = 'KORG'         COLLATE NOCASE), 'T2',                                          'Synth'),
  ((SELECT id FROM manufacturers WHERE name = 'KORG'         COLLATE NOCASE), 'WAVESTATION',                                 'Synth'),
  ((SELECT id FROM manufacturers WHERE name = 'KORG'         COLLATE NOCASE), 'TRINITY',                                     'Synth'),
  ((SELECT id FROM manufacturers WHERE name = 'Roland'       COLLATE NOCASE), 'JD-800',                                      'Synth'),
  ((SELECT id FROM manufacturers WHERE name = 'Roland'       COLLATE NOCASE), 'JV-80',                                       'Synth'),
  ((SELECT id FROM manufacturers WHERE name = 'Roland'       COLLATE NOCASE), 'L-CD1',                                       'Hardware'),
  ((SELECT id FROM manufacturers WHERE name = 'Roland'       COLLATE NOCASE), 'D-70',                                        'Synth'),
  ((SELECT id FROM manufacturers WHERE name = 'EastWest'     COLLATE NOCASE), 'Dance/Industrial II',                         'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'EastWest'     COLLATE NOCASE), 'Jeff Skunk Baxter Skunkworks',                'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Crypton'      COLLATE NOCASE), 'Drumbase 5000',                               'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Ueberschall'  COLLATE NOCASE), 'Big Beat',                                    'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Ueberschall'  COLLATE NOCASE), 'Easy Listening',                              'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Ueberschall'  COLLATE NOCASE), 'Brazil Electro',                              'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Best Service' COLLATE NOCASE), 'Sound Cube Vol. 2 - Orchestra & Classic',     'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Steinberg'    COLLATE NOCASE), 'Virtual Guitarist 2',                         'Instrument'),
  ((SELECT id FROM manufacturers WHERE name = 'Zero-G'       COLLATE NOCASE), 'Datafile 1',                                  'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Zero-G'       COLLATE NOCASE), 'Ethnic',                                      'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Zero-G'       COLLATE NOCASE), 'EZ Rollers Drum & Bass Producer Pack',        'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Zero-G'       COLLATE NOCASE), 'Jungle Frenzy',                               'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Ensoniq'      COLLATE NOCASE), 'SQ-R',                                        'Synth'),
  ((SELECT id FROM manufacturers WHERE name = 'Spectrasonics' COLLATE NOCASE), 'Burning Grooves',                            'Sample Library');

INSERT INTO games (title, platform, released, composers, composers_normalized, notes) VALUES
  ('Virtua Fighter',                              'Arcade',                                                  '1993-10-01', NULL,                  NULL,                  'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 4 Virtua). CSV release cell "(Released: October, 1993)" — month only; day=01 used as sort key.'),
  ('Virtua Fighter 2',                            'Arcade',                                                  '1994-11-01', NULL,                  NULL,                  'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 4 Virtua). CSV release cell "(Released: November, 1994)" — month only; day=01 used as sort key. Only 1 source row in CSV (Zero-G Datafile 1 wolf call).'),
  ('Virtua Tennis 2/Tennis 2K2',                  'PlayStation 2, Arcade',                                   '2001-01-08', NULL,                  NULL,                  'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 4 Virtua). Title preserved verbatim with "2/Tennis 2K2" dual naming from the CSV.'),
  ('Virtua Tennis 3 (PSP)',                       'PlayStation Portable',                                    '2007-03-20', NULL,                  NULL,                  'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 4 Virtua). Split from "Virtua Tennis 3" by platform sub-header in CSV; PSP version has its own stuff_to_find rows.'),
  ('Virtua Tennis 3 (PC)',                        'PC',                                                      '2007-03-20', NULL,                  NULL,                  'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 4 Virtua). PC version split from "Virtua Tennis 3" — CSV implies different music between PSP and PC builds.'),
  ('SEGA Rally Championship (SEGA Saturn)',       'Sega Saturn',                                             '1995-11-18', NULL,                  NULL,                  'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 5 SEGA Rally). Saturn port; arcade original predates this entry.'),
  ('Sega Rally 2 (SEGA Dreamcast)',               'Sega Dreamcast',                                          '1999-01-28', 'Hideki Naganuma',     'hideki naganuma',     'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 5 SEGA Rally). The only entry in this section with an explicit "(Music by:" credit in the CSV.'),
  ('Sega Rally 2006',                             'PlayStation 2',                                           '2006-01-12', NULL,                  NULL,                  'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 5 SEGA Rally). JP-only PS2 release.'),
  ('NiGHTS Into Dreams…',                         'Sega Saturn',                                             '1996-07-05', NULL,                  NULL,                  'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 6 NiGHTS). Title preserves the U+2026 ellipsis character verbatim from the CSV. Notable cross-media sample: Home Alone (20th Century Fox) used in "Gate of Your Dream".'),
  ('Christmas NiGHTS',                            'Sega Saturn',                                             '1996-11-22', NULL,                  NULL,                  'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 6 NiGHTS). Holiday-themed standalone demo distributed via SEGA Saturn Magazine.'),
  ('NiGHTS: Journey of Dreams',                   'Wii',                                                     '2007-12-13', NULL,                  NULL,                  'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 6 NiGHTS). Wii sequel — heavy reliance on Best Service and Ueberschall sample libraries.');

INSERT INTO usages
  (game_id, product_id, path_bank, preset, notes, raw_source, examples, category, source_family, position)
VALUES
  -- ====== Section 4 - Virtua Series ======

  -- G1: Virtua Fighter — 3 main + 1 stuff = 4 rows
  ((SELECT id FROM games WHERE title = 'Virtua Fighter'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Dance/Industrial' COLLATE NOCASE),
   'Partition C -> VOLUME 005', 'HITS + EFX 1', 'FX18, FX20, FX21, FX22, FX23', NULL, 'Ending / Ending 4', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Virtua Fighter'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'T2' COLLATE NOCASE),
   'PROG A', 'A01 Piano16''', NULL, NULL, 'Too many to count', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Virtua Fighter'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88 Pro' COLLATE NOCASE),
   'Native Map -> Drum set', '050 Ethnic', NULL, NULL, 'Jacky, Pai', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Virtua Fighter'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = '01/W' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, NULL, 'stuff_to_find', 'newer_vgm', 4),

  -- G2: Virtua Fighter 2 — 1 row
  ((SELECT id FROM games WHERE title = 'Virtua Fighter 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 1' COLLATE NOCASE),
   'Track 35 - Primitive animal FX -> TS 0:22', 'wolf call no. 1', NULL, NULL, 'Black Cat Moon', 'main', 'newer_vgm', 1),

  -- G3: Virtua Tennis 2/Tennis 2K2 — 4 stuff_to_find rows (no main usages)
  ((SELECT id FROM games WHERE title = 'Virtua Tennis 2/Tennis 2K2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Burning Grooves' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, '~Used through the soundtrack~', 'stuff_to_find', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Virtua Tennis 2/Tennis 2K2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'Classic Stylus', '?', NULL, NULL, '~Used through the soundtrack~', 'stuff_to_find', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Virtua Tennis 2/Tennis 2K2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, '~Used through the soundtrack~', 'stuff_to_find', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Virtua Tennis 2/Tennis 2K2'),
   NULL, NULL, NULL, NULL, 'Roland - ? (Probably JV-1080 or XV-5080)', '~Used through the soundtrack~', 'stuff_to_find', 'newer_vgm', 4),

  -- G4: Virtua Tennis 3 (PSP) — 3 stuff_to_find rows
  ((SELECT id FROM games WHERE title = 'Virtua Tennis 3 (PSP)'),
   NULL, NULL, NULL, 'Impact Hit', 'Roland - ? (Probably JV-1080 or XV-5080)', 'Unsure about names, ost seem to be a mix of new tracks and from older games, but it plays on Singles Exhibitions', 'stuff_to_find', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Virtua Tennis 3 (PSP)'),
   NULL, NULL, 'Amen Break', 'Derivation', NULL, 'Game 04, Game 07, Select', 'stuff_to_find', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Virtua Tennis 3 (PSP)'),
   NULL, NULL, 'Guitar loop with phaser', 'Guitar also in Budokai 3''s character select', NULL, 'Select', 'stuff_to_find', 'newer_vgm', 3),

  -- G5: Virtua Tennis 3 (PC) — 2 stuff_to_find rows
  ((SELECT id FROM games WHERE title = 'Virtua Tennis 3 (PC)'),
   NULL, NULL, NULL, 'Techno Hit', 'Roland - ? (Probably JV-1080 or XV-5080)', 'Vancouver Open Stage,  Buenos Aires', 'stuff_to_find', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Virtua Tennis 3 (PC)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'Classic Stylus -> ?', '?', NULL, NULL, 'Buenos Aires', 'stuff_to_find', 'newer_vgm', 2),

  -- ====== Section 5 - SEGA Rally ======

  -- G6: SEGA Rally Championship (SEGA Saturn) — 16 main + 1 stuff = 17 rows
  ((SELECT id FROM games WHERE title = 'SEGA Rally Championship (SEGA Saturn)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = '01/W' COLLATE NOCASE),
   'PROG', 'A59 Orch Hit', NULL, NULL, 'POWER GAMES, FANFARE', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'SEGA Rally Championship (SEGA Saturn)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = '01/W' COLLATE NOCASE),
   'PROG', 'A83 Flute', NULL, NULL, 'FOREST REPLAY ~evaluation~, LAKE SIDE REPLAY', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'SEGA Rally Championship (SEGA Saturn)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = '01/W' COLLATE NOCASE),
   'PROG', 'B13 SopranoSax', NULL, NULL, 'LAKE SIDE REPLAY', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'SEGA Rally Championship (SEGA Saturn)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = '01/W' COLLATE NOCASE),
   'PROG', 'B61 Gospel Org', NULL, NULL, 'MOUNTAIN REPLAY ~evaluation~', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'SEGA Rally Championship (SEGA Saturn)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Polestar Magnetics' COLLATE NOCASE AND p.name = 'The X-Static Goldmine' COLLATE NOCASE),
   'CD 2 -> Track 14 - FAT BASS 1 -> TS 0:20', 'Fat Pro 3', NULL, NULL, 'RESULT', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'SEGA Rally Championship (SEGA Saturn)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JD-800' COLLATE NOCASE),
   NULL, 'I-13: Crystal Rhodes', NULL, NULL, 'LAKE SIDE REPLAY', 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'SEGA Rally Championship (SEGA Saturn)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JD-800' COLLATE NOCASE),
   NULL, 'I-53: Ac Piano 1', NULL, NULL, 'ARCADE SELECT, DESERT REPLAY ~evaluation~, LAKE SIDE REPLAY', 'main', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'SEGA Rally Championship (SEGA Saturn)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JD-990' COLLATE NOCASE),
   'PR-A', 'A-63 Velo Switch Bass', NULL, NULL, 'POWER GAMES', 'main', 'newer_vgm', 8),
  ((SELECT id FROM games WHERE title = 'SEGA Rally Championship (SEGA Saturn)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JV-80' COLLATE NOCASE),
   'Internal', 'I44 Fantasia JV', NULL, NULL, 'POWER GAMES', 'main', 'newer_vgm', 9),
  ((SELECT id FROM games WHERE title = 'SEGA Rally Championship (SEGA Saturn)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JV-80' COLLATE NOCASE),
   'Preset A', 'A15 Pop Piano 2', NULL, NULL, 'FOREST REPLAY ~evaluation~', 'main', 'newer_vgm', 10),
  ((SELECT id FROM games WHERE title = 'SEGA Rally Championship (SEGA Saturn)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JV-80' COLLATE NOCASE),
   'Preset A', 'A47 Jazz Organ 2', NULL, NULL, 'FOREST REPLAY ~evaluation~', 'main', 'newer_vgm', 11),
  ((SELECT id FROM games WHERE title = 'SEGA Rally Championship (SEGA Saturn)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JV-80' COLLATE NOCASE),
   'Preset A', 'A73 Woody Bass 1', NULL, NULL, 'FOREST REPLAY ~evaluation~', 'main', 'newer_vgm', 12),
  ((SELECT id FROM games WHERE title = 'SEGA Rally Championship (SEGA Saturn)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JV-80' COLLATE NOCASE),
   'Preset B', 'B46 Brass Sect 1', NULL, NULL, 'LAKE SIDE REPLAY, etc.', 'main', 'newer_vgm', 13),
  ((SELECT id FROM games WHERE title = 'SEGA Rally Championship (SEGA Saturn)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JV-80' COLLATE NOCASE),
   'Preset B', 'B47 Brass Sect 2', NULL, NULL, 'MOUNTAIN REPLAY ~evaluation~', 'main', 'newer_vgm', 14),
  ((SELECT id FROM games WHERE title = 'SEGA Rally Championship (SEGA Saturn)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'L-CD1' COLLATE NOCASE),
   'Orchestra #1', 'P13 Orchestra 3', NULL, NULL, 'POWER GAMES', 'main', 'newer_vgm', 15),
  ((SELECT id FROM games WHERE title = 'SEGA Rally Championship (SEGA Saturn)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 2' COLLATE NOCASE),
   'Track 05 - Breakbeat Live -> TS 0:00', '1 Bar', NULL, NULL, 'POWER GAMES', 'main', 'newer_vgm', 16),
  ((SELECT id FROM games WHERE title = 'SEGA Rally Championship (SEGA Saturn)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Polestar Magnetics' COLLATE NOCASE AND p.name = 'The X-Static Goldmine' COLLATE NOCASE),
   NULL, NULL, 'TR-909 drums', NULL, 'RESULT', 'stuff_to_find', 'newer_vgm', 17),

  -- G7: Sega Rally 2 (SEGA Dreamcast) — 9 main + 1 stuff = 10 rows
  ((SELECT id FROM games WHERE title = 'Sega Rally 2 (SEGA Dreamcast)'),
   NULL, NULL, 'Timestamp 0:00', 'Horn Sustain', 'Sample: Miles Davis - High Speed Chase', 'Drive Me Mad, Groove Rally #1, Groove Rally #2', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Sega Rally 2 (SEGA Dreamcast)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Dance/Industrial' COLLATE NOCASE),
   'Track 16 -> TS 0:26', NULL, NULL, NULL, 'Drive Me Mad, Groove Rally #1', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Sega Rally 2 (SEGA Dreamcast)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Dance/Industrial II' COLLATE NOCASE),
   'Demo Track', 'Timestamp 0:27', 'Hit', NULL, 'Groove Rally #1, Groove Rally #2', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Sega Rally 2 (SEGA Dreamcast)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'TRINITY' COLLATE NOCASE),
   'Programs -> Bank A', 'A040 !{Mega-Mix}! Kit', NULL, NULL, 'Drive Me Mad', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Sega Rally 2 (SEGA Dreamcast)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'TRINITY' COLLATE NOCASE),
   'Programs -> Bank A', '059 Future Synth', NULL, NULL, 'Drive Me Mad, Drive Me Mad For Select', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'Sega Rally 2 (SEGA Dreamcast)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Jungle Warfare' COLLATE NOCASE),
   'Straight Loops ', 'Copta 162', NULL, NULL, 'Drive Me Mad', 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'Sega Rally 2 (SEGA Dreamcast)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Jungle Warfare' COLLATE NOCASE),
   'Straight Loops ', 'Raw 162', NULL, NULL, 'Drive Me Mad', 'main', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'Sega Rally 2 (SEGA Dreamcast)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Jungle Warfare' COLLATE NOCASE),
   'Straight Loops ', 'Silver 162', NULL, NULL, 'Drive Me Mad', 'main', 'newer_vgm', 8),
  ((SELECT id FROM games WHERE title = 'Sega Rally 2 (SEGA Dreamcast)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Jungle Warfare' COLLATE NOCASE),
   'Instruments -> Sampled Notes', 'Zap 1', NULL, NULL, 'Drive Me Mad', 'main', 'newer_vgm', 9),
  ((SELECT id FROM games WHERE title = 'Sega Rally 2 (SEGA Dreamcast)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JV-1080' COLLATE NOCASE),
   NULL, NULL, 'Impact Hits', NULL, 'King of Island', 'stuff_to_find', 'newer_vgm', 10),

  -- G8: Sega Rally 2006 — 11 main rows
  ((SELECT id FROM games WHERE title = 'Sega Rally 2006'),
   NULL, NULL, 'Timestamp 0:02', 'Bass', 'Sample: The Crystal Method - "Wild, Sweet And Cool"', 'BOOSTED', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Sega Rally 2006'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Big Fish Audio' COLLATE NOCASE AND p.name = 'Electric Ghetto' COLLATE NOCASE),
   'Disc 2 -> 05 150 Emin', 'drums01', NULL, NULL, 'Blazing', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Sega Rally 2006'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Big Fish Audio' COLLATE NOCASE AND p.name = 'Electric Ghetto' COLLATE NOCASE),
   'Disc 2 -> 05 150 Emin', 'drums02', NULL, NULL, 'Blazing', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Sega Rally 2006'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Jeff Skunk Baxter Skunkworks' COLLATE NOCASE),
   '61 Slow Blues', '61-126-G-SlideRhythm', NULL, NULL, 'BOOSTED', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Sega Rally 2006'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-12 Hip Hop Collection' COLLATE NOCASE),
   'XP-X', '176 Lo-Fi Hits', NULL, NULL, 'Steppin Pedal', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'Sega Rally 2006'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Ueberschall' COLLATE NOCASE AND p.name = 'Big Beat' COLLATE NOCASE),
   'Track 04 - Drum-Loops I -> TS 0:00', 'smack my bitch 140', NULL, NULL, 'BOOSTED', 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'Sega Rally 2006'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Ueberschall' COLLATE NOCASE AND p.name = 'Big Beat' COLLATE NOCASE),
   'Track 04 - Drum-Loops I -> TS 0:05', 'smack my bitch 140', NULL, NULL, 'BOOSTED', 'main', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'Sega Rally 2006'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Ueberschall' COLLATE NOCASE AND p.name = 'Big Beat' COLLATE NOCASE),
   'Track 04 - Drum-Loops I -> TS 0:12', 'smack my bitch 140', NULL, NULL, 'BOOSTED', 'main', 'newer_vgm', 8),
  ((SELECT id FROM games WHERE title = 'Sega Rally 2006'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Ueberschall' COLLATE NOCASE AND p.name = 'Big Beat' COLLATE NOCASE),
   'Track 70 - Guitars -> TS 0:00', 'rock''n''roll highschool 120', NULL, NULL, 'BOOSTED', 'main', 'newer_vgm', 9),
  ((SELECT id FROM games WHERE title = 'Sega Rally 2006'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Ueberschall' COLLATE NOCASE AND p.name = 'Easy Listening' COLLATE NOCASE),
   'Track 27 -> TS 0:05', 'Effect Hit', NULL, NULL, 'BOOSTED', 'main', 'newer_vgm', 10),
  ((SELECT id FROM games WHERE title = 'Sega Rally 2006'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Chemical Beats' COLLATE NOCASE),
   NULL, '096-FX Loop 09', NULL, NULL, 'BOOSTED', 'main', 'newer_vgm', 11),

  -- ====== Section 6 - NiGHTS Series ======

  -- G9: NiGHTS Into Dreams… — 37 main + 8 stuff = 45 rows
  ((SELECT id FROM games WHERE title = 'NiGHTS Into Dreams…'),
   NULL, NULL, NULL, NULL, 'Sample: Teresa Berganza - Una voce poco fa', 'She Had Long Ears', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'NiGHTS Into Dreams…'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Crypton' COLLATE NOCASE AND p.name = 'Drumbase 5000' COLLATE NOCASE),
   'Partition B -> DANCE KIT #3', 'H33 02', NULL, NULL, 'The Dragon Gave a Loud Scream', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'NiGHTS Into Dreams…'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Crypton' COLLATE NOCASE AND p.name = 'Drumbase 5000' COLLATE NOCASE),
   'Partition E -> BREAKBEATS#1', 'BREAKBEATS 1', 'EDIT BEAT, MASTERGROOVE', NULL, 'Message From Nightopia', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'NiGHTS Into Dreams…'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Crypton' COLLATE NOCASE AND p.name = 'Drumbase 5000' COLLATE NOCASE),
   'Partition I -> ORCHESTRAHIT', 'HITS 1-1', '1208HITSYN, ORCH 06', NULL, 'NiGHTS and Reala, NiGHTS and Reala : Theme of a Tragedic Revenge', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'NiGHTS Into Dreams…'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Crypton' COLLATE NOCASE AND p.name = 'Drumbase 5000' COLLATE NOCASE),
   'Partition I -> ORCHESTRAHIT', 'HITS 1-2', '0408HIT', NULL, 'NiGHTS and Reala, NiGHTS and Reala : Theme of a Tragedic Revenge', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'NiGHTS Into Dreams…'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = '01/W' COLLATE NOCASE),
   'PROG -> Bank A', 'A00 Ephemerals', NULL, NULL, 'The Dragon Gave a Loud Scream', 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'NiGHTS Into Dreams…'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = '01/W' COLLATE NOCASE),
   'PROG -> Bank A', 'A05 VS Bells 1', NULL, NULL, 'After the Dream, <EVENT> Score The Goal!', 'main', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'NiGHTS Into Dreams…'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = '01/W' COLLATE NOCASE),
   'PROG -> Bank A', 'A13 Alto Sax', NULL, NULL, 'NiGHTS and Reala', 'main', 'newer_vgm', 8),
  ((SELECT id FROM games WHERE title = 'NiGHTS Into Dreams…'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = '01/W' COLLATE NOCASE),
   'PROG -> Bank A', 'A27 Analog Pad', NULL, NULL, 'After the Dream', 'main', 'newer_vgm', 9),
  ((SELECT id FROM games WHERE title = 'NiGHTS Into Dreams…'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = '01/W' COLLATE NOCASE),
   'PROG -> Bank A', 'A32 FrHrn&Tuba', NULL, NULL, 'Paternal Horn : Complete Ver.', 'main', 'newer_vgm', 10),
  ((SELECT id FROM games WHERE title = 'NiGHTS Into Dreams…'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = '01/W' COLLATE NOCASE),
   'PROG -> Bank A', 'A40 FreeFlight', NULL, NULL, 'Message From Nightopia', 'main', 'newer_vgm', 11),
  ((SELECT id FROM games WHERE title = 'NiGHTS Into Dreams…'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = '01/W' COLLATE NOCASE),
   'PROG -> Bank A', 'A43 Harmonica', NULL, NULL, 'Paternal Horn : Complete Ver., After the Dream', 'main', 'newer_vgm', 12),
  ((SELECT id FROM games WHERE title = 'NiGHTS Into Dreams…'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = '01/W' COLLATE NOCASE),
   'PROG -> Bank A', 'A50 DesertDawn', NULL, NULL, 'NiGHTS and Reala, NiGHTS and Reala : Theme of a Tragedic Revenge', 'main', 'newer_vgm', 13),
  ((SELECT id FROM games WHERE title = 'NiGHTS Into Dreams…'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = '01/W' COLLATE NOCASE),
   'PROG -> Bank A', 'A82 Muted Trpt', NULL, NULL, 'Gloom of The N.H.C. : Complete Ver.', 'main', 'newer_vgm', 14),
  ((SELECT id FROM games WHERE title = 'NiGHTS Into Dreams…'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = '01/W' COLLATE NOCASE),
   'PROG -> Bank A', 'A83 Flute', NULL, NULL, 'After the Dream', 'main', 'newer_vgm', 15),
  ((SELECT id FROM games WHERE title = 'NiGHTS Into Dreams…'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = '01/W' COLLATE NOCASE),
   'PROG -> Bank B', 'B01 Piano 8''', NULL, NULL, '<EVENT> Score The Goal!', 'main', 'newer_vgm', 16),
  ((SELECT id FROM games WHERE title = 'NiGHTS Into Dreams…'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = '01/W' COLLATE NOCASE),
   'PROG -> Bank B', 'B07 YourString', NULL, NULL, 'The Dragon Gave a Loud Scream', 'main', 'newer_vgm', 17),
  ((SELECT id FROM games WHERE title = 'NiGHTS Into Dreams…'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = '01/W' COLLATE NOCASE),
   'PROG -> Bank B', 'B11 DigiPiano2', NULL, NULL, 'The Dragon Gave a Loud Scream', 'main', 'newer_vgm', 18),
  ((SELECT id FROM games WHERE title = 'NiGHTS Into Dreams…'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = '01/W' COLLATE NOCASE),
   'PROG -> Bank B', 'B29 Percussion', NULL, NULL, 'After the Dream, The Dragon Gave a Loud Scream', 'main', 'newer_vgm', 19),
  ((SELECT id FROM games WHERE title = 'NiGHTS Into Dreams…'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = '01/W' COLLATE NOCASE),
   'PROG -> Bank B', 'B39 Timpani', NULL, NULL, '<JINGLE> Mare Over', 'main', 'newer_vgm', 20),
  ((SELECT id FROM games WHERE title = 'NiGHTS Into Dreams…'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = '01/W' COLLATE NOCASE),
   'PROG -> Bank B', 'B43 Musette', NULL, NULL, 'Paternal Horn : Complete Ver., After the Dream, Take The Snow Train : Complete Ver.', 'main', 'newer_vgm', 21),
  ((SELECT id FROM games WHERE title = 'NiGHTS Into Dreams…'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = '01/W' COLLATE NOCASE),
   'PROG -> Bank B', 'B57 Pizzicato', NULL, NULL, 'She Had Long Ears', 'main', 'newer_vgm', 22),
  ((SELECT id FROM games WHERE title = 'NiGHTS Into Dreams…'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = '01/W' COLLATE NOCASE),
   'PROG -> Bank B', 'B93 Scotland', NULL, NULL, 'Suburban Museum : Complete Ver.', 'main', 'newer_vgm', 23),
  ((SELECT id FROM games WHERE title = 'NiGHTS Into Dreams…'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'WAVESTATION' COLLATE NOCASE),
   'RAM2 -> Performances', '39 Ivesian Split', NULL, NULL, '<EVENT> Dreaming Youngsters : Claris Ver.', 'main', 'newer_vgm', 24),
  ((SELECT id FROM games WHERE title = 'NiGHTS Into Dreams…'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Polestar Magnetics' COLLATE NOCASE AND p.name = 'The X-Static Goldmine' COLLATE NOCASE),
   'CD1 -> Track 14 - Clonk -> TS 0:10', '1 Bar', 'pitched up +1 semitone', NULL, 'NiGHTS and Reala : Theme of a Tragedic Revenge', 'main', 'newer_vgm', 25),
  ((SELECT id FROM games WHERE title = 'NiGHTS Into Dreams…'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'D-70' COLLATE NOCASE),
   'PATCH -> A', 'A23 JP–Strings', NULL, NULL, 'The Dragon Gave a Loud Scream', 'main', 'newer_vgm', 26),
  ((SELECT id FROM games WHERE title = 'NiGHTS Into Dreams…'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'D-70' COLLATE NOCASE),
   'PATCH -> A', 'A28 Calliopead', NULL, NULL, 'Take The Snow Train : Complete Ver.', 'main', 'newer_vgm', 27),
  ((SELECT id FROM games WHERE title = 'NiGHTS Into Dreams…'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JD-800' COLLATE NOCASE),
   'Internal', 'I-13: Crystal Rhodes', 'Could also be JD-990', NULL, 'After the Dream', 'main', 'newer_vgm', 28),
  ((SELECT id FROM games WHERE title = 'NiGHTS Into Dreams…'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JD-800' COLLATE NOCASE),
   'Internal', 'I-34: Wet Bass', NULL, NULL, 'NiGHTS and Reala', 'main', 'newer_vgm', 29),
  ((SELECT id FROM games WHERE title = 'NiGHTS Into Dreams…'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JD-800' COLLATE NOCASE),
   'Internal', 'I-53: Ac Piano 1', NULL, NULL, 'Paternal Horn : Complete Ver.', 'main', 'newer_vgm', 30),
  ((SELECT id FROM games WHERE title = 'NiGHTS Into Dreams…'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JD-800' COLLATE NOCASE),
   'Internal', 'I-64: Synth Pipe Solo', NULL, NULL, 'The Dragon Gave a Loud Scream', 'main', 'newer_vgm', 31),
  ((SELECT id FROM games WHERE title = 'NiGHTS Into Dreams…'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JD-800' COLLATE NOCASE),
   'Preset A', '4-8 Harlequin', 'Could also be JD-990', NULL, 'Pia Over', 'main', 'newer_vgm', 32),
  ((SELECT id FROM games WHERE title = 'NiGHTS Into Dreams…'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JD-990' COLLATE NOCASE),
   'Preset A', 'A-17 Cherish', NULL, NULL, 'After the Dream', 'main', 'newer_vgm', 33),
  ((SELECT id FROM games WHERE title = 'NiGHTS Into Dreams…'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JD-990' COLLATE NOCASE),
   'Preset A', 'A-45 Nylon Guitar', NULL, NULL, 'Deep It Lies, Dreams Dreams : In Silent Memory', 'main', 'newer_vgm', 34),
  ((SELECT id FROM games WHERE title = 'NiGHTS Into Dreams…'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JD-990' COLLATE NOCASE),
   'Preset B', 'B-21 Brass Section', NULL, NULL, 'Paternal Horn : Complete Ver.', 'main', 'newer_vgm', 35),
  ((SELECT id FROM games WHERE title = 'NiGHTS Into Dreams…'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 2' COLLATE NOCASE),
   'Track 05 - Breakbeat Live -> TS 0:00', '1 Bar', NULL, NULL, 'The Amazing Water : Complete Ver.', 'main', 'newer_vgm', 36),
  ((SELECT id FROM games WHERE title = 'NiGHTS Into Dreams…'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Ethnic' COLLATE NOCASE),
   'Track 39 - ETHNIC TECHNO HOUSE -> TS 1:04', 'Ethno Tech 9 - Timbales, Congas', NULL, NULL, 'Message From Nightopia', 'main', 'newer_vgm', 37),
  ((SELECT id FROM games WHERE title = 'NiGHTS Into Dreams…'),
   NULL, NULL, 'Timestamp 19:30', NULL, 'Sample: 20th Century Fox - Home Alone', 'Gate of Your Dream', 'stuff_to_find', 'newer_vgm', 38),
  ((SELECT id FROM games WHERE title = 'NiGHTS Into Dreams…'),
   NULL, NULL, NULL, NULL, 'E-MU Systems - ?', NULL, 'stuff_to_find', 'newer_vgm', 39),
  ((SELECT id FROM games WHERE title = 'NiGHTS Into Dreams…'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Ensoniq' COLLATE NOCASE AND p.name = 'SQ-R' COLLATE NOCASE),
   NULL, NULL, 'Dance piano', NULL, 'NiGHTS and Reala', 'stuff_to_find', 'newer_vgm', 40),
  ((SELECT id FROM games WHERE title = 'NiGHTS Into Dreams…'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Polestar Magnetics' COLLATE NOCASE AND p.name = 'The X-Static Goldmine' COLLATE NOCASE),
   NULL, NULL, 'TR-909 drums', NULL, 'Gloom of The N.H.C. : Complete Ver.', 'stuff_to_find', 'newer_vgm', 41),
  ((SELECT id FROM games WHERE title = 'NiGHTS Into Dreams…'),
   NULL, NULL, NULL, 'Harmonica', 'Roland - ?', 'She Had Long Ears', 'stuff_to_find', 'newer_vgm', 42),
  ((SELECT id FROM games WHERE title = 'NiGHTS Into Dreams…'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JV-1080' COLLATE NOCASE),
   NULL, NULL, 'Sweeping synth', NULL, 'After the Dream (Saturn Version)', 'stuff_to_find', 'newer_vgm', 43),
  ((SELECT id FROM games WHERE title = 'NiGHTS Into Dreams…'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JV-1080' COLLATE NOCASE),
   NULL, NULL, 'GM Honky Tonk', NULL, 'Gloom of The N.H.C. : Complete Ver.', 'stuff_to_find', 'newer_vgm', 44),
  ((SELECT id FROM games WHERE title = 'NiGHTS Into Dreams…'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = '01/W' COLLATE NOCASE),
   NULL, NULL, 'Acoustic Upright Bass', NULL, 'Gloom of The N.H.C. : Complete Ver.', 'stuff_to_find', 'newer_vgm', 45),

  -- G10: Christmas NiGHTS — 4 main + 1 stuff = 5 rows
  ((SELECT id FROM games WHERE title = 'Christmas NiGHTS'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = '01/W' COLLATE NOCASE),
   'PROG -> Bank B', 'B39 Timpani', NULL, NULL, 'Rolling Eggman', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Christmas NiGHTS'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JD-800' COLLATE NOCASE),
   NULL, 'I-53: Ac Piano 1', NULL, NULL, 'Dreams Dreams : Sweet Mix in Holy Night', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Christmas NiGHTS'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JV-80' COLLATE NOCASE),
   'Preset A', 'A56 Velo Harmnix', NULL, NULL, 'Dreams Dreams : Sweet Mix in Holy Night', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Christmas NiGHTS'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JV-80' COLLATE NOCASE),
   'Preset B', 'B13 Harp', NULL, NULL, '<EVENT> Missing Star', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Christmas NiGHTS'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Dance/Industrial' COLLATE NOCASE),
   NULL, NULL, 'Drum loops', NULL, 'Rolling Eggman', 'stuff_to_find', 'newer_vgm', 5),

  -- G11: NiGHTS: Journey of Dreams — 8 main + 1 stuff = 9 rows
  ((SELECT id FROM games WHERE title = 'NiGHTS: Journey of Dreams'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube Vol. 2 - Orchestra & Classic' COLLATE NOCASE),
   'CD 2 -> CHOIRS', 'CLGL_UP', NULL, NULL, 'Drifting Donbalon, Drifting Donbalon : Hard Ver.', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'NiGHTS: Journey of Dreams'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube Vol. 2 - Orchestra & Classic' COLLATE NOCASE),
   'CD 2 -> CHOIRS', 'FALL5', NULL, NULL, 'Drifting Donbalon, Drifting Donbalon : Hard Ver.', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'NiGHTS: Journey of Dreams'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube Vol. 2 - Orchestra & Classic' COLLATE NOCASE),
   'CD 2 -> CHOIRS', 'OOAH', NULL, NULL, 'Drifting Donbalon, Drifting Donbalon : Hard Ver.', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'NiGHTS: Journey of Dreams'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Steinberg' COLLATE NOCASE AND p.name = 'Virtual Guitarist 2' COLLATE NOCASE),
   'Electric Guitars -> Wah Wah', 'Soul Wah', NULL, NULL, 'Wandering Wildness : Coaster Rescue', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'NiGHTS: Journey of Dreams'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Ueberschall' COLLATE NOCASE AND p.name = 'Brazil Electro' COLLATE NOCASE),
   'BEATLOOPS -> sidekick beat 100 bpm', 'sidekick100 var 1-#197', NULL, NULL, 'Sweeping Seashore, Sweeping Seashore : Aqua Challenge, Sweeping Seashore : Marine Escape', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'NiGHTS: Journey of Dreams'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Ethnic' COLLATE NOCASE),
   'Track 06 - AFRO LATIN -> TS 0:00', 'Rhythm 8: Congas, bells,scraper 4 bars', NULL, NULL, 'Drifting Donbalon, Drifting Donbalon : Hard Ver.', 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'NiGHTS: Journey of Dreams'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'EZ Rollers Drum & Bass Producer Pack' COLLATE NOCASE),
   'Percussion -> Rolls', 'Filter 165bpm', NULL, NULL, 'Sweeping Seashore : Aqua Challenge', 'main', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'NiGHTS: Journey of Dreams'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Jungle Frenzy' COLLATE NOCASE),
   'Track 25 - Twist Ups! -> TS 0:04', 'Programmed Break Beat w/Filter 1', NULL, NULL, 'Wandering Wildness : Coaster Rescue', 'main', 'newer_vgm', 8),
  ((SELECT id FROM games WHERE title = 'NiGHTS: Journey of Dreams'),
   NULL, NULL, NULL, 'Lyrical Vocals', NULL, 'Drifting Donbalon, Drifting Donbalon : Hard Ver.', 'stuff_to_find', 'newer_vgm', 9);
