-- NEWER VGM SEGA/Atlus — Section 7 (Persona)
--
-- Source: reference/NEWER VGM Sound Sources - SEGAAtlus.csv lines 725-970.
-- 19 game records, ~213 usage rows. The flagship section.
--
-- Notable preservations (Rule 2):
--   - Dual JP/Western titles preserved verbatim: "Megami Ibunroku Persona /
--     Revelations: Persona", "Persona 2: Sin / Persona 2: Innocent Sin (PS1)",
--     "Persona 2: Punishment / Persona 2: Eternal Punishment (PS1)".
--   - "Persona 2: Eternal Punishment (PSP)" has the literal CSV stub
--     "???,???,???,???,No findings, so far." — single stuff_to_find row.
--   - "Fender Stratocaster 1974 " trailing-space preserved in the Live
--     Recording: Shoji Meguro row (Persona 4 T817).
--   - "BFD 1.5*" with asterisk (FXpansion, P4 T834) — distinct product from
--     "BFD 1.5" (InMusic, P4 stuff_to_find T849). Same library, different
--     manufacturer attributions in the CSV (FXpansion originally made BFD;
--     InMusic acquired the line) — both preserved verbatim.
--   - "AMG / Dance Mega Drums" (P4 T825) — contributor mis-attribution
--     (the library is published by Best Service); preserved verbatim as a
--     separate product distinct from "Best Service / Dance Mega Drums".
--   - "Norman Cook - Skip To My Loops" (P2EP T756, capital T) merges via
--     NOCASE with the existing "Skip to my Loops" from Section 3.
--   - Cross-media live recordings: "Live Recording: Shoji Meguro (Fender
--     Stratocaster 1974 )" (P4), "Live Recording: Muroya Strings (Strings)"
--     (P5).
--
-- Conventions: per-game positions restart at 1; stuff_to_find rows after
-- the per-game "Stuff to Find" marker; ?,? unknowns → both NULL.

INSERT OR IGNORE INTO manufacturers (name) VALUES
  ('Access Music'),
  ('e-instruments'),
  ('MusicLab'),
  ('Scarbee'),
  ('Spitfire Audio'),
  ('InMusic'),
  ('FXpansion'),
  ('Vengeance Sound'),
  ('u-he');

INSERT OR IGNORE INTO products (manufacturer_id, name, type) VALUES
  ((SELECT id FROM manufacturers WHERE name = 'Roland'             COLLATE NOCASE), 'JV-880',                                       'Synth'),
  ((SELECT id FROM manufacturers WHERE name = 'Roland'             COLLATE NOCASE), 'SR-JV80-07 Super Sound Set',                   'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Access Music'       COLLATE NOCASE), 'Virus Indigo',                                 'Synth'),
  ((SELECT id FROM manufacturers WHERE name = 'Best Service'       COLLATE NOCASE), 'Dance Mega Drums',                             'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Best Service'       COLLATE NOCASE), 'Hallelujah',                                   'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Best Service'       COLLATE NOCASE), 'ProSamples Vol. 12 - Dance Vocals',            'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Best Service'       COLLATE NOCASE), 'Voice Spectral II',                            'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Best Service'       COLLATE NOCASE), 'Advanced Orchestra Extended',                  'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Best Service'       COLLATE NOCASE), 'Sound Cube',                                   'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'e-instruments'      COLLATE NOCASE), 'Session Horns Pro',                            'Instrument'),
  ((SELECT id FROM manufacturers WHERE name = 'Native Instruments' COLLATE NOCASE), 'Noire',                                        'Instrument'),
  ((SELECT id FROM manufacturers WHERE name = 'Native Instruments' COLLATE NOCASE), 'The Grandeur',                                 'Instrument'),
  ((SELECT id FROM manufacturers WHERE name = 'Native Instruments' COLLATE NOCASE), 'Vintage Organs',                               'Instrument'),
  ((SELECT id FROM manufacturers WHERE name = 'Native Instruments' COLLATE NOCASE), 'Akoustik Piano',                               'Instrument'),
  ((SELECT id FROM manufacturers WHERE name = 'Scarbee'            COLLATE NOCASE), 'Clavinet/Pianet',                              'Instrument'),
  ((SELECT id FROM manufacturers WHERE name = 'Scarbee'            COLLATE NOCASE), 'Mark I',                                       'Instrument'),
  ((SELECT id FROM manufacturers WHERE name = 'Spitfire Audio'     COLLATE NOCASE), 'Chamber Strings',                              'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'InMusic'            COLLATE NOCASE), 'BFD3',                                         'Instrument'),
  ((SELECT id FROM manufacturers WHERE name = 'InMusic'            COLLATE NOCASE), 'BFD 1.5',                                      'Instrument'),
  ((SELECT id FROM manufacturers WHERE name = 'FXpansion'          COLLATE NOCASE), 'BFD 1.5*',                                     'Instrument'),
  ((SELECT id FROM manufacturers WHERE name = 'MusicLab'           COLLATE NOCASE), 'RealGuitar',                                   'Instrument'),
  ((SELECT id FROM manufacturers WHERE name = 'IK Multimedia'      COLLATE NOCASE), 'SampleTank 2.5 XL',                            'Instrument'),
  ((SELECT id FROM manufacturers WHERE name = 'MOTU'               COLLATE NOCASE), 'Universal Loops & Instruments',                'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'AMG'                COLLATE NOCASE), 'Dance Mega Drums',                             'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'E-MU Systems'       COLLATE NOCASE), 'Proteus FX',                                   'Synth'),
  ((SELECT id FROM manufacturers WHERE name = 'Vengeance Sound'    COLLATE NOCASE), 'Essential Clubsounds Vol. 3',                  'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Vengeance Sound'    COLLATE NOCASE), 'Essential Dubstep Vol. 1',                     'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Vengeance Sound'    COLLATE NOCASE), 'Essential Dubstep',                            'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'e-LAB'              COLLATE NOCASE), 'X-Files of Jungle',                            'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'u-he'               COLLATE NOCASE), 'Hive',                                         'Synth');

INSERT INTO games (title, platform, released, composers, composers_normalized, notes) VALUES
  ('Megami Ibunroku Persona / Revelations: Persona',                  'PlayStation',                                                         '1996-09-20', NULL, NULL, 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 7 Persona). Dual JP/Western title preserved verbatim.'),
  ('Shin Megami Tensei: Persona (PSP)',                               'PlayStation Portable',                                                '2009-04-29', NULL, NULL, 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 7 Persona). PSP remake of the 1996 original; only one source row identified in CSV.'),
  ('Persona 2: Sin / Persona 2: Innocent Sin (PS1)',                  'PlayStation',                                                         '1999-06-24', NULL, NULL, 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 7 Persona). Dual JP/Western title preserved verbatim. JP name "Sin" / Western "Innocent Sin" — distinct from the later PSP rerelease entry in this section.'),
  ('Persona 2: Punishment / Persona 2: Eternal Punishment (PS1)',     'PlayStation',                                                         '2000-06-29', NULL, NULL, 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 7 Persona). Dual JP/Western title preserved verbatim.'),
  ('Persona 3',                                                       'PlayStation 2',                                                       '2006-07-13', NULL, NULL, 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 7 Persona). Stuff_to_find note from CSV T790: "Source unknown, even by Meguro!"'),
  ('Persona 3 Portable',                                              'PlayStation Portable',                                                '2009-11-01', NULL, NULL, 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 7 Persona). Female protagonist route added.'),
  ('Persona 3 Reload',                                                'PlayStation 4, PlayStation 5, Xbox One, Xbox Series X|S, Nintendo Switch, PC', '2024-02-02', NULL, NULL, 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 7 Persona). Modern remake of Persona 3; entirely re-recorded soundtrack with current sample libraries (Spitfire, Native Instruments Noire/The Grandeur, etc.).'),
  ('Persona 4',                                                       'PlayStation 2',                                                       '2008-07-10', NULL, NULL, 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 7 Persona). Live Recording row credits Shoji Meguro on Fender Stratocaster 1974 (Line 6 POD 2.0 amp simulation) — preserved with trailing space verbatim.'),
  ('Persona 4 Golden',                                                'PlayStation Vita, PC, PlayStation 4, Xbox One, Nintendo Switch',      '2012-06-14', NULL, NULL, 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 7 Persona). Vita expansion adding winter content.'),
  ('Persona 2: Innocent Sin (PSP)',                                   'PlayStation Portable',                                                '2011-04-14', NULL, NULL, 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 7 Persona). PSP remake of the 1999 PS1 original.'),
  ('Persona 2: Eternal Punishment (PSP)',                             'PlayStation Portable',                                                '2012-05-17', NULL, NULL, 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 7 Persona). CSV row reads "???,???,???,???,No findings, so far." — no sources identified yet. PSP remake of the 2000 PS1 original.'),
  ('Persona Q: Shadow of the Labyrinth',                              'Nintendo 3DS',                                                        '2014-06-05', NULL, NULL, 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 7 Persona). Etrian Odyssey-style crossover of P3 and P4 casts.'),
  ('Persona 4: Dancing All Night',                                    'PlayStation 3, PlayStation Vita',                                     '2015-06-25', NULL, NULL, 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 7 Persona). Rhythm game spinoff.'),
  ('Persona 5',                                                       'PlayStation 3, PlayStation 4',                                        '2016-09-15', NULL, NULL, 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 7 Persona). Live Recording credit: Muroya Strings.'),
  ('Persona 5 Royal',                                                 'PlayStation 4, Nintendo Switch, PC, PlayStation 5, Xbox One, Xbox Series X|S', '2019-10-31', NULL, NULL, 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 7 Persona). Expanded P5 rerelease.'),
  ('Persona 3: Dancing In Moonlight',                                 'PlayStation Vita, PlayStation 4',                                     '2018-05-24', NULL, NULL, 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 7 Persona). Rhythm game spinoff.'),
  ('Persona Q2: New Cinema Labyrinth',                                'Nintendo 3DS',                                                        '2018-11-29', NULL, NULL, 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 7 Persona). Sequel to Persona Q.'),
  ('Persona 5 Strikers',                                              'PlayStation 4, Nintendo Switch, PC',                                  '2020-02-20', NULL, NULL, 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 7 Persona). Musou-style sequel co-developed with Omega Force.'),
  ('Persona 5 Tactica',                                               'PlayStation 4, PlayStation 5, Xbox One, Xbox Series X|S, Nintendo Switch, PC', '2023-11-17', NULL, NULL, 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 7 Persona). Tactics spinoff.');

INSERT INTO usages
  (game_id, product_id, path_bank, preset, notes, raw_source, examples, category, source_family, position)
VALUES
  -- G1: Megami Ibunroku Persona / Revelations: Persona — 20 main + 1 stuff = 21
  ((SELECT id FROM games WHERE title = 'Megami Ibunroku Persona / Revelations: Persona'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Dance/Industrial' COLLATE NOCASE),
   'Track 16 - MIDI File Rhythm loops -> TS 0:29', 'Effect 3', 'above sample w/horn hit', NULL, '1st & 2nd Ward Shopping District (West Entrance)', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Megami Ibunroku Persona / Revelations: Persona'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Dance/Industrial' COLLATE NOCASE),
   'Track 23 - MIDI File Rhythm loops -> TS 0:16', 'Kick', 'bass drum followed by hi hat pattern', NULL, '1st & 2nd Ward Shopping District (West Entrance)', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Megami Ibunroku Persona / Revelations: Persona'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Dance/Industrial' COLLATE NOCASE),
   'Track 23 - MIDI File Rhythm loops -> TS 0:28', 'Hi hat 3', 'panned left w/delay  electronic sounding', NULL, '1st & 2nd Ward Shopping District (West Entrance)', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Megami Ibunroku Persona / Revelations: Persona'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Dance/Industrial' COLLATE NOCASE),
   'Track 79 - Miscellaneous -> TS 0:00', 'Effect', 'sliding scratch', NULL, '1st & 2nd Ward Shopping District (West Entrance)', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Megami Ibunroku Persona / Revelations: Persona'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Dance/Industrial' COLLATE NOCASE),
   'Track 79 - Miscellaneous -> TS 0:03', 'Effect', 'scratch lick', NULL, '1st & 2nd Ward Shopping District (West Entrance)', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'Megami Ibunroku Persona / Revelations: Persona'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Dance/Industrial' COLLATE NOCASE),
   'Track 79 - Miscellaneous -> TS 0:06', 'Effect', 'scratch rhythm', NULL, '1st & 2nd Ward Shopping District (West Entrance)', 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'Megami Ibunroku Persona / Revelations: Persona'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JV-1080' COLLATE NOCASE),
   'PR-B', '019 Slap Bass 2', NULL, NULL, 'Maki''s Theme, Reiji''s Theme', 'main', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'Megami Ibunroku Persona / Revelations: Persona'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JV-1080' COLLATE NOCASE),
   'PR-B', '075 Tekno Hit 3', NULL, NULL, 'Common Battle', 'main', 'newer_vgm', 8),
  ((SELECT id FROM games WHERE title = 'Megami Ibunroku Persona / Revelations: Persona'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JV-1080' COLLATE NOCASE),
   'PR-E', '004 PopDrumSet 2', NULL, NULL, 'Maki''s Theme', 'main', 'newer_vgm', 9),
  ((SELECT id FROM games WHERE title = 'Megami Ibunroku Persona / Revelations: Persona'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JV-880' COLLATE NOCASE),
   'Internal', 'I50 Analog Pad 2', NULL, NULL, 'Dungeon ~ Hypnos Tower', 'main', 'newer_vgm', 10),
  ((SELECT id FROM games WHERE title = 'Megami Ibunroku Persona / Revelations: Persona'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-06 Dance' COLLATE NOCASE),
   'XP-X', '174 Baby', NULL, NULL, '1st & 2nd Ward Shopping District (West Entrance)', 'main', 'newer_vgm', 11),
  ((SELECT id FROM games WHERE title = 'Megami Ibunroku Persona / Revelations: Persona'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-06 Dance' COLLATE NOCASE),
   'XP-X', '066 Organ Tong', NULL, NULL, 'Dungeon ~ SEBEC Underground Research Lab', 'main', 'newer_vgm', 12),
  ((SELECT id FROM games WHERE title = 'Megami Ibunroku Persona / Revelations: Persona'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-07 Super Sound Set' COLLATE NOCASE),
   'XP-X', '184 Chineez Wave', NULL, NULL, 'Dungeon ~ Devil''s Mountain', 'main', 'newer_vgm', 13),
  ((SELECT id FROM games WHERE title = 'Megami Ibunroku Persona / Revelations: Persona'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-06 Dance' COLLATE NOCASE),
   'XP-X', '082 Sync Lead', NULL, NULL, 'Common Battle', 'main', 'newer_vgm', 14),
  ((SELECT id FROM games WHERE title = 'Megami Ibunroku Persona / Revelations: Persona'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-06 Dance' COLLATE NOCASE),
   'XP-X', '187 Girl Ah', 'TS: 0:34', NULL, 'Dungeon ~ Nemesis Tower', 'main', 'newer_vgm', 15),
  ((SELECT id FROM games WHERE title = 'Megami Ibunroku Persona / Revelations: Persona'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88 Pro' COLLATE NOCASE),
   'Native Map -> Drum Set', '009 ROOM', NULL, NULL, 'Common Battle, Reiji''s Theme', 'main', 'newer_vgm', 16),
  ((SELECT id FROM games WHERE title = 'Megami Ibunroku Persona / Revelations: Persona'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88 Pro' COLLATE NOCASE),
   'Native Map', '056 008 Impact Hit', NULL, NULL, 'Common Battle', 'main', 'newer_vgm', 17),
  ((SELECT id FROM games WHERE title = 'Megami Ibunroku Persona / Revelations: Persona'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88 Pro' COLLATE NOCASE),
   'Native Map', '074 000 Flute', NULL, NULL, 'Maki''s Theme', 'main', 'newer_vgm', 18),
  ((SELECT id FROM games WHERE title = 'Megami Ibunroku Persona / Revelations: Persona'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88 Pro' COLLATE NOCASE),
   'SC-88 Map', '053 000 Choir Aahs', 'In-game sample has two octaves layered', NULL, 'Common Battle', 'main', 'newer_vgm', 19),
  ((SELECT id FROM games WHERE title = 'Megami Ibunroku Persona / Revelations: Persona'),
   NULL, NULL, NULL, 'Music Box', 'Roland - ? (JD-990 or JV-1080)', 'City 2', 'stuff_to_find', 'newer_vgm', 20),

  -- G2: Shin Megami Tensei: Persona (PSP) — 1 row
  ((SELECT id FROM games WHERE title = 'Shin Megami Tensei: Persona (PSP)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Access Music' COLLATE NOCASE AND p.name = 'Virus Indigo' COLLATE NOCASE),
   'Bank C', 'AutobendBC', NULL, NULL, 'Deva-Yuga', 'main', 'newer_vgm', 1),

  -- G3: Persona 2: Sin / Persona 2: Innocent Sin (PS1) — 2 rows
  ((SELECT id FROM games WHERE title = 'Persona 2: Sin / Persona 2: Innocent Sin (PS1)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'TRITON-Rack' COLLATE NOCASE),
   'Programs -> Bank A', '096 Shape Shifter', 'TS 0:00', NULL, 'Mt. Iwato', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Persona 2: Sin / Persona 2: Innocent Sin (PS1)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-06 Dance' COLLATE NOCASE),
   'XP-X', '141 Spooky', NULL, NULL, 'Yukino Theme', 'main', 'newer_vgm', 2),

  -- G4: Persona 2: Punishment / Persona 2: Eternal Punishment (PS1) — 1 row
  ((SELECT id FROM games WHERE title = 'Persona 2: Punishment / Persona 2: Eternal Punishment (PS1)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG & Hit Music' COLLATE NOCASE AND p.name = 'Norman Cook - Skip to my Loops' COLLATE NOCASE),
   '101_BPM', '772_COOK', NULL, NULL, 'Club Zodiac', 'main', 'newer_vgm', 1),

  -- G5: Persona 3 — 29 main + 3 stuff = 32 rows
  ((SELECT id FROM games WHERE title = 'Persona 3'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG' COLLATE NOCASE AND p.name = 'Kick-Ass Brass!' COLLATE NOCASE),
   'KAB Trumpet', NULL, NULL, NULL, '~Used throughout the soundtrack~', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Persona 3'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'EXS24' COLLATE NOCASE),
   'Bass -> Acoustic Bass', 'Upright Jazz Bass', NULL, NULL, 'Iwatodai Dorm', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Persona 3'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'EXS24' COLLATE NOCASE),
   'Bass -> Electric Bass', 'Slapped Electric Bass', NULL, NULL, 'Tanaka''s Amazing Commodities', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Persona 3'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'EXS24' COLLATE NOCASE),
   'Acoustic Pianos', 'Steinway Grand Piano', 'plays in part with the brass', NULL, 'Aria of the Soul', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Persona 3'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Advanced Orchestra' COLLATE NOCASE),
   'CD 1 -> Partition A -> 01 VI LNG FF', 'VI LONG FF', NULL, NULL, 'Aria of the Soul', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'Persona 3'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Advanced Orchestra' COLLATE NOCASE),
   'CD 1 -> Partition A -> 06 VI PIZ 1', 'VI PIZICTO 1', NULL, NULL, 'Aria of the Soul, Living With Determination, Enduring Bonds', 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'Persona 3'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Advanced Orchestra' COLLATE NOCASE),
   'CD 1 -> Partition B -> 03 VI CR TRM', 'VI CRSC TREM', NULL, NULL, 'Aria of the Soul', 'main', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'Persona 3'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Advanced Orchestra' COLLATE NOCASE),
   'CD 1 -> Partition C -> 15 VA LNG FF', 'VA LONG FF', NULL, NULL, 'Aria of the Soul', 'main', 'newer_vgm', 8),
  ((SELECT id FROM games WHERE title = 'Persona 3'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Advanced Orchestra' COLLATE NOCASE),
   'CD 1 -> Partition E -> 18 CL LG FF', 'CL LONG FF', NULL, NULL, 'Aria of the Soul', 'main', 'newer_vgm', 9),
  ((SELECT id FROM games WHERE title = 'Persona 3'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Advanced Orchestra' COLLATE NOCASE),
   'CD 1 -> Partition G -> 13 CL PIZZ 1', 'CL PIZICTO 1', NULL, NULL, 'Aria of the Soul', 'main', 'newer_vgm', 10),
  ((SELECT id FROM games WHERE title = 'Persona 3'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Advanced Orchestra' COLLATE NOCASE),
   'CD 1 -> Partition G -> 15 BA LNG FF', 'BA LONG FF', NULL, NULL, 'Aria of the Soul', 'main', 'newer_vgm', 11),
  ((SELECT id FROM games WHERE title = 'Persona 3'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Advanced Orchestra' COLLATE NOCASE),
   'CD 1 -> Partition G -> 17 BA PIZZ 1', 'BA PIZICTO 1', NULL, NULL, 'Aria of the Soul', 'main', 'newer_vgm', 12),
  ((SELECT id FROM games WHERE title = 'Persona 3'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Advanced Orchestra' COLLATE NOCASE),
   'CD 3 -> Partition B -> 10 FLS LG F', 'FLS LONG F', NULL, NULL, 'Aria of the Soul', 'main', 'newer_vgm', 13),
  ((SELECT id FROM games WHERE title = 'Persona 3'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Advanced Orchestra' COLLATE NOCASE),
   'CD 3 -> Partition D -> 01 OBS LG F', 'OBS LONG F', NULL, NULL, 'This Mysterious Feeling', 'main', 'newer_vgm', 14),
  ((SELECT id FROM games WHERE title = 'Persona 3'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Dance Mega Drums' COLLATE NOCASE),
   'CD 2 -> Partition A -> 03 BD-HIP 03', 'D2 BD1-100', NULL, NULL, 'During The Test', 'main', 'newer_vgm', 15),
  ((SELECT id FROM games WHERE title = 'Persona 3'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Hallelujah' COLLATE NOCASE),
   'Partition F -> RAPPER 1-2', 'RAP PHRASES1', 'RAPHRASE10', NULL, 'Joy', 'main', 'newer_vgm', 16),
  ((SELECT id FROM games WHERE title = 'Persona 3'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Hallelujah' COLLATE NOCASE),
   'Partition F -> RAPPER 1-2', 'RAP PHRASES1', 'RAPHRASE17', NULL, 'Joy', 'main', 'newer_vgm', 17),
  ((SELECT id FROM games WHERE title = 'Persona 3'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Hallelujah' COLLATE NOCASE),
   'Track 31 - Rap Voices -> TS 0:00', 'Rapper 1,2', '"So dance, while I put you..."', NULL, 'Iwatodai Dorm, Joy', 'main', 'newer_vgm', 18),
  ((SELECT id FROM games WHERE title = 'Persona 3'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Hallelujah' COLLATE NOCASE),
   'Track 31 - Rap Voices -> TS 0:03', 'Rapper 1,2', '"Let''s party, put the boogie..."', NULL, 'Iwatodai Dorm, Joy', 'main', 'newer_vgm', 19),
  ((SELECT id FROM games WHERE title = 'Persona 3'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Hallelujah' COLLATE NOCASE),
   'Track 31 - Rap Voices -> TS 0:09', 'Rapper 1,2', '"Work that body, work that..."', NULL, 'Iwatodai Dorm, Joy', 'main', 'newer_vgm', 20),
  ((SELECT id FROM games WHERE title = 'Persona 3'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Hallelujah' COLLATE NOCASE),
   'Track 31 - Rap Voices -> TS 0:14', 'Rapper 1,2', '"I say hey, hey, hey"', NULL, 'Iwatodai Dorm, Joy', 'main', 'newer_vgm', 21),
  ((SELECT id FROM games WHERE title = 'Persona 3'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Hallelujah' COLLATE NOCASE),
   'Track 32 - Rap Voices -> TS 0:00', 'Rapper 1,2', '"Fill in the fire with the burn..."', NULL, 'Iwatodai Dorm, Joy', 'main', 'newer_vgm', 22),
  ((SELECT id FROM games WHERE title = 'Persona 3'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Hallelujah' COLLATE NOCASE),
   'Track 32 - Rap Voices -> TS 0:03', 'Rapper 1,2', '"Yeah, get up fourth of that..."', NULL, 'Iwatodai Dorm, Joy', 'main', 'newer_vgm', 23),
  ((SELECT id FROM games WHERE title = 'Persona 3'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Hallelujah' COLLATE NOCASE),
   'Track 32 - Rap Voices -> TS 0:08', 'Rapper 1,2', '"Come on girl, let me rock..."', NULL, 'Iwatodai Dorm, Joy', 'main', 'newer_vgm', 24),
  ((SELECT id FROM games WHERE title = 'Persona 3'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'ProSamples Vol. 12 - Dance Vocals' COLLATE NOCASE),
   'Partition B -> FEMALE', NULL, 'VOC103-F', NULL, 'Changing Seasons', 'main', 'newer_vgm', 25),
  ((SELECT id FROM games WHERE title = 'Persona 3'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'ProSamples Vol. 12 - Dance Vocals' COLLATE NOCASE),
   'Parition C -> MALE', '12C-VOC51-M', 'Pitched down ≈5 semitones.', NULL, 'p3ct004_01', 'main', 'newer_vgm', 26),
  ((SELECT id FROM games WHERE title = 'Persona 3'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'ProSamples Vol. 12 - Dance Vocals' COLLATE NOCASE),
   'Parition C -> MALE', 'VOC25-M', 'Pitched down ≈5 semitones.', NULL, 'p3ct004_01', 'main', 'newer_vgm', 27),
  ((SELECT id FROM games WHERE title = 'Persona 3'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Voice Spectral II' COLLATE NOCASE),
   'CD 1 -> Track 55 - adlib styled melodic lines -> TS 0:57', 'medium length lines 1 / dry (ricarda/jane)', NULL, NULL, 'Changing Seasons', 'main', 'newer_vgm', 28),
  ((SELECT id FROM games WHERE title = 'Persona 3'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Voice Spectral II' COLLATE NOCASE),
   'CD 1 -> Track 74 - lyric melodic lines -> TS 0:08', 'medium length lines (ricarda/jane)', '"Ayyyyyy, yea!"', NULL, 'Mass Destruction', 'main', 'newer_vgm', 29),
  ((SELECT id FROM games WHERE title = 'Persona 3'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Voice Spectral II' COLLATE NOCASE),
   'CD 2 -> Track 8 -> TS 0:27', NULL, NULL, NULL, 'Changing Seasons', 'main', 'newer_vgm', 30),
  ((SELECT id FROM games WHERE title = 'Persona 3'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Voice Spectral II' COLLATE NOCASE),
   'Partition D -> 03 MELODIC03', 'MEL 03 C', NULL, NULL, 'Master of Shadow', 'main', 'newer_vgm', 31),
  ((SELECT id FROM games WHERE title = 'Persona 3'),
   NULL, NULL, NULL, 'Source unknown, even by Meguro! Check notes.', NULL, '~Used throughout the soundtrack~', 'stuff_to_find', 'newer_vgm', 32),
  ((SELECT id FROM games WHERE title = 'Persona 3'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Advanced Orchestra Extended' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, 'Aria of the Soul, This Mysterious Feeling, Living With Determination', 'stuff_to_find', 'newer_vgm', 33),
  ((SELECT id FROM games WHERE title = 'Persona 3'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Polestar Magnetics' COLLATE NOCASE AND p.name = 'The X-Static Goldmine' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, 'During The Test', 'stuff_to_find', 'newer_vgm', 34),

  -- G6: Persona 3 Portable — 5 rows
  ((SELECT id FROM games WHERE title = 'Persona 3 Portable'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG' COLLATE NOCASE AND p.name = 'Kick-Ass Brass!' COLLATE NOCASE),
   'KAB Trumpet', NULL, NULL, NULL, 'Sun', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Persona 3 Portable'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Dance Mega Drums' COLLATE NOCASE),
   'CD 2 -> Partition A -> 01 BD-HIP 01', 'D2 BD1-036', NULL, NULL, 'A Way of Life', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Persona 3 Portable'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Voice Spectral II' COLLATE NOCASE),
   'CD 1 -> Track 71 - lyric melodic lines -> TS 0:09', 'rhythmic lines (ricarda/jane)', NULL, NULL, 'Sun', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Persona 3 Portable'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Voice Spectral II' COLLATE NOCASE),
   'CD 1 -> Track 73 - lyric melodic lines -> TS 0:26', 'medium length lines (ricarda/jane)', NULL, NULL, 'Sun', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Persona 3 Portable'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Voice Spectral II' COLLATE NOCASE),
   'CD 1 -> Track 81 - lyric melodic lines -> TS 0:02', 'melodic words (ricarda/jane)', NULL, NULL, 'Sun', 'main', 'newer_vgm', 5),

  -- G7: Persona 3 Reload — 15 rows
  ((SELECT id FROM games WHERE title = 'Persona 3 Reload'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Hallelujah' COLLATE NOCASE),
   'Partition F -> RAPPER 1-2', 'RAP PHRASES1', 'RAPHRASE10', NULL, 'Joy', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Persona 3 Reload'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Voice Spectral II' COLLATE NOCASE),
   'CD 1 -> Track 74 - lyric melodic lines -> TS 0:08', 'medium length lines (ricarda/jane)', '"Ayyyyyy, yea!"', NULL, 'Mass Destruction -Reload-', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Persona 3 Reload'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'e-instruments' COLLATE NOCASE AND p.name = 'Session Horns Pro' COLLATE NOCASE),
   'Session Horns Pro - Keyswitch', 'Bright Brass', NULL, NULL, 'It''s Going Down Now, Mass Destruction -Reload-', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Persona 3 Reload'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Native Instruments' COLLATE NOCASE AND p.name = 'Kontakt Factory Library' COLLATE NOCASE),
   'Band -> 4 - Organ', 'Jazz', NULL, NULL, 'It''s Going Down Now', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Persona 3 Reload'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Native Instruments' COLLATE NOCASE AND p.name = 'Kontakt Factory Library' COLLATE NOCASE),
   'World -> 7 - Metallophones', 'Kalimba', NULL, NULL, 'During the Exams…', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'Persona 3 Reload'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Native Instruments' COLLATE NOCASE AND p.name = 'Noire' COLLATE NOCASE),
   NULL, 'Noire Felt', NULL, NULL, NULL, 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'Persona 3 Reload'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Native Instruments' COLLATE NOCASE AND p.name = 'The Grandeur' COLLATE NOCASE),
   NULL, 'The Grandeur', NULL, NULL, 'Changing Seasons, Meaning of Armbands, Mass Destruction -Reload-, Joy', 'main', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'Persona 3 Reload'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Native Instruments' COLLATE NOCASE AND p.name = 'Vintage Organs' COLLATE NOCASE),
   '2 - Jazz', 'Groove Holmes', NULL, NULL, 'Color Your Night', 'main', 'newer_vgm', 8),
  ((SELECT id FROM games WHERE title = 'Persona 3 Reload'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Scarbee' COLLATE NOCASE AND p.name = 'Clavinet/Pianet' COLLATE NOCASE),
   'Upper -> In Da Phase', NULL, NULL, NULL, 'Changing Seasons', 'main', 'newer_vgm', 9),
  ((SELECT id FROM games WHERE title = 'Persona 3 Reload'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Scarbee' COLLATE NOCASE AND p.name = 'Mark I' COLLATE NOCASE),
   'Scarbee Mark I', 'D.I.', 'Added phaser.', NULL, 'Living with Determination', 'main', 'newer_vgm', 10),
  ((SELECT id FROM games WHERE title = 'Persona 3 Reload'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spitfire Audio' COLLATE NOCASE AND p.name = 'Chamber Strings' COLLATE NOCASE),
   'a - Violins 1', NULL, NULL, NULL, 'Full Moon Full Life', 'main', 'newer_vgm', 11),
  ((SELECT id FROM games WHERE title = 'Persona 3 Reload'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Steinberg' COLLATE NOCASE AND p.name = 'HALion Sonic SE' COLLATE NOCASE),
   'Pro Set', 'Expressive Flute', NULL, NULL, 'During the Exams', 'main', 'newer_vgm', 12),
  ((SELECT id FROM games WHERE title = 'Persona 3 Reload'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'InMusic' COLLATE NOCASE AND p.name = 'BFD3' COLLATE NOCASE),
   'Custom Kit', NULL, NULL, NULL, 'Color Your Night, It''s Going Down Now', 'main', 'newer_vgm', 13),
  ((SELECT id FROM games WHERE title = 'Persona 3 Reload'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves', '86-Outlaw Drums', NULL, NULL, 'Meaning of Armbands', 'main', 'newer_vgm', 14),
  ((SELECT id FROM games WHERE title = 'Persona 3 Reload'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Trilian' COLLATE NOCASE),
   'Bass - Electric Fingered', 'Clean Fender - Full Range All', NULL, NULL, 'Master of Tartarus, Color Your Night, Joy, During the Exams…', 'main', 'newer_vgm', 15),

  -- G8: Persona 4 — 29 main + 6 stuff = 35 rows
  ((SELECT id FROM games WHERE title = 'Persona 4'),
   NULL, NULL, NULL, 'Single-coil pickups ran through a Line 6 POD 2.0', 'Live Recording: Shoji Meguro (Fender Stratocaster 1974 )', NULL, 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Persona 4'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Access Music' COLLATE NOCASE AND p.name = 'Virus Indigo' COLLATE NOCASE),
   'Bank A', 'SinebassJS', NULL, NULL, 'Long Way', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Persona 4'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Access Music' COLLATE NOCASE AND p.name = 'Virus Indigo' COLLATE NOCASE),
   'Bank D', 'Backing HS', NULL, NULL, 'A Corner of Memories, Reverie', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Persona 4'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Access Music' COLLATE NOCASE AND p.name = 'Virus Indigo' COLLATE NOCASE),
   'Bank D', 'Begin? HS', NULL, NULL, 'Your Affection', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Persona 4'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Access Music' COLLATE NOCASE AND p.name = 'Virus Indigo' COLLATE NOCASE),
   'Bank G', 'AandreasM@', NULL, NULL, 'Border of Insanity, Deduction (Another Version)', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'Persona 4'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Access Music' COLLATE NOCASE AND p.name = 'Virus Indigo' COLLATE NOCASE),
   'Bank G', 'Driven M@', NULL, NULL, 'Castle', 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'Persona 4'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Access Music' COLLATE NOCASE AND p.name = 'Virus Indigo' COLLATE NOCASE),
   'Bank G', 'HarmopadM@', NULL, NULL, 'Your Affection', 'main', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'Persona 4'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Access Music' COLLATE NOCASE AND p.name = 'Virus Indigo' COLLATE NOCASE),
   'Bank G', 'Bowzerz M@', NULL, NULL, 'Sauna', 'main', 'newer_vgm', 8),
  ((SELECT id FROM games WHERE title = 'Persona 4'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG' COLLATE NOCASE AND p.name = 'Dance Mega Drums' COLLATE NOCASE),
   'CD 2 -> Partition A -> 01 BD-HIP 01', 'D2 BD1-036', NULL, NULL, 'Heartbeat Heartbreak', 'main', 'newer_vgm', 9),
  ((SELECT id FROM games WHERE title = 'Persona 4'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG' COLLATE NOCASE AND p.name = 'Kick-Ass Brass!' COLLATE NOCASE),
   'KAB Tenor Sax', NULL, NULL, NULL, 'Youthful Lunch', 'main', 'newer_vgm', 10),
  ((SELECT id FROM games WHERE title = 'Persona 4'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG' COLLATE NOCASE AND p.name = 'Kick-Ass Brass!' COLLATE NOCASE),
   'KAB Trombone', NULL, NULL, NULL, 'Youthful Lunch', 'main', 'newer_vgm', 11),
  ((SELECT id FROM games WHERE title = 'Persona 4'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG' COLLATE NOCASE AND p.name = 'Kick-Ass Brass!' COLLATE NOCASE),
   'KAB Trumpet', NULL, NULL, NULL, '~Used throughout the soundtrack~', 'main', 'newer_vgm', 12),
  ((SELECT id FROM games WHERE title = 'Persona 4'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'EXS24' COLLATE NOCASE),
   'Acoustic Pianos', 'Grand Piano', NULL, NULL, 'Mist', 'main', 'newer_vgm', 13),
  ((SELECT id FROM games WHERE title = 'Persona 4'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'EXS24' COLLATE NOCASE),
   'Acoustic Pianos', 'Steinway Grand Piano', NULL, NULL, 'Junes Theme, Strength of Heart', 'main', 'newer_vgm', 14),
  ((SELECT id FROM games WHERE title = 'Persona 4'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'EXS24' COLLATE NOCASE),
   'Keyboards', 'Vibraphone', NULL, NULL, 'muscle blues', 'main', 'newer_vgm', 15),
  ((SELECT id FROM games WHERE title = 'Persona 4'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Advanced Orchestra' COLLATE NOCASE),
   'CD 5 -> Partition B -> 03 TI FF', 'TI FF', NULL, NULL, 'The Genesis', 'main', 'newer_vgm', 16),
  ((SELECT id FROM games WHERE title = 'Persona 4'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Voice Spectral II' COLLATE NOCASE),
   'Track 17 -> TS 0:23 Onwards', NULL, NULL, NULL, 'Striptease', 'main', 'newer_vgm', 17),
  ((SELECT id FROM games WHERE title = 'Persona 4'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'FXpansion' COLLATE NOCASE AND p.name = 'BFD 1.5*' COLLATE NOCASE),
   'Ayotte Kit', NULL, '*Also available as BFD Eldorado', NULL, 'I''ll Face Myself -Battle-', 'main', 'newer_vgm', 18),
  ((SELECT id FROM games WHERE title = 'Persona 4'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'TRITON-Rack' COLLATE NOCASE),
   'Programs -> Bank A', '017 Studio Stage EP', NULL, NULL, 'Specialist', 'main', 'newer_vgm', 19),
  ((SELECT id FROM games WHERE title = 'Persona 4'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'TRITON-Rack' COLLATE NOCASE),
   'Programs -> Bank B', '055 Gospel PercOrgan', NULL, NULL, 'Heartbeat Heartbreak, Youthful Lunch', 'main', 'newer_vgm', 20),
  ((SELECT id FROM games WHERE title = 'Persona 4'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'MusicLab' COLLATE NOCASE AND p.name = 'RealGuitar' COLLATE NOCASE),
   NULL, 'Steel 2 (Doubling)', NULL, NULL, 'Someone Else''s Man', 'main', 'newer_vgm', 21),
  ((SELECT id FROM games WHERE title = 'Persona 4'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'MusicLab' COLLATE NOCASE AND p.name = 'RealGuitar' COLLATE NOCASE),
   NULL, 'Steel Fingered', NULL, NULL, 'Someone Else''s Man', 'main', 'newer_vgm', 22),
  ((SELECT id FROM games WHERE title = 'Persona 4'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Native Instruments' COLLATE NOCASE AND p.name = 'Akoustik Piano' COLLATE NOCASE),
   NULL, 'Concert Grand D', NULL, NULL, '~Used throughout the soundtrack~', 'main', 'newer_vgm', 23),
  ((SELECT id FROM games WHERE title = 'Persona 4'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Native Instruments' COLLATE NOCASE AND p.name = 'Kontakt Factory Library' COLLATE NOCASE),
   'Band -> 2 - Acoustic Pianos', 'Upright Piano', NULL, NULL, 'Heaven', 'main', 'newer_vgm', 24),
  ((SELECT id FROM games WHERE title = 'Persona 4'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Native Instruments' COLLATE NOCASE AND p.name = 'Kontakt Factory Library' COLLATE NOCASE),
   'Band -> 4 - Organ', 'Cool Cats', NULL, NULL, 'Like A Dream Come True', 'main', 'newer_vgm', 25),
  ((SELECT id FROM games WHERE title = 'Persona 4'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Native Instruments' COLLATE NOCASE AND p.name = 'Kontakt Factory Library' COLLATE NOCASE),
   'Orchestral -> 1 - VSL Strings', 'Violin Ensemble', 'could be VSL', NULL, 'Mist, The Genesis', 'main', 'newer_vgm', 26),
  ((SELECT id FROM games WHERE title = 'Persona 4'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Native Instruments' COLLATE NOCASE AND p.name = 'Kontakt Factory Library' COLLATE NOCASE),
   'Orchestral -> 3 - VSL Brass', 'French Horn Ensemble', 'could be VSL', NULL, 'The Genesis', 'main', 'newer_vgm', 27),
  ((SELECT id FROM games WHERE title = 'Persona 4'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Native Instruments' COLLATE NOCASE AND p.name = 'Kontakt Factory Library' COLLATE NOCASE),
   'Orchestral -> 3 - VSL Brass', 'Trombone Ensemble', 'could be VSL', NULL, 'The Genesis', 'main', 'newer_vgm', 28),
  ((SELECT id FROM games WHERE title = 'Persona 4'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Native Instruments' COLLATE NOCASE AND p.name = 'Kontakt Factory Library' COLLATE NOCASE),
   'Orchestral -> 3 - VSL Brass', 'Trumpet Ensemble', 'could be VSL', NULL, 'The Genesis', 'main', 'newer_vgm', 29),
  ((SELECT id FROM games WHERE title = 'Persona 4'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'EXS24' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, NULL, 'stuff_to_find', 'newer_vgm', 30),
  ((SELECT id FROM games WHERE title = 'Persona 4'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Advanced Orchestra Extended' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, 'The Genesis', 'stuff_to_find', 'newer_vgm', 31),
  ((SELECT id FROM games WHERE title = 'Persona 4'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'InMusic' COLLATE NOCASE AND p.name = 'BFD 1.5' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, NULL, 'stuff_to_find', 'newer_vgm', 32),
  ((SELECT id FROM games WHERE title = 'Persona 4'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'MusicLab' COLLATE NOCASE AND p.name = 'RealGuitar' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, 'It''s Showtime!', 'stuff_to_find', 'newer_vgm', 33),
  ((SELECT id FROM games WHERE title = 'Persona 4'),
   NULL, NULL, NULL, 'Tango Accordion / Reed Organ', 'Yamaha - ?', 'It''s Showtime!', 'stuff_to_find', 'newer_vgm', 34),
  ((SELECT id FROM games WHERE title = 'Persona 4'),
   NULL, NULL, NULL, NULL, 'Yamaha - ?', 'Reasoning', 'stuff_to_find', 'newer_vgm', 35),

  -- G9: Persona 4 Golden — 8 rows
  ((SELECT id FROM games WHERE title = 'Persona 4 Golden'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG' COLLATE NOCASE AND p.name = 'Kick-Ass Brass!' COLLATE NOCASE),
   'KAB Trumpet', NULL, NULL, NULL, 'Let''s Hit the Beach, Everyday Sunshine, Midnight Trivia Miracle Quiz', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Persona 4 Golden'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'Strings -> Solo Violin -> 5 Keysw', 'SVL KS Master', NULL, NULL, 'SNOWFLAKES -powder snow mix-', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Persona 4 Golden'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves', '120-Notre Dame Beat Mix', NULL, NULL, 'Time to Make History', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Persona 4 Golden'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves -> 84-Particles', '84-Particles Reflections 2', NULL, NULL, 'SNOWFLAKES -powder snow mix-', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Persona 4 Golden'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'Core Library -> Classic Stylus -> 78-Perturbed', '78-Perturbed', NULL, NULL, 'Memories', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'Persona 4 Golden'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Native Instruments' COLLATE NOCASE AND p.name = 'Kontakt Factory Library' COLLATE NOCASE),
   'World -> Metallophones', 'Music Box', NULL, NULL, 'Aria of the Soul - Music Box', 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'Persona 4 Golden'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Native Instruments' COLLATE NOCASE AND p.name = 'New York Concert Grand' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, '~Used throughout the soundtrack~', 'main', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'Persona 4 Golden'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'XLN Audio' COLLATE NOCASE AND p.name = 'Addictive Drums' COLLATE NOCASE),
   NULL, NULL, 'Custom kit', NULL, 'Everyone at the First New Years Shrine Visit', 'main', 'newer_vgm', 8),

  -- G10: Persona 2: Innocent Sin (PSP) — 24 main + 3 stuff = 27 rows
  ((SELECT id FROM games WHERE title = 'Persona 2: Innocent Sin (PSP)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'Loops' COLLATE NOCASE),
   'Final Cut Pro Sound Effects', 'Dog Bark Large', NULL, NULL, 'CD Shop ~ Giga Macho', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Persona 2: Innocent Sin (PSP)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'Loops' COLLATE NOCASE),
   'Final Cut Pro Sound Effects', 'Dog Pant', NULL, NULL, 'CD Shop ~ Giga Macho', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Persona 2: Innocent Sin (PSP)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'Loops' COLLATE NOCASE),
   'Final Cut Pro Sound Effects', 'Gun Hand Load 03', NULL, NULL, 'CD Shop ~ Giga Macho', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Persona 2: Innocent Sin (PSP)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'Loops' COLLATE NOCASE),
   'Final Cut Pro Sound Effects', 'Gun Hand Shot 01', NULL, NULL, 'CD Shop ~ Giga Macho', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Persona 2: Innocent Sin (PSP)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'Loops' COLLATE NOCASE),
   'Jam Pack For Garageband', 'Vinyl Scratch 27', NULL, NULL, 'CD Shop ~ Giga Macho', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'Persona 2: Innocent Sin (PSP)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'Loops' COLLATE NOCASE),
   'Jam Pack Remix Tools', 'Remix Beat Box Vocal FX', 'filtered', NULL, 'CD Shop ~ Giga Macho', 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'Persona 2: Innocent Sin (PSP)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'Loops' COLLATE NOCASE),
   'Jam Pack Remix Tools', 'Remix Beat Box Vocal FX', 'filtered', NULL, 'CD Shop ~ Giga Macho', 'main', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'Persona 2: Innocent Sin (PSP)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'Loops' COLLATE NOCASE),
   'Jam Pack Voices', 'Halleujah Lyric 02', 'pitched down 200 cents', NULL, 'CD Shop ~ Giga Macho', 'main', 'newer_vgm', 8),
  ((SELECT id FROM games WHERE title = 'Persona 2: Innocent Sin (PSP)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'Loops' COLLATE NOCASE),
   'Jam Pack Voices', 'Roger Improv 01', NULL, NULL, 'CD Shop ~ Giga Macho', 'main', 'newer_vgm', 9),
  ((SELECT id FROM games WHERE title = 'Persona 2: Innocent Sin (PSP)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'Loops' COLLATE NOCASE),
   'Jam Pack Voices', 'Roger Improv 02', 'pitched up 400 cents', NULL, 'CD Shop ~ Giga Macho', 'main', 'newer_vgm', 10),
  ((SELECT id FROM games WHERE title = 'Persona 2: Innocent Sin (PSP)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'Loops' COLLATE NOCASE),
   'Jam Pack Voices', 'Roger Improv 03', 'pitched up 400 cents', NULL, 'CD Shop ~ Giga Macho', 'main', 'newer_vgm', 11),
  ((SELECT id FROM games WHERE title = 'Persona 2: Innocent Sin (PSP)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'Loops' COLLATE NOCASE),
   'Jam Pack Voices', 'Tia Lyric 01', NULL, NULL, 'CD Shop ~ Giga Macho', 'main', 'newer_vgm', 12),
  ((SELECT id FROM games WHERE title = 'Persona 2: Innocent Sin (PSP)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'Loops' COLLATE NOCASE),
   'Jam Pack Voices', 'Tia Lyric 02', NULL, NULL, 'CD Shop ~ Giga Macho', 'main', 'newer_vgm', 13),
  ((SELECT id FROM games WHERE title = 'Persona 2: Innocent Sin (PSP)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'Loops' COLLATE NOCASE),
   'Jam Pack Voices', 'Tia Lyric 09', NULL, NULL, 'CD Shop ~ Giga Macho', 'main', 'newer_vgm', 14),
  ((SELECT id FROM games WHERE title = 'Persona 2: Innocent Sin (PSP)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'Loops' COLLATE NOCASE),
   'Jam Pack Voices', 'Tia Lyric 10', NULL, NULL, 'CD Shop ~ Giga Macho', 'main', 'newer_vgm', 15),
  ((SELECT id FROM games WHERE title = 'Persona 2: Innocent Sin (PSP)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'Loops' COLLATE NOCASE),
   'Jam Pack Voices', 'Tia Lyric 11', NULL, NULL, 'CD Shop ~ Giga Macho', 'main', 'newer_vgm', 16),
  ((SELECT id FROM games WHERE title = 'Persona 2: Innocent Sin (PSP)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Hallelujah' COLLATE NOCASE),
   'Track 31 - Rap Voices -> Sample 2', 'Rapper 1,2', '"Put the boogie in your body"', NULL, 'CD Shop ~ Giga Macho', 'main', 'newer_vgm', 17),
  ((SELECT id FROM games WHERE title = 'Persona 2: Innocent Sin (PSP)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 3 "Voice Spectral" > VOX_A_C', 'COMEON06', NULL, NULL, 'Vehicle Handling', 'main', 'newer_vgm', 18),
  ((SELECT id FROM games WHERE title = 'Persona 2: Innocent Sin (PSP)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'IK Multimedia' COLLATE NOCASE AND p.name = 'SampleTank 2.5 XL' COLLATE NOCASE),
   'Drums -> Acoustic', 'Room', NULL, NULL, 'Hero Theme', 'main', 'newer_vgm', 19),
  ((SELECT id FROM games WHERE title = 'Persona 2: Innocent Sin (PSP)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'MOTU' COLLATE NOCASE AND p.name = 'Universal Loops & Instruments' COLLATE NOCASE),
   '01 Piano & co -> Acoustic Pianos', 'Concert Grnd Piano', NULL, NULL, 'Yukino Theme (Sad)', 'main', 'newer_vgm', 20),
  ((SELECT id FROM games WHERE title = 'Persona 2: Innocent Sin (PSP)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Native Instruments' COLLATE NOCASE AND p.name = 'New York Concert Grand' COLLATE NOCASE),
   NULL, 'New York Concert Grand', NULL, NULL, 'Seven Sisters High School, Maya Theme (Sad), Ginko Theme (Sad)', 'main', 'newer_vgm', 21),
  ((SELECT id FROM games WHERE title = 'Persona 2: Innocent Sin (PSP)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-06 Dance' COLLATE NOCASE),
   'XP-X', '141 Spooky', NULL, NULL, 'Yukino Theme', 'main', 'newer_vgm', 22),
  ((SELECT id FROM games WHERE title = 'Persona 2: Innocent Sin (PSP)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves -> 86-Outlaw', '86-Outlaw Drums', NULL, NULL, 'Unbreakable Tie', 'main', 'newer_vgm', 23),
  ((SELECT id FROM games WHERE title = 'Persona 2: Innocent Sin (PSP)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'E-MU Systems' COLLATE NOCASE AND p.name = 'Proteus FX' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, 'Yukino''s Theme', 'stuff_to_find', 'newer_vgm', 24),
  ((SELECT id FROM games WHERE title = 'Persona 2: Innocent Sin (PSP)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JV-1080' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, 'Toa Defense', 'stuff_to_find', 'newer_vgm', 25),
  ((SELECT id FROM games WHERE title = 'Persona 2: Innocent Sin (PSP)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88 Pro' COLLATE NOCASE),
   'Native Map', '085 008 P5 Sync Lead', NULL, NULL, NULL, 'stuff_to_find', 'newer_vgm', 26),

  -- G11: Persona 2: Eternal Punishment (PSP) — 1 stub row
  ((SELECT id FROM games WHERE title = 'Persona 2: Eternal Punishment (PSP)'),
   NULL, NULL, NULL, 'No findings, so far.', NULL, NULL, 'stuff_to_find', 'newer_vgm', 1),

  -- G12: Persona Q: Shadow of the Labyrinth — 8 rows
  ((SELECT id FROM games WHERE title = 'Persona Q: Shadow of the Labyrinth'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG' COLLATE NOCASE AND p.name = 'Kick-Ass Brass!' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, 'Maze of Life', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Persona Q: Shadow of the Labyrinth'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Hallelujah' COLLATE NOCASE),
   'Partition F -> RAPPER 1-2', 'RAP PHRASES1', 'RAPHRASE10', NULL, 'JOY -in the labyrinth-', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Persona Q: Shadow of the Labyrinth'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Voice Spectral II' COLLATE NOCASE),
   'CD 1 -> Track 55 - adlib styled melodic lines -> TS 0:04', 'medium length lines 1 / dry (ricarda/jane)', NULL, NULL, 'Laser Beam', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Persona Q: Shadow of the Labyrinth'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Voice Spectral II' COLLATE NOCASE),
   'CD 1 -> Track 73 - lyric melodic lines -> TS 0:15', 'medium length lines (ricarda/jane)', NULL, NULL, 'Laser Beam', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Persona Q: Shadow of the Labyrinth'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'Perc -> Metals ', 'Celesta', NULL, NULL, 'Sweets and Cards', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'Persona Q: Shadow of the Labyrinth'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'Perc -> Metals ', 'Glock', NULL, NULL, 'Shadow In Wonderland', 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'Persona Q: Shadow of the Labyrinth'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, NULL, 'main', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'Persona Q: Shadow of the Labyrinth'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Trilian' COLLATE NOCASE),
   'Bass - Electric', 'Clean Fender - Full Range All', NULL, NULL, NULL, 'main', 'newer_vgm', 8),

  -- G13: Persona 4: Dancing All Night — 4 main + 1 stuff = 5 rows
  ((SELECT id FROM games WHERE title = 'Persona 4: Dancing All Night'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG' COLLATE NOCASE AND p.name = 'Kick-Ass Brass!' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, 'specialist (_NEVER MORE_ P4D-EDIT ver.)', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Persona 4: Dancing All Night'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'Loops' COLLATE NOCASE),
   'Jam Pack World Music', 'Brazilian Cuica 02', NULL, NULL, 'Dance!', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Persona 4: Dancing All Night'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   NULL, '85-Bongos 1', 'pitched up', NULL, 'Dance!', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Persona 4: Dancing All Night'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Vengeance Sound' COLLATE NOCASE AND p.name = 'Essential Clubsounds Vol. 3' COLLATE NOCASE),
   'VEC3 Loops 140 BPM -> VEC3 Fills 140 BPM', 'VEC3 Fill 140 BPM 094', NULL, NULL, 'Time To Make History AKIRA YAMAOKA Remix', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Persona 4: Dancing All Night'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Vengeance Sound' COLLATE NOCASE AND p.name = 'Essential Dubstep Vol. 1' COLLATE NOCASE),
   'VDUB1 Melody Loops', 'VDUB1 Melody 106 D 140BPM', NULL, NULL, 'Time To Make History AKIRA YAMAOKA Remix', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'Persona 4: Dancing All Night'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Vengeance Sound' COLLATE NOCASE AND p.name = 'Essential Dubstep' COLLATE NOCASE),
   NULL, '?', NULL, NULL, 'Time To Make History AKIRA YAMAOKA Remix', 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'Persona 4: Dancing All Night'),
   NULL, NULL, 'horns, maybe session horns?', NULL, NULL, 'Dance!', 'stuff_to_find', 'newer_vgm', 7),

  -- G14: Persona 5 — 20 main + 3 stuff = 23 rows
  ((SELECT id FROM games WHERE title = 'Persona 5'),
   NULL, NULL, NULL, 'Credited', 'Live Recording: Muroya Strings (Strings)', 'Last Surprise, Regret; Wake Up, Get Up, Get Out There', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Persona 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG' COLLATE NOCASE AND p.name = 'Kick-Ass Brass!' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, 'Tanaka''s Shady Commodities, Last Surprise', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Persona 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'Logic Pro' COLLATE NOCASE),
   'Bass -> Electric Bass', 'Slapped Electric Bass', NULL, NULL, 'Tanaka''s Shady Commodities', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Persona 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'Logic Pro' COLLATE NOCASE),
   'Orchestral -> Brass', 'Trumpets', NULL, NULL, NULL, 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Persona 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'Perc -> Drums', 'Timp Hits LR', NULL, NULL, 'Our Beginning', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'Persona 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Native Instruments' COLLATE NOCASE AND p.name = 'Kontakt Factory Library' COLLATE NOCASE),
   'World -> 1 - Flutes', 'Irish Flute', NULL, NULL, 'New Beginning', 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'Persona 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Native Instruments' COLLATE NOCASE AND p.name = 'Kontakt Factory Library' COLLATE NOCASE),
   'World -> 3 Reeds', 'Zurna', NULL, NULL, 'Price', 'main', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'Persona 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Native Instruments' COLLATE NOCASE AND p.name = 'Massive' COLLATE NOCASE),
   'Massive Exp. 2 -> Classic Mono Lead', 'Orient Saw', NULL, NULL, 'Blooming Villain', 'main', 'newer_vgm', 8),
  ((SELECT id FROM games WHERE title = 'Persona 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Native Instruments' COLLATE NOCASE AND p.name = 'Massive' COLLATE NOCASE),
   'Urban Arsenal 2 -> Synth Lead -> Vox Lead', 'OyBoy', NULL, NULL, 'Blooming Villain', 'main', 'newer_vgm', 9),
  ((SELECT id FROM games WHERE title = 'Persona 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Native Instruments' COLLATE NOCASE AND p.name = 'New York Concert Grand' COLLATE NOCASE),
   NULL, NULL, 'available in Kontakt Factory Library and Akoustik Piano', NULL, '~Used throughout the soundtrack~', 'main', 'newer_vgm', 10),
  ((SELECT id FROM games WHERE title = 'Persona 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Native Instruments' COLLATE NOCASE AND p.name = 'Vintage Organs' COLLATE NOCASE),
   '2 - Jazz', 'C3 - Jazz', NULL, NULL, 'Beneath the Mask -Instrumental-', 'main', 'newer_vgm', 11),
  ((SELECT id FROM games WHERE title = 'Persona 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Scarbee' COLLATE NOCASE AND p.name = 'Mark I' COLLATE NOCASE),
   'Scarbee Mark I', 'Funky Rio', NULL, NULL, 'Butterfly Kiss', 'main', 'newer_vgm', 12),
  ((SELECT id FROM games WHERE title = 'Persona 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Scarbee' COLLATE NOCASE AND p.name = 'Mark I' COLLATE NOCASE),
   'Scarbee Mark I', 'Pan Cake Kore', 'Distortion Turned Off', NULL, 'Wake Up, Get Up, Get Out There, Suspicion', 'main', 'newer_vgm', 13),
  ((SELECT id FROM games WHERE title = 'Persona 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Liquid Grooves S.A.G.E. Xpander' COLLATE NOCASE),
   '078-Ice Brushes', '078-Ice-Brushes-Triangle', NULL, NULL, 'Tokyo Daylight, Last Surprise', 'main', 'newer_vgm', 14),
  ((SELECT id FROM games WHERE title = 'Persona 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'Classic Stylus -> 73-Blue note', '73-Blue Note b', NULL, NULL, 'Wake Up, Get Up, Get Out There', 'main', 'newer_vgm', 15),
  ((SELECT id FROM games WHERE title = 'Persona 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'Classic Stylus -> 73-Blue note', '73-Blue Note d', 'Custom Loop', NULL, 'Sunset Bridge, etc.', 'main', 'newer_vgm', 16),
  ((SELECT id FROM games WHERE title = 'Persona 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves -> 120-Notre Dame', '?', NULL, NULL, 'Wake Up, Get Up, Get Out There', 'main', 'newer_vgm', 17),
  ((SELECT id FROM games WHERE title = 'Persona 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves -> 123-Festivo', '123-Festivo a', NULL, NULL, 'Wake Up, Get Up, Get Out There', 'main', 'newer_vgm', 18),
  ((SELECT id FROM games WHERE title = 'Persona 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves -> 135-Iron Boy', '135-Iron Boy Starter', NULL, NULL, 'The Collapse of Wrath', 'main', 'newer_vgm', 19),
  ((SELECT id FROM games WHERE title = 'Persona 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves -> 60-Volcano', '60-Volcano Kabuki Wood', NULL, NULL, 'Getaway & Arrest', 'main', 'newer_vgm', 20),
  ((SELECT id FROM games WHERE title = 'Persona 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Trilian' COLLATE NOCASE),
   'Bass - Electric', 'Clean Fender - Full Range All', NULL, NULL, '~Used throughout the soundtrack~', 'main', 'newer_vgm', 21),
  ((SELECT id FROM games WHERE title = 'Persona 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, NULL, 'stuff_to_find', 'newer_vgm', 22),
  ((SELECT id FROM games WHERE title = 'Persona 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Liquid Grooves S.A.G.E. Xpander' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, 'Tension', 'stuff_to_find', 'newer_vgm', 23),
  ((SELECT id FROM games WHERE title = 'Persona 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Liquid Grooves S.A.G.E. Xpander' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, 'Have a Short Rest', 'stuff_to_find', 'newer_vgm', 24),

  -- G15: Persona 5 Royal — 8 rows
  ((SELECT id FROM games WHERE title = 'Persona 5 Royal'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Metamorphosis S.A.G.E. Xpander' COLLATE NOCASE),
   '050-059', '055-Mohave a', NULL, NULL, 'Out of Kindness', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Persona 5 Royal'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Metamorphosis S.A.G.E. Xpander' COLLATE NOCASE),
   '050-059', '055-Mohave c', NULL, NULL, 'Gentle Madman', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Persona 5 Royal'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Metamorphosis S.A.G.E. Xpander' COLLATE NOCASE),
   '070-074', '072-Snug Bug c', NULL, NULL, 'Colors Flying High', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Persona 5 Royal'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'Classic Stylus', '115-Congas', NULL, NULL, 'Ideal and the Real', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Persona 5 Royal'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'Classic Stylus', '92-Tambourine', NULL, NULL, 'Ideal and the Real', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'Persona 5 Royal'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Trilian' COLLATE NOCASE),
   'Bass - Acoustic Upright', 'Trilian Ac 1 - Full Range All', NULL, NULL, 'No More What Ifs', 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'Persona 5 Royal'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Trilian' COLLATE NOCASE),
   'Bass - Electric Fingered', 'Clean Fender - Full Range All', NULL, NULL, '~Used throughout the soundtrack~', 'main', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'Persona 5 Royal'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Trilian' COLLATE NOCASE),
   'XTRA - Bass Legends', 'XTRA - Loboriel French Fretless', NULL, NULL, 'Out of Kindness', 'main', 'newer_vgm', 8),

  -- G16: Persona 3: Dancing In Moonlight — 3 rows
  ((SELECT id FROM games WHERE title = 'Persona 3: Dancing In Moonlight'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'e-LAB' COLLATE NOCASE AND p.name = 'X-Files of Jungle' COLLATE NOCASE),
   'Track 06 - -Hard Step Loops & Samples - 168 BPM -> TS 0:00', '6DRLPS', NULL, NULL, 'When The Moon''s Reaching Out Stars [Hideki Naganuma Remix]', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Persona 3: Dancing In Moonlight'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'Classic Stylus -> 65-Chill', '65-Chill c', NULL, NULL, 'Memories of the School - P3D Version', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Persona 3: Dancing In Moonlight'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Ueberschall' COLLATE NOCASE AND p.name = 'Brazil Electro' COLLATE NOCASE),
   'CONSTRUCTIONKITS -> 26-30braz on the floor', 'Organ-#449', NULL, NULL, 'When The Moon''s Reaching Out Stars [Hideki Naganuma Remix]', 'main', 'newer_vgm', 3),

  -- G17: Persona Q2: New Cinema Labyrinth — 7 rows
  ((SELECT id FROM games WHERE title = 'Persona Q2: New Cinema Labyrinth'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Hallelujah' COLLATE NOCASE),
   'Partition F -> RAPPER 1-2', 'RAP PHRASES1', 'RAPHRASE10', NULL, 'Joy -inside the cinema-', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Persona Q2: New Cinema Labyrinth'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'e-instruments' COLLATE NOCASE AND p.name = 'Session Horns Pro' COLLATE NOCASE),
   'Session Horns Pro - Keyswitch', 'Bright Brass', 'FoPiCre 4Beat', NULL, 'Invitation to Freedom, Wait and See', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Persona Q2: New Cinema Labyrinth'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'Strings -> 11 Violins -> 3 Effects', '11V Trill H', NULL, NULL, 'Invitation to Freedom', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Persona Q2: New Cinema Labyrinth'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'Strings -> Large String Ens', '70 Piece Str Sec Sus', NULL, NULL, 'Invitation to Freedom', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Persona Q2: New Cinema Labyrinth'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'Strings -> Solo Violin -> 5 Keysw', 'SVL KS Master', NULL, NULL, 'Cinematic Tale (All Versions)', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'Persona Q2: New Cinema Labyrinth'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'Classic Stylus', '73-Blue Note b', NULL, NULL, 'Road Less Taken', 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'Persona Q2: New Cinema Labyrinth'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Trilian' COLLATE NOCASE),
   'Bass - Electric', 'Clean Fender - Full Range All', NULL, NULL, NULL, 'main', 'newer_vgm', 7),

  -- G18: Persona 5 Strikers — 7 rows
  ((SELECT id FROM games WHERE title = 'Persona 5 Strikers'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'Loops' COLLATE NOCASE),
   'Jam Pack', NULL, 'synth at beginning', NULL, 'Anti HERO, Anti HERO - Another Version', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Persona 5 Strikers'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'Loops' COLLATE NOCASE),
   'Jam Pack 1', 'Synth Swirl 1', NULL, NULL, 'Anti HERO, Anti HERO - Another Version', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Persona 5 Strikers'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'Loops' COLLATE NOCASE),
   'Jam Pack Vocals', 'Beatbox Old School 11', NULL, NULL, 'Love te Wonderland, Love te Wonderland - Another Version', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Persona 5 Strikers'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'Loops' COLLATE NOCASE),
   'Jam Pack Vocals', 'Beatbox Old School 13', NULL, NULL, 'Love te Wonderland, Love te Wonderland - Another Version', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Persona 5 Strikers'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'Loops' COLLATE NOCASE),
   'Jam Pack Vocals', 'Beatbox Old School 14', NULL, NULL, 'Love te Wonderland, Love te Wonderland - Another Version', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'Persona 5 Strikers'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'Classic Stylus', '73-Blue Note b', NULL, NULL, 'You are Stronger', 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'Persona 5 Strikers'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Trilian' COLLATE NOCASE),
   'Bass - Electric Fingered', 'Clean Fender - Full Range All', NULL, NULL, 'You are Stronger', 'main', 'newer_vgm', 7),

  -- G19: Persona 5 Tactica — 5 rows
  ((SELECT id FROM games WHERE title = 'Persona 5 Tactica'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Scarbee' COLLATE NOCASE AND p.name = 'Mark I' COLLATE NOCASE),
   '-', 'D.I.', NULL, NULL, 'Beneath the Mask - Tactica -', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Persona 5 Tactica'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Scarbee' COLLATE NOCASE AND p.name = 'Mark I' COLLATE NOCASE),
   '-', 'Pan Cake Kore', 'Distortion Turned Off', NULL, 'Kindness', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Persona 5 Tactica'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'Classic Stylus -> 73-Blue note', '73-Blue note b', NULL, NULL, 'Hm?', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Persona 5 Tactica'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Trilian' COLLATE NOCASE),
   'Bass - Electric', 'Clean Fender - Full Range All', NULL, NULL, 'Mysteriously ', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Persona 5 Tactica'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'u-he' COLLATE NOCASE AND p.name = 'Hive' COLLATE NOCASE),
   '01 Basses', 'ARK Dirty Cog', NULL, NULL, 'The Night We Stood', 'main', 'newer_vgm', 5);
