-- NEWER VGM SEGA/Atlus — Section 8 (The House of the Dead)
--
-- Source: reference/NEWER VGM Sound Sources - SEGAAtlus.csv lines 972-1153.
-- 8 game records, ~164 usage rows.
--
-- The House of the Dead (1997) is split into three game records following
-- the Puyo Puyo Sun / Virtua Tennis 3 convention — the CSV identifies
-- distinct Arcade, Saturn, and Arcade Prototype builds with distinct
-- sound sources (esp. the Saturn version's NASA Challenger Disaster
-- sample and Hollywood Edge police radio FX).
--
-- HotD 2's "1998 Arcade Prototype" subheader is NOT split into its own
-- game record (only 1 prototype-found sample row); instead it's stored
-- under HotD 2 with category='unused' to capture the contributor note
-- "unused (found in sample ROM data)".
--
-- Verbatim preservations (Rule 2):
--   - Cross-media samples:
--       * Sample: NASA - Space Shuttle Challenger Disaster (HotD Saturn)
--         with the actual broadcast phrase "Challenger, go at throttle up."
--       * Sample: The House of the Dead 2 - Dawn / - Original Sin (HotD 4
--         remixes its own predecessor)
--       * Interpolation: Julius Fučík - Entrance of the Gladiators
--         (HotD Overkill quotes the famous circus march in Boss 3)
--   - "e-LAB / X-Static Goldmine 1" (HotD Overkill) preserved distinct
--     from "Polestar Magnetics / The X-Static Goldmine" — same library
--     family, different publisher attributions in the CSV.
--   - "Sounds Good" without suffix (HotD 2/4) preserved distinct from
--     prior "Sonic Foundry/Sounds Good" (FFX) and "Sounds Good & Steinberg"
--     (Daytona 2001) — contributor inconsistency across batches.
--   - "Roland - ? (JD-990 or JV-1080)" and "Garritan - ?" / "EastWest - ?"
--     contributor-uncertainty rows preserved as raw_source.
--   - "Link" demo column entries (HotD 2 T1053-1105) all skipped — they
--     are placeholder hyperlinks from the spreadsheet, not URLs.

INSERT OR IGNORE INTO manufacturers (name) VALUES
  ('Garritan'),
  ('Sounds Good');

INSERT OR IGNORE INTO products (manufacturer_id, name, type) VALUES
  ((SELECT id FROM manufacturers WHERE name = 'KORG'           COLLATE NOCASE), 'XSC-2S Orchestral',                                  'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Roland'         COLLATE NOCASE), 'SR-JV80-05 World',                                   'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Roland'         COLLATE NOCASE), 'SR-JV80-11 Techno Collection',                       'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Roland'         COLLATE NOCASE), 'JP-8000',                                            'Synth'),
  ((SELECT id FROM manufacturers WHERE name = 'Kurzweil'       COLLATE NOCASE), 'Industrial/Techno Programs',                         'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Kurzweil'       COLLATE NOCASE), 'K2VX',                                               'Synth'),
  ((SELECT id FROM manufacturers WHERE name = 'Kurzweil'       COLLATE NOCASE), 'K2VX Program Farm Disk',                             'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'AMG'            COLLATE NOCASE), 'Dave Ruffy''s Ruff Cutz',                            'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'AMG'            COLLATE NOCASE), 'Gota Yashiki - Groove Activator',                    'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Hollywood Edge' COLLATE NOCASE), 'The Edge Edition',                                   'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Masterbits'     COLLATE NOCASE), 'RAPsody',                                            'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Sounds Good'    COLLATE NOCASE), 'Methods of Mayhem',                                  'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Sound Ideas'    COLLATE NOCASE), 'Hollywood Series 4000',                              'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Sound Ideas'    COLLATE NOCASE), 'Series 1000',                                        'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Sound Ideas'    COLLATE NOCASE), 'Universal Studios Sound Effects',                    'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Ueberschall'    COLLATE NOCASE), 'Drum ''N'' Bass Resonance',                          'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Toontrack'      COLLATE NOCASE), 'Superior Drummer 2',                                 'Instrument'),
  ((SELECT id FROM manufacturers WHERE name = 'e-LAB'          COLLATE NOCASE), 'X-Static Goldmine 1',                                'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Zero-G'         COLLATE NOCASE), 'Datafile 3',                                         'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Zero-G'         COLLATE NOCASE), 'Funk Guitar',                                        'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Zero-G'         COLLATE NOCASE), 'Technotrance',                                       'Sample Library');

INSERT INTO games (title, platform, released, composers, composers_normalized, notes) VALUES
  ('The House of the Dead (Arcade)',             'Arcade',                              '1997-03-01', NULL,                              NULL,                              'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 8 House of the Dead). CSV release "(Released: March, 1997)" — month only; day=01 sort key. Split from "The House of the Dead" CSV game block by platform sub-header.'),
  ('The House of the Dead (SEGA Saturn)',        'Sega Saturn',                         '1998-03-26', NULL,                              NULL,                              'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 8 House of the Dead). Saturn port with additional samples (NASA Challenger broadcast, Hollywood Edge police radio FX).'),
  ('The House of the Dead (Arcade Prototype)',   'Arcade',                              NULL,         NULL,                              NULL,                              'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 8 House of the Dead). Unknown release date in CSV. Only 1 row identified: Zero-G Technotrance Classic Raver sample found in prototype ROM but flagged unused.'),
  ('The House of the Dead 2',                    'Arcade, Dreamcast, PC',               '1998-11-20', NULL,                              NULL,                              'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 8 House of the Dead). Largest entry in the section (~85 main + 12 stuff_to_find). The 1998 Arcade Prototype sub-section contributes 1 category=''unused'' row (Best Service Classical Choir CLS FEMALE) — sample found in prototype ROM but not in final.'),
  ('The House of the Dead III',                  'Arcade, Xbox, PC',                    '2002-12-19', NULL,                              NULL,                              'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 8 House of the Dead). Sparse identifications — only 2 main rows; most sources still flagged stuff_to_find.'),
  ('The House of the Dead 4',                    'Arcade, PlayStation 3',               '2005-12-21', NULL,                              NULL,                              'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 8 House of the Dead). Heavily samples its own predecessor (HotD 2) — 2 cross-game sample references to Dawn and Original Sin tracks preserved as raw_source.'),
  ('The House Of The Dead: Overkill',            'Wii',                                 '2009-09-17', 'John Sanderson, Nadeem Daya',     'john sanderson, nadeem daya',     'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 8 House of the Dead). Grindhouse spinoff. Boss 3 interpolates Julius Fučík''s "Entrance of the Gladiators" (the famous circus march).'),
  ('The House of the Dead: Remake',              'Nintendo Switch, PlayStation 4, Xbox One, PC', '2022-04-07', NULL,                              NULL,                              'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 8 House of the Dead). Forever Entertainment remake; only stuff_to_find rows (Omnisphere, HALion Sonic SE, Superior Drummer 2 candidates from social-media tips).');

INSERT INTO usages
  (game_id, product_id, path_bank, preset, notes, raw_source, examples, category, source_family, position)
VALUES
  -- G1: The House of the Dead (Arcade) — 28 main + 2 stuff_to_find = 30 rows
  ((SELECT id FROM games WHERE title = 'The House of the Dead (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = '01/W' COLLATE NOCASE),
   'PROG -> Bank A', 'A07 TheStrings', NULL, NULL, 'Unused Track 1, Emperor, Magician, Tragedy', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'The House of the Dead (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = '01/W' COLLATE NOCASE),
   'PROG -> Bank A', 'A09 TotalKit', NULL, NULL, '-Used throughout the soundtrack-', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'The House of the Dead (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = '01/W' COLLATE NOCASE),
   'PROG -> Bank A', 'A63 VeloVoices', NULL, NULL, 'The House of the Dead, Theme of the Magician', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'The House of the Dead (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = '01/W' COLLATE NOCASE),
   'PROG -> Bank A', 'A12 Brass Band', NULL, NULL, 'Tragedy, Unused Track 2, Stage Clear', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'The House of the Dead (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = '01/W' COLLATE NOCASE),
   'PROG -> Bank A', 'A77 ArcoAttack', NULL, NULL, 'Tragedy, Unused Track 2, The House of the Dead, etc.', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'The House of the Dead (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = '01/W' COLLATE NOCASE),
   'PROG -> Bank A', 'A59 Orch Hit', NULL, NULL, 'Truth, Unused Track 2, Magician', 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'The House of the Dead (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = '01/W' COLLATE NOCASE),
   'PROG -> Bank A', 'A91 Full Pipes', NULL, NULL, 'Revenge, Attract', 'main', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'The House of the Dead (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = '01/W' COLLATE NOCASE),
   'PROG -> Bank B', 'B01 ExpressoPF', NULL, NULL, 'Ending, The House of the Dead, Unused Track 1', 'main', 'newer_vgm', 8),
  ((SELECT id FROM games WHERE title = 'The House of the Dead (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = '01/W' COLLATE NOCASE),
   'PROG -> Bank B', 'B69 Orch Perc', NULL, NULL, 'Attract, Nativity of the Magician', 'main', 'newer_vgm', 9),
  ((SELECT id FROM games WHERE title = 'The House of the Dead (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'XSC-2S Orchestral' COLLATE NOCASE),
   'Multisound', 'C12 OC-OrcCrsh', NULL, NULL, 'Advertise', 'main', 'newer_vgm', 10),
  ((SELECT id FROM games WHERE title = 'The House of the Dead (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JV-2080' COLLATE NOCASE),
   'PR-A', '091 AmbienceVibe', NULL, NULL, 'Unused Track 2', 'main', 'newer_vgm', 11),
  ((SELECT id FROM games WHERE title = 'The House of the Dead (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88 Pro' COLLATE NOCASE),
   'Native Map -> Drum Set', '001 STANDARD 1', 'Notes D#4, F4, B4 ', NULL, '-Used throughout the soundtrack-', 'main', 'newer_vgm', 12),
  ((SELECT id FROM games WHERE title = 'The House of the Dead (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88 Pro' COLLATE NOCASE),
   'SC-55 Map', '127 000 Heart Beat', NULL, NULL, 'Revenge, SFX (Boss Encounter)', 'main', 'newer_vgm', 13),
  ((SELECT id FROM games WHERE title = 'The House of the Dead (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88 Pro' COLLATE NOCASE),
   'SC-88 Map', '056 000 Philly Hit', NULL, NULL, 'Theme of the Magician', 'main', 'newer_vgm', 14),
  ((SELECT id FROM games WHERE title = 'The House of the Dead (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88 Pro' COLLATE NOCASE),
   'SC-88 Map', '114 001 Atarigane', 'Unused (?)', NULL, NULL, 'main', 'newer_vgm', 15),
  ((SELECT id FROM games WHERE title = 'The House of the Dead (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88 Pro' COLLATE NOCASE),
   'SC-88Pro Map', '053 000 Choir Aahs', NULL, NULL, 'Theme of the Magician, Name Entry', 'main', 'newer_vgm', 16),
  ((SELECT id FROM games WHERE title = 'The House of the Dead (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 2' COLLATE NOCASE),
   'Track 95 - Sci-fi speech -> TS 0:08', '"...three..."', NULL, NULL, 'Revenge', 'main', 'newer_vgm', 17),
  ((SELECT id FROM games WHERE title = 'The House of the Dead (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 2' COLLATE NOCASE),
   'Track 95 - Sci-fi speech -> TS 0:12', '"...two..."', NULL, NULL, 'Revenge', 'main', 'newer_vgm', 18),
  ((SELECT id FROM games WHERE title = 'The House of the Dead (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 2' COLLATE NOCASE),
   'Track 95 - Sci-fi speech -> TS 0:14', '"...one..."', NULL, NULL, 'Revenge', 'main', 'newer_vgm', 19),
  ((SELECT id FROM games WHERE title = 'The House of the Dead (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 3' COLLATE NOCASE),
   'Track 87 - Misc. vocals + FX -> TS 0:00', 'mad laugh', NULL, NULL, 'Revenge', 'main', 'newer_vgm', 20),
  ((SELECT id FROM games WHERE title = 'The House of the Dead (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 3' COLLATE NOCASE),
   'Track 88 - Misc. vocals + FX -> TS 0:00', 'backspin 1', NULL, NULL, 'Revenge', 'main', 'newer_vgm', 21),
  ((SELECT id FROM games WHERE title = 'The House of the Dead (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 3' COLLATE NOCASE),
   'Track 89 - Misc. vocals + FX -> TS 0:08', '"ello daddy!"', NULL, NULL, 'Revenge', 'main', 'newer_vgm', 22),
  ((SELECT id FROM games WHERE title = 'The House of the Dead (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Funk Guitar' COLLATE NOCASE),
   'Track 75 - Funkin'' Heavy... -> TS 0:05', 'Big Riff 2', NULL, NULL, 'Tragedy, Boss', 'main', 'newer_vgm', 23),
  ((SELECT id FROM games WHERE title = 'The House of the Dead (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Technotrance' COLLATE NOCASE),
   'Track 01 - CLASSIC RAVE SYNTHS -> TS 0:34', 'Whistler', NULL, NULL, 'Tragedy', 'main', 'newer_vgm', 24),
  ((SELECT id FROM games WHERE title = 'The House of the Dead (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Technotrance' COLLATE NOCASE),
   'Track 02 - CLASSIC RAVE SYNTHS -> TS 0:29', 'Horror Synth', NULL, NULL, 'Truth', 'main', 'newer_vgm', 25),
  ((SELECT id FROM games WHERE title = 'The House of the Dead (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Technotrance' COLLATE NOCASE),
   'Track 13 - RAVE & HARDCORE BASSES -> TS 0:04', 'Red Hot Bass', NULL, NULL, 'Tragedy', 'main', 'newer_vgm', 26),
  ((SELECT id FROM games WHERE title = 'The House of the Dead (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Technotrance' COLLATE NOCASE),
   'Track 17 - TOP 20 STABS & PROGRESSIVE HOUSE -> TS 0:04', 'Ambientish', NULL, NULL, 'Revenge', 'main', 'newer_vgm', 27),
  ((SELECT id FROM games WHERE title = 'The House of the Dead (Arcade)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Technotrance' COLLATE NOCASE),
   'Track 50 - TECHNO SYNTHS & FX -> TS 0:12', 'Techno Chords 2', NULL, NULL, 'Revenge', 'main', 'newer_vgm', 28),
  ((SELECT id FROM games WHERE title = 'The House of the Dead (Arcade)'),
   NULL, NULL, 'Piano', NULL, NULL, 'Ending', 'stuff_to_find', 'newer_vgm', 29),
  ((SELECT id FROM games WHERE title = 'The House of the Dead (Arcade)'),
   NULL, NULL, 'Snare', NULL, NULL, 'Tragedy', 'stuff_to_find', 'newer_vgm', 30),

  -- G2: The House of the Dead (SEGA Saturn) — 11 rows
  ((SELECT id FROM games WHERE title = 'The House of the Dead (SEGA Saturn)'),
   NULL, NULL, NULL, '"Challenger, go at throttle up."', 'Sample: NASA - Space Shuttle Challenger Disaster', 'Revenge', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'The House of the Dead (SEGA Saturn)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Hollywood Edge' COLLATE NOCASE AND p.name = 'The Edge Edition' COLLATE NOCASE),
   'Radios & Static, Police', 'PoliceRadioVoices TE040301', 'Timestamp 0:20', NULL, 'Revenge', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'The House of the Dead (SEGA Saturn)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = '01/W' COLLATE NOCASE),
   'PROG -> Bank A', 'A26 Zap Bass', NULL, NULL, 'Theme of the Magician', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'The House of the Dead (SEGA Saturn)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = '01/W' COLLATE NOCASE),
   'PROG -> Bank A', 'A36 PickedBass', NULL, NULL, 'Boss', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'The House of the Dead (SEGA Saturn)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = '01/W' COLLATE NOCASE),
   'PROG -> Bank A', 'A98 MonoLead 1', NULL, NULL, 'Theme of the Magician, Boss', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'The House of the Dead (SEGA Saturn)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JD-990' COLLATE NOCASE),
   'PR-A', 'A-31 Pipe Organ', NULL, NULL, 'Advertise, Nativity of the Magician', 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'The House of the Dead (SEGA Saturn)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JV-2080' COLLATE NOCASE),
   'PR-A', '125 Power Trip', NULL, NULL, 'Boss', 'main', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'The House of the Dead (SEGA Saturn)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88 Pro' COLLATE NOCASE),
   'SC-88 Map', '121 006 Pick Scrape', NULL, NULL, 'Boss', 'main', 'newer_vgm', 8),
  ((SELECT id FROM games WHERE title = 'The House of the Dead (SEGA Saturn)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88 Pro' COLLATE NOCASE),
   'Native Map', '031 000 DistortionGt', NULL, NULL, 'Theme of the Magician', 'main', 'newer_vgm', 9),
  ((SELECT id FROM games WHERE title = 'The House of the Dead (SEGA Saturn)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88 Pro' COLLATE NOCASE),
   'Native Map', '074 001 Flute 2', NULL, NULL, 'Name Entry', 'main', 'newer_vgm', 10),
  ((SELECT id FROM games WHERE title = 'The House of the Dead (SEGA Saturn)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-05 World' COLLATE NOCASE),
   'XP-X', '060 Living Dead', NULL, NULL, 'Tragedy', 'main', 'newer_vgm', 11),

  -- G3: The House of the Dead (Arcade Prototype) — 1 row
  ((SELECT id FROM games WHERE title = 'The House of the Dead (Arcade Prototype)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Technotrance' COLLATE NOCASE),
   'Track 01 - CLASSIC RAVE SYNTHS -> TS 0:05', 'Classic Raver', 'Unused (found in sample ROM data)', NULL, NULL, 'main', 'newer_vgm', 1),

  -- G4: The House of the Dead 2 — 85 main + 1 unused (prototype) + 12 stuff_to_find = 98 rows
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG' COLLATE NOCASE AND p.name = 'Dave Ruffy''s Ruff Cutz' COLLATE NOCASE),
   'Track 02 - FULL GROOVES', 'User - 135 BPM', NULL, NULL, 'Despair, Boss (NAOMI version)', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG' COLLATE NOCASE AND p.name = 'Gota Yashiki - Groove Activator' COLLATE NOCASE),
   'Track 04 - Grooves -> TS 0:31', 'Sunrise - 96 bpm', NULL, NULL, 'Item Select', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG' COLLATE NOCASE AND p.name = 'Gota Yashiki - Groove Activator' COLLATE NOCASE),
   'Track 14 - Grooves -> TS 0:00', 'Riding 1 - 117 bpm', NULL, NULL, 'Boss Mode', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG' COLLATE NOCASE AND p.name = 'Gota Yashiki - Groove Activator' COLLATE NOCASE),
   'Track 17 - Grooves -> TS 0:00', 'Riding 4 - 117 bpm', NULL, NULL, 'Training Mode', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Steve Stevens Guitar' COLLATE NOCASE),
   'Partition A -> 5THS', '5THS     4M', NULL, NULL, 'Muddy, Stage Clear', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Steve Stevens Guitar' COLLATE NOCASE),
   'Partition A -> 5THS LOOPED', '5THS LP 11M', '5TH A#1 LP', NULL, 'Darkness', 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Steve Stevens Guitar' COLLATE NOCASE),
   'Partition B -> CHUGS', 'CHUGS     1M', NULL, NULL, 'Muddy', 'main', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Steve Stevens Guitar' COLLATE NOCASE),
   'Partition A -> DIVE-BOMBS', 'DIVEBOMB11', 'D4', NULL, 'A Prelude, Muddy', 'main', 'newer_vgm', 8),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Steve Stevens Guitar' COLLATE NOCASE),
   'Partition A -> DIVE-BOMBS', 'DIVEBOMB14', 'F4', NULL, 'A Prelude, Muddy', 'main', 'newer_vgm', 9),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Steve Stevens Guitar' COLLATE NOCASE),
   'Partition A -> SPECIAL EFX', 'SCRAPE 1', 'E3', NULL, 'A Prelude, Muddy', 'main', 'newer_vgm', 10),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = '01/W' COLLATE NOCASE),
   'PROG -> Bank A', 'A21 Brass Band', NULL, NULL, 'Muddy', 'main', 'newer_vgm', 11),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = '01/W' COLLATE NOCASE),
   'PROG -> Bank A', 'A91 Full Pipes', NULL, NULL, 'Muddy, Resurrection of the Magician, Theme of the Magician', 'main', 'newer_vgm', 12),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = '01/W' COLLATE NOCASE),
   'PROG -> Bank B', 'B37 ArcoAttack', NULL, NULL, 'Theme of the Emperor', 'main', 'newer_vgm', 13),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'XSC-2S Orchestral' COLLATE NOCASE),
   'Multisound', 'C12 OC-OrcCrsh', NULL, NULL, 'Theme of the Emperor', 'main', 'newer_vgm', 14),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Kurzweil' COLLATE NOCASE AND p.name = 'Industrial/Techno Programs' COLLATE NOCASE),
   'Programs', '213 Tech Jabs', NULL, NULL, 'Original Sin', 'main', 'newer_vgm', 15),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Kurzweil' COLLATE NOCASE AND p.name = 'Industrial/Techno Programs' COLLATE NOCASE),
   'Programs', '227 Industrial Bass', NULL, NULL, 'Darkness', 'main', 'newer_vgm', 16),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Kurzweil' COLLATE NOCASE AND p.name = 'Industrial/Techno Programs' COLLATE NOCASE),
   'Programs', '246 Workhouse Kit', 'E3, F#3', NULL, 'Boss, Name Entry', 'main', 'newer_vgm', 17),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Kurzweil' COLLATE NOCASE AND p.name = 'Industrial/Techno Programs' COLLATE NOCASE),
   'Programs', '266 Flangemachine(mod)', 'E5, A5', NULL, 'Advertise', 'main', 'newer_vgm', 18),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Kurzweil' COLLATE NOCASE AND p.name = 'Industrial/Techno Programs' COLLATE NOCASE),
   'Programs', '267 Rise(data)', NULL, NULL, 'Boss', 'main', 'newer_vgm', 19),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Kurzweil' COLLATE NOCASE AND p.name = 'Industrial/Techno Programs' COLLATE NOCASE),
   'Programs', '280 Psycho pt. 436', NULL, NULL, 'Boss, Introduction', 'main', 'newer_vgm', 20),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Kurzweil' COLLATE NOCASE AND p.name = 'Industrial/Techno Programs' COLLATE NOCASE),
   'Programs', '281  Movie Strings', 'C6', NULL, 'Name Entry', 'main', 'newer_vgm', 21),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Kurzweil' COLLATE NOCASE AND p.name = 'Industrial/Techno Programs' COLLATE NOCASE),
   'Programs', '288 Dist Square 5ths', NULL, NULL, 'Name Entry', 'main', 'newer_vgm', 22),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Kurzweil' COLLATE NOCASE AND p.name = 'K2VX' COLLATE NOCASE),
   'Programs -> 600''S BANK', '609 Pick It Bass', NULL, NULL, 'Training Mode, Boss Mode, Item Select', 'main', 'newer_vgm', 23),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Kurzweil' COLLATE NOCASE AND p.name = 'K2VX' COLLATE NOCASE),
   'Programs -> BASS', '074 Ripper Bass', NULL, NULL, 'Darkness', 'main', 'newer_vgm', 24),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Kurzweil' COLLATE NOCASE AND p.name = 'K2VX' COLLATE NOCASE),
   'Programs -> GUITAR', '093 Cee Taur', NULL, NULL, 'Name Entry', 'main', 'newer_vgm', 25),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Kurzweil' COLLATE NOCASE AND p.name = 'K2VX' COLLATE NOCASE),
   'Programs -> HYBRID SYNTHS', '157 Aurora', NULL, NULL, 'Darkness', 'main', 'newer_vgm', 26),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Kurzweil' COLLATE NOCASE AND p.name = 'K2VX' COLLATE NOCASE),
   'Programs -> KEYBOARDS', '012 Suitcase E Piano', NULL, NULL, 'Despair', 'main', 'newer_vgm', 27),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Kurzweil' COLLATE NOCASE AND p.name = 'K2VX' COLLATE NOCASE),
   'Programs -> SYNTH', '029 Hyper Guitar', NULL, NULL, 'Name Entry', 'main', 'newer_vgm', 28),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Kurzweil' COLLATE NOCASE AND p.name = 'K2VX Program Farm Disk' COLLATE NOCASE),
   'ANACOMPS.K25 -> SAWS W/ RESONANCE', '234 Alaska', NULL, NULL, 'Boss Mode, Training Mode', 'main', 'newer_vgm', 29),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Kurzweil' COLLATE NOCASE AND p.name = 'K2VX Program Farm Disk' COLLATE NOCASE),
   'ANALEADS.K25 -> PSEUDAMENTOS', '239 Prs Wow Lead', NULL, NULL, 'Darkness (Arcade Mode)', 'main', 'newer_vgm', 30),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Kurzweil' COLLATE NOCASE AND p.name = 'K2VX Program Farm Disk' COLLATE NOCASE),
   'STRINGS.K25 -> STRING PADS', '237 String Paddy', 'Pitch bends to simulate a "voice"', NULL, 'Despair, Introduction', 'main', 'newer_vgm', 31),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Kurzweil' COLLATE NOCASE AND p.name = 'Orchestral ROM' COLLATE NOCASE),
   'Programs -> PERCUSSION', '978 Orch Percussion1', 'Gong (Note C1)', NULL, 'Boss, Name Entry', 'main', 'newer_vgm', 32),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Masterbits' COLLATE NOCASE AND p.name = 'RAPsody' COLLATE NOCASE),
   'Track 26 - Naughty Nz -> TS 0:40', 'See there out ...', '"Boom, check it out like boom-boom"', NULL, 'Boss', 'main', 'newer_vgm', 33),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JP-8000' COLLATE NOCASE),
   'Performances', 'P:24 1979!', 'C4', NULL, 'Advertise', 'main', 'newer_vgm', 34),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JV-2080' COLLATE NOCASE),
   'PR-A', '002 Bright Piano', NULL, NULL, 'Ranking', 'main', 'newer_vgm', 35),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JV-2080' COLLATE NOCASE),
   'PR-A', '040 Claviduck', NULL, NULL, 'Despair', 'main', 'newer_vgm', 36),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JV-2080' COLLATE NOCASE),
   'PR-A', '102 Drone Split', NULL, NULL, 'Ranking', 'main', 'newer_vgm', 37),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JV-2080' COLLATE NOCASE),
   'PR-A', '125 Power Trip', NULL, NULL, 'Darkness', 'main', 'newer_vgm', 38),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JV-2080' COLLATE NOCASE),
   'PR-C', '045 Film Octaves', NULL, NULL, 'Unused Track', 'main', 'newer_vgm', 39),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JV-2080' COLLATE NOCASE),
   'PR-C', '105 CeremonyTimp', NULL, NULL, 'Boss, Darkness', 'main', 'newer_vgm', 40),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JV-2080' COLLATE NOCASE),
   'PR-D (GM)', '019 Organ 3', NULL, NULL, 'Muddy', 'main', 'newer_vgm', 41),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JV-2080' COLLATE NOCASE),
   'PR-D (GM)', '031 DistortionGt', 'Added EQ', NULL, 'Dawn', 'main', 'newer_vgm', 42),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JV-2080' COLLATE NOCASE),
   'Rhythm Set -> PR-B', '001 PowerDrumSet', 'Toms, cymbal, hi-hats, ride', NULL, 'Boss, Darkness', 'main', 'newer_vgm', 43),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88 Pro' COLLATE NOCASE),
   'Native Map', '034 Rock Bass', NULL, NULL, 'Muddy', 'main', 'newer_vgm', 44),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88 Pro' COLLATE NOCASE),
   'Native Map', '038 008 FM Slap', NULL, NULL, 'Boss, Despair, Original Sin', 'main', 'newer_vgm', 45),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88 Pro' COLLATE NOCASE),
   'Native Map', '049 000 Orchestra 2', NULL, NULL, 'A Prelude', 'main', 'newer_vgm', 46),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88 Pro' COLLATE NOCASE),
   'Native Map', '053 000 Choir Aahs', NULL, NULL, 'A Prelude, Theme of the Emperor, Theme of the Magician', 'main', 'newer_vgm', 47),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88 Pro' COLLATE NOCASE),
   'Native Map', '061 000 French Horns', NULL, NULL, 'Theme of the Emperor', 'main', 'newer_vgm', 48),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88 Pro' COLLATE NOCASE),
   'Native Map', '061 001 FHorn Rip', NULL, NULL, 'Theme of the Emperor', 'main', 'newer_vgm', 49),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88 Pro' COLLATE NOCASE),
   'Native Map', '062 000 Brass ff', NULL, NULL, 'Darkness', 'main', 'newer_vgm', 50),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88 Pro' COLLATE NOCASE),
   'Native Map -> Drum Set', '001 STANDARD 1', 'C#5, D5, A#6', NULL, 'Ranking', 'main', 'newer_vgm', 51),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-02 Orchestral' COLLATE NOCASE),
   'XP-X', '022 Marcato Vcs1', NULL, NULL, 'Introduction', 'main', 'newer_vgm', 52),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-02 Orchestral' COLLATE NOCASE),
   'XP-X', '092 Oboe 1', NULL, NULL, 'Ending', 'main', 'newer_vgm', 53),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-05 World' COLLATE NOCASE),
   'XP-X', '060 Living Dead', NULL, NULL, 'Ranking', 'main', 'newer_vgm', 54),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-05 World' COLLATE NOCASE),
   'XP-X', '071 Saintly', NULL, NULL, 'Dawn', 'main', 'newer_vgm', 55),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-05 World' COLLATE NOCASE),
   'XP-X', '141 ChineseOrch2', NULL, NULL, 'Despair', 'main', 'newer_vgm', 56),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-05 World' COLLATE NOCASE),
   'XP-X', '174 Bagpipes', NULL, NULL, 'Name Entry', 'main', 'newer_vgm', 57),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-05 World' COLLATE NOCASE),
   'XP-X', '194 Tambura', NULL, NULL, 'Darkness', 'main', 'newer_vgm', 58),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-11 Techno Collection' COLLATE NOCASE),
   'XP-X', '104 Dirty Stack', NULL, NULL, 'A Prelude', 'main', 'newer_vgm', 59),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-11 Techno Collection' COLLATE NOCASE),
   'XP-X', '109 Dance Stack', NULL, NULL, 'A Prelude', 'main', 'newer_vgm', 60),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-11 Techno Collection' COLLATE NOCASE),
   'XP-X -> Rhythm Set', '008 Indust.SET', NULL, NULL, 'A Prelude', 'main', 'newer_vgm', 61),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-12 Hip Hop Collection' COLLATE NOCASE),
   'XP-X', '095 Loops Menu 1', 'A4, B4', NULL, 'Ranking', 'main', 'newer_vgm', 62),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-12 Hip Hop Collection' COLLATE NOCASE),
   'XP-X', '191 Voice Menu', NULL, NULL, 'A Prelude, Ranking', 'main', 'newer_vgm', 63),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-12 Hip Hop Collection' COLLATE NOCASE),
   'XP-X -> Rhythm Set', '251 Snare Menu 1', 'E6', NULL, 'Darkness', 'main', 'newer_vgm', 64),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sound Ideas' COLLATE NOCASE AND p.name = 'Hollywood Series 4000' COLLATE NOCASE),
   '4003-16-02', 'CARTOON, GROAN', 'MALE, AGONY, HUMAN, HORROR', NULL, 'SFX (Strength)', 'main', 'newer_vgm', 65),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sound Ideas' COLLATE NOCASE AND p.name = 'Series 1000' COLLATE NOCASE),
   '1016-72-01', 'LOGGING, CHAINSAW', 'START, IDLE, REV, STOP', NULL, 'SFX (chainsaw)', 'main', 'newer_vgm', 66),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sound Ideas' COLLATE NOCASE AND p.name = 'Universal Studios Sound Effects' COLLATE NOCASE),
   'US02-36-01', 'MONSTER', 'ROAR, ANIMAL', NULL, 'SFX (Tower)', 'main', 'newer_vgm', 67),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sound Ideas' COLLATE NOCASE AND p.name = 'Universal Studios Sound Effects' COLLATE NOCASE),
   'US02-37-03', 'MONSTER', 'ROAR, ANIMAL', NULL, 'SFX (Tower)', 'main', 'newer_vgm', 68),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sound Ideas' COLLATE NOCASE AND p.name = 'Universal Studios Sound Effects' COLLATE NOCASE),
   'US02-38-01', 'MONSTER', 'ROAR, ANIMAL', NULL, 'SFX (Tower)', 'main', 'newer_vgm', 69),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sounds Good' COLLATE NOCASE AND p.name = 'Methods of Mayhem' COLLATE NOCASE),
   'Track 02 - Analoops 1 -> TS 0:16', 'ANALOOP 03 140 E S', NULL, NULL, 'Boss', 'main', 'newer_vgm', 70),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sounds Good' COLLATE NOCASE AND p.name = 'Methods of Mayhem' COLLATE NOCASE),
   'Track 16 - Drumb Beats 4 -> TS 0:11', 'BEAT 30 130 S', NULL, NULL, 'Original Sin', 'main', 'newer_vgm', 71),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sounds Good' COLLATE NOCASE AND p.name = 'Methods of Mayhem' COLLATE NOCASE),
   'Track 16 - Drumb Beats 4 -> TS 0:22', 'BEAT 33 130 S', NULL, NULL, 'Original Sin', 'main', 'newer_vgm', 72),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sounds Good' COLLATE NOCASE AND p.name = 'Methods of Mayhem' COLLATE NOCASE),
   'Track 17 - Drumb Beats 5 -> TS 0:18', 'BEAT 44 140 S', 'Custom loop at BGM Timestamp 0:47', NULL, 'Boss', 'main', 'newer_vgm', 73),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sounds Good' COLLATE NOCASE AND p.name = 'Methods of Mayhem' COLLATE NOCASE),
   'Track 23 - Ugly Loops 3 -> TS 0:00', 'UGLY 19 130 S', NULL, NULL, 'Original Sin', 'main', 'newer_vgm', 74),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sounds Good' COLLATE NOCASE AND p.name = 'Methods of Mayhem' COLLATE NOCASE),
   'Track 32 - Grind Control 2 -> TS 0:00', 'RIFF 11 120 C M', NULL, NULL, 'Dawn', 'main', 'newer_vgm', 75),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sounds Good' COLLATE NOCASE AND p.name = 'Methods of Mayhem' COLLATE NOCASE),
   'Track 32 - Grind Control 2 -> TS 0:27', 'RIFF 22 130 C M', NULL, NULL, 'Original Sin', 'main', 'newer_vgm', 76),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sounds Good' COLLATE NOCASE AND p.name = 'Methods of Mayhem' COLLATE NOCASE),
   'Track 48 - Gain Control 1 -> TS 0:01', 'FEEDBACK 01 S', NULL, NULL, 'Despair', 'main', 'newer_vgm', 77),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sounds Good' COLLATE NOCASE AND p.name = 'Methods of Mayhem' COLLATE NOCASE),
   'Track 53 - Old School -> TS 0:00', 'CLANK 01 M', NULL, NULL, 'Dawn', 'main', 'newer_vgm', 78),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sounds Good' COLLATE NOCASE AND p.name = 'Methods of Mayhem' COLLATE NOCASE),
   'Track 53 - Old School -> TS 0:01', 'CLANK 02 M', NULL, NULL, 'Dawn', 'main', 'newer_vgm', 79),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sounds Good' COLLATE NOCASE AND p.name = 'Methods of Mayhem' COLLATE NOCASE),
   'Track 53 - Old School -> TS 0:06', 'CLANK 06 M', NULL, NULL, 'Dawn', 'main', 'newer_vgm', 80),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sounds Good' COLLATE NOCASE AND p.name = 'Methods of Mayhem' COLLATE NOCASE),
   'Track 53 - Old School -> TS 0:08', 'CLANK 08 M', NULL, NULL, 'Dawn', 'main', 'newer_vgm', 81),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sounds Good' COLLATE NOCASE AND p.name = 'Methods of Mayhem' COLLATE NOCASE),
   'Track 53 - Old School -> TS 0:09', 'CLANK 09 M', NULL, NULL, 'Dawn', 'main', 'newer_vgm', 82),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sounds Good' COLLATE NOCASE AND p.name = 'Methods of Mayhem' COLLATE NOCASE),
   'Track 53 - Old School -> TS 0:11', 'CLANK 11 M', NULL, NULL, 'Dawn', 'main', 'newer_vgm', 83),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Ueberschall' COLLATE NOCASE AND p.name = 'Drum ''N'' Bass Resonance' COLLATE NOCASE),
   'Track 42 - Track Pack 124 BPM -> TS 0:00', 'Drumloops (8 bars)', NULL, NULL, 'Dawn', 'main', 'newer_vgm', 84),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Chemical Beats' COLLATE NOCASE),
   'Track 12 -> TS 0:00', 'FX Loops 1-5 104 bpm', NULL, NULL, 'Introduction', 'main', 'newer_vgm', 85),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Classical Choir' COLLATE NOCASE),
   'Partition H -> CLUSTER', 'CLS FEMALE', 'unused (found in sample ROM data); from 1998 Arcade Prototype build', NULL, 'Dawn', 'unused', 'newer_vgm', 86),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   NULL, NULL, NULL, NULL, 'Best Service - ?', NULL, 'stuff_to_find', 'newer_vgm', 87),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = '01/W' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, NULL, 'stuff_to_find', 'newer_vgm', 88),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Kurzweil' COLLATE NOCASE AND p.name = 'K2VX' COLLATE NOCASE),
   NULL, NULL, 'Distorted/crunchy bass', NULL, 'Boss (Original Mode), Darkness (Original Mode), Despair (Original Mode)', 'stuff_to_find', 'newer_vgm', 89),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Kurzweil' COLLATE NOCASE AND p.name = 'K2VX' COLLATE NOCASE),
   NULL, NULL, 'Arp Synth', NULL, 'Despair, Introduction', 'stuff_to_find', 'newer_vgm', 90),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Kurzweil' COLLATE NOCASE AND p.name = 'Industrial/Techno Programs' COLLATE NOCASE),
   NULL, '297 Clock Arp', NULL, NULL, 'Despair', 'stuff_to_find', 'newer_vgm', 91),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Kurzweil' COLLATE NOCASE AND p.name = 'Industrial/Techno Programs' COLLATE NOCASE),
   NULL, NULL, 'snare', NULL, 'Introduction, Despair', 'stuff_to_find', 'newer_vgm', 92),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Kurzweil' COLLATE NOCASE AND p.name = 'Industrial/Techno Programs' COLLATE NOCASE),
   NULL, NULL, 'open hi-hat', NULL, 'Boss, Dawn', 'stuff_to_find', 'newer_vgm', 93),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Kurzweil' COLLATE NOCASE AND p.name = 'Industrial/Techno Programs' COLLATE NOCASE),
   NULL, NULL, 'harpsichord', NULL, 'Name Entry', 'stuff_to_find', 'newer_vgm', 94),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-05 World' COLLATE NOCASE),
   'XP-X', '?', 'tabla', NULL, 'Ranking', 'stuff_to_find', 'newer_vgm', 95),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JP-8000' COLLATE NOCASE),
   'Performances', 'P:43 Touchy Alarmist', NULL, NULL, 'Advertise', 'stuff_to_find', 'newer_vgm', 96),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   NULL, NULL, NULL, 'rising horror string', NULL, 'Introduction', 'stuff_to_find', 'newer_vgm', 97),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 2'),
   NULL, NULL, NULL, 'beep / sine wave', NULL, 'Boss, Unused Track', 'stuff_to_find', 'newer_vgm', 98),

  -- G5: The House of the Dead III — 2 main + 6 stuff = 8 rows
  ((SELECT id FROM games WHERE title = 'The House of the Dead III'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = '01/W' COLLATE NOCASE),
   'PROG -> Bank A', 'A17 ChamberEns', NULL, NULL, 'Infiltrate', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'The House of the Dead III'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88 Pro' COLLATE NOCASE),
   'Native Map', '061 024 F.Horn Rip', NULL, NULL, 'Theme of the Last Mystery', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'The House of the Dead III'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Advanced Orchestra' COLLATE NOCASE),
   '?', NULL, NULL, NULL, NULL, 'stuff_to_find', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'The House of the Dead III'),
   NULL, NULL, NULL, 'church organ', 'EastWest - ?', 'Fugue of Awakening, Theme of the Last Mystery', 'stuff_to_find', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'The House of the Dead III'),
   NULL, NULL, NULL, 'harp gliss', 'Garritan - ?', 'Infiltrate', 'stuff_to_find', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'The House of the Dead III'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JV-2080' COLLATE NOCASE),
   '?', NULL, NULL, NULL, NULL, 'stuff_to_find', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'The House of the Dead III'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-02 Orchestral' COLLATE NOCASE),
   'XP-X', NULL, NULL, NULL, NULL, 'stuff_to_find', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'The House of the Dead III'),
   NULL, NULL, NULL, 'techno loop', 'Zero-G - ?', 'Theme of "The House of the Dead III", Flash of Labyrinth', 'stuff_to_find', 'newer_vgm', 8),

  -- G6: The House of the Dead 4 — 8 main + 2 stuff = 10 rows
  ((SELECT id FROM games WHERE title = 'The House of the Dead 4'),
   NULL, NULL, 'n/a (various timestamps)', NULL, 'Sample: The House of the Dead 2 - Dawn', 'Dawn (Remix of Year Seventh)', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 4'),
   NULL, NULL, 'n/a (various timestamps)', NULL, 'Sample: The House of the Dead 2 - Original Sin', 'Original Sin (Remix of Year Seventh)', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 4'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sounds Good' COLLATE NOCASE AND p.name = 'Methods of Mayhem' COLLATE NOCASE),
   'Track 16 - Drum Beats 4 -> Sample 4', 'BEAT 30 130 S', NULL, NULL, 'Original Sin (Remix of Year Seventh)', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 4'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sounds Good' COLLATE NOCASE AND p.name = 'Methods of Mayhem' COLLATE NOCASE),
   'Track 16 - Drum Beats 4 -> Sample 7', 'BEAT 33 130 S', NULL, NULL, 'Original Sin (Remix of Year Seventh)', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 4'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sounds Good' COLLATE NOCASE AND p.name = 'Methods of Mayhem' COLLATE NOCASE),
   'Track 23 - Ugly Loops 3 -> TS 0:00', 'UGLY 19 130 S', NULL, NULL, 'Original Sin (Remix of Year Seventh)', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 4'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sounds Good' COLLATE NOCASE AND p.name = 'Methods of Mayhem' COLLATE NOCASE),
   'Track 33 - Grind Control 3 -> TS 0:00', 'RIFF 23 140 E S', NULL, NULL, 'Original Sin (Remix of Year Seventh)', 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 4'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sounds Good' COLLATE NOCASE AND p.name = 'Methods of Mayhem' COLLATE NOCASE),
   'Track 48 - Gain Control 1 -> TS 0:00', 'FEEDBACK 01 S', NULL, NULL, 'Original Sin (Remix of Year Seventh)', 'main', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 4'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sounds Good' COLLATE NOCASE AND p.name = 'Methods of Mayhem' COLLATE NOCASE),
   'Track 48 - Gain Control 1 -> Sample 8', 'FEEDBACK 08 M', NULL, NULL, 'Original Sin (Remix of Year Seventh)', 'main', 'newer_vgm', 8),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 4'),
   NULL, NULL, NULL, NULL, 'Big Fish Audio - ?', 'Bullet of Death, Bullet of Death (Gauge), Boss Raid', 'stuff_to_find', 'newer_vgm', 9),
  ((SELECT id FROM games WHERE title = 'The House of the Dead 4'),
   NULL, NULL, NULL, NULL, 'Zero-G - ?', 'Boss Raid, Give it All You Got!', 'stuff_to_find', 'newer_vgm', 10),

  -- G7: The House Of The Dead: Overkill — 2 main + 1 stuff = 3 rows
  ((SELECT id FROM games WHERE title = 'The House Of The Dead: Overkill'),
   NULL, NULL, NULL, NULL, 'Interpolation: Julius Fučík - Entrance of the Gladiators', 'Boss 3', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'The House Of The Dead: Overkill'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'e-LAB' COLLATE NOCASE AND p.name = 'X-Static Goldmine 1' COLLATE NOCASE),
   'XEa_LoopTools -> EA_135_Loops_and_Seq', 'EA6106_Loop_Break5', NULL, NULL, 'Boss 4 (Unused)', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'The House Of The Dead: Overkill'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'EXS24' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, '~Used Throughout the Soundtrack~', 'stuff_to_find', 'newer_vgm', 3),

  -- G8: The House of the Dead: Remake — 3 stuff_to_find rows (no main)
  ((SELECT id FROM games WHERE title = 'The House of the Dead: Remake'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Omnisphere' COLLATE NOCASE),
   NULL, NULL, 'See Instagram response', NULL, NULL, 'stuff_to_find', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'The House of the Dead: Remake'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Steinberg' COLLATE NOCASE AND p.name = 'HALion Sonic SE' COLLATE NOCASE),
   NULL, NULL, 'the composer is confirmed to have Cubase', NULL, NULL, 'stuff_to_find', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'The House of the Dead: Remake'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Toontrack' COLLATE NOCASE AND p.name = 'Superior Drummer 2' COLLATE NOCASE),
   NULL, NULL, '(Potentially) seen in a screenshot', NULL, NULL, 'stuff_to_find', 'newer_vgm', 3);
