-- NEWER VGM SEGA/Atlus — Section 9 (Space Channel 5)
--
-- Source: reference/NEWER VGM Sound Sources - SEGAAtlus.csv lines 1155-1354.
-- 2 game records, ~194 usage rows.
--
-- This section is heavily sample-based. The Space Channel 5 soundtracks
-- pull from jazz, lounge, film score, and bossa nova classics — preserved
-- as 'Sample: <artist> - <track>' in raw_source. Notable cross-media
-- artists sampled include Quincy Jones, Lalo Schifrin, Elmer Bernstein,
-- John Williams (The Hunt, The Raptors Appear), Henry Mancini, Hugo
-- Montenegro, Duke Ellington, Dizzy Gillespie, and more.
--
-- Notable curiosities preserved verbatim per Rule 2:
--   - "Live Recording: Michael Jackson (Beatboxing)" — SC5 Part 2 T1257.
--     Documented contribution from Michael Jackson, who was a fan of the
--     original; sampled for "Save Space Michael the Office Chief!"
--   - "Interpolation: Hugo Montenegro - Wild Bike" (SC5 main row 1).
--   - "Sample: ? - Blue Danube" (SC5 Part 2 stuff_to_find T1341) —
--     contributor knows the song but not the recording artist.
--   - "? (Song Sample)" / "? (DJ Tool?)" rows preserved with that literal
--     uncertainty annotation in raw_source.
--   - The "Mororina♥" / "Coco★Tapioka" diacritical characters preserved
--     verbatim in the example columns.

INSERT OR IGNORE INTO manufacturers (name) VALUES
  ('Clavia'),
  ('Ninja Tune');

INSERT OR IGNORE INTO products (manufacturer_id, name, type) VALUES
  ((SELECT id FROM manufacturers WHERE name = 'Best Service'  COLLATE NOCASE), 'Brass Super Section',                       'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Clavia'        COLLATE NOCASE), 'Nord Lead 2',                               'Synth'),
  ((SELECT id FROM manufacturers WHERE name = 'KORG'          COLLATE NOCASE), 'TR-Rack',                                   'Synth'),
  ((SELECT id FROM manufacturers WHERE name = 'Ninja Tune'    COLLATE NOCASE), 'Break Beats ''N'' Grooves Volume Three',    'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Sound Ideas'   COLLATE NOCASE), 'Hanna-Barbera Sound FX Library',            'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Sound Ideas'   COLLATE NOCASE), 'The General Series 6000',                   'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'EastWest'      COLLATE NOCASE), 'Quantum Leap Brass',                        'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'IK Multimedia' COLLATE NOCASE), 'SampleTank XL',                             'Instrument');

INSERT INTO games (title, platform, released, composers, composers_normalized, notes) VALUES
  ('Space Channel 5',        'Dreamcast',          '1999-12-16', NULL, NULL, 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 9 Space Channel 5). Heavily sample-based score — ~30 cross-media samples from jazz/lounge/film soundtracks preserved as Sample: <artist> - <track> in raw_source.'),
  ('Space Channel 5: Part 2','Dreamcast, PlayStation 2, PC', '2002-02-14', NULL, NULL, 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 9 Space Channel 5). Includes "Live Recording: Michael Jackson (Beatboxing)" credit — Jackson was a fan of the original and contributed vocal samples for "Save Space Michael the Office Chief!"');

INSERT INTO usages
  (game_id, product_id, path_bank, preset, notes, raw_source, examples, category, source_family, position)
VALUES
  -- G1: Space Channel 5 — 84 main + 13 stuff_to_find = 97 rows
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   NULL, NULL, 'Timestamp 0:25', 'Brass Phrase', 'Interpolation: Hugo Montenegro - Wild Bike', '-Used throughout the soundtrack-', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   NULL, NULL, NULL, NULL, 'Live Recording: Koji Motosugi (Acoustic Bass)', '-Used throughout the soundtrack-', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   NULL, NULL, NULL, 'Various', 'Live Recording: Koji Motosugi (Electric Bass)', '-Used throughout the soundtrack-', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   NULL, NULL, NULL, NULL, 'Live Recording: Chewtaro Moritake (Electric Guitar (Wow Filter))', '-Used throughout the soundtrack-', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   NULL, NULL, NULL, 'Streamed tracks only', 'Live Recording: Yutaka Minobe (Electric Piano)', '-Used throughout the soundtrack-', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   NULL, NULL, 'Timestamp 0:00', 'Kick & Hi-Hat Oneshot', 'Sample: Albatros - Ha-Ri-Ah', NULL, 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   NULL, NULL, 'Timestamp 2:01', 'Brass', 'Sample: Al Caiola - The Mod Squad', '-Used throughout the soundtrack-', 'main', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   NULL, NULL, 'Timestamp 2:41', 'Hit', 'Sample: Armando Trovajoli - Blazing Magnum', 'Space Ship: Trapped in the Galaxy (Cockpit)', 'main', 'newer_vgm', 8),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   NULL, NULL, 'Timestamp 0:00', 'Organ Phrase', 'Sample: Armando Trovajoli - Masquerade', 'Spaceport: Introducing Ulala!! (Spaceport Check-in)', 'main', 'newer_vgm', 9),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   NULL, NULL, 'Timestamp 0:00', 'Cowbell Loop', 'Sample: Baden Powell - Blues A Volonte', 'Mororina♥: The Elegant Coward', 'main', 'newer_vgm', 10),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   NULL, NULL, 'Timestamp 1:35', 'String Crescendo', 'Sample: Berto Pisano - Kill Them All', 'Asteroid Belt: Go! Go! "Astrobeat Jr."', 'main', 'newer_vgm', 11),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   NULL, NULL, 'Timestamp 0:05', 'Bongo & Shaker Loop', 'Sample: Clarke-Boland Big Band - Un Grao De Areia', 'Mororina♥: The Elegant Coward', 'main', 'newer_vgm', 12),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   NULL, NULL, 'Timestamp 0:58', 'Brass Fall', 'Sample: Dick Schory - Shim-Wha', 'Spaceport: Introducing Ulala!! (Spaceport Check-in)', 'main', 'newer_vgm', 13),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   NULL, NULL, 'Timestamp 0:00', 'Drum Loop', 'Sample: Duke Ellington - Oclupaca', 'Space Channel 5: Getting The Truth (News Room)', 'main', 'newer_vgm', 14),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   NULL, NULL, 'Timestamp 4:40', 'Toms', 'Sample: Eddie Cano and His Sextet - Deep In A Drum', 'Spaceport: Introducing Ulala!! (Spaceport Check-in)', 'main', 'newer_vgm', 15),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   NULL, NULL, 'Timestamp 0:00', 'Brass Hit & Fall', 'Sample: Elmer Bernstein - Main Title from "The Silencers"', 'Spaceport: Introducing Ulala!! (Control Tower), Asteroid Belt: Go! Go! "Astrobeat Jr.", Evila: Attack of the Perfect Reporter', 'main', 'newer_vgm', 16),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   NULL, NULL, 'Timestamp 0:38', 'Bongo Loop', 'Sample: Elmer Bernstein - Main Title from "The Silencers"', 'Spaceport: Introducing Ulala!! (Luggage Room)', 'main', 'newer_vgm', 17),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   NULL, NULL, 'Timestamp 0:51, 0:55, 1:03', 'Brass', 'Sample: Elmer Bernstein - Main Title from "The Silencers"', 'Space Channel 5: Getting The Truth (News Room)', 'main', 'newer_vgm', 18),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   NULL, NULL, 'Timestamp 0:00', 'Piano Hit', 'Sample: Francis Coppieters - Piano In Transit', 'Asteroid Belt: Go! Go! "Astrobeat Jr."', 'main', 'newer_vgm', 19),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   NULL, NULL, 'Timestamp 0:21', 'Guitar & Plucked Piano', 'Sample: Henry Mancini - Charade (Main Title)', 'Evila: Attack of the Perfect Reporter', 'main', 'newer_vgm', 20),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   NULL, NULL, 'Timestamp 0:02, 0:06, 0:20, 0:23, 0:24', 'Brass Phrase, Drum Break', 'Sample: Hugo Montenegro - Wild Bike', 'Space Ship: Strut, Space Ship: Trapped in the Galaxy (Cockpit), Spaceport: Introducing Ulala!! (Spaceport Check-in)', 'main', 'newer_vgm', 21),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   NULL, NULL, 'Timestamp 2:09', 'Brass Hit', 'Sample: Hugo Montenegro - Run Spy Run', 'Space Ship: Trapped in the Galaxy (Cockpit)', 'main', 'newer_vgm', 22),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   NULL, NULL, 'Timestamp 1:30', 'Brass Hit', 'Sample: Jerry Goldsmith - The Man From U.N.C.L.E.', 'The Reporter from Space Channel 5, Spaceport: Introducing Ulala!! (Control Tower), Asteroid Belt: Go! Go! "Astrobeat Jr."', 'main', 'newer_vgm', 23),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   NULL, NULL, 'Timestamp 2:20', 'Horn Rip', 'Sample: John Williams - The Hunt (Unused)', 'Space Channel 5: Getting The Truth', 'main', 'newer_vgm', 24),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   NULL, NULL, 'Timestamp 2:13', 'Brass', 'Sample: John Williams - The Raptors Appear', 'Space Channel 5: Getting The Truth', 'main', 'newer_vgm', 25),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   NULL, NULL, 'n/a (various timestamps)', 'Multiple Elements', 'Sample: Ken Woodman - Mexican Flyer', 'Spaceport: Introducing Ulala!!, Evila: The Ultimate Reporter', 'main', 'newer_vgm', 26),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   NULL, NULL, 'Timestamp 0:04, 1:16 1:41', 'Drum Fill, Brass Hits', 'Sample: Lalo Schifrin - Dirty Harry', 'Giant Evila Space Dogfight!!', 'main', 'newer_vgm', 27),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   NULL, NULL, 'Timestamp 0:13', 'Harp & String Phrase', 'Sample: Lalo Schifrin - Maria', 'Giant Evila Space Dogfight!!', 'main', 'newer_vgm', 28),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   NULL, NULL, 'Timestamp 0:38', 'Bongo Loop', 'Sample: Lalo Schifrin - Mission: Impossible', 'Space Channel 5: Trapped in the Galaxy (Cockpit), Giant Evila Space Dogfight!!', 'main', 'newer_vgm', 29),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   NULL, NULL, 'Timestamp 1:14, 2:22', 'String Run, Piano Phrase', 'Sample: Lalo Schifrin - Rio After Dark', 'Giant Evila Space Dogfight!!', 'main', 'newer_vgm', 30),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   NULL, NULL, 'Timestamp 0:03, 0:39, 2:11', 'Multiple Elements', 'Sample: Marty Gold & His Orchestra - The Donkey Serenade', 'Spaceport: Introducing Ulala!! (Spaceport Check-in, Luggage Room, 2nd Floor Lobby)', 'main', 'newer_vgm', 31),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   NULL, NULL, 'Timestamp 2:58', 'Drum Fill', 'Sample: Pizzicato Five - Playboy Playgirl', 'Spaceport: Introducing Ulala!! (Spaceport Check-in)', 'main', 'newer_vgm', 32),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   NULL, NULL, 'Timestamp 0:10, 0:38, 0:43', 'Brass Hits', 'Sample: Quincy Jones - Ironside', 'Space Ship: Trapped in the Galaxy (Cockpit), Space Channel 5: Getting The Truth (Blank''s Office, Control Room)', 'main', 'newer_vgm', 33),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   NULL, NULL, 'Timestamp 0:00', 'Tambourine Loop', 'Sample: Russ Garcia And His Orchestra - Delicado', 'Evila: Attack of the Perfect Reporter', 'main', 'newer_vgm', 34),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   NULL, NULL, 'Timestamp 0:00', 'Drum Fill', 'Sample: Sid Bass - Valencia', 'Spaceport: Introducing Ulala!! (Spaceport Check-in)', 'main', 'newer_vgm', 35),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   NULL, NULL, 'Timestamp 0:06', 'Vocal', 'Sample: Wilson Simonal - Cai, Cai!', 'Pala Paya... Lounge Music', 'main', 'newer_vgm', 36),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   NULL, NULL, 'Timestamp 0:00', 'Piano Glissando', 'Sample: Xavier Cugat & His Orchestra - Danse Des Mirlitons', 'Spaceport: Introducing Ulala!! (Spaceport Check-in), Asteroid Belt: Go! Go! "Astrobeat Jr."', 'main', 'newer_vgm', 37),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Brass Super Section' COLLATE NOCASE),
   'Partition A -> SAX SHTFLL', 'SAX SHTFLL', 'Layered with TRP SHTFLL', NULL, 'Spaceport: Introducing Ulala!! (Control Tower)', 'main', 'newer_vgm', 38),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Brass Super Section' COLLATE NOCASE),
   'Partition C -> TRP SHTFLL', 'TRP SHTFLL', 'Layered with SAX SHTFLL', NULL, 'Spaceport: Introducing Ulala!! (Control Tower)', 'main', 'newer_vgm', 39),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Brass Super Section' COLLATE NOCASE),
   'Partition C -> TRP SWL 140', 'TRP SWL 140', NULL, NULL, 'Spaceport: Introducing Ulala!! (Control Tower)', 'main', 'newer_vgm', 40),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 1 -> BASS_140', 'D_SY17C', NULL, NULL, 'Morolian''s Base: Strange Path', 'main', 'newer_vgm', 41),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 1 -> BASS_140', 'D_SY17F', NULL, NULL, 'Morolian''s Base: Strange Path', 'main', 'newer_vgm', 42),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 1 -> DRUMTOOL', 'NATSNAR4', NULL, NULL, '-Used throughout the soundtrack-', 'main', 'newer_vgm', 43),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 1 -> HORNS', 'BS_13', NULL, NULL, 'Spaceport: Introducing Ulala!! (Control Tower)', 'main', 'newer_vgm', 44),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 1 -> LOOP_130', '130B_3', NULL, NULL, '-Used throughout the soundtrack-', 'main', 'newer_vgm', 45),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 1 -> LOOP_130', '130B_12', NULL, NULL, 'Mororina♥: The Elegant Coward', 'main', 'newer_vgm', 46),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 1 -> LOOP_130', '130B_17', NULL, NULL, 'Evila: Attack of the Perfect Reporter', 'main', 'newer_vgm', 47),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 1 -> LOOP_MIX', 'CLAPN_7', NULL, NULL, 'Space Ship: Strut, Space Ship: Trapped in the Galaxy (Cockpit)', 'main', 'newer_vgm', 48),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 2 -> GREGORIA', 'GL1_3', NULL, NULL, 'Mororina: The Elegant Coward', 'main', 'newer_vgm', 49),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 3 -> VOX_D_I', 'GONGADD', NULL, NULL, 'Coco★Tapioka: The Huge Dancer', 'main', 'newer_vgm', 50),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 3 -> VOX_D_I', 'HU', NULL, NULL, 'Coco★Tapioka: The Huge Dancer', 'main', 'newer_vgm', 51),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 3 -> VOX_D_I', 'HUYEAH1', NULL, NULL, 'Coco★Tapioka: The Huge Dancer', 'main', 'newer_vgm', 52),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Clavia' COLLATE NOCASE AND p.name = 'Nord Lead 2' COLLATE NOCASE),
   'Program ', '52 Space clavinet', NULL, NULL, 'Space Channel 5: Getting The Truth (Blank''s Office, Control Room)', 'main', 'newer_vgm', 53),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Clavia' COLLATE NOCASE AND p.name = 'Nord Lead 2' COLLATE NOCASE),
   NULL, NULL, 'Custom Patches', NULL, '-Used throughout the soundtrack-', 'main', 'newer_vgm', 54),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = '01/W' COLLATE NOCASE),
   'PROG -> Bank A', 'A01 16'' Piano', NULL, NULL, 'Spaceport: Introducing Ulala!!, Mororina♥: The Elegant Coward, Pala Paya... Lounge Music', 'main', 'newer_vgm', 55),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = '01/W' COLLATE NOCASE),
   'PROG -> Bank A', 'A61 Clav', NULL, NULL, '-Used throughout the soundtrack-', 'main', 'newer_vgm', 56),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = '01/W' COLLATE NOCASE),
   'PROG -> Bank B', 'B22 Brass 1', 'Layered with A77 Brass from the Roland D-70', NULL, '-Used throughout the soundtrack-', 'main', 'newer_vgm', 57),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'TR-Rack' COLLATE NOCASE),
   'Programs -> Bank A', 'A001 Acoustic Piano', NULL, NULL, 'Space Ship: Strut (Dining Hall), Getting The Truth (Control Room)', 'main', 'newer_vgm', 58),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'TR-Rack' COLLATE NOCASE),
   'Programs -> Bank A', 'A007 Stereo Strings', NULL, NULL, 'Mororina: The Elegant Coward, Evila: Attack of the Perfect Reporter', 'main', 'newer_vgm', 59),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'TR-Rack' COLLATE NOCASE),
   'Programs -> Bank A', 'A045 Vibraphone', NULL, NULL, 'Space Ship: Strut (Dining Hall), Mororina♥: The Elegant Coward, Getting The Truth (Control Room)', 'main', 'newer_vgm', 60),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'TR-Rack' COLLATE NOCASE),
   'Programs -> Bank A', 'A074 Garage Organ', NULL, NULL, 'Asteroid Belt: Go! Go! "Astrobeat Jr."', 'main', 'newer_vgm', 61),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'TR-Rack' COLLATE NOCASE),
   'Programs -> Bank A', 'A058 Jazz-Organ 2', NULL, NULL, '-Used throughout the soundtrack-', 'main', 'newer_vgm', 62),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'TR-Rack' COLLATE NOCASE),
   'Programs -> Bank A', 'A059 Future Synth', NULL, NULL, 'Morolian''s Base: Strange Path', 'main', 'newer_vgm', 63),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'TR-Rack' COLLATE NOCASE),
   'Programs -> Bank A', 'A063 Harp', NULL, NULL, 'Mororina: The Elegant Coward', 'main', 'newer_vgm', 64),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'TR-Rack' COLLATE NOCASE),
   'Programs -> Bank A', 'A088 Jazz/Brush Kits', 'Toms', NULL, 'Spaceport: Introducing Ulala!! (Luggage Room)', 'main', 'newer_vgm', 65),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'TR-Rack' COLLATE NOCASE),
   'Programs -> Bank A', 'A106 Gospel Organ', NULL, NULL, '-Used throughout the soundtrack-', 'main', 'newer_vgm', 66),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'TR-Rack' COLLATE NOCASE),
   'Programs -> Bank A', 'A112 Insectisuicides', 'In MULTI mode', NULL, 'Mororian''s Base: Strange Path', 'main', 'newer_vgm', 67),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'TR-Rack' COLLATE NOCASE),
   'Programs -> Bank B', 'B000 Sky Diver...', 'In MULTI mode', NULL, 'Space Ship: Trapped in the Galaxy (Cockpit)', 'main', 'newer_vgm', 68),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'TR-Rack' COLLATE NOCASE),
   'Programs -> Bank B', 'B008 Processed Kit', NULL, NULL, 'Space Ship: Strut (Dining Hall)', 'main', 'newer_vgm', 69),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'TR-Rack' COLLATE NOCASE),
   'Programs -> Bank B', 'B056 Timpani', NULL, NULL, 'Mororina♥: The Elegant Coward, Evila: Attack of the Perfect Reporter', 'main', 'newer_vgm', 70),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'TR-Rack' COLLATE NOCASE),
   'Programs -> Bank B', 'B058 Jazz-Organ 1', NULL, NULL, '-Used throughout the soundtrack-', 'main', 'newer_vgm', 71),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'TR-Rack' COLLATE NOCASE),
   'Programs -> Bank B', 'B088 Analog/Club Kits', NULL, NULL, '-Used throughout the soundtrack-', 'main', 'newer_vgm', 72),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'TR-Rack' COLLATE NOCASE),
   'Programs -> Bank C', 'C010 HipHop/Rap Kit', NULL, NULL, '-Used throughout the soundtrack-', 'main', 'newer_vgm', 73),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'TR-Rack' COLLATE NOCASE),
   'Programs -> Bank C', 'C090 AnalogSweeper', 'In MULTI mode', NULL, 'Mororian''s Base: Strange Path', 'main', 'newer_vgm', 74),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Ninja Tune' COLLATE NOCASE AND p.name = 'Break Beats ''N'' Grooves Volume Three' COLLATE NOCASE),
   'Track 10 -> TS 1:17', 'Energetic Fats (131 BPM)', NULL, NULL, 'Space Ship: Trapped in the Galaxy (Cockpit)', 'main', 'newer_vgm', 75),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Ninja Tune' COLLATE NOCASE AND p.name = 'Break Beats ''N'' Grooves Volume Three' COLLATE NOCASE),
   'Track 14 -> TS 1:51', 'Rusty Goes Ga Ga (104 BPM)', NULL, NULL, 'Space Channel 5: Getting The Truth (News Room)', 'main', 'newer_vgm', 76),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Polestar Magnetics' COLLATE NOCASE AND p.name = 'The X-Static Goldmine' COLLATE NOCASE),
   'CD 1 -> Track 27 -> Africa On D Move -> TS 0:11', 'Kano 108', NULL, NULL, 'Spaceport: Introducing Ulala!! (Spaceport Check-in)', 'main', 'newer_vgm', 77),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Polestar Magnetics' COLLATE NOCASE AND p.name = 'The X-Static Goldmine' COLLATE NOCASE),
   'CD 1 -> Track 27 -> Africa On D Move -> TS 0:23', 'Freetown 108', NULL, NULL, 'Spaceport: Introducing Ulala!! (Control Tower)', 'main', 'newer_vgm', 78),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'D-70' COLLATE NOCASE),
   'TONES -> A', 'A77 Brass', NULL, NULL, '-Used throughout the soundtrack-', 'main', 'newer_vgm', 79),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JD-800' COLLATE NOCASE),
   'Internal', 'I-53 Ac Piano 1', NULL, NULL, '-Used throughout the soundtrack-', 'main', 'newer_vgm', 80),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JV-80' COLLATE NOCASE),
   'Preset A', 'B52 Woody Bass 2', NULL, NULL, NULL, 'main', 'newer_vgm', 81),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sound Ideas' COLLATE NOCASE AND p.name = 'Hollywood Series 4000' COLLATE NOCASE),
   '4001-27-06', 'CARTOON, GONG', 'LARGE, CHINESE GONG, SOFT MALLET', NULL, 'Option: The Reporter From sch5, Mororina♥: The Elegant Coward', 'main', 'newer_vgm', 82),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 2' COLLATE NOCASE),
   'Track 06 - Breakbeat Live -> TS 0:04', '2 Bars (Human Beatbox)', NULL, NULL, 'Blank TV: Ulala Support Chant', 'main', 'newer_vgm', 83),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 2' COLLATE NOCASE),
   'Track 33 - Sci-fi techno FX -> TS 0:04', 'Hit 1', NULL, NULL, 'Morolian''s Base: Strange Path', 'main', 'newer_vgm', 84),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   NULL, NULL, NULL, 'Violin Phrase', 'Sample: Josef Suk - Op. 64: III. Allegretto non troppo', 'Giant Evila Space Dogfight!!', 'stuff_to_find', 'newer_vgm', 85),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   NULL, NULL, NULL, 'Piano Phrase', 'Sample: Sergio Mendes & Brasil 66'' - Tim Dom Dom', 'Pala Paya... Lounge Music', 'stuff_to_find', 'newer_vgm', 86),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = '01/W' COLLATE NOCASE),
   'PROG -> Bank A', 'A09 Total Kit', 'Hi-Hats', NULL, NULL, 'stuff_to_find', 'newer_vgm', 87),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Clavia' COLLATE NOCASE AND p.name = 'Nord Lead 2' COLLATE NOCASE),
   NULL, 'FMClavinet', 'Harpsichord Lead', NULL, 'Evila: Attack of the Perfect Reporter', 'stuff_to_find', 'newer_vgm', 88),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Clavia' COLLATE NOCASE AND p.name = 'Nord Lead 2' COLLATE NOCASE),
   NULL, NULL, 'Various', NULL, NULL, 'stuff_to_find', 'newer_vgm', 89),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   NULL, NULL, NULL, 'Brass Phrase', '? (Song Sample)', 'Coco★Tapioka: The Huge Dancer', 'stuff_to_find', 'newer_vgm', 90),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   NULL, NULL, NULL, 'Brass Hit', '? (Song Sample)', 'Space Channel 5: Getting The Truth', 'stuff_to_find', 'newer_vgm', 91),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   NULL, NULL, NULL, 'String Hit', '? (Song Sample)', 'Giant Evila Space Dogfight!!', 'stuff_to_find', 'newer_vgm', 92),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   NULL, NULL, NULL, 'Hit', '? (Song Sample)', 'Giant Evila Space Dogfight!!', 'stuff_to_find', 'newer_vgm', 93),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   NULL, NULL, NULL, 'Vocals', '? (Song Sample)', 'Pala Paya... Lounge Music', 'stuff_to_find', 'newer_vgm', 94),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   NULL, NULL, NULL, 'Drum Fill', '? (Song Sample)', 'Pala Paya... Lounge Music', 'stuff_to_find', 'newer_vgm', 95),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   NULL, NULL, NULL, 'Nutcracker Strings', '? (Song Sample)', 'Mororina♥: The Elegant Coward', 'stuff_to_find', 'newer_vgm', 96),
  ((SELECT id FROM games WHERE title = 'Space Channel 5'),
   NULL, NULL, NULL, 'Hoppin'' John Break', '? (DJ Tool?)', NULL, 'stuff_to_find', 'newer_vgm', 97),

  -- G2: Space Channel 5: Part 2 — 83 main + 14 stuff_to_find = 97 rows
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, NULL, NULL, 'Live Recording: Michael Jackson (Beatboxing)', 'Save Space Michael the Office Chief!', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, 'Timestamp 1:34', 'Percussion & Guitar Loop', 'Sample: Alan Parker - Black Light', 'We''re a Dancing Team!, Connected Hearts', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, 'Timestamp 0:00', 'Conga Loop', 'Sample: Alan Parker - Solid Satin', 'Perfection! Space Primary Schooler Band', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, 'Timestamp 0:00, 1:19, 1:21', 'Multiple Elements', 'Sample: Armando Trovajoli - Beat Trombone', 'Perfection! Space Primary Schooler Band', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, 'Timestamp 2:08', 'Strings and Snare Hit', 'Sample: Armando Trovajoli - Qualcosa Più Grande Di Noi', 'Perfection! Space Primary Schooler Band', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, 'Timestamp 0:00', 'Multiple Elements', 'Sample: Armando Trovajoli - Theme for a Murderer', 'Perfection! Space Primary Schooler Band, Connected Hearts, We''re a Dancing Team!', 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, 'Timestamp 6:04', 'Tom Drum Loop', 'Sample: Art Blakey - Quicksilver', 'Pursuers In The Sky', 'main', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, 'Timestamp 0:00', 'Brass Hits', 'Sample: Betty Moorer - It''s My Thing', 'Report1 - Ulala Again', 'main', 'newer_vgm', 8),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, 'Timestamp 2:22', 'Brass Hit', 'Sample: Bob Thompson - Mmm, Nice!', 'Rescue Before Melting', 'main', 'newer_vgm', 9),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, 'Timestamp 0:15', 'Brass Shake', 'Sample: Bob Thompson - People Will Say We''re In Love', 'Go Go Cheerleader', 'main', 'newer_vgm', 10),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, 'Timestamp 0:00, 2:18', 'Muted Trumpet & Xylophone, Brass Fall', 'Sample: Bob Thompson - The Song Is You', 'Rescue Before Melting', 'main', 'newer_vgm', 11),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, 'Timestamp 0:03', 'Drum Loop', 'Sample: Carlo Savina - 2968', 'Perfection! Space Primary Schooler Band', 'main', 'newer_vgm', 12),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, 'Timestamp 0:00', 'Conga Roll', 'Sample: Carlo Savina - Down left', 'Perfection! Space Primary Schooler Band', 'main', 'newer_vgm', 13),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, 'Timestamp 0:00', 'Tom Fill & Drum Loop', 'Sample: Charlotte Leslie - Les Filles C''est Fait...', 'Birdman Assembly', 'main', 'newer_vgm', 14),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, 'Timestamp 0:58', 'Brass Fall', 'Sample: Dick Schory - Shim-Wha', 'Connected Hearts', 'main', 'newer_vgm', 15),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, 'Timestamp 0:03, 2:48', 'Brass', 'Sample: Dizzy Gillespie - One Bass Hit, Pt. 2', 'Escape from the Flames', 'main', 'newer_vgm', 16),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, 'Timestamp 2:20', 'Brass', 'Sample: Dizzy Gillespie - Our Delight', 'Escape from the Flames', 'main', 'newer_vgm', 17),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, 'Timestamp 0:05, 0:10', 'Brass Hits', 'Sample: Dizzy Gillespie - Ray''s Idea', 'JINGLE Swinging Report Show!', 'main', 'newer_vgm', 18),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, 'Timestamp 2:42', 'Brass', 'Sample: Dizzy Gillespie - Things To Come', 'Escape from the Flames', 'main', 'newer_vgm', 19),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, 'Timestamp 0:01', 'Clave & Conga', 'Sample: Dolor Et Ses Étoiles - Bourrique La', 'This is My Happiness', 'main', 'newer_vgm', 20),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, 'Timestamp 0:00', 'Conga Roll', 'Sample: Eddie Cano - Deep In A Drum', 'INVASION! Song Mecha Kin Kon Kan, Perfection! Space Primary Schooler Band', 'main', 'newer_vgm', 21),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, 'Timestamp 3:17', 'Piano Hit', 'Sample: Francis Coppieters - Cross Talk', 'Guitar Showdown', 'main', 'newer_vgm', 22),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, 'Timestamp 0:27', 'Hits', 'Sample: Gino Peguri - Nightmare', 'Perfection! Space Primary Schooler Band, INVASION! Song Mecha Pon Piri', 'main', 'newer_vgm', 23),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, 'Timestamp 0:00, 0:15, 2:05', 'Multiple Elements', 'Sample: Henry Mancini - Charade (Main Title)', 'Guitar Showdown, Connected Hearts', 'main', 'newer_vgm', 24),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, 'Timestamp 4:53', 'Hi-Hat Oneshot', 'Sample: Horace Silver - Doodlin''', 'Pursuers In The Sky', 'main', 'newer_vgm', 25),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, 'Timestamp 0:54, 1:53', 'Brass', 'Sample: Hugo Montenegro - Jungle Heat', 'INVASION! Song Mecha Kin Kon Kan', 'main', 'newer_vgm', 26),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, 'Timestamp 1:21, 1:30', 'Brass Hits', 'Sample: Johnny Pearson - Assault Course', 'Perfection! Space Primary Schooler Band', 'main', 'newer_vgm', 27),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, 'n/a (various timestamps)', 'Multiple Elements', 'Sample: Ken Woodman - Mexican Flyer', 'We''re a Dancing Team!', 'main', 'newer_vgm', 28),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, 'Timestamp 0:03, 2:11', 'Brass Rip, String Rip & Timpani', 'Sample: Marty Gold & His Orchestra - The Donkey Serenade', 'INVASION! Song Mecha Kin Kon Kan, Connected Hearts', 'main', 'newer_vgm', 29),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, 'Timestamp 1:23, 2:50', 'Drum Fills', 'Sample: Orchestra Harlow - Horsin'' Up', 'Perfection! Space Primary Schooler Band, We''re a Dancing Team!', 'main', 'newer_vgm', 30),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, 'Timestamp 0:00', 'Hit', 'Sample: Peppino De Luca & Marc 4 - L''Uomo Dagli Occhi Di Ghiaccio', 'Perfection! Space Primary Schooler Band (Ingame Version)', 'main', 'newer_vgm', 31),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, 'Timestamp 0:12, 2:50', 'Brass', 'Sample: Quincy Jones - A Taste Of Honey', 'Pursuers In The Sky', 'main', 'newer_vgm', 32),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, 'Timestamp 1:09, 1:14', 'Brass Phrase', 'Sample: Quincy Jones - Chega De Saudade (No More Blues)', 'Pursuers In The Sky', 'main', 'newer_vgm', 33),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, 'Timestamp 0:04', 'Percussion Loop', 'Sample: Quincy Jones - Lalo Bossa Nova', 'Pursuers In The Sky', 'main', 'newer_vgm', 34),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, 'Timestamp 0:00', 'Drum Fill', 'Sample: Riz Ortolani - Cani E Gatti', 'Report1 - Ulala Again', 'main', 'newer_vgm', 35),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, 'Timestamp 2:55', 'Snare Hit', 'Sample: Rogerio Duprat - Meeting In Brazilia', 'Connected Hearts', 'main', 'newer_vgm', 36),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, 'Timestamp 2:38', 'Tom Solo', 'Sample: Royal Crown Revue - Hey Pachuco', 'INVASION! Song Mecha Kin Kon Kan', 'main', 'newer_vgm', 37),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, 'Timestamp 0:00', 'Tambourine Loop', 'Sample: Russ Garcia And His Orchestra - Delicado', 'Perfection! Space Primary Schooler Band, This is My Happiness', 'main', 'newer_vgm', 38),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, 'Timestamp 0:00', 'Drum Fill', 'Sample: Sid Bass - Valencia', 'We''re a Dancing Team!', 'main', 'newer_vgm', 39),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, 'Timestamp 1:42, 1:43, 1:44', 'Vocal & Brass Oneshots', 'Sample: The Brothers Johnson - Ain''t We Funkin'' Now', 'Strobe Action', 'main', 'newer_vgm', 40),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, 'Timestamp 0:00', 'Hit', 'Sample: The Command All-Stars - Perdido', 'Perfection! Space Primary Schooler Band', 'main', 'newer_vgm', 41),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, 'Timestamp 0:00', 'Drum Fill', 'Sample: The Electric Indian - My Cherie Amour', 'Birdman Assembly', 'main', 'newer_vgm', 42),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, 'Timestamp 0:50', 'String Glissando', 'Sample: The Heinz Kiessling Orchestra - Latin Carnival', 'INVASION! Song Mecha Pon Piri', 'main', 'newer_vgm', 43),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, 'Timestamp 4:01', 'Drum Loop', 'Sample: The Karminsky Experience Inc. - Mah Nà Mah Nà (Karmexperience Mix)', 'Perfection! Space Primary Schooler Band', 'main', 'newer_vgm', 44),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, 'Timestamp 2:20', 'Drum Loop', 'Sample: The Karminsky Experience Inc. - The Hip Sheik', 'Fountain Plaza', 'main', 'newer_vgm', 45),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, 'Timestamp 1:13', 'Conga Loop', 'Sample: The Paris Studio Group - Punching Ball', 'INVASION! Song Mecha Pon Piri', 'main', 'newer_vgm', 46),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, 'Timestamp 2:18', 'Hit', 'Sample: The Pete Jacques Orchestra - Bossa De Bahia', 'Guitar Showdown', 'main', 'newer_vgm', 47),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, 'Timestamp 1:14', 'Drum Fill', 'Sample: The Pierre Lavin Pop Band - In Advance (Re-Edit)', 'We''re a Dancing Team!', 'main', 'newer_vgm', 48),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, 'Timestamp 0:04', 'Drum Loop', 'Sample: The Ventures - Hawaii Five-O', 'Perfection! Space Primary Schooler Band', 'main', 'newer_vgm', 49),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, 'Timestamp 0:00', 'Piano Glissando', 'Sample: Xavier Cugat & His Orchestra - Danse Des Mirlitons', 'Desperate Dance Showdown, Connected Hearts', 'main', 'newer_vgm', 50),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, 'Timestamp 0:30', 'Drum Loop', 'Sample: Yasuharu Konishi - A Tribute To Simon Harris', 'Report4 - Signs of Great Disaster', 'main', 'newer_vgm', 51),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 2 -> BASIC', 'COLE_C', NULL, NULL, 'INVASION! Song Mecha Pon Piri', 'main', 'newer_vgm', 52),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 2 -> BASIC', 'COLE_D#', NULL, NULL, 'INVASION! Song Mecha Pon Piri', 'main', 'newer_vgm', 53),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 2 -> BASIC', 'SOB_F#', NULL, NULL, 'INVASION! Song Mecha Pon Piri', 'main', 'newer_vgm', 54),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 2 -> BASIC', 'TCS1_C', NULL, NULL, 'INVASION! Song Mecha Pon Piri', 'main', 'newer_vgm', 55),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 2 -> ORCHESTR', 'HAAR1', NULL, NULL, 'INVASION! Song Mecha Pon Piri', 'main', 'newer_vgm', 56),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Clavia' COLLATE NOCASE AND p.name = 'Nord Lead 2' COLLATE NOCASE),
   NULL, NULL, 'Custom Patches', NULL, '-Used throughout the soundtrack-', 'main', 'newer_vgm', 57),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Dance/Industrial' COLLATE NOCASE),
   'Track 01 -> TS 0:33', '101 Rhythm loop', 'house groove, huge sounds w/ barks', NULL, 'We''re a Dancing Team!', 'main', 'newer_vgm', 58),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Dance/Industrial' COLLATE NOCASE),
   'Track 26 - MIDI File Rhythm loops -> TS 0:30', '106 Rhythm loop', '2 bars - 70''s type groove w/ percussion', NULL, 'Save Space Michael the Office Chief!', 'main', 'newer_vgm', 59),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Dance/Industrial' COLLATE NOCASE),
   'Track 61 - Kick drums -> TS 0:24', 'Bass drum', 'solid, sound effect decay', NULL, 'Save Space Michael the Office Chief!', 'main', 'newer_vgm', 60),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Dance/Industrial' COLLATE NOCASE),
   'Track 76 - Miscellaneous -> TS 0:00', 'Effect', 'huge flanging slam', NULL, 'Save Space Michael the Office Chief!', 'main', 'newer_vgm', 61),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Dance/Industrial' COLLATE NOCASE),
   'Track 76 - Miscellaneous -> TS 0:05', 'Effect', 'wooden, dry slam', NULL, 'Save Space Michael the Office Chief!', 'main', 'newer_vgm', 62),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Dance/Industrial' COLLATE NOCASE),
   'Track 76 - Miscellaneous -> TS 0:20', 'Effect', 'breathy, click slam', NULL, 'Save Space Michael the Office Chief!', 'main', 'newer_vgm', 63),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Dance/Industrial' COLLATE NOCASE),
   'Track 77 - Miscellaneous -> TS 0:03', 'Effect', 'solid metallic click w/reverb', NULL, 'Save Space Michael the Office Chief!', 'main', 'newer_vgm', 64),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Dance/Industrial' COLLATE NOCASE),
   'Track 77 - Miscellaneous -> TS 0:09', 'Effect', 'ambient, flanging finger snap', NULL, 'Save Space Michael the Office Chief!', 'main', 'newer_vgm', 65),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Quantum Leap Brass' COLLATE NOCASE),
   'CD 2 -> Partition C -> VOLUME 002', '3TP SUS', NULL, NULL, 'INVASION! Song Suit Purge the King', 'main', 'newer_vgm', 66),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Quantum Leap Brass' COLLATE NOCASE),
   'CD 3 -> Partition F -> VOLUME 004', '3B SUSFF', NULL, NULL, 'INVASION! Song Mecha Kin Kon Kan, INVASION! Song Suit Purge the King', 'main', 'newer_vgm', 67),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'TR-Rack' COLLATE NOCASE),
   'PROG -> Bank A', 'A016 Indian Duet', NULL, NULL, 'Perfection! Space Primary Schooler Band (Ingame Version)', 'main', 'newer_vgm', 68),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'TR-Rack' COLLATE NOCASE),
   'PROG -> Bank D', 'D086 Radio Piano(SW1)', NULL, NULL, 'Perfection! Space Primary Schooler Band (Ingame Version)', 'main', 'newer_vgm', 69),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88 Pro' COLLATE NOCASE),
   'SC-88Pro Map', '049 000 Muted Trumpet', NULL, NULL, 'Indication of a Great Disaster', 'main', 'newer_vgm', 70),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sound Ideas' COLLATE NOCASE AND p.name = 'Hanna-Barbera Sound FX Library' COLLATE NOCASE),
   'HB02-72-01', 'BIRD, ROOSTER', 'ROOSTER MORNING CALL, ANIMAL', NULL, 'Birdman Assembly', 'main', 'newer_vgm', 71),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sound Ideas' COLLATE NOCASE AND p.name = 'Hanna-Barbera Sound FX Library' COLLATE NOCASE),
   'HB02-72-02', 'BIRD, ROOSTER', 'ROOSTER MORNING CALL, ANIMAL', NULL, 'Birdman Assembly', 'main', 'newer_vgm', 72),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sound Ideas' COLLATE NOCASE AND p.name = 'Hollywood Series 4000' COLLATE NOCASE),
   '4001-27-06', 'CARTOON, GONG', 'LARGE, CHINESE GONG, SOFT MALLET', NULL, 'We''re a Dancing Team!, INVASION! Song Mecha Kin Kon Kan, Perfection! Space Primary Schooler Band, Birdman Assembly', 'main', 'newer_vgm', 73),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sound Ideas' COLLATE NOCASE AND p.name = 'The General Series 6000' COLLATE NOCASE),
   '6003-25-03', 'BIRD, PIGEON', 'FLAPPING WINGS, CLOSE UP, ANIMAL', NULL, 'Birdman Assembly', 'main', 'newer_vgm', 74),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sound Ideas' COLLATE NOCASE AND p.name = 'The General Series 6000' COLLATE NOCASE),
   '6003-28-02', 'BIRD, ROOSTER', 'MORNING CALL, ANIMAL', NULL, 'Birdman Assembly', 'main', 'newer_vgm', 75),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Ueberschall' COLLATE NOCASE AND p.name = 'Easy Listening' COLLATE NOCASE),
   'Track 33 -> TS 0:08', 'Brass Hit', NULL, NULL, 'Purge TV Show', 'main', 'newer_vgm', 76),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 2' COLLATE NOCASE),
   'Track 04 - Breakbeat Live -> TS 0:09', '2 Bars', NULL, NULL, 'Save Space Michael the Office Chief!', 'main', 'newer_vgm', 77),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 2' COLLATE NOCASE),
   'Track 04 - Breakbeat Live -> TS 0:19', '1 Bar', NULL, NULL, 'Connected Hearts', 'main', 'newer_vgm', 78),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 2' COLLATE NOCASE),
   'Track 04 - Breakbeat Live -> TS 0:43', '2 Bars', NULL, NULL, 'INVASION! Song Mecha Pon Piri', 'main', 'newer_vgm', 79),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 2' COLLATE NOCASE),
   'Track 07 - Breakbeat Live -> TS 0:12', '1 Bar', NULL, NULL, 'Save Space Michael the Office Chief!', 'main', 'newer_vgm', 80),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 2' COLLATE NOCASE),
   'Track 10 - Breakbeat Live -> TS 0:04', '2 Bars', NULL, NULL, 'Save Space Michael the Office Chief!', 'main', 'newer_vgm', 81),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 2' COLLATE NOCASE),
   'Track 74 - House horn stabs -> TS 0:11', 'Nos. 1-10', NULL, NULL, 'Save Space Michael the Office Chief!', 'main', 'newer_vgm', 82),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 2' COLLATE NOCASE),
   'Track 75 - Stabs -> TS 0:00', 'House orch. stab Nos. 1-8', NULL, NULL, 'Save Space Michael the Office Chief!', 'main', 'newer_vgm', 83),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, NULL, 'Blue Danube samples', 'Sample: ? - Blue Danube', 'INVASION! Song Mecha Pon Piri', 'stuff_to_find', 'newer_vgm', 84),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Brass Super Section' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, 'Let''s Shoot and Rescue!, Pine''s Theme', 'stuff_to_find', 'newer_vgm', 85),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'IK Multimedia' COLLATE NOCASE AND p.name = 'SampleTank XL' COLLATE NOCASE),
   'Winds', 'Recorder', 'Probably just TR-Rack instead', NULL, 'Perfection! Space Primary Schooler Band', 'stuff_to_find', 'newer_vgm', 86),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, NULL, 'Crash Cymbal', 'KORG - ?', 'Save Space Michael the Office Chief!', 'stuff_to_find', 'newer_vgm', 87),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, NULL, 'Tremolo Strings', 'Roland - ?', 'INVASION! Song Mecha Kin Kon Kan', 'stuff_to_find', 'newer_vgm', 88),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, NULL, 'The rest of the (non-intro) bird sounds', 'Sound Ideas - ?', 'Birdman Assembly', 'stuff_to_find', 'newer_vgm', 89),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, NULL, 'Cinematic Brass', '? (Sample Library?)', 'INVASION! Song Mecha Kin Kon Kan', 'stuff_to_find', 'newer_vgm', 90),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, NULL, 'Snare Hits', '? (Song Sample)', 'Pursuers In The Sky', 'stuff_to_find', 'newer_vgm', 91),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, NULL, 'Brass Phrase', '? (Song Sample)', 'Rescue Before Melting', 'stuff_to_find', 'newer_vgm', 92),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, NULL, 'Xylophone Hit', '? (Song Sample)', 'Guitar Showdown', 'stuff_to_find', 'newer_vgm', 93),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, NULL, 'Brass Hit', '? (Song Sample)', 'Connected Hearts', 'stuff_to_find', 'newer_vgm', 94),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, NULL, 'Brass Hits', '? (Song Sample)', 'Birdman Assembly', 'stuff_to_find', 'newer_vgm', 95),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, NULL, 'Ride Cymbal Loop', '? (Song Sample)', 'Birdman Assembly', 'stuff_to_find', 'newer_vgm', 96),
  ((SELECT id FROM games WHERE title = 'Space Channel 5: Part 2'),
   NULL, NULL, NULL, 'Accordion', NULL, 'Perfection! Space Primary Schooler Band', 'stuff_to_find', 'newer_vgm', 97);
