-- NEWER VGM SEGA/Atlus — Section 10 part A (Jet Set Radio + E3 Prototype)
--
-- Source: reference/NEWER VGM Sound Sources - SEGAAtlus.csv lines 1356-1581.
-- 2 game records, ~219 usage rows. Section 10 split into 10a / 10b — JSR
-- Future has its own seed file due to total section size.
--
-- Jet Set Radio E3 Prototype (April 2000) split into its own game record
-- per the HotD Arcade Prototype / Puyo Puyo Sun split convention. The CSV
-- identifies a distinct prototype build with samples (Beastie Boys,
-- fIREHOSE) and synth gear (KORG MS-20, Roland System-100M) seen on the
-- "Holiday Plug-In!" promotional cover.
--
-- Verbatim preservations (Rule 2):
--   - Dual JP/Western title "Jet Set Radio / Jet Grind Radio".
--   - "Sample: Miles Davis - High Speed Chase" (T1376) — same Miles Davis
--     track sampled by SEGA Rally 2 in Section 5. Cross-game sample reuse.
--   - "Live Recording: B.B. Rights/Billy Brown (Vocals)" + F-Fields
--     (Electric Guitar) — the iconic "Jet Set Radio!" station IDs.
--   - "DJ Toolz / Break Beats 'N' Grooves Vol. 3" preserved distinct
--     from "Ninja Tune / Break Beats 'N' Grooves Volume Three" — possibly
--     same library but different publisher attributions in CSV.
--   - "KORG / TRINITY proX" — new variant joining TRINITY and TRINITY pro
--     in the DB.
--   - E3 build "(Fuzita Blender)" parenthetical examples preserved as-is.

INSERT OR IGNORE INTO manufacturers (name) VALUES
  ('DJ Toolz'),
  ('Freeze Records'),
  ('Wizoo'),
  ('Profile Records');

INSERT OR IGNORE INTO products (manufacturer_id, name, type) VALUES
  ((SELECT id FROM manufacturers WHERE name = 'AMG'              COLLATE NOCASE), 'Diffusion Series: The Next Generation',     'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'AMG'              COLLATE NOCASE), 'Now CD-ROM',                                'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Best Service'     COLLATE NOCASE), 'Killer Horns',                              'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'DJ Toolz'         COLLATE NOCASE), 'Break Beats ''N'' Grooves Vol. 3',          'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'EastWest'         COLLATE NOCASE), 'Chronic Horns',                             'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'EastWest'         COLLATE NOCASE), 'Funky Ass Loops',                           'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'e-LAB'            COLLATE NOCASE), 'Strictly 12 Inch',                          'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'e-LAB'            COLLATE NOCASE), 'The X-Static Sample Disc',                  'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Freeze Records'   COLLATE NOCASE), 'Trey Max - Top Secret CD Beats Vol. 3',     'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Hollywood Edge'   COLLATE NOCASE), 'The Premiere Edition 1',                    'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'KORG'             COLLATE NOCASE), 'TRINITY proX',                              'Synth'),
  ((SELECT id FROM manufacturers WHERE name = 'KORG'             COLLATE NOCASE), 'MS-20',                                     'Synth'),
  ((SELECT id FROM manufacturers WHERE name = 'Profile Records'  COLLATE NOCASE), 'Sample City',                               'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Roland'           COLLATE NOCASE), 'System-100M',                               'Synth'),
  ((SELECT id FROM manufacturers WHERE name = 'Spectrasonics'    COLLATE NOCASE), 'Heart of Asia',                             'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Wizoo'            COLLATE NOCASE), 'Cologne Cyclez 1 + 2',                      'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Zero-G'           COLLATE NOCASE), 'Beats N'' The Hood',                        'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Zero-G'           COLLATE NOCASE), 'Dance Vocals',                              'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Zero-G'           COLLATE NOCASE), 'Electric Dreamz',                           'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Zero-G'           COLLATE NOCASE), 'Global S.F.X.',                             'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Zero-G'           COLLATE NOCASE), 'Rhythm Guitar & FX',                        'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Zero-G'           COLLATE NOCASE), 'The Funky Element',                         'Sample Library');

INSERT INTO games (title, platform, released, composers, composers_normalized, notes) VALUES
  ('Jet Set Radio / Jet Grind Radio', 'Dreamcast, Game Boy Advance, PlayStation 3, Xbox 360, PC, PlayStation Vita, iOS, Android, Nintendo Switch, PlayStation 4, Xbox One', '2000-06-29', NULL, NULL, 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 10 Jet Set Radio). Dual JP/Western title preserved verbatim (JP "Jet Set Radio" / NA "Jet Grind Radio"). CSV says "(Original Music by: See note)" — composers listed inline include B.B. Rights, Billy Brown, F-Fields. The Hideki Naganuma soundtrack borrowed heavily from sample CDs; ~16 cross-media samples identified, plus 179 total identified manufacturer rows + 32 stuff_to_find.'),
  ('Jet Set Radio E3 Prototype',     'Dreamcast',                                                       '2000-04-28', NULL, NULL, 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 10 Jet Set Radio). E3 demo build shown April 2000, distinct from the June 2000 release. Notable extras: Beastie Boys "(You Gotta) Fight For Your Right (To Party!)" and fIREHOSE "Windmilling" samples in the "Fuzita Blender" placeholder track. Synths KORG MS-20 and Roland System-100M seen on cover of the "Holiday Plug-In!" promo CD.');

INSERT INTO usages
  (game_id, product_id, path_bank, preset, notes, raw_source, examples, category, source_family, position)
VALUES
  -- G1: Jet Set Radio / Jet Grind Radio — 179 main + 32 stuff = 211 rows
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   NULL, NULL, NULL, '"Jet Set Radio!"', 'Live Recording: B.B. Rights (Vocals)', 'Funky Radio', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   NULL, NULL, NULL, '"Jet Set Radio!"', 'Live Recording: Billy Brown (Vocals)', 'Jet Set Station', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   NULL, NULL, NULL, NULL, 'Live Recording: F-Fields (Electric Guitar)', 'Yellow Bream', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   NULL, NULL, 'Timestamp 0:01', 'Drums', 'Sample: Blooblo - Superstition', 'Jurassic 5 - Improvise', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   NULL, NULL, 'Timestamp 1:00', 'Drums', 'Sample: Carleen & the Groovers - Can We Rap', 'Featurecast - Recipe for the Perfect Afro', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   NULL, NULL, 'Timestamp 4:50', 'Drums', 'Sample: The Chemical Brothers - Dig Your Own Hole', 'Sneakman', 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   NULL, NULL, 'Timestamp 0:00', 'Drum Fill', 'Sample: Cibo Matto - Spoon', 'Sweet Soul Brother, Jet Set Groove #1', 'main', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   NULL, NULL, 'Timestamp 0:11', 'Piano', 'Sample: Cut & Paste - Take a Piece of America', 'Grace & Glory', 'main', 'newer_vgm', 8),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   NULL, NULL, 'Timestamp 6:44', 'Drums', 'Sample: Cut & Paste - Watch Me Rollin''', 'Sneakman', 'main', 'newer_vgm', 9),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   NULL, NULL, 'Timestamp 1:22', 'Big Snare (R)', 'Sample: Fatboy Slim - Always Read The Label', 'That''s Enough', 'main', 'newer_vgm', 10),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   NULL, NULL, 'Timestamp 5:11', 'Big Kick (R)', 'Sample: Fatboy Slim - Kalifornia', 'That''s Enough', 'main', 'newer_vgm', 11),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   NULL, NULL, 'Timestamp 0:57', 'Additional Drum Loop w/Hard Snare', 'Sample: Galt MacDermot - Space', 'Humming The Bassline', 'main', 'newer_vgm', 12),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   NULL, NULL, 'Timestamp 0:00', 'Guitar', 'Sample: Guy Jean - Sitting by The River', 'Jurassic 5 - Improvise', 'main', 'newer_vgm', 13),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   NULL, NULL, 'Timestamp 0:03', 'Beatbox', 'Sample: James Brown - Godfather Runnin'' The Joint', 'That''s Enough', 'main', 'newer_vgm', 14),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   NULL, NULL, 'Timestamp 0:13', 'Stab', 'Sample: James Brown - Godfather Runnin'' The Joint', 'That''s Enough', 'main', 'newer_vgm', 15),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   NULL, NULL, 'Timestamp 0:19, 0:25', '"Bass" & "Fatback Drums"', 'Sample: King Curtis - Memphis Soul Stew', 'Featurecast - Recipe for the Perfect Afro', 'main', 'newer_vgm', 16),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   NULL, NULL, 'Timestamp 0:00', 'Horn Sustain', 'Sample: Miles Davis - High Speed Chase', 'Let Mom Sleep', 'main', 'newer_vgm', 17),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   NULL, NULL, 'Timestamp 0:04', 'Shout', 'Sample: Paula Abdul - One Or The Other (1990 Mix)', 'Sneakman', 'main', 'newer_vgm', 18),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   NULL, NULL, 'Timestamp 0:19', 'Bass', 'Sample: Quincy Jones - The Hot Rock Theme', 'Jurassic 5 - Improvise', 'main', 'newer_vgm', 19),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG' COLLATE NOCASE AND p.name = 'Diffusion Series: The Next Generation' COLLATE NOCASE),
   '160dB', '010_D&B1', 'Upright Bass 3', NULL, 'Humming The Bassline', 'main', 'newer_vgm', 20),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG' COLLATE NOCASE AND p.name = 'Diffusion Series: The Next Generation' COLLATE NOCASE),
   '160dB', '150_D&B1', 'Gated FX 5', NULL, 'Let Mom Sleep', 'main', 'newer_vgm', 21),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG' COLLATE NOCASE AND p.name = 'Diffusion Series: The Next Generation' COLLATE NOCASE),
   'BIIB1_2', 'Rub-Roll', NULL, NULL, 'Moody''s Shuffle', 'main', 'newer_vgm', 22),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG' COLLATE NOCASE AND p.name = 'Diffusion Series: The Next Generation' COLLATE NOCASE),
   'ROL1', '058_POP', 'Bata Drum Pattern - Mono', NULL, 'Humming The Bassline', 'main', 'newer_vgm', 23),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG' COLLATE NOCASE AND p.name = 'Diffusion Series: The Next Generation' COLLATE NOCASE),
   'RUFFCUTZ -> HUSTLER', 'HUSTLER 1', NULL, NULL, 'Humming The Bassline', 'main', 'newer_vgm', 24),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG' COLLATE NOCASE AND p.name = 'Diffusion Series: The Next Generation' COLLATE NOCASE),
   'RUFFCUTZ -> USER', 'USER 2', NULL, NULL, 'Grace & Glory', 'main', 'newer_vgm', 25),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG' COLLATE NOCASE AND p.name = 'Diffusion Series: The Next Generation' COLLATE NOCASE),
   'T-HEAD', '001_TH1', 'Hook Drums (R)', NULL, 'Sneakman', 'main', 'newer_vgm', 26),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG' COLLATE NOCASE AND p.name = 'Diffusion Series: The Next Generation' COLLATE NOCASE),
   'T-HEAD', '020_TH1', 'Funky Crunch Gate Corner', NULL, 'That''s Enough', 'main', 'newer_vgm', 27),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG' COLLATE NOCASE AND p.name = 'Gota Yashiki - Groove Activator' COLLATE NOCASE),
   'Track 46 - Grooves -> TS 0:00', 'Jammer - 120 bpm', NULL, NULL, 'Mischievous Boy', 'main', 'newer_vgm', 28),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG' COLLATE NOCASE AND p.name = 'Now CD-ROM' COLLATE NOCASE),
   'Partition A -> COLDCUT 1', 'PLAY IT', '"Play it"', NULL, 'Everybody Jump Around', 'main', 'newer_vgm', 29),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG' COLLATE NOCASE AND p.name = 'Now CD-ROM' COLLATE NOCASE),
   'Partition A -> MEGABASS 1', 'MEGABASS T1', 'DANCE-MUSI, TOO SOFT, IDENTIFYBT', NULL, 'Everybody Jump Around', 'main', 'newer_vgm', 30),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG' COLLATE NOCASE AND p.name = 'Now CD-ROM' COLLATE NOCASE),
   'Partition G -> B.2.B VOL 1', 'BLACK2BLACK1', 'ALARMING105, RUBNROLL93', NULL, 'Everybody Jump Around', 'main', 'newer_vgm', 31),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG' COLLATE NOCASE AND p.name = 'Now CD-ROM' COLLATE NOCASE),
   'Partition J -> PASCAL 1', 'SPACED OUT', NULL, NULL, 'Funky Radio', 'main', 'newer_vgm', 32),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG' COLLATE NOCASE AND p.name = 'Now CD-ROM' COLLATE NOCASE),
   'Partition J -> PASCAL 3', 'HIP-HOP GATE', NULL, NULL, 'Everybody Jump Around', 'main', 'newer_vgm', 33),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG & Hit Music' COLLATE NOCASE AND p.name = 'Norman Cook - Skip to my Loops' COLLATE NOCASE),
   'Track 13 - 108 BPM -> TS 0:10', 'Sidewalk 2', NULL, NULL, 'Let Mom Sleep', 'main', 'newer_vgm', 34),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG & Hit Music' COLLATE NOCASE AND p.name = 'Norman Cook - Skip to my Loops' COLLATE NOCASE),
   'Track 50 - Misc. FX -> TS 0:05', 'Japanese Girl', NULL, NULL, 'Let Mom Sleep', 'main', 'newer_vgm', 35),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Hallelujah' COLLATE NOCASE),
   'Partition F -> RAPPER 1-2', 'RAP PHRASES1', 'RAPHRASE10', NULL, 'Everybody Jump Around', 'main', 'newer_vgm', 36),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Hallelujah' COLLATE NOCASE),
   'Partition F -> MOUTH PERC.', 'MOUTH PERCUS', 'VOCDRUM 2', NULL, 'Everybody Jump Around', 'main', 'newer_vgm', 37),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Killer Horns' COLLATE NOCASE),
   'Track 14 - Brass Sections -> TS 0:10', 'brass section 114 shf.', NULL, NULL, 'Everybody Jump Around', 'main', 'newer_vgm', 38),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Killer Horns' COLLATE NOCASE),
   'Track 19 - Brass Sections  -> TS 0:07', 'tenor/baritone 148 str./shf. Gmaj', NULL, NULL, 'Everybody Jump Around', 'main', 'newer_vgm', 39),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Killer Horns' COLLATE NOCASE),
   'Track 19 - Brass Sections  -> TS 0:28', 'brass section 112 shf.', NULL, NULL, 'Everybody Jump Around', 'main', 'newer_vgm', 40),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Killer Horns' COLLATE NOCASE),
   'Track 20 - Brass Sections -> TS 0:02', 'brass section 112 str.', NULL, NULL, 'Everybody Jump Around', 'main', 'newer_vgm', 41),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 1 -> GUIT_140', 'COUNTRYG', NULL, NULL, 'Sweet Soul Brother', 'main', 'newer_vgm', 42),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 1 -> GUIT_140', 'OCTAVE_G', NULL, NULL, 'Let Mom Sleep, Sweet Soul Brother', 'main', 'newer_vgm', 43),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 1 -> GUIT_140', 'SNGLWAHA', NULL, NULL, 'Sneakman', 'main', 'newer_vgm', 44),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 1 -> GUIT_140', 'WAH___G', NULL, NULL, 'Let Mom Sleep, Sweet Soul Brother', 'main', 'newer_vgm', 45),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 1 -> GUIT_160', 'WAHWAH_A', NULL, NULL, 'Sneakman', 'main', 'newer_vgm', 46),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 1 -> HORNS', 'BS_11', NULL, NULL, 'Jet Set Groove #1', 'main', 'newer_vgm', 47),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 2 -> ORCHESTR', 'WSG_F#', NULL, NULL, 'Sneakman', 'main', 'newer_vgm', 48),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 2 -> ORCHESTR', 'WST_D#', NULL, NULL, 'Sneakman', 'main', 'newer_vgm', 49),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 3 -> GREGORIA', 'GG_B', NULL, NULL, 'Grace & Glory', 'main', 'newer_vgm', 50),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 3 -> GREGORIA', 'GG_C', NULL, NULL, 'Grace & Glory', 'main', 'newer_vgm', 51),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 3 -> VOX_A_C', 'CLASSIC1', NULL, NULL, 'Grace & Glory', 'main', 'newer_vgm', 52),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 3 -> VOX_A_C', 'COMEON10', NULL, NULL, 'Rock It On', 'main', 'newer_vgm', 53),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 3 -> VOX_D_I', 'HA2', NULL, NULL, 'Humming The Bassline', 'main', 'newer_vgm', 54),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 3 -> VOX_D_I', 'HEY', NULL, NULL, 'Sweet Soul Brother', 'main', 'newer_vgm', 55),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 3 -> VOX_D_I', 'HUAH', NULL, NULL, 'Sneakman', 'main', 'newer_vgm', 56),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 3 -> VOX_J_R', 'OUH', NULL, NULL, 'Jet Set Groove #2', 'main', 'newer_vgm', 57),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 3 -> VOX_J_R', 'PRAY_1', NULL, NULL, 'Grace & Glory', 'main', 'newer_vgm', 58),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 3 -> VOX_J_R', 'PRAY_2', NULL, NULL, 'Grace & Glory', 'main', 'newer_vgm', 59),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 3 -> VOX_S_Z', 'VIVA', NULL, NULL, 'Rock It On', 'main', 'newer_vgm', 60),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 3 -> VOX_S_Z', 'WAUHAU', NULL, NULL, 'Rock It On', 'main', 'newer_vgm', 61),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 3 -> VOX_S_Z', 'YEAH', NULL, NULL, 'Humming The Bassline', 'main', 'newer_vgm', 62),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'DJ Toolz' COLLATE NOCASE AND p.name = 'Break Beats ''N'' Grooves Vol. 3' COLLATE NOCASE),
   'Track 02 -> TS 0:06', 'Show Me (148 BPM)', 'Organ hit', NULL, 'Let Mom Sleep', 'main', 'newer_vgm', 63),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'DJ Toolz' COLLATE NOCASE AND p.name = 'Break Beats ''N'' Grooves Vol. 3' COLLATE NOCASE),
   'Track 05 -> TS 0:01', 'Intercontinental (110 BPM)', 'AUGH', NULL, 'Humming The Bassline', 'main', 'newer_vgm', 64),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Chronic Horns' COLLATE NOCASE),
   'CD 1 -> Track 19 - Section & Solo Riffs -> TS 0:03', 'Section Riffs G# min 2', '20.02 RIFF', NULL, 'Let Mom Sleep', 'main', 'newer_vgm', 65),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Dance/Industrial II' COLLATE NOCASE),
   'Demo Track', 'Timestamp 0:29', '3.6 SCRTCH', NULL, 'Moody''s Shuffle', 'main', 'newer_vgm', 66),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Dance/Industrial II' COLLATE NOCASE),
   'Demo Track', 'Timestamp 1:05', 'Drums', NULL, 'Moody''s Shuffle', 'main', 'newer_vgm', 67),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Funky Ass Loops' COLLATE NOCASE),
   'Demo Track', 'Timestamp 0:39', '1.5 LOOP', NULL, 'Moody''s Shuffle', 'main', 'newer_vgm', 68),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'e-LAB' COLLATE NOCASE AND p.name = 'Strictly 12 Inch' COLLATE NOCASE),
   'Demos -> 08_XTcFiles_of_Jungle', 'FC01_Lop_170bpm', NULL, NULL, 'Jet Set Station', 'main', 'newer_vgm', 69),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'e-LAB' COLLATE NOCASE AND p.name = 'Strictly 12 Inch' COLLATE NOCASE),
   'XSa_LoopTools -> SA_130_Loops', 'SA3301_Loop_Houseclip', NULL, NULL, 'Electric Toothbrush', 'main', 'newer_vgm', 70),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'e-LAB' COLLATE NOCASE AND p.name = 'The X-Static Sample Disc' COLLATE NOCASE),
   'Track 05 -> TS 0:21', 'SAMPLES FROM X4', 'Trippy Guitars', NULL, 'Humming The Bassline', 'main', 'newer_vgm', 71),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'e-LAB' COLLATE NOCASE AND p.name = 'The X-Static Sample Disc' COLLATE NOCASE),
   'Track 09 -> TS 1:26', 'SAMPLES FROM V2', 'Drum Beat', NULL, 'Sweet Soul Brother', 'main', 'newer_vgm', 72),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'e-LAB' COLLATE NOCASE AND p.name = 'The X-Static Sample Disc' COLLATE NOCASE),
   'Track 11 -> TS 0:45', 'SAMPLES FROM XFT', '"Flip the raps, flip the tracks"', NULL, 'Grace & Glory', 'main', 'newer_vgm', 73),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'e-LAB' COLLATE NOCASE AND p.name = 'The X-Static Sample Disc' COLLATE NOCASE),
   'Track 13 -> TS 0:00', 'SAMPLES FROM X2', 'Drum Beat', NULL, 'Jet Set Groove #2', 'main', 'newer_vgm', 74),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'e-LAB' COLLATE NOCASE AND p.name = 'The X-Static Sample Disc' COLLATE NOCASE),
   'Track 13 -> TS 0:11', 'SAMPLES FROM X2', 'Drum Beat', NULL, 'Humming The Bassline', 'main', 'newer_vgm', 75),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'e-LAB' COLLATE NOCASE AND p.name = 'The X-Static Sample Disc' COLLATE NOCASE),
   'Track 13 -> TS 0:14', 'SAMPLES FROM X2', 'Drum Beat', NULL, 'That''s Enough', 'main', 'newer_vgm', 76),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'e-LAB' COLLATE NOCASE AND p.name = 'The X-Static Sample Disc' COLLATE NOCASE),
   'Track 13 -> TS 0:24', 'SAMPLES FROM X2', 'Bass', NULL, 'Sneakman', 'main', 'newer_vgm', 77),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'e-LAB' COLLATE NOCASE AND p.name = 'The X-Static Sample Disc' COLLATE NOCASE),
   'Track 17 -> TS 0:09', 'SAMPLES FROM V1', 'Drum Beat', NULL, 'Rock It On, Jet Set Groove #1', 'main', 'newer_vgm', 78),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'e-LAB' COLLATE NOCASE AND p.name = 'The X-Static Sample Disc' COLLATE NOCASE),
   'Track 17 -> TS 0:24', 'SAMPLES FROM V1', 'Drum layer', NULL, 'Let Mom Sleep', 'main', 'newer_vgm', 79),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'e-LAB' COLLATE NOCASE AND p.name = 'X-Files of Jungle' COLLATE NOCASE),
   'Track 23 - -159 BPM -Steel Snares', 'XTENDED DRUM LOOP', 'Drums (R), Roll', NULL, 'Sweet Soul Brother', 'main', 'newer_vgm', 80),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Freeze Records' COLLATE NOCASE AND p.name = 'Trey Max - Top Secret CD Beats Vol. 3' COLLATE NOCASE),
   'Track 27 -> TS 0:10', 'GRUNT', NULL, NULL, 'Let Mom Sleep', 'main', 'newer_vgm', 81),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Freeze Records' COLLATE NOCASE AND p.name = 'Trey Max - Top Secret CD Beats Vol. 3' COLLATE NOCASE),
   'Track 28 -> TS 0:00', '"HE''S A SWEET SOUL BROTHER"', NULL, NULL, 'Sweet Soul Brother', 'main', 'newer_vgm', 82),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Freeze Records' COLLATE NOCASE AND p.name = 'Trey Max - Top Secret CD Beats Vol. 3' COLLATE NOCASE),
   'Track 29 -> TS 0:10', 'GRUNT', NULL, NULL, 'Let Mom Sleep', 'main', 'newer_vgm', 83),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Freeze Records' COLLATE NOCASE AND p.name = 'Trey Max - Top Secret CD Beats Vol. 3' COLLATE NOCASE),
   'Track 29 -> TS 0:13', 'FEMALE VOCAL RIFF', NULL, NULL, 'That''s Enough', 'main', 'newer_vgm', 84),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Freeze Records' COLLATE NOCASE AND p.name = 'Trey Max - Top Secret CD Beats Vol. 3' COLLATE NOCASE),
   'Track 29 -> TS 0:17', '"BREAK DOWN"', NULL, NULL, 'Sneakman', 'main', 'newer_vgm', 85),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Freeze Records' COLLATE NOCASE AND p.name = 'Trey Max - Top Secret CD Beats Vol. 3' COLLATE NOCASE),
   'Track 33 -> TS 0:06', 'HIP HOP HIT', NULL, NULL, 'Humming The Bassline', 'main', 'newer_vgm', 86),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Hollywood Edge' COLLATE NOCASE AND p.name = 'The Premiere Edition 1' COLLATE NOCASE),
   'Crowd-Applause & Cheer, Medium', 'MediumExteriorCrow PE140401', NULL, NULL, 'Sweet Soul Brother', 'main', 'newer_vgm', 87),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Hollywood Edge' COLLATE NOCASE AND p.name = 'The Premiere Edition 1' COLLATE NOCASE),
   'Crowd-Applause & Cheer, Medium', 'MediumExteriorCrow PE140501', NULL, NULL, 'Sweet Soul Brother', 'main', 'newer_vgm', 88),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'TRINITY proX' COLLATE NOCASE),
   'Programs -> Bank A', 'A106 Gospel Organ', NULL, NULL, 'Sweet Soul Brother', 'main', 'newer_vgm', 89),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'TRINITY proX' COLLATE NOCASE),
   'Programs -> Bank B', 'B049 Super Wurly', 'Organ riff, Overdrive effect on center', NULL, 'That''s Enough', 'main', 'newer_vgm', 90),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Masterbits' COLLATE NOCASE AND p.name = 'RAPsody' COLLATE NOCASE),
   'Track 09 - Short Swiny -> TS 0:28', 'Like demolition ...', '"Bwop bwop!" 100', NULL, 'Humming The Bassline', 'main', 'newer_vgm', 91),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Masterbits' COLLATE NOCASE AND p.name = 'RAPsody' COLLATE NOCASE),
   'Track 21 - Witness -> TS 0:49', 'And if you wanna ...', '"Get up to get down" 120', NULL, 'Humming The Bassline', 'main', 'newer_vgm', 92),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Masterbits' COLLATE NOCASE AND p.name = 'RAPsody' COLLATE NOCASE),
   'Track 26 - Naughty Nz -> TS 1:53', 'Black and blue, they wanna', '"Yo, you''d better watch that"', NULL, 'That''s Enough', 'main', 'newer_vgm', 93),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Masterbits' COLLATE NOCASE AND p.name = 'RAPsody' COLLATE NOCASE),
   'Track 27 - Heey Hoo AD -> TS 0:38', 'Come on, let go ...', NULL, NULL, 'Humming The Bassline', 'main', 'newer_vgm', 94),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Masterbits' COLLATE NOCASE AND p.name = 'RAPsody' COLLATE NOCASE),
   'Track 28 - Musical Names -> TS 0:23', 'Slap Bass', NULL, NULL, 'Sneakman', 'main', 'newer_vgm', 95),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Masterbits' COLLATE NOCASE AND p.name = 'RAPsody' COLLATE NOCASE),
   'Track 32 - Male AdLib 1 -> TS 0:26', 'One 4 the trouble ...', NULL, NULL, 'Humming The Bassline', 'main', 'newer_vgm', 96),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Masterbits' COLLATE NOCASE AND p.name = 'RAPsody' COLLATE NOCASE),
   'Track 36 - Shouts ! -> TS 0:02', 'Brazilian female', '"How cledger"', NULL, 'Yellow Bream', 'main', 'newer_vgm', 97),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Masterbits' COLLATE NOCASE AND p.name = 'RAPsody' COLLATE NOCASE),
   'Track 37 - Countdown & Space -> TS 0:49', 'Outer space choir', NULL, NULL, 'Grace & Glory', 'main', 'newer_vgm', 98),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Masterbits' COLLATE NOCASE AND p.name = 'RAPsody' COLLATE NOCASE),
   'Track 39 - Nostalgic Vocals -> TS 0:00', 'ATA-Chorus', NULL, NULL, 'Sweet Soul Brother', 'main', 'newer_vgm', 99),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Masterbits' COLLATE NOCASE AND p.name = 'RAPsody' COLLATE NOCASE),
   'Track 39 - Nostalgic Vocals -> TS 0:44', 'HB-Männchen Plot Point', '"Halt, mein freund..."', NULL, 'Yellow Bream', 'main', 'newer_vgm', 100),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Masterbits' COLLATE NOCASE AND p.name = 'RAPsody' COLLATE NOCASE),
   'Track 40 - Sound Effects -> TS 0:00', 'Reverser''s EFX', NULL, NULL, 'Yellow Bream', 'main', 'newer_vgm', 101),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Masterbits' COLLATE NOCASE AND p.name = 'RAPsody' COLLATE NOCASE),
   'Track 40 - Sound Effects -> TS 0:22', 'Clocktower machine', NULL, NULL, 'Yellow Bream', 'main', 'newer_vgm', 102),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Masterbits' COLLATE NOCASE AND p.name = 'RAPsody' COLLATE NOCASE),
   'Track 40 - Sound Effects -> TS 0:37', 'SPACE GUNS', NULL, NULL, 'Yellow Bream', 'main', 'newer_vgm', 103),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Polestar Magnetics' COLLATE NOCASE AND p.name = 'The X-Static Goldmine' COLLATE NOCASE),
   'CD 1 -> Track 06 - HIPHOP -> TS 0:22', 'Eurobix 102', '"Uh! Ah!"', NULL, 'Sneakman', 'main', 'newer_vgm', 104),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Polestar Magnetics' COLLATE NOCASE AND p.name = 'The X-Static Goldmine' COLLATE NOCASE),
   'CD 2 -> Track 02 - YO! BOIIE! -> TS 0:12', 'Rock Dat Shit...', '"...Homie!"', NULL, 'Rock It On', 'main', 'newer_vgm', 105),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Polestar Magnetics' COLLATE NOCASE AND p.name = 'The X-Static Goldmine' COLLATE NOCASE),
   'CD 2 -> Track 03 - SCREAMERS -> TS 0:18', 'Reversed''', NULL, NULL, 'Grace & Glory', 'main', 'newer_vgm', 106),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Polestar Magnetics' COLLATE NOCASE AND p.name = 'The X-Static Goldmine' COLLATE NOCASE),
   'CD 2 -> Track 04 - COME ON! -> TS 0:10', 'I Said It Before...', '"...And I''ll say it again"', NULL, 'Sneakman', 'main', 'newer_vgm', 107),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Polestar Magnetics' COLLATE NOCASE AND p.name = 'The X-Static Goldmine' COLLATE NOCASE),
   'CD 2 -> Track 55 - MAN MACHINE -> TS 0:24', 'Choke'' (FX)', NULL, NULL, 'Grace & Glory', 'main', 'newer_vgm', 108),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Polestar Magnetics' COLLATE NOCASE AND p.name = 'The X-Static Goldmine' COLLATE NOCASE),
   'CD 2 -> Track 57 - LUCY IN D SKY… -> TS 0:07', 'Tune In. Turn On...', '"...And drop out"', NULL, 'Rock It On', 'main', 'newer_vgm', 109),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Polestar Magnetics' COLLATE NOCASE AND p.name = 'The X-Static Goldmine' COLLATE NOCASE),
   'CD 2 -> Track 69 - FEAR -> TS 0:18', 'Screams', NULL, NULL, 'Grace & Glory', 'main', 'newer_vgm', 110),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Profile Records' COLLATE NOCASE AND p.name = 'Sample City' COLLATE NOCASE),
   'Track 19', 'Mm, Mm, Mm, Mm, Mm', NULL, NULL, 'Humming The Bassline', 'main', 'newer_vgm', 111),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JV-1080' COLLATE NOCASE),
   'PR-B', '013 Finger Bass', 'Electric Bass, distortion added', NULL, 'Sweet Soul Brother', 'main', 'newer_vgm', 112),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JV-1080' COLLATE NOCASE),
   'PR-D (GM)', '019 Organ 3', NULL, NULL, 'Funky Radio', 'main', 'newer_vgm', 113),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Burning Grooves' COLLATE NOCASE),
   'CD 1 -> Partition E -> 105 HOP LOFI', 'HIP-HOP LOFI', NULL, NULL, 'Funky Radio', 'main', 'newer_vgm', 114),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Heart of Asia' COLLATE NOCASE),
   'CD 2 -> Partition F -> CHINESE PERC', 'CHINESE MENU', NULL, NULL, 'Yellow Bream', 'main', 'newer_vgm', 115),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Heart of Asia' COLLATE NOCASE),
   'CD 3 -> Partition G -> CHINESE GUY', 'CHINESE GUY', NULL, NULL, 'Yellow Bream', 'main', 'newer_vgm', 116),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sounds Good & Steinberg' COLLATE NOCASE AND p.name = 'Hip Hop Beats & Treats' COLLATE NOCASE),
   'CD 1 -> 80_SCRATCH', '080AH', NULL, NULL, 'Moody''s Shuffle', 'main', 'newer_vgm', 117),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sounds Good & Steinberg' COLLATE NOCASE AND p.name = 'Hip Hop Beats & Treats' COLLATE NOCASE),
   'CD 4 (HFS) -> Sounds&Cycles -> Chemical Big Beats', '110MDL5C', 'Appears in Sounds & Cycles demo samples', NULL, 'Sneakman', 'main', 'newer_vgm', 118),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sounds Good & Steinberg' COLLATE NOCASE AND p.name = 'Hip Hop Beats & Treats' COLLATE NOCASE),
   'CD 4 (HFS) -> Sounds&Cycles -> Cold Fusion Technologic', '120DU01', 'Appears in Sounds & Cycles demo samples', NULL, 'Grace & Glory', 'main', 'newer_vgm', 119),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sounds Good & Steinberg' COLLATE NOCASE AND p.name = 'Hip Hop Beats & Treats' COLLATE NOCASE),
   'CD 4 (HFS) -> Sounds&Cycles -> The Electro Age', '130MDL1A', 'Appears in Sounds & Cycles demo samples', NULL, 'Rock It On', 'main', 'newer_vgm', 120),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Wizoo' COLLATE NOCASE AND p.name = 'Cologne Cyclez 1 + 2' COLLATE NOCASE),
   'Demo Track', 'Timestamp 0:01', NULL, NULL, 'Jet Set Groove #2', 'main', 'newer_vgm', 121),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Beats N'' The Hood' COLLATE NOCASE),
   'Track 55 -> Sample 1', 'Drum Fills 1-10', NULL, NULL, 'Everybody Jump Around', 'main', 'newer_vgm', 122),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Beats N'' The Hood' COLLATE NOCASE),
   'Track 57 -> Sample 3', 'Drum Fills 21-30', NULL, NULL, 'Everybody Jump Around', 'main', 'newer_vgm', 123),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Beats N'' The Hood' COLLATE NOCASE),
   'Track 57 -> Sample 8', 'Drum Fills 21-30', NULL, NULL, 'Everybody Jump Around', 'main', 'newer_vgm', 124),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Beats N'' The Hood' COLLATE NOCASE),
   'Track 57 -> Sample 9', 'Drum Fills 21-30', NULL, NULL, 'Everybody Jump Around', 'main', 'newer_vgm', 125),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Beats N'' The Hood' COLLATE NOCASE),
   'Track 59 -> Sample 2', 'Static Intro', NULL, NULL, 'Everybody Jump Around', 'main', 'newer_vgm', 126),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Beats N'' The Hood' COLLATE NOCASE),
   'Track 59 -> Sample 4', 'Ref', NULL, NULL, 'Everybody Jump Around', 'main', 'newer_vgm', 127),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Beats N'' The Hood' COLLATE NOCASE),
   'Track 63 -> Sample 2', 'Metal Scream', '"Owwaaaa---ow-ow-ow"', NULL, 'Everybody Jump Around', 'main', 'newer_vgm', 128),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Beats N'' The Hood' COLLATE NOCASE),
   'Track 66 -> Sample 6', 'Yow', NULL, NULL, 'Everybody Jump Around', 'main', 'newer_vgm', 129),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Dance Vocals' COLLATE NOCASE),
   'Track 36 - Rap - Conway Ellis -> Sample 19', 'The funky rhythm... 2', '"The funky rhythm comin'' atcha"', NULL, 'That''s Enough', 'main', 'newer_vgm', 130),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 2' COLLATE NOCASE),
   'Track 17 - Percussion -> Sample 5', 'Alesis HR 16B Drum M/C HH open 3', NULL, NULL, 'Let Mom Sleep', 'main', 'newer_vgm', 131),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 2' COLLATE NOCASE),
   'Track 26 - Vocal Hooks (Male) -> TS 0:03', '"Hagh!" + echo', NULL, NULL, 'That''s Enough', 'main', 'newer_vgm', 132),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 2' COLLATE NOCASE),
   'Track 43 - Speech (Female) -> TS 0:11', '"The music just turns me on!"', NULL, NULL, 'That''s Enough', 'main', 'newer_vgm', 133),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 2' COLLATE NOCASE),
   'Track 45 - Speech (Male) -> TS 0:07', 'Scratch + "Let''s get scratchin''!"', NULL, NULL, 'Moody''s Shuffle', 'main', 'newer_vgm', 134),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 2' COLLATE NOCASE),
   'Track 51 - Ambient FX -> TS 0:52', 'Japanese ambient flute', NULL, NULL, 'Yellow Bream', 'main', 'newer_vgm', 135),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 2' COLLATE NOCASE),
   'Track 52 - Speech (Chorus) -> TS 0:09', '"Ayyyy!" (African chant)', NULL, NULL, 'Let Mom Sleep', 'main', 'newer_vgm', 136),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 2' COLLATE NOCASE),
   'Track 53 - Vocal (Female) -> TS 0:05', '"That''s right... get down!"', NULL, NULL, 'Let Mom Sleep', 'main', 'newer_vgm', 137),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 2' COLLATE NOCASE),
   'Track 54 - Speech (Male) -> TS 0:29', '"Come on doc gimme a break!"', NULL, NULL, 'Sneakman', 'main', 'newer_vgm', 138),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 2' COLLATE NOCASE),
   'Track 55 - Speech (Female) -> TS 0:07', '"Stop playing with that radio..."', NULL, NULL, 'Let Mom Sleep', 'main', 'newer_vgm', 139),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 2' COLLATE NOCASE),
   'Track 58 - Misc. House FX -> TS 0:24', 'Organ slide FX', NULL, NULL, 'Let Mom Sleep', 'main', 'newer_vgm', 140),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 2' COLLATE NOCASE),
   'Track 59 - Speech (Male) -> TS 0:06', 'Bippity-bom-bom-bom!"', NULL, NULL, 'Moody''s Shuffle', 'main', 'newer_vgm', 141),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 2' COLLATE NOCASE),
   'Track 66 - Misc House FX -> TS 0:10', 'Siren start-up FX', NULL, NULL, 'Let Mom Sleep', 'main', 'newer_vgm', 142),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 2' COLLATE NOCASE),
   'Track 67 - Speech (Male) -> TS 0:03', '"It''s a tough beat but...!"', NULL, NULL, 'Sneakman', 'main', 'newer_vgm', 143),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 2' COLLATE NOCASE),
   'Track 68 - Speech (Male) -> TS 0:23', '"Git funky, git down!"', NULL, NULL, 'Let Mom Sleep', 'main', 'newer_vgm', 144),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 2' COLLATE NOCASE),
   'Track 72 - Guitar FX -> TS 0:16', 'Guitar fall FX', NULL, NULL, 'Jet Set Groove #1', 'main', 'newer_vgm', 145),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 2' COLLATE NOCASE),
   'Track 72 - Guitar FX -> TS 0:34', 'Guitar riff part b', NULL, NULL, 'Humming The Bassline', 'main', 'newer_vgm', 146),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 2' COLLATE NOCASE),
   'Track 72 - Guitar FX -> TS 0:36', 'Guitar riff part c', NULL, NULL, 'Humming The Bassline', 'main', 'newer_vgm', 147),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 2' COLLATE NOCASE),
   'Track 73 - Guitar Breaks -> TS 0:16', 'Break 3 (bar B)', NULL, NULL, 'Sneakman', 'main', 'newer_vgm', 148),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 2' COLLATE NOCASE),
   'Track 73 - Guitar Breaks -> TS 0:22', 'Break 5 (1 bar)', NULL, NULL, 'Jet Set Groove #2', 'main', 'newer_vgm', 149),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 2' COLLATE NOCASE),
   'Track 73 - Guitar Breaks -> TS 0:25', 'Break 6 (2 bars)', NULL, NULL, 'That''s Enough', 'main', 'newer_vgm', 150),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 2' COLLATE NOCASE),
   'Track 73 - Guitar Stab -> TS 0:30', 'Stab 1', NULL, NULL, 'Let Mom Sleep', 'main', 'newer_vgm', 151),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 2' COLLATE NOCASE),
   'Track 89 - Speech (Male) -> TS 0:14', '"Let the bass go!"', NULL, NULL, 'Sneakman', 'main', 'newer_vgm', 152),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 2' COLLATE NOCASE),
   'Track 92 - Human Beatbox -> TS 0:00', 'Human beatbox Snare A', NULL, NULL, 'That''s Enough', 'main', 'newer_vgm', 153),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 2' COLLATE NOCASE),
   'Track 92 - Human Beatbox -> TS 0:14', 'Human beatbox Rhythm B', NULL, NULL, 'That''s Enough', 'main', 'newer_vgm', 154),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 2' COLLATE NOCASE),
   'Track 92 - Human Beatbox -> TS 0:35', 'Human beatbox Snare C', NULL, NULL, 'That''s Enough', 'main', 'newer_vgm', 155),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 2' COLLATE NOCASE),
   'Track 92 - Human Beatbox -> TS 0:39', 'Human beatbox Bass drum B', NULL, NULL, 'That''s Enough', 'main', 'newer_vgm', 156),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 2' COLLATE NOCASE),
   'Track 99 - Speech (Male) -> TS 0:00', '"This is most disturbing!"', NULL, NULL, 'Let Mom Sleep', 'main', 'newer_vgm', 157),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 2' COLLATE NOCASE),
   'Track 99 - Speech (Male) -> TS 0:03', '"I don''t know what''s going on here!"', NULL, NULL, 'Sneakman', 'main', 'newer_vgm', 158),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 2' COLLATE NOCASE),
   'Track 99 - Speech (Male) -> TS 0:06', '"Let''s look at the funk!"', NULL, NULL, 'Let Mom Sleep', 'main', 'newer_vgm', 159),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 3' COLLATE NOCASE),
   'Track 39 - Vocal ad libs -> TS 0:32', '"a-ha!" (female)', NULL, NULL, 'Everybody Jump Around', 'main', 'newer_vgm', 160),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 3' COLLATE NOCASE),
   'Track 49 - Misc. vocal hooks -> TS 0:13', '"heyy!" (female)', NULL, NULL, 'Everybody Jump Around', 'main', 'newer_vgm', 161),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 3' COLLATE NOCASE),
   'Track 84 - Misc. vocals + FX -> TS 0:18', '"bwaah!"', NULL, NULL, 'Everybody Jump Around', 'main', 'newer_vgm', 162),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 3' COLLATE NOCASE),
   'Track 85 - Misc. vocals + FX -> TS 0:03', '"y'' all ready..."', '"...to get funky?"', NULL, 'Everybody Jump Around', 'main', 'newer_vgm', 163),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 3' COLLATE NOCASE),
   'Track 86 - Misc. vocals + FX -> TS 0:00', '"say yeah!"', NULL, NULL, 'Everybody Jump Around', 'main', 'newer_vgm', 164),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 3' COLLATE NOCASE),
   'Track 86 - Misc. vocals + FX -> TS 0:02', 'cheers FX', NULL, NULL, 'Everybody Jump Around', 'main', 'newer_vgm', 165),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 3' COLLATE NOCASE),
   'Track 87 - Misc. vocals + FX -> TS 0:26', 'scratched fresh', NULL, NULL, 'Everybody Jump Around', 'main', 'newer_vgm', 166),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 3' COLLATE NOCASE),
   'Track 89 - Misc. vocals + FX -> TS 0:00', '"1-2-3-four!"', NULL, NULL, 'Everybody Jump Around', 'main', 'newer_vgm', 167),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Electric Dreamz' COLLATE NOCASE),
   'Track 06 - Mod''s 4 VC''s 3 -> TS 0:02', 'Mod''s 02', NULL, NULL, 'Mischievous Boy', 'main', 'newer_vgm', 168),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Electric Dreamz' COLLATE NOCASE),
   'Track 07 - Random Synthesis -> TS 0:18', 'Random 05', NULL, NULL, 'Mischievous Boy', 'main', 'newer_vgm', 169),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Electric Dreamz' COLLATE NOCASE),
   'Track 07 - Random Synthesis -> TS 0:36', 'Random 07', NULL, NULL, 'Mischievous Boy', 'main', 'newer_vgm', 170),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Electric Dreamz' COLLATE NOCASE),
   'Track 09 - Trans Machine -> Sample 8', 'Trans Steam', NULL, NULL, 'Mischievous Boy', 'main', 'newer_vgm', 171),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Ethnic' COLLATE NOCASE),
   'Track 80 - MISCELLANEOUS -> TS 0:04', 'Harmonica 2 Key of E', NULL, NULL, 'Jet Set Groove #1', 'main', 'newer_vgm', 172),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Ethnic' COLLATE NOCASE),
   'Track 80 - MISCELLANEOUS -> TS 0:10', 'Harmonica 3 Key of E', NULL, NULL, 'Jet Set Groove #1', 'main', 'newer_vgm', 173),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Global S.F.X.' COLLATE NOCASE),
   'Track 04 -> Sample 11', '999', '"Emergency. Which service?"', NULL, 'Mischievous Boy', 'main', 'newer_vgm', 174),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Rhythm Guitar & FX' COLLATE NOCASE),
   'Track 22 - Electric Guitar, 132 bpm -> TS 0:24', 'Scratch Wah 2 SC/W', NULL, NULL, 'Sneakman', 'main', 'newer_vgm', 175),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Rhythm Guitar & FX' COLLATE NOCASE),
   'Track 23 - Electric Guitar, 132 bpm -> TS 0:00', 'All over the World A 1 VOD', NULL, NULL, 'Rock It On', 'main', 'newer_vgm', 176),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Rhythm Guitar & FX' COLLATE NOCASE),
   'Track 23 - Electric Guitar, 132 bpm -> TS 0:03', 'All over the World D 1 VOD', NULL, NULL, 'Rock It On', 'main', 'newer_vgm', 177),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Rhythm Guitar & FX' COLLATE NOCASE),
   'Track 23 - Electric Guitar, 132 bpm -> TS 0:06', 'All over the World F 1 VOD', NULL, NULL, 'Rock It On', 'main', 'newer_vgm', 178),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'The Funky Element' COLLATE NOCASE),
   'Track 19 - horn hits + stabs -> TS 0:03', 'roots hit', NULL, NULL, 'Let Mom Sleep', 'main', 'newer_vgm', 179),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Killer Horns' COLLATE NOCASE),
   NULL, NULL, 'Additional Horns', NULL, 'Everybody Jump Around', 'stuff_to_find', 'newer_vgm', 180),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'TRINITY proX' COLLATE NOCASE),
   NULL, NULL, 'Wah Space Bass', NULL, 'Sneakman', 'stuff_to_find', 'newer_vgm', 181),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Burning Grooves' COLLATE NOCASE),
   NULL, NULL, 'Drum Elements', NULL, 'Funky Radio', 'stuff_to_find', 'newer_vgm', 182),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Rhythm Guitar & FX' COLLATE NOCASE),
   NULL, NULL, 'Rock ''n'' Roll guitar', NULL, 'Jet Set Groove #1', 'stuff_to_find', 'newer_vgm', 183),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   NULL, NULL, NULL, 'Tambourine Loop', '? (Sample Loop Library)', 'Let Mom Sleep', 'stuff_to_find', 'newer_vgm', 184),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   NULL, NULL, NULL, 'Slap Bass Loop', '? (Sample Loop Library)', 'That''s Enough', 'stuff_to_find', 'newer_vgm', 185),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   NULL, NULL, NULL, 'Synth Bass', '? (Synth)', 'That''s Enough', 'stuff_to_find', 'newer_vgm', 186),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   NULL, NULL, NULL, 'Crash Cymbal', '? (Sample Loop Library)', 'That''s Enough', 'stuff_to_find', 'newer_vgm', 187),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   NULL, NULL, NULL, 'Percussion Loop', '? (Sample Loop Library)', 'That''s Enough', 'stuff_to_find', 'newer_vgm', 188),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   NULL, NULL, NULL, 'Sine Lead', '? (Synth)', 'That''s Enough', 'stuff_to_find', 'newer_vgm', 189),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   NULL, NULL, NULL, 'Guitar Phrases', '? (Sample Loop Library)', 'Everybody Jump Around', 'stuff_to_find', 'newer_vgm', 190),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   NULL, NULL, NULL, 'Percussion Loops', '? (Sample Loop Library)', 'Sneakman', 'stuff_to_find', 'newer_vgm', 191),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   NULL, NULL, NULL, 'Additional Drum Fills', '? (Sample Loop Library)', 'Sneakman', 'stuff_to_find', 'newer_vgm', 192),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   NULL, NULL, NULL, 'Brass (Raspy)', '? (Sample Loop Library)', 'Sneakman', 'stuff_to_find', 'newer_vgm', 193),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   NULL, NULL, NULL, 'Guitar (Acoustic) Rhythm', '? (Sample Loop Library)', 'Sweet Soul Brother', 'stuff_to_find', 'newer_vgm', 194),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   NULL, NULL, NULL, 'Stomp/Clap Loop', '? (Sample Loop Library)', 'Sweet Soul Brother', 'stuff_to_find', 'newer_vgm', 195),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   NULL, NULL, NULL, 'Drums (Electronic, C)', '? (Sample Loop Library)', 'Rock It On', 'stuff_to_find', 'newer_vgm', 196),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   NULL, NULL, NULL, 'Drum Loop (Acoustic, L)', '? (Sample Loop Library)', 'Rock It On', 'stuff_to_find', 'newer_vgm', 197),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   NULL, NULL, NULL, 'Electric Bass', '? (Synth)', 'Rock It On', 'stuff_to_find', 'newer_vgm', 198),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   NULL, NULL, NULL, 'Rock Piano', '? (Synth)', 'Rock It On', 'stuff_to_find', 'newer_vgm', 199),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   NULL, NULL, NULL, 'Lead', '? (Synth)', 'Rock It On', 'stuff_to_find', 'newer_vgm', 200),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   NULL, NULL, NULL, 'Additional Vocals', '? (Sample Loop Library)', 'Funky Radio', 'stuff_to_find', 'newer_vgm', 201),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   NULL, NULL, NULL, 'Congas', '? (Sample Loop Library)', 'Moody''s Shuffle', 'stuff_to_find', 'newer_vgm', 202),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   NULL, NULL, NULL, 'Sub Bass', '? (Sample Loop or Instrument Library)', 'Moody''s Shuffle', 'stuff_to_find', 'newer_vgm', 203),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   NULL, NULL, NULL, 'Horn Hit/Scratch', '? (Sample Loop Library)', 'Moody''s Shuffle', 'stuff_to_find', 'newer_vgm', 204),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   NULL, NULL, NULL, 'Vinyl Crackle (In-game version)', '? (Sample Loop Library)', 'Grace & Glory', 'stuff_to_find', 'newer_vgm', 205),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   NULL, NULL, NULL, 'Church Organ', '? (Synth)', 'Grace & Glory', 'stuff_to_find', 'newer_vgm', 206),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   NULL, NULL, NULL, 'Bass Synth', '? (Synth)', 'Grace & Glory', 'stuff_to_find', 'newer_vgm', 207),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   NULL, NULL, NULL, 'Plane SFX', '? (Sample Loop Library)', 'Jet Set Station', 'stuff_to_find', 'newer_vgm', 208),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   NULL, NULL, NULL, '"Woo, yeah!" (Bitcrushed)', '? (Sample Loop Library)', 'Jet Set Groove #1', 'stuff_to_find', 'newer_vgm', 209),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   NULL, NULL, NULL, 'Drum Loops', '? (Sample Loop Library)', 'Jet Set Groove #2', 'stuff_to_find', 'newer_vgm', 210),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio / Jet Grind Radio'),
   NULL, NULL, NULL, 'Screech FX', '? (Sample Loop Library)', 'Jet Set Groove #2', 'stuff_to_find', 'newer_vgm', 211),

  -- G2: Jet Set Radio E3 Prototype — 4 main + 4 stuff = 8 rows
  ((SELECT id FROM games WHERE title = 'Jet Set Radio E3 Prototype'),
   NULL, NULL, 'Timestamp 0:00', '"Yeaaaaahh!"', 'Sample: Beastie Boys - (You Gotta) Fight For Your Right (To Party!)', 'Fuzita Blender - Pizza Delivery Man on Harley-Davidson', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio E3 Prototype'),
   NULL, NULL, 'Timestamp 0:33', NULL, 'Sample: fIREHOSE - Windmilling', 'Fuzita Blender - Pizza Delivery Man on Harley-Davidson', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio E3 Prototype'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sounds Good & Steinberg' COLLATE NOCASE AND p.name = 'Hip Hop Beats & Treats' COLLATE NOCASE),
   'CD 1 -> 80_SCRATCH', '080GOVER', NULL, NULL, 'SFX (E3 Build Scratch)', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio E3 Prototype'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Beats N'' The Hood' COLLATE NOCASE),
   'Track 57 -> Sample 9', 'Drum Fills 21-30', NULL, NULL, 'SFX (E3 Build Scratch)', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio E3 Prototype'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'MS-20' COLLATE NOCASE),
   NULL, NULL, 'Seen on cover of "Holiday Plug-In!"', NULL, '(Fuzita Blender)', 'stuff_to_find', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio E3 Prototype'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'System-100M' COLLATE NOCASE),
   NULL, NULL, 'Seen on cover of "Holiday Plug-In!"', NULL, '(Fuzita Blender)', 'stuff_to_find', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio E3 Prototype'),
   NULL, NULL, NULL, 'Electric Bass', '? (Synth)', 'Fuzita Blender - Fantastic Boobie Band, Fuzita Blender - Pizza Delivery Man on Harley-Davidson', 'stuff_to_find', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'Jet Set Radio E3 Prototype'),
   NULL, NULL, NULL, 'Background Vocals (Scratches)', '? (Sample Loop Library)', 'Everybody Jump Around (E3 Build)', 'stuff_to_find', 'newer_vgm', 8);
