-- NEWER VGM SEGA/Atlus — Section 12 (Phantasy Star Online)
--
-- Source: reference/NEWER VGM Sound Sources - SEGAAtlus.csv lines 2177-2275.
-- 2 game records, ~93 usage rows.
--
-- PSO 2 (2012) is dominated by Spectrasonics Omnisphere + Omnisphere 2 +
-- Stylus RMX usage (~28 rows across those three products). Japanese track
-- names preserved verbatim (白ノ領域 - 武踏, 黒ノ領域 - 闘諍, 29 PSO2 S.E.集),
-- as are accented international titles (la L'inno per il "IDOLA", MIERNO
-- ''IDOLA''). Demo column "Demo"/"Discord" values across both games skipped
-- as provenance annotations rather than URLs.
--
-- Verbatim preservations (Rule 2):
--   - "Vienna Symphonic Library / ?" (T2257-2260) — manufacturer known,
--     product unidentified; preserved as raw_source = 'Vienna Symphonic
--     Library - ?' on 4 stuff_to_find rows.
--   - "? (UVI, MOTU or VSL product)" (T2275) — three-way contributor
--     uncertainty preserved as raw_source.
--   - "Spectrasonics / Distorted Reality" (T2192-2193) preserved distinct
--     from existing "Distorted Reality 2".
--   - "Spectrasonics / Omnisphere 2" preserved distinct from "Omnisphere".

INSERT OR IGNORE INTO manufacturers (name) VALUES
  ('Equipped Music'),
  ('Vienna Symphonic Library'),
  ('Xfer Records'),
  ('Impact Soundworks');

INSERT OR IGNORE INTO products (manufacturer_id, name, type) VALUES
  ((SELECT id FROM manufacturers WHERE name = 'Spectrasonics'      COLLATE NOCASE), 'Bass Legends',                                'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Spectrasonics'      COLLATE NOCASE), 'Distorted Reality',                           'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Spectrasonics'      COLLATE NOCASE), 'Stylus',                                      'Instrument'),
  ((SELECT id FROM manufacturers WHERE name = 'Spectrasonics'      COLLATE NOCASE), 'Omnisphere 2',                                'Instrument'),
  ((SELECT id FROM manufacturers WHERE name = 'Yamaha'             COLLATE NOCASE), 'FS1R',                                        'Synth'),
  ((SELECT id FROM manufacturers WHERE name = 'Yamaha'             COLLATE NOCASE), 'A4000',                                       'Synth'),
  ((SELECT id FROM manufacturers WHERE name = 'Best Service'       COLLATE NOCASE), 'Ethno World Instruments',                     'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'EastWest'           COLLATE NOCASE), 'Voices of Passion',                           'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Equipped Music'     COLLATE NOCASE), 'SLO'' MOTION: Tokyo Soundscapes',             'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Xfer Records'       COLLATE NOCASE), 'Serum',                                       'Synth'),
  ((SELECT id FROM manufacturers WHERE name = 'Impact Soundworks'  COLLATE NOCASE), 'Shreddage',                                   'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Impact Soundworks'  COLLATE NOCASE), 'Slavic Women''s Choir',                       'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Sound Ideas'        COLLATE NOCASE), 'Sci-Fi Series 8000',                          'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Sound Ideas'        COLLATE NOCASE), 'Sci-Fi Warp 2 8000',                          'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Ueberschall'        COLLATE NOCASE), 'Trap',                                        'Sample Library');

INSERT INTO games (title, platform, released, composers, composers_normalized, notes) VALUES
  ('Phantasy Star Online',   'Dreamcast, GameCube, Xbox',                                          '2000-12-21', NULL, NULL, 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 12 Phantasy Star Online). Sega''s seminal online RPG.'),
  ('Phantasy Star Online 2', 'PC, PlayStation Vita, PlayStation 4, Nintendo Switch, Xbox One, iOS, Android', '2012-07-04', NULL, NULL, 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 12 Phantasy Star Online). Heavy Spectrasonics use (Omnisphere + Omnisphere 2 + Stylus RMX dominate ~28 rows). Japanese track names preserved verbatim alongside accented international titles.');

INSERT INTO usages
  (game_id, product_id, path_bank, preset, notes, raw_source, examples, category, source_family, position)
VALUES
  -- G1: Phantasy Star Online — 18 main + 4 stuff = 22 rows
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Clavia' COLLATE NOCASE AND p.name = 'Nord Lead 2' COLLATE NOCASE),
   'Program', '44 Gimme 5', NULL, NULL, 'Image of hero', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = '01/W' COLLATE NOCASE),
   'PROG -> Bank A', 'A06 XFade Bass', NULL, NULL, 'Image of hero', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'TR-Rack' COLLATE NOCASE),
   'Combinations -> Bank A', 'A050 {Lonely} [Alien]', 'note B3', NULL, 'The kink in the wind and the way PART 1', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'TR-Rack' COLLATE NOCASE),
   'Programs -> Bank A', 'A001 Acoustic Piano', NULL, NULL, 'Mother Earth of Dishonesty Part 1', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'TR-Rack' COLLATE NOCASE),
   'Programs -> Bank A', 'A048 Moon Walking', NULL, NULL, 'Jungle -a lush load-, Jungle ~A forest cage~', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'TR-Rack' COLLATE NOCASE),
   'Programs -> Bank C', 'C001 Clear Mallet', 'MULTI mode', NULL, 'Song For Eternal Story', 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'TR-Rack' COLLATE NOCASE),
   'Programs -> Bank C', 'C099 DSP Noise', NULL, NULL, 'SFX (Loading Screen)', 'main', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Polestar Magnetics' COLLATE NOCASE AND p.name = 'The X-Static Goldmine' COLLATE NOCASE),
   'CD 2 -> Track 25 - KRAFTWERK 1 -> TS 0:09', 'Zap 3', NULL, NULL, 'Image of hero', 'main', 'newer_vgm', 8),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JV-2080' COLLATE NOCASE),
   'PR-A', '125 Power Trip', NULL, NULL, 'Abysmal ball -banquet-', 'main', 'newer_vgm', 9),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JV-2080' COLLATE NOCASE),
   'PR-B', '067 TeknoSoloVox', NULL, NULL, 'Abysmal ball -banquet-', 'main', 'newer_vgm', 10),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JV-2080' COLLATE NOCASE),
   'PR-C', '008 Massed Horns', NULL, NULL, 'Mother Earth of Dishonesty Part 1', 'main', 'newer_vgm', 11),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Bass Legends' COLLATE NOCASE),
   'Parition A -> 6-STR FUNK', 'JP FUNK-V3 C', NULL, NULL, NULL, 'main', 'newer_vgm', 12),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Distorted Reality' COLLATE NOCASE),
   'Partition A -> PIXIES', 'ELVES', NULL, NULL, 'Song For Eternal Story, Mother Earth of Dishonesty Part 1', 'main', 'newer_vgm', 13),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Distorted Reality' COLLATE NOCASE),
   'Partition A -> WEIGHTLESS', 'PYCHEDELICS', NULL, NULL, 'Transport/warp SFX', 'main', 'newer_vgm', 14),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus' COLLATE NOCASE),
   '1. Breakbeat Loops -> 64-69 BPM', '67-Crenshaw a', NULL, NULL, 'Weird night', 'main', 'newer_vgm', 15),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Yamaha' COLLATE NOCASE AND p.name = 'FS1R' COLLATE NOCASE),
   'PR-A', 'A009 Platipus', NULL, NULL, 'Abysmal ball -banquet-', 'main', 'newer_vgm', 16),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Yamaha' COLLATE NOCASE AND p.name = 'FS1R' COLLATE NOCASE),
   'PR-A', 'A062 DippeDut', NULL, NULL, 'Healing', 'main', 'newer_vgm', 17),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Ethnic' COLLATE NOCASE),
   'Track 28 - AFRICAN -> TS 0:42', 'Rhythm 31: Kenyan wakamba drums 4 bars', NULL, NULL, 'Revive the secred of rough wave', 'main', 'newer_vgm', 18),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online'),
   NULL, NULL, NULL, NULL, 'E-MU Systems - ?', 'Chaotic bar', 'stuff_to_find', 'newer_vgm', 19),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'TR-Rack' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, 'Chaotic bar', 'stuff_to_find', 'newer_vgm', 20),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JV-2080' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, NULL, 'stuff_to_find', 'newer_vgm', 21),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Yamaha' COLLATE NOCASE AND p.name = 'A4000' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, NULL, 'stuff_to_find', 'newer_vgm', 22),

  -- G2: Phantasy Star Online 2 — 61 main + 10 stuff = 71 rows
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Ethno World Instruments' COLLATE NOCASE),
   'BOWED INSTRUMENTS -> EGYPTIAN FIDDLE', 'Egyptian Fiddle Licks TM SYNC', NULL, NULL, 'ESTUGA', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Ethno World Instruments' COLLATE NOCASE),
   'WOODWIND AND BRASS -> IRISH WHISTLES', 'Overton Irish Whistle Key High', NULL, NULL, 'MIERNO ''''IDOLA'''' - TORDIERA', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   NULL, '4TB Stac RR', NULL, NULL, 'Unfathomable Darkness', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Voices of Passion' COLLATE NOCASE),
   'America', 'America Master', NULL, NULL, 'Anga Fhandarge', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Voices of Passion' COLLATE NOCASE),
   'Bulgaria', 'Bulgaria Master', NULL, NULL, 'Lizard Sanctuary Probe - Amduskia - Scenery', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Voices of Passion' COLLATE NOCASE),
   'Wales', 'Wales Ah DXF', NULL, NULL, 'Acheron', 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Equipped Music' COLLATE NOCASE AND p.name = 'SLO'' MOTION: Tokyo Soundscapes' COLLATE NOCASE),
   'EQ-Slo motion - Loops Wav > 03 Tokyo Soundscape Loops 070', 'EQ04 Scp Bluecat Pad 070 G#m', 'TS: 0:00', NULL, 'Team Meeting', 'main', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Equipped Music' COLLATE NOCASE AND p.name = 'SLO'' MOTION: Tokyo Soundscapes' COLLATE NOCASE),
   'EQ-Slo motion - Loops Wav > 03 Tokyo Soundscape Loops 070', 'EQ05 Scp Closing Pad 070 Bbm', 'TS: 0:00', NULL, 'Team Meeting', 'main', 'newer_vgm', 8),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Equipped Music' COLLATE NOCASE AND p.name = 'SLO'' MOTION: Tokyo Soundscapes' COLLATE NOCASE),
   'EQ-Slo motion - Samples > 05 Mixed Fx Sounds', 'EQ-eFx 007 Physical', 'TS: 0:21', NULL, 'Greenscape Probe - Naberius - Scenery', 'main', 'newer_vgm', 9),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Heavyocity' COLLATE NOCASE AND p.name = 'Damage' COLLATE NOCASE),
   '01 Rhythmic Suites -> Loop Menus', 'LPS Epic Organic Full', NULL, NULL, 'Superluminal - danger - Esca Falz Mother -', 'main', 'newer_vgm', 10),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'TR-Rack' COLLATE NOCASE),
   'Programs -> Bank C', 'C042 House/Techno/Jun', NULL, NULL, 'Greenscape Probe - Naberius - Battle', 'main', 'newer_vgm', 11),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'TR-Rack' COLLATE NOCASE),
   'Programs -> Bank C', 'C099 DSP Noise', 'SFX loading screen', NULL, NULL, 'main', 'newer_vgm', 12),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Native Instruments' COLLATE NOCASE AND p.name = 'Kontakt Factory Library' COLLATE NOCASE),
   'World -> 1 - Flutes', 'Shakuhachi', NULL, NULL, '白ノ領域 - 武踏', 'main', 'newer_vgm', 13),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JV-2080' COLLATE NOCASE),
   'PR-B', '073 Tekno Hit 1', NULL, NULL, 'Fleet Fencer - Breu Ringarda -', 'main', 'newer_vgm', 14),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JV-2080' COLLATE NOCASE),
   'PR-E', '066 Mental Chord', 'Reverb MFX disabled and boost to high-end frequencies', NULL, '29 PSO2 S.E.集', 'main', 'newer_vgm', 15),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Atmosphere' COLLATE NOCASE),
   'Bells and Vibes', 'Attack Shimmer', NULL, NULL, 'White Summit Probe - Naberius - Scenery', 'main', 'newer_vgm', 16),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Atmosphere' COLLATE NOCASE),
   'Percussive Organic', 'Ambient Gamelan', NULL, NULL, 'Underworks Probe - Lilipur - Scenery', 'main', 'newer_vgm', 17),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Atmosphere' COLLATE NOCASE),
   'Transition Effects', 'Twilight Passing', NULL, NULL, 'Zero-G - The Earth', 'main', 'newer_vgm', 18),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Omnisphere' COLLATE NOCASE),
   'Synth Mono', 'Amped Electric SuperSaw', NULL, NULL, 'Neon Nights - The Earth - Battle', 'main', 'newer_vgm', 19),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Omnisphere' COLLATE NOCASE),
   'Synth Mono', 'Amped Square Expresso', NULL, NULL, 'Zero-G - The Earth', 'main', 'newer_vgm', 20),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Omnisphere' COLLATE NOCASE),
   'Synth Mono', 'Authentic PWM Lead', NULL, NULL, 'Lizard Sanctuary Probe - Amduskia - Battle', 'main', 'newer_vgm', 21),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Omnisphere' COLLATE NOCASE),
   'Synth Poly', 'Compressed Supersawz', NULL, NULL, 'Dive into Constellated Sea - Sector 3', 'main', 'newer_vgm', 22),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Omnisphere' COLLATE NOCASE),
   'Human Voices', 'Choir Full Vibrato Heavy', NULL, NULL, 'Unfathomable Darkness', 'main', 'newer_vgm', 23),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Omnisphere' COLLATE NOCASE),
   'Human Voices', 'Chordal Choir Big Minor', NULL, NULL, 'Unfathomable Darkness', 'main', 'newer_vgm', 24),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Omnisphere' COLLATE NOCASE),
   'Human Voices', 'Classical Soprano Eh-Oh', NULL, NULL, 'Primordial Darkness - 1st half', 'main', 'newer_vgm', 25),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Omnisphere' COLLATE NOCASE),
   'Human Voices', 'Classical Soprano Ohs', NULL, NULL, 'Unfathomable Darkness', 'main', 'newer_vgm', 26),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Omnisphere' COLLATE NOCASE),
   'Human Voices', 'Classical Tenor Ah - f', NULL, NULL, 'la L''inno per il "IDOLA" - Persona di Onnipotente -', 'main', 'newer_vgm', 27),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Omnisphere' COLLATE NOCASE),
   'ARP + BPM', 'Cross Beat Kicker', NULL, NULL, 'Superior Probe - Underworks - Scenery', 'main', 'newer_vgm', 28),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Omnisphere' COLLATE NOCASE),
   'ARP + BPM', 'Cross Beat Overdriver', NULL, NULL, 'Growl from the Blast Rage - Vol Dragon -', 'main', 'newer_vgm', 29),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Omnisphere' COLLATE NOCASE),
   'ARP + BPM', 'Digi Buzzer 1', NULL, NULL, 'Emergency', 'main', 'newer_vgm', 30),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Omnisphere' COLLATE NOCASE),
   'ARP + BPM', 'Eternal Piano SUS Freezer', NULL, NULL, 'Neon Nights - The Earth - Scenery', 'main', 'newer_vgm', 31),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Omnisphere' COLLATE NOCASE),
   'Synth Mono', 'Happy Gaga Lead', NULL, NULL, 'Colorful Spacial', 'main', 'newer_vgm', 32),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Omnisphere' COLLATE NOCASE),
   'Synth Mono', 'Simple Lead', NULL, NULL, 'Survive from D-arker''s Nest - Struggle', 'main', 'newer_vgm', 33),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Omnisphere 2' COLLATE NOCASE),
   'ARP + BPM', 'Accidental Magic', NULL, NULL, 'Superior Probe - Underworks - Battle', 'main', 'newer_vgm', 34),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Omnisphere 2' COLLATE NOCASE),
   'ARP + BPM', 'Anticpation of Energy 1', NULL, NULL, 'Infiltrate the Battleship', 'main', 'newer_vgm', 35),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Omnisphere 2' COLLATE NOCASE),
   'ARP + BPM', 'White Morpheus', NULL, NULL, 'Superior Probe - Underworks - Scenery', 'main', 'newer_vgm', 36),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Omnisphere 2' COLLATE NOCASE),
   'Electric Perc', 'Snare Me', NULL, NULL, 'Superior Probe - Underworks - Battle', 'main', 'newer_vgm', 37),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Omnisphere 2' COLLATE NOCASE),
   'Synth Bass', 'Pinched Grinder', NULL, NULL, 'Superior Probe - Underworks - Battle', 'main', 'newer_vgm', 38),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Omnisphere 2' COLLATE NOCASE),
   'Synth Mono', 'Epic Turnt Up Lead', NULL, NULL, 'Superior Probe - Underworks - Battle', 'main', 'newer_vgm', 39),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves', '54-Eclipse Combo', NULL, NULL, 'Cauldron Probe - Amduskia - Battle', 'main', 'newer_vgm', 40),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves', '70-Dinosaur Drum Mix', NULL, NULL, 'Growl from the Blast Rage - Vol Dragon -', 'main', 'newer_vgm', 41),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves', '74-Rhinoceros Fury', NULL, NULL, 'Growl from the Blast Rage - Vol Dragon -', 'main', 'newer_vgm', 42),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves', '84-Particles', NULL, NULL, 'Neon Nights - The Earth - Scenery', 'main', 'newer_vgm', 43),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves', '106-King Kong Big Metal', NULL, NULL, 'Cauldron Probe - Amduskia - Battle', 'main', 'newer_vgm', 44),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves', '126-Transonica', NULL, NULL, 'Casino Lobby', 'main', 'newer_vgm', 45),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves', '160-Find The Exit', NULL, NULL, 'Spiral Tracker - Val Rodos -', 'main', 'newer_vgm', 46),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves', '174-World Hunt Combo Big', NULL, NULL, 'Resonant Defensive', 'main', 'newer_vgm', 47),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves', '174-World Hunt Snares 1', NULL, NULL, '黒ノ領域 - 闘諍 -', 'main', 'newer_vgm', 48),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Metamorphosis S.A.G.E. Xpander' COLLATE NOCASE),
   '050-059', '055-Mohave c', NULL, NULL, 'Team Meeting', 'main', 'newer_vgm', 49),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Trilian' COLLATE NOCASE),
   'ARP + BPM', 'Black Spider', NULL, NULL, 'Neon Nights - The Earth - Scenery', 'main', 'newer_vgm', 50),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Trilian' COLLATE NOCASE),
   'Bass Instruments', 'Clean Fender', NULL, NULL, 'MITORIA BORQUE SONDAL - BATALLURA', 'main', 'newer_vgm', 51),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Trilian' COLLATE NOCASE),
   'Synth Bass', 'Clicky FM Swell', NULL, NULL, 'Training!', 'main', 'newer_vgm', 52),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Vengeance Sound' COLLATE NOCASE AND p.name = 'Essential Clubsounds Vol. 3' COLLATE NOCASE),
   NULL, 'VEC3 Fill 140 BPM 100', 'Included with studio one', NULL, 'Underworks Probe - Lilipur - Battle', 'main', 'newer_vgm', 53),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   NULL, NULL, 'Cello Ensemble', NULL, 'Vienna Symphonic Library - ?', 'Resonant Defensive', 'main', 'newer_vgm', 54),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   NULL, NULL, 'Double Bass Ensemble', NULL, 'Vienna Symphonic Library - ?', 'Resonant Defensive', 'main', 'newer_vgm', 55),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   NULL, NULL, 'French Horn Ensemble', NULL, 'Vienna Symphonic Library - ?', 'Resonant Defensive', 'main', 'newer_vgm', 56),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   NULL, NULL, 'Violin Ensemble', NULL, 'Vienna Symphonic Library - ?', 'Resonant Defensive', 'main', 'newer_vgm', 57),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Xfer Records' COLLATE NOCASE AND p.name = 'Serum' COLLATE NOCASE),
   'Bass', 'BA Three Oh Three!', NULL, NULL, 'Rush Cutz 1st Step', 'main', 'newer_vgm', 58),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Xfer Records' COLLATE NOCASE AND p.name = 'Serum' COLLATE NOCASE),
   'Leads', 'LD booty', NULL, NULL, 'Zero-G - The Earth', 'main', 'newer_vgm', 59),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Xfer Records' COLLATE NOCASE AND p.name = 'Serum' COLLATE NOCASE),
   'Pads', 'PD Defiant', NULL, NULL, 'Rush Finished', 'main', 'newer_vgm', 60),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Xfer Records' COLLATE NOCASE AND p.name = 'Serum' COLLATE NOCASE),
   'Seq', 'SQ Automator 1', NULL, NULL, 'Rush Cutz 1st Step', 'main', 'newer_vgm', 61),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Impact Soundworks' COLLATE NOCASE AND p.name = 'Shreddage' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, 'Growl from the Blast Rage - Vol Dragon -', 'stuff_to_find', 'newer_vgm', 62),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Impact Soundworks' COLLATE NOCASE AND p.name = 'Slavic Women''s Choir' COLLATE NOCASE),
   NULL, NULL, 'Will add program path soon', NULL, 'Zero-G - Interlude', 'stuff_to_find', 'newer_vgm', 63),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'TR-Rack' COLLATE NOCASE),
   NULL, NULL, 'Kobayashi snare', NULL, NULL, 'stuff_to_find', 'newer_vgm', 64),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sound Ideas' COLLATE NOCASE AND p.name = 'Sci-Fi Series 8000' COLLATE NOCASE),
   NULL, NULL, 'SFX using a teleporter', NULL, NULL, 'stuff_to_find', 'newer_vgm', 65),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sound Ideas' COLLATE NOCASE AND p.name = 'Sci-Fi Warp 2 8000' COLLATE NOCASE),
   NULL, NULL, 'SFX low hp', NULL, NULL, 'stuff_to_find', 'newer_vgm', 66),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sound Ideas' COLLATE NOCASE AND p.name = 'Sci-Fi Warp 2 8000' COLLATE NOCASE),
   NULL, NULL, 'SFX near incapacitation', NULL, NULL, 'stuff_to_find', 'newer_vgm', 67),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Omnisphere' COLLATE NOCASE),
   NULL, '022 Frozen Lake (?)', 'Synth pad', NULL, 'Gateship', 'stuff_to_find', 'newer_vgm', 68),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   '?', NULL, NULL, NULL, 'Zero-G - The Earth', 'stuff_to_find', 'newer_vgm', 69),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Ueberschall' COLLATE NOCASE AND p.name = 'Trap' COLLATE NOCASE),
   NULL, NULL, 'Sounds like this might be used', NULL, 'Zero-G - The Earth', 'stuff_to_find', 'newer_vgm', 70),
  ((SELECT id FROM games WHERE title = 'Phantasy Star Online 2'),
   NULL, NULL, NULL, 'Vibraphone', '? (UVI, MOTU or VSL product)', 'Spumoni - Franca''s Cafe -', 'stuff_to_find', 'newer_vgm', 71);
