-- NEWER VGM SEGA/Atlus — Section 13 (Yakuza)
--
-- Source: reference/NEWER VGM Sound Sources - SEGAAtlus.csv lines 2277-2394.
-- 12 game records, ~96 usage rows.
--
-- Spans the Yakuza franchise from 2005 (PS2 original) through 2024 (Like
-- a Dragon: Infinite Wealth), plus the two Kurohyou PSP spinoffs.
-- Spectrasonics Stylus RMX dominates throughout — appears in nearly every
-- entry. Heavy international/Japanese track name preservation.
--
-- Verbatim preservations (Rule 2):
--   - Japanese track names: 唖然呆然, ハジマリノシラベ, 平静と困惑のあいだ,
--     花「はしる」, 緊張, 不穏な空気, 迫, GET TO THE TOP! ～森 摩耶～.
--   - "Spectrasonics / Burning Grooves S.A.G.E. Xpander" preserved
--     distinct from existing "Spectrasonics / Burning Grooves".
--   - "Reveal Sound / Spire ?" (Yakuza 0 stuff_to_find T2379) — product
--     name has literal "?" suffix per CSV.
--   - "PowerFX / The Electro Jazz Retro Funk Thing" preserved distinct
--     from existing "The Funk Master".
--   - "Was EXS24 and this patch available in 2005?" Yakuza T2280 note
--     preserved — contributor flagged anachronism uncertainty.
--   - T2372 path_bank is a giant whitespace-only padding string in CSV;
--     stored as NULL since the contributor's intent was clearly empty.

INSERT OR IGNORE INTO manufacturers (name) VALUES
  ('PrimeSounds'),
  ('Reveal Sound');

INSERT OR IGNORE INTO products (manufacturer_id, name, type) VALUES
  ((SELECT id FROM manufacturers WHERE name = 'Sonic Foundry'      COLLATE NOCASE), 'Euro Techno - Ground Loops',                  'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'PrimeSounds'        COLLATE NOCASE), 'Methods of Mayhem II',                        'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Spectrasonics'      COLLATE NOCASE), 'Burning Grooves S.A.G.E. Xpander',            'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'PowerFX'            COLLATE NOCASE), 'The Electro Jazz Retro Funk Thing',           'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Ueberschall'        COLLATE NOCASE), 'Nu Metal',                                    'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'UltimateSoundBank'  COLLATE NOCASE), 'Soundscan Vol. 26 - Big Beat Vol. 2 Samples', 'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Zero-G'             COLLATE NOCASE), 'Interface Guitar',                            'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Zero-G'             COLLATE NOCASE), 'Rock & Pop Vocals',                           'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Zero-G'             COLLATE NOCASE), 'Twisted City',                                'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Zero-G'             COLLATE NOCASE), 'Upfront Lead Guitar',                         'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Heavyocity'         COLLATE NOCASE), 'Evolve R2',                                   'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Reveal Sound'       COLLATE NOCASE), 'Spire ?',                                     'Synth');

INSERT INTO games (title, platform, released, composers, composers_normalized, notes) VALUES
  ('Yakuza',                                    'PlayStation 2',                          '2005-12-08', NULL, NULL, 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 13 Yakuza). Original PS2 entry. Contributor flagged uncertainty: "Was EXS24 and this patch available in 2005?"'),
  ('Yakuza 2',                                  'PlayStation 2',                          '2006-12-07', NULL, NULL, 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 13 Yakuza).'),
  ('Yakuza 3',                                  'PlayStation 3',                          '2009-02-26', NULL, NULL, 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 13 Yakuza). Only 1 source row identified.'),
  ('Yakuza 4',                                  'PlayStation 3',                          '2010-03-18', NULL, NULL, 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 13 Yakuza).'),
  ('Kurohyou: Ryu ga Gotoku Shinsho (Yakuza PSP)', 'PlayStation Portable',                '2010-09-22', NULL, NULL, 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 13 Yakuza). PSP spinoff; largest entry in section by row count (~27 rows). Heavy Zero-G Vocal XTC usage for the "SO UNUSUAL" track.'),
  ('Yakuza: Dead Souls',                        'PlayStation 3',                          '2011-06-09', NULL, NULL, 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 13 Yakuza). Zombie-themed spinoff.'),
  ('Kurohyou 2: Ryu ga Gotoku Ashura Hen',      'PlayStation Portable',                   '2012-03-22', NULL, NULL, 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 13 Yakuza). PSP sequel; Japanese subtitle preserved.'),
  ('Yakuza 5',                                  'PlayStation 3',                          '2012-12-06', NULL, NULL, 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 13 Yakuza). All 3 identified samples are unreleased on OST (in-game cutscene-only).'),
  ('Yakuza 0',                                  'PlayStation 3, PlayStation 4, PC, Xbox One', '2015-03-12', NULL, NULL, 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 13 Yakuza). 80s-set prequel.'),
  ('Yakuza Kiwami',                             'PlayStation 3, PlayStation 4, PC, Xbox One', '2016-01-21', NULL, NULL, 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 13 Yakuza). Remake of Yakuza 1.'),
  ('Yakuza: Like a Dragon',                     'PlayStation 4, PlayStation 5, Xbox One, Xbox Series X|S, PC, Nintendo Switch', '2020-01-16', NULL, NULL, 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 13 Yakuza). RPG reboot. Only stuff_to_find rows identified.'),
  ('Like a Dragon: Infinite Wealth',            'PlayStation 4, PlayStation 5, Xbox One, Xbox Series X|S, PC', '2024-01-26', NULL, NULL, 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 13 Yakuza). Only 1 source row identified.');

INSERT INTO usages
  (game_id, product_id, path_bank, preset, notes, raw_source, examples, category, source_family, position)
VALUES
  -- G1: Yakuza — 6 main + 3 stuff = 9 rows
  ((SELECT id FROM games WHERE title = 'Yakuza'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'EXS24' COLLATE NOCASE),
   'Acoustic Pianos', 'Grand Piano', 'Was EXS24 and this patch available in 2005?', NULL, 'Hideout', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Yakuza'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'Classic Stylus -> 67-Crenshaw', '67-Crenshaw a', NULL, NULL, 'Intelligence For Violence, Receive You The Prototype', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Yakuza'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves -> 126-Reaction', '126-Reaction PCF', NULL, NULL, 'Service Games (2005)', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Yakuza'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves -> 126-Transonica', '126-Transonica  Combo', NULL, NULL, 'Service Games (2005)', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Yakuza'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sounds Good' COLLATE NOCASE AND p.name = 'Methods of Mayhem' COLLATE NOCASE),
   'Nasty', 'Ear Candy 02 51-02', NULL, NULL, 'Scarlet Scar', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'Yakuza'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Technotrance' COLLATE NOCASE),
   'Hardcore Loops -> Arpeggios', '37b01gro160', NULL, NULL, 'For Who''s Sake', 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'Yakuza'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Atmosphere' COLLATE NOCASE),
   NULL, NULL, 'Confirmed by Shoji', NULL, NULL, 'stuff_to_find', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'Yakuza'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves', NULL, 'main loops + also uses a conga loop', NULL, 'Turning Point', 'stuff_to_find', 'newer_vgm', 8),
  ((SELECT id FROM games WHERE title = 'Yakuza'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves', NULL, NULL, NULL, 'Poison Pill', 'stuff_to_find', 'newer_vgm', 9),

  -- G2: Yakuza 2 — 10 main + 6 stuff = 16 rows
  ((SELECT id FROM games WHERE title = 'Yakuza 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Masterbits' COLLATE NOCASE AND p.name = 'RAPsody' COLLATE NOCASE),
   'Track 05 - Yoho Chink -> TS 0:00', 'Diingeling ding dong ...', NULL, NULL, 'Block Head Boy', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Yakuza 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Masterbits' COLLATE NOCASE AND p.name = 'RAPsody' COLLATE NOCASE),
   'Track 30 - Too tough ! -> TS 0:00', 'Uh, a n ...', '"Rough stuff.."', NULL, 'Tracker', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Yakuza 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sonic Foundry' COLLATE NOCASE AND p.name = 'Euro Techno - Ground Loops' COLLATE NOCASE),
   'Scratch & Vinyl Bits', 'Scratch 35', NULL, NULL, 'Block Head Boy', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Yakuza 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Bonus Spectrasonics S.A.G.E. Xpander' COLLATE NOCASE),
   'Distorted Reality 060-089', '73-Blasting Caps', NULL, NULL, 'Wirepuller', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Yakuza 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves -> 60-Volcano', '60-Volcano  Combo', NULL, NULL, 'Push Me Under Water', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'Yakuza 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves -> 135-Hysteria', '135-Hysteria  Combo a', NULL, NULL, 'Tracker, Bad Fortune Flower, A Scattered Moment', 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'Yakuza 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves -> 135-Horse Fury', '?', NULL, NULL, 'The Grudge', 'main', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'Yakuza 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves -> 135-Vertigo', '135-Vertigo Beat', NULL, NULL, 'Push Me Under Water', 'main', 'newer_vgm', 8),
  ((SELECT id FROM games WHERE title = 'Yakuza 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves -> 140-Run Lola Run', '140-Run Lola Run Fuzz', NULL, NULL, 'West Insanity', 'main', 'newer_vgm', 9),
  ((SELECT id FROM games WHERE title = 'Yakuza 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves -> 160-The Call', '160-The Call Breakbeat Stutters', NULL, NULL, 'Tracker', 'main', 'newer_vgm', 10),
  ((SELECT id FROM games WHERE title = 'Yakuza 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Ra' COLLATE NOCASE),
   NULL, NULL, 'Shamisen', NULL, 'No Laughter', 'stuff_to_find', 'newer_vgm', 11),
  ((SELECT id FROM games WHERE title = 'Yakuza 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'PrimeSounds' COLLATE NOCASE AND p.name = 'Methods of Mayhem II' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, 'Face to Face', 'stuff_to_find', 'newer_vgm', 12),
  ((SELECT id FROM games WHERE title = 'Yakuza 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Bonus Spectrasonics S.A.G.E. Xpander' COLLATE NOCASE),
   NULL, NULL, 'Distorted Reality 1 or 2 loop', NULL, 'The Grudge', 'stuff_to_find', 'newer_vgm', 13),
  ((SELECT id FROM games WHERE title = 'Yakuza 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Burning Grooves S.A.G.E. Xpander' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, 'North Menace', 'stuff_to_find', 'newer_vgm', 14),
  ((SELECT id FROM games WHERE title = 'Yakuza 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Burning Grooves S.A.G.E. Xpander' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, 'Evil Itself', 'stuff_to_find', 'newer_vgm', 15),
  ((SELECT id FROM games WHERE title = 'Yakuza 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, 'Outlaw''s Lullaby', 'stuff_to_find', 'newer_vgm', 16),

  -- G3: Yakuza 3 — 1 row
  ((SELECT id FROM games WHERE title = 'Yakuza 3'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves -> 126-Transonica', '126-Transonica Kick', NULL, NULL, 'Dead Run', 'main', 'newer_vgm', 1),

  -- G4: Yakuza 4 — 3 main + 4 stuff = 7 rows
  ((SELECT id FROM games WHERE title = 'Yakuza 4'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Native Instruments' COLLATE NOCASE AND p.name = 'Absynth' COLLATE NOCASE),
   'Abynth Legacy', 'Pulso 3', NULL, NULL, 'GET TO THE TOP! ～森 摩耶～', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Yakuza 4'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Omnisphere' COLLATE NOCASE),
   'Synth Mono', 'Greasy Lead', NULL, NULL, 'Speed Star', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Yakuza 4'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Hardcore' COLLATE NOCASE),
   'DJ Brisk -> Vocals', 'Sky Vox', NULL, NULL, 'JeweL', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Yakuza 4'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, 'Theme of Saigoh', 'stuff_to_find', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Yakuza 4'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, 'Roarless Dragon', 'stuff_to_find', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'Yakuza 4'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, 'Underground Dazzling Star '' Mashup''', 'stuff_to_find', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'Yakuza 4'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Omnisphere' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, 'JeweL', 'stuff_to_find', 'newer_vgm', 7),

  -- G5: Yakuza: Dead Souls — 1 main + 4 stuff = 5 rows
  ((SELECT id FROM games WHERE title = 'Yakuza: Dead Souls'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves -> 79-Bossa Love', '79-BossaLuv Combo a', NULL, NULL, '花「はしる」', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Yakuza: Dead Souls'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, '緊張', 'stuff_to_find', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Yakuza: Dead Souls'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, '不穏な空気', 'stuff_to_find', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Yakuza: Dead Souls'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Trilian' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, '緊張', 'stuff_to_find', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Yakuza: Dead Souls'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Omnisphere' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, 'JeweL OF THE END', 'stuff_to_find', 'newer_vgm', 5),

  -- G6: Kurohyou: Ryu ga Gotoku Shinsho (Yakuza PSP) — 24 main + 3 stuff = 27 rows
  ((SELECT id FROM games WHERE title = 'Kurohyou: Ryu ga Gotoku Shinsho (Yakuza PSP)'),
   NULL, NULL, 'Timestamp 0:00', 'Bass (C)', 'Sample: Lunatic Calm - Leave You Far Behind', 'YOUR KNIFE FEELS GOOD', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Kurohyou: Ryu ga Gotoku Shinsho (Yakuza PSP)'),
   NULL, NULL, 'Timestamp 2:25', 'Synth bass, layered with above', 'Sample: The Prodigy - Colours', 'YOUR KNIFE FEELS GOOD', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Kurohyou: Ryu ga Gotoku Shinsho (Yakuza PSP)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Midi Mark Productions' COLLATE NOCASE AND p.name = 'Vocal Bytes' COLLATE NOCASE),
   'Track 38 - EUGENE HENDERSON -> TS 0:23', 'Get down to this sound', NULL, NULL, 'YOUR KNIFE FEELS GOOD', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Kurohyou: Ryu ga Gotoku Shinsho (Yakuza PSP)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'PowerFX' COLLATE NOCASE AND p.name = 'The Electro Jazz Retro Funk Thing' COLLATE NOCASE),
   'Track 06 - 105 Precinct Cmin -> TS 0:57', 'synth pad', NULL, NULL, 'YOUR KNIFE FEELS GOOD', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Kurohyou: Ryu ga Gotoku Shinsho (Yakuza PSP)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sonic Foundry & Hook Up' COLLATE NOCASE AND p.name = '日本語取扱説明書 CD-ROM' COLLATE NOCASE),
   'Loops for ACID Demo -> Audio -> EssentialsoundsII', 'Shiny Dirt', 'Appears in SF''s demo samples', NULL, 'YOUR KNIFE FEELS GOOD', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'Kurohyou: Ryu ga Gotoku Shinsho (Yakuza PSP)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves -> 126-Transonica', '126-Transonica HiHats', NULL, NULL, 'Die Anyway', 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'Kurohyou: Ryu ga Gotoku Shinsho (Yakuza PSP)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Ueberschall' COLLATE NOCASE AND p.name = 'Nu Metal' COLLATE NOCASE),
   'CD 1 -> Track 35', 'Timestamp 01:08', NULL, NULL, 'SO UNUSUAL', 'main', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'Kurohyou: Ryu ga Gotoku Shinsho (Yakuza PSP)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'UltimateSoundBank' COLLATE NOCASE AND p.name = 'Soundscan Vol. 18 - Funky Vocals' COLLATE NOCASE),
   '35-ELECTRONIC VOX A', 'FEELSGOOD3', NULL, NULL, 'YOUR KNIFE FEELS GOOD', 'main', 'newer_vgm', 8),
  ((SELECT id FROM games WHERE title = 'Kurohyou: Ryu ga Gotoku Shinsho (Yakuza PSP)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'UltimateSoundBank' COLLATE NOCASE AND p.name = 'Soundscan Vol. 26 - Big Beat Vol. 2 Samples' COLLATE NOCASE),
   'Partition C -> REVERSE KIT', 'REVERSE KIT', 'FADEINREV', NULL, 'THE NAKED PANTHER', 'main', 'newer_vgm', 9),
  ((SELECT id FROM games WHERE title = 'Kurohyou: Ryu ga Gotoku Shinsho (Yakuza PSP)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Chemical Beats' COLLATE NOCASE),
   'FX Loops-096', '096-FX Loop 09', NULL, NULL, 'DIGITALIZED', 'main', 'newer_vgm', 10),
  ((SELECT id FROM games WHERE title = 'Kurohyou: Ryu ga Gotoku Shinsho (Yakuza PSP)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Hardcore' COLLATE NOCASE),
   'DJ Brisk -> 303', 'Bouncer', NULL, NULL, 'YOUR KNIFE FEELS GOOD', 'main', 'newer_vgm', 11),
  ((SELECT id FROM games WHERE title = 'Kurohyou: Ryu ga Gotoku Shinsho (Yakuza PSP)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Interface Guitar' COLLATE NOCASE),
   'Rock -> Rock 116-BPM', 'Rock 116 05-E', NULL, NULL, 'YOUR KNIFE FEELS GOOD', 'main', 'newer_vgm', 12),
  ((SELECT id FROM games WHERE title = 'Kurohyou: Ryu ga Gotoku Shinsho (Yakuza PSP)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Rock & Pop Vocals' COLLATE NOCASE),
   'Track 02 - ''Keith'' Shannon -> Sample 7', 'Let Me Tell You Now 2', NULL, NULL, 'YOUR KNIFE FEELS GOOD', 'main', 'newer_vgm', 13),
  ((SELECT id FROM games WHERE title = 'Kurohyou: Ryu ga Gotoku Shinsho (Yakuza PSP)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Rock & Pop Vocals' COLLATE NOCASE),
   'Track 02 - ''Keith'' Shannon -> Sample 8', 'Let Me Tell You Now 3', '"I''m tired of your loving"', NULL, 'YOUR KNIFE FEELS GOOD', 'main', 'newer_vgm', 14),
  ((SELECT id FROM games WHERE title = 'Kurohyou: Ryu ga Gotoku Shinsho (Yakuza PSP)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Rock & Pop Vocals' COLLATE NOCASE),
   'Track 02 - ''Keith'' Shannon -> Sample 9', 'Your Life Is A Gift', NULL, NULL, 'YOUR KNIFE FEELS GOOD', 'main', 'newer_vgm', 15),
  ((SELECT id FROM games WHERE title = 'Kurohyou: Ryu ga Gotoku Shinsho (Yakuza PSP)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Twisted City' COLLATE NOCASE),
   'Track 08 - Twisted Beats -> TS 0:59', 'Pelvic Trust', NULL, NULL, 'YOUR KNIFE FEELS GOOD', 'main', 'newer_vgm', 16),
  ((SELECT id FROM games WHERE title = 'Kurohyou: Ryu ga Gotoku Shinsho (Yakuza PSP)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Upfront Lead Guitar' COLLATE NOCASE),
   'Track 06 - Metal/Grunge -> Sample 2', 'Country Metal 108 2', NULL, NULL, 'DIGITALIZED', 'main', 'newer_vgm', 17),
  ((SELECT id FROM games WHERE title = 'Kurohyou: Ryu ga Gotoku Shinsho (Yakuza PSP)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Vocal XTC' COLLATE NOCASE),
   'Track 34 - Male - Rob Marshall -> TS 0:11', 'You Are So Stupid... B', NULL, NULL, 'SO UNUSUAL', 'main', 'newer_vgm', 18),
  ((SELECT id FROM games WHERE title = 'Kurohyou: Ryu ga Gotoku Shinsho (Yakuza PSP)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Vocal XTC' COLLATE NOCASE),
   'Track 34 - Male - Rob Marshall -> TS 0:27', 'You Look So Sad G', NULL, NULL, 'SO UNUSUAL', 'main', 'newer_vgm', 19),
  ((SELECT id FROM games WHERE title = 'Kurohyou: Ryu ga Gotoku Shinsho (Yakuza PSP)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Vocal XTC' COLLATE NOCASE),
   'Track 35 - Male - Rob Marshall -> TS 0:00', 'Cos You Are So Cold To Me B 120', NULL, NULL, 'SO UNUSUAL', 'main', 'newer_vgm', 20),
  ((SELECT id FROM games WHERE title = 'Kurohyou: Ryu ga Gotoku Shinsho (Yakuza PSP)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Vocal XTC' COLLATE NOCASE),
   'Track 35 - Male - Rob Marshall -> TS 0:20', 'Meant for you... A', NULL, NULL, 'SO UNUSUAL', 'main', 'newer_vgm', 21),
  ((SELECT id FROM games WHERE title = 'Kurohyou: Ryu ga Gotoku Shinsho (Yakuza PSP)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Vocal XTC' COLLATE NOCASE),
   'Track 36 - Male - Rob Marshall -> TS 0:41', 'You''re So Unusual, You''re Strange E', NULL, NULL, 'SO UNUSUAL', 'main', 'newer_vgm', 22),
  ((SELECT id FROM games WHERE title = 'Kurohyou: Ryu ga Gotoku Shinsho (Yakuza PSP)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Vocal XTC' COLLATE NOCASE),
   'Track 37 - Male - Rob Marshall -> TS 0:38', 'Never Any Time... B 80', NULL, NULL, 'SO UNUSUAL', 'main', 'newer_vgm', 23),
  ((SELECT id FROM games WHERE title = 'Kurohyou: Ryu ga Gotoku Shinsho (Yakuza PSP)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Vocal XTC' COLLATE NOCASE),
   'Track 37 - Male - Rob Marshall -> TS 0:42', 'Never Any Time... (Harmony) C 80', NULL, NULL, 'SO UNUSUAL', 'main', 'newer_vgm', 24),
  ((SELECT id FROM games WHERE title = 'Kurohyou: Ryu ga Gotoku Shinsho (Yakuza PSP)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Ueberschall' COLLATE NOCASE AND p.name = 'Big Beat' COLLATE NOCASE),
   NULL, NULL, 'Cymbal', NULL, 'THE NAKED PANTHER', 'stuff_to_find', 'newer_vgm', 25),
  ((SELECT id FROM games WHERE title = 'Kurohyou: Ryu ga Gotoku Shinsho (Yakuza PSP)'),
   NULL, NULL, NULL, 'Scratching FX Loop', '? (Sample Loop Library)', 'DIGITALIZED, SOLIDNESS (Unused)', 'stuff_to_find', 'newer_vgm', 26),
  ((SELECT id FROM games WHERE title = 'Kurohyou: Ryu ga Gotoku Shinsho (Yakuza PSP)'),
   NULL, NULL, NULL, 'String Loop', '? (Sample Loop Library)', 'YOUR KNIFE FEELS GOOD', 'stuff_to_find', 'newer_vgm', 27),

  -- G7: Kurohyou 2 — 8 rows
  ((SELECT id FROM games WHERE title = 'Kurohyou 2: Ryu ga Gotoku Ashura Hen'),
   NULL, NULL, 'Timestamp 0:07', NULL, 'Sample: Lunatic Calm - Leave You Far Behind', 'LUST 4 POWER', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Kurohyou 2: Ryu ga Gotoku Ashura Hen'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'Loops' COLLATE NOCASE),
   'Apple Loops for GarageBand', 'Mini Mono Synth 03', NULL, NULL, 'LUST 4 POWER', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Kurohyou 2: Ryu ga Gotoku Ashura Hen'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Big Fish Audio' COLLATE NOCASE AND p.name = 'Big Beat - Megaton Bomb Vol. 4' COLLATE NOCASE),
   'CD 2 -> Track 01 -> TS 0:59', 'hit E 123.74', NULL, NULL, 'THE ELECTRIZER', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Kurohyou 2: Ryu ga Gotoku Ashura Hen'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'MOTU' COLLATE NOCASE AND p.name = 'Digital Performer 4' COLLATE NOCASE),
   'DP Demo Projects -> Can Tommy Come Out & Play', 'Main Loop-1', NULL, NULL, 'LUST 4 POWER', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Kurohyou 2: Ryu ga Gotoku Ashura Hen'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Native Instruments' COLLATE NOCASE AND p.name = 'FM8' COLLATE NOCASE),
   'FM8 Factory', 'Aqua Atmo', NULL, NULL, 'PANTHER IN THE STORM', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'Kurohyou 2: Ryu ga Gotoku Ashura Hen'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Ueberschall' COLLATE NOCASE AND p.name = 'Big Beat' COLLATE NOCASE),
   'Track 90 - Single Drums -> TS 0:00', 'cymbals', NULL, NULL, 'LUST 4 POWER', 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'Kurohyou 2: Ryu ga Gotoku Ashura Hen'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'UltimateSoundBank' COLLATE NOCASE AND p.name = 'Soundscan Vol. 26 - Big Beat Vol. 2 Samples' COLLATE NOCASE),
   'Partition F -> SEQS 105-130', 'SEQ105-130 K', '120SEQMOD2', NULL, 'LUST 4 POWER', 'main', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'Kurohyou 2: Ryu ga Gotoku Ashura Hen'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Chemical Beats' COLLATE NOCASE),
   'CD 2 -> Partition E -> MADLOOPS', 'MADLOOPS  120', '120MADLP05', NULL, 'NEO-FRANTIC', 'main', 'newer_vgm', 8),

  -- G8: Yakuza 5 — 3 rows
  ((SELECT id FROM games WHERE title = 'Yakuza 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves -> 160-Find The Exit', '160-Find The Exit Combo', 'Custom Loop', NULL, NULL, 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Yakuza 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves ->  60-Volcano', '60-Volcano Kabuki Wood', 'Custom Loop', NULL, '(seemingly not on OST - plays in Part 2, Chapter 2 immediately after the deputy warden lets out Saejima)', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Yakuza 5'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves -> 64-Foggy Skyline', '61-Foggy Skyline Combo', 'Custom Loop', NULL, '(seemingly not on OST - plays in early Part 2 during the ''visualising Tsukimino'' cutscene)', 'main', 'newer_vgm', 3),

  -- G9: Yakuza 0 — 8 main + 6 stuff = 14 rows
  ((SELECT id FROM games WHERE title = 'Yakuza 0'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'Logic Pro' COLLATE NOCASE),
   'World -> South Asian', 'Indian & Middle Eastern Kit', NULL, NULL, '唖然呆然', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Yakuza 0'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'Perc -> Metals', 'Orch chimes', NULL, NULL, 'Mad Desire', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Yakuza 0'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Heavyocity' COLLATE NOCASE AND p.name = 'Damage' COLLATE NOCASE),
   '01 Rhythmic Suites -> Loop Menus', 'LPS Industrial Full', NULL, NULL, 'Fiercest Warrior ver 0', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Yakuza 0'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Native Instruments' COLLATE NOCASE AND p.name = 'Kontakt Factory Library' COLLATE NOCASE),
   'Band -> 5 - Guitar', NULL, NULL, NULL, 'ハジマリノシラベ', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Yakuza 0'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Native Instruments' COLLATE NOCASE AND p.name = 'FM8' COLLATE NOCASE),
   'FM8 Factory', 'Rock Baby', NULL, NULL, NULL, 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'Yakuza 0'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves -> 125-Elephant Boy', '125-Elephant Boy Perc', NULL, NULL, '平静と困惑のあいだ', 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'Yakuza 0'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves -> 160-Spheres ', '160-Spheres Stars', NULL, NULL, 'ON THE EDGE', 'main', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'Yakuza 0'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'Sound Menus -> Cymbals', 'MENU - All Cymbals Hi-Fi', 'D3, C4', NULL, 'Parry Addiction, Crash Addiction, Rocket Nuts Groove', 'main', 'newer_vgm', 8),
  ((SELECT id FROM games WHERE title = 'Yakuza 0'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Omnisphere' COLLATE NOCASE),
   'Distortion', 'Shredder Head', NULL, NULL, 'Archnemesis', 'main', 'newer_vgm', 9),
  ((SELECT id FROM games WHERE title = 'Yakuza 0'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Reveal Sound' COLLATE NOCASE AND p.name = 'Spire ?' COLLATE NOCASE),
   '?', NULL, NULL, NULL, NULL, 'stuff_to_find', 'newer_vgm', 10),
  ((SELECT id FROM games WHERE title = 'Yakuza 0'),
   NULL, NULL, NULL, NULL, 'Roland - ?', 'Beyond the Speed', 'stuff_to_find', 'newer_vgm', 11),
  ((SELECT id FROM games WHERE title = 'Yakuza 0'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Omnisphere' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, NULL, 'stuff_to_find', 'newer_vgm', 12),
  ((SELECT id FROM games WHERE title = 'Yakuza 0'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'Classic Stylus -> Congas', '?', NULL, NULL, 'Mad Desire', 'stuff_to_find', 'newer_vgm', 13),
  ((SELECT id FROM games WHERE title = 'Yakuza 0'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Burning Grooves S.A.G.E. Xpander' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, 'With Vengeance', 'stuff_to_find', 'newer_vgm', 14),

  -- G10: Yakuza Kiwami — 3 rows
  ((SELECT id FROM games WHERE title = 'Yakuza Kiwami'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'XLN Audio' COLLATE NOCASE AND p.name = 'Addictive Drums' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, 'Parry Addiction, Customer Creed', 'stuff_to_find', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Yakuza Kiwami'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Heavyocity' COLLATE NOCASE AND p.name = 'Evolve R2' COLLATE NOCASE),
   '1 Rythmic Suites -> Looped Percussives', 'Dramatic Evolved 01', NULL, NULL, '迫', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Yakuza Kiwami'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Omnisphere' COLLATE NOCASE),
   'ARP + BPM', 'The Big Nasty', NULL, NULL, 'Flirt With Bomb', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Yakuza Kiwami'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Trilian' COLLATE NOCASE),
   'Bass - Electric Picked', 'Rock P-Bass Pick - Full Range', NULL, NULL, '迫', 'main', 'newer_vgm', 4),

  -- G11: Yakuza: Like a Dragon — 2 stuff_to_find rows
  ((SELECT id FROM games WHERE title = 'Yakuza: Like a Dragon'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Omnisphere' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, 'Korean Mafia', 'stuff_to_find', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Yakuza: Like a Dragon'),
   NULL, NULL, NULL, 'Amen Break', NULL, 'Korean Mafia', 'stuff_to_find', 'newer_vgm', 2),

  -- G12: Like a Dragon: Infinite Wealth — 1 row
  ((SELECT id FROM games WHERE title = 'Like a Dragon: Infinite Wealth'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Omnisphere' COLLATE NOCASE),
   'ARP + BPM', 'Lil Bouncer Strat Pick', NULL, NULL, 'Reminiscent Mood', 'main', 'newer_vgm', 1);
