-- NEWER VGM SEGA/Atlus — "Section 17 - Other" sub-batch C (mid-2000s DS through Metaphor 2024)
--
-- Source: reference/NEWER VGM Sound Sources - SEGAAtlus.csv lines 3342-3602.
-- 18 game/album records, ~225 usage rows.
--
-- Final SEGA/Atlus sub-batch covering mid-2000s DS through 2024
-- Atlus flagship releases. Feel the Magic's "Music Jingles" sub-section
-- is split into its own game record per the arrange-album convention
-- (the jingles list is grouped under its own CSV sub-header and
-- references different game tracks — "Antlion", "Bull", "Bus Stop",
-- "Clean Up", "Painter", etc. — that don't overlap with the main
-- music tracks).
--
-- Composer credits (in-CSV):
--   - SEGA Superstars         — Tomoya Ohtani, Mariko Nanba
--   - Feel the Magic: XY/XX   — Naofumi Hataya, Mariko Nanba (applied to both
--                                main entry and Music Jingles sub-entry)
--   - The Rub Rabbits!        — Naofumi Hataya
--   - Blazer Drive            — Tomonori Sawada
--   - Radiant Historia        — Yoko Shimomura
--
-- New manufacturers introduced this batch:
--   - AIR Music Technology    (Vacuum, Xpand!2 — Dengeki Bunko stuff_to_find)
--   - Spitfire Audio          (Hans Zimmer Percussion — Metaphor: ReFantazio)
--   - Vienna Symphonic Library (placeholder ? product — Dengeki Bunko stuff_to_find)
--
-- New products this batch (selection — all INSERT OR IGNORE):
--   - Audiobro / LA Scoring Strings 2  (distinct from existing
--     LA Scoring Strings per Rule 2)
--   - Spitfire Audio / Hans Zimmer Percussion
--   - Native Instruments / The Grandeur
--   - AIR Music Technology / Vacuum, Xpand!2
--   - Toontrack / Superior Drummer 2
--   - Big Fish Audio / Electric Ghetto
--   - EastWest / Percussive Adventures
--   - Spectrasonics / Metamorphosis S.A.G.E. Xpander
--   - AKAI / SG01v
--   - KORG / 05R/W
--   - Yamaha / MU80
--   - Ueberschall / Drum n Bass Fast Forward
--   - Zero-G / Total Rex, Cuckooland Vol. 3 Asylum, The Funky Element
--   - PrimeSounds / Methods of Mayhem II - Damage Control  (distinct
--     from existing "Methods of Mayhem II" per Rule 2)
--   - Heavyocity / Damage path "01 Rhythmic Suites -> Loop Menus" and
--     "02 Percussive Kits -> 05 Damage Kits" — both NEW paths within
--     the existing Heavyocity Damage product
--
-- CSV mangling artifacts preserved or flagged:
--   - Odin Sphere CSV row 3484 reads "(Released: March 17, 2007" with
--     missing closing paren. Normalised to 2007-03-17 in released
--     column; flagged in notes.
--   - Dengeki Bunko CSV uses Spitfire Audio name spelling that
--     standardised to "Spitfire Audio" (verbatim from CSV).
--
-- Stella Glow has a CSV section header (Released: June 4, 2015) but
-- ZERO usage rows. A placeholder game record is created with no
-- usages to surface the contributor's intent to research it later
-- (Rule 11: fail loud — recording absence of data).
--
-- Feel the Magic Music Jingles split (Rule 9 — checkpointable structure):
--   The CSV groups Feel the Magic's jingle/sound-effect cues under a
--   sub-header "Music Jingles" at row 3395 with its own set of cross-
--   media samples and instrument-library references. These reference
--   game tracks ("Antlion", "Bull", "Bus Stop", "Candle", etc.) that
--   are distinct from the main music tracks ("I'd Die For You",
--   "Kimi Shine Love Theme 1", etc.). Split into separate game record
--   to keep the row count per game manageable and matching CSV grouping.

INSERT OR IGNORE INTO manufacturers (name) VALUES
  ('AIR Music Technology'),
  ('Spitfire Audio'),
  ('Vienna Symphonic Library');

INSERT OR IGNORE INTO products (manufacturer_id, name, type) VALUES
  ((SELECT id FROM manufacturers WHERE name = 'Audiobro'                    COLLATE NOCASE), 'LA Scoring Strings 2',                            'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Spitfire Audio'              COLLATE NOCASE), 'Hans Zimmer Percussion',                          'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Native Instruments'          COLLATE NOCASE), 'The Grandeur',                                    'Instrument'),
  ((SELECT id FROM manufacturers WHERE name = 'AIR Music Technology'        COLLATE NOCASE), 'Vacuum',                                          'Synth'),
  ((SELECT id FROM manufacturers WHERE name = 'AIR Music Technology'        COLLATE NOCASE), 'Xpand!2',                                         'Synth'),
  ((SELECT id FROM manufacturers WHERE name = 'Toontrack'                   COLLATE NOCASE), 'Superior Drummer 2',                              'Instrument'),
  ((SELECT id FROM manufacturers WHERE name = 'Big Fish Audio'              COLLATE NOCASE), 'Electric Ghetto',                                 'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'EastWest'                    COLLATE NOCASE), 'Percussive Adventures',                           'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Spectrasonics'               COLLATE NOCASE), 'Metamorphosis S.A.G.E. Xpander',                  'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'AKAI'                        COLLATE NOCASE), 'SG01v',                                           'Hardware'),
  ((SELECT id FROM manufacturers WHERE name = 'KORG'                        COLLATE NOCASE), '05R/W',                                           'Synth'),
  ((SELECT id FROM manufacturers WHERE name = 'Yamaha'                      COLLATE NOCASE), 'MU80',                                            'Synth'),
  ((SELECT id FROM manufacturers WHERE name = 'Ueberschall'                 COLLATE NOCASE), 'Drum n Bass Fast Forward',                        'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Zero-G'                      COLLATE NOCASE), 'Total Rex',                                       'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Zero-G'                      COLLATE NOCASE), 'Cuckooland Vol. 3 Asylum',                        'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Zero-G'                      COLLATE NOCASE), 'The Funky Element',                               'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'PrimeSounds'                 COLLATE NOCASE), 'Methods of Mayhem II - Damage Control',           'Sample Library');

INSERT INTO games (title, platform, released, composers, composers_normalized, notes) VALUES
  ('SEGA Superstars',                              'PlayStation 2 (EyeToy)', '2004-10-22', 'Tomoya Ohtani, Mariko Nanba',    'tomoya ohtani, mariko nanba',    'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 17 Other). EyeToy PS2 launch title; sample-heavy with cross-media references.'),
  ('Feel the Magic: XY/XX',                        'Nintendo DS',            '2004-11-18', 'Naofumi Hataya, Mariko Nanba',   'naofumi hataya, mariko nanba',   'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 17 Other). Nintendo DS launch title; main music tracks. The CSV''s "Music Jingles" sub-section is split into a separate game record.'),
  ('Feel the Magic: XY/XX (Music Jingles)',        'Nintendo DS',            '2004-11-18', 'Naofumi Hataya, Mariko Nanba',   'naofumi hataya, mariko nanba',   'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 17 Other). Music Jingles sub-section: jingle/SFX cues for non-music game elements (Antlion, Bull, Bus Stop, Candle, Chaser, Clean Up, Painter, etc.).'),
  ('The Rub Rabbits!',                             'Nintendo DS',            '2005-10-20', 'Naofumi Hataya',                 'naofumi hataya',                 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 17 Other). Feel the Magic sequel.'),
  ('Stuart Little 3: Big Photo Adventure',         'PlayStation 2',          '2005-11-14', NULL,                             NULL,                             'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 17 Other). All five rows reference AMG & Hit Music ""Norman Cook - Skip to my Loops"" for "The Garden" track.'),
  ('Luminous Arc',                                 'Nintendo DS',            '2007-02-08', NULL,                             NULL,                             'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 17 Other). DS SRPG; orchestral sample-library based score.'),
  ('Odin Sphere',                                  'PlayStation 2',          '2007-03-17', NULL,                             NULL,                             'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 17 Other). CSV row 3484 has unclosed paren "(Released: March 17, 2007" — released date normalised. Introduces EastWest Percussive Adventures.'),
  ('Luminous Arc 2',                               'Nintendo DS',            '2008-05-15', NULL,                             NULL,                             'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 17 Other). Sequel to Luminous Arc; same orchestral library stack.'),
  ('Thunder Force VI',                             'PlayStation 2',          '2008-10-30', NULL,                             NULL,                             'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 17 Other). Only two source rows identified. CSV notes that the Zero-G Altered States sample is "From Cuckooland Vol. 1 Unhinged".'),
  ('Blazer Drive',                                 'Nintendo DS',            '2008-12-04', 'Tomonori Sawada',                'tomonori sawada',                'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 17 Other). DS card-battle title; introduces Ueberschall Drum n Bass Fast Forward and Zero-G Total Rex sample libraries.'),
  ('Let''s Tap',                                   'Wii',                    '2008-12-18', NULL,                             NULL,                             'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 17 Other). Wii rhythm-tap title.'),
  ('Shining Force Feather',                        'Nintendo DS',            '2009-02-19', NULL,                             NULL,                             'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 17 Other). Only one confirmed source row (XLN Audio Addictive Drums) plus six Stuff to Find candidates spanning AKAI SG01v, KORG 05R/W + WAVESTATION SR, Yamaha MU80, Apple Logic Pro.'),
  ('Radiant Historia',                             'Nintendo DS',            '2010-11-03', 'Yoko Shimomura',                 'yoko shimomura',                 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 17 Other). Yoko Shimomura score; introduces Spectrasonics Metamorphosis S.A.G.E. Xpander.'),
  ('Dengeki Bunko: Fighting Climax',               'PlayStation 3',          '2014-11-13', NULL,                             NULL,                             'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 17 Other). PS3/Vita release date used (arcade release was earlier in 2014). Introduces AIR Music Technology Vacuum/Xpand!2 and Toontrack Superior Drummer 2.'),
  ('Stella Glow',                                  'Nintendo 3DS',           '2015-06-04', NULL,                             NULL,                             'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 17 Other). PLACEHOLDER — CSV row 3569 has the section header and release date but ZERO source rows. Recording absence of data per Rule 11 (fail loud); future contributors may attach rows.'),
  ('Tokyo Mirage Sessions #FE',                    'Wii U',                  '2015-12-26', NULL,                             NULL,                             'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 17 Other). Atlus / Intelligent Systems / Nintendo collaboration. CSV uses literal-quote track name ""b09_f_shibuya""; preserved verbatim.'),
  ('Catherine: Full Body',                         'PlayStation 4',          '2019-02-14', NULL,                             NULL,                             'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 17 Other). Heavy Spectrasonics Stylus RMX Classic Stylus usage + AMG Kick-Ass Brass! reuse from Trauma Center pattern.'),
  ('Metaphor: ReFantazio',                         'PlayStation 5',          '2024-10-11', NULL,                             NULL,                             'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 17 Other). Latest Atlus flagship in this dataset; introduces Spitfire Audio Hans Zimmer Percussion, Native Instruments The Grandeur, and Audiobro LA Scoring Strings 2.');

INSERT INTO usages
  (game_id, product_id, path_bank, preset, notes, raw_source, examples, category, source_family, position)
VALUES
  -- G1: SEGA Superstars — 12 main + 2 stuff = 14
  ((SELECT id FROM games WHERE title = 'SEGA Superstars'),
   NULL, NULL, 'Timestamp 0:00', 'Conga Loop', 'Sample: Afrique - Slow Motion', 'Options', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'SEGA Superstars'),
   NULL, NULL, 'Timestamp 0:05', 'Organ Phrase', 'Sample: Alan Hawkshaw - Tap Footer', 'Main Theme', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'SEGA Superstars'),
   NULL, NULL, 'Timestamp 0:00', 'Drum Loop', 'Sample: Anne Murray - Put Your Hand In The Hand', 'Main Theme', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'SEGA Superstars'),
   NULL, NULL, 'Timestamp 0:00', 'Hi-Hats', 'Sample: Johnny Pate - Auto Chase', 'Game Selection Screen', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'SEGA Superstars'),
   NULL, NULL, 'Timestamp 0:00', 'Brass', 'Sample: Ken Woodman - Town Talk', 'Game Selection Screen', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'SEGA Superstars'),
   NULL, NULL, 'Timestamp 1:24', 'Drum Loop', 'Sample: Kool And The Gang - Chocolate Buttermilk', 'Options', 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'SEGA Superstars'),
   NULL, NULL, 'Timestamp 3:00', 'Shout', 'Sample: Michel Fugain - La-bas Dans Les Îles', 'Options', 'main', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'SEGA Superstars'),
   NULL, NULL, 'Timestamp 0:00', 'Drum Fill', 'Sample: Ricardo Ray Orchestra - Nitty Gritty', 'Game Selection Screen', 'main', 'newer_vgm', 8),
  ((SELECT id FROM games WHERE title = 'SEGA Superstars'),
   NULL, NULL, 'Timestamp 0:00, 0:04', 'Multiple Elements', 'Sample: Sammy Kaye & His Orchestra - The Huckebuck', 'Game Selection Screen', 'main', 'newer_vgm', 9),
  ((SELECT id FROM games WHERE title = 'SEGA Superstars'),
   NULL, NULL, 'Timestamp 0:03', 'Triangle Loop', 'Sample: The Carnival - Canto De Carnival', 'Options', 'main', 'newer_vgm', 10),
  ((SELECT id FROM games WHERE title = 'SEGA Superstars'),
   NULL, NULL, 'Timestamp 0:00', 'Drum Loop', 'Sample: The Monkees - Mary, Mary', 'Main Theme', 'main', 'newer_vgm', 11),
  ((SELECT id FROM games WHERE title = 'SEGA Superstars'),
   NULL, NULL, 'Timestamp 0:00, 0:07', 'Claps, Drum Loop', 'Sample: The Routers - Let''s Go (Pony)', 'Game Selection Screen', 'main', 'newer_vgm', 12),
  ((SELECT id FROM games WHERE title = 'SEGA Superstars'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Ueberschall' COLLATE NOCASE AND p.name = 'Easy Listening' COLLATE NOCASE),
   'Track 10 -> TS 0:09', 'Brass Trumpet', NULL, NULL, 'Options', 'main', 'newer_vgm', 13),
  ((SELECT id FROM games WHERE title = 'SEGA Superstars'),
   NULL, NULL, NULL, NULL, NULL, NULL, 'stuff_to_find', 'newer_vgm', 14),

  -- G2: Feel the Magic: XY/XX (main music) — 22 main + 12 stuff = 34
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX'),
   NULL, NULL, 'Timestamp 2:41', 'Brass Ending', 'Sample: Jack Ary - Les Tomates', 'I''d Die For You ~Rapid 60''s Tone Mix~', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX'),
   NULL, NULL, 'Timestamp 2:51', 'Shout', 'Sample: Pizzicato Five - Roma', 'Kimi Shine Love Theme 1', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX'),
   NULL, NULL, 'Timestamp 4:01', 'Drum Loop', 'Sample: The Karminsky Experience Inc. - Mah Nà Mah Nà (Karmexperience Mix)', '[Dance]', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 1 -> SYNTHS', 'DS1_4', 'Reversed', NULL, NULL, 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 2 -> ORCHESTR', 'FAN_C', NULL, NULL, NULL, 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 2 -> ORCHESTR', 'FAN_F#', NULL, NULL, NULL, 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 3 -> VOX_A_C', 'AEH', NULL, NULL, 'Kimi Shine Love Theme 1', 'main', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'IK Multimedia' COLLATE NOCASE AND p.name = 'SampleTank 2 XL' COLLATE NOCASE),
   'Drums -> Acoustic', 'Very Old', NULL, NULL, 'I''d Die For You, [Goldfish], Kimi Shine Theme of Danger, [Nightmare], [The Last Battle], I''d Die For You [Web Version], SEQ_TITLE23', 'main', 'newer_vgm', 8),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'IK Multimedia' COLLATE NOCASE AND p.name = 'SampleTank 2 XL' COLLATE NOCASE),
   'Guitar -> Acoustic', 'Fingered 1', NULL, NULL, 'Kimi Shine Love Theme 2', 'main', 'newer_vgm', 9),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'IK Multimedia' COLLATE NOCASE AND p.name = 'SampleTank 2 XL' COLLATE NOCASE),
   'Guitar -> Electric', 'Fuzz LP', NULL, NULL, 'I''d Die For You, [Dance], Kimi Shine Selection Theme, I''d Die For You [Web Version], I''d Die For You ~Rapid 60''s Tone Mix~', 'main', 'newer_vgm', 10),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'IK Multimedia' COLLATE NOCASE AND p.name = 'SampleTank 2 XL' COLLATE NOCASE),
   'Organ', '60s Amp Organ', NULL, NULL, 'Kimi Shine Op, Kimi Shine Theme of Peace, Kimi Shine Love Theme 2, Kimi Shine Ed', 'main', 'newer_vgm', 11),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'IK Multimedia' COLLATE NOCASE AND p.name = 'SampleTank 2 XL' COLLATE NOCASE),
   'Organ', 'B-3 Organ 1', NULL, NULL, '[Dance]', 'main', 'newer_vgm', 12),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'IK Multimedia' COLLATE NOCASE AND p.name = 'SampleTank 2 XL' COLLATE NOCASE),
   'Percussion', 'Vibes 1', NULL, NULL, 'SEQ_TITLE15', 'main', 'newer_vgm', 13),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'IK Multimedia' COLLATE NOCASE AND p.name = 'SampleTank 2 XL' COLLATE NOCASE),
   'Voices', 'Soprano Ahs lite', NULL, NULL, 'Kimi Shine Theme of Peace, Kimi Shine Love Theme 2', 'main', 'newer_vgm', 14),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'JV-2080' COLLATE NOCASE),
   'PR-A', '092 Warm Vibes', NULL, NULL, 'Love''s Ending Theme', 'main', 'newer_vgm', 15),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88 Pro' COLLATE NOCASE),
   'SC-88 Map', '061 000 French Horns', NULL, NULL, 'Love''s Ending Theme', 'main', 'newer_vgm', 16),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88 Pro' COLLATE NOCASE),
   'SC-88 Map', '076 000 Pan Flute', NULL, NULL, 'Love''s Ending Theme', 'main', 'newer_vgm', 17),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SOUND Canvas SC-88 Pro' COLLATE NOCASE),
   'SC-88 Map -> Drum Set', '041 BRUSH', NULL, NULL, 'Love''s Ending Theme', 'main', 'newer_vgm', 18),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Ueberschall' COLLATE NOCASE AND p.name = 'Brazil Electro' COLLATE NOCASE),
   'BEATLOOPS -> nova mood 95 bpm', 'nova m95 mix-#170', NULL, NULL, 'Kimi Shine Theme of Peace, Kimi Shine Ed', 'main', 'newer_vgm', 19),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Ueberschall' COLLATE NOCASE AND p.name = 'Brazil Electro' COLLATE NOCASE),
   'BEATLOOPS -> sidekick beat 100 bpm', 'sidekick100 mix-#195', NULL, NULL, 'Kimi Shine Theme of Peace (OST)', 'main', 'newer_vgm', 20),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'The Funky Element' COLLATE NOCASE),
   'Track 02 - vinyl-style loops -> TS 0:00', 'booming beats 109 BPM', NULL, NULL, 'Kimi Shine Love Theme 1', 'main', 'newer_vgm', 21),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'The Funky Element' COLLATE NOCASE),
   'Track 02 - vinyl-style loops -> TS 0:13', 'the gut bucket funk break 110', NULL, NULL, 'Kimi Shine Love Theme 1', 'main', 'newer_vgm', 22),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX'),
   NULL, NULL, NULL, 'Crash Cymbal', 'Roland - ? (SOUND Canvas SC-88 Pro or JV-2080)', 'I''d Die For You, [Dance]', 'stuff_to_find', 'newer_vgm', 23),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Vocal Planet' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, NULL, 'stuff_to_find', 'newer_vgm', 24),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'The Funky Element' COLLATE NOCASE),
   NULL, NULL, 'Track 96 or 97 or 98 (Percussion Loop)', NULL, 'Kimi Shine Love Theme 1', 'stuff_to_find', 'newer_vgm', 25),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX'),
   NULL, NULL, NULL, 'Bass', NULL, 'I''d Die For You', 'stuff_to_find', 'newer_vgm', 26),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX'),
   NULL, NULL, NULL, '60''s Drum Fill / Bass Drum, Hi-Hat', NULL, 'I''d Die For You, [Goldfish]', 'stuff_to_find', 'newer_vgm', 27),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX'),
   NULL, NULL, NULL, 'Syn. Organ', NULL, 'Kimi Shine Love Theme 1', 'stuff_to_find', 'newer_vgm', 28),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX'),
   NULL, NULL, NULL, 'Synth', NULL, 'Kimi Shine Love Theme 1', 'stuff_to_find', 'newer_vgm', 29),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX'),
   NULL, NULL, NULL, '2 Vocals', NULL, 'Kimi Shine Love Theme 1', 'stuff_to_find', 'newer_vgm', 30),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX'),
   NULL, NULL, NULL, 'Bass', NULL, 'Love''s Ending Theme', 'stuff_to_find', 'newer_vgm', 31),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX'),
   NULL, NULL, NULL, 'Strings', NULL, 'Love''s Ending Theme', 'stuff_to_find', 'newer_vgm', 32),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX'),
   NULL, NULL, NULL, 'Open Hi-Hat', NULL, 'Love''s Ending Theme', 'stuff_to_find', 'newer_vgm', 33),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX'),
   NULL, NULL, NULL, 'Female Vocal Loop', NULL, 'Kimi Shine Ed', 'stuff_to_find', 'newer_vgm', 34);

-- G3: Feel the Magic: XY/XX (Music Jingles) — 43 main + 6 stuff = 49 rows
INSERT INTO usages
  (game_id, product_id, path_bank, preset, notes, raw_source, examples, category, source_family, position)
VALUES
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX (Music Jingles)'),
   NULL, NULL, 'Timestamp 0:49', 'Brass Hit', 'Sample: Juan Erlando & His Latin Band - Jungle Baby', 'Kimi Shine Jingle 1 (Break Time 01)', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX (Music Jingles)'),
   NULL, NULL, 'Timestamp 2:11', 'String Rip', 'Sample: Marty Gold & His Orchestra - The Donkey Serenade', 'Kimi Shine Jingle 1 (Break Time 01)', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX (Music Jingles)'),
   NULL, NULL, 'Timestamp 1:54', 'Brass Phrase', 'Sample: SEGA - We''re a Dancing Team!', 'Dance', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX (Music Jingles)'),
   NULL, NULL, 'Timestamp 0:00', 'Piano Glissando', 'Sample: Xavier Cugat & His Orchestra - Danse Des Mirlitons', NULL, 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX (Music Jingles)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 1 -> GUIT_120', 'HENDRIXG', NULL, NULL, 'Clean Up', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX (Music Jingles)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 1 -> HORNS', 'BS_01', NULL, NULL, 'Chaser', 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX (Music Jingles)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 1 -> HORNS', 'BS_05', NULL, NULL, 'Goldfish', 'main', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX (Music Jingles)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 1 -> HORNS', 'BS_14', NULL, NULL, 'Bus Stop', 'main', 'newer_vgm', 8),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX (Music Jingles)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 1 -> HORNS', 'BS_20', NULL, NULL, 'Last Battle', 'main', 'newer_vgm', 9),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX (Music Jingles)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 1 -> HORNS', 'BS_24', NULL, NULL, 'Bull', 'main', 'newer_vgm', 10),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX (Music Jingles)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 1 -> HORNS', 'BS_25', NULL, NULL, 'Bull', 'main', 'newer_vgm', 11),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX (Music Jingles)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 1 -> HORNS', 'BS_26', NULL, NULL, 'Bull, Painter', 'main', 'newer_vgm', 12),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX (Music Jingles)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 1 -> HORNS', 'FALL_2', NULL, NULL, 'Bus Stop', 'main', 'newer_vgm', 13),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX (Music Jingles)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 1 -> ORGANS', 'RILI_3', NULL, NULL, 'Seeker', 'main', 'newer_vgm', 14),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX (Music Jingles)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 1 -> SAX', 'SAX_02', NULL, NULL, 'Painter', 'main', 'newer_vgm', 15),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX (Music Jingles)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 1 -> SAX', 'SAX_17', NULL, NULL, 'Antlion', 'main', 'newer_vgm', 16),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX (Music Jingles)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 1 -> SYNTHS', 'DS1_4', NULL, NULL, 'Candle', 'main', 'newer_vgm', 17),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX (Music Jingles)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 1 -> SYNTHS', 'DS1_13', NULL, NULL, 'Scorpion', 'main', 'newer_vgm', 18),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX (Music Jingles)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 1 -> SYNTHS', 'DS1_17', NULL, NULL, 'Do Not Attempt To Recreate', 'main', 'newer_vgm', 19),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX (Music Jingles)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 1 -> SYNTHS', 'DS1_19', NULL, NULL, 'Final Battle', 'main', 'newer_vgm', 20),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX (Music Jingles)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 1 -> SYNTHS', 'DS2_25', NULL, NULL, 'Drive', 'main', 'newer_vgm', 21),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX (Music Jingles)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 2 -> CHOIRS', 'CLUST_2', NULL, NULL, 'Nightmare 03', 'main', 'newer_vgm', 22),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX (Music Jingles)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 2 -> CHOIRS', 'FALL5', NULL, NULL, 'Nightmare 03', 'main', 'newer_vgm', 23),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX (Music Jingles)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 2 -> CHOIRS', 'OOAH', NULL, NULL, 'Nightmare 02', 'main', 'newer_vgm', 24),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX (Music Jingles)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 2 -> FEMALE', 'NUS2_1', NULL, NULL, 'Nightmare 01', 'main', 'newer_vgm', 25),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX (Music Jingles)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 2 -> FEMALE', 'NUS2_4', NULL, NULL, 'Nightmare 02', 'main', 'newer_vgm', 26),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX (Music Jingles)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Chronic Horns' COLLATE NOCASE),
   'CD 1 -> Track 08 - Section & Solo Riffs -> TS 0:00', 'Section Riffs E min 1', '09.01 RIFF', NULL, 'Sign', 'main', 'newer_vgm', 27),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX (Music Jingles)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Chronic Horns' COLLATE NOCASE),
   'CD 1 -> Track 08 - Section & Solo Riffs -> TS 0:25', 'Section Riffs E min 9', '09.09 RIFF', NULL, 'Sign', 'main', 'newer_vgm', 28),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX (Music Jingles)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Ueberschall' COLLATE NOCASE AND p.name = 'Brazil Electro' COLLATE NOCASE),
   'CUTS', 'braz-#610', NULL, NULL, 'SFX (Candle)', 'main', 'newer_vgm', 29),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX (Music Jingles)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Ueberschall' COLLATE NOCASE AND p.name = 'Brazil Electro' COLLATE NOCASE),
   'CUTS', 'cowb+taiko-#614', NULL, NULL, 'Monocycle', 'main', 'newer_vgm', 30),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX (Music Jingles)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Ueberschall' COLLATE NOCASE AND p.name = 'Brazil Electro' COLLATE NOCASE),
   'CUTS', 'flute-#618', NULL, NULL, 'Clean Up', 'main', 'newer_vgm', 31),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX (Music Jingles)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Ueberschall' COLLATE NOCASE AND p.name = 'Brazil Electro' COLLATE NOCASE),
   'HORNSAMPLES', 'brasil hit 2-#657', 'Lowered 2 semitones', NULL, 'Antlion', 'main', 'newer_vgm', 32),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX (Music Jingles)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Ueberschall' COLLATE NOCASE AND p.name = 'Brazil Electro' COLLATE NOCASE),
   'HORNSAMPLES', 'cuba 4-#662', NULL, NULL, 'Yacht', 'main', 'newer_vgm', 33),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX (Music Jingles)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Ueberschall' COLLATE NOCASE AND p.name = 'Brazil Electro' COLLATE NOCASE),
   'HORNSAMPLES', 'jazz 3-#684', NULL, NULL, 'Steal', 'main', 'newer_vgm', 34),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX (Music Jingles)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 2' COLLATE NOCASE),
   'Track 04 - Breakbeat Live -> TS 0:43', '2 Bars', NULL, NULL, 'Microphone', 'main', 'newer_vgm', 35),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX (Music Jingles)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Ethnic' COLLATE NOCASE),
   'Track 50 - BREAKBEAT FILLS -> TS 0:00', 'Breakbeat Fill 1', NULL, NULL, 'Last Battle', 'main', 'newer_vgm', 36),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX (Music Jingles)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Ethnic' COLLATE NOCASE),
   'Track 60 - EASTERN -> TS 0:00', 'Chinese Buffalo Horn Key of F', NULL, NULL, 'Bonfire', 'main', 'newer_vgm', 37),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX (Music Jingles)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Ethnic' COLLATE NOCASE),
   'Track 71 - BRASS -> TS 0:13', 'Stab:', NULL, NULL, 'Cart', 'main', 'newer_vgm', 38),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX (Music Jingles)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Ethnic' COLLATE NOCASE),
   'Track 82 - MISCELLANEOUS -> TS 0:05', 'Bongo, Handclaps 4 bars', NULL, NULL, 'Cart', 'main', 'newer_vgm', 39),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX (Music Jingles)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Ethnic' COLLATE NOCASE),
   'Track 84 - ONE HIT SAMPLES -> TS 0:00', 'Japanese Cymbal 1', NULL, NULL, 'Final Battle', 'main', 'newer_vgm', 40),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX (Music Jingles)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Ethnic 2' COLLATE NOCASE),
   'Track 65 - MIDDLE EASTERN SECTION -> TS 0:00', 'Rhythm: Drums / bells 4 bars 117 bpm', NULL, NULL, 'Plants', 'main', 'newer_vgm', 41),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX (Music Jingles)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Ethnic 2' COLLATE NOCASE),
   'Track 70 - MIDDLE EASTERN SECTION -> TS 0:00', 'Zither arpeggio', NULL, NULL, 'Plants', 'main', 'newer_vgm', 42),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX (Music Jingles)'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Ethnic 2' COLLATE NOCASE),
   'Track 71 - MIDDLE EASTERN SECTION -> TS 0:00', 'Solo flute  1', NULL, NULL, 'Hands', 'main', 'newer_vgm', 43),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX (Music Jingles)'),
   NULL, NULL, NULL, 'Choir Pad', NULL, 'Do Not Attempt To Recreate', 'stuff_to_find', 'newer_vgm', 44),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX (Music Jingles)'),
   NULL, NULL, NULL, 'Vintage Marching Snares', NULL, 'Parachute', 'stuff_to_find', 'newer_vgm', 45),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX (Music Jingles)'),
   NULL, NULL, NULL, 'Guitar Phrase', NULL, 'Monocycle', 'stuff_to_find', 'newer_vgm', 46),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX (Music Jingles)'),
   NULL, NULL, NULL, 'Brass Hit', NULL, 'Kimi Shine Jingle 1 (Break Time 01)', 'stuff_to_find', 'newer_vgm', 47),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX (Music Jingles)'),
   NULL, NULL, NULL, 'Backing', NULL, 'Snake', 'stuff_to_find', 'newer_vgm', 48),
  ((SELECT id FROM games WHERE title = 'Feel the Magic: XY/XX (Music Jingles)'),
   NULL, NULL, NULL, 'Harp Gliss', NULL, 'Magic Touch', 'stuff_to_find', 'newer_vgm', 49);

-- G4-G18: Rub Rabbits through Metaphor: ReFantazio
INSERT INTO usages
  (game_id, product_id, path_bank, preset, notes, raw_source, examples, category, source_family, position)
VALUES
  -- G4: The Rub Rabbits! — 15 main + 9 stuff = 24
  ((SELECT id FROM games WHERE title = 'The Rub Rabbits!'),
   NULL, NULL, 'Timestamp 1:46', 'Brass Ending', 'Sample: Earl Palmer - Hey, Let''s Twist', 'Where Do Babies Come From? ~Akadoko Hell Mix~', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'The Rub Rabbits!'),
   NULL, NULL, 'Timestamp 0:00', 'Drum Fill', 'Sample: The Ventures - Go-Go Slow', 'Where Do Babies Come From? ~Akadoko Hell Mix~', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'The Rub Rabbits!'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'IK Multimedia' COLLATE NOCASE AND p.name = 'SampleTank 2 XL' COLLATE NOCASE),
   'Bass', 'Double Bass', NULL, NULL, '[Rose], [Hitohada]', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'The Rub Rabbits!'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'IK Multimedia' COLLATE NOCASE AND p.name = 'SampleTank 2 XL' COLLATE NOCASE),
   'Ethnic', 'Whistle', NULL, NULL, 'Akadoko Theme of Peace', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'The Rub Rabbits!'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'IK Multimedia' COLLATE NOCASE AND p.name = 'SampleTank 2 XL' COLLATE NOCASE),
   'Drums -> Acoustic', 'Very Old', NULL, NULL, 'Akadoko Op', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'The Rub Rabbits!'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'IK Multimedia' COLLATE NOCASE AND p.name = 'SampleTank 2 XL' COLLATE NOCASE),
   'Guitar -> Electric', 'Electro Strato', NULL, NULL, NULL, 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'The Rub Rabbits!'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'IK Multimedia' COLLATE NOCASE AND p.name = 'SampleTank 2 XL' COLLATE NOCASE),
   'Guitar -> Electric', 'Fuzz LP', NULL, NULL, 'Akadoko Boss 2, Fate [Akadoko Mix]', 'main', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'The Rub Rabbits!'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'IK Multimedia' COLLATE NOCASE AND p.name = 'SampleTank 2 XL' COLLATE NOCASE),
   'Orchestra', 'Glockenspiel', NULL, NULL, 'Akadoko Staff Roll', 'main', 'newer_vgm', 8),
  ((SELECT id FROM games WHERE title = 'The Rub Rabbits!'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'IK Multimedia' COLLATE NOCASE AND p.name = 'SampleTank 2 XL' COLLATE NOCASE),
   'Orchestra', 'Harp', NULL, NULL, 'SEQ_TITLE00', 'main', 'newer_vgm', 9),
  ((SELECT id FROM games WHERE title = 'The Rub Rabbits!'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'IK Multimedia' COLLATE NOCASE AND p.name = 'SampleTank 2 XL' COLLATE NOCASE),
   'Orchestra', 'Harpsichord', NULL, NULL, 'Akadoko Staff Roll', 'main', 'newer_vgm', 10),
  ((SELECT id FROM games WHERE title = 'The Rub Rabbits!'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'IK Multimedia' COLLATE NOCASE AND p.name = 'SampleTank 2 XL' COLLATE NOCASE),
   'Organ', '60s Amp Organ', NULL, NULL, 'Childhood Friend''s Theme, Fate [Akadoko Mix]', 'main', 'newer_vgm', 11),
  ((SELECT id FROM games WHERE title = 'The Rub Rabbits!'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'IK Multimedia' COLLATE NOCASE AND p.name = 'SampleTank 2 XL' COLLATE NOCASE),
   'Organ', 'B-3 Organ 1', NULL, NULL, 'SEQ_TITLE00', 'main', 'newer_vgm', 12),
  ((SELECT id FROM games WHERE title = 'The Rub Rabbits!'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'IK Multimedia' COLLATE NOCASE AND p.name = 'SampleTank 2 XL' COLLATE NOCASE),
   'Voices', 'Soprano Ahs lite', NULL, NULL, 'Akadoko Op', 'main', 'newer_vgm', 13),
  ((SELECT id FROM games WHERE title = 'The Rub Rabbits!'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sound Ideas' COLLATE NOCASE AND p.name = 'Hanna-Barbera Sound FX Library' COLLATE NOCASE),
   'HB03-16-01', 'ELECTRONIC', 'ELECTRONIC MAGIC', NULL, 'Akadoko Op', 'main', 'newer_vgm', 14),
  ((SELECT id FROM games WHERE title = 'The Rub Rabbits!'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Datafile 2' COLLATE NOCASE),
   'Track 04 - Breakbeat Live -> TS 0:43', '2 Bars', NULL, NULL, 'Rubit2005 (Conflict)', 'main', 'newer_vgm', 15),
  ((SELECT id FROM games WHERE title = 'The Rub Rabbits!'),
   NULL, NULL, NULL, 'Crash Cymbal', 'Roland - ? (SOUND Canvas SC-88 Pro or JV-2080)', NULL, 'stuff_to_find', 'newer_vgm', 16),
  ((SELECT id FROM games WHERE title = 'The Rub Rabbits!'),
   NULL, NULL, NULL, 'Weird Percussion Loop', NULL, 'Where Do Babies Come From?', 'stuff_to_find', 'newer_vgm', 17),
  ((SELECT id FROM games WHERE title = 'The Rub Rabbits!'),
   NULL, NULL, NULL, 'Bass', NULL, NULL, 'stuff_to_find', 'newer_vgm', 18),
  ((SELECT id FROM games WHERE title = 'The Rub Rabbits!'),
   NULL, NULL, NULL, '60''s Drum Fill', NULL, NULL, 'stuff_to_find', 'newer_vgm', 19),
  ((SELECT id FROM games WHERE title = 'The Rub Rabbits!'),
   NULL, NULL, NULL, 'Bass Drum', NULL, NULL, 'stuff_to_find', 'newer_vgm', 20),
  ((SELECT id FROM games WHERE title = 'The Rub Rabbits!'),
   NULL, NULL, NULL, 'Bossa Nova Drum Loop', NULL, NULL, 'stuff_to_find', 'newer_vgm', 21),
  ((SELECT id FROM games WHERE title = 'The Rub Rabbits!'),
   NULL, NULL, NULL, 'Syn. Organ', NULL, NULL, 'stuff_to_find', 'newer_vgm', 22),
  ((SELECT id FROM games WHERE title = 'The Rub Rabbits!'),
   NULL, NULL, NULL, 'Slide Guitar, Vintage Broken Guitar', NULL, NULL, 'stuff_to_find', 'newer_vgm', 23),
  ((SELECT id FROM games WHERE title = 'The Rub Rabbits!'),
   NULL, NULL, NULL, 'High Pass Elec. Percussion Loop', NULL, NULL, 'stuff_to_find', 'newer_vgm', 24),

  -- G5: Stuart Little 3 — 5 main
  ((SELECT id FROM games WHERE title = 'Stuart Little 3: Big Photo Adventure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG & Hit Music' COLLATE NOCASE AND p.name = 'Norman Cook - Skip to my Loops' COLLATE NOCASE),
   'REGGAE', '194_COOK', NULL, NULL, 'The Garden', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Stuart Little 3: Big Photo Adventure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG & Hit Music' COLLATE NOCASE AND p.name = 'Norman Cook - Skip to my Loops' COLLATE NOCASE),
   'SFX', '137_COOK', NULL, NULL, 'The Garden', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Stuart Little 3: Big Photo Adventure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG & Hit Music' COLLATE NOCASE AND p.name = 'Norman Cook - Skip to my Loops' COLLATE NOCASE),
   'SFX', '212_COOK', NULL, NULL, 'The Garden', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Stuart Little 3: Big Photo Adventure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG & Hit Music' COLLATE NOCASE AND p.name = 'Norman Cook - Skip to my Loops' COLLATE NOCASE),
   'FX_LOOPS', '216_COOK', NULL, NULL, 'The Garden', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Stuart Little 3: Big Photo Adventure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG & Hit Music' COLLATE NOCASE AND p.name = 'Norman Cook - Skip to my Loops' COLLATE NOCASE),
   'FLUTE', '262_COOK', NULL, NULL, 'The Garden', 'main', 'newer_vgm', 5),

  -- G6: Luminous Arc — 5 main
  ((SELECT id FROM games WHERE title = 'Luminous Arc'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'Perc -> Metals', 'Orch chimes', NULL, NULL, 'Awoken Priest, Attack', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Luminous Arc'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Native Instruments' COLLATE NOCASE AND p.name = 'Kontakt Factory Library' COLLATE NOCASE),
   'Orchestral -> 3 - VSL Brass', 'Trumpet Ensemble', NULL, NULL, NULL, 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Luminous Arc'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Native Instruments' COLLATE NOCASE AND p.name = 'Kontakt Factory Library' COLLATE NOCASE),
   'Orchestral -> 4 - VSL Percussion', 'Marimba', NULL, NULL, 'Every Day sunny', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Luminous Arc'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves', '135-Hysteria Chemical a', NULL, NULL, 'Non-Stop Battle!! -Battle Medley-', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Luminous Arc'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'UVI' COLLATE NOCASE AND p.name = 'PlugSound Pro (01-Keyboards)' COLLATE NOCASE),
   '08-Mallets & co', 'Music Box', NULL, NULL, 'Teardrops', 'main', 'newer_vgm', 5),

  -- G7: Odin Sphere — 1 main + 2 stuff
  ((SELECT id FROM games WHERE title = 'Odin Sphere'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Percussive Adventures' COLLATE NOCASE),
   NULL, '075 Brazil', NULL, NULL, 'Battle in the Land of Fire', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Odin Sphere'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'Perc -> Metals', 'Crotales', NULL, NULL, 'The Attic Library', 'stuff_to_find', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Odin Sphere'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Roland' COLLATE NOCASE AND p.name = 'SR-JV80-02 Orchestral' COLLATE NOCASE),
   'XP-X', 'Harpsichord1', NULL, NULL, 'The Attic Library', 'stuff_to_find', 'newer_vgm', 3),

  -- G8: Luminous Arc 2 — 4 main
  ((SELECT id FROM games WHERE title = 'Luminous Arc 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   NULL, 'Orch chimes', NULL, NULL, 'Assault!!', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Luminous Arc 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   NULL, 'Solo Violin', NULL, NULL, 'Cherry Blossoms Falling in the Snow', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Luminous Arc 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Native Instruments' COLLATE NOCASE AND p.name = 'Kontakt Factory Library' COLLATE NOCASE),
   NULL, 'Flute', NULL, NULL, 'The Path Where the Wind Dances', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Luminous Arc 2'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Native Instruments' COLLATE NOCASE AND p.name = 'Kontakt Factory Library' COLLATE NOCASE),
   NULL, 'Trumpet Ensemble', NULL, NULL, 'The Path Where the Wind Dances, Challenging a Formidable Enemy', 'main', 'newer_vgm', 4),

  -- G9: Thunder Force VI — 1 main + 1 stuff
  ((SELECT id FROM games WHERE title = 'Thunder Force VI'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Altered States' COLLATE NOCASE),
   'FX -> Altered States -> Surreal', 'GRAVELBRAS', 'From Cuckooland Vol. 1 Unhinged', NULL, 'RUINED GREEN (STAGE01-B)', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Thunder Force VI'),
   NULL, NULL, NULL, 'Piccolo Snare', 'Roland - ?', 'ORN GAUNTLET (BOSS05-03)', 'stuff_to_find', 'newer_vgm', 2),

  -- G10: Blazer Drive — 11 main + 4 stuff = 15
  ((SELECT id FROM games WHERE title = 'Blazer Drive'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves -> 126-Transonica', '126-Transonica  Combo', NULL, NULL, 'Wing of the Earth', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Blazer Drive'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves -> 135-Horse Fury', '135-Horse Fury', NULL, NULL, 'Desktop Load', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Blazer Drive'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Ueberschall' COLLATE NOCASE AND p.name = 'Drum n Bass Fast Forward' COLLATE NOCASE),
   '02-04 step+stutter 176-e -> 03 drums', '_gro176stutter', NULL, NULL, 'MYSTICKER BATTLE NO.1', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Blazer Drive'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Vengeance Sound' COLLATE NOCASE AND p.name = 'Essential House Vol. 2' COLLATE NOCASE),
   'VEH2 Hard Kicks', 'VEH2 Hard Kicks - 001', NULL, NULL, 'Sky Meadows', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Blazer Drive'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Vengeance Sound' COLLATE NOCASE AND p.name = 'Essential House Vol. 2' COLLATE NOCASE),
   'VEH2 Houseloops 128BPM', 'VEH2 Houseloops - 008', NULL, NULL, 'Sky Meadows', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'Blazer Drive'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Vengeance Sound' COLLATE NOCASE AND p.name = 'Essential House Vol. 2' COLLATE NOCASE),
   'VEH2 Houseloops 128BPM', 'VEH2 Houseloops - 009', NULL, NULL, 'Sky Meadows', 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'Blazer Drive'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Vengeance Sound' COLLATE NOCASE AND p.name = 'Essential House Vol. 2' COLLATE NOCASE),
   'VEH2 Special Sounds', 'VEH2 Special Sounds - 05', NULL, NULL, 'Shibuya 003', 'main', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'Blazer Drive'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Vengeance Sound' COLLATE NOCASE AND p.name = 'Essential House Vol. 2' COLLATE NOCASE),
   'VEH2 Special Sounds', 'VEH2 Special Sounds - 06', NULL, NULL, 'Shibuya 003', 'main', 'newer_vgm', 8),
  ((SELECT id FROM games WHERE title = 'Blazer Drive'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Total Rex' COLLATE NOCASE),
   'House & Garage Construction -> Rhythm Loops (140-bpm)', 'Rhythm Loop-1 140', NULL, NULL, 'Mystery Creature Pettan', 'main', 'newer_vgm', 9),
  ((SELECT id FROM games WHERE title = 'Blazer Drive'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Total Rex' COLLATE NOCASE),
   'House & Garage Construction -> Rhythm Loops (140-bpm)', 'Rhythm Loop-2 140', NULL, NULL, 'Mystery Creature Pettan', 'main', 'newer_vgm', 10),
  ((SELECT id FROM games WHERE title = 'Blazer Drive'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Total Rex' COLLATE NOCASE),
   'Total Drum & Bass -> Drum Loops 160 4', 'Shark bay', NULL, NULL, 'NEXT Four Emperors', 'main', 'newer_vgm', 11),
  ((SELECT id FROM games WHERE title = 'Blazer Drive'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 3', NULL, NULL, NULL, 'Desktop Load', 'stuff_to_find', 'newer_vgm', 12),
  ((SELECT id FROM games WHERE title = 'Blazer Drive'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Chemical Beats' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, NULL, 'stuff_to_find', 'newer_vgm', 13),
  ((SELECT id FROM games WHERE title = 'Blazer Drive'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Cuckooland Vol. 3 Asylum' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, NULL, 'stuff_to_find', 'newer_vgm', 14),
  ((SELECT id FROM games WHERE title = 'Blazer Drive'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Total Rex' COLLATE NOCASE),
   'Total Funk -> ?', '?', 'Guitar Loop', NULL, 'MYSTICKER Storage', 'stuff_to_find', 'newer_vgm', 15),

  -- G11: Let's Tap — 16 main + 3 stuff = 19
  ((SELECT id FROM games WHERE title = 'Let''s Tap'),
   NULL, NULL, 'Timestamp 1:19', 'Drum Fill', 'Sample: Armando Trovajoli - Beat Trombone', '365 Children', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Let''s Tap'),
   NULL, NULL, 'Timestamp 2:11', 'String Rip', 'Sample: Marty Gold & His Orchestra - The Donkey Serenade', '365 Children', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Let''s Tap'),
   NULL, NULL, 'Timestamp 0:00', 'Piano Glissando', 'Sample: Xavier Cugat & His Orchestra - Danse Des Mirlitons', '365 Children', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Let''s Tap'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'Loops' COLLATE NOCASE),
   'Apple Loops for GarageBand', 'Club Dance Beat 001', NULL, NULL, 'I Got Rhythm (Tap Edition)', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Let''s Tap'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 3 -> VOX_A_C', 'CHECKIT2', NULL, NULL, 'Blue Hero', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'Let''s Tap'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 3 -> VOX_A_C', 'COMEON10', 'Raised 3 semitones', NULL, 'Jupiter (Extreme Tap Edition)', 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'Let''s Tap'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 3 -> VOX_J_R', 'PUH', NULL, NULL, '365 Children', 'main', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'Let''s Tap'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 3 -> VOX_S_Z', 'VIVA', NULL, NULL, 'Jupiter (Extreme Tap Edition), Blue Hero', 'main', 'newer_vgm', 8),
  ((SELECT id FROM games WHERE title = 'Let''s Tap'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 9 -> MIXED', 'FOREIGN3', NULL, NULL, '365 Children', 'main', 'newer_vgm', 9),
  ((SELECT id FROM games WHERE title = 'Let''s Tap'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'PrimeSounds' COLLATE NOCASE AND p.name = 'Methods of Mayhem II - Damage Control' COLLATE NOCASE),
   'Hypercussion -> Hypercussion 140', 'renoisloop_140_001', NULL, NULL, NULL, 'main', 'newer_vgm', 10),
  ((SELECT id FROM games WHERE title = 'Let''s Tap'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves -> 58-Motion Century', '58-Motion Vocal Slicer', 'Rearranged', NULL, 'Milky Way Rendezvous', 'main', 'newer_vgm', 11),
  ((SELECT id FROM games WHERE title = 'Let''s Tap'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'UltimateSoundBank' COLLATE NOCASE AND p.name = 'Soundscan Vol. 18 - Funky Vocals' COLLATE NOCASE),
   '11-RAP RAGA VOX', 'ROBOTRAP1', 'Rearranged', NULL, 'Jupiter (Extreme Tap Edition)', 'main', 'newer_vgm', 12),
  ((SELECT id FROM games WHERE title = 'Let''s Tap'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'UltimateSoundBank' COLLATE NOCASE AND p.name = 'Soundscan Vol. 18 - Funky Vocals' COLLATE NOCASE),
   '12-LINE CONSTRUCTION', 'BEFORE2', NULL, NULL, 'Blue Hero', 'main', 'newer_vgm', 13),
  ((SELECT id FROM games WHERE title = 'Let''s Tap'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'UltimateSoundBank' COLLATE NOCASE AND p.name = 'Soundscan Vol. 18 - Funky Vocals' COLLATE NOCASE),
   '12-LINE CONSTRUCTION', 'TUTUTO TEL', NULL, NULL, 'Blue Hero', 'main', 'newer_vgm', 14),
  ((SELECT id FROM games WHERE title = 'Let''s Tap'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'UltimateSoundBank' COLLATE NOCASE AND p.name = 'Soundscan Vol. 18 - Funky Vocals' COLLATE NOCASE),
   '31-COMPUTER VOX A', '12345678', NULL, NULL, 'Blue Hero', 'main', 'newer_vgm', 15),
  ((SELECT id FROM games WHERE title = 'Let''s Tap'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'UltimateSoundBank' COLLATE NOCASE AND p.name = 'Soundscan Vol. 18 - Funky Vocals' COLLATE NOCASE),
   '31-COMPUTER VOX A', 'DONT WANT', NULL, NULL, 'Blue Hero', 'main', 'newer_vgm', 16),
  ((SELECT id FROM games WHERE title = 'Let''s Tap'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'UltimateSoundBank' COLLATE NOCASE AND p.name = 'Soundscan Vol. 18 - Funky Vocals' COLLATE NOCASE),
   '37-FX DELIRIUM VOX A', 'ETHNOREV', NULL, NULL, 'Blue Hero', 'main', 'newer_vgm', 17),
  ((SELECT id FROM games WHERE title = 'Let''s Tap'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'UltimateSoundBank' COLLATE NOCASE AND p.name = 'Soundscan Vol. 18 - Funky Vocals' COLLATE NOCASE),
   NULL, NULL, 'Text to Speech Vocal', NULL, 'Jupiter (Extreme Tap Edition)', 'stuff_to_find', 'newer_vgm', 18),
  ((SELECT id FROM games WHERE title = 'Let''s Tap'),
   NULL, NULL, NULL, '"1, 2, 3, 4"', NULL, '365 Children', 'stuff_to_find', 'newer_vgm', 19),
  ((SELECT id FROM games WHERE title = 'Let''s Tap'),
   NULL, NULL, NULL, '"Blue Hero"', NULL, 'Blue Hero', 'stuff_to_find', 'newer_vgm', 20),

  -- G12: Shining Force Feather — 1 main + 6 stuff = 7
  ((SELECT id FROM games WHERE title = 'Shining Force Feather'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'XLN Audio' COLLATE NOCASE AND p.name = 'Addictive Drums' COLLATE NOCASE),
   'Kit', 'Startup', NULL, NULL, 'Reverberation of Victory, Decision, The Ship, Exploration', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Shining Force Feather'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AKAI' COLLATE NOCASE AND p.name = 'SG01v' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, NULL, 'stuff_to_find', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Shining Force Feather'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'Logic Pro' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, 'Training Place', 'stuff_to_find', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Shining Force Feather'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = '05R/W' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, 'Break Battle', 'stuff_to_find', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Shining Force Feather'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'KORG' COLLATE NOCASE AND p.name = 'WAVESTATION SR' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, NULL, 'stuff_to_find', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'Shining Force Feather'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'XLN Audio' COLLATE NOCASE AND p.name = 'Addictive Drums' COLLATE NOCASE),
   NULL, NULL, 'Compressed kit', NULL, 'Goblins', 'stuff_to_find', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'Shining Force Feather'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Yamaha' COLLATE NOCASE AND p.name = 'MU80' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, NULL, 'stuff_to_find', 'newer_vgm', 7),

  -- G13: Radiant Historia — 8 main
  ((SELECT id FROM games WHERE title = 'Radiant Historia'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Ethno World' COLLATE NOCASE),
   NULL, 'Sitar Gliss', NULL, NULL, 'Dreams Showed by a Cloud of Dust', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Radiant Historia'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'Perc -> CymGong', '20 Cymbal', NULL, NULL, NULL, 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Radiant Historia'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'Perc -> Metals', 'Orch chimes', NULL, NULL, NULL, 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Radiant Historia'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'Strings -> Harp -> 1 Long', 'Harp Pluck', NULL, NULL, 'Mechanical Kingdom', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Radiant Historia'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'Strings -> Solo Violin -> 1 Long', 'SVL Leg Vib', NULL, NULL, 'Rebellion', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'Radiant Historia'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Metamorphosis S.A.G.E. Xpander' COLLATE NOCASE),
   '050-059', '055-Mohave', NULL, NULL, 'To the Battlefield', 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'Radiant Historia'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, 'Blue Radiance', 'main', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'Radiant Historia'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, 'Mechanical Kingdom', 'main', 'newer_vgm', 8),

  -- G14: Dengeki Bunko: Fighting Climax — 7 main + 5 stuff = 12
  ((SELECT id FROM games WHERE title = 'Dengeki Bunko: Fighting Climax'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Big Fish Audio' COLLATE NOCASE AND p.name = 'Electric Ghetto' COLLATE NOCASE),
   'Disc 2 -> 16 180 Emin', 'drums01', NULL, NULL, 'Decision-Maker', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Dengeki Bunko: Fighting Climax'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Omnisphere' COLLATE NOCASE),
   'Synth Mono', 'Analog FM ModWheeling Lead', NULL, NULL, NULL, 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Dengeki Bunko: Fighting Climax'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Omnisphere' COLLATE NOCASE),
   'Synth Mono', 'Frantic Lead', NULL, NULL, 'Higher Higher', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Dengeki Bunko: Fighting Climax'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves -> 86-Outlaw', '86-Outlaw Drums', 'Custom Loop', NULL, 'Login:Next Dream', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Dengeki Bunko: Fighting Climax'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves -> 160-Find The Exit', '160-Find The Exit Combo', NULL, NULL, '深淵', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'Dengeki Bunko: Fighting Climax'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'SOUND MENUS - Cinematic', 'MENU - Ambient Metals', 'G5', NULL, '深淵, 碧の幻影', 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'Dengeki Bunko: Fighting Climax'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Toontrack' COLLATE NOCASE AND p.name = 'Superior Drummer 2' COLLATE NOCASE),
   'N.Y. - Avatar', 'Default Kit', NULL, NULL, '碧の幻影', 'main', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'Dengeki Bunko: Fighting Climax'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AIR Music Technology' COLLATE NOCASE AND p.name = 'Vacuum' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, NULL, 'stuff_to_find', 'newer_vgm', 8),
  ((SELECT id FROM games WHERE title = 'Dengeki Bunko: Fighting Climax'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AIR Music Technology' COLLATE NOCASE AND p.name = 'Xpand!2' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, NULL, 'stuff_to_find', 'newer_vgm', 9),
  ((SELECT id FROM games WHERE title = 'Dengeki Bunko: Fighting Climax'),
   NULL, NULL, NULL, NULL, 'Scarbee - ?', NULL, 'stuff_to_find', 'newer_vgm', 10),
  ((SELECT id FROM games WHERE title = 'Dengeki Bunko: Fighting Climax'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, 'Higher Higher', 'stuff_to_find', 'newer_vgm', 11),
  ((SELECT id FROM games WHERE title = 'Dengeki Bunko: Fighting Climax'),
   NULL, NULL, NULL, NULL, 'Vienna Symphonic Library - ?', '碧の幻影', 'stuff_to_find', 'newer_vgm', 12),

  -- G15: Stella Glow has zero usage rows (placeholder game record only)

  -- G16: Tokyo Mirage Sessions #FE — 2 main + 4 stuff = 6
  ((SELECT id FROM games WHERE title = 'Tokyo Mirage Sessions #FE'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Heavyocity' COLLATE NOCASE AND p.name = 'Damage' COLLATE NOCASE),
   NULL, 'LPS Mangled Pop Elements', NULL, NULL, '"b09_f_shibuya"', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Tokyo Mirage Sessions #FE'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves', '135-Squashed', 'Custom loop', NULL, 'Normal Battle', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Tokyo Mirage Sessions #FE'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, NULL, 'stuff_to_find', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Tokyo Mirage Sessions #FE'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Omnisphere' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, NULL, 'stuff_to_find', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Tokyo Mirage Sessions #FE'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Trilian' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, NULL, 'stuff_to_find', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'Tokyo Mirage Sessions #FE'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'XLN Audio' COLLATE NOCASE AND p.name = 'Addictive Drums' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, NULL, 'stuff_to_find', 'newer_vgm', 6),

  -- G17: Catherine: Full Body — 5 main + 2 stuff = 7
  ((SELECT id FROM games WHERE title = 'Catherine: Full Body'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG' COLLATE NOCASE AND p.name = 'Kick-Ass Brass!' COLLATE NOCASE),
   'KAB Trombone', 'Bone Express', NULL, NULL, 'It''s a Golden Show', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Catherine: Full Body'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG' COLLATE NOCASE AND p.name = 'Kick-Ass Brass!' COLLATE NOCASE),
   'KAB Trumpet', 'Trumpet Exp, Trumpet Ripss, Trumpet Full', NULL, NULL, 'It''s a Golden Show', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Catherine: Full Body'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'Classic Stylus -> 68-Grime', '68-Grime a', NULL, NULL, 'Good Morning New Day', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Catherine: Full Body'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'Classic Stylus -> 71-Gangois', '71-Gangois', NULL, NULL, 'Jouji Washington', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Catherine: Full Body'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'Classic Stylus -> 90-Nu Skool', '90-Nu Skool a', NULL, NULL, 'Lost', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'Catherine: Full Body'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'Classic Stylus -> 91-Tough Break', '91-Tough Break', 'custom loop', NULL, 'Also Sprach Brooks', 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'Catherine: Full Body'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'Classic Stylus -> 117-ProgHouse', '117-ProgHouse a', NULL, NULL, 'It''s a Golden Show', 'main', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'Catherine: Full Body'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Apple' COLLATE NOCASE AND p.name = 'Logic Pro' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, NULL, 'stuff_to_find', 'newer_vgm', 8),
  ((SELECT id FROM games WHERE title = 'Catherine: Full Body'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   NULL, NULL, 'finding track name brb', NULL, NULL, 'stuff_to_find', 'newer_vgm', 9),

  -- G18: Metaphor: ReFantazio — 7 main + 2 stuff = 9
  ((SELECT id FROM games WHERE title = 'Metaphor: ReFantazio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Audiobro' COLLATE NOCASE AND p.name = 'LA Scoring Strings 2' COLLATE NOCASE),
   'Staccato', 'Cellos B Staccato', NULL, NULL, 'Onward', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Metaphor: ReFantazio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Heavyocity' COLLATE NOCASE AND p.name = 'Damage' COLLATE NOCASE),
   '01 Rhythmic Suites -> Loop Menus', 'LPS Epic Organic Elements 02', 'A#3, D#5', NULL, 'Skyrunner Charadrius', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Metaphor: ReFantazio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Heavyocity' COLLATE NOCASE AND p.name = 'Damage' COLLATE NOCASE),
   '02 Percussive Kits -> 05 Damage Kits', 'PERC Big Organo Kit', NULL, NULL, 'Transformation', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Metaphor: ReFantazio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Native Instruments' COLLATE NOCASE AND p.name = 'The Grandeur' COLLATE NOCASE),
   NULL, 'The Grandeur', 'adjustments needed', NULL, 'Lament', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Metaphor: ReFantazio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spitfire Audio' COLLATE NOCASE AND p.name = 'Hans Zimmer Percussion' COLLATE NOCASE),
   '_Presets_', 'Paper Djuns', NULL, NULL, 'Port Brilehaven -Night-', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'Metaphor: ReFantazio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spitfire Audio' COLLATE NOCASE AND p.name = 'Hans Zimmer Percussion' COLLATE NOCASE),
   '_Presets_', 'Snare', NULL, NULL, 'Brimming Determination', 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'Metaphor: ReFantazio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spitfire Audio' COLLATE NOCASE AND p.name = 'Hans Zimmer Percussion' COLLATE NOCASE),
   '_Presets_', 'Taikos', NULL, NULL, 'Port Brilehaven -Night-', 'main', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'Metaphor: ReFantazio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Heavyocity' COLLATE NOCASE AND p.name = 'Damage' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, 'Belly of the Beast, Seeking the Curse, Priestess of the Temple', 'stuff_to_find', 'newer_vgm', 8),
  ((SELECT id FROM games WHERE title = 'Metaphor: ReFantazio'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spitfire Audio' COLLATE NOCASE AND p.name = 'Hans Zimmer Percussion' COLLATE NOCASE),
   NULL, NULL, NULL, NULL, NULL, 'stuff_to_find', 'newer_vgm', 9);
