-- NEWER VGM SEGA/Atlus — Section 17 (Rhythm Thief) — FINAL SEGA/Atlus section
--
-- Source: reference/NEWER VGM Sound Sources - SEGAAtlus.csv lines 2548-2803.
-- 2 game records, ~250 usage rows.
--
-- This is the final SEGA/Atlus section. After this batch the entire
-- "NEWER VGM SEGA/Atlus" 3609-line CSV is fully ingested.
--
-- Games:
--   - Rhythm Thief & the Emperor's Treasure (3DS, 2012-01-19)
--     67 Sample: cross-media references + 67 instrument/library rows
--     + 22 stuff_to_find = ~195 rows. Largest single-game Sample list
--     in the project after Billy Hatcher.
--   - Rhythm Thief & the Paris Caper (iOS, 2013-10-30)
--     14 Sample: + 31 instrument/library + 10 stuff_to_find = ~55 rows.
--
-- Neither game has an in-CSV composer credit (line 2550 and 2747 lack
-- "(Music by:" notes); composers left NULL.
--
-- New manufacturer this batch:
--   - NemeSys (Larry Seyer's Upright Acoustic Bass — used in
--     three Rhythm Thief tracks)
--
-- New products this batch (selection — INSERT OR IGNORE on all):
--   - AMG / 160dB - The Drum&Bass Interface
--   - Big Fish Audio / Nu Jazz City 2
--   - Big Fish Audio / Acid Jazz City
--   - MOTU / Universal Loops & Instruments
--   - NemeSys / Larry Seyer's Upright Acoustic Bass
--   - Spectrasonics / Bonus Spectrasonics S.A.G.E. Xpander
--   - Spectrasonics / Burning Grooves S.A.G.E. Xpander
--   - Spectrasonics / Distorted Reality 2
--   - Spectrasonics / Retro Funk S.A.G.E. Xpander
--   - Zero-G / Brutal Beats
--   - Zero-G / EZ Rollers Drum & Bass Producer Pack
--   - Vengeance Sound / Vengeance Essential House Vol. 2
--     (CSV row 2719 uses "Vengeance Essential House Vol. 2" — kept
--     distinct from existing "Essential House Vol. 2" per Rule 2)
--
-- Verbatim preservations (Rule 2):
--   - "Plugsound" lowercase 's' (CSV rows 2715-2718) collates equal to
--     existing "PlugSound" via NOCASE — same product, no duplicate.
--   - Track name "Polestar Magnetics ... 4,3,2,1, Zero" (T2644) has
--     an em-dash–like full-width character separator (1―2―3―4 at T2642)
--     preserved verbatim.
--   - Spectrasonics "Distorted Reality 2" is a fresh product name; not
--     to be merged with the existing "Distorted Reality" or with the
--     "Spectrasonics / Metamorphosis S.A.G.E. Xpander" family.

INSERT OR IGNORE INTO manufacturers (name) VALUES
  ('NemeSys');

INSERT OR IGNORE INTO products (manufacturer_id, name, type) VALUES
  ((SELECT id FROM manufacturers WHERE name = 'AMG'                          COLLATE NOCASE), '160dB - The Drum&Bass Interface',                 'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Big Fish Audio'               COLLATE NOCASE), 'Nu Jazz City 2',                                  'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Big Fish Audio'               COLLATE NOCASE), 'Acid Jazz City',                                  'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'MOTU'                         COLLATE NOCASE), 'Universal Loops & Instruments',                   'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'NemeSys'                      COLLATE NOCASE), 'Larry Seyer''s Upright Acoustic Bass',            'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Spectrasonics'                COLLATE NOCASE), 'Bonus Spectrasonics S.A.G.E. Xpander',            'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Spectrasonics'                COLLATE NOCASE), 'Burning Grooves S.A.G.E. Xpander',                'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Spectrasonics'                COLLATE NOCASE), 'Distorted Reality 2',                             'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Spectrasonics'                COLLATE NOCASE), 'Retro Funk S.A.G.E. Xpander',                     'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Zero-G'                       COLLATE NOCASE), 'Brutal Beats',                                    'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Zero-G'                       COLLATE NOCASE), 'EZ Rollers Drum & Bass Producer Pack',            'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'Vengeance Sound'              COLLATE NOCASE), 'Vengeance Essential House Vol. 2',                'Sample Library'),
  ((SELECT id FROM manufacturers WHERE name = 'UVI'                          COLLATE NOCASE), 'Plugsound Pro (03-Drums and Percs)',              'Instrument');

INSERT INTO games (title, platform, released, composers, composers_normalized, notes) VALUES
  ('Rhythm Thief & the Emperor''s Treasure', 'Nintendo 3DS', '2012-01-19', NULL, NULL, 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 17 Rhythm Thief). 3DS original. Heavy cross-media sampling — 53 Sample: rows referencing 1960s-70s easy listening, bossa nova, and library music tracks. Spectrasonics Stylus RMX dominates the instrument-library rows (~34 of ~120).'),
  ('Rhythm Thief & the Paris Caper',         'iOS',          '2013-10-30', NULL, NULL, 'Source: NEWER VGM Sound Sources - SEGAAtlus.csv (Section 17 Rhythm Thief). Mobile sequel; reuses many of the same sample libraries as the 3DS original. CSV row 2761 "Phantom Fondue - Remix" indicates new arrange-mix tracks not present in the original.');

-- G1: Rhythm Thief & the Emperor's Treasure — 53 Sample: rows (positions 1-53)
INSERT INTO usages
  (game_id, product_id, path_bank, preset, notes, raw_source, examples, category, source_family, position)
VALUES
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, 'Timestamp 0:00', 'Conga Loop', 'Sample: Afrique - Slow Motion', 'Enter The Waiter', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, 'Timestamp 0:00', 'Conga Loop', 'Sample: Alan Parker - Solid Satin', 'IT''S DOG SHOW TIME', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, 'Timestamp 0:39', 'Brass Phrase', 'Sample: Berto Pisano - Kill Them All', 'Vergier vs. The Chevaliers', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, 'Timestamp 2:37', 'Brass Phrase', 'Sample: Betty White - Man''s Basic Step', 'Bone Appétit', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, 'Timestamp 1:34', 'Drum Loop', 'Sample: Cozy Cole And Gary Chester - Sing, Sing, Sing (With A Swing)', 'Phantom Fondue', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, 'Timestamp 0:00', 'Bongos', 'Sample: Derek And Ray - St. Thomas', 'Le Getaway', 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, 'Timestamp 0:58', 'Brass Fall', 'Sample: Dick Schory - Shim-Wha', 'Looting the Louvre', 'main', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, 'Timestamp 0:00', 'Agogo', 'Sample: Djalma Ferreira - Soul Limbo', 'Bone Appétit', 'main', 'newer_vgm', 8),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, 'Timestamp 0:00', 'Conga Roll', 'Sample: Eddie Cano And His Sextet - Deep In A Drum', 'Looting the Louvre', 'main', 'newer_vgm', 9),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, 'Timestamp 0:00', 'Drum Loop', 'Sample: Electric Light Orchestra - Don''t Bring Me Down', 'Battle Diabolique, Destroyer Diabolique, Chevalier Showdown', 'main', 'newer_vgm', 10),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, 'Timestamp 0:00, 1:03', 'Brass', 'Sample: Elmer Bernstein - Main Title from "The Silencers"', 'Looting the Louvre', 'main', 'newer_vgm', 11),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, 'Timestamp 1:28, 1:35', 'Brass', 'Sample: Esquivel - Johnson Rag', 'IT''S DOG SHOW TIME', 'main', 'newer_vgm', 12),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, 'Timestamp 0:08', 'Drums', 'Sample: Françoise Hardy - Comment Te Dire Adieu', 'Bone Appétit', 'main', 'newer_vgm', 13),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, 'Timestamp 1:32', 'String Rip', 'Sample: Françoise Hardy - Dame Souris Trotte', 'Hurry Up and Wait, IT''S DOG SHOW TIME', 'main', 'newer_vgm', 14),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, 'Timestamp 0:24', 'Drum Fill', 'Sample: Hugo Montenegro - Wild Bike', 'Looting the Louvre', 'main', 'newer_vgm', 15),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, 'Timestamp 0:00', 'Woodblocks', 'Sample: Henry Mancini - Charade (Main Title)', 'Phantom From the Opera', 'main', 'newer_vgm', 16),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, 'Timestamp 0:00', 'Drum Loop', 'Sample: Incredible Bongo Band - Apache', 'The Faux Phantom R (Option Remix)', 'main', 'newer_vgm', 17),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, 'Timestamp 0:00', 'Drum Loop', 'Sample: Jack Marshall - The River Kwai March', 'Bone Appétit', 'main', 'newer_vgm', 18),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, 'Timestamp 0:03', 'Hi-Hats', 'Sample: Johnny Pate - Auto Chase', 'Le Getaway', 'main', 'newer_vgm', 19),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, 'Timestamp 0:00', 'Conga Intro', 'Sample: Johnny Pate - Shaft in Africa (Addis)', 'The True Chevaliers', 'main', 'newer_vgm', 20),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, 'Timestamp 0:00', 'Guiro', 'Sample: Keith Mansfield - The Mexican D.J.', 'Bone Appétit', 'main', 'newer_vgm', 21),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, 'Timestamp 0:00', 'Brass', 'Sample: Ken Woodman - Town Talk', 'Battle Diabolique', 'main', 'newer_vgm', 22),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, 'Timestamp 1:12', 'Percussion Loop', 'Sample: Kongas - Kongas Fun (A Tom Moulton Mix)', 'Bone Appétit', 'main', 'newer_vgm', 23),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, 'Timestamp 0:03', 'Drum Loop', 'Sample: Lalo Schifrin - Lalo''s Bossa Nova', 'Rhythm Kitchen', 'main', 'newer_vgm', 24),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, 'Timestamp 0:02, 0:07', 'Multiple Elements', 'Sample: Lennie Dale - O Pato', 'Hurry Up and Wait, Restaurant Test', 'main', 'newer_vgm', 25),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, 'Timestamp 0:00', 'Piano Phrase', 'Sample: Lester Lanin - Cheek To Cheek (Fox Trot)', 'Bone Appétit', 'main', 'newer_vgm', 26),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, 'Timestamp 0:44', 'Drum Loop', 'Sample: Luis Bacalov - We Still Kill The Old Way', 'Rhythm Kitchen', 'main', 'newer_vgm', 27),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, 'Timestamp 0:07', 'String Fall', 'Sample: Manfred Minnich Strings - With Following Winds', 'Battle Diabolique, Napoleon''s Hideout', 'main', 'newer_vgm', 28),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, 'Timestamp 0:00, 0:03, 0:07, 0:10', 'Multiple Elements', 'Sample: Marty Gold & His Orchestra - The Donkey Serenade', 'IT''S DOG SHOW TIME', 'main', 'newer_vgm', 29),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, 'Timestamp 0:02', 'Brass Phrase', 'Sample: Nino Ferrer - Les Cornichons', 'Family Ties', 'main', 'newer_vgm', 30),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, 'Timestamp 0:00', 'Hit', 'Sample: Peppino De Luca & Marc 4 - L''Uomo Dagli Occhi Di Ghiaccio', 'Phantom From the Opera', 'main', 'newer_vgm', 31),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, 'Timestamp 0:00, 0:05, 0:06, 0:26', 'Brass Hits, Piano Phrase', 'Sample: René Touzet - Theme From The Brothers Grimm', 'Bone Appétit', 'main', 'newer_vgm', 32),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, 'Timestamp 0:16', 'Drum Loop', 'Sample: Roger Roger - Take Seven', 'Bone Appétit', 'main', 'newer_vgm', 33),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, 'Timestamp 0:00', 'Drum Loop', 'Sample: Ronnie Keaton - Going Down For The Last Time', 'Enter The Waiter', 'main', 'newer_vgm', 34),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, 'Timestamp 0:00', 'Tambourine Loop', 'Sample: Russ Garcia And His Orchestra - Delicado', 'IT''S DOG SHOW TIME', 'main', 'newer_vgm', 35),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, 'Timestamp 0:00', 'Conga Loop', 'Sample: Sabu Martinez - My Son Johnny And Me', 'The True Chevaliers', 'main', 'newer_vgm', 36),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, 'Timestamp 0:59', 'Organ Phrase', 'Sample: Sammy Kaye & His Orchestra - A Walk In The Black Forest', 'Bone Appétit', 'main', 'newer_vgm', 37),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, 'Timestamp 0:00', 'Shaker Loop', 'Sample: Serge Gainsbourg - Couleur Café', 'Rhythm Kitchen', 'main', 'newer_vgm', 38),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, 'Timestamp 0:00', 'Drum Fill', 'Sample: Sid Bass - Valencia ', 'Day in Paris', 'main', 'newer_vgm', 39),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, 'Timestamp 1:12', 'Drum Loop', 'Sample: Sounds Incorporated - William Tell', 'Phantom Fondue', 'main', 'newer_vgm', 40),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, 'Timestamp 0:00', 'Drum Fill', 'Sample: Sylvie Vartan - Ne T''en Vas Pas', 'Le Getaway', 'main', 'newer_vgm', 41),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, 'Timestamp 0:02', 'Vocal', 'Sample: The Cliff Davis Sextet - Twine Time', 'Bone Appétit', 'main', 'newer_vgm', 42),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, 'Timestamp 0:03, 0:13', 'Brass & Xylophone Hits', 'Sample: The Command All-Stars - All The Way', 'Hurry Up and Wait, Restaurant Test', 'main', 'newer_vgm', 43),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, 'Timestamp 0:00, 0:11, 0:15', 'Multiple Elements', 'Sample: The Command All-Stars - Perdido', 'Vergier vs. The Chevaliers', 'main', 'newer_vgm', 44),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, 'Timestamp 0:00', 'Brass Hit', 'Sample: The Fat Albert Orchestra - Cosbyianna', 'The True Chevaliers', 'main', 'newer_vgm', 45),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, 'Timestamp 0:04', 'Drum Loop', 'Sample: The Hollywood Persuaders - Drums A-Go-Go', 'Le Getaway', 'main', 'newer_vgm', 46),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, 'Timestamp 2:22', 'Drums', 'Sample: The Jimi Entley Sound - Apache', 'Family Ties', 'main', 'newer_vgm', 47),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, 'Timestamp 4:10', 'Drum Loop', 'Sample: The Karminsky Experience Inc. - Mah Nà Mah Nà (Karmexperience Mix)', 'Day in Paris', 'main', 'newer_vgm', 48),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, 'Timestamp 0:33', 'Drum Loop', 'Sample: The Trashmen - Surfin'' Bird', 'Le Getaway', 'main', 'newer_vgm', 49),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, 'Timestamp 0:00', 'Drum Fill', 'Sample: The Ventures - Go-Go Slow', '-Used throughout the soundtrack-', 'main', 'newer_vgm', 50),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, 'Timestamp 0:11', 'Drum Fill', 'Sample: Tommy McCook - Ska Jam', 'Le Getaway', 'main', 'newer_vgm', 51),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, 'Timestamp 0:00, 0:46', 'Drum Fill', 'Sample: Tommy Quickly - It''s As Simple As That', 'Bone Appétit, Battle Diabolique', 'main', 'newer_vgm', 52),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, 'Timestamp 0:00', 'Drum Fill', 'Sample: Wilbur Bascomb - Just A Groove In "G"', 'Enter The Waiter', 'main', 'newer_vgm', 53);

-- G1 continued: equipment/library rows (positions 54-173) — AMG → Spectrasonics
INSERT INTO usages
  (game_id, product_id, path_bank, preset, notes, raw_source, examples, category, source_family, position)
VALUES
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG' COLLATE NOCASE AND p.name = '160dB - The Drum&Bass Interface' COLLATE NOCASE),
   'Track 02 -> TS 1:02', 'BREAKS (Mono)', NULL, NULL, 'Shop Auban', 'main', 'newer_vgm', 54),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG' COLLATE NOCASE AND p.name = '160dB - The Drum&Bass Interface' COLLATE NOCASE),
   'Track 33 -> TS 0:00', 'GATED FX (Mono/Stereo)', NULL, NULL, 'Shop Auban', 'main', 'newer_vgm', 55),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG' COLLATE NOCASE AND p.name = '160dB - The Drum&Bass Interface' COLLATE NOCASE),
   'Track 33 -> TS 0:08', 'GATED FX (Mono/Stereo)', NULL, NULL, 'Shop Auban', 'main', 'newer_vgm', 56),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG' COLLATE NOCASE AND p.name = '160dB - The Drum&Bass Interface' COLLATE NOCASE),
   'Track 33 -> TS 0:23', 'GATED FX (Mono/Stereo)', NULL, NULL, 'Shop Auban', 'main', 'newer_vgm', 57),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG' COLLATE NOCASE AND p.name = '160dB - The Drum&Bass Interface' COLLATE NOCASE),
   'Track 46 -> TS 0:00', 'LIVE DRUMS', NULL, NULL, 'Record & Play Sounds', 'main', 'newer_vgm', 58),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG' COLLATE NOCASE AND p.name = '160dB - The Drum&Bass Interface' COLLATE NOCASE),
   'Track 47 -> TS 0:00', 'LIVE DRUMS', NULL, NULL, 'Time Limit', 'main', 'newer_vgm', 59),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG' COLLATE NOCASE AND p.name = '160dB - The Drum&Bass Interface' COLLATE NOCASE),
   'Track 47 -> TS 0:21', 'LIVE DRUMS', NULL, NULL, 'Time Limit', 'main', 'newer_vgm', 60),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG' COLLATE NOCASE AND p.name = '160dB - The Drum&Bass Interface' COLLATE NOCASE),
   'Track 48 -> TS 0:00', 'LIVE DRUMS', NULL, NULL, 'Record & Play Sounds', 'main', 'newer_vgm', 61),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG' COLLATE NOCASE AND p.name = '160dB - The Drum&Bass Interface' COLLATE NOCASE),
   'Track 56 -> TS 0:12', 'RHODES (Mono)', NULL, NULL, 'Time Limit', 'main', 'newer_vgm', 62),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG' COLLATE NOCASE AND p.name = '160dB - The Drum&Bass Interface' COLLATE NOCASE),
   'Track 56 -> TS 0:25', 'RHODES (Mono)', NULL, NULL, 'Time Limit', 'main', 'newer_vgm', 63),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG' COLLATE NOCASE AND p.name = '160dB - The Drum&Bass Interface' COLLATE NOCASE),
   'Track 57 -> TS 0:15', 'RHODES (Mono)', 'Added flanger/chorus', NULL, 'Record & Play Sounds', 'main', 'newer_vgm', 64),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG' COLLATE NOCASE AND p.name = '160dB - The Drum&Bass Interface' COLLATE NOCASE),
   'Track 57 -> TS 0:19', 'RHODES (Mono)', 'Chopped up & resequenced', NULL, 'Record & Play Sounds', 'main', 'newer_vgm', 65),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG' COLLATE NOCASE AND p.name = '160dB - The Drum&Bass Interface' COLLATE NOCASE),
   'Track 57 -> TS 0:21', 'RHODES (Mono)', 'Chopped up & resequenced', NULL, 'Record & Play Sounds', 'main', 'newer_vgm', 66),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG' COLLATE NOCASE AND p.name = '160dB - The Drum&Bass Interface' COLLATE NOCASE),
   'Track 57 -> TS 0:37', 'RHODES (Mono)', NULL, NULL, 'Time Limit, Record & Play Sounds', 'main', 'newer_vgm', 67),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG' COLLATE NOCASE AND p.name = '160dB - The Drum&Bass Interface' COLLATE NOCASE),
   'Track 58 -> TS 0:00', 'RHODES (Mono)', NULL, NULL, 'Time Limit', 'main', 'newer_vgm', 68),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG' COLLATE NOCASE AND p.name = '160dB - The Drum&Bass Interface' COLLATE NOCASE),
   'Track 61 -> TS 0:56', 'RHODES (Mono)', 'Stretched', NULL, 'Record & Play Sounds', 'main', 'newer_vgm', 69),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 1 -> DANCEVOX', 'FEMAL10', '"This is not a game"', NULL, 'SHOW TIME', 'main', 'newer_vgm', 70),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 1 -> DANCEVOX', 'FEMAL11', '"Searching for love"', NULL, 'SHOW TIME', 'main', 'newer_vgm', 71),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 3 -> VOX_A_C', 'ALLRIGH2', NULL, NULL, 'SHOW TIME', 'main', 'newer_vgm', 72),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 3 -> VOX_J_R', 'PUH', NULL, NULL, 'SHOW TIME', 'main', 'newer_vgm', 73),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Big Fish Audio' COLLATE NOCASE AND p.name = 'Nu Jazz City 2' COLLATE NOCASE),
   '08 140 A', '08 drum loop', NULL, NULL, 'The True Chevaliers', 'main', 'newer_vgm', 74),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Big Fish Audio' COLLATE NOCASE AND p.name = 'Nu Jazz City 2' COLLATE NOCASE),
   '15 120 A', '15 drums 04', NULL, NULL, 'The True Chevaliers', 'main', 'newer_vgm', 75),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Big Fish Audio' COLLATE NOCASE AND p.name = 'Nu Jazz City 2' COLLATE NOCASE),
   '15 120 A', '15 horns 03', NULL, NULL, 'The True Chevaliers', 'main', 'newer_vgm', 76),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Big Fish Audio' COLLATE NOCASE AND p.name = 'Nu Jazz City 2' COLLATE NOCASE),
   '20 125 E', '20 congas', NULL, NULL, 'Night in Paris, Main Menu', 'main', 'newer_vgm', 77),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Chronic Horns' COLLATE NOCASE),
   'CD 1 -> Track 04 - Section & Solo Riffs -> TS 0:25', 'Section Riffs C min 7', NULL, NULL, 'Puzzle Game', 'main', 'newer_vgm', 78),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'Brass -> 4 Trumpets -> 5 Keysw', '4TP KS Master', NULL, NULL, 'Escape from Notre Dame', 'main', 'newer_vgm', 79),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   'Perc -> Metals', 'Orch chimes', NULL, NULL, 'Throwdown with Napoleon', 'main', 'newer_vgm', 80),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'IK Multimedia' COLLATE NOCASE AND p.name = 'SampleTank 2 XL' COLLATE NOCASE),
   'Organ', 'Vox Cont Spring', 'Disable reverb', NULL, 'Throwdown with Alfred', 'main', 'newer_vgm', 81),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'IK Multimedia' COLLATE NOCASE AND p.name = 'SampleTron' COLLATE NOCASE),
   'Chamberlin M Series', 'Chamberlin Sax', NULL, NULL, 'Master Instruments', 'main', 'newer_vgm', 82),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'IK Multimedia' COLLATE NOCASE AND p.name = 'SampleTron' COLLATE NOCASE),
   'Chamberlin Music Masters', 'M4 Pizz CH', NULL, NULL, 'Hurry to the Eiffel Tower', 'main', 'newer_vgm', 83),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'IK Multimedia' COLLATE NOCASE AND p.name = 'SampleTron' COLLATE NOCASE),
   'Mellotron M400 and Mark V', 'MlTrn Flute', NULL, NULL, 'Phantom Notes', 'main', 'newer_vgm', 84),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'IK Multimedia' COLLATE NOCASE AND p.name = 'SampleTron' COLLATE NOCASE),
   'Talentmaker Loops -> Individual Loops TM', 'Talentmaker11', NULL, NULL, 'Master Instruments', 'main', 'newer_vgm', 85),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Masterbits' COLLATE NOCASE AND p.name = 'RAPsody' COLLATE NOCASE),
   'Track 27 - Heey Hoo AD -> TS 0:46', 'Come on, let go ...', '"Everybody feel a sound.."', NULL, 'SHOW TIME', 'main', 'newer_vgm', 86),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'MOTU' COLLATE NOCASE AND p.name = 'Universal Loops & Instruments' COLLATE NOCASE),
   '01 Piano & co -> Mallets', 'Vibraphone 1 or Vibraphone 2', NULL, NULL, 'Breaking In, Looting the Louvre, Night in Paris, Time Limit, Onward Through the Dark', 'main', 'newer_vgm', 87),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Native Instruments' COLLATE NOCASE AND p.name = 'Massive' COLLATE NOCASE),
   'Factory -> Bass', 'Industrious', NULL, NULL, 'Battle Diabolique, Napoleon''s Hideout', 'main', 'newer_vgm', 88),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Native Instruments' COLLATE NOCASE AND p.name = 'Massive' COLLATE NOCASE),
   'Factory -> Synth Lead', 'Big Lead', NULL, NULL, 'Battle Diabolique', 'main', 'newer_vgm', 89),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'NemeSys' COLLATE NOCASE AND p.name = 'Larry Seyer''s Upright Acoustic Bass' COLLATE NOCASE),
   NULL, '01 Optimal - Upright Bass', NULL, NULL, 'Sneaking and Entering, To the Manor Borne, Shall We Dance? (The Blue Danube)', 'main', 'newer_vgm', 90),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Polestar Magnetics' COLLATE NOCASE AND p.name = 'The X-Static Goldmine' COLLATE NOCASE),
   'CD 2 -> Track 05 - LET D BASS KICK -> TS 0:16', 'Lets Go 2', NULL, NULL, '-Used throughout the soundtrack-', 'main', 'newer_vgm', 91),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Polestar Magnetics' COLLATE NOCASE AND p.name = 'The X-Static Goldmine' COLLATE NOCASE),
   'CD 2 -> Track 06 - KICK OFF! -> TS 0:17', '1―2―3―4', NULL, NULL, 'SHOW TIME', 'main', 'newer_vgm', 92),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Polestar Magnetics' COLLATE NOCASE AND p.name = 'The X-Static Goldmine' COLLATE NOCASE),
   'CD 2 -> Track 06 - KICK OFF! -> TS 0:36', '...New Style', NULL, NULL, 'SHOW TIME', 'main', 'newer_vgm', 93),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Polestar Magnetics' COLLATE NOCASE AND p.name = 'The X-Static Goldmine' COLLATE NOCASE),
   'CD 2 -> Track 49 - RABOTNIK 1 -> TS 0:01', '4,3,2,1, Zero', NULL, NULL, 'Looting the Louvre, Vergier vs. The Chevaliers, Throwdown with Alfred', 'main', 'newer_vgm', 94),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sound Ideas' COLLATE NOCASE AND p.name = 'Hollywood Series 4000' COLLATE NOCASE),
   '4001-27-06', 'CARTOON, GONG', 'LARGE, CHINESE GONG, SOFT MALLET', NULL, 'Enter The Waiter', 'main', 'newer_vgm', 95);

-- G1 continued: Spectrasonics block (positions 96-152)
INSERT INTO usages
  (game_id, product_id, path_bank, preset, notes, raw_source, examples, category, source_family, position)
VALUES
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Bonus Spectrasonics S.A.G.E. Xpander' COLLATE NOCASE),
   'Vocal Planet Mouth Perc 066-079', '066-EH Reggae 1', NULL, NULL, 'Shop Auban', 'main', 'newer_vgm', 96),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Bonus Spectrasonics S.A.G.E. Xpander' COLLATE NOCASE),
   'Vocal Planet Mouth Perc 066-079', '083-Hi Lolo 2', NULL, NULL, 'Looting the Louvre', 'main', 'newer_vgm', 97),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Bonus Spectrasonics S.A.G.E. Xpander' COLLATE NOCASE),
   'Vocal Planet Mouth Perc 090-099', '099-Kukoo 1', NULL, NULL, 'Looting the Louvre Redux', 'main', 'newer_vgm', 98),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Bonus Spectrasonics S.A.G.E. Xpander' COLLATE NOCASE),
   'Vocal Planet Mouth Perc 090-099', '099-Kukoo 2', NULL, NULL, 'Looting the Louvre Redux', 'main', 'newer_vgm', 99),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Bonus Spectrasonics S.A.G.E. Xpander' COLLATE NOCASE),
   'Vocal Planet Mouth Perc 100-109', '100-Kukoo 8', NULL, NULL, 'Time Limit', 'main', 'newer_vgm', 100),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Bonus Spectrasonics S.A.G.E. Xpander' COLLATE NOCASE),
   'Vocal Planet Mouth Perc 116-119', '118-Boogabreath', NULL, NULL, 'Looting the Louvre Redux', 'main', 'newer_vgm', 101),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Bonus Spectrasonics S.A.G.E. Xpander' COLLATE NOCASE),
   'Vocal Planet Mouth Perc 120-234', '120-DoWa Chick', NULL, NULL, 'Record & Play Sounds', 'main', 'newer_vgm', 102),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Bonus Spectrasonics S.A.G.E. Xpander' COLLATE NOCASE),
   'Vocal Planet Mouth Perc 120-234', '121-Clavanos', NULL, NULL, 'To the Manor Borne', 'main', 'newer_vgm', 103),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Bonus Spectrasonics S.A.G.E. Xpander' COLLATE NOCASE),
   'Vocal Planet Mouth Perc 120-234', '122-Super Fill', NULL, NULL, 'Time Limit', 'main', 'newer_vgm', 104),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Burning Grooves S.A.G.E. Xpander' COLLATE NOCASE),
   '104-Chunky Monkey', '104-Chunky Monkey', NULL, NULL, 'Looting the Louvre Redux, To the Manor Borne', 'main', 'newer_vgm', 105),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Burning Grooves S.A.G.E. Xpander' COLLATE NOCASE),
   '136-Hyper', '136-Hyper Edge', NULL, NULL, 'Mastermind', 'main', 'newer_vgm', 106),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Burning Grooves S.A.G.E. Xpander' COLLATE NOCASE),
   '151-Street Dance', '151-Street Dance 1', NULL, NULL, 'Through the Hanging Gardens, Flight from the Gardens', 'main', 'newer_vgm', 107),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Distorted Reality 2' COLLATE NOCASE),
   'CD 1 -> Partition B -> 03 130-139', 'SWEEPSTEP130', NULL, NULL, 'Escape from Notre Dame', 'main', 'newer_vgm', 108),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Metamorphosis S.A.G.E. Xpander' COLLATE NOCASE),
   '130-139', '130-Race Ya', NULL, NULL, 'Onward Through the Dark', 'main', 'newer_vgm', 109),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Metamorphosis S.A.G.E. Xpander' COLLATE NOCASE),
   '140-149', '140-DB Police', NULL, NULL, 'Puzzle Game', 'main', 'newer_vgm', 110),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Omnisphere' COLLATE NOCASE),
   'Synth Bass', 'Vicious Moog', NULL, NULL, 'SHOW TIME', 'main', 'newer_vgm', 111),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Omnisphere' COLLATE NOCASE),
   'Synth Poly', 'Brainsalad Modular', NULL, NULL, 'Battle Diabolique, Destroyer Diabolique, Napoleon''s Hideout, Chevalier Showdown', 'main', 'newer_vgm', 112),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Retro Funk S.A.G.E. Xpander' COLLATE NOCASE),
   '082-Slinky', '082-Slinky Fill f', NULL, NULL, 'Puzzle Game', 'main', 'newer_vgm', 113),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Retro Funk S.A.G.E. Xpander' COLLATE NOCASE),
   '116-Tower', '116-Tower Fill a', NULL, NULL, 'Looting the Louvre', 'main', 'newer_vgm', 114),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Retro Funk S.A.G.E. Xpander' COLLATE NOCASE),
   '128-Got to Be', '128-Got to Be 1', NULL, NULL, 'Throwdown with Alfred', 'main', 'newer_vgm', 115),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'Classic Stylus -> 92-Genuine', '92-Genuine a', NULL, NULL, 'SHOW TIME', 'main', 'newer_vgm', 116),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'Classic Stylus -> 132-Bristolized', '132-Bristolized a', NULL, NULL, 'Puzzle Game', 'main', 'newer_vgm', 117),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'Classic Stylus -> Congas', '80-Congas 1 ', NULL, NULL, 'Throwdown with Alfred', 'main', 'newer_vgm', 118),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'Classic Stylus -> Congas', '100-Congas Bend', NULL, NULL, 'Day in Paris, Day in Paris Ver.2', 'main', 'newer_vgm', 119),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'Classic Stylus -> Congas', '107-Congas', NULL, NULL, 'SHOW TIME', 'main', 'newer_vgm', 120),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'Classic Stylus -> Congas', '118-Congas', NULL, NULL, 'Gone with the Wind', 'main', 'newer_vgm', 121),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'Classic Stylus -> Cowbells', '121-Cowbell', NULL, NULL, 'Looting the Louvre Redux, To the Manor Borne', 'main', 'newer_vgm', 122),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'Classic Stylus -> Cowbells', '123-Cowbell', NULL, NULL, 'Throwdown with Alfred', 'main', 'newer_vgm', 123),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'Classic Stylus -> Ride Cymbals', '67-Ride Cymbal', NULL, NULL, 'Hurry Up and Wait', 'main', 'newer_vgm', 124),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'Classic Stylus -> Triangle', '126-Triangle', NULL, NULL, 'Day in Paris, Day in Paris Ver.2, To the Manor Borne, Fête de Paris (Je te veux)', 'main', 'newer_vgm', 125),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'Groove Elements -> HiHats 1', '70-Hi-Hats', 'Time -> Pattern Modify -> Variation F', NULL, 'Puzzle Game', 'main', 'newer_vgm', 126),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves -> 60-Volcano', '60-Volcano Kabuki Wood', NULL, NULL, 'Day in Paris, Day in Paris Ver.2', 'main', 'newer_vgm', 127),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves -> 64-Plod', '64-Plod Kicks', NULL, NULL, 'Hurry Up and Wait', 'main', 'newer_vgm', 128),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves -> 68-Small Blocks', '68-Small Blocks Bending Bass', NULL, NULL, 'Puzzle Game', 'main', 'newer_vgm', 129),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves -> 68-Tower Zero', '68-Tower Zero Hi Hats', NULL, NULL, 'Looting the Louvre', 'main', 'newer_vgm', 130),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves -> 72-Liquid Frame', '72-Liquid Frame Drippings', NULL, NULL, 'Onward Through the Dark', 'main', 'newer_vgm', 131),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves -> 72-Liquid Frame', '72-Liquid Frame Orbital', NULL, NULL, 'Onward Through the Dark', 'main', 'newer_vgm', 132),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves -> 72-Liquid Frame', '72-Liquid Frame Ticks', NULL, NULL, 'Onward Through the Dark', 'main', 'newer_vgm', 133),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves -> 79-Bossa Love', '79-BossaLuv  Combo a', NULL, NULL, 'Day in Paris, Day in Paris Ver.2', 'main', 'newer_vgm', 134),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves -> 79-Bossa Love', '79-BossaLuv Hi-Hat', NULL, NULL, 'Onward Through the Dark', 'main', 'newer_vgm', 135),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves -> 80-Space Ranger', '80-Space Ranger HiHat Bend', NULL, NULL, 'Hurry Up and Wait, Restaurant Test', 'main', 'newer_vgm', 136),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves -> 88-Farmer', '88-Farmer Combo', NULL, NULL, 'Trying Tryouts (Air on the G)', 'main', 'newer_vgm', 137),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves -> 90-Madrid', '90-Madrid Vinyl Drums', NULL, NULL, 'Onward Through the Dark', 'main', 'newer_vgm', 138),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves -> 90-Stutter', '90-Stutter 16th', NULL, NULL, 'Trying Tryouts (Air on the G)', 'main', 'newer_vgm', 139),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves -> 97-Wax Wash', '97-Wax Wash HiHats Spring', NULL, NULL, 'Looting the Louvre, Hope''s Melody', 'main', 'newer_vgm', 140),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves -> 120-Notre Dame', '120-Notre Dame Echobeat', NULL, NULL, 'Through the Hanging Gardens', 'main', 'newer_vgm', 141),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves -> 135-Tough Guy', '135-Tough Guy', NULL, NULL, 'Hurry Up and Wait', 'main', 'newer_vgm', 142),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves -> 140-Atomic ZOO', '140-Atomic ZOO Big Frog', NULL, NULL, 'Vergier vs. The Chevaliers', 'main', 'newer_vgm', 143),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves -> 143-Mind Bender', '143-Mind Bender  Combo 1', NULL, NULL, 'Battle Diabolique, Napoleon''s Hideout', 'main', 'newer_vgm', 144),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves -> 160-Find The Exit', '160-Find The Exit Combo', NULL, NULL, 'Hope''s Melody', 'main', 'newer_vgm', 145),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves -> 174-World Hunt', '174-World Hunt  Combo Big', NULL, NULL, 'Flight from the Gardens', 'main', 'newer_vgm', 146),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves -> 174-World Hunt', '174-World Hunt Big Boom', 'Needs to be confirmed', NULL, 'Phantom Notes', 'main', 'newer_vgm', 147),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'Sound Menus -> Cymbals', 'MENU - Crashes Hi-Fi', 'C#4', NULL, 'Gone with the Wind, To the Manor Borne, Vergier vs. The Chevaliers', 'main', 'newer_vgm', 148),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'Sound Menus -> Retro Hits', 'MENU - Big Band Vintage Hits', 'F3, G5', NULL, 'Throwdown with Alfred, Phantom From the Opera, Vergier vs. The Chevaliers', 'main', 'newer_vgm', 149),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Trilian' COLLATE NOCASE),
   'Bass Instruments', 'Clean Fender - Full Range All', NULL, NULL, 'Raphael''s Daily Life, Restaurant Test', 'main', 'newer_vgm', 150),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Trilian' COLLATE NOCASE),
   'Bass Instruments', 'Trilian Ac 1 - Full Range All', NULL, NULL, '-Used throughout the soundtrack-', 'main', 'newer_vgm', 151),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Trilian' COLLATE NOCASE),
   'Bass Instruments', 'Trilogy Acoustic - Full Range', NULL, NULL, 'Looting the Louvre', 'main', 'newer_vgm', 152);

-- G1 continued: Ueberschall / UVI / Vengeance / Zero-G (positions 153-173) + stuff_to_find (174-195)
INSERT INTO usages
  (game_id, product_id, path_bank, preset, notes, raw_source, examples, category, source_family, position)
VALUES
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Ueberschall' COLLATE NOCASE AND p.name = 'Brazil Electro' COLLATE NOCASE),
   'HORNSAMPLES', 'big hit 3-#652', 'Pitched up 300 cents', NULL, 'Looting the Louvre', 'main', 'newer_vgm', 153),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Ueberschall' COLLATE NOCASE AND p.name = 'Brazil Electro' COLLATE NOCASE),
   'HORNSAMPLES', 'final brasil-#675', 'Pitched up 200 cents', NULL, 'Looting the Louvre', 'main', 'newer_vgm', 154),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Ueberschall' COLLATE NOCASE AND p.name = 'Brazil Electro' COLLATE NOCASE),
   'HORNSAMPLES', 'flute 1-#677', NULL, NULL, 'Vergier vs. The Chevaliers', 'main', 'newer_vgm', 155),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Ueberschall' COLLATE NOCASE AND p.name = 'Easy Listening' COLLATE NOCASE),
   'Track 28 -> TS 0:10', 'Echo-Effect', NULL, NULL, 'Vergier vs. The Chevaliers', 'main', 'newer_vgm', 156),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Ueberschall' COLLATE NOCASE AND p.name = 'Easy Listening' COLLATE NOCASE),
   'Track 29 -> TS 0:34', 'Trumpet Electric', NULL, NULL, 'Onward Through the Dark', 'main', 'newer_vgm', 157),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Ueberschall' COLLATE NOCASE AND p.name = 'Easy Listening' COLLATE NOCASE),
   'Track 32 -> TS 0:24', 'Hit', NULL, NULL, 'Onward Through the Dark', 'main', 'newer_vgm', 158),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Ueberschall' COLLATE NOCASE AND p.name = 'Easy Listening' COLLATE NOCASE),
   'Track 33 -> TS 0:00', 'Hit Sound Effect', NULL, NULL, 'Through the Hanging Gardens', 'main', 'newer_vgm', 159),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Ueberschall' COLLATE NOCASE AND p.name = 'Easy Listening' COLLATE NOCASE),
   'Track 33 -> TS 0:30', 'Hit Sound Effect', NULL, NULL, 'Through the Hanging Gardens', 'main', 'newer_vgm', 160),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Ueberschall' COLLATE NOCASE AND p.name = 'Easy Listening' COLLATE NOCASE),
   'Track 56 -> TS 0:22', 'Drumloop 107,2 Bass, Bassline', NULL, NULL, 'Looting the Louvre', 'main', 'newer_vgm', 161),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Ueberschall' COLLATE NOCASE AND p.name = 'Easy Listening' COLLATE NOCASE),
   'Track 58 -> TS 0:10', 'Drumloop 139,7', NULL, NULL, 'Looting the Louvre', 'main', 'newer_vgm', 162),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Ueberschall' COLLATE NOCASE AND p.name = 'Easy Listening' COLLATE NOCASE),
   'Track 78 -> TS 0:04', 'Male Vocals', NULL, NULL, 'Hurry Up and Wait, IT''S DOG SHOW TIME, Restaurant Test', 'main', 'newer_vgm', 163),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'UVI' COLLATE NOCASE AND p.name = 'PlugSound Pro (01-Keyboards)' COLLATE NOCASE),
   '01-Acoustic Pianos -> 01-Grand Piano', 'Acoustic Grand Piano', NULL, NULL, 'Breaking In', 'main', 'newer_vgm', 164),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'UVI' COLLATE NOCASE AND p.name = 'PlugSound Pro (02-Fretted)' COLLATE NOCASE),
   '03-Acoustic Bass -> 01-Jazzistic Bass', 'Jazz Double Bass', NULL, NULL, 'Breaking In', 'main', 'newer_vgm', 165),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'UVI' COLLATE NOCASE AND p.name = 'Plugsound Pro (03-Drums and Percs)' COLLATE NOCASE),
   '01-Acoustic Drums -> Jazz Kits', 'Complete Jazz Kit', NULL, NULL, 'Breaking In', 'main', 'newer_vgm', 166),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'UVI' COLLATE NOCASE AND p.name = 'PlugSound Pro (06-Orchestral)' COLLATE NOCASE),
   'Strings Ensemble', 'All Strings trem', 'Increase attack', NULL, 'Breaking In', 'main', 'newer_vgm', 167),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'UVI' COLLATE NOCASE AND p.name = 'PlugSound Pro (06-Orchestral)' COLLATE NOCASE),
   'Strings Ensemble', 'All Strings sus', NULL, NULL, 'Breaking In', 'main', 'newer_vgm', 168),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Vengeance Sound' COLLATE NOCASE AND p.name = 'Vengeance Essential House Vol. 2' COLLATE NOCASE),
   'VEH2 Cymbals -> VEH2 Reverse Crash', 'VEH2 Reverse Crash - 1', NULL, NULL, 'Battle Diabolique', 'main', 'newer_vgm', 169),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Brutal Beats' COLLATE NOCASE),
   '067 Not Half', 'NH-Comp 2', NULL, NULL, 'Throwdown with Napoleon', 'main', 'newer_vgm', 170),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Cuckooland Vol. 3 Asylum' COLLATE NOCASE),
   'Track 24 - Non Drum Grooves -> Sample 1', 'Squirty Bass 118.5 bpm', NULL, NULL, 'SHOW TIME', 'main', 'newer_vgm', 171),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'Cuckooland Vol. 3 Asylum' COLLATE NOCASE),
   'Track 31 - Strange Bits -> Sample 2', 'Spinning Jungle Wheels', NULL, NULL, 'SHOW TIME', 'main', 'newer_vgm', 172),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Zero-G' COLLATE NOCASE AND p.name = 'EZ Rollers Drum & Bass Producer Pack' COLLATE NOCASE),
   'Breaks -> Classics', 'A-Men 160bpm', NULL, NULL, 'Battle at the Eiffel Tower', 'main', 'newer_vgm', 173),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Choirs' COLLATE NOCASE),
   NULL, NULL, 'Choir', NULL, 'Decisive Battle! Emperor Napoleon', 'stuff_to_find', 'newer_vgm', 174),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   NULL, NULL, 'Strings', NULL, 'Ralph''s Appearance', 'stuff_to_find', 'newer_vgm', 175),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Omnisphere' COLLATE NOCASE),
   NULL, NULL, 'Vocal Planet Voices', NULL, 'SHOW TIME, Sound Trick Clear, Rhythm Kitchen, IT''S DOG SHOW TIME', 'stuff_to_find', 'newer_vgm', 176),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, NULL, 'Drum Fill', '? (Song Sample)', 'Looting the Louvre', 'stuff_to_find', 'newer_vgm', 177),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, NULL, 'Drum Loop', '? (Song Sample)', 'Bone Appétit', 'stuff_to_find', 'newer_vgm', 178),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, NULL, 'Long Drum Fill', '? (Song Sample)', 'Bone Appétit', 'stuff_to_find', 'newer_vgm', 179),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, NULL, 'Brass Phrases (Latin)', '? (Song Sample)', 'Bone Appétit', 'stuff_to_find', 'newer_vgm', 180),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, NULL, 'Drum Fill', '? (Song Sample)', 'Rhythm Kitchen', 'stuff_to_find', 'newer_vgm', 181),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, NULL, 'Brass Hits & Phrases (Stereo)', '? (Song Sample)', 'Through the Hanging Gardens', 'stuff_to_find', 'newer_vgm', 182),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, NULL, 'Drum Fill', '? (Song Sample)', 'Family Ties', 'stuff_to_find', 'newer_vgm', 183),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, NULL, 'Drum Fill', '? (Song Sample)', 'IT''S DOG SHOW TIME', 'stuff_to_find', 'newer_vgm', 184),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, NULL, 'Intro FX Hits', '? (Sample Instrument or Loop Library)', 'SHOW TIME', 'stuff_to_find', 'newer_vgm', 185),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, NULL, 'Rhodes', '? (Sample Instrument Library)', 'SHOW TIME', 'stuff_to_find', 'newer_vgm', 186),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, NULL, 'Synth Stabs', '? (Sample Instrument Library)', 'SHOW TIME', 'stuff_to_find', 'newer_vgm', 187),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, NULL, 'Piano', '? (Sample Instrument Library)', 'Looting the Louvre', 'stuff_to_find', 'newer_vgm', 188),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, NULL, 'Strings', '? (Sample Instrument Library)', 'Looting the Louvre', 'stuff_to_find', 'newer_vgm', 189),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, NULL, 'Harpsichord', '? (Sample Instrument Library)', 'Onward Through the Dark', 'stuff_to_find', 'newer_vgm', 190),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, NULL, 'Cymbal Loop & Water Droplet Loop', '? (Sample Loop Library)', 'Phantom From the Opera', 'stuff_to_find', 'newer_vgm', 191),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, NULL, 'Clock Ticking', '? (Sample Loop Library)', 'Time Limit', 'stuff_to_find', 'newer_vgm', 192),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, NULL, 'Drums', '? (Sample Loop Library)', 'Vergier vs. The Chevaliers', 'stuff_to_find', 'newer_vgm', 193),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, NULL, 'Synth Bass', '? (Sample Instrument Library)', 'Vergier vs. The Chevaliers', 'stuff_to_find', 'newer_vgm', 194),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Emperor''s Treasure'),
   NULL, NULL, NULL, 'Saxophone', '? (Sample Instrument Library)', 'IT''S DOG SHOW TIME', 'stuff_to_find', 'newer_vgm', 195);

-- G2: Rhythm Thief & the Paris Caper — 14 Sample + 31 equipment + 10 stuff = 55 rows
INSERT INTO usages
  (game_id, product_id, path_bank, preset, notes, raw_source, examples, category, source_family, position)
VALUES
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Paris Caper'),
   NULL, NULL, 'Timestamp 0:02', 'String Phrase & Piano Glissando', 'Sample: Hi-Fi Set - Yuzorani Hang-Glider', 'Elegant Infiltration', 'main', 'newer_vgm', 1),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Paris Caper'),
   NULL, NULL, 'Timestamp 0:03', 'Drum Loop', 'Sample: Jack Parnell & His Orchestra - Viramundo', 'Cookin'' on Gas', 'main', 'newer_vgm', 2),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Paris Caper'),
   NULL, NULL, 'Timestamp 0:03', 'Brass Shake', 'Sample: Joseph Gershenson - Big Spender', 'Elegant Infiltration', 'main', 'newer_vgm', 3),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Paris Caper'),
   NULL, NULL, 'Timestamp 0:00', 'Guiro', 'Sample: Keith Mansfield - The Mexican D.J.', 'Tango de Fondue', 'main', 'newer_vgm', 4),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Paris Caper'),
   NULL, NULL, 'Timestamp 0:07', 'String Fall', 'Sample: Manfred Minnich Strings - With Following Winds', 'Elegant Infiltration', 'main', 'newer_vgm', 5),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Paris Caper'),
   NULL, NULL, 'Timestamp 2:26', 'Brass Hit', 'Sample: Michel Fugain - Monsieur Bernard', 'Elegant Infiltration', 'main', 'newer_vgm', 6),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Paris Caper'),
   NULL, NULL, 'Timestamp 0:00', 'Tapping Loop', 'Sample: Neal Hefti - Show Time', 'Elegant Infiltration', 'main', 'newer_vgm', 7),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Paris Caper'),
   NULL, NULL, 'Timestamp 0:56', 'Brass Hit', 'Sample: Ray Conniff - Love (Can Make You Happy)', 'Elegant Infiltration', 'main', 'newer_vgm', 8),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Paris Caper'),
   NULL, NULL, 'Timestamp 0:00, 0:05', 'Brass Hits', 'Sample: René Touzet - Theme From The Brothers Grimm', 'Elegant Infiltration', 'main', 'newer_vgm', 9),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Paris Caper'),
   NULL, NULL, 'Timestamp 0:00', 'Conga Loop', 'Sample: Sabu Martinez - My Son Johnny And Me', 'Cookin'' on Gas', 'main', 'newer_vgm', 10),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Paris Caper'),
   NULL, NULL, 'Timestamp 0:43', 'Brass Hit', 'Sample: The Fat Albert Orchestra - Cosbyianna', 'Elegant Infiltration', 'main', 'newer_vgm', 11),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Paris Caper'),
   NULL, NULL, 'Timestamp 2:22', 'Drums', 'Sample: The Jimi Entley Sound - Apache', 'Tango de Fondue', 'main', 'newer_vgm', 12),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Paris Caper'),
   NULL, NULL, 'Timestamp 0:00', 'Drum Loop', 'Sample: The Monkees - Mary, Mary', 'Phantom Fondue - Remix', 'main', 'newer_vgm', 13),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Paris Caper'),
   NULL, NULL, 'Timestamp 0:00', 'Claps', 'Sample: The Routers - Let''s Go (Pony)', 'Phantom Fondue - Remix', 'main', 'newer_vgm', 14),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Paris Caper'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG & Hit Music' COLLATE NOCASE AND p.name = 'Norman Cook - Skip to my Loops' COLLATE NOCASE),
   'Track 32 - More Conga Loops -> TS 0:08', '3 - Kelly''s Conga - 124 BPM', NULL, NULL, 'Twilight of Chevaliers', 'main', 'newer_vgm', 15),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Paris Caper'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'AMG & Hit Music' COLLATE NOCASE AND p.name = 'Norman Cook - Skip to my Loops' COLLATE NOCASE),
   'Track 71 - Vox -> TS 0:19', 'B-B-B-Brupa', NULL, NULL, 'The Last Dance Remix', 'main', 'newer_vgm', 16),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Paris Caper'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 3 -> VOX_D_I', 'HEY', NULL, NULL, 'Bite the Bobbies'' Bums! ', 'main', 'newer_vgm', 17),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Paris Caper'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 3 -> VOX_J_R', 'PUH', NULL, NULL, 'Bite the Bobbies'' Bums! ', 'main', 'newer_vgm', 18),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Paris Caper'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Best Service' COLLATE NOCASE AND p.name = 'Sound Cube' COLLATE NOCASE),
   'CD 3 -> VOX_S_Z', 'SHAKE', NULL, NULL, 'Bite the Bobbies'' Bums! ', 'main', 'newer_vgm', 19),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Paris Caper'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Big Fish Audio' COLLATE NOCASE AND p.name = 'Acid Jazz City' COLLATE NOCASE),
   '02 120 D', '02 drums 02', NULL, NULL, 'Elegant Infiltration', 'main', 'newer_vgm', 20),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Paris Caper'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Big Fish Audio' COLLATE NOCASE AND p.name = 'Acid Jazz City' COLLATE NOCASE),
   '12 120 A', '12 drums 09', NULL, NULL, 'Elegant Infiltration', 'main', 'newer_vgm', 21),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Paris Caper'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'IK Multimedia' COLLATE NOCASE AND p.name = 'SampleTron' COLLATE NOCASE),
   'Chamberlin Music Masters', 'M4 Pizz CH', NULL, NULL, 'Bite the Bobbies'' Bums! ', 'main', 'newer_vgm', 22),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Paris Caper'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'MOTU' COLLATE NOCASE AND p.name = 'Universal Loops & Instruments' COLLATE NOCASE),
   '01 Piano & co -> Mallets', 'Vibraphone 1 or Vibraphone 2', NULL, NULL, 'Sneak n'' Peak, Mini Game 1', 'main', 'newer_vgm', 23),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Paris Caper'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Native Instruments' COLLATE NOCASE AND p.name = 'Kontakt Factory Library' COLLATE NOCASE),
   'Orchestral -> 1 - VSL Strings', 'Violin Solo', NULL, NULL, 'On Dangerous Ground', 'main', 'newer_vgm', 24),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Paris Caper'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sound Ideas' COLLATE NOCASE AND p.name = 'Hollywood Series 4000' COLLATE NOCASE),
   '4001-27-06', 'CARTOON, GONG', 'LARGE, CHINESE GONG, SOFT MALLET', NULL, 'Friend vs. Faux', 'main', 'newer_vgm', 25),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Paris Caper'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Bonus Spectrasonics S.A.G.E. Xpander' COLLATE NOCASE),
   'Bizarre Guitar', '081-Vermin', NULL, NULL, 'Showdown by Moonlight', 'main', 'newer_vgm', 26),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Paris Caper'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Bonus Spectrasonics S.A.G.E. Xpander' COLLATE NOCASE),
   'Bizarre Guitar', '090-Roboshriek', NULL, NULL, 'Harder Than Hard Boiled', 'main', 'newer_vgm', 27),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Paris Caper'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Bonus Spectrasonics S.A.G.E. Xpander' COLLATE NOCASE),
   'Distorted Reality 060-089', '85-Big Bone', NULL, NULL, 'Showdown by Moonlight', 'main', 'newer_vgm', 28),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Paris Caper'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Bonus Spectrasonics S.A.G.E. Xpander' COLLATE NOCASE),
   'Distorted Reality 060-089', '85-Dem Bones', NULL, NULL, 'Showdown by Moonlight', 'main', 'newer_vgm', 29),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Paris Caper'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Burning Grooves S.A.G.E. Xpander' COLLATE NOCASE),
   '135-James Burn', '135-James Burn', NULL, NULL, 'Sneak n'' Peak', 'main', 'newer_vgm', 30),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Paris Caper'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Burning Grooves S.A.G.E. Xpander' COLLATE NOCASE),
   '151-Street Dance', '151-Street Dance 1', NULL, NULL, 'Le Theme Diabolique', 'main', 'newer_vgm', 31),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Paris Caper'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'Classic Stylus -> 67-Crenshaw', '67-Crenshaw a', NULL, NULL, 'Arabian Knights', 'main', 'newer_vgm', 32),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Paris Caper'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'Classic Stylus -> Congas', '65-Congas 1', NULL, NULL, 'Mini Game 1', 'main', 'newer_vgm', 33),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Paris Caper'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves -> 68-Tower Zero', '68-Tower Zero Hi Hats', NULL, NULL, 'Sneak n'' Peak', 'main', 'newer_vgm', 34),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Paris Caper'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves -> 125-Emperor', '125-Emperor Combo 2', NULL, NULL, 'Showdown by Moonlight', 'main', 'newer_vgm', 35),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Paris Caper'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves -> 140-Atomic ZOO', '140-Atomic ZOO Break 2', NULL, NULL, 'Bite the Bobbies'' Bums! ', 'main', 'newer_vgm', 36),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Paris Caper'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves -> 160-The Call', '160-The Call  Combo', NULL, NULL, 'Bite the Bobbies'' Bums!, Le Theme Diabolique', 'main', 'newer_vgm', 37),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Paris Caper'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'RMX Grooves -> 174-World Hunt', '174-World Hunt  Combo Dry', NULL, NULL, 'Showdown by Moonlight', 'main', 'newer_vgm', 38),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Paris Caper'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Stylus RMX' COLLATE NOCASE),
   'Sound Menus -> Retro Hits', 'MENU - Big Band Vintage Hits', 'coarse +4', NULL, 'Main Menu', 'main', 'newer_vgm', 39),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Paris Caper'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Trilian' COLLATE NOCASE),
   'Synth Bass', 'Blown Metasonix Tubes', NULL, NULL, 'Showdown by Moonlight', 'main', 'newer_vgm', 40),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Paris Caper'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sounds Good & Steinberg' COLLATE NOCASE AND p.name = 'Hip Hop Beats & Treats' COLLATE NOCASE),
   'CD 1 -> 80_SCRATCH', '080AH', NULL, NULL, 'Tango de Fondue', 'main', 'newer_vgm', 41),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Paris Caper'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Sounds Good & Steinberg' COLLATE NOCASE AND p.name = 'Hip Hop Beats & Treats' COLLATE NOCASE),
   'CD 1 -> 80_SCRATCH', '080SCR03', NULL, NULL, 'Tango de Fondue', 'main', 'newer_vgm', 42),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Paris Caper'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Ueberschall' COLLATE NOCASE AND p.name = 'Easy Listening' COLLATE NOCASE),
   'Track 10 -> TS 0:09', 'Brass Trumpet', NULL, NULL, 'Sneak n'' Peak', 'main', 'newer_vgm', 43),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Paris Caper'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'YMCK' COLLATE NOCASE AND p.name = 'Magical 8bit Plug' COLLATE NOCASE),
   'OscKind', '25%Pulse', NULL, NULL, 'Ping Pong Rally', 'main', 'newer_vgm', 44),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Paris Caper'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'YMCK' COLLATE NOCASE AND p.name = 'Magical 8bit Plug' COLLATE NOCASE),
   'OscKind', 'square', NULL, NULL, 'Ping Pong Rally', 'main', 'newer_vgm', 45),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Paris Caper'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'EastWest' COLLATE NOCASE AND p.name = 'Symphonic Orchestra' COLLATE NOCASE),
   NULL, NULL, 'Strings', NULL, 'Cheering Marie - Remix', 'stuff_to_find', 'newer_vgm', 46),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Paris Caper'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Omnisphere' COLLATE NOCASE),
   NULL, NULL, 'Voices', NULL, 'Bite the Bobbies'' Bums!, Sneak n'' Peak, Mini Game 1, Mini Game Fail, Mini Game 2', 'stuff_to_find', 'newer_vgm', 47),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Paris Caper'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Trilian' COLLATE NOCASE),
   NULL, NULL, 'Electric Bass', NULL, 'Sneak n'' Peak', 'stuff_to_find', 'newer_vgm', 48),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Paris Caper'),
   (SELECT p.id FROM products p JOIN manufacturers m ON m.id = p.manufacturer_id WHERE m.name = 'Spectrasonics' COLLATE NOCASE AND p.name = 'Trilian' COLLATE NOCASE),
   NULL, NULL, 'Rock Bass', NULL, 'Friend vs. Faux', 'stuff_to_find', 'newer_vgm', 49),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Paris Caper'),
   NULL, NULL, NULL, 'Piano Hit', '? (Song Sample)', 'Elegant Infiltration', 'stuff_to_find', 'newer_vgm', 50),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Paris Caper'),
   NULL, NULL, NULL, 'Guitar & Brass Hit', '? (Song Sample)', 'Elegant Infiltration', 'stuff_to_find', 'newer_vgm', 51),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Paris Caper'),
   NULL, NULL, NULL, 'Brass Hit (Timestamp 0:23)', '? (Song Sample)', 'Elegant Infiltration', 'stuff_to_find', 'newer_vgm', 52),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Paris Caper'),
   NULL, NULL, NULL, 'Acoustic Bass', '? (Sample Instrument Library)', 'Elegant Infiltration', 'stuff_to_find', 'newer_vgm', 53),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Paris Caper'),
   NULL, NULL, NULL, 'Piano', '? (Sample Instrument Library)', 'Elegant Infiltration', 'stuff_to_find', 'newer_vgm', 54),
  ((SELECT id FROM games WHERE title = 'Rhythm Thief & the Paris Caper'),
   NULL, NULL, NULL, 'String Hits / FX', '? (Sample Loop Library)', 'Elegant Infiltration', 'stuff_to_find', 'newer_vgm', 55);
